### ISSUE TITLE
Absent/different data after switching from Fusioninventory to GLPI-Agent

### ISSUE THREAD

**Issue by corymar** [glpi-project/glpi-agent#101]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Hi!

Dicovered that some computer Info disappeared from GLPI after switching to GLPI-Agent
Made xml files comparison from agents

GLPI software: GLPI 9.5.6 + Fusioninventory 9.5+3.0
Screenshot comparison: Left - FI 2.6, Right - GA 1.2

Some data is now absent in inventory file
OS info absent:

![изображение](https://user-images.githubusercontent.com/60350203/164674902-722e9374-f99a-4c93-8510-27b86cd81e98.png)

User profile installed applications now absent:

![изображение](https://user-images.githubusercontent.com/60350203/164675991-48105ba2-3fa5-4175-bcf8-4dde63872528.png)

There are now differences:

![изображение](https://user-images.githubusercontent.com/60350203/164675764-e01dfec6-429a-4873-881e-d2138cca8c01.png)

Now software names are Non-localized:

![изображение](https://user-images.githubusercontent.com/60350203/164676210-91810407-2474-45d9-abff-03e348d0dc7e.png)

### To reproduce

1. Switch from Fusioninventory 2.6 to GLPI-Agent 1.2 on x64 Windows 10 21H2 Home Single Language
2. Discover that OS Info disappeared from Computer Info in GLPI
3. Compare xml files to find the reason for that

### Expected behavior

Hope that GA will provide same or more information for PC than Fusioninventory but not less

### Operating system

Windows

### GLPI Agent version

1.2

### GLPI version

9.5.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

9.5+3.0

**Comment by g-bougard** [comment]
Hi @corymar 

encoding issue was indeed an issue in FusionInventory agent. GLPI Agent is then more reliable between languages. I can understand you prefer to see localized name, but this was really pain to handle correctly.

About the "Comet Lake" put in Controllers name, that's weird, but this is maybe related to pci.ids update. Are you really concern by such an issue ?

About the "missing" entries, as I see in your old XML, the software seems to be installed in a user profiles... Maybe you just forgot to install GLPI Agent with "scan-profiles" option enabled ?

**Comment by corymar** [comment]
Hi, @g-bougard 

Thank you for clarifying

Comet Lake in controller name isn't really an issue since TYPE remains the same and we can identify it in Device manager by that string.

"Missing" entries fixed by scan-profiles, thank you
