### ISSUE TITLE
Netinventory  with SNMPv3 support is unavailable (Required module Digest/SHA1.pm not found)

### ISSUE THREAD

**Issue by rbrannath** [glpi-project/glpi-agent#103]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

GLPI-Serverside: v.10.0.0

GLPI-Agent is installed on Windows (64x)

While testing out the agent to perform netinventory from my laptop, I receive the following error in my command line:
_**SNMPv3 support is unavailable (Required module Digest/SHA1.pm not found)**_

This was my command:
```
./glpi-netinventory --host 10.10.1.1
 --credentials version:3,username:glpi,authprotocol:sha,authpassword:s3cr3t1! --debug
```

Tested with GLPI-Agent v1.1, v.1.2 and even v.1.3. Every time the same result.

This is the whole output:
```
PS C:\Program Files\GLPI-Agent> ./glpi-netinventory --host 10.10.1.1 --credentials version:3,username:glpi,authprotocol:sha,authpassword:s3cr3t1! --debug
[debug] Logger backend Stderr initialized
[debug] Current run expiration timeout: 1.0 hour
[debug] creating 1 worker threads
[debug] [thread 1] creation
[debug] [thread 1] #1, scanning 0: 10.10.1.1
[error] [thread 1] #1, [thread 1] SNMP communication error: SNMPv3 support is unavailable (Required module Digest/SHA1.pm not found)
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <ERROR>
        <ID>0</ID>
        <MESSAGE>SNMP communication error: SNMPv3 support is unavailable (Required module Digest/SHA1.pm not found)</MESSAGE>
      </ERROR>
    </DEVICE>
    <MODULEVERSION>5.1</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>SNMPQUERY</QUERY>
</REQUEST>
[debug] [thread 1] termination
[debug] All netinventory threads terminated
```

### To reproduce

1. Open command line and type the following:
```
./glpi-netinventory --host insert.your.ip.address
 --credentials version:3,username:glpi,authprotocol:sha,authpassword:s3cr3t1! --debug
```

### Expected behavior

Netinventory should run

### Operating system

Windows

### GLPI Agent version

1.2, 1.1, Nightly build (git version in additional context below)

### GLPI version

Not applicable

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

**Comment by rbrannath** [comment]
FYI:
glpi-net**discovery** is working with SNMPv3
Tested SNMP with an SMTP tester tool. Host is configured correctly and answers to SNMP-Requests

**Comment by g-bougard** [comment]
Hi @rbrannath 

thank you for your report.

This is my fault, I tried to cleanup the packaging from unused modules but I forgot that Digest modules was necessary for SNMPv3 authentication.

Next nightly should fix your issue. Can you validate ?

**Comment by rbrannath** [comment]
Hi @g-bougard,
you're welcome. I will look at it tomorrow

Best regards

**Comment by rbrannath** [comment]
@g-bougard 
glpi-netinventory with SNMPv3 works now

Thank you very much!
