### ISSUE TITLE
Glpi-agent can't connect to server : [http client] internal response: 500 Can't connect to glpi10:443 (Bad file descriptor)

### ISSUE THREAD

**Issue by waaalex** [glpi-project/glpi-agent#105]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Is your help request related to a problem?

I have migrated glpi 9.5 to 10 and have an issue with glpi-agent.
Here is the error

```
[Thu Apr 28 14:07:43 2022][info] target server0: next run: Thu Apr 28 14:11:43 2022 - https://glpi10/glpi/plugins/glpiinventory
[Thu Apr 28 14:07:44 2022][info] GLPI Agent memory usage: WSS=3313664 PFU=126713856
[Thu Apr 28 14:11:43 2022][info] target server0: server https://glpi10/glpi/plugins/glpiinventory
[Thu Apr 28 14:11:44 2022][info] sending prolog request to server0
[Thu Apr 28 14:11:44 2022][error] [http client] internal response: 500 Can't connect to glpi10:443 (Bad file descriptor)
[Thu Apr 28 14:11:44 2022][error] No answer from server at https://glpi10/glpi/plugins/glpiinventory
[Thu Apr 28 14:11:44 2022][info] target server0: next run: Thu Apr 28 14:19:44 2022 - https://glpi10/glpi/plugins/glpiinventory
[Thu Apr 28 14:11:45 2022][info] GLPI Agent memory usage: WSS=3272704 PFU=126681088
```

### Expected behavior

Agent should conect to server.

### Actions you've considered

I have modified address in the entity, and changed path to agent files in plugin configuration.

**Comment by waaalex** [comment]
seems to be an SSL issue.
Server : Alma linux 8.5
Server version: Apache/2.4.37 (AlmaLinux)
OpenSSL 1.1.1k  FIPS 25 Mar 2021

There is no key exchange, i have a fatal error, description : unknown CA.
I ve put root certificate (corporate) on the server, and ldap authentication is OK.

Maybe TLSv1.3? because on old fusion inventory agent, it was TLSv1.2.
Note that i allow TLSV1.3 and TLSv1.2
```
<VirtualHost glpi10:443>
 ServerName glpi10
 DocumentRoot /var/www/html/glpi
 SSLEngine on
 ErrorLog logs/ssl_error_log
 TransferLog logs/ssl_access_log
 LogLevel warn
 SSLProtocol -all +TLSV1.2 +TLSv1.3
 SSLCipherSuite HIGH:!aNULL:!MD5:!3DES
 SSLCertificateFile /etc/pki/tls/certs/glpi10.crt
 SSLCertificateKeyFile /etc/pki/tls/private/glpi10.key
```

**Comment by waaalex** [comment]
My client is Windows.
Ok, i have put ssl-no-check at 1 in registry and it works.
glpi server certificate is valid, is there a trick to make ssl check to work?

**Comment by g-bougard** [comment]
Hi @waaalex 
for SSL support, you may set debug to 2 in registry to see SSL debugging in agent log. In your case, you should obtain the right explanation for the problem.

My guess is the hostname `glpi10` is not signed by a public authority so you're probably using a self-signed SSL certificate on server side. This explains the "Unknown CA" error. Agent actually won't look for certificates installed in system key store. You need to export your SSL server certificate as PEM file and use `ca-cert-file` option to point to the file. See [ca-cert-file configuration](https://glpi-agent.readthedocs.io/en/latest/configuration.html#ca-cert-file) or for `CA_CERT_FILE=filename` in [windows command line installer options](https://glpi-agent.readthedocs.io/en/latest/installation/windows-command-line.html#command-line-parameters).

As requested in #33, maybe being able to check the system key store in windows could also be a good enhancement for the agent on windows.

**Comment by waaalex** [comment]
Ok that's it.
My certificate is not signed by a public authority but by my enterprise authority.
Will agent look keystore certificates in future version?
Thank you.

**Comment by g-bougard** [comment]
As #33, this would be surely a nice enhancement feature.
Can you open a new issue to request the feature so you'll be informed when I find time to investigate and you would be able to validate the solution ?
Then I'm closing this issue.

**Comment by g-bougard** [comment]
Hi @waaalex 

can you open a Q&A discussion to see if you're current problem with v1.7 is a configuration problem or not ?

But before, first check if you have enabled one of the `ca-cert-file`, `ca-cert-dir` or `ssl-fingerprint` option. From v1.7, if one of these options is used, we consider it must work and so we don't export windows keystore. If you want to use keystore, don't set any of these options.

**Comment by ra1qcw** [comment]
I have the same problem with agent 1.7.1 on my test computer (after upgrade from 1.6.1). Agent 1.6.1 (on all other computers) work normally.
All agents using ssl-fingerprint option.
All versions before 1.7.1 works ok.
Will have to back to 1.6.1 version  (

**Comment by g-bougard** [comment]
Hi @ra1qcw 

please open another issue or Q&A discussion so we can investigate your case. You won't help yourself and the community hi-jacking an old and closed issue.

**Comment by BritoG26481** [comment]
Buenas noches a mi me envia este error lo tengo alojado en HostGator

![glpi2](https://github.com/glpi-project/glpi-agent/assets/60078786/78b13506-9f87-409e-83ee-57c75fdddfab)
