### ISSUE TITLE
FusionInventory to GLPI Agent

### ISSUE THREAD

**Issue by eglyn** [glpi-project/glpi-agent#109]
Hello, 

We are on GLPI 9.5, and I have a test server on GLPI 10. I installed GLPIInventory in this server to replace old FusionInventory.

In this test server, I imported the database of 9.5, and do some tests with a workstation that was already in the database.

I disabled fusioninventory, installed glpi-agent, and put a server config to the test server.

On the server GLPI 10 I see the computer with Fusioninventory agent, but nothing happen when I force update.
However, when I go in the GLPI Inventory tab, I see 2 agents with the same computer name. the old one with fusion agent, and the new one with glpi-agent.

So, why the glpi-agent does not create the computer, and/or why the computer is not update with the new agent to replace fusion agent ? 

I try to stop glpi-agent, and start fusioninventory agent on the new server URL, and it works ^^, , but I don't want to stay on an unsupported agent.

Any idea to migrate fusion --> glpi-agent correctly ? 

thx :)

**Comment by g-bougard** [comment]
Hi @eglyn 

firstly, you'll always see a new agent as they are different clients. So after the migration, fusion agents from your agent list will still have to be removed if you don't want to see them anymore.

Secondly, you must check your glpi-agent log to look for any error. Have you check this page: https://glpi-agent.readthedocs.io/en/latest/configuration.html#available-parameters ? Maybe you're just using a wrong server url, and the log would still have tell you ;-)

Also you're asking for idea about migration but without telling which is the context ? Are your agent running on windows, linux, macosx ?

**Comment by eglyn** [comment]
Ok, so I need to remove all fusion agent ? But I will lose all configuration ? user associate to the workstation for example.

I don't have any error, the glpi-agent from the workstation is present in the glpi inventory menu, but not in the computer tab. I have only the old computer with fusion inventory.

However in agent log I have a lot of time out: 
```
[Mon May  2 15:10:11 2022][info] sending contact request to server0
[Mon May  2 15:10:11 2022][info] sending prolog request to server0
[Mon May  2 15:10:11 2022][info] running task Inventory
[Mon May  2 15:10:11 2022][info] New inventory from ****************-2022-04-29-08-27-56 for server0 (tag=*****)
[Mon May  2 15:26:17 2022][info] Timeout reached on SELECT * FROM Win32_UserAccount WHERE Name='___VMware_Conv_SA___' AND Disabled='False' and Lockout='False' WMI query
[Mon May  2 15:28:52 2022][info] Timeout reached on SELECT * FROM Win32_UserAccount WHERE Name='*****-*' AND Disabled='False' and Lockout='False' WMI query
[Mon May  2 15:31:29 2022][info] Timeout reached on SELECT * FROM Win32_UserAccount WHERE Name='******' AND Disabled='False' and Lockout='False' WMI query
[Mon May  2 15:31:39 2022][info] Timeout reached on SELECT * FROM Win32_UserProfile WHERE SID='**************************************' WMI query
[Mon May  2 15:34:49 2022][info] Timeout reached on AntiVirusProduct class WMI objects
[Mon May  2 15:35:00 2022][info] Timeout reached on Win32_SystemEnclosure class WMI objects
[Mon May  2 15:41:09 2022][info] Timeout reached on Win32_SCSIController class WMI objects
[Mon May  2 15:44:08 2022][info] Timeout reached on Win32_VideoController class WMI objects
[Mon May  2 15:47:18 2022][info] Timeout reached on Win32_USBController class WMI objects
[Mon May  2 15:50:40 2022][info] Timeout reached on CIM_LogicalDevice class WMI objects
[Mon May  2 15:53:38 2022][info] Timeout reached on Win32_OperatingSystem class WMI objects
[Mon May  2 15:53:49 2022][info] Timeout reached on Win32_LogicalDisk class WMI objects
[Mon May  2 15:54:00 2022][info] Timeout reached on Win32_Volume class WMI objects
[Mon May  2 15:56:59 2022][info] Timeout reached on Win32_EncryptableVolume class WMI objects
[Mon May  2 15:59:58 2022][info] Timeout reached on Win32_Environment class WMI objects
[Mon May  2 16:02:57 2022][info] Timeout reached on Win32_NetworkAdapterConfiguration class WMI objects
[Mon May  2 16:03:08 2022][info] Timeout reached on MSFT_NetAdapter class WMI objects
[Mon May  2 16:06:07 2022][info] Timeout reached on Win32_NetworkAdapter class WMI objects
[Mon May  2 16:09:06 2022][info] Timeout reached on Win32_Keyboard class WMI objects
[Mon May  2 16:09:17 2022][info] Timeout reached on Win32_PointingDevice class WMI objects
```

Most of agents are on Windows 10, some on Debian.
And migration concern Debian 10 GLPI 9.5 -> Debian 11 GLPI10. I would like to stay on fusion, but I did not find a version compatible with glpi 10, and I find your fork ^^

**Comment by eglyn** [comment]
Ok, don't ask me how, but it works now... the fusioninventory agent has been replace in the computer by the glpi-agent, and inventory is up to date... I do nothing special, maybe I have to wait more :0

**Comment by g-bougard** [comment]
About `Timeout reached on ... WMI objects/query` you should probably set `backend-collect-timeout` to a greater value. The default is 300 for 5 minutes. Or maybe you have to check if WMI is consistent on your computer.
When installing, you may ask for an immediate inventory if you don't want to wait ;-)

**Comment by eglyn** [comment]
I reopen the topic because I have another issue ^^: 

With fusion, we use "tag" value to put the computer in the right entity, but with glpi-agent, even with the tag value, computer is in the main entity, not the child entity.
How put the computer in a specific entity at the setup ? 

thx :)

**Comment by g-bougard** [comment]
Hi @eglyn 

here you can obtain help regarding glpi-agent issues. But your new question concerns server-side support.
