### ISSUE TITLE
Error for GLPI-Injector

### ISSUE THREAD

**Issue by chris29B** [glpi-project/glpi-agent#111]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Professional support

I still have but want a public following to help the community

### Is your help request related to a problem?

Bonjour,

Je n'ai pas de souci de remonter d'agent ou l'execution de request type NetInventory ou ESX, ou NetDiscovery depuis un agent Windows ou UNIX.

Mon souci est dans la remonter vers la console GLPI, que ce soit un fichier type .ocs, xml ou json, j'ai toujours le meme souci `ERROR : Unexpected empty server response`

### Expected behavior

Exemple de commande :
`.\glpi-injector.bat -v -d C:\GLPI-injector\netdiscovery\ --url https://***********/front/inventory.php --debug`

```
GLPI-injector\netdiscovery\/134.246.155.1.xml...[9D62E53A] ERROR: Unexpected empty server response
```

`.\glpi-injector.bat -v -d C:\RIC\GLPI-injector\ --url https://*********/marketplace/glpiinventory/`

```
GLPI-injector\netdiscovery\/134.246.155.1.xml...[9D62E53A] ERROR: Unexpected empty server response
```

### Actions you've considered

J'ai tester un CURL de L'URL, aucune erreur.

J'ai tester la communication avec le serveur via :
 
`.\glpi-agent.bat --logger=stderr --task netinventory --debug --server=https://********/front/inventory.php`
```
[debug] Logger backend Stderr initialized
[debug] Logger backend File initialized
[debug] GLPI Agent (1.2-gitdd04d55d)
[debug] Configuration directory: C:/Program Files/GLPI-Agent/etc
[debug] Data directory: C:/Program Files/GLPI-Agent/share
[debug] Storage directory: C:\Program Files\GLPI-Agent\var
[debug] Lib directory: C:/Program Files/GLPI-Agent/perl/agent
[debug] [target server0] Next server contact planned for Tue May  3 14:05:16 2022
[debug] Available tasks:
[debug] - Collect: 2.7
[debug] - Deploy: 2.9
[debug] - ESX: 2.7
[debug] - Inventory: 1.10
[debug] - NetDiscovery: 5.0
[debug] - NetInventory: 5.0
[debug] - RemoteInventory: 1.0
[debug] target server0: server https://*******front/inventory.php
[debug] Planned tasks for server0: NetInventory
[debug] Provided by Teclib Edition
[debug] Installer built on Fri Feb  4 16:23:44 2022 UTC
[debug] Built with Strawberry Perl 5.34.0
[debug] Built on github actions windows image for glpi-project/glpi-agent repository
[debug] Running in foreground mode
[info] server0 is not ready yet, next server contact planned for Tue May  3 14:05:16 2022
```

**Comment by g-bougard** [comment]
Hi @chris29B 

you seem to use a very old nightly (built 3 months ago). Please first use latest official release.

For your injector issue, did you try with `--no-ssl-check` option ?

For the communication with server, your URL is wrong. Please read the **Caution** from doc there:
https://glpi-agent.readthedocs.io/en/latest/configuration.html#available-parameters

**Comment by chris29B** [comment]
Hi @g-bougard 

\glpi-agent.bat --logger=stderr --task netinventory --debug --server=https://*******/marketplace/glpiinventory/
[debug] Logger backend Stderr initialized
[debug] Logger backend File initialized
[debug] GLPI Agent (1.2)
[debug] Configuration directory: C:/Program Files/GLPI-Agent/etc
[debug] Data directory: C:/Program Files/GLPI-Agent/share
[debug] Storage directory: C:\Program Files\GLPI-Agent\var
[debug] Lib directory: C:/Program Files/GLPI-Agent/perl/agent
[debug] [target server0] Next server contact planned for Tue May  3 17:21:43 2022
[debug] Available tasks:
[debug] - Collect: 2.8
[debug] - Deploy: 2.10
[debug] - ESX: 2.7
[debug] - Inventory: 1.11
[debug] - NetDiscovery: 5.1
[debug] - NetInventory: 5.1
[debug] - RemoteInventory: 1.0
[debug] target server0: server https://********/marketplace/glpiinventory/
[debug] Planned tasks for server0: NetInventory
[debug] Provided by Teclib Edition
[debug] Installer built on Wed Apr 13 15:37:28 2022 UTC
[debug] Built with Strawberry Perl 5.34.0
[debug] Built on github actions windows image for glpi-project/glpi-agent repository
[debug] Running in foreground mode
[info] server0 is not ready yet, next server contact planned for Tue May  3 17:21:43 2022

I test the --no-ssl-check of course, but it's the same with a Windows agent and Linux Agent (Debian)

`.\glpi-injector.bat -v -d C:\GLPI-injector\netdiscovery\ --url https://******/marketplace/glpiinventory/ --debug --no-ssl-check`
Loading C:\GLPI-injector\netdiscovery\/X.Y.Z.1.xml...[1485CBA0] ERROR: Unexpected empty server response (ssl check disabled)

**Comment by g-bougard** [comment]
As the agent is telling you, it won't contact the server before `Tue May  3 17:21:43 2022`.
This means `lazy` parameter is enabled by default.
Try to add `--force` option to force the agent to contact the server.

For the injector error, can you confirm GLPI 10 version and GlpiInventory version you're using ?

**Comment by chris29B** [comment]
I don't have any communication issues between GLPI and GLPI agent to upload the inventory, the inventory works on the Windows and Linux machine.

The upload of tasks does not work, and when I execute an agent-injector I have the messages.

I am in GLPI 10

`GLPI 10.0.0 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:fr_FR`

![image](https://user-images.githubusercontent.com/102288193/166480636-54e08fc3-1223-47a6-9bba-3e1f56045ae1.png)

**Comment by g-bougard** [comment]
As you're using a `/marketplace/glpiinventory/` URL, can you still confirm you installed GLPI Inventory plugin via marketplace in the latest version ?

You may need to check on server side in the `glpi/files/_log/php-errors.log` if you have an error at the same time you try to upload a file with injector.
You should also always check the failing file is not corrupted: empty or truncated.

**Comment by chris29B** [comment]
Yes I install the last GLPI Inventory by marketplace

When I run injection for ocs or xml file, I have this log in php-error.log

```
[2022-05-04 08:48:02] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function getOcsComputer() on null in /var/www/glpi/marketplace/ocsinventoryng/hook.php at line 1369
  Backtrace :
  src/Plugin.php:1530                                plugin_ocsinventoryng_ruleCollectionPrepareInputDataForProcess()
  src/RuleCollection.php:1770                        Plugin::doOneHook()
  src/RuleCollection.php:1577                        RuleCollection->prepareInputDataForProcessWithPlugins()
  src/Inventory/Asset/MainAsset.php:499              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:678                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:316                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:364                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:88                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:296    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:233    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:83                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()
```

My ocs, json or xml file not empty

**Comment by g-bougard** [comment]
Okay, so you seem to have an issue with [ocsinventoryng plugin](https://github.com/pluginsGLPI/ocsinventoryng).
Be sure to have installed the latest ocsinventoryng plugin version.

Anyway can you disable that plugin and check if injection works ?

If yes, you should open and issue on the related project linking this issue.

**Comment by chris29B** [comment]
Good idea @g-bougard , it's the plugin ocsinventory 2.0.0. When I disable the plugin, I can inject the file .ocs.

**Comment by g-bougard** [comment]
Okay, then I'm closing this issue. You should open an issue for the plugin linking this one. If finally the plugin issue analysis shows there's indeed an issue on agent side, you would be able to re-open this one.
