### ISSUE TITLE
Variable TAG issue at setup

### ISSUE THREAD

**Issue by lyonelf** [glpi-project/glpi-agent#112]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

here is my command to put in the TAG variable, the 1st OU of the computer DN :
(for /f "tokens=*" %%i in ('powershell -file "\\vm-kya\00\Fusion Inventory\GLPI-PShell.ps1"') do Set TAG=%%i)

here is the PShell.ps1:

function GetComputerOU
    {
     
    $SysInfo = New-Object -ComObject "ADSystemInfo"
        $Computer = [ADSI]("LDAP://{0}" -f $SysInfo.GetType().InvokeMember('ComputerName', [System.Reflection.BindingFlags]::GetProperty, $null, $SysInfo, $null))
        return ([ADSI]$Computer.Parent).OU}  
         GetComputerOU

And this is my command to install the agent with parameters
msiexec /i "\\vm-kya\00\Fusion Inventory\GLPI-Agent-1.2-x64.msi" /quiet SERVER=http://glpi.xxx.local/plugins/fusioninventory TAG=%TAG% ADD_FIREWALL_EXCEPTION=1 DEBUG=1 RUNNOW=1 TASK_FREQUENCY=daily LOGGER=file

Problem: if the %TAG% contain a space, the msi show me the msi option window and the install is killed
               with no space the setup is executed and the variable added in regedit key

### To reproduce

use my scripts in a domain network

### Expected behavior

TAG accept spaces

### Operating system

Windows

### GLPI Agent version

1.2

### GLPI version

9.5.7

**Comment by g-bougard** [comment]
Hi @lyonelf 
did you try to put `%TAG%` into double-quote to have: `TAG="%TAG%"` ?

**Comment by lyonelf** [comment]
Nooo, shame !

i tried only with do set "TAG=%%i"

Other issue, their is not uninstall.exe and an agent don't won't to reinstall on its same version

How can i do, except go back to 1.0 ?

**Comment by g-bougard** [comment]
This is a MSI package. You can uninstall it from the standard UI or just search microsoft documentation to find how to uninstall it.

You can also install a [nightly build](https://nightly.glpi-project.org/glpi-agent/) and switch back to 1.2.
