### ISSUE TITLE
GLPI_AGENT  http authentication doesn't work (windows Domain on IIS)

### ISSUE THREAD

**Issue by Sarameen78** [glpi-project/glpi-agent#113]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

Hello,

I have PHP7.4 installed on a IIS windows 2019 server. I'm using windows authentication (for SSO) to automatically log in my user in GLPI. It works fine.

I've installed the GLPI_AGENT 1.2 and I've been unable to use any credential to authenticate on my IIS.
The log I'm getting is 
`[http client] authentication required, wrong credentials`

I've tried every syntax in the world for authentication directly on the registry key (restart service, relaunch inventory): 
- user : 'domain\logonuser'
- user : 'logonuser'
- user : 'domain\\logonuser'
- user : domain\logonuser
- user : logonuser

Still getting the same error on the log. Using the credential works fine directly on the GLPI interface, and also while using a browser like Firefow which ask for credential to enter my website. Only with the agent, it doesn't work.

I've ended to add the user "IUSR" with reading deny (ntfs security) on the file index.php and allow anonymous authentication to both have the SSO for user and have the agent do not need (and use) http authentication.

### To reproduce

- having GLPI running on a IIS with windows authentication on a Active Directory Domain

### Expected behavior

Expect the agent to use correctly the "user" and "password" credential for http authentication

### Operating system

Windows

### GLPI Agent version

1.2

### GLPI version

10.0.0-rc3

**Comment by g-bougard** [comment]
Hi @Sarameen78 

user/password is needed for "basic http authentication". This is a totally different thing than GLPI interface authentication.

By default, GLPI doesn't require authentication for inventory submission. So did you try to set no user/password on agent side ? And then do you still have `[http client] authentication required` without user/password set in agent configuration ?

~~Also, GLPI final release has been released, upgrade please ;-)~~ _(I updated the bug report form if you would have indeed selected 10.0.0)_

**Comment by g-bougard** [comment]
Hi @Sarameen78 
did you fix your issue from my comment ?

**Comment by g-bougard** [comment]
Hi @Sarameen78 
I'm closing the issue without any answer to my questions.
Feel free to reopen.

**Comment by Sarameen78** [comment]
Hello,
Sorry for the long delay but I was drowing in my new job.

It is still not working. (I've tested again just now)

I do see there is some misunderstanding so I'm gonna try to be clearer.
I do not confuse basic http authentification and glpi authentification.

What I've done before installing the glpi inventory is to set up my GLPI installation on my IIS server and using as http authentification the "Windows Authentification". My GLPI synchronize all my Active Directory users correctly.
And I've set up the GLPI to "receive" the http basic authentification to be the glpi authentification as well.
So when a user open the GLPI web page, the http authentification is its credential as an Active Directory User, then GLPI use that credential to authenticate the user in GLPI.
So my user doesn't enter any credential to be recognize in GLPI.
So far, so good.


But when I've installed the GLPI Inventory plugin and installed the glpi-agent on computer. If I do not set any user and password, I get : 
`[error] [http client] authentication required, no credentials available`
Which is normal as I asked the IIS to require basic http authentification.

So, reading https://glpi-agent.readthedocs.io/en/latest/installation/windows-command-line.html#command-line-parameters
I see that I can set a parameter for basic http authentication. So I've setup an account user and password for GLPI AGENT in my domain.
But, whatever how I write it (I do it directly on the registry before restarting the service - HKEY_LOCAL_MACHINE\SOFTWARE\GLPI-Agent) : 
user='domain\logonuser'                   -                    password='password'
user='logonuser'                 -                   password='password'
user='domain\logonuser'                  -                  password='password'
user=domain\logonuser                 -                   password=password
user=logonuser                 -                   password='password'
user=domain\\logonuser                 -                   password=password
user='domain\\logonuser'                 -                   password='password'
It doesn't work : 
```
[Thu Jun  2 09:01:53 2022][debug] [http client] authentication required, submitting credentials
[Thu Jun  2 09:01:53 2022][error] [http client] authentication required, wrong credentials
[Thu Jun  2 09:01:53 2022][debug2] [http client] received message:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>

<title>401 - Non autorisé : accès refusé en raison d'informations d'identification non valides.</title>
```

I can assure that the credentials are correct.

**Comment by g-bougard** [comment]
Hi @Sarameen78
this still seems to be a httpd server configuration issue. I understand you expect this to work but you probably need to also investigate your IIS server log and look for any error related to the error.
The only thing I see you can try is to double the `\` in the user parameter to have something like: `domain\\logonuser`
I don't know but maybe IIS also permits you to create a dedicated user which is not connected to ldap.
You should also probably try to validate/test your authentication using a commandline like curl.

**Comment by Sarameen78** [comment]
I've seen no special error in my IIS log.
I've tried the \\ but it doesn't work either.
And I've tried with a local account and it doesn't work as well.
I'm gonna investigate on the IIS log to see if I can "catch" how the authentification is being sent by the glpi agent....

**Comment by glionel** [comment]
@Sarameen78 .

Hi,
I hope you are doing well. I recently came across your message from 2022 regarding a similar issue to what I am currently experiencing on my Server 2022 with GLPI, IIS, SSL, and Windows Authentication enabled (SSO).

I was wondering if you had eventually resolved your issue back then. If so, could you please share the solution or the steps you took to resolve it? Your experience would be greatly helpful to me and others facing the same challenge.

Thank you in advance for your response and for sharing your insights.

**Comment by Sarameen78** [comment]
Hi,

Like I said on my first message, I'm using a workaround :
"I've ended to add the user "IUSR" with reading deny (ntfs security) on the file index.php and allow anonymous authentication to both have the SSO for user and have the agent do not need (and use) http authentication."

So : on IIS, I'm using anonymous authentication on all my GLPI installation and I'm not using any authentication for GLPI-Agent. And on the file "index.php", I configure the NTFS right to forbid the account "IUSR" (account used for anonymous authentication) to force other kind of authentication for my GLPI interface (in my case, using windows authentication for SSO login).

I'm still on 10.0.0 so I don't know if the problem has been resolved on later update (I had the feeling that nobody understood my problem and no one else shared the same issue so....)

**Comment by glionel** [comment]
hummm, ça semble fonctionner. Mes connexions reste en https, le http est bien rediriger en https, et l'inventaire fonctionne. Merci à toi.

**Comment by glionel** [comment]
hmmm, that seems to work for me. My connections remain in https, the http is redirected to https, and the inventory works. Thanks to you.
