### ISSUE TITLE
JSON validation error in monitor serial number

### ISSUE THREAD

**Issue by mapass** [glpi-project/glpi-agent#114]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

Hey, I'm trying to install the GLPI Agent on my colleague's computer, but it seems GLPI Agent is trying to send the monitor's serial number as integer, not as string, which produces the following output in the glpi-agent.log:
```[Mon May  2 13:01:26 2022][info] New inventory from 19843UIT.tasr.local-2022-05-02-10-40-57 for server0
[Mon May  2 13:01:57 2022][error] [http client] communication error: 500 Internal Server Error
[Mon May  2 13:01:57 2022][error] [http client] server error: JSON does not validate. Violations:
String expected, 12345678 received at #->properties:content->properties:monitors->items[0]:0->properties:serial
```
and when I've tried to generate the json inventory file, it's obvious, one of the monitors serial number is displayed as an integer, while the other one is wrapper in the quotes, which makes it a string.
Is there any way to fix this and get the glpi-inventory to wrap the serial number in quotes?
Thanks for any help!

### To reproduce

1. Install GLPI Agent 1.2 on Windows 11 PC with two screens/monitors
2. Make sure, one of them is Eizo from 2012, I guess...

### Expected behavior

Well, I would expect the GLPI Agent to upload the inventory to the GLPI server without errors.

### Operating system

Windows

### GLPI Agent version

1.2

### GLPI version

10.0.0-beta

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.0-rc7

### Additional context

Versions are in fact GLPI 10.0.0 and GLPIInventory plugin 1.0.0, so first stable releases, no betas or release candidates.

**Comment by g-bougard** [comment]
Hi @mapass 

thank you for your report. Sorry, we missed this case.

You should use next nightly build on your colleague's computer.

**Comment by mapass** [comment]
Thanks @g-bougard,
it's working now, with the nightly build.
Thank You very much!
