### ISSUE TITLE
Error when scheduling task for Windows machines

### ISSUE THREAD

**Issue by pantherra** [glpi-project/glpi-agent#117]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

When MSI package installs, and you are choosing task scheduling scheme - task not created correctly. 
 Mistake is in the path of application (C:\Program Files\GLPI-Agent\glpi-agent.bat).
  When you are looking for schedule, and open tab with "Actions" - Path to application to run is divided into 2 sections:
 1. "Program or script": C:\Program
  2. And other piece is in "Arguments": Files\GLPI-Agent\glpi-agent.bat
  3. I think mistake in cmd command to create schedule, there is no quotes when you point path to executable script of agent.
  schtasks /create /sc hourly /mo 6 /sd 06/05/2022 /tn GLPI-Agent /tr "C:\Program Files\GLPI-Agent\glpi-agent.bat"

### To reproduce

1. Download latest release of MSI package GLPI-Agent 1.2
2. Run MSI package with Admin rights
3. Choose task schedule
4. Wait for install

### Expected behavior

Task should be created with correct path to executable script.

### Operating system

Windows

### GLPI Agent version

1.2

### GLPI version

10.0.0

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

**Comment by g-bougard** [comment]
Hi @pantherra 
thank you for the reporting, I think like you, I should have missed some quote somewhere.

**Comment by g-bougard** [comment]
Hi @pantherra 

please, can you try next tomorrow [nightly build](https://nightly.glpi-project.org/glpi-agent/) to validate it fixes your issue ?

**Comment by pantherra** [comment]
> 

Hello! I checked nightly build, and schedule task created correct. Thank you!
