### ISSUE TITLE
Adding Good format of naming file for .json

### ISSUE THREAD

**Issue by krenaudUR** [glpi-project/glpi-agent#119]
### Documentation

Yes, I read it

### Professional support

Still not applicable

### Expected behavior

I would like that when we use glpi-agent.bat -l=C:\ --json it's give a name format like html with is Name-Year-Date-Month-Hour-Minute-Second.
Because html do the right name format but we can't import html in glpi (only json, xml, ocs)

Or maybe add a --xml because it's seems xml also have the right format and can be imported
 

### Alternatives you've considered

Manually change name of the file but it's not really a solution

### Additional context

It's important because we keep the file imported in glpi in case of problem and if the name format is not right it's more complicated to know what is this file if it's "18b1033b-6c1a-1014-8ba1-a057aa281ae1.json"

**Comment by g-bougard** [comment]
Hi @krenaudUR 

for now, just don't use `--json` option and the agent will generate a XML file by default with a filename like you want.

I'll check if we can better come back on a pretty name for json format too.

**Comment by krenaudUR** [comment]
> Hi @krenaudUR
> 
> for now, just don't use `--json` option and the agent will generate a XML file by default with a filename like you want.
> 
> I'll check if we can better come back on a pretty name for json format too.

Ah it's using xml when we don't specify, I didn't know, thanks
