### ISSUE TITLE
Service Agent installation fail, service no start

### ISSUE THREAD

**Issue by Guillaume3300** [glpi-project/glpi-agent#120]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

agent installation fails when in windows environment variable there is already a PERL5LIB variable for another application

### To reproduce

add windows environment variable PERL5LIB with another path
launch an installation, it will fail because it is impossible to start the service

### Expected behavior

service agent can't start

### Operating system

Windows

### GLPI Agent version

1.2

### GLPI version

10.0.0

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.0

**Comment by g-bougard** [comment]
Hi @Guillaume3300 
thank you for your report.
I'm currently testing. But I would like a confirmation on a point to be sure I reproduce the same way than your issue: can you confirm if you see a "GLPI-Agent" service or not in service manager ?
In my case, if I set PERL5LIB to C:\Temp with nothing related to a perl installation, I don't have any trouble. But if I set PERL5LIB to C:\Strawberry\perl\vendor and as this points to a different perl installation than the one used by GLPI Agent, I don't even see the service installed.
So can you also confirm with what value your PERL5LIB environment variable is set ?

**Comment by g-bougard** [comment]
Hi @Guillaume3300 
[latest nightly](https://nightly.glpi-project.org/glpi-agent/) fixes that issue in the case I was able to reproduce.
Can you confirm on your side ?
Thank you
