### ISSUE TITLE
SNMP Discovery Devices Network - GLPI V10

### ISSUE THREAD

**Issue by eltonsjbv1** [glpi-project/glpi-agent#122]
![Captura de tela 2022-05-19 163928](https://user-images.githubusercontent.com/42739800/169388950-38b08727-3376-4255-8003-f9a937ea8cb4.png)
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Professional support

Yes, I know

### Is your help request related to a problem?

I have installed glpi inventory plugin, and i did the configuration for discovery devices network, but i have the bellow error:

"Error The agent is requesting a configuration that has already been sent to it by the server. The agent is more likely to be subject to a critical error."

I use the glpi server agent same.  Version: GLPI-Agent_v1.2-1

### Expected behavior

Discovery all my devices network snmp, like printers, etc

### Actions you've considered

I have the old glpi version 9.5 and work fine the fusioninventory, so i copy the same configs and rules for my new glpi v10, but not work.

### Additional context

My agent snmp start, but with 0 threads

**Comment by g-bougard** [comment]
Hi @eltonsjbv1 
can you enable debug=2 on agent side, force again the task on server-side and then force the agent to run ?
Then check the agent log for any error and share it here.
This kind of error is often a misconfiguration problem and this process can show where is the problem.

**Comment by eltonsjbv1** [comment]
![Captura de tela 2022-05-20 102927](https://user-images.githubusercontent.com/42739800/169538320-a76aa526-966f-4159-b717-3cb45a6130d8.png)

This my log agent


![Captura de tela 2022-05-20 103011](https://user-images.githubusercontent.com/42739800/169538531-dfabad7f-71ac-4fc0-8121-c303f456ed7f.png)

**Comment by g-bougard** [comment]
Hi @eltonsjbv1 
please use `http://glpi/plugins/glpiinventory/` or `http://glpi/marketplace/glpiinventory/` as server url depending on how you installed GlpiInventory and as this is explained in documentation:
https://glpi-agent.readthedocs.io/en/latest/configuration.html#available-parameters
