### ISSUE TITLE
Update GLPI agent from version 1.1 to version 1.2 using deploy functionality (FI)

### ISSUE THREAD

**Issue by joschi99** [glpi-project/glpi-agent#125]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

Updating GLPI agent for Windows from version 1.1 to version 1.2 will fail using the software deployment function from Fusion Inventory 9.5 4.1
Manual silent update works

### To reproduce

1. Computer with GLPI agent for Windows x64 version 1.1 installed
2. create a new software deployment task on GLPI 9.5.7 and FI 9.5 4.1
3. upload the new agent version 1.2 and create the silent installation
![image](https://user-images.githubusercontent.com/6400595/170124999-708ddb4f-5da1-4fd4-b0d5-070816dd2b22.png)
4. start software deployment task on client

Software deployment task starts successfull, silent setup will start, Task will failed because glpi agent service stops during the upgrade process. But the client update failes on, agent is not updated correctly and glpi agent service will not more working correctly on this client.
To resolve the problem you need to uninstall the agent, reboot the computer and install from scratch the agent

### Expected behavior

Client upgrade will finish correctly and glpi agent service will restart with version 1.2
Software deployment job will return an error because during the update the service will be restart

### Operating system

Windows

### GLPI Agent version

1.2, 1.1

### GLPI version

9.5.7

### GLPIInventory plugin or FusionInventory for GLPI plugin version

9.5+4.0

**Comment by g-bougard** [comment]
Hi @joschi99 

can you try with the following command ?
```
msiexec /i GLPI-Agent-1.2-x64.msi /quiet
```

Also it would probably be more clean to better schedule the upgrade with such a command:
```
schtasks /create /sc minute /mo 1 /tn GLPI-Agent-1.2-Upgrade /ru system /f /tr 'C:\Program Files\GLPI-Agent\upgrade.bat'
```
This will schedule the upgrade at the next minute change.

With the package, before scheduling the bat file, copy `GLPI-Agent-1.2-x64.msi` & `upgrade.bat` under `C:\Program Files\GLPI-Agent`, where `upgrade.bat` file contains:
```
schtasks /delete /f /tn GLPI-Agent-1.2-Upgrade
cd "C:\Program Files\GLPI-Agent"
start /wait msiexec /i GLPI-Agent-1.2-x64.msi /quiet
del upgrade.bat GLPI-Agent-1.2-x64.msi
```

You can of course change the schedule by specifying a given time or ask it on reboot or when the computer is idle. Check the [schtasks command doc](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/schtasks-create) if you want a more convenient schedule.

**Comment by g-bougard** [comment]
Closing without feedback.
Feel free to reopen or just comment.
