### ISSUE TITLE
Non-ascii characters are malformed in json on MacOSX

### ISSUE THREAD

**Issue by marekpierog** [glpi-project/glpi-agent#127]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

Non-ascii characters such as polish diacritics are improperly saved.
For example MacOS default application Photos is called Zdjęcia if system locale are set to Polish and this is the way glpi-agent saves it's name:

`         {
            "install_date": "2022-03-26",
            "name": "ZdjeÌ¨cia",
            "system_category": "System/Applications",
            "username": "",
            "version": "7.0"
         },`

### To reproduce

`/Applications/GLPI-Agent/bin/glpi-inventory --json > somefile.txt`

### Expected behavior

Non-ascii characters should be saved as UTF-8.

### Operating system

MacOSX

### GLPI Agent version

1.2

### GLPI version

10.0.0

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.0, Not applicable

**Comment by g-bougard** [comment]
Hi @marekpierog 

can you provide the output of `/usr/sbin/system_profiler -xml SPApplicationsDataType` ?

Is the problem only for softwares or do you see any other encoding problem somewhere else ?

Is the encoding correct when you using xml format when running: `/Applications/GLPI-Agent/bin/glpi-inventory > somefile.xml` ?

**Comment by marekpierog** [comment]
Hi @g-bougard 
in the output of system_profiler all names are correctly encoded as UTF-8. As an example with Photos app:
```
			<dict>
				<key>_name</key>
				<string>Zdjęcia</string>
				<key>arch_kind</key>
				<string>arch_arm_i64</string>
				<key>lastModified</key>
				<date>2022-03-26T07:21:13Z</date>
				<key>obtained_from</key>
				<string>apple</string>
				<key>path</key>
				<string>/System/Applications/Photos.app</string>
				<key>signed_by</key>
				<array>
					<string>Software Signing</string>
					<string>Apple Code Signing Certification Authority</string>
					<string>Apple Root CA</string>
				</array>
				<key>version</key>
				<string>7.0</string>
			</dict>
```

From what I can see the same problem apears on every string - for instance computer name:
`Artur's MacBook Pro becomes Arturâs MacBook Pro`

XML output is fine, again as an example:
```
    <SOFTWARES>
      <INSTALLDATE>26/03/2022</INSTALLDATE>
      <NAME>Zdjęcia</NAME>
      <SYSTEM_CATEGORY>System/Applications</SYSTEM_CATEGORY>
      <USERNAME></USERNAME>
      <VERSION>7.0</VERSION>
    </SOFTWARES>
```

**Comment by g-bougard** [comment]
Thank you, this should help to make a fix.
Just a point, does your XML produced by system_profiler have a header with the currently used xml encoding ?
I'm not a MacOSX expert but do you know if that output is always UTF-8 or could be a local one depending on some system configurations ?

**Comment by marekpierog** [comment]
Yep, system_profiler output has utf-8 encoding (first line states: ```<?xml version="1.0" encoding="UTF-8"?>```).
I'm not 100% sure if it was always the case, but at least at all currently supported MacOS versions (10.15+) the output is always encoded as UTF-8.

**Comment by we-sell-bags** [comment]
I think it's the top part  he needs.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
```

i'd have to reboot to Chinese to see if its the same

**Comment by g-bougard** [comment]
Hi @marekpierog and @we-sell-bags 
can I ask you to test the development build that is attached to that [GLPI Agent Packaging GH actions](https://github.com/glpi-project/glpi-agent/actions/runs/2434553207) as MacOSX-Build archive artifact ? As this is a development version, it won't be notarized so you'll probably have to by-pass the system security through the security panel.
If this build fixes that issue, it will be merged and will be integrated in next nightly build which this time will be notarized to be approved by the system.
Thank you.

**Comment by g-bougard** [comment]
I tested myself today the build and it seems to fix the JSON case.

Can you confirm this is also the case for you using the next nightly build ?

**Comment by marekpierog** [comment]
@g-bougard I tried on bunch of both Intel and Apple Silicon Macbooks - the encoding is fine now - thank you!
