### ISSUE TITLE
[package] fusioninventory-agent detect and remove

### ISSUE THREAD

**Issue by bato3** [glpi-project/glpi-agent#13]
As `glpi-agent` replaces `fusioninventory-agent`, I suggest adding an extra step in installers to detect settings from `fusioninventory` and optionally uninstall it.

BTW: Currently `glpi-agent` uses the same local port as `fusioninventory` by default, and this will cause conflicts.

**Comment by g-bougard** [comment]
Hi @bato3 
thank you for your suggestion.
Btw uninstalling a software from another one installer is definitively not recommended and I'm sure official distributions (including MS) will consider this as an error. Can you imagine Chrome uninstalling FF or Edge ?
Then another point, it is definitively possible to have fusioninventory-agent and glpi-agent running on the same platform, and maybe people will need this possibility.
So even taking the fusioninventory-agent configuration could be a mistake.

And of course we use the same default port and this could generate a conflict with a still installed fusioninventory-agent, but glpi-agent will still continue to run its major expected job : make inventory and submit it to GLPI.

Indeed, I agree this is still not clear in doc (as there're not so much docs) but you really need to uninstall fusioninventory-agent before installing glpi-agent if the purpose is to replace the current agent with the same config. Historically, this was still the way to do when people wanted to replace OCSInventory agent by fusionivnentory-agent.

Maybe we will propose a script to do this task automatically, including keeping the fusioninventory-agent settings but this can't happen in the installer at this time. Indeed such a script still exists for FusionInventory vs OCSInventory so you can expect such a script when we will start to publish official releases.

**Comment by bato3** [comment]
Hi @g-bougard 
thanks for your reply.

We might not really understand each other. I never wanted settings and uninstallation to be mandatory.
For years, browsers have been asking whether to import bookmarks. Also, anti-viruses have installers with the option to uninstall other anti-virus software.

You say that two agents can act together, but it will be marginal cases.  So, according to what you said: **I'm waiting for the migration support script for a new solution.**

And I still think the installer should detect `fusioninventory-agent` as a possible conflict, suggest uninstallation, and check port is taken.

**Comment by glassworksvfx** [comment]
Sorry more novice questions here. Is this staement by @bato3 true?

> As `glpi-agent` replaces `fusioninventory-agent`

If yes then I can plan the replacement as we are still in an early stage of deployment, or are we getting ahead of ourselves here?

**Comment by g-bougard** [comment]
Hi @glassworksvfx 
it depends on when you're planning your production. But you still can plan a replacement later unless you really need some glpi-agent features everywhere.
At the moment, glpi-agent is more than 90% equals to fusioninventory-agent v2.6. In few case, like it is still recommended to use glpi-agent but you still can go with fusioninventory-agent.
The first official glpi-agent release should come before the end of the year.
Also, we'll continue to support fusioninventory-agent as it will still be the same code base.
So planning a replacement is probably a good thing but this is not a constraint at the moment.

**Comment by glassworksvfx** [comment]
Thank you @g-bougard , I'm just trying to get the general gist here as I'm fairly new to GLPI.
