### ISSUE TITLE
SNAP version don't work with certificate

### ISSUE THREAD

**Issue by NoneRain** [glpi-project/glpi-agent#131]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

glpi-agent can't communicate with the https server using a certificate, when installed with snap.
`glpi-agent.daemon[541]: [error] [http client] internal response: 500 Can't connect to webserver.local:443 (certificate verify failed)`

Perl version is working with this config.
Win32 version is working with this config.

OS: Ubuntu LTS 22.04
Agent: 1.2
Package: snap

### To reproduce

1. snap install --classic --dangerous glpi-agent_1.2_amd64.snap
2. snap set glpi-agent server="https://webserver.local/front/inventory.php" nosslcheck=1 cacertfile=/etc/ssl/certs/cacert.pem
3. snap restart glpi-agent

### Expected behavior

Successful communication with the server.
`[info] sending contact request to server0`
`[info] New inventory from LOCALPC-time for sever0`

### Operating system

Linux

### GLPI Agent version

1.2

### GLPI version

10.0.0

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.0

**Comment by g-bougard** [comment]
Hi @NoneRain 

the configuration parameter should be `ca-cert-file`, not `cacertfile`. So try running:
```
snap set glpi-agent server="https://webserver.local/" ca-cert-file=/etc/ssl/certs/cacert.pem
```

Also `nosslcheck` is wrong as this should be `no-ssl-check` but you don't need it if `ca-cert-file` is working.

**Comment by NoneRain** [comment]
@g-bougard,
Sorry for the mistake, I used parameters without '-' and had no errors, so I wrongly assumed it was correct.
After that, I changed `https://webserver.local/front/inventory.php` for `https://webserver.local/`, and it successfully communicated with the server.
Thanks, and mb.
