### ISSUE TITLE
ADMX import error : Encountered an error while parsing. DTD is prohibited

### ISSUE THREAD

**Issue by Benoit72** [glpi-project/glpi-agent#137]
### Bug reporting acknowledgment

Not applicable

### Describe the bug

Hello,

I import ADMX file (GLPI-Agent.admx) in my domain.
I get this error  
Encountered an error while parsing. DTD is prohibited
"File:
\\domainname.local\sysvol\domainname\Policies\PolicyDefinitions\GLPI-Agent.admx, line 8, column 9"

Domain Windows is in french language.

Thanks for your help.

Benoît

### To reproduce

1.Download admx file https://github.com/glpi-project/glpi-agent/blob/develop/contrib/windows/GLPI-Agent.admx
2.Copy the file in \\domainname.local\SysVol\domainname.local\Policies\PolicyDefinitions
3 Open Gpedit.msc and obtain the error

### Expected behavior

I would like to use the admx file

### Operating system

Windows

### GLPI Agent version

1.2

### GLPI version

10.0.0

**Comment by g-bougard** [comment]
Hi @Benoit72 
can you double-check the file you copied ? I don't see any problem at line 8, column 9 in this file. Maybe yours has been modified for some reason.

**Comment by Benoit72** [comment]
Hi,

Il understood the error.
I download file with "save as". The code was not the same.

Thanks

Ben
