### ISSUE TITLE
GLPI Agent remote management of LiteManager

### ISSUE THREAD

**Issue by shadrinid** [glpi-project/glpi-agent#138]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

When the device is inventoried, the LiteManager server id is not added to the Remote Management tab. Everything is fine with TeamViewer and AnyDesk.

### To reproduce

![Screenshot_1](https://user-images.githubusercontent.com/107064892/172633151-5c887cef-6159-49f0-82f8-5302ac3aa913.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/107064892/172633180-6b0094f0-9732-4a2d-a13e-fc6056503efe.jpg)

### Expected behavior

Adding a link is similar to AnyDesk

### Operating system

Windows

### GLPI Agent version

1.2

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

Version GLPI 10.0.1
Plugin GLPI 1.0.1

**Comment by g-bougard** [comment]
Hi @shadrinid 

~~to be sure this is a remote inventory problem, did you try to install the agent locally to verify you get the LiteManager id this time ?~~

You can also check the computer registry and search for a `ID (read only)` into `HKEY_LOCAL_MACHINE/SYSTEM/LiteManager` key tree or `HKEY_LOCAL_MACHINE/SOFTWARE/LiteManager` key tree. If you find it can you report the for registry path and the value you found ?

**Comment by g-bougard** [comment]
Can you try to update the LiteManager.pm module manually to modify the line 21 so it looks like:
```
            maxdepth    => 3,
```
in place of:
```
            maxdepth    => 1,
```

**Comment by shadrinid** [comment]
The ID key is missing. The module has been updated.

**Comment by g-bougard** [comment]
If you enable debug=2 in registry, can you check the agent log to see if LiteManager module is enabled when running inventory ?
By `The ID key is missing.`, what do you mean ? It is missing from inventory or registry ? Can you check for `ID (read only)` in registry as I asked earlier ?

**Comment by shadrinid** [comment]
ID (read only) is missing in the registry when installing LiteManager Server Pro. This key is created in the HKEY_LOCAL_USER/SOFTWARE/LiteManager branch only when the portable version is launched ROMServer.exe

**Comment by g-bougard** [comment]
Okay, so this case is not supported.

As the agent is run with the local system account, it can't really guess LiteManager is run from a given user.

So I'm closing the issue, but feel free to reopen if you know any way to catch that `ID (read only)` from the local system account.

**Comment by shadrinid** [comment]
I solved the problem with the missing ID key (read only). Now the key is in the correct registry branch, but LiteManager has not appeared in remote management in GLPI.

**Comment by g-bougard** [comment]
Can you describe how you solved the problem ? And eventually can you make an export of the resulting registry key and share it here (obfuscating the ID) ?

**Comment by shadrinid** [comment]
Fixed by setting the generate new ID flag when starting and restarting LiteManager. The key is attached to the comment.
[ID(litemanager).zip](https://github.com/glpi-project/glpi-agent/files/8870821/ID.litemanager.zip)

**Comment by g-bougard** [comment]
Do you have any other "Server\Parameters" sub key under any `HKEY_LOCAL_MACHINE\SOFTWARE\LiteManager` or `HKEY_LOCAL_MACHINE\SYSTEM\LiteManager` version subkey ?
Like for example a `HKEY_LOCAL_MACHINE\SOFTWARE\LiteManager\v3.3\Server\Parameters` one where no `ID (read only)` key is present.

**Comment by shadrinid** [comment]
No. The specified subsections have this key.
![image](https://user-images.githubusercontent.com/107064892/172874332-3c25cf9f-4f31-49c3-b8d3-6e80f6c16a57.png)

**Comment by g-bougard** [comment]
Can you share the output of the following command (obfuscating any sensible data) ?
```
glpi-inventory --partial remote_mgmt --debug --debug
```
Run it from an administrator console and from the GLPI-Agent installation folder.

**Comment by g-bougard** [comment]
Oh ! I see you have the 2 `HKEY_LOCAL_MACHINE\SYSTEM\LiteManager\v3.4\Server\Parameters` and `HKEY_LOCAL_MACHINE\SOFTWARE\LiteManager\v3.4\Server\Parameters` keys...
Do you have `ID (read only)` key in the 2 locations ? or is it missing from the "SYSTEM" one ?
