### ISSUE TITLE
Add openSUSE  support

### ISSUE THREAD

**Issue by ghost** [glpi-project/glpi-agent#139]
### Documentation

Yes, I read it

### Professional support

Yes, I know

### Is your feature request related to a problem?

Currently, (in my opinion) there is no way to install the GLPI Agent on a client running OpenSUSE (Leap and Tumbleweed). In our company there is one employee who uses OpenSUSE Leap, and we cannot install the GLPI agent via the perl script or via the rpm package (the rpm package has unmet dependencies). 

### Expected behavior

I would like a support for OpenSUSE in the perl installation script and a rpm package which works with OpenSUSE.

### Alternatives you've considered

The current workaround is that we use the snap or appImage. But I'm not a fan of both. So if there is a Flatpak support in the near future, it would make me very happy too.

**Comment by g-bougard** [comment]
Hi @tzaspel-finatix 

thank you for this feedback.

Maybe we will add a flatpak package in the future, but this is not planned at that time.

Indeed the first thing I can do is to add support for OpenSUSE to the perl installer. This should be relatively easy as I developed it to be modular against distro.
Everything is there: https://github.com/glpi-project/glpi-agent/tree/develop/contrib/unix/installer

I'm not familiar with OpenSUSE but I guess the perl installer detects it as RPM based distro and tries to use dnf or yum. And this should be wrong with OpenSUSE. So I need to learn what's the right way with OpenSUSE.

About the rpm, it was modified to be kept as generic as possible. Did you still try to install the dependencies manually to finally have it installed and working ? If yes, maybe you or someone still have scripted the process so I can quickly implement it in the perl installer.

**Comment by ghost** [comment]
Hi @g-bougard

Thanks for your swift response!  
This sounds really great! Yeah, OpenSUSE uses zypper instead of dnf or yum.
I haven't installed the dependencies, but I'll try it the next days and update you.

Update:

I installed a test VM with OpenSUSE Leap 15.4 and got the following message:

```bash
localhost:/home/test-user/Downloads # zypper install glpi-agent-1.2-1.noarch.rpm
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'perl(Proc::Daemon)' needed by the to be installed glpi-agent-1.2-1.noarch
 Solution 1: do not install glpi-agent-1.2-1.noarch
 Solution 2: break glpi-agent-1.2-1.noarch by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c): 
```

**Comment by ghost** [comment]
I'm currently not able to install this dependency because I don't know how to install `perl(Proc::Daemon)`. Do you have advice?

**Comment by g-bougard** [comment]
I just tested on a fresh openSUSE tumbleweed installation. I was able to install manually the glpi-agent rpm after I had added the [devel:languages:perl repository](https://build.opensuse.org/repositories/devel:languages:perl).
I'm preparing an update for glpi-agent perl installer to support `zypper` and follow this requirement.

On OpenSUSE Leap 15.4, you should just have to run this commands:
```
zypper --gpg-auto-import-keys addrepo -f https://download.opensuse.org/repositories/devel:/languages:/perl/15.4/devel:languages:perl.repo
zypper refresh
zypper install --allow-unsigned-rpm glpi-agent-1.2.noarch.rpm
```

**Comment by g-bougard** [comment]
Hi there,

next nightly perl installer should support openSUSE. Please test and report any problem ;-)

**Comment by ghost** [comment]
Thanks a lot!!! I greatly appreciate your fast responses and work on this project!
