### ISSUE TITLE
[installer] spell mistake

### ISSUE THREAD

**Issue by bato3** [glpi-project/glpi-agent#14]
GLPI-Agent-1.0-gite321be48-x64.msi

 `é` -> `e`

![image](https://user-images.githubusercontent.com/11570/122189152-f8d12280-ce90-11eb-8f87-ecec58c78cf4.png)

**Comment by g-bougard** [comment]
Ha ! Yes, I saw it yesterday but forgot to note it ;-)
Thank you for this reminder !

**Comment by g-bougard** [comment]
and also I should have tell it is `recommended`... not `recommanded` double mistake in the sentence
