### ISSUE TITLE
Force Inventory fails

### ISSUE THREAD

**Issue by willgl1** [glpi-project/glpi-agent#140]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

When pressing force inventory or manually running through the "C:\Program Files\GLPI-Agent\glpi-inventory.bat" file nothing happens. Status remains as "waiting" for me.

Inventory agent shows in GLPI but only actually runs an inventory on the default 24 hour schedule.

### To reproduce

1. navigate to `http://localhost:62354/`
2. press force inventory
3. Press Back and check status

### Expected behavior

status with Fusion would change to running inventory, and inventory would complete. This is only from local host, I understand now that the web refresh requires a plugin configuration to allow this.

### Operating system

Windows

### GLPI Agent version

1.2

### GLPI version

10.0.0

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.0

**Comment by g-bougard** [comment]
Hi @willgl1 

about the commandline run, here, there's a change against FI Agent. By default, the "lazy" option has been enabled. You should be able to force the inventory when running with the `--force` option. Can you confirm ?

For forcing from the integrated http interface, this is more strange. Can you check an report any error you can see and which could be related to the moment you ask to run now ?

Maybe changing the `lazy` parameter to `0` in registry can help. Let us know as maybe this is a bug I missed if lazy=1 also means `/runnow` won't do the expected job.

**Comment by willgl1** [comment]
Just found the log file and it seems this is a URI issue as getting multiple 400 not found. Been playing around with this quite a lot and the root URI was `http://censored-server/front/inventory.php` I believe the initial inventory worked when set to `http://censored-server/`

Going to check and come back, useful to know the lazy parameter in the registry either way.

**Comment by willgl1** [comment]
Again, thanks for the quick response. Seems this was me jumping the gun and a false alarm. URI needed to be the root not the full path. Not sure if this is still a bug? But had to be `http://censored-server/glpi` to work

**Comment by g-bougard** [comment]
Okay, if this is a `server` parameter configuration issue, this is definitively not a bug ;-)
