### ISSUE TITLE
Get keyboard and mouse S/N

### ISSUE THREAD

**Issue by walday** [glpi-project/glpi-agent#143]
### Documentation

Yes, I read it

### Is your feature request related to a problem?

I need correct inventory mouse and keyboard in company

### Expected behavior

If agent get SN, then inject this data automatic to glpi

### Alternatives you've considered

Manual inventory - bad tracking devices, and problem if scratching SN on old devices.

**Comment by g-bougard** [comment]
Hi @walday 

as far I know, we are not able to catch S/N for input devices. But maybe I missed something as `inputs` category is related to an historic kind of devices.
Do you know a method to get such information in a specific context ?
