### ISSUE TITLE
Antivirus is not displayed on Windows Server

### ISSUE THREAD

**Issue by Badkempachi** [glpi-project/glpi-agent#144]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

Good afternoon,
There is a problem with the antivirus display on Windows Server OS.
The agent itself collects information about the antivirus, but does not display the information in the web panel.

### To reproduce

The easiest way is to import the inventory file that I attached.
In another case, install Dr.web or Kaspersky antivirus on Windows Server, and then install GLPI Agent.
[drweb2.localhost.net-2022-02-11-15-39-53.xml.txt](https://github.com/glpi-project/glpi-agent/files/8897917/drweb2.localhost.net-2022-02-11-15-39-53.xml.txt)

### Expected behavior

Installing the agent on a Windows Server with Dr.web or Kaspersky antivirus installed and this information is displayed in the GLPI web panel

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

development release (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

GLPI Inventory 1.0.1
GLPI 10.0.2
GLPI-Agent-1.3-git8249d66c-x64
[glpi-agent.log](https://github.com/glpi-project/glpi-agent/files/8897920/glpi-agent.log)
![glpi_web](https://user-images.githubusercontent.com/97535165/173532568-0354a046-9b92-41ed-8533-045544839724.jpg)

**Comment by g-bougard** [comment]
Hi @Badkempachi 

afaik, the problem is indeed Windows Server doesn't provide any information about installed AV as Windows Desktop does. Unless this has changed on OS side we can't do anything. You should probably better complain to Microsoft.
