### ISSUE TITLE
TAG option is not updated on Inventory Number field into GLPI

### ISSUE THREAD

**Issue by elmotofan** [glpi-project/glpi-agent#147]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

After deploy GLPI-Agent v1.2 on Windows (Workstations and Servers), using glpi-agent-deployment.vbs with TAG option. This is not taken by Inventory on GLPI, the field Inventory Number is filled out by the serial number of the computer.

Same computer with the FusionInventory-Agent with the same TAG option, reports into Inventory on GLPI correctly.

![image](https://user-images.githubusercontent.com/57363519/174209162-0e39aa05-cba0-4e52-8492-44c5b9927bb5.png)

Inventory Agent:
![image](https://user-images.githubusercontent.com/57363519/174209420-07fbf197-b2c6-4d4d-9a35-a4d2442f95d3.png)

Other Computer with FusionInventory-Agent:
![image](https://user-images.githubusercontent.com/57363519/174209888-b24f3502-f43a-49e1-924a-f4169e1c7154.png)

Inventory Agent:
![image](https://user-images.githubusercontent.com/57363519/174210088-2df43ebf-d22d-4c72-9ed6-0fcf00b12861.png)

Is the same Entity, same rules for import. 

### To reproduce

Install a GLPI-Agent v1.2 on a computer using command line through script: glpi-agent-deployment.vbs add "TAG" option in line 116
SetupOptions = "/quiet RUNNOW=1 SERVER='http://glpi-server/glpi/front/inventory.php' TAG=Production" 

Check Asset / Computers the content of "Inventory number" field.

### Expected behavior

I expected to view the TAG set into "Inventory Number" field, like occur with the FusionInventory-Agent.

### Operating system

Windows

### GLPI Agent version

1.2

### GLPI version

10.0.0

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

**Comment by g-bougard** [comment]
Hi @elmotofan 

"Inventory number" is definitively something else than "Tag". In GLPI 10, it's possible to show "Tag" in the list by selecting "Tag" from "Agents" section when adding a column to the view.

Also "Inventory number" is definitively not set by the agent. This is a server-side feature and before this was set by FI plugin if I remember well. Do you still have this plugin installed ?
I can just suggest you to review your full server configuration. Few configuration features has been moved around so you should be a little confused.

I'm closing as this is definitively not an agent issue.
