### ISSUE TITLE
Server connection error after upgrade to version 1.3

### ISSUE THREAD

**Issue by yasanchezco** [glpi-project/glpi-agent#148]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

After upgrading the agent to version 1.3 it is not possible to connect to the server. 

### To reproduce

[Wed Jun 15 06:58:56 2022][info] sending prolog request to server0
[Wed Jun 15 06:58:58 2022][info] server0 answer shows it supports GLPI Agent protocol
[Wed Jun 15 06:59:00 2022][info] running task Deploy
[Wed Jun 15 06:59:01 2022][error] [http client] Can't decode JSON content, starting with 
[Wed Jun 15 06:59:01 2022][info] Deploy task not supported by server0
[Wed Jun 15 06:59:03 2022][info] running task Inventory
[Wed Jun 15 06:59:03 2022][info] New inventory from LAPTOP123-2021-12-27-11-43-33 for server0
[Wed Jun 15 06:59:33 2022][info] running task Collect
[Wed Jun 15 06:59:35 2022][error] [http client] Can't decode JSON content, starting with 
[Wed Jun 15 06:59:35 2022][info] Collect task not supported by server0
[Wed Jun 15 06:59:36 2022][info] target server0: next run: Thu Jun 16 06:41:42 2022 - https://glpi.xxxxxx.com/glpi/
[Wed Jun 15 06:59:36 2022][info] GLPI Agent memory usage: WSS=3362816 PFU=166428672
[Wed Jun 15 17:21:13 2022][info] GLPI Agent service starting
[Wed Jun 15 17:21:13 2022][error] unable to get address for 'glpi.xxxxxx.com': Host desconocido. 
[Wed Jun 15 17:21:13 2022][error] unable to get address for 'glpi.xxxxxx.com': Host desconocido.
[Wed Jun 15 17:21:14 2022][info] [http server] HTTPD service started on port 62354
[Wed Jun 15 17:21:15 2022][info] GLPI Agent memory usage: WSS=3706880 PFU=104079360
[Wed Jun 15 17:21:15 2022][info] target server0: next run: Thu Jun 16 06:41:42 2022 - https://glpi.xxxxxx.com/glpi/
[Wed Jun 15 17:23:28 2022][info] running task Deploy: storage maintenance event
[Wed Jun 15 17:23:30 2022][info] GLPI Agent memory usage: WSS=3485696 PFU=112517120
[Wed Jun 15 17:46:17 2022][info] GLPI Agent service starting
[Wed Jun 15 17:46:17 2022][error] unable to get address for 'glpi.xxxxxx.com': Host desconocido. 
[Wed Jun 15 17:46:17 2022][error] unable to get address for 'glpi.xxxxxx.com': Host desconocido.
[Wed Jun 15 17:46:18 2022][info] [http server] HTTPD service started on port 62354
[Wed Jun 15 17:46:19 2022][info] GLPI Agent memory usage: WSS=3690496 PFU=104157184
[Wed Jun 15 17:46:19 2022][info] target server0: next run: Thu Jun 16 06:41:42 2022 - https://glpi.xxxxxx.com/glpi/
[Thu Jun 16 07:10:10 2022][info] running task Deploy: storage maintenance event
[Thu Jun 16 07:10:12 2022][info] GLPI Agent memory usage: WSS=3248128 PFU=117329920
[Thu Jun 16 07:10:13 2022][info] target server0: server https://glpi.xxxxxx.com/glpi/
[Thu Jun 16 07:10:13 2022][info] sending contact request to server0
[Thu Jun 16 07:10:15 2022][info] sending prolog request to server0
[Thu Jun 16 07:10:16 2022][info] running task Inventory
[Thu Jun 16 07:10:16 2022][info] New inventory from LAPTOP123-2021-12-27-11-43-33 for server0
[Thu Jun 16 07:10:56 2022][info] running task Deploy
[Thu Jun 16 07:10:56 2022][error] [http client] Can't decode JSON content, starting with 
[Thu Jun 16 07:10:56 2022][info] Deploy task not supported by server0
[Thu Jun 16 07:11:00 2022][info] running task Collect
[Thu Jun 16 07:11:01 2022][error] [http client] Can't decode JSON content, starting with 
[Thu Jun 16 07:11:01 2022][info] Collect task not supported by server0
[Thu Jun 16 07:11:02 2022][info] target server0: next run: Fri Jun 17 06:51:01 2022 - https://glpi.xxxxxx.com/glpi/
[Thu Jun 16 07:27:53 2022][info] GLPI Agent service starting
[Thu Jun 16 07:27:53 2022][error] unable to get address for 'glpi.xxxxxx.com': Host desconocido. 
[Thu Jun 16 07:27:53 2022][error] unable to get address for 'glpi.xxxxxx.com': Host desconocido.
[Thu Jun 16 07:27:53 2022][info] [http server] HTTPD service started on port 62354
[Thu Jun 16 07:27:56 2022][info] GLPI Agent memory usage: WSS=3678208 PFU=104230912
[Thu Jun 16 07:27:56 2022][info] target server0: next run: Fri Jun 17 06:51:01 2022 - https://glpi.xxxxxx.com/glpi/
[Thu Jun 16 07:30:09 2022][info] running task Deploy: storage maintenance event
[Thu Jun 16 07:30:11 2022][info] GLPI Agent memory usage: WSS=3219456 PFU=112754688
[Thu Jun 16 20:36:29 2022][info] target server0: server https://glpi.xxxxxx.com/glpi/
[Thu Jun 16 20:36:29 2022][info] sending contact request to server0
[Thu Jun 16 20:36:31 2022][info] running task Inventory
[Thu Jun 16 20:36:31 2022][info] New inventory from LAPTOP123-2021-12-27-11-43-33 for server0
[Thu Jun 16 20:36:58 2022][info] target server0: next run: Fri Jun 17 20:16:21 2022 - https://glpi.xxxxxx.com/glpi/
[Thu Jun 16 20:36:58 2022][info] GLPI Agent memory usage: WSS=3411968 PFU=128593920
[Fri Jun 17 07:13:54 2022][info] GLPI Agent service starting
[Fri Jun 17 07:13:54 2022][error] unable to get address for 'glpi.xxxxxx.com': Host desconocido. 
[Fri Jun 17 07:13:54 2022][error] unable to get address for 'glpi.xxxxxx.com': Host desconocido.
[Fri Jun 17 07:13:55 2022][info] [http server] HTTPD service started on port 62354
[Fri Jun 17 07:13:58 2022][info] GLPI Agent memory usage: WSS=3903488 PFU=103862272
[Fri Jun 17 07:13:58 2022][info] target server0: next run: Fri Jun 17 20:16:21 2022 - https://glpi.xxxxxx.com/glpi/
[Fri Jun 17 07:16:08 2022][info] running task Deploy: storage maintenance event
[Fri Jun 17 07:16:10 2022][info] GLPI Agent memory usage: WSS=3325952 PFU=114171904
[Fri Jun 17 16:58:24 2022][info] GLPI Agent exiting (5320)
[Fri Jun 17 16:58:52 2022][info] GLPI Agent service starting
[Fri Jun 17 16:58:54 2022][info] [http server] HTTPD service started on port 62354
[Fri Jun 17 16:58:55 2022][info] GLPI Agent memory usage: WSS=3690496 PFU=105259008
[Fri Jun 17 16:58:55 2022][info] target server0: next run: Fri Jun 17 16:58:52 2022 - https://glpi.xxxxxx.com/glpi/
[Fri Jun 17 16:58:55 2022][info] target server0: server https://glpi.xxxxxx.com/glpi/
[Fri Jun 17 16:58:55 2022][info] sending contact request to server0
[Fri Jun 17 16:58:58 2022][error] [http client] internal response: 500 Can't connect to glpi.xxxxxx.com:443 (Bad file descriptor)
[Fri Jun 17 16:58:58 2022][error] [http client] unexpected content, starting with: Can't connect to glpi.xxxxxx.com:443 (Bad file descriptor)
[Fri Jun 17 16:58:58 2022][error] No answer from server at https://glpi.xxxxxx.com/glpi/
[Fri Jun 17 16:58:58 2022][info] target server0: next run: Fri Jun 17 16:59:58 2022 - https://glpi.xxxxxx.com/glpi/
[Fri Jun 17 16:59:58 2022][info] target server0: server https://glpi.xxxxxx.com/glpi/
[Fri Jun 17 16:59:58 2022][info] sending prolog request to server0
[Fri Jun 17 16:59:59 2022][error] [http client] internal response: 500 Can't connect to glpi.xxxxxx.com:443 (Bad file descriptor)
[Fri Jun 17 16:59:59 2022][error] No answer from server at https://glpi.xxxxxx.com/glpi/
[Fri Jun 17 16:59:59 2022][info] target server0: next run: Fri Jun 17 17:01:59 2022 - https://glpi.xxxxxx.com/glpi/
[Fri Jun 17 16:59:59 2022][info] GLPI Agent memory usage: WSS=3219456 PFU=114831360
[Fri Jun 17 17:01:05 2022][info] running task Deploy: storage maintenance event
[Fri Jun 17 17:01:07 2022][info] GLPI Agent memory usage: WSS=3170304 PFU=121675776
[Fri Jun 17 17:01:59 2022][info] target server0: server https://glpi.xxxxxx.com/glpi/
[Fri Jun 17 17:01:59 2022][info] sending prolog request to server0
[Fri Jun 17 17:01:59 2022][error] [http client] internal response: 500 Can't connect to glpi.xxxxxx.com:443 (Bad file descriptor)
[Fri Jun 17 17:01:59 2022][error] No answer from server at https://glpi.xxxxxx.com/glpi/
[Fri Jun 17 17:01:59 2022][info] target server0: next run: Fri Jun 17 17:05:59 2022 - https://glpi.xxxxxx.com/glpi/
[Fri Jun 17 17:02:11 2022][info] target server0: server https://glpi.xxxxxx.com/glpi/
[Fri Jun 17 17:02:11 2022][info] sending prolog request to server0
[Fri Jun 17 17:02:12 2022][error] [http client] internal response: 500 Can't connect to glpi.xxxxxx.com:443 (Bad file descriptor)
[Fri Jun 17 17:02:12 2022][error] No answer from server at https://glpi.xxxxxx.com/glpi/
[Fri Jun 17 17:02:12 2022][info] target server0: next run: Fri Jun 17 17:10:12 2022 - https://glpi.xxxxxx.com/glpi/
[Fri Jun 17 17:02:12 2022][info] GLPI Agent memory usage: WSS=3162112 PFU=122064896
[Fri Jun 17 17:02:20 2022][info] target server0: server https://glpi.xxxxxx.com/glpi/
[Fri Jun 17 17:02:20 2022][info] sending prolog request to server0
[Fri Jun 17 17:02:20 2022][error] [http client] internal response: 500 Can't connect to glpi.xxxxxx.com:443 (Bad file descriptor)
[Fri Jun 17 17:02:20 2022][error] No answer from server at https://glpi.xxxxxx.com/glpi/
[Fri Jun 17 17:02:20 2022][info] target server0: next run: Fri Jun 17 17:18:20 2022 - https://glpi.xxxxxx.com/glpi/
[Fri Jun 17 17:05:48 2022][info] GLPI Agent exiting (8852)
[Fri Jun 17 17:05:50 2022][info] GLPI Agent service starting
[Fri Jun 17 17:05:50 2022][info] [http server] HTTPD service started on port 62354
[Fri Jun 17 17:05:51 2022][info] GLPI Agent memory usage: WSS=3747840 PFU=104927232
[Fri Jun 17 17:05:51 2022][info] target server0: next run: Fri Jun 17 17:49:17 2022 - https://glpi.xxxxxx.com/glpi/front/inventory.php
[Fri Jun 17 17:06:03 2022][info] target server0: server https://glpi.xxxxxx.com/glpi/front/inventory.php
[Fri Jun 17 17:06:03 2022][info] sending prolog request to server0
[Fri Jun 17 17:06:04 2022][error] [http client] internal response: 500 Can't connect to glpi.xxxxxx.com:443 (Bad file descriptor)
[Fri Jun 17 17:06:04 2022][error] No answer from server at https://glpi.xxxxxx.com/glpi/front/inventory.php
[Fri Jun 17 17:06:04 2022][info] target server0: next run: Fri Jun 17 17:07:04 2022 - https://glpi.xxxxxx.com/glpi/front/inventory.php

### Expected behavior

I expect to connect the agent to the server.

### Operating system

Windows

### GLPI Agent version

1.3

### GLPI version

10.0.1

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.1

### Additional context

[dmidecode-output.txt](https://github.com/glpi-project/glpi-agent/files/8931624/dmidecode-output.txt)

**Comment by g-bougard** [comment]
Hi @yasanchezco 

as the 1.3 release was on 2022-06-16 and your log seems to show there was still a problem before, I don't think for now the problem is really due to the agent upgrade. If it worked before and it was no more working on 2022-06-15, this better means you have a connectivity issue, maybe due to a dns problem if I analyze correctly the agent reported errors.

Anyway, you should in this case change the debug level of the agent to 2. This should give you few more informations related to SSL support. You can even try to temporarily enable the `no-ssl-check` option to see if you have a SSL issue.

**Comment by TheRoby** [comment]
Hi @g-bougard 
I have the same (Bad File descriptor)
It work with 1.1 and 1.2 but not 1.3

with debug level to 2 :
```
[Tue Jun 21 16:33:31 2022][debug] [http server] GET request /now/12345678 from client 172.xxx.xxx.xxx
[Tue Jun 21 16:33:31 2022][debug] [http server] rescheduling next contact for all targets right now
[Tue Jun 21 16:33:31 2022][debug] [http server] response status 200
[Tue Jun 21 16:33:31 2022][info] target server0: server https://xxx.fr/plugins/fusioninventory/
[Tue Jun 21 16:33:31 2022][debug] [http client] Using Compress::Zlib for compression
[Tue Jun 21 16:33:31 2022][info] sending prolog request to server0
[Tue Jun 21 16:33:31 2022][debug2] [http client] sending message:
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <DEVICEID>xxxxxxxxxxx.2022-03-11-14-34-24</DEVICEID>
  <QUERY>PROLOG</QUERY>
  <TOKEN>12345678</TOKEN>
</REQUEST>
[Tue Jun 21 16:33:31 2022][error] [http client] internal response: 500 Can't connect to xxx.fr:443 (Bad file descriptor)
[Tue Jun 21 16:33:31 2022][error] No answer from server at https://xxx.fr/plugins/fusioninventory/
[Tue Jun 21 16:33:31 2022][info] target server0: next run: Tue Jun 21 16:35:31 2022 - https://xxx.fr/plugins/fusioninventory/
[Tue Jun 21 16:33:31 2022][debug] [http server] GET request /status from client 172.xxx.xxx.xxx
[Tue Jun 21 16:33:31 2022][debug] [http server] response status 200
[Tue Jun 21 16:33:36 2022][debug] [http server] GET request /status from client 172.xxx.xxx.xxx
[Tue Jun 21 16:33:36 2022][debug] [http server] response status 200
```

If i check no-ssl-check : 

```
[Tue Jun 21 16:34:21 2022][debug2] https://xxx.fr/plugins/fusioninventory/?action=getConfig&machineid=xxxxxxxxxxxx-2022-03-11-14-34-24&task[Deploy]=2.10
[Tue Jun 21 16:34:21 2022][info] [http client] SSL Client warning: Peer certificate not verified
[Tue Jun 21 16:34:21 2022][info] [http client] SSL Client info: Cert-Issuer: '/C=GB/ST=XX/L=XX/O=XX/CN=Sectigo RSA Organization Validation Secure Server CA', Cert-Subject: '/C=XX/ST=XX/O=XX/OU=IT/CN=*.xxx.fr', Version: 'TLSv1_3', Cipher: 'TLS_AES_256_GCM_SHA384'
[Tue Jun 21 16:34:21 2022][info] [http client] SSL server certificate fingerprint: sha256$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[Tue Jun 21 16:34:21 2022][info] [http client] You can set it in conf as 'ssl-fingerprint' and disable 'no-ssl-check' option to trust that server certificate
```

So i think i need to add the fingerprint... yes ?

Thank you :)

**Comment by g-bougard** [comment]
This is probably not exactly the same problem, but yes you can set `sha256$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` as `ssl-fingerprint` option.
You can also deploy the CA Cert file for `/C=GB/ST=XX/L=XX/O=XX/CN=Sectigo RSA Organization Validation Secure Server CA` issuer and set its path as `ca-cert-file` option.

**Comment by igorvisi** [comment]
Same error after using version 1.3
I downgraded to 1.2. The problem disappeared

**Comment by g-bougard** [comment]
Hi @igorvisi 
please, be more accurate on which same error occurred for you as there still was 2 different errors reported.
If you can also attach an export of agent log running with debug2, this can help to understand if this is the same error.

**Comment by miguelanruiz** [comment]
Hi Guillaume,

Im have been testing installer and i have reached the same problem (See attached log)

Before use no-ssl-check output was: 

`[Thu Jun 23 11:20:05 2022][error] [http client] internal response: 500 Can't connect to glpi.imagunet.com:443 (Bad file descriptor)`

But after put this key as 1, it works and ask something else:
`[Thu Jun 23 11:51:58 2022][info] [http client] You can set it in conf as 'ssl-fingerprint' and disable 'no-ssl-check' option to trust that server certificate`

Best regards,

Annotations:
```
GLPI Agent v1.3
GLPI Inventory v1.0.2
GLPI v10.0.1
```

LOGS-- 
[glpi-agent.log](https://github.com/glpi-project/glpi-agent/files/8969311/glpi-agent.log)

**Comment by g-bougard** [comment]
Hi @miguelanruiz,

I see few error in you agent log not related to SSL problem:
 - an Oracle database inventory issue
 - an Office license scan issue
I've just fixed that issues and you'll be able to test them with the next nightly build.
As I see you're actually a GLPI partner, concerning the Office license, in the case it still doesn't work with next nightly, you may be concerned by #51. If this is the case, can you contact me by email to share few private datas so I can work on the #51 feature request.

About the SSL problem, this is really not a problem. The new 'info' message is telling you you can secure the connection by trusting the server SSL certificate thanks to the new 1.3 feature, the 'ssl-fingerprint' option as you can see in [ssl-fingerprint documentation](https://glpi-agent.readthedocs.io/en/latest/configuration.html#ssl-fingerprint). The info messages also show you're using a Let's Encrypt generated certificate so it should probably be trusted if the agent knows the CA certificate. But maybe this means they are using a newer certificate which may not have been integrated in used Mozilla CA store. A new feature from 1.3 is also to check certificates from the windows store, eventually published through the enterprise keystore...

Anyway, maybe the keystore feature is part of the issue as writing about it triggers me an idea. Can you confirm the SSL access was working like a charm before ? That was indeed not clear for me on all report here. If yes, I now understand the issue as the agent is maybe restricting the trusting to only the certificate available in keystore...

**Comment by g-bougard** [comment]
Hi here,
please try next nightly build as it should fix this issue.

**Comment by miguelanruiz** [comment]
Hi Guillaume,

Thanks for observations i will have in account not related to SSL. As you say, certificate was reissued recently from 10 of June, 
certificate currencty is working good, and some days before 1 of June it was okay with Agent. 

Regarding to your last comment, i put GLPI-Agent-1.4-gitfeb6dc99-x64.msi from Github cause nightly does not looks published yet and everything works nice without problem.

Thank you so much, have a good day

**Comment by g-bougard** [comment]
Just for you information, GLPI-Agent 1.4 has been released and of course includes the fix.

**Comment by miguelanruiz** [comment]
Thank you for information Guillaume
