### ISSUE TITLE
Agent 1.3 server not ready

### ISSUE THREAD

**Issue by VGzsysadm** [glpi-project/glpi-agent#149]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

GLPI-Agent-1.3-x64.msi

Just installing the agent, default mode all time response is:

un 20 11:51:07 2022][info] [http server] HTTPD service started on port 62354
[Mon Jun 20 11:51:08 2022][info] GLPI Agent memory usage: WSS=3768320 PFU=105041920
[Mon Jun 20 11:51:08 2022][info] target local0: next run: Mon Jun 20 12:36:22 2022 - C:\Program Files\GLPI-Agent\
[Mon Jun 20 11:51:08 2022][info] target server0: next run: Mon Jun 20 12:31:39 2022 - http://10.10.101.33/front/inventory.php
[Mon Jun 20 11:51:34 2022][info] local0 is not ready yet, next server contact planned for Mon Jun 20 12:36:22 2022
[Mon Jun 20 11:51:34 2022][info] server0 is not ready yet, next server contact planned for Mon Jun 20 12:31:39 2022

Forcing the sync with the server

glpi-agent -s http://10.10.101.33 -f

[Mon Jun 20 12:01:33 2022][info] [http server] HTTPD service started on port 62354
[Mon Jun 20 12:01:34 2022][info] GLPI Agent memory usage: WSS=3710976 PFU=105336832
[Mon Jun 20 12:01:34 2022][info] target server0: next run: Mon Jun 20 12:31:39 2022 - http://10.10.101.33/front/inventory.php
[Mon Jun 20 12:01:37 2022][info] server0 is not ready yet, next server contact planned for Mon Jun 20 12:31:39 2022
[Mon Jun 20 12:02:21 2022][info] server0 is not ready yet, next server contact planned for Mon Jun 20 12:31:39 2022
[Mon Jun 20 12:02:47 2022][info] local0 is not ready yet, next server contact planned for Mon Jun 20 12:36:22 2022
[Mon Jun 20 12:02:47 2022][info] server0 is not ready yet, next server contact planned for Mon Jun 20 12:31:39 2022
[Mon Jun 20 12:03:11 2022][info] local0 is not ready yet, next server contact planned for Mon Jun 20 12:36:22 2022
[Mon Jun 20 12:03:11 2022][info] server0 is not ready yet, next server contact planned for Mon Jun 20 12:31:39 2022
[Mon Jun 20 12:03:45 2022][info] server0 is not ready yet, but run is forced
[Mon Jun 20 12:03:45 2022][info] target server0: server http://10.10.101.33/front/inventory.php
[Mon Jun 20 12:03:45 2022][info] sending prolog request to server0
[Mon Jun 20 12:03:45 2022][info] server0 answer shows it supports GLPI Agent protocol
[Mon Jun 20 12:03:45 2022][info] running task Inventory
[Mon Jun 20 12:03:45 2022][info] New inventory from DESKTOP-XXXXXXXX-2022-06-20-09-15-39 for server0
[Mon Jun 20 12:03:49 2022][info] running task Deploy: storage maintenance event
[Mon Jun 20 12:03:51 2022][info] GLPI Agent memory usage: WSS=3252224 PFU=119455744
[Mon Jun 20 12:04:28 2022][info] running task ESX
[Mon Jun 20 12:04:28 2022][error] [http client] communication error: 400 Bad Request, Protocol not supported
[Mon Jun 20 12:04:28 2022][info] ESX task not supported by server0
[Mon Jun 20 12:04:28 2022][info] running task Deploy
[Mon Jun 20 12:04:28 2022][error] [http client] communication error: 400 Bad Request, Protocol not supported
[Mon Jun 20 12:04:28 2022][info] Deploy task not supported by server0
[Mon Jun 20 12:04:28 2022][info] running task Collect
[Mon Jun 20 12:04:28 2022][error] [http client] communication error: 400 Bad Request, Protocol not supported
[Mon Jun 20 12:04:28 2022][info] Collect task not supported by server0

Although the computer & software is registered on the GLPI server

### To reproduce

1. Install default agent 1.3
2. Send data to the server http://10.10.101.33/front/inventory.php
3. 

### Expected behavior

Computer and software is being registered.

### Operating system

Linux

### GLPI Agent version

1.3

### GLPI version

10.0.1

**Comment by g-bougard** [comment]
Hi @VGzsysadm 
sorry but I don't see any problem in your output.
By default, the agent won't start immediately an inventory unless you requested to "run now" during the installation. And by default, it will start the inventory during the next hour as your first output is showing.

**Comment by VGzsysadm** [comment]
Hello @g-bougard 
You are right.
Sorry for the inconvenience.
