### ISSUE TITLE
How can I deploy the agent on the domain using command prompt ?

### ISSUE THREAD

**Issue by IlhanYapici** [glpi-project/glpi-agent#15]
I'm trying to replace Fusion Inventory Agent with GLPI Agent with silent installation. I can't figure out what are the arguments though. I've seen in the glpi-agent-deployment.vbs that the SetupLocation uses the link to download the release but there is still no release on GitHub. So I tried to use PsExec to remotely install, and it kinda seems to work beacause it exits with error code 0 but there isn't the glpi service installed. 
Here is what the cmd returns : 
![image](https://user-images.githubusercontent.com/76203025/122212690-6e94b880-cea8-11eb-9d7d-02587f38569b.png)
And here is the command that I used : 
`psexec \\SEXTANS -u ******* -p ******** -h -i "C:\Windows\System32\msiexec.exe" /a "\\eros\commun\Service Informatique\Fusioninventory\GLPI-A-1.0-x64.msi" /quiet RUNNOW=1 EXECMODE=SERVICE SERVER='http://myserver/glpi/plugins/fusioninventory/' NO-SSL-CHECK=1 `
I've seen that one of the arguments used in the vbs script was RUNNOW=1 so I tried to do the same syntax but I guess it's not working. But I need to use the no-ssl-check argument.
I'd be glad if you could help me to make a silent install !

**Comment by g-bougard** [comment]
Hi @IlhanYapici 
we still need to write a MSI install documentation but you're doing in the right way. Indeed you still can run directly the msi with the /quiet option and all required options following using the syntax `OPTION=value` or `OPTION="value"`.
For the list of supported values you can check the script from l. 428 to l. 466:
https://github.com/glpi-project/glpi-agent/blob/develop/contrib/windows/glpi-agent-packaging.pl#L428
There, all reference to values in uppercase are all usable on the command line. As you can see, `RUNNOW` can be used. As other example, you can use `HTTPD_TRUST=127.0.0.1/32`. For no-ssl-check, you must use `NO_SSL_CHECK=1`. Indeed, all "dash" symbols must be replaced by "underscore" symbols. You should probably also use `ADD_FIREWALL_EXCEPTION=1`.

**Comment by g-bougard** [comment]
About the vbs, you should probably be able to use:
```
SetupLocation = "https://nightly.glpi-project.com/glpi-agent"
```
And set `SetupVersion` to `"1.0-gitXXXXYYYY"` where XXXXYYYY is replaced by the git reference available on the nightly build page (but remember only the last 3 nightly builds are kept so the version can disappear in 3 days).

**Comment by IlhanYapici** [comment]
Thank you! I was wondering what value should I set for `TASKS=`, `DEBUG=` and `LOGFILE_MAXSIZE=` ?
I want to fully install the agent with all tasks so I should set `TASKS=FULL` ?

**Comment by g-bougard** [comment]
Hum, no, TASKS is really the `tasks` option for the agent, so a list of tasks to run in a given order.
After a short internet research, it seems you just need to add `ADDLOCAL=ALL` to install all features of a MSI package. Indeed I didn't test this point, sorry. See https://docs.microsoft.com/en-us/windows/win32/msi/addlocal for the official documentation. If I understand well and I'll have to test that, possible values for features are NETINV, DEPLOY, COLLECT and ESX (WOL is still not supported) in a comma separated list.

**Comment by IlhanYapici** [comment]
Alright thank you. 
Meanwhile I tried to install remotely on 2 computers (not both at the same time) with the following command : 
`psexec \\computer -u domain\user -p **** -h -i msiexec /a "\\network\share\agent.msi" /quiet RUNNOW=1 SERVER='https://myserver/glpi/plugins/fusioninventory/' ADD_FIREWALL_EXCEPTION=1` 
One computer was x64 and the other one x86, so I make sure to have both x64 and x86 version of the .msi but when I checked if it was intalled on the computers, the folder GLPI-Agent was installed in _C:\\_ not _C:\Program Files_. And the installation was not complete. What I mean is that there should be _etc_, _logs_, _perl_, _share_ and _var_ folders right ? On both computer there was only _etc_, _perl_ and _share_. Then I checked _services.msc_ and the service GLPI Agent was not here.

EDIT: So I think I found where the problem come from. When I execute the command, it copy the .msi in _C:\\_, and then try to install. So I tried to execute the .msi that was copied on the remote computer but when the installation was almost finished an error occured saying that there was missing perl files.

**Comment by g-bougard** [comment]
Locally, I can install with `/i` option but `/a` is not doing the job. I'm not a windows expert so I'm not sure if this is normal as my compute is not in a domain.
Anyway, I made few other tests with `ADDLOCAL=...` definition. Indeed `ADDLOCAL=ALL` just does what you expect: install all tasks. But you can also list the package features you want and as of now each feature needs the `feat_` prefix against the name I gave earlier as in `ADDLOCAL=feat_NETINV,feat_DEPLOY`.
So all the available features are: `feat_NETINV,feat_COLLECT,feat_DEPLOY,feat_ESX` but this may change in the future as I discover these are not optimal names.
Without `ADDLOCAL`, `feat_COLLECT` and `feat_DEPLOY` are selected.
You can remove a feature after the install running again the installer but with `REMOVE=feat_DEPLOY` for example.

**Comment by IlhanYapici** [comment]
Thank you for all those informations. I'll try `/i` tomorrow. I'll let you know if it works or not.

**Comment by IlhanYapici** [comment]
It works! Thank you so much.
