### ISSUE TITLE
Error on instalation glpi-agent on Oracle Linux 8

### ISSUE THREAD

**Issue by SaukInfraNOC** [glpi-project/glpi-agent#151]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Professional support

I still have but want a public following to help the community

### Is your help request related to a problem?

Yes

### Expected behavior

Next stage is show the line for include the URL default for collection off the data.

### Actions you've considered

I used other methods of instalation but dont working. I used all installation modes.

### Additional context

![image](https://user-images.githubusercontent.com/107886140/174667218-46620e83-cd20-48b0-b307-3673722ceb69.png)

**Comment by g-bougard** [comment]
Hi @SaukInfraNOC 

can you try the latest version released last week and report the output of installation using the `--verbose` option ?

**Comment by SaukInfraNOC** [comment]
Good Afternum for all!

First, i want to thank you for your help. The command --verbose showed the error.

For installation in OS Oracle Linux 8, the dependence for the Perl --set-enable is not 'PowerTools'.

By default, part of installation requires enable PowerTools for ConfigManager.
For exemple, using Percona Mysql for the DB, fallow the command:

![image](https://user-images.githubusercontent.com/107886140/175139571-a35ccdee-bc4c-40db-809a-e30bed3a770b.png)

The command `dnf config-manager --set-enabled powertools` PowerTools is a package of CentOs 7, that eventually don't works on Oracle Linux 8.
It's needed use other package, `dnf config-manager --set-enable ol8_codeready_builder`

It's needed also tho install Perl in server for works: `dnf -y install perl`

After this, running the command `perl glpi-agent-1.2-linux-installer.pl --verbose --install` the Perl search the remaining dependeces needed, converting the command to `dnf -y install glpi-agent-1.2-1.noarch.rpm` solving the script and performing the agent installation.

![image](https://user-images.githubusercontent.com/107886140/175143258-3a7562c8-8d9a-4ddc-b697-0475cf8679d8.png)

![image](https://user-images.githubusercontent.com/107886140/175143378-3f0af143-86f7-4261-8d59-fb892996b594.png)

Thanks for the great help!

**Comment by g-bougard** [comment]
Okay, if I understand well, you fixed your issue by simply running:
```
dnf config-manager --set-enable ol8_codeready_builder
```
in place of:
```
dnf config-manager --set-enabled powertools
```
If you confirm, I'll update the installer to support Oracle Linux distro.

**Comment by SaukInfraNOC** [comment]
Hello @g-bougard 

Yes, to resolve the problem, it's necessery changing dependence to `ol8_codeready_builder` for Oracle Linux 8 with DB Percona Mysql.

**Comment by g-bougard** [comment]
Hi @SaukInfraNOC 
just updated the perl installer in that way. Can you validate it does the job with the next nightly ?
Or if you have time today, you can get the installer from the related packaging GH Actions: [GH Actions run](https://github.com/glpi-project/glpi-agent/actions/runs/2549312726). Just download the Linux-Installer-Build archive artifact and extract the installer from it.

**Comment by SaukInfraNOC** [comment]
Good morning @g-bougard 
I performed the test. The script was updated but only two dependencies were downloaded and the error persists.
I will forward all the dependencies that the command installs, or you can do a test with a zeroed machine.

**Comment by g-bougard** [comment]
Hi @SaukInfraNOC 
I've done a fresh a install of a minimal Oracle Linux 8.6.
I was able to install the agent as the attach comple log of the installation is showing:
[oracle-linux-8.6-install.txt](https://github.com/glpi-project/glpi-agent/files/8976516/oracle-linux-8.6-install.txt)
Maybe something is wrong somewhere, but you need to explain a little bit what goes wrong with your own test.
As the log shows, I only had to install wget (didn't check if curl was available) and perl packages on the minimal install.

**Comment by g-bougard** [comment]
GLPI-Agent v1.4 has been release and includes Oracle Linux 8.6 support with perl installer.
