### ISSUE TITLE
Error on instalation glpi-agent on Oracle Linux 8

### ISSUE THREAD

**Issue by SaukInfraNOC** [glpi-project/glpi-agent#152]
The operating system on which the GLPI agent is running:
Oracle Linux 8

The GLPI agent version you're using and the way you installed it:
1.2

The problem itself, eventually including log extract or agent run output:
Image on attachment.

what you're expecting:
Next stage is show the line for include the URL default for collection off the data.
![error1](https://user-images.githubusercontent.com/107886140/174665844-b81ebf0b-23df-495e-87ec-1bca608a9fa0.png)

**Comment by trasher** [comment]
duplicates #151
