### ISSUE TITLE
AOC 1970W monitors - wrong serial number

### ISSUE THREAD

**Issue by joschi99** [glpi-project/glpi-agent#156]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

We have some AOC 1970 monitor, where GLPI agent 1.2 reports wrong serial number. The XML file from agents reports this data:
```
    <MONITORS>
      <BASE64>AP///////wAF43AZIL0BABkZAQNoKRd4KgzFpFdQoSgNUFS/7gCBwAEBAQEBAQEBAQEBAQEBZiFWqlEAHjBGjzMAmuYQAAAeZiFQsFEAGzBAcDYAmuYQAAAeAAAA/QAyTB48CQAKICAgICAgAAAA/AAxOTcwVwogICAgICAgAFw=</BASE64>
      <CAPTION>1970W</CAPTION>
      <DESCRIPTION>25/2015</DESCRIPTION>
      <MANUFACTURER>AOC International (USA) Ltd.</MANUFACTURER>
      <NAME>Generic PnP Monitor</NAME>
      <PORT>VGA</PORT>
      <SERIAL>0001bd20</SERIAL>
      <TYPE>Generic PnP Monitor</TYPE>
    </MONITORS>
```

Using PS script we get the correct SN:
```
get-wmiobject wmimonitorid -namespace root\wmi|foreach-object{($_.SerialnumberID|foreach-object{[char]$_}) -join ""}
113952
```

The full data are there:
```
get-wmiobject wmimonitorid -namespace root\wmi


__GENUS                : 2
__CLASS                : WmiMonitorID
__SUPERCLASS           : MSMonitorClass
__DYNASTY              : MSMonitorClass
__RELPATH              : WmiMonitorID.InstanceName="DISPLAY\\AOC1970\\4&1a6469cc&0&UID65793_0"
__PROPERTY_COUNT       : 9
__DERIVATION           : {MSMonitorClass}
__SERVER               : PU01500002
__NAMESPACE            : root\wmi
__PATH                 : \\PU01500002\root\wmi:WmiMonitorID.InstanceName="DISPLAY\\AOC1970\\4&1a6469cc&0&UID65793_0"
Active                 : True
InstanceName           : DISPLAY\AOC1970\4&1a6469cc&0&UID65793_0
ManufacturerName       : {65, 79, 67, 0...}
ProductCodeID          : {49, 57, 55, 48...}
SerialNumberID         : {49, 49, 51, 57...}
UserFriendlyName       : {49, 57, 55, 48...}
UserFriendlyNameLength : 13
WeekOfManufacture      : 25
YearOfManufacture      : 2015
PSComputerName         : PU01500002
```

### To reproduce

Do a inventory on a Windows computer with a AOC 1970W monitor attached

### Expected behavior

do have the correct SN

### Operating system

Windows

### GLPI Agent version

1.2

### GLPI version

9.5.7

### GLPIInventory plugin or FusionInventory for GLPI plugin version

9.5+4.1

**Comment by g-bougard** [comment]
Hi @joschi99 
indeed the `0001bd20` S/N which is reported is exactly `113952` in hexadecimal base. So this is the same number, but not reported in the same format.
You're comparing with a powershell output where what would be more accurate would be to compare with the sticker on monitor. And indeed, the relevant value would be also what the manufacturer would request you in a device registration process or during a RMA request.
Also I guess you can modify your PS one-liner to report an hexadecimal for that value instead of an integer in base 10.

So is there really a bug ?

**Comment by joschi99** [comment]
Hi @g-bougard,
the correct number is `113952` and not the hex value. Consider that there is a prefix (FXWF6HA) for the complete number, wich is not set, so the complete correct number for a RMA should be: `FXWF6HA113952`
Could we can add prefix and decimal number as SN for AOC 1970/1970W models?

**Comment by g-bougard** [comment]
This is possible, but I should know how to compute the prefix.
If AOC is always expecting a decimal, I still can update the code to better report a decimal for this manufacturer.

**Comment by joschi99** [comment]
I try to ask AOC for them. I update you asap.
