### ISSUE TITLE
Problem on running WinRM over SSL

### ISSUE THREAD

**Issue by hey0010** [glpi-project/glpi-agent#158]
### Documentation

Yes, I read it

### Solution search

Not applicable

### Professional support

Yes, I know

### Is your help request related to a problem?

I used this command but it didn't work:
```
sudo glpi-remote add winrm://'administrator':'*******'@******:5986 --target server0 --ssl --ssl-cert-file SSL_PS_Remoting.cer
```
I face the following error:
`'winrm://administrator:****@********:5986' check failure: Winrm identify request failure: 500 Status read failed: Connection reset by peer`
I have check port and certificate by powershell and everything is working fine!
any suggestion for this?!

### Expected behavior

please Give a sample for running WinRM on 5986 port, ssl. 

### Actions you've considered

please Give a sample for running WinRM on 5986 port, ssl.

**Comment by g-bougard** [comment]
Hi @hey0010 
I guess you're the guy who asked about that problem on GLPI Telegram channel. Do you have some feed back after I asked you to use `--debug --debug` options ? Do you see some interesting output or can you simply share the output (obfuscating any sensible data) ?

**Comment by hey0010** [comment]
Hi 
Here is the error in debug mode. 
```
glpi-remote add winrm://'********':'**********'@**********:5986 --target server0 --ssl --ssl-cert-file SSL_PS_Remoting.pem --debug
Current vardir: /usr/local/var/glpi-agent
[debug] Logger backend Stderr initialized
[debug] 500 Status read failed: Connection reset by peer
'winrm://***********:****@********:5986' check failure: Winrm identify request failure: 500 Status read failed: Connection reset by peer
```

Here is the test for open port:
```
telnet ********** 5986
Trying ***********...
Connected to **************.
Escape character is '^]'.
```

Here is the test for Powershell:
```
$SessionOption = New-PSSessionOption -SkipCNCheck
Enter-PSSession -Computername *************** -UseSSL -Credential ************* -SessionOption $SessionOption
```

thank you

**Comment by g-bougard** [comment]
Hi @hey0010 
I asked you to add `--debug` 2 times to enable debug2 level. This is required to debug any SSL issue. Here you only used `--debug` 1 time.

**Comment by hey0010** [comment]
Here you’re:
```
sudo glpi-remote add winrm://administrator:aA123456@*******:5986 --target server0 --ssl --ssl-cert-file SSL_PS_Remoting.pem --debug --debug
Current vardir: /var/lib/glpi-agent
[debug] Logger backend Stderr initialized
[debug] 500 read timeout
'winrm://administrator:****@********:5986' check failure: Winrm identify request failure: 500 read timeout
```

I checked the over ssl connection by wireshark and see that the connection is http and not https!
So I add this lines in winrm.pm:
$url->scheme( $self->mode('ssl') ? "https" : "http" );
$url->scheme("https");”

By adding above lines, the ssl connection got ok but another error appeard:
```
sudo glpi-remote add winrm://administrator:aA123456@********:5986 --target server0 --ssl --ssl-cert-file SSL_PS_Remoting.pem --debug --debug
Current vardir: /var/lib/glpi-agent
[debug] Logger backend Stderr initialized

############### scheme:http

############### ssl_set:0

############### url:http://********:5986/wsman/
[debug] 500 Can't connect to **********:5986 (Connection timed out)
'winrm://administrator:****@********:5986' check failure: Winrm identify request failure: 500 Can't connect to *********:5986 (Connection timed out)
```

**Comment by g-bougard** [comment]
One point, you should not have to set port or change the code if you uses `--ssl` option.
Then if you have now a different message now, this means something has changed with the server... and even the error is telling to me the server is no more reachable. Is it up ? I don't understand you the PS test you made yesterday as I don't see any output, did you test it today ?

**Comment by hadim85** [comment]
I

> Here you’re:
> 
> ```
> sudo glpi-remote add winrm://administrator:aA123456@*******:5986 --target server0 --ssl --ssl-cert-file SSL_PS_Remoting.pem --debug --debug
> Current vardir: /var/lib/glpi-agent
> [debug] Logger backend Stderr initialized
> [debug] 500 read timeout
> 'winrm://administrator:****@********:5986' check failure: Winrm identify request failure: 500 read timeout
> ```
> 
> I checked the over ssl connection by wireshark and see that the connection is http and not https! So I add this lines in winrm.pm: $url->scheme( $self->mode('ssl') ? "https" : "http" ); $url->scheme("https");”
> 
> By adding above lines, the ssl connection got ok but another error appeard:
> 
> ```
> sudo glpi-remote add winrm://administrator:aA123456@********:5986 --target server0 --ssl --ssl-cert-file SSL_PS_Remoting.pem --debug --debug
> Current vardir: /var/lib/glpi-agent
> [debug] Logger backend Stderr initialized
> 
> ############### scheme:http
> 
> ############### ssl_set:0
> 
> ############### url:http://********:5986/wsman/
> [debug] 500 Can't connect to **********:5986 (Connection timed out)
> 'winrm://administrator:****@********:5986' check failure: Winrm identify request failure: 500 Can't connect to *********:5986 (Connection timed out)
> ```

I had the same problem.
when I run the following command and then capturing related network traffic, I had found that it did not establish SSL session and just send a http request(instead of https connection over ssl)! 

sudo glpi-remote add winrm://administrator:mypass@remoteMachine --target server0 --ssl --ssl-cert-file SSL_PS_Remoting.pem --debug --debug --debug

Although the server side winrm service over https is up and running on the **remoteMachine** and i have tested it with windows powershell command from other machine. 
The output is as bellow:

Current vardir: /var/lib/glpi-agent
[debug] Logger backend Stderr initialized
[debug] 500 Can't connect to remoteMachine:5985 (Connection timed out)
'winrm://administrator:****@remoteMachine' check failure: Winrm identify request failure: 500 Can't connect to remoteMachine:5985 (Connection timed out)

would you please give me a sample command for winrm over ssl **remoteInventory**?

**Comment by g-bougard** [comment]
Hi @hey0010 & @hadim85 

I'm very sorry, I made a confusion that I just clarified in my though after reading carefully the code.

Actually, the `--ssl` option is only supported for [Inventory Server plugin](https://glpi-agent.readthedocs.io/en/latest/plugins/inventory-server-plugin.html) requests. 

For remoteinventory task, there's another way of asking to use winrm over ssl: You need to specify a mode in the winrm url itself like in this example:
```
sudo glpi-remote add winrm://administrator:mypass@remoteMachine?mode=ssl --target server0 --ssl-cert-file SSL_PS_Remoting.pem --debug --debug 
```

I need to fix the documentation to clarify this feature.

**Comment by hadim85** [comment]
> Hi @hey0010 & @hadim85
> 
> I'm very sorry, I made a confusion that I just clarified in my though after reading carefully the code.
> 
> Actually, the `--ssl` option is only supported for [Inventory Server plugin](https://glpi-agent.readthedocs.io/en/latest/plugins/inventory-server-plugin.html) requests.
> 
> For remoteinventory task, there's another way of asking to use winrm over ssl: You need to specify a mode in the winrm url itself like in this example:
> 
> ```
> sudo glpi-remote add winrm://administrator:mypass@remoteMachine?mode=ssl --target server0 --ssl-cert-file SSL_PS_Remoting.pem --debug --debug 
> ```
> 
> I need to fix the documentation to clarify this feature.

Thanks for your response.
I had tested this command too, but I faced new error which comes bellow.
I't should be noted that the remote machine's Winrm service over ssl is up and I could connect from other windows machine with the provided user credential without any problem(the password did not have complexity for simplification).
would you please tell me what should I do?

```
sudo glpi-remote add winrm://administrator:mypass@winrm-test?mode=ssl --target server0 --ssl-cert-file SSL_PS_Remoting.pem --debug --debug
Current vardir: /var/lib/glpi-agent
[debug] Logger backend Stderr initialized
DEBUG: .../IO/Socket/SSL.pm:3010: new ctx 94650171814480
DEBUG: .../IO/Socket/SSL.pm:762: socket not yet connected
DEBUG: .../IO/Socket/SSL.pm:1177: global error: Undefined SSL object
DEBUG: .../IO/Socket/SSL.pm:1177: global error: Undefined SSL object
DEBUG: .../IO/Socket/SSL.pm:764: socket connected
DEBUG: .../IO/Socket/SSL.pm:787: ssl handshake not started
DEBUG: .../IO/Socket/SSL.pm:829: using SNI with hostname winrm-test
DEBUG: .../IO/Socket/SSL.pm:864: request OCSP stapling
DEBUG: .../IO/Socket/SSL.pm:880: set socket to non-blocking to enforce timeout=10
DEBUG: .../IO/Socket/SSL.pm:894: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:897: done Net::SSLeay::connect -> -1
DEBUG: .../IO/Socket/SSL.pm:907: ssl handshake in progress
DEBUG: .../IO/Socket/SSL.pm:917: waiting for fd to become ready: SSL wants a read first
DEBUG: .../IO/Socket/SSL.pm:937: socket ready, retrying connect
DEBUG: .../IO/Socket/SSL.pm:894: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:2864: ok=1 [0] /CN=WINRM-TEST/CN=WINRM-TEST
DEBUG: .../IO/Socket/SSL.pm:1840: scheme=www cert=94650174261808
DEBUG: .../IO/Socket/SSL.pm:1850: identity=winrm-test cn=WINRM-TEST alt=2 WINRM-TEST 2 172.******

DEBUG: .../IO/Socket/SSL.pm:2911: did not get stapled OCSP response
DEBUG: .../IO/Socket/SSL.pm:897: done Net::SSLeay::connect -> -1
DEBUG: .../IO/Socket/SSL.pm:907: ssl handshake in progress
DEBUG: .../IO/Socket/SSL.pm:917: waiting for fd to become ready: SSL wants a read first
DEBUG: .../IO/Socket/SSL.pm:937: socket ready, retrying connect
DEBUG: .../IO/Socket/SSL.pm:894: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:897: done Net::SSLeay::connect -> 1
DEBUG: .../IO/Socket/SSL.pm:952: ssl handshake done
DEBUG: .../IO/Socket/SSL.pm:3059: free ctx 94650171814480 open=94650171814480
DEBUG: .../IO/Socket/SSL.pm:3063: free ctx 94650171814480 callback
DEBUG: .../IO/Socket/SSL.pm:3070: OK free ctx 94650171814480
[debug] [http client] authentication required, submitting credentials
[error] [http client] authentication required, wrong credentials
[debug] 401 Unauthorized
'winrm://administrator:**@winrm-test?mode=ssl' check failure: Winrm identify request failure: 401 Unauthorized
```

**Comment by g-bougard** [comment]
Here you have a clear error saying you're not authorized to use winrm on that remote platform with user and password you gave.
If you have a password with special chars, you still can try to set it in the PASSWORD environment variable and not in the winrm URL.
And you must double-check your user/pass is authorized for winrm on the remote computer.

**Comment by hadim85** [comment]
My password did not have any special character for simplification(but it may have in production environment).
But as you have told, I also check with PASSWORD environment variable.|
below you can see the results:
![glpi-remote add winrm over ssl](https://user-images.githubusercontent.com/69196623/178487535-7381ff34-9a94-46b8-ac27-fec4bbac5efe.JPG)

I double checked the user/pass from another windows machine and all things was OK. 
below you can see the results(check winrm connection from a windows machine to the same machine with the same user/pass):

![powershell_winrm](https://user-images.githubusercontent.com/69196623/178487914-f8b15156-316a-4c64-ac42-edf8c1af380f.jpg)

**Comment by g-bougard** [comment]
Now as the error is "unauthorized", this may just mean this computer is not authorized to access this machine via winrm. Can you check if you have a winrm restriction on the targeted computer ?

**Comment by hadim85** [comment]
> Now as the error is "unauthorized", this may just mean this computer is not authorized to access this machine via winrm. Can you check if you have a winrm restriction on the targeted computer ?

As  you can see in the entitled picture, I can connect to winrm service from oanother windows machine with that user/pass, but I see the error while trying to add winrm remote machine from glpi-agent. 
Iis there any specific setting or policy for winrm that I have to set on the remote machine for enabling winrm from glpi-agent? The general policy/permissions  is OK and I can connect to this machine with same user/pass credential from another windows machine.

**Comment by g-bougard** [comment]
@hadim85 I'm sorry but I'm not an expert of winrm security setup. You'll have to get help on that subject on another place and eventually share here a solution.

**Comment by g-bougard** [comment]
Hi @hadim85
to be sure I didn't miss anything, I just managed to setup a windows 10 server for winrm over SSL. And it works.
This was not easy as official documentation is really bad for this case.
Anyway can you share your winrm config reported with `winrm get winrm/config` and `winrm enumerate winrm/config/listener` commands ?

**Comment by g-bougard** [comment]
And even, I still have an idea... you should not have "Basic authentication" enabled.
If this is the case, just run as administrator: `winrm set winrm/config/service/auth @{Basic="true"}`

**Comment by g-bougard** [comment]
Closing without anymore feedback.
