### ISSUE TITLE
Inventory frequency (in hours)

### ISSUE THREAD

**Issue by whamulti** [glpi-project/glpi-agent#162]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

I'm using GLPi-Agent 1.4 on Windows 10, on GLPi the Inventory update frequency is every 1 hour and it's not updating
![msedge_dia_01_mes_07_162](https://user-images.githubusercontent.com/80924754/176952358-d1af2b37-a6e9-4751-bc49-0595e8e05dee.jpg)

### To reproduce

http://10.2.17.42/glpi/front/inventory.conf.php

### Expected behavior

Inventory has to be updated every 1 hour

### Operating system

Linux

### GLPI Agent version

1.3

### GLPI version

10.0.1

**Comment by g-bougard** [comment]
Hi @ricardo98349 

please don't open the same exactly issue on glpi-project/glpi repo as glpi-project/glpi#12116 and here unless you see a specific problem with glpi-agent.

Here you even don't share any agent log in debug2 level showing if agent is doing something wrong.

To me the agent is just following the expiration the server is sending.
