### ISSUE TITLE
Les ordinateurs ne remontent pas

### ISSUE THREAD

**Issue by JMROC85** [glpi-project/glpi-agent#169]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Is your help request related to a problem?

J'installe l'agent GLPI-Agent-1.4-x64.msi sur une machine Windows.
Sur cette machine, dans un navigateur je tape : localhost:62354
Je clique sur Force an inventory
Rien ne remonte dans mon serveur GLPI (V. GLPI 10.0.0-rc3 Copyright (C) 2015-2022 Teclib' and contributors]) !!!???

Quel est le problème ? un oubli dans le serveur GLPI (qui semble très bien fonctionner) ?

Merci beaucoup pour vos réponses,
Jean-Marc

### Expected behavior

J'attendais la remontée du PC dans ordinateurs de mon serveur GLPI

### Actions you've considered

J'ai modifié les chemins de remote control de l'agent :
`https://172.16.10.106/` : Thu Jul 7 15:49:36 2022 (et http au lieu de https)
`https://172.16.10.106/html/glpi/front/inventory.php` : Thu Jul 7 15:49:40 2022 (et http au lieu de https)
`https://172.16.10.106/glpi/front/inventory.php` : Thu Jul 7 15:49:33 2022 (et http au lieu de https)

**Comment by g-bougard** [comment]
Hi @JMROC85 

please, for community support in french, please use the forum: https://forum.glpi-project.org/

As you probably have a self-signed certificate on server-side as you're accessing your glpi on server ip, for ssl support, you can use ssl-fingerprint option to permit the agent to trust the server certificate. You can find the value to use if you enable just one time for a successful server contact the no-ssl-check option as you'll see the value to use in log file.

What is your URL when you're accessing your GLPI ?
Can you check the agent log for any error ?

**Comment by g-bougard** [comment]
Closing without issuer feedback.
