### ISSUE TITLE
How to install the agent on MacOS (intel version)

### ISSUE THREAD

**Issue by IlhanYapici** [glpi-project/glpi-agent#17]
I know how to install the FusionInventory Agent, I can modify the agent.cfg then install the package and it works perfectly. But It seems that it's not the same process for the GLPI Agent. How can I configure the agent ?

EDIT: if this information can help, one device is a Mac Pro on MacOS X El Capitan and the other one is a iMac Pro on MacOS Big Sur.

**Comment by g-bougard** [comment]
Hi @IlhanYapici 
the process for FusionInventory Agent was to modify the agent.cfg in the .pkg file if I remember well. Indeed, I didn't test that possibility with glpi-agent installer.
Anyway, when you install GLPI Agent on MacOSX, it is installed under `/Applications/GLPI-Agent.app`. From this folder, you should find the `etc` subfolder but also the `etc/conf.d` subfolder.
You should then create a ".cfg" file under `etc/conf.d` with only the values you want to change, for instance, at least `server = https/you-glpi-server/plugins/fusioninventory`.
Any .cfg file under `/Applications/GLPI-Agent.app/etc/conf.d` will be included and any legit value will override the default config.
The big advantage here is you won't have to reconfigure the agent when upgrading to a newer GLPI Agent version.

**Comment by IlhanYapici** [comment]
I tried what you told me but it doesn't work. I created a `agent.cfg` file in the `etc/conf.d` subfolder, I stopped and started the service and tried to access localhost:62354 from safari but it can't load the page. I also restarted the Mac but still nothing work.

EDIT: the agent send the information to the server, I see the Mac in the Computer tab but I can't access to `localhost:62354`

**Comment by g-bougard** [comment]
Okay, I found an issue on MacOSX build with a recently merged feature. This is related to the new `vardir` option support.
Indeed the agent doesn't find the expected vardir by itself.
As a temporary work-around, you can edit your dedicated **.cfg** config file and set **vardir** to the expected default:
```
vardir = /Applications/GLPI-Agent.app/var
```

**Comment by IlhanYapici** [comment]
It works. Thank you.
