### ISSUE TITLE
Wakeonlan

### ISSUE THREAD

**Issue by guinfox** [glpi-project/glpi-agent#170]
### Documentation

Not applicable

### Solution search

Not applicable

### Professional support

I still have but want a public following to help the community

### Is your help request related to a problem?

I'm trying to wake up a station through wake on lan and it's not working, I did it through fusion inventory in version 9.5, but I couldn't do it in glpi inventory. Does this function work?

### Expected behavior

use wakeonlan to wake up devices on the local network

### Actions you've considered

I checked the agent settings and everything seems ok

**Comment by guinfox** [comment]
![image](https://user-images.githubusercontent.com/107438460/177878847-eed33a48-885b-42ef-9eea-0ca9448bd427.png)

I'm using the PC treinamento to wakeup the pc ADM002.

the status is ok, but it does not return the status and does not turn on the pc

**Comment by g-bougard** [comment]
Hi @guinfox 

can you report the OS level used where the agent is installed ? This can actually work only with linux based systems. So if you really need WOL, please dedicate a linux agent. I didn't focused on supporting WOL on windows as this is a deprecated technology in modern infrastructures.

You still can also use a FI agent just for that purpose if this still works.

**Comment by guinfox** [comment]
Hello, I'm using agents on windows 11. Is that why?

**Comment by g-bougard** [comment]
Yes, this is the reason. It's a pain on windows to build the required perl libraries. Also as the required system libraries are not opensource, we can't provide them.
So can you try with an agent on a linux system ?
