### ISSUE TITLE
Antivirus: Missing Version for TrendMicro

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [glpi-project/glpi-agent#171]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

I'm testing GLPI-Agent 1.3 and missing the Version of the currently installed Version of Trendmicro.

![grafik](https://user-images.githubusercontent.com/25504254/177942479-e0f39b1c-3c11-4184-866d-fce5fea63d2d.png)

### To reproduce

1. Using GLPI-Agent 1.3, make an inventory.
2. Select a Computer => Antivirus
3. Look ;-)

### Expected behavior

Showing the Version ov the currently installed Trend-Micro Agent

### Operating system

Windows

### GLPI Agent version

1.3

### GLPI version

10.0.1

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

Not shure. glpi native without plugin

**Comment by g-bougard** [comment]
Hi @vollkommenIrrelevant 

opening an administrative console and chaging directory to the glpi-agent installation folder, can you report the output of the following command obfuscating any sensible data:
```
glpi-inventory --partial antivirus --debug --debug
```

But I think this AV is just actually not supported. Have you any knowledge on how requesting such info on the system ?

**Comment by vollkommenIrrelevant** [comment]
> Hi @vollkommenIrrelevant
> 
> opening an administrative console and chaging directory to the glpi-agent installation folder, can you report the output of the following command obfuscating any sensible data:
> 
> ```
> glpi-inventory --partial antivirus --debug --debug
> ```
![grafik](https://user-images.githubusercontent.com/25504254/177949389-8e76d3d0-6f9c-4999-8423-8fbcacc0e483.png)
> 
> But I think this AV is just actually not supported. Have you any knowledge on how requesting such info on the system ?

I found a solution for TrendMicro Worry Free Business. I was able to get the base Version of the agent via wmiobject:
Get-WmiObject Win32_Product
![grafik](https://user-images.githubusercontent.com/25504254/177951198-f80e31c5-e030-4f61-be70-07b37c89cda8.png)

The current Version can be read from registry. Not shure if it is a good solution:
For x86 OS: HKEY_LOCAL_MACHINE\SOFTWARE\TrendMicro\PC-cillinNTCorp\CurrentVersion\Misc.\BuildNum
For x64 OS: HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\TrendMicro\PC-cillinNTCorp\CurrentVersion\Misc.\BuildNum
![grafik](https://user-images.githubusercontent.com/25504254/177956716-15618d54-4780-4d44-b072-8706b37c0f9d.png)

But I found no solution for reading the virus pattern. The Value from the gui is not the same from the registry
![grafik](https://user-images.githubusercontent.com/25504254/177956535-e84a7a9d-a366-4e03-8cc2-26010b4eab35.png)

Only the date may be usable
![grafik](https://user-images.githubusercontent.com/25504254/177956909-2500322c-4dd2-42d2-8bcb-80aff1e3116e.png)

**Comment by g-bougard** [comment]
Hi @vollkommenIrrelevant 

can you try next nightly tomorrow as 10f8a48 add support for Trend Micro Security Agent and report if it's okay for you ?

I managed to installed this AV agent on a test machine and found more interesting values in registry. So today I got:
```
    ...
    "antivirus": [
      {
        "base_version": "17.679.00",
        "enabled": true,
        "guid": "{AFFAE026-36BF-4CDC-A29D-F1E44465AA4A}",
        "name": "Trend Micro Security Agent",
        "company": "Trend Micro Inc.",
        "uptodate": true,
        "version": "20.0.2035"
      },
      ...
    ],
    ...
```

**Comment by vollkommenIrrelevant** [comment]
> Hi @vollkommenIrrelevant
> 
> can you try next nightly tomorrow as [10f8a48](https://github.com/glpi-project/glpi-agent/commit/10f8a4844d185533956376f03a4d2e345d6bfb53) add support for Trend Micro Security Agent and report if it's okay for you ?

Great, i will test tomorrow!

**Comment by vollkommenIrrelevant** [comment]
> > Hi @vollkommenIrrelevant
> > can you try next nightly tomorrow as [10f8a48](https://github.com/glpi-project/glpi-agent/commit/10f8a4844d185533956376f03a4d2e345d6bfb53) add support for Trend Micro Security Agent and report if it's okay for you ?
> 
> Great, i will test tomorrow!

Working like it should, thank you!
