### ISSUE TITLE
glpi agent compatibility

### ISSUE THREAD

**Issue by kintaro1981** [glpi-project/glpi-agent#172]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Professional support

Yes, I know

### Expected behavior

I would like to know if GLPI Agent is compatible with GLPI 9.5.

### Actions you've considered

I don't have a test env so I didn't tried my self.

**Comment by g-bougard** [comment]
Hi @kintaro1981 
yes it is as you should have seen it in documentation and in release news ;-)
