### ISSUE TITLE
Make Perl installation script versionless

### ISSUE THREAD

**Issue by ghost** [glpi-project/glpi-agent#174]
### Documentation

Yes, I read it

### Professional support

Yes, I know

### Is your feature request related to a problem?

We use a script to install every necessary to our new clients. With every new release of the GLPI agent, we have to adjust the download path in order to replace the version number. 

### Expected behavior

I would like to have a versionless download path, so we don't have to adjust the path in our scripts every time a new version is released.

### Alternatives you've considered

I don't see any alternative beside of adjust the path every time.

**Comment by g-bougard** [comment]
Hi @tzaspel-finatix 

as alternative, you may host the require package on a dedicated server so:
 - you decide which version to install, and so you can even revert an upgrade easily in the case this is necessary,
 - you use your own URL,

as another alternative, you can just host a simple text file which tells your script which version to download.

as even another alternative, you can request github site to discover lastest release. On linux, such a request gives the latest version number:
```
[gbougard@dev glpi-agent]$ curl -s https://api.github.com/repos/glpi-project/glpi-agent/releases/latest | jq ".. .tag_name? // empty"
"1.4"
```
`https://api.github.com/repos/glpi-project/glpi-agent/releases/latest` gives a lot of information, even uri to download packages.
You should be able to adapt your script to request "latest" online API to your script.

**Comment by ghost** [comment]
Hi @g-bougard,

Thank you for your ideas! I'll implement it asap.
