### ISSUE TITLE
[error] [http server] unknown path:

### ISSUE THREAD

**Issue by mrtemp2** [glpi-project/glpi-agent#175]
### Documentation

Not applicable

### Solution search

Not applicable

### Professional support

Still not applicable

### Is your help request related to a problem?

Greeting.
when starting a new network scan with ip rang and actor where glpi-agent 1.4  installed i get the following error and nothing happen
this is the log file of the glpi-agent 
```
[Mon Jul 11 11:47:36 2022][info] GLPI Agent service starting
[Mon Jul 11 11:47:37 2022][info] [http server] HTTPD service started on port 62354
[Mon Jul 11 11:47:39 2022][info] GLPI Agent memory usage: WSS=3813376 PFU=105193472
[Mon Jul 11 11:47:39 2022][info] target server0: next run: Mon Jul 11 12:17:36 2022 - http://127.0.0.1/glpi/front/inventory.php
[Mon Jul 11 11:47:53 2022][info] target server0: server http://127.0.0.1/glpi/front/inventory.php
[Mon Jul 11 11:47:53 2022][info] sending prolog request to server0
[Mon Jul 11 11:47:53 2022][info] server0 answer shows it supports GLPI Agent protocol
[Mon Jul 11 11:47:54 2022][info] running task Deploy
[Mon Jul 11 11:47:54 2022][error] [http client] communication error: 400 Bad Request, Protocol not supported
[Mon Jul 11 11:47:54 2022][info] Deploy task not supported by server0
[Mon Jul 11 11:47:55 2022][info] running task Inventory
[Mon Jul 11 11:47:55 2022][info] New inventory from DESKTOP-C5C6TS8.UNIFACTOR.INTRA-2022-07-11-11-47-35 for server0
[Mon Jul 11 11:48:38 2022][info] running task ESX
[Mon Jul 11 11:48:38 2022][error] [http client] communication error: 400 Bad Request, Protocol not supported
[Mon Jul 11 11:48:38 2022][info] ESX task not supported by server0
[Mon Jul 11 11:48:39 2022][info] running task Collect
[Mon Jul 11 11:48:39 2022][error] [http client] communication error: 400 Bad Request, Protocol not supported
[Mon Jul 11 11:48:39 2022][info] Collect task not supported by server0
[Mon Jul 11 11:48:40 2022][info] target server0: next run: Mon Jul 11 12:47:01 2022 - http://127.0.0.1/glpi/front/inventory.php
[Mon Jul 11 11:48:40 2022][info] GLPI Agent memory usage: WSS=3424256 PFU=152371200
[Mon Jul 11 11:49:49 2022][info] running task Deploy: storage maintenance event
[Mon Jul 11 11:49:49 2022][info] GLPI Agent memory usage: WSS=3391488 PFU=158932992
[Mon Jul 11 11:50:37 2022][error] [http server] unknown path: -%A9$+%D8
```

### Expected behavior

i created a task as in the previous version of glpi 9.5 with fusioninventory and it works fine

### Actions you've considered

the task created in an older version of glpi 9.5 and fusioninventory and it work perfect but in the new version i get this problem.

### Additional context

no context

**Comment by g-bougard** [comment]
Hi @mrtemp2 

the `[http server] unknown path: -%A9$+%D8` line is just telling a http client is requesting a wrong `-%A9$+%D8` path to the agent on its embedded http server. You can enable debug or debug2 mode to discover the remote client ip if you really want to know what is this client.

For your starting a task problem, please read the documentation as your server url is probably wrong:
https://glpi-agent.readthedocs.io/en/latest/configuration.html#server
