### ISSUE TITLE
package "Win32::API"

### ISSUE THREAD

**Issue by bigred38** [glpi-project/glpi-agent#176]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Is your help request related to a problem?

On a Windows 10, I'm try to run manualy agent-glpi.bat, but...

### Expected behavior

```
C:\Program Files\GLPI-Agent>glpi-agent.bat
Execution failure:.
Can't locate object method "new" via package "Win32::API" at C:/Program Files/GLPI-Agent/perl/agent/GLPI/Agent/Tools/Hostname.pm line 54.
```

### Actions you've considered

```
C:\Program Files\GLPI-Agent>echo %PATH%
C:\ProgramData\Oracle\Java\javapath;D:\OneproD\XPR\o10gpe\bin;D:\OneproD\XPR\o10gpe;D:\OneproD\XPR\BIP\jre\1.4.2\bin\client;D:\OneproD\XPR\BIP\jre\1.4.2\bin;D:\OneproD\XPR\odev6i17\bin;C:\Windows\system32;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\PuTTY\;D:\OneproD\XPR\odev6i17;D:\OneproD\XPR\odev6i17\jdk\bin;D:\OneproD\XPR\srv\dll;D:\OneproD\XPR\cli\dll;D:\OneproD\XPR\cli\bin;C:\Program Files\GLPI-Agent\perl;C:\Python\Python35\Scripts\;C:\Python\Python35\;C:\Users\DTG_ACQ\AppData\Local\Microsoft\WindowsApps
```

**Comment by g-bougard** [comment]
Hi @bigred38 

this is more probably a bug triggered in your specific context. To understand when this happens, can you share the output of the following command and option run from an administrative console:
```
C:\Program Files\GLPI-Agent>glpi-agent.bat --logger=stderr --debug --debug
```

**Comment by g-bougard** [comment]
Have you also an error when running:
```
C:\Program Files\GLPI-Agent>perl\bin\glpi-agent.exe -Iperl\agent -MGLPI::Agent::Tools::Hostname -e "print getHostname()"
```
?

**Comment by g-bougard** [comment]
Can you also report the output of:
```
C:\Program Files\GLPI-Agent>perl\bin\glpi-agent.exe -MWin32::API -MData::Dumper -e "print Dumper(\%INC)"
```
?

**Comment by bigred38** [comment]
> Can you also report the output of:
> 
> ```
> C:\Program Files\GLPI-Agent>perl\bin\glpi-agent.exe -MWin32::API -MData::Dumper -e "print Dumper(\%INC)"
> ```
> 
> ?

Weak references are not implemented in the version of perl at C:/Program Files/GLPI-Agent/perl/vendor/lib/Win32/API.pm line 40
BEGIN failed--compilation aborted at C:/Program Files/GLPI-Agent/perl/vendor/lib/Win32/API.pm line 40.
Compilation failed in require.
BEGIN failed--compilation aborted.

**Comment by bigred38** [comment]
> Hi @bigred38
> 
> this is more probably a bug triggered in your specific context. To understand when this happens, can you share the output of the following command and option run from an administrative console:
> 
> ```
> C:\Program Files\GLPI-Agent>glpi-agent.bat --logger=stderr --debug --debug
> ```
[debug] Logger backend Stderr initialized
[debug] GLPI Agent (1.4)
[debug] Configuration directory: C:/Program Files/GLPI-Agent/etc
[debug] Data directory: C:/Program Files/GLPI-Agent/share
[debug] Storage directory: C:\Program Files\GLPI-Agent\var
[debug] Lib directory: C:/Program Files/GLPI-Agent/perl/agent
[error] No target defined, aborting

But I defined a target

**Comment by bigred38** [comment]
> glpi-agent.exe -Iperl\agent -MGLPI::Agent::Tools::Hostname -e "print getHostname()"

```
Can't locate GLPI/Agent/Tools/Hostname.pm in @INC (you may need to install the GLPI::Agent::Tools::Hostname module) (@INC contains: perl\agent D:\OneproD\XPR\o10gpe\perl\5.8.3\lib\MSWin32-x86 D:\OneproD\XPR\o10gpe\perl\5.8.3\lib D:\OneproD\XPR\o10gpe\perl\5.8.3\lib\MSWin32-x86 D:\OneproD\XPR\o10gpe\perl\site\5.8.3 D:\OneproD\XPR\o10gpe\perl\site\5.8.3\lib D:\OneproD\XPR\o10gpe\sysman\admin\scripts D:\OneproD\XPR\o10gpe\perl\5.8.3\lib\MSWin32-x86 D:\OneproD\XPR\o10gpe\perl\5.8.3\lib D:\OneproD\XPR\o10gpe\perl\5.8.3\lib\MSWin32-x86 D:\OneproD\XPR\o10gpe\perl\site\5.8.3 D:\OneproD\XPR\o10gpe\perl\site\5.8.3\lib D:\OneproD\XPR\o10gpe\sysman\admin\scripts C:/Program Files/GLPI-Agent/perl/site/lib C:/Program Files/GLPI-Agent/perl/vendor/lib C:/Program Files/GLPI-Agent/perl/lib).
BEGIN failed--compilation aborted.
```

**Comment by bigred38** [comment]
I only have this problem on one computer...

**Comment by bigred38** [comment]
Nobody?

**Comment by g-bougard** [comment]
> > glpi-agent.exe -Iperl\agent -MGLPI::Agent::Tools::Hostname -e "print getHostname()"
> 
> ```
> Can't locate GLPI/Agent/Tools/Hostname.pm in @INC (you may need to install the GLPI::Agent::Tools::Hostname module) (@INC contains: perl\agent D:\OneproD\XPR\o10gpe\perl\5.8.3\lib\MSWin32-x86 D:\OneproD\XPR\o10gpe\perl\5.8.3\lib D:\OneproD\XPR\o10gpe\perl\5.8.3\lib\MSWin32-x86 D:\OneproD\XPR\o10gpe\perl\site\5.8.3 D:\OneproD\XPR\o10gpe\perl\site\5.8.3\lib D:\OneproD\XPR\o10gpe\sysman\admin\scripts D:\OneproD\XPR\o10gpe\perl\5.8.3\lib\MSWin32-x86 D:\OneproD\XPR\o10gpe\perl\5.8.3\lib D:\OneproD\XPR\o10gpe\perl\5.8.3\lib\MSWin32-x86 D:\OneproD\XPR\o10gpe\perl\site\5.8.3 D:\OneproD\XPR\o10gpe\perl\site\5.8.3\lib D:\OneproD\XPR\o10gpe\sysman\admin\scripts C:/Program Files/GLPI-Agent/perl/site/lib C:/Program Files/GLPI-Agent/perl/vendor/lib C:/Program Files/GLPI-Agent/perl/lib).
> BEGIN failed--compilation aborted.
> ```

Did you really run this from the glpi-agent installation folder ? It seems not to me.

**Comment by g-bougard** [comment]
> > > glpi-agent.exe -Iperl\agent -MGLPI::Agent::Tools::Hostname -e "print getHostname()"
> > 
> > 
> > ```
> > Can't locate GLPI/Agent/Tools/Hostname.pm in @INC (you may need to install the GLPI::Agent::Tools::Hostname module) (@INC contains: perl\agent D:\OneproD\XPR\o10gpe\perl\5.8.3\lib\MSWin32-x86 D:\OneproD\XPR\o10gpe\perl\5.8.3\lib D:\OneproD\XPR\o10gpe\perl\5.8.3\lib\MSWin32-x86 D:\OneproD\XPR\o10gpe\perl\site\5.8.3 D:\OneproD\XPR\o10gpe\perl\site\5.8.3\lib D:\OneproD\XPR\o10gpe\sysman\admin\scripts D:\OneproD\XPR\o10gpe\perl\5.8.3\lib\MSWin32-x86 D:\OneproD\XPR\o10gpe\perl\5.8.3\lib D:\OneproD\XPR\o10gpe\perl\5.8.3\lib\MSWin32-x86 D:\OneproD\XPR\o10gpe\perl\site\5.8.3 D:\OneproD\XPR\o10gpe\perl\site\5.8.3\lib D:\OneproD\XPR\o10gpe\sysman\admin\scripts C:/Program Files/GLPI-Agent/perl/site/lib C:/Program Files/GLPI-Agent/perl/vendor/lib C:/Program Files/GLPI-Agent/perl/lib).
> > BEGIN failed--compilation aborted.
> > ```
> 
> Did you really run this from the glpi-agent installation folder ? It seems not to me.

Well, I missed you seem to have another perl installation on your system under `D:\OneproD\XPR\o10gpe` as the `@INC` is showing a lot of paths. I can guess you probably have **PERL5LIB** environment variable defined. This should not be a problem for the service, but it seems this is while running from the commandline.

Please check your environment variables and just try to unset any PERL* one before running the agent from the command line.
