### ISSUE TITLE
Generate ticket after change of the hardware

### ISSUE THREAD

**Issue by fernandobayit** [glpi-project/glpi-agent#178]
### Documentation

Yes, I read it

### Professional support

Still not applicable

### Expected behavior

Whether it would be possible to generate a ticket/issue/change when there is a hardware change.

### Alternatives you've considered

N/A

**Comment by g-bougard** [comment]
Hi @fernandogobah 

sorry, this is not the right place for such question (even not directly related to glpi-agent project), it should be asked on the forum: https://forum.glpi-project.org
