### ISSUE TITLE
Deploy GLPI agent to client that user don't have local admin privilege

### ISSUE THREAD

**Issue by wikilike7** [glpi-project/glpi-agent#180]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Professional support

Still not applicable

### Is your help request related to a problem?

Hi:

**Backend:**
1. Our OS is Windows, I want to deploy GLPI Agent to all our clients.
2. Users have no local admin privileges

**What we do**
1. And we plan to post it via GPO, but GPO's way can't add parameters like SERVER=xxxx.
2. If we deploy Agent via vb script, users have no privileges so they can't install it.

### Expected behavior

1. I want to add SERVER=xxx to the MSI package, can I do this?
2. or do you have any suggestions?

### Actions you've considered

None

**Comment by wikilike7** [comment]
Anyone can help ? please

**Comment by ntinti** [comment]
Same problem. Without admin rights it's a mess

**Comment by vollkommenIrrelevant** [comment]
I did intial deploy the msi file to existing computer with our own deploymenttool, params could be find here: https://glpi-agent.readthedocs.io/en/latest/installation/windows-command-line.html#command-line-parameters

For new computer we made a shortcut (wih the params) - so one doubleclick and istallation is done...

Ps. Without Adminrights wasn't able to get the vbs via gpo working...

**Comment by kintaro1981** [comment]
@wikilike7 try to modify the msi with Orca

**Comment by g-bougard** [comment]
Hi there, I'm definitively not a windows admin, but isn't it possible to deploy a registry key via GPO ? If yes, just deploy the expect config under `HK_LM\Softwares\GLPI-Agent` and install the agent after: it will discover the configuration during installation.

**Comment by vollkommenIrrelevant** [comment]
> 
@g-bougard 
It's possible to deploy registry keys via GPO, great Idea. I'm not able to check this because we found a other solution for this...

**Comment by jmchrc** [comment]
You can use batch file  and scheduled task with "SYSTEM" account to deploy your glpi agent without admin account


This script tests the existence of fusioninventory uninstalls it if necessary, installs GLPI-AGENT if it is not installed, if it is already installed it then tests the installed version compared to the update that you place in C:\temp \GLPI to see if it updates or not.

!!Can be improved!!  

@echo off
REM Test Fusion Inventory (désinstallation si existant)
if exist "C:\Program Files\FusionInventory-Agent\Uninstall.exe" (
"C:\Program Files\FusionInventory-Agent\Uninstall.exe" /S
)

REM Récupération du MSI d'installation
FOR /R "C:\temp\GLPI" %%f IN (*.msi) DO set fichier=%%f

REM Si l'agent GLPI existe déja goto :VERSION Sinon installation de base
if exist "C:\Program Files\GLPI-Agent\glpi-agent.bat" (
goto VERSION
) ELSE (
goto INSTALL
)

REM Récupération de la version actuellement installée
:VERSION
REM Sélection du fichier version
for /f "tokens=4 delims= " %%i  in ('FIND /I "version" "C:\Program Files\GLPI-Agent\perl\agent\GLPI\Agent\Version.pm"') do set retour=%%i
REM découpe pour ne récupérer que la version
for /f "tokens=1 delims= " %%a  in (%retour%) do set version=%%a

REM Récupération de la version du MSI 
set update=%fichier:~47,-8%

REM Si MSI > à la version installée goto UPDATE sinon goto FIN
IF %version% LSS %update% (
goto INSTALL
) ELSE (
goto FIN
)
REM Installation
:INSTALL
%fichier% /quiet SERVER=https://yourserver QUICKINSTALL=1 ADDLOCAL=ALL EXECMODE=1 DELAYTIME=15 ADD_FIREWALL_EXCEPTION=1 RUNNOW=1 TAG=YourTag

RMDIR /Q /S C:\temp\GLPIA

:FIN

**Comment by g-bougard** [comment]
> You can use batch file and scheduled task with "SYSTEM" account to deploy your glpi agent without admin account
> 
> This script tests the existence of fusioninventory uninstalls it if necessary, installs GLPI-AGENT if it is not installed, if it is already installed it then tests the installed version compared to the update that you place in C:\temp \GLPI to see if it updates or not.
> 
> !!Can be improved!!
> 
> ...

Hi @jmchrc 
this is still the purpose of [the glpi-agent-deployment.vbs script](https://raw.github.com/glpi-project/glpi-agent/develop/contrib/windows/glpi-agent-deployment.vbs) as explained in [documentation](https://glpi-agent.readthedocs.io/en/latest/installation/index.html#large-installations).

**Comment by jmchrc** [comment]
> > You can use batch file and scheduled task with "SYSTEM" account to deploy your glpi agent without admin account
> > This script tests the existence of fusioninventory uninstalls it if necessary, installs GLPI-AGENT if it is not installed, if it is already installed it then tests the installed version compared to the update that you place in C:\temp \GLPI to see if it updates or not.
> > !!Can be improved!!
> > ...
> 
> Hi @jmchrc this is still the purpose of [the glpi-agent-deployment.vbs script](https://raw.github.com/glpi-project/glpi-agent/develop/contrib/windows/glpi-agent-deployment.vbs) as explained in [documentation](https://glpi-agent.readthedocs.io/en/latest/installation/index.html#large-installations).

Hi, i have never used the proposed vbs, I made this script initially for FI then GLPI-Agent, however the scheduled task with SYSTEM user can also launch a vbs. The idea is that the person can install GLPI without an admin account.
The advantage of scheduled tasks is that GPOs can be deployed outside the domain and this very quickly (if the vpn is connected the policies apply, the task if immediate runs well compared to a logon script for example )

**Comment by g-bougard** [comment]
Okay, anyway I'm closing the issue. @wikilike7 should have find an answer to his problem.
