### ISSUE TITLE
Problème recovissait état ordinateur

### ISSUE THREAD

**Issue by mouhcine90zi** [glpi-project/glpi-agent#181]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

![Sans titre](https://user-images.githubusercontent.com/109590837/179727915-13a0d253-389c-4ca0-87c0-1ecbcebeac03.png)

### To reproduce

error

### Expected behavior

error

### Operating system

Linux

### GLPI Agent version

1.2

### GLPI version

10.0.1

**Comment by g-bougard** [comment]
Hi @mouhcine90zi 
I don't see any problem with your GLPI Agent log: it's just saying it have trouble to contact the serveur. Or your server url is wrong or your server is wrongly setup.

Also remember to upgrade your agent. If you still have troubles after upgrading, can you make some effort to describe them ?

**Comment by mouhcine90zi** [comment]
bonjour @g-bougard ,
je changer version glpi-agent 1.2  a 1.4 mais toujours meme probleme

**Comment by mouhcine90zi** [comment]
![Sans titre](https://user-images.githubusercontent.com/109590837/183610850-b64d7572-65d6-4df8-be16-f664d8def0b3.png)
