### ISSUE TITLE
Centos 9 Stream support

### ISSUE THREAD

**Issue by loopway** [glpi-project/glpi-agent#182]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

GLPI Agent Installation on Centos 9 Stream fails because of missing dependency: perl(XML::TreePP). The perl-XML-TreePP RPM has not yet been built and made available in EPEL9. See also https://bugzilla.redhat.com/show_bug.cgi?id=2031448

### To reproduce

perl glipi-agent-1.4-linux-installer.pl --reinstall --no question --server=https://server.domain/glpi/plugins/fusioninvetory/ --tag=Server --runnow --verbose

### Expected behavior

successful gpli-agent installation

### Operating system

Linux

### GLPI Agent version

Other (See additional context below)

### GLPI version

Not applicable

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

### Additional context

GLPI Agent Version 1.4 (not selectable in dropdown)

**Comment by g-bougard** [comment]
Hi @loopway 
as you pointed it out, this is a CentOS 9 Stream issue. We can't do anything on our side as XML::TreePP is really needed by the agent. You may try to install it from cpan and then forcing the installation of the package, but this is definitively not clean.
You should probably more avoid to use CentOS 9 Stream until it becomes really stable.
A last alternative is to use remoteinventory task.

**Comment by g-bougard** [comment]
As pointed out in #187, you should probably use AppImage build.

**Comment by g-bougard** [comment]
Hi @loopway 
development packages are now available and should work on CentOS 9.
Can you check my comment here which are for RockyLinux 9 but should also apply for CentOS 9: https://github.com/glpi-project/glpi-agent/issues/187#issuecomment-1269746041 ?

Any feedback would be appreciated.

**Comment by loopway** [comment]
Hi @g-bougard, 
We have installed the inventory agent on CentOS 9 and tested your dev build. We have not found any issues with the provided dev RPM or the agent itself. However, the perl installer would need some adjustments for CentOS9 (and probably RHEL9) too, similar to the ones for Rocky 9. This for example worked for us:

https://github.com/glpi-project/glpi-agent/blob/develop/contrib/unix/installer/RpmDistro.pm

```
diff glpi-agent-1.5-git23776baf-linux-installer.pl.orig glpi-agent-1.5-git23776baf-linux-installer.pl
913,923c913
<         # On CentOS 8, we need PowerTools
<         # On CentOS 9, we need CRB
<         if ($v >= 9) {
<             $self->verbose("Checking CRB repository is enabled");
<             my $ret = $self->run("dnf config-manager --set-enabled crb");
<             die "Can't enable CRB repository: $!\n" if $ret;
<         } elsif ($v == 8) {
<             $self->verbose("Checking PowerTools repository is enabled");
<             my $ret = $self->run("dnf config-manager --set-enabled powertools");
<             die "Can't enable PowerTools repository: $!\n" if $ret
<         } else {
---
>         if ($v < 8) {
925a916,919
>         } else {
>             $self->verbose("Checking PowerTools repository is enabled");
>             my $ret = $self->run("dnf config-manager --set-enabled powertools");
>             die "Can't enable PowerTools repository: $!\n" if $ret;

```

Further we like to bring to your attention that we use Foreman (upstream Satellite) to manage our RPM/DEB repositories. It would be very useful to have a flag/switch to turn off the enablement of the required repositories in the perl installer, since we would satisfy those requirements with Foreman and subscription-manager. If this is not a good solution for you we will manage our GLPI installations with a plain RPM/DEB repository hosted on Foreman instead of using the perl installer ...

**Comment by g-bougard** [comment]
Hi @loopway 

thank you for your feedback.

I will check what I can do for the new option request but I agree this should be a good issue to leave people handles the dependency problem if they want to.

**Comment by g-bougard** [comment]
Hi @loopway 
actually nightly built rpms works on CentOS 9.
Next nightly will also included the fixed rpm installer.
Thank for your help.
