### ISSUE TITLE
communication error: 400 Bad Request after SSL installation

### ISSUE THREAD

**Issue by TABHEFED** [glpi-project/glpi-agent#184]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Professional support

I still have but want a public following to help the community

### Is your help request related to a problem?

I have this error since I installed an SSL certificate on my GLPI server :

[Wed Jul 20 10:08:48 2022][info] target server0: server https://server_url/front/inventory.php
[Wed Jul 20 10:08:48 2022][info] sending contact request to server0
[Wed Jul 20 10:09:10 2022][error] [http client] communication error: 400 Bad Request, 
[Wed Jul 20 10:09:10 2022][error] [http client] unexpected content, starting with: <?xml version="1.0"?>
<REPLY><ERROR>XML not well formed!</ERROR></REPLY>
[Wed Jul 20 10:09:10 2022][error] No answer from server at https://server_url/front/inventory.php
[Wed Jul 20 10:09:10 2022][info] target server0: next run: Wed Jul 20 10:10:10 2022 - https://server_url/front/inventory.php
[Wed Jul 20 10:09:10 2022][info] GLPI Agent memory usage: WSS=3395584 PFU=124186624
[Wed Jul 20 10:09:10 2022][info] target server0: server https://server_url/front/inventory.php
[Wed Jul 20 10:09:10 2022][info] sending prolog request to server0
[Wed Jul 20 10:09:10 2022][info] server0 answer shows it supports GLPI Agent protocol
[Wed Jul 20 10:09:10 2022][info] running task ESX
[Wed Jul 20 10:09:11 2022][error] [http client] communication error: 400 Bad Request, 
[Wed Jul 20 10:09:11 2022][info] ESX task not supported by server0
[Wed Jul 20 10:09:13 2022][info] running task Collect
[Wed Jul 20 10:09:13 2022][error] [http client] communication error: 400 Bad Request, 
[Wed Jul 20 10:09:13 2022][info] Collect task not supported by server0
[Wed Jul 20 10:09:14 2022][info] running task Inventory
[Wed Jul 20 10:09:14 2022][info] New inventory from LAPT-0019.success.lan-2022-02-16-15-17-26 for server0

here is a screenshot of the agent configuration under windows :

![image](https://user-images.githubusercontent.com/109657270/179939994-655e0afc-1fe4-4d67-8e3c-fd5d9a41488e.png)

I do not understand before the implementation of the certificate it worked well with the parameter no-ssl-check=1

### Expected behavior

Computer and software is being registered.

### Actions you've considered

I tried with the no-ssl-check option with the value 1 but the problem is identical

### Additional context

the version of the GLPI agent is 1.4 and GLPI 10.1.0
Debian Server 11

**Comment by LeFouineur** [comment]
Hi,
If you try a local inventory exported as HTML and XML, does both conclude without error and are usable ?

Can you post the a curated copy of your xml file seeing as apparently there is an error in it ?

**Comment by g-bougard** [comment]
Hi @TABHEFED 
can you enable debug=2 in registry, restart the service, force an inventory and check/share the log again ?
As you're still using `/front/inventory.php` in your URL, don't forget to read the **Caution** in this doc: https://glpi-agent.readthedocs.io/en/latest/configuration.html#server
Also this means ESX & Collect will normally be in error: if you need them, read carefuly the **Caution** I asked you to check and update the `server` url accordingly.
