### ISSUE TITLE
Powersupply not added

### ISSUE THREAD

**Issue by ntinti** [glpi-project/glpi-agent#185]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Still not applicable

### Describe the bug

Powersupply is not inventoried because of "W" in integer field:

Supermicro Server:

` "Removing POWERSUPPLIES POWER_MAX value as not of integer type: '920 W'"`

### To reproduce

start inventory task on a supermicro server

### Expected behavior

Strip "W" before import in database

### Operating system

Linux

### GLPI Agent version

1.3

### GLPI version

10.0.1

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

**Comment by g-bougard** [comment]
Hi @ntinti 
thank you for your report.
Next nightly build should fix your issue.

**Comment by g-bougard** [comment]
Indeed, nightly build failed last night and I need to fix it today.
You still can download the required build from artifacts at: https://github.com/glpi-project/glpi-agent/actions/runs/2793880917
