### ISSUE TITLE
XML not well formed!

### ISSUE THREAD

**Issue by BlackBitUser** [glpi-project/glpi-agent#186]
### Documentation

Not applicable

### Solution search

Not applicable

### Professional support

I still have but want a public following to help the community

### Is your help request related to a problem?

With GLPI-inventory.bat create the X file, but when loading it from both GLPI and GLPI-Injector.bat gives the message of the title. What's the matter? The XML extructure is correct. (Google translate)

### Expected behavior

Successful loading of the file.

### Actions you've considered

Try JSON

### Additional context

GLPI 10.0.1 on Debian 11 BullsEye.

**Comment by g-bougard** [comment]
Hi @BlackBitUser 
we can't help you if we can't check ourself if the XML structure is really correct.
But you should first probably share you agent log enabling debug=2 in your agent. This may show another error for which the "XML not well formed" message is just a side-effect.

**Comment by BlackBitUser** [comment]
Hello **@g-bougard**, adding the --debug=2 option
says "Option debug does not take an argument"

Leaving only the --debug option shows:
..\PC0025.XML...[E83CF988] ERROR: XML not well formed!
DEBUG: <?xml version="1.0"?>
<REPLY><ERROR>XML not well formed!</ERROR></REPLY>

These elements were not sent:

**Comment by BlackBitUser** [comment]
Ups...

**Comment by g-bougard** [comment]
`debug=2` would be in configuration (in registry on windows), but for `glpi-agent` or `glpi-inventory` just use `--debug` 2 times: `--debug --debug`
The error you're showing seems to be from `glpi-injector`.

So in an administrative console, you should run:
```
glpi-agent --logger=stderr --debug --debug
```
And then you should report the lines around the error if you have it.

PS: Just in case, do you use as powershell console like in glpi-project/glpi-inventory-plugin#207 ? If yes, don't please.

**Comment by BlackBitUser** [comment]
I run glpi-inventory.bat from the powershell console.
Other XML files have been fine.
I have to scroll back to where I generate the xml's and repeat them. This time with version 1.4 and try.
I'll tell you the result.

**Comment by BlackBitUser** [comment]
@g-bougard 
From the MS-DOS console the XML file is correct.
Thank you very much.
