### ISSUE TITLE
Error during installation on ROCKY Linux 9

### ISSUE THREAD

**Issue by JTrotta** [glpi-project/glpi-agent#187]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

I still have but want a public following to keep the community aware

### Error during installation on RockyLinux 9:

```
Found distro: Rocky Linux
Running on linux distro: Rocky Linux release 9.0 (Blue Onyx) : Rocky Linux : 9.0...
Installing glpi-agent v1.4...
Trying to install glpi-agent v1.4-1 on Rocky Linux release 9.0 (Blue Onyx) release (Rocky Linux:9.0)...
Extracting glpi-agent-1.4-1.noarch.rpm ...
EPEL 9 repository still installed
Running: dnf -y install glpi-agent-1.4-1.noarch.rpm
Last metadata expiration check: 0:07:41 ago on Fri Jul 22 17:33:46 2022.
Error:
 Problem: conflicting requests
  - nothing provides perl(DateTime) needed by glpi-agent-1.4-1.noarch
  - nothing provides perl(Data::UUID) needed by glpi-agent-1.4-1.noarch
  - nothing provides perl(HTTP::Daemon) needed by glpi-agent-1.4-1.noarch
  - nothing provides perl(YAML::Tiny) needed by glpi-agent-1.4-1.noarch
  - nothing provides perl(XML::TreePP) needed by glpi-agent-1.4-1.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Failed to install glpi-agent
```

### To reproduce

1. perl glpi-agent-1.3-linux-installer.pl --server=https://x.y.z/  --install --runnow -v

### Expected behavior

Installation coplete

### Operating system

Linux

### GLPI Agent version

Other (See additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

### Additional context

Agent 1.4
GLPI 10.0.2

**Comment by auguzsto** [comment]
Try the snap install. It worked for me.
https://github.com/glpi-project/glpi-agent/releases/download/1.4/glpi-agent_1.4_amd64.snap

**Comment by g-bougard** [comment]
Hi @JTrotta 
the problem here seems to be RockyLinux 9 is still not providing some required package. Maybe this distro is still too young. Maybe the missing packages are provided by a RockyLinux specific repository which is not trivial.
You can also use the AppImage.

**Comment by JTrotta** [comment]
> You can also use the AppImage.

How to? Help?

**Comment by g-bougard** [comment]
https://glpi-agent.readthedocs.io/en/latest/installation/linux-appimage.html
Using latest 1.4 version.

**Comment by g-bougard** [comment]
I found few missing dependencies can be installed if CRB repository is enabled. But one very important is still missing `perl(XML::TreePP)`. This is also the case for CentOS 9 Stream as pointed out in #182.

As XML::TreePP CPAN module has not been updated since 8 years, maybe it's time to get rid of as no more maintained, and avoid such issue.

**Comment by emayoral** [comment]
You can temporarily get it installed using 
perl-DateTime-Locale-1.32-1.fc34.noarch.rpm
perl-XML-TreePP-0.43-18.fc34.noarch.rpm

From Fedora Core 34

All the other dependencies, you can get from CRB (what used to be the "extras" repo).

**Comment by g-bougard** [comment]
Hi there,

I made some refactoring for the XML support in the [fix/refacto-xml-libxml branch](https://github.com/glpi-project/glpi-agent/tree/fix/refacto-xml-libxml). The goal is to get rid of XML::TreePP.

I managed to install a development build on a RockyLinux9. The only pitfall was the requirement of perl-Parallel-ForkManager which can be installed actually from epel-testing repository using:
```
dnf install epel-release
dnf install --enablerepo=epel-testing perl-Parallel-ForkManager
```

You can try the development perl installer or rpm package from this build:
https://github.com/glpi-project/glpi-agent/actions/runs/3190810702
Perl installer is in Linux-Installer-Build  artifact archive and rpm packages are in the RPM-Build artifact archive.

Any feedback would be appreciated before merging the branch.

**Comment by g-bougard** [comment]
Hi @JTrotta, @auguzsto & @emayoral 
forgot to tell you the XML support lib refacto has been merged so actually nightly built rpms and rpm installer works on Rockylinux 9.
This closes that issue.
