### ISSUE TITLE
The new stations do not go back to GLPI AGENT 1.4

### ISSUE THREAD

**Issue by blainvillem** [glpi-project/glpi-agent#188]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

```
[Fri Jul 22 17:48:38 2022][info] sending prolog request to server0
[Fri Jul 22 17:48:38 2022][error] [http client] internal response: 500 Can't connect to ****:443 (Bad file descriptor), SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
[Fri Jul 22 17:48:38 2022][error] No answer from server at https://******/plugins/fusioninventory/
```

[http client] You can set it in conf as 'ssl-fingerprint' and disable 'no-ssl-check' option to trust that server certificate

COMMAND: GLPI-Agent-1.4-x64.msi /quiet SERVER="****" NO-SSL-CHECK=1 RUNNOW=1

I have the impression that the NO-SSL-CHECK=1 parameter does not work, because the GUI installation works fine.

### To reproduce

idk

### Expected behavior

idk

### Operating system

Windows

### GLPI Agent version

1.3

### GLPI version

9.5.6

**Comment by blainvillem** [comment]
Workaround:

Instead of:

GLPI-Agent-1.4-x64.msi /quiet SERVER="https://***/plugins/fusioninventory/" no-ssl-check=1 runnow=1

Write :

GLPI-Agent-1.4-x64.msi /quiet SERVER="https://***/plugins/fusioninventory/"
Sleep 15
Set-Itemproperty -path 'HKLM:\SOFTWARE \GLPI-Agent' -Name 'no-ssl-check' -value '1'
Restart-Service -Name 'glpi-agent'

**Comment by g-bougard** [comment]
Hi @blainvillem 
you probably missed to read carefully the doc about MSI installer:
https://glpi-agent.readthedocs.io/en/latest/installation/windows-command-line.html#command-line-parameters

The right syntax for the option with the installer is:
```
GLPI-Agent-1.4-x64.msi /quiet SERVER="****" NO_SSL_CHECK=1 RUNNOW=1
```
Where there are underscores in place of dashes.

Can I also advise you to use the new SSL_FINGERPRINT option ? Just check an agent log on which you enabled no-ssl-check option, you'll find the exact value to use. Adn this will make ssl connections even more secure.

**Comment by vollkommenIrrelevant** [comment]
NO-SSL-CHECK=1 is working, but I got the same error if I don't use it. 

`msiexec.exe /i "GLPI-Agent-1.5-git8a054db4-x64.msi" /quiet ADDLOCAL=feat_AGENT ADD_FIREWALL_EXCEPTION=1 server='https://XXXX.local/front/inventory.php' RUNNOW=1 ssl-fingerprint=sha256$XXXXX debug=2`

Logfile of Agent:
```
[Fri Sep 23 15:17:43 2022][info] target server0: server https://XXXX.local/front/inventory.php
[Fri Sep 23 15:17:43 2022][info] sending prolog request to server0
[Fri Sep 23 15:17:43 2022][error] [http client] internal response: 500 Can't connect to XXXX.local:443 (Bad file descriptor), SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
[Fri Sep 23 15:17:43 2022][error] No answer from server at https://XXXX.local/front/inventory.php
```

My Certificate is selfsigned and imported, any Ideas how to get more information what is going wrong?

**Comment by g-bougard** [comment]
As pointed in the other issue, you probably forgot to restart the service.
Setting debug=2 is the way to obtain full SSL debugging.

**Comment by vollkommenIrrelevant** [comment]
Yes, probably :-)
