### ISSUE TITLE
Erro 404 Agent GLPI Inventory

### ISSUE THREAD

**Issue by joaomariagomes** [glpi-project/glpi-agent#189]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Is your help request related to a problem?

Hello everybody,

I am installing the GLPI - Agent but the computer is not inventoried, it presents the following error in the log;

[Wed Jul 27 16:11:20 2022][error] [http client] communication error: 404 Not Found
[Wed Jul 27 16:11:20 2022][error] No answer from server at hmm/x.x.x.x/front/inventory.php
[Wed Jul 27 16:11:20 2022][info] target server0: next run: Wed Jul 27 16:13:20 2022 - hmm/x.x.x.x/front/inventory.php
[Wed Jul 27 16:11:20 2022][info] GLPI Agent memory usage: WSS=3252224 PFU=116101120
[Wed Jul 27 16:13:20 2022][info] target server0: server hmm/x.x.x.x/front/inventory.php
[Wed Jul 27 16:13:20 2022][info] sending prolog request to server0

But on the server the file is there as shown in the print;

Directory: https://drive.google.com/file/d/1-L5vDR5JNKoke7vdJN4bUdGGq1VLueJZ/view?usp=sharing
Browser Error: https://drive.google.com/file/d/1-MSBXQywEtraE_8n-PB7YYBmRMIhO4Oh/view?usp=sharing

Server: Ubuntu Server 20.04
Server: Web Apache2
GLPI Version: 10.0.2
Agent Version: GLPI Agent 1.4 x64
Host: Windows 10 x64

### Expected behavior

Send computer inventory to GLPI server.

### Actions you've considered

1 - Conceder permissão total (chmod 777) na pasta do GLPI em /var/www/html/glpi 
2 - Conceder permisão para o usuário do apache www-data.www-data
3 - Testar versões anteriores do Agente (1.2, 1,3, 1.4)
4 - Liberar total de todas as portas e protocolos para se conectarem ao servidor do GLPI.
5 - Instalar o agent em outro computador.
6 - Desativar Firewall do Windows

**Comment by LeFouineur** [comment]
Hi,
Something stupid, but does your webserver's user as the right to read that file ?
Do a `ls -la` and check the result, not just a `ls`.

**Comment by g-bougard** [comment]
Hi @joaomariagomes 
can you try with `http:///x.x.x.x/glpi` as server url ? Just in case you http server configuration point the root to `/var/www/html` and not `/var/www/html/glpi` as you expect to.
