### ISSUE TITLE
Silent installation of GLPI-Agent 

### ISSUE THREAD

**Issue by TPIexpert** [glpi-project/glpi-agent#19]
Hello, 
is it possible to do a silent installation of glpi-agent from the command line?
If so, what are the commands?
thanks in advance

**Comment by g-bougard** [comment]
Hi @TPIexpert 

I guess you're talking about windows installation.

Then, of course, take a look at the SetupOptions in [glpi-agent-deployment.vbs](https://github.com/glpi-project/glpi-agent/blob/cfde44b668a1464e1bb3aaf5da4f864ef81ed4da/contrib/windows/glpi-agent-deployment.vbs#L103):
```
SetupOptions = "/quiet RUNNOW=1 SERVER='http://glpi.yourcompany.com/glpi/fusioninventory/'"
```

`/quiet` is an option for msiexec binary which make the installation "silent" and the other are for the agent options.

That said, linux installation can also be silent.

**Comment by CTparental** [comment]
silent install in powershell:
https://gitlab.com/marsat/tools/-/blob/master/glpi/Silent_install_GLPI-Agent.ps1
