### ISSUE TITLE
The screens are not inventoried under linux

### ISSUE THREAD

**Issue by MaximePou** [glpi-project/glpi-agent#191]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Is your help request related to a problem?

The screens are not inventoried under linux, but the computers is ok 

### Expected behavior

have the inventory of screens

### Actions you've considered

have the inventory of screens

**Comment by g-bougard** [comment]
Hi @MaximePou 
please provide the agent version you tested, the linux systems you're using. Also what is your screen manufacturer & model ?
You can also provide the output of:
```
glpi-inventory --debug --partial monitor
```
