### ISSUE TITLE
Official debian packages

### ISSUE THREAD

**Issue by Fantu** [glpi-project/glpi-agent#197]
### Documentation

Yes, I read it

### Is your feature request related to a problem?

Hi, you can please considering to add official debian packages for glpi-agent like there are for fusioninventory-agent? ( https://tracker.debian.org/pkg/fusioninventory-agent )

### Expected behavior

-

### Alternatives you've considered

-

**Comment by g-bougard** [comment]
Hi @Fantu 
I was the guy who managed to add fusioninventory-agent to the official debian packages.
That was really a pain for a too little benefit.
And this is the reason why I developed the perl script installer, snap packaging and the AppImage support. They are specifically thought to support installation other a large infrastructure with very few scripting.

So yes, we considered this possibility, but this is actually not planned.
