### ISSUE TITLE
Agent doesn't collect GPU VRAM information (videos.pm)

### ISSUE THREAD

**Issue by n2b12** [glpi-project/glpi-agent#199]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Agent doesn't save any data about GPU memory. 
From reading perl script, I noticed that even if it did - it would present incorrect value, as data stored in `root\cimv2\Win32_VideoController.AdapterRAM` is uint32, and any modern GPU with >4GB VRAM will report as 4GB.

### To reproduce

1. Run agent on computer with GPU
2. Go to videos section of agent's output
Example data:
```json
      "videos": [
         {
            "chipset": "Intel(R) HD Graphics Family",
            "name": "Intel(R) HD Graphics 4600",
            "resolution": "1920x1200"
         },
         {
            "chipset": "NVIDIA GeForce GTX 950",
            "name": "NVIDIA GeForce GTX 950",
            "resolution": "1920x1200"
         }
      ]
```

### Expected behavior

Agent should collect VRAM. Correct VRAM values are stored in registry, inside video driver's classes.
My perl is too weak to submit pull request, so below is powershell script I used to collect this data from correlating WMI information with registry. I hope that helps.
```powershell
$cimVideoController = Get-CimInstance -ClassName "Win32_VideoController"
function Resolve-VRAM ($VideoController) {
    # first try resolving by matching device ID from CimInstance to device ID in video driver registry key 
    $GPUDeviceID = $VideoController.PNPDeviceID.Split('&')[0..1] -join '&'
    $x = Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0*" |
    Where-Object { $_.MatchingDeviceId -like "${GPUDeviceID}*" } |
    # then take vram size from registry key
    Select-Object -ExpandProperty HardwareInformation.qwMemorySize -ErrorAction SilentlyContinue
    # for integral GPUs use whatever CimInstance reports
    if ($null -eq $x -or $x -eq 0) {
        $x = $VideoController.AdapterRAM
    }
    return $x
}
$cimVideoController | Select-Object -Property `
    Name, 
@{name = 'Manufacturer'; expression = { $_.AdapterCompatibility } },
@{name = 'VRamGB'; expression = { [math]::round(((Resolve-VRAM($_)) / 1GB)) } },
DriverDate,
DriverVersion
```
Script has been tested in production and has worked without a problem across every graphics card manufacturer on Windows 10 machines.

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.1, 10.0.0

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

GLPI-Agent_v1.5-gite074b77e
GLPI Inventory plugin 1.0.3

**Comment by g-bougard** [comment]
Hi @n2b12 
thank you for your detailed issue with your sample code.
I managed to prepare a fix, but it would be nice if you can share few information so I can also develop a dedicated test with your datas.
I need the output of:
```
wmic path Win32_VideoController get /format:list
```
You can safely remove the `SystemName` value from the output.

I also need an export of the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}` registry key made from regedit.

Thank you in advance.

**Comment by n2b12** [comment]
I did this on a different machine, without integrated GPU, but it will confirm discrepancy between them as it has 8GB VRAM. Curiously enough, it has 2 identical entries in registry for gpu driver I'm currently using. Never happened to me before in testing of the powershell code.
`wimc` output:
```AcceleratorCapabilities=
AdapterCompatibility=Advanced Micro Devices, Inc.
AdapterDACType=Internal DAC(400MHz)
AdapterRAM=4293918720
Availability=3
CapabilityDescriptions=
Caption=AMD Radeon RX 6600 XT
ColorTableEntries=
ConfigManagerErrorCode=0
ConfigManagerUserConfig=FALSE
CreationClassName=Win32_VideoController
CurrentBitsPerPixel=32
CurrentHorizontalResolution=1920
CurrentNumberOfColors=4294967296
CurrentNumberOfColumns=0
CurrentNumberOfRows=0
CurrentRefreshRate=59
CurrentScanMode=4
CurrentVerticalResolution=1080
Description=AMD Radeon RX 6600 XT
DeviceID=VideoController1
DeviceSpecificPens=
DitherType=0
DriverDate=20220622000000.000000-000
DriverVersion=30.0.21023.1015
ErrorCleared=
ErrorDescription=
ICMIntent=
ICMMethod=
InfFilename=oem104.inf
InfSection=ati2mtag_Navi23
InstallDate=
InstalledDisplayDrivers=C:\WINDOWS\System32\DriverStore\FileRepository\u0380677.inf_amd64_dba19d925381d5ad\B380472\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0380677.inf_amd64_dba19d925381d5ad\B380472\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0380677.inf_amd64_dba19d925381d5ad\B380472\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0380677.inf_amd64_dba19d925381d5ad\B380472\amdxc64.dll
LastErrorCode=
MaxMemorySupported=
MaxNumberControlled=
MaxRefreshRate=75
MinRefreshRate=50
Monochrome=FALSE
Name=AMD Radeon RX 6600 XT
NumberOfColorPlanes=
NumberOfVideoPages=
PNPDeviceID=PCI\VEN_1002&amp;DEV_73FF&amp;SUBSYS_23361458&amp;REV_C1\6&amp;EAF386A&amp;0&amp;00000019
PowerManagementCapabilities=
PowerManagementSupported=
ProtocolSupported=
ReservedSystemPaletteEntries=
SpecificationVersion=
Status=OK
StatusInfo=
SystemCreationClassName=Win32_ComputerSystem
SystemName=
SystemPaletteEntries=
TimeOfLastReset=
VideoArchitecture=5
VideoMemoryType=2
VideoMode=
VideoModeDescription=1920 x 1080 x 4294967296 colors
VideoProcessor=AMD Radeon Graphics Processor (0x73FF)
```

Registry output. It's a bit large though.
[video diver.txt](https://github.com/glpi-project/glpi-agent/files/9426802/video.diver.txt)

**Comment by g-bougard** [comment]
Hi @n2b12 
thank you for the datas, this helped a lot.
I finally managed to update the module to support reading the VRAM memory size in registry, partially following your algorithm.
Checking few other windows computers, it seems `DeviceID` in the WMI output if referencing the video card number in registry. So I optimized the lookup to not parse all videocard entries, but only the expected one. For example with `DeviceID=VideoController1`, I check the `0001` registry key.
Tell me if you find cases where this is not correct.

Next nightly builds will include the fix.

**Comment by n2b12** [comment]
No, unfortunately you can't hardcode the `0001` key. On my other computer (one from the OP) the data is stored in `0000` key for GTX 950, and under 0001 I have Intel iGPU. And on top of that, intel entry doesn't have `HardwareInformation.qwMemorySize` property

**Comment by g-bougard** [comment]
I don't hardcode `0001`... I extract the `1` from `VideoController1` to look for `0001`.
Can you check your `wmic path Win32_VideoController get /format:list` on this computer and see if you have `DeviceID=VideoController0` for the GTX 950 and `DeviceID=VideoController1` for the intel iGPU ?
If `HardwareInformation.qwMemorySize` is missing, this won't be a problem. I also found a typo in WMI call: `AdaptaterRAM` was set in place of `AdapterRAM`, so if WMI report the right value it should be inventoried.

**Comment by g-bougard** [comment]
You can eventually directly try the development build you can download at: https://github.com/glpi-project/glpi-agent/actions/runs/2934366071
The installer will be in the "Windows-Build" artifact.

**Comment by n2b12** [comment]
I don't think it's going to work. On the computer with Intel and GTX 950 the numbers don't line up at all. Maybe it has something to do with using remote desktop, but that's a common use case and it would completely mess things up.
[wimc.txt](https://github.com/glpi-project/glpi-agent/files/9435135/wimc.txt)
[video driver intel+nvi.txt](https://github.com/glpi-project/glpi-agent/files/9435147/video.driver.intel%2Bnvi.txt)

**Comment by g-bougard** [comment]
You're indeed right. Thanks for the sharing of that outputs which helped to understand my mistake.
I'll fix that on monday.

**Comment by g-bougard** [comment]
Hi @n2b12 
I updated the algorithm to follow yours.
Please can you test next nightly build ?
Thank you

**Comment by n2b12** [comment]
I tried this on the Intel + Nvidia machine, and it worked correctly. I will try on more machines after nightly containing #198 resolution will be published.
