### ISSUE TITLE
Error on manual inventory creation

### ISSUE THREAD

**Issue by glassworksvfx** [glpi-project/glpi-agent#20]
Version: `GLPI-Agent-1.0-gitcfde44b6_arm64.pkg`

Attempting to create a manual inventory via

`./glpi-agent --server=URL`

Generates the following error

```
Execution failure:.
Can't write in /Applications/GLPI-Agent.app/var at /Applications/GLPI-Agent.app/agent/FusionInventory/Agent/Storage.pm line 29.
```

**Comment by g-bougard** [comment]
Hi @glassworksvfx 
you probably missed to run the agent as root.

**Comment by glassworksvfx** [comment]
Yes running it as root works. Thank you again.
