### ISSUE TITLE
Error JSON does not validate 'wireless' network port on win32

### ISSUE THREAD

**Issue by tdelaux** [glpi-project/glpi-agent#202]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

Hello,
GLPI Agent don't create/update computer into GLPI.

The GLPI Agent is correctly created in GLPI, but not the computer.

glpi-agent.log contains the following error lines : 

```
[Tue Aug 30 17:26:30 2022][error] [http client] communication error: 500 Internal Server Error
[Tue Aug 30 17:26:30 2022][debug2] format: Zlib
[Tue Aug 30 17:26:30 2022][debug2] [http client] F2FE8A99: received message:
{"status":"error","message":"JSON does not validate. Violations:\n\"**wireless**\" does not match to ^(ethernet|wifi|infiniband|aggregate|alias|dialup|loopback|bridge|fibrechannel|bluetooth)$ at #->properties:content->properties:networks->items[0]:0->properties:type\n","expiration":24}
[Tue Aug 30 17:26:30 2022][error] [http client] F2FE8A99: server error: JSON does not validate. Violations:
"wireless" does not match to ^(ethernet|wifi|infiniband|aggregate|alias|dialup|loopback|bridge|fibrechannel|bluetooth)$ at #->properties:content->properties:networks->items[0]:0->properties:type
```

### To reproduce

Wireless is used here : 
```
"networks": [
         {
            "description": "Intel(R) Wi-Fi 6 AX201 160MHz",
            "ipaddress": "10.1.10.45",
            "ipdhcp": "10.1.31.200",
            "ipgateway": "10.1.10.254",
            "ipmask": "255.255.255.0",
            "ipsubnet": "10.1.10.0",
            "mac": "70:1A:B8:7D:15:4A",
            "pciid": "8086:A0F0:0074:8086",
            "pnpdeviceid": "PCI\\VEN_8086&DEV_A0F0&SUBSYS_00748086&REV_20\\3&11583659&1&A3",
            "speed": "144",
            "status": "up",
            "type": "wireless",
            "virtualdev": false
         },
```
### Expected behavior

No error ...

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

GLPI version : 10.0.2
GLPI Inventory version : 1.0.3

**Comment by g-bougard** [comment]
Hi @tdelaux 
thank you for your report. This was a regression from 0c219a9.
The fix will be included in next nightly build.
You should be able to validate the development build took from: https://github.com/glpi-project/glpi-agent/actions/runs/2962086503

**Comment by tdelaux** [comment]
Hello,
it's OK
Thank's
