### ISSUE TITLE
Missing detailed port view in GLPI

### ISSUE THREAD

**Issue by Smiley-k** [glpi-project/glpi-agent#203]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

in the version of the glpi agent 1.0.3 plugin, it is not possible to configure port scanning, as well as the inventory agent itself (1.4) does not scan snmp (switches and routers), it scans but does not transmit anywhere to glpi

### To reproduce

no ports with switches after scanning

### Expected behavior

full information on the ports and what is connected on the ports, the speed of the ports, and so on

### Operating system

Linux

### GLPI Agent version

Other (See additional context below)

### GLPI version

Other (See additional context below)

### Additional context

glpi agent 1.4

**Comment by g-bougard** [comment]
Hi @Smiley-k 
honestly, you should clarify your issue:
 * the title is too general
 * by `glpi agent 1.0.3 plugin`, you probably mean `glpi inventory plugin v1.0.3`
 * It seems you're expecting something in GLPI as explained in "Expected behavior", but your bug description is really not clear enough

**Comment by Smiley-k** [comment]
I was expecting the functionality that was in fusioninventory


https://monosnap.com/file/UCMwquPhuOUypkBorEYUskaVlG3dX6

**Comment by g-bougard** [comment]
Hi @Smiley-k 
so this is definitively not a GLPI Agent issue but a GLPI native inventory feature one.
You can open a new dedicated issue on GLPI project linking this one. But you should be more accurate in your description.
