### ISSUE TITLE
GLPI Netinventory command issue

### ISSUE THREAD

**Issue by 575544685** [glpi-project/glpi-agent#205]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Is your help request related to a problem?

I'd like to add a network printer to GLPI server. I peform a local net inventory from an agent:
C:\Program Files\GLPI-Agent>glpi-netinventory --host 10.10.50.135 --credentials version:2c,community:public 
Here is the output of the command:
![image](https://user-images.githubusercontent.com/111935528/188555867-b83e0bf9-5228-42e3-a1fd-96137e1a2b73.png)
It is no problem. But when I check the XML inventory file expected in curent and netinventory directory. There is nothing. Where is the  inventory file generated by glpi-netinventory command?  The file should be injected to GLPI server.

### Expected behavior

How to generate the inventory file after performing glpi-netinventory command?

### Actions you've considered

Run glpi-inventory against the network printer and then inject the inventory file generated to GLPI server.

**Comment by g-bougard** [comment]
Hi @575544685 
`glpi-netinventory` generates an output so you need to redirect the output to a file like with:
```
C:\Program Files\GLPI-Agent>glpi-netinventory --host 10.10.50.135 --credentials version:2c,community:public >printer.xml
```

Or you can better use the `glpi-netdiscovery` command like this:
```
C:\Program Files\GLPI-Agent>glpi-netdiscovery --host 10.10.50.135 --credentials version:2c,community:public -i -s .
```
This will create 2 folders and you'll find the expected file in the `netdiscovery` one.
Take a look at man page here: https://glpi-agent.readthedocs.io/en/latest/man/glpi-netdiscovery.html

**Comment by Franco-Sparrow** [comment]
@g-bougard Hi Sir, sorry to reopen this issue.

Only thing I want is to inventory my network devices via SNMP without configure each field of information. That is a slave work. Unfortunely GLPI documentation doesnt give a clear example of how to do this. Could you please give me a hand and explain me how to execute a `glpi-netinventory` scan (for a given host, like `10.7.100.3`) and import this information to my GLPI server?

I am using:
- `glpi-agent_1.6.1`
- `glpi-agent-task-network_1.6.1`
- OS: `Ubuntu 20.04`
- Server: `glpi-10.0.10`
- Aditional info: The agent is installed on same GLPI server and the server has access to isolated network for network devices, through VPN. Network devices are under `10.7.100.0/24`, while GLPI server is *glpi.ecasa.avianet.cu*. The agent config is as follow:

```
server = https://glpi.ecasa.avianet.cu/marketplace/glpiinventory
delaytime = 3600
lazy = 0
scan-homedirs = 0
scan-profiles = 0
html = 0
backend-collect-timeout = 180
force = 0
additional-content =
no-p2p = 0
proxy =
user =
password =
ca-cert-dir =
ca-cert-file =
no-ssl-check = 1
timeout = 180
no-httpd = 1
httpd-ip =
httpd-port = 62354
httpd-trust =
logger = stderr
logfile = /var/log/glpi-agent.log
logfacility = LOG_USER
color = 0
tag =
debug = 0
```

The```glpi-netdiscovery``` does not create the folder `netinventory` inside the glpi-agent config directory. It just created the `netdiscovery` folder. Your first command with ```netinventory``` does not create a `netinventory` folder, it just create a file specified for output. In my case:

```bash
glpi-netdiscovery --host 10.7.100.3 --credentials version:2c,community:ecasanc --timeout 30 --inventory --save /etc/glpi-agent/ --debug
```

Created the file `10.7.100.3.xml`

```bash
cat /etc/glpi-agent//netdiscovery/10.7.100.3.xml
```

Its contents is as follow:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <AUTHSNMP>1</AUTHSNMP>
      <CONTACT>Grupo de soporte redes@ecasa.avianet.cu</CONTACT>
      <DESCRIPTION>Huawei Versatile Routing Platform Software
VRP Software Version 3.10, Release 1510P02
Quidway S5624P Product Version S5600-1510P02
Copyright (c) 1998-2006 Huawei Technologies Co.,Ltd. All rights reserved.</DESCRIPTION>
      <DNSHOSTNAME>10.7.100.3</DNSHOSTNAME>
      <IP>10.7.100.3</IP>
      <LOCATION>Centro de Datos #1 (principal). Redes. Rack de equipos activos.</LOCATION>
      <MAC>00:0f:e2:59:ef:dd</MAC>
      <MANUFACTURER>Huawei</MANUFACTURER>
      <MODEL>QuidWay S5624P</MODEL>
      <SERIAL>210235A126A075000117</SERIAL>
      <SNMPHOSTNAME>SW2-S5600</SNMPHOSTNAME>
      <TYPE>NETWORKING</TYPE>
      <UPTIME>348 days, 11:43:07.00</UPTIME>
    </DEVICE>
    <MODULEVERSION>6.0</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
```

But when used `glpi-netinventory` command:

```bash
glpi-netinventory --host 10.7.100.3 --credentials version:2c,community:ecasanc --timeout 30 --type NETWORKING --debug > 10.7.100.3.xml
```

It only created the file `10.7.100.3.xml` on your root directory, not inside the agent folder as expected (it can be fixed specifying the complete path, but you still have to create the `netinventory` folder first)

Anyway, the output of the previous command is as follow:

```bash
[debug] Current netinventory run expiration timeout: 1.0 hour
[debug] using 1 netinventory worker
[debug] #1, full snmp scan of 10.7.100.3 with credentials 1
[debug] #1, full match for sysobjectID .1.3.6.1.4.1.2011.10.1.43 in database
```

When you check the file `10.7.100.3.xml`, is *empty*. 

I can execute an snmpwalk to the network device:

```bash
snmpwalk 10.7.100.3 -v2c -c ecasanc | less
```

The output is as follow:

```bash
iso.3.6.1.2.1.1.1.0 = STRING: "Huawei Versatile Routing Platform Software
VRP Software Version 3.10, Release 1510P02
Quidway S5624P Product Version S5600-1510P02

Copyright (c) 1998-2006 Huawei Technologies Co.,Ltd. All rights reserved.
"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.2011.10.1.43
iso.3.6.1.2.1.1.3.0 = Timeticks: (3010900800) 348 days, 11:36:48.00
iso.3.6.1.2.1.1.4.0 = STRING: "Grupo de soporte redes@ecasa.avianet.cu"
iso.3.6.1.2.1.1.5.0 = STRING: "SW2-S5600"
iso.3.6.1.2.1.1.6.0 = STRING: "Centro de Datos #1 (principal). Redes. Rack de equipos activos."
iso.3.6.1.2.1.1.7.0 = INTEGER: 78
iso.3.6.1.2.1.2.1.0 = INTEGER: 35
iso.3.6.1.2.1.2.2.1.1.14 = INTEGER: 14
iso.3.6.1.2.1.2.2.1.1.16 = INTEGER: 16
iso.3.6.1.2.1.2.2.1.1.31 = INTEGER: 31
iso.3.6.1.2.1.2.2.1.1.823 = INTEGER: 823
iso.3.6.1.2.1.2.2.1.1.4227614 = INTEGER: 4227614
# [...]
```

Trying again with glpi-netinventory command, this time more simple:

```bash
glpi-netinventory --host 10.7.100.3 --credentials version:2c,community:ecasanc
```

The output show error communication via SNMP using the agent:

```xml
[error] #1, SNMP communication error: no response from host 10.7.100.3
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <ERROR>
        <ID>0</ID>
        <MESSAGE>SNMP communication error: no response from host 10.7.100.3</MESSAGE>
      </ERROR>
    </DEVICE>
    <MODULEVERSION>6.0</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>SNMPQUERY</QUERY>
</REQUEST>
```

Why is not working the netinventort using the agent, when snmpwalk is able to query the remote network device using this protocol?

**Comment by g-bougard** [comment]
Hi @Franco-Sparrow 

hijacking old issues is not what I would expect for such kind of request.

So I created a new issue and migrated is as Q&A discussion here: #558
