### ISSUE TITLE
Error JSON does not validate 'interface' storage property on win32

### ISSUE THREAD

**Issue by tdelaux** [glpi-project/glpi-agent#207]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

Hello,
GLPI Agent don't create/update computer into GLPI.

The GLPI Agent is correctly created in GLPI, but not the computer.

glpi-agent.log contains the following error lines :

[Wed Sep  7 17:13:05 2022][error] [http client] communication error: 500 Internal Server Error
[Wed Sep  7 17:13:05 2022][debug2] format: Zlib
[Wed Sep  7 17:13:05 2022][debug2] [http client] 54DA5067: received message:
{"status":"error","message":"JSON does not validate. Violations:\n\"NVME\" does not match to ^(SCSI|HDC|IDE|USB|1394|SATA|SAS|ATAPI)$ at #->properties:content->properties:storages->items[0]:0->properties:interface\n","expiration":24}
[Wed Sep  7 17:13:05 2022][error] [http client] 54DA5067: server error: JSON does not validate. Violations:
"NVME" does not match to ^(SCSI|HDC|IDE|USB|1394|SATA|SAS|ATAPI)$ at #->properties:content->properties:storages->items[0]:0->properties:interface

### To reproduce

"controllers": [
         {
            "caption": "NVMe SSD Controller PM9A1/PM9A3/980PRO",
            "manufacturer": "Samsung Electronics Co Ltd",
            "name": "NVMe SSD Controller PM9A1/PM9A3/980PRO",
            "pcisubsystemid": "144d:a801",
            "productid": "a80a",
            "type": "Standard NVM Express Controller",
            "vendorid": "144d"
         },

### Expected behavior

No error ... ;-)

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

GLPI version : 10.0.2
GLPI Inventory version : 1.0.3

**Comment by g-bougard** [comment]
Hi @tdelaux 
can you better share the output of:
```
glpi-inventory --partial storage --debug --debug
```

**Comment by g-bougard** [comment]
Anyway, you still can fix the problem by editing the `vendor/glpi-project/inventory_format/inventory.schema.json` file from your GLPI installation. Search the line `"pattern": "^(SCSI|HDC|IDE|USB|1394|SATA|SAS|ATAPI)$"` around the 1850 line. Remove this line and also the comma from the previous line to have:
```
              "interface": {
                "type": "string",
                "examples": [
                  "IDE"
                ]
              },
```
With that fix, you inventory should be imported and the interface type correctly updated in GLPI.

I'll make a PR to remove that pattern which is really too restrictive.

**Comment by g-bougard** [comment]
Hi @tdelaux 
next glpi release will integrate the fix.
