### ISSUE TITLE
Printer serial is incorrect

### ISSUE THREAD

**Issue by skyemk** [glpi-project/glpi-agent#208]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Professional support

Still not applicable

### Is your help request related to a problem?

not exactly sure

### Expected behavior

GLPI agent picks up printer connected to desktop but gets incorrect printer serial number

system shows a serial ex: 1234567890000

actual serial ex: r9dy100000 (this whole series starts with rdy)

printer model: epson lq310

### Actions you've considered

not much

**Comment by g-bougard** [comment]
Hi @skyemk 
are you talkinbg about doing inventory from the computer itself or via glpi-netinventory and snmp scan ?
In the first case, can you share the output of `glpi-inventory --debug --debug --partial printer` ?
This should also show which agent version and which OS you're using as you forgot to tell about them.

**Comment by xir6fir6iriezdu** [comment]
> Hi @skyemk are you talkinbg about doing inventory from the computer itself or via glpi-netinventory and snmp scan ? In the first case, can you share the output of `glpi-inventory --debug --debug --partial printer` ? This should also show which agent version and which OS you're using as you forgot to tell about them.

hey,
sorry about the late reply, rought month.
will share the glpiinventory printer debug data when i manage to get my hands on the printer again.

the computers i install glpi on is mostly windows 10, however few are 11, as for driver version its 1.4 the latest.

**Comment by g-bougard** [comment]
Closing without user feedback, feel free to re-open if you have more to share.
