### ISSUE TITLE
How to make glpi-agent starting automatically after rebooting

### ISSUE THREAD

**Issue by 575544685** [glpi-project/glpi-agent#209]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Expected behavior

Today, I install glpi-agent1.4 from sources according the schedules spcified in installation manual. The agent computer is based on a kind of Linux. After the installation I'd like the agent to run as a service(like on windows or Linux perl/Appimage installation). I input the command according the manual: 
glpi-agent --server=http://glpiserver/glpi/plugins/glpiinventory/ --daemon

But the command runs at foreground not at background I expected.  I have to exit the agent and run the agent again with a "&" at the end. Even though, there are running status information showed on the screen. I think if the computer is rebooted, the agent won't run automatically either.

On windows system or if I use Perl installer or AppImage installer, the agent can run as a service or a daemon at background. And the agent can boot automatically after rebooting. How can I do next  after installation from sources?

### Actions you've considered

[root@localhost glpi-agent-1.4]# cpanm inc::Module::Install
[root@localhost glpi-agent-1.4]# cpanm .
[root@localhost glpi-agent-1.4]# perl Makefile.PL
[root@localhost glpi-agent-1.4]# make
[root@localhost glpi-agent-1.4]# make install
[root@localhost glpi-agent-1.4]#glpi-agent --server=http://glpiserver/glpi/plugins/glpiinventory/ --daemon

**Comment by g-bougard** [comment]
Hi @575544685 
can you at least tell us which OS and version you're using ?

**Comment by 575544685** [comment]
Kylin Linux, 
cpu aarch64

**Comment by 575544685** [comment]
The command "glpi-agent --server=http://glpiserver/glpi/plugins/glpiinventory/ --daemon &" can run normally. I can see the server from GLPI now. I just want it can run automatically after rebooting and I can do inverntory from GLPI server. BTW, Kylin Linux is a Linux Chinese build.  But It looks no different as other Linux for the agent by now. The cpu of my agent is ARM.

**Comment by g-bougard** [comment]
Does it use systemd or another service management system ?

**Comment by 575544685** [comment]
It looks systemd.

**Comment by g-bougard** [comment]
So you should as root:
1. Install [glpi-agent.service](https://raw.githubusercontent.com/glpi-project/glpi-agent/develop/contrib/unix/glpi-agent.service) file under `/lib/systemd/system` folder
2. Create a dedicated cfg file under `/etc/glpi-agent/conf.d` folder to setup your agent with at least a `server` line
3. Enable the service by running: `systemctl enable glpi-agent`
4. Start the service by running: `systemctl start glpi-agent`

The service will be started at next boot as it is "enabled".
This process assumes the glpi-agent script was installed as `/usr/bin/glpi-agent`. If this is not the case, fix the path in `glpi-agent.service` file.

**Comment by 575544685** [comment]
@g-bougard Thx.
