### ISSUE TITLE
Fields not being updated after GLPI Agent automated connection

### ISSUE THREAD

**Issue by leont216** [glpi-project/glpi-agent#210]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

In Setup > General > Assets 

We have it configured to be Copy the computer and and set the status to deployed on any connecting or updating.

![image](https://user-images.githubusercontent.com/113643369/190517458-1dc1fdfa-76a4-4ec7-b422-60ed7efc7211.png)
 
When we run the disconnect the monitor via connections, and then run the inventory & agent it does not copy the fields/change the status to deployed. (We have also confirmed there is no lock on any of the fields on the monitor)

When we manually connect the monitor to the computer , the fields are updated accordingly.

### To reproduce

1. Unlink monitor on the connections
2. Remove any locks on the machine/monitor
3. Run glpi agent to inventory , or run an update via the web ui.

### Expected behavior

Fields should update according to the connected machine and status should be set to deployed when automatically updating with GLPI Agent.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.3

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

**Comment by leont216** [comment]
Of note, we were having this issue on GLPI 10.0.0 and GLPI Agent 1.2, we tried an update to see if it would fix the issue

**Comment by g-bougard** [comment]
Hi @leont216,

your problem seems to be only related to GLPI, and not to GLPI Agent.

I'm just closing this issue as you still also opened glpi-project/glpi#12658 on GLPI project.

**Comment by leont216** [comment]
> Hi @leont216,
> 
> your problem seems to be only related to GLPI, and not to GLPI Agent.
> 
> I'm just closing this issue as you still also opened [glpi-project/glpi#12658](https://github.com/glpi-project/glpi/issues/12658) on GLPI project.

Im not sure which one it was related to, because it seems like its working properly when linking connections manually. But when the agent links something via the auto inventory or manual trigger the status' dont update. On a new import it will update the fields, but on a disconnect and reconnect or field change it wont.

**Comment by nykroy** [comment]
i have the same problem with glpi 10.0.9 and glpi-agent 1.5 :(
