### ISSUE TITLE
GLPI agent upgrade over 1.2 triggers windows reboot

### ISSUE THREAD

**Issue by grego1981** [glpi-project/glpi-agent#215]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Professional support

Yes, I know

### Is your help request related to a problem?

i have made a deployment script to upgrade the agent on windows 10 (mostly) machines, from v1.2 to v1.4 The issue is that during the msi install the computer reboots leaving the machine unconfigured and without the agent at all, disrupting the users as well. Is there a way to suppress/bypass the reboot? I use the /norestart  and REBOOT=ReallySuppress and failed. It seems the reboot is triggered on uninstalling the previous version. In the script I stop the glpi-agent service prior to running the msi installation.
I even tried uninstalling the 1.2 version prior to installing the new version and it still has the same behaviour.
The same occurs using msiexec and the vbs script. 
This is the batch script I use:

`net stop glpi-agent`
`wmic product where name="GLPI Agent 1.2" call uninstall /nointeractive && shutdown /a`
`START /B /WAIT cmd /c "cscript.exe c:\scripts\agent\glpi-agent-deployment.vbs" `
`reg.exe import c:\scripts\agent\glpi-agent-conf.reg`

this is the line I modified in the vbs script :
`
SetupOptions = "/quiet /norestart RUNNOW=1 ADD_FIREWALL_EXCEPTION=1 ADDLOCAL=ALL  NO_SSL_CHECK=1 EXECMODE=1 SERVER='http://glpi-server-ip/glpi/plugins/fusioninventory'"
`

### Expected behavior

To upgrade the agent without having to reboot the machine, don't care if the agent will work on next reboot.

### Actions you've considered

All described in "Is your help request related to a problem?"

**Comment by g-bougard** [comment]
Hi @grego1981 
you're the first person who "discovered" upgrading the agent would require a reboot. For me, the problem is surely not the agent.
In your script I see the `shutdown` command and I don't understand why you're using this command. It seems to me this command has nothing to do there and it is the reason of the reboot.

Have you even tried to manually installed v1.2 on a computer, and upgraded to 1.4 manually to verify glpi-agent really requires a reboot ?

**Comment by grego1981** [comment]
The `&& shutdown /a` command is to suppress reboot if required by the uninstall procedure, due to wmic limitations.
When installing manually the reboot doesn't occur. The point is that the reboot occurs when I use the MSI installation method, which is the point when deploying in 120 computers. Even with the command below the reboot occurs:
`msiexec.exe /i agent1.4.msi /quiet ADD_FIREWALL_EXCEPTION=1 ADDLOCAL=ALL  NO_SSL_CHECK=1`

I used this one liner when I upgraded to the current version (1.2) without issues and without a single reboot incident.

**Comment by g-bougard** [comment]
Maybe there's another issue with your installation process.
Is the script run as with admin rights ? In principle, you don't have to stop the agent and uninstall it as this is done during the upgrade process.

**Comment by grego1981** [comment]
Yes the script is run with admin rights. The initial method I tried was to run the `msiexec.exe /i agent1.4.msi /quiet ADD_FIREWALL_EXCEPTION=1 ADDLOCAL=ALL NO_SSL_CHECK=1` as administrator, that is when the reboot occured... and that is why I tried a more complex script... For years, with the FI agent and with the first version of glpi-agent I just used this command to upgrade the agent. This is the first time it didn't work as expected, hence this issue..

**Comment by grego1981** [comment]
This is the msi log which initiates a reboot after running `msiexec.exe /i agent1.4.msi /quiet ADD_FIREWALL_EXCEPTION=1 ADDLOCAL=ALL NO_SSL_CHECK=1 /L*V "C:\scripts\agent.log"`

[agent.zip](https://github.com/glpi-project/glpi-agent/files/9606085/agent.zip)

**Comment by g-bougard** [comment]
Nice share.

In this log, I see these lines:
```
MSI (s) (A0:54) [11:58:32:750]: RESTART MANAGER: Will attempt to shut down and restart applications in no UI modes.
MSI (s) (A0:54) [11:58:32:750]: RESTART MANAGER: Did detect that the client process of this installation holds file[s] in use, so a reboot will be necessary.
MSI (s) (A0:54) [11:58:32:750]: Note: 1: 1610 
MSI (s) (A0:54) [11:58:32:766]: RESTART MANAGER: The user chose to go on with the installation, although a reboot will be required.
The setup must update files or services that cannot be updated while the system is running. If you choose to continue, a reboot will be required to complete the setup.
```

So I understand MSI decides the computer must be rebooted as some files are locked by the system. Why the system locked the files (and which files), I don't see any reason in that log...

But I see one thing early in the log:
```
MSI (s) (A0:68) [11:57:57:604]: Running installation inside multi-package transaction C:\Program Files\GLPI-Agent\var\http..__10.10.99.12_glpi_plugins_fusioninventory_\deploy\workdir\63297f32a2c67\agent1.4.msi
```

To me this means you're probably trying to upgrade the agent from a FI Deploy task. This is probably a bad idea: people generally uses GPO to deploy and upgrade agents. I can only guess your Deploy script locks the service from the OS point of view and then I can understand MSI decides a reboot is required.
Maybe you can try to modify your deploy task to:
1. Move the the package in folder not under the installation folder
2. Setup a schedule job to start the installation one minute later (after the deploy task has been processed and the agent is really able to cleanly stop)

**Comment by grego1981** [comment]
Yes I'm doing it from FI as I always did... Attached the log from the result with the msi saved locally and not coming from the deployment. Same machine (it's a vm in which I roll back to a snapshot to avoid changes in the environment)..
[agent.zip](https://github.com/glpi-project/glpi-agent/files/9606750/agent.zip)

**Comment by grego1981** [comment]
Also is there an example or documention on how to setup through a scheduled task?

**Comment by g-bougard** [comment]
For your other log, I see you have this on the msiexec commandline:
```
CURRENTDIRECTORY=C:\Program Files\GLPI-Agent\var\http..__10.10.99.12_glpi_plugins_fusioninventory_\deploy\workdir\6329972bc5a94
```
Something may still be wrong in that test.

For the doc, read [official schtasks.exe documentation](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/schtasks-create).

Maybe this would work before but maybe some OS changes make this now impossible to upgrade the way you used before as the system recognizes a dangerous situation. Who knows, windows remains mysterious sometime like the fact the log doesn't report what is locked by the system...
