### ISSUE TITLE
GLPI-Agent-ID missing on getConfig requests

### ISSUE THREAD

**Issue by pmatis** [glpi-project/glpi-agent#219]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

I'm experimenting with the agent and reverse engineering the communication protocol. In a packet capture, I noticed that GLPI-Agent-ID is not in the header during all requests, according to the documentation:
https://glpi-json-protocol.readthedocs.io/en/latest/common.html

I haven't dug in to the code very much, so I don't know how to fix it. On the assumption that I'm not missing something and this is in error that should be looked at, I think that this module:
GLPI::Agent::HTTP::Client::Fusion

Needs a line like this:
https://github.com/glpi-project/glpi-agent/blob/develop/lib/GLPI/Agent/HTTP/Client/GLPI.pm#L78
...to add the header to the GET request.

### To reproduce

Install agent
Point to a HTTP server (no ssl)
Capture traffic and look for the GLPI-Agent-ID header in requests from the agent

### Expected behavior

GLPI-Agent-ID header should be present in all requests to the server

### Operating system

Windows, Linux, MacOSX

### GLPI Agent version

1.4

### GLPI version

Not applicable

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

**Comment by g-bougard** [comment]
Hi @pmatis 

thank you for your interest in this protocol, and I'll follow your feedback if you discover any issue. The protocol is actually not fully finalize and only some part is really implemented.

Btw, here, you're referencing the "getConfig" requets in the issue title. "getConfig" requests comes from legacy XML-based protocol for tasks like netdiscovery, netinventory, collect and deploy. As this is the legacy XML-based protocol, and the server should not answer with json protocol, the `GLPI-Agent-ID` header is just not required.

The legacy XML-based protocol is inherited from FusionInventory agent code and this agent supports it to support FusionInventory for GLPI plugin as server target or for exchanges with transitional GlpiInventory plugin.

**Comment by g-bougard** [comment]
Just in case, if you have any comment on the protocol itself, don't hesitate to open an issue on the related doc project:
https://github.com/glpi-project/json-protocol

**Comment by pmatis** [comment]
@g-bougard,
Thank you for the fast response and explanation. So it appears that it's working as expected and I'll need to figure out how to uniquely identify a client. I'm experimenting with using the agent to report in to my own custom server. Is there an equivalent method in the json protocol that I should be watching for?

**Comment by g-bougard** [comment]
`Agent-ID` header is probably just what you need if you only need to identify an agent. Anyway, you also can use the `deviceid` which was still reported in XML inventory and is also present in JSON format. But this "id" made often trouble for people as it can be easily reset so the agent can change this "id" sometime. This is why we wanted to introduce the "Agent-ID" as it should be kept unique and static for an agent and permits to change the agent `deviceid` without loosing its main reference.

Actually in GLPI, `Agent-ID` is not really used but it should be used with the [REGISTER](https://glpi-json-protocol.readthedocs.io/en/latest/register.html) protocol in a near future.

If you expect to only use JSON protocol, keep in mind `Agent-ID` MUST always be set by the agent. Tasks using legacy XML exchange format will be updated in a near future to support JSON based protocol. GLPI-Agent will always use the [CONTACT](https://glpi-json-protocol.readthedocs.io/en/latest/contact.html) protocol if the server answers in JSON. Actually GLPI 10 answers in JSON if it detects the `Agent-ID` header, even if the agent starts with the legacy XML PROLOG request. After the agent received a first JSON answer from a server, it will always start with the CONTACT protocol.

Legacy XML based protocol comes always after a CONTACT, so you'll always be able to link `Agent-ID` to the current "deviceid" as the deviceid is also sent during the CONTACT. So if you also need to support XML based protocol for netdiscovery, netinventory, deploy or collect tasks, you'll still be able to "link" the agent to its `Agent-ID` through the "deviceid" exchanged during the previous CONTACT.

If you still require netdiscovery, netinventory, collet or deploy tasks using JSON protocol, you're free to propose some specs on the project I still linked before and if I agree I'll be happy to implement myself the specified protocol in GLPI-Agent or merge your code if you even want to implement the protocol I would have validated ;-)
