### ISSUE TITLE
How to install glpi-agent automaticly with msiexec ? 

### ISSUE THREAD

**Issue by kevkev-73** [glpi-project/glpi-agent#22]
Hi ! 
I'd like ton install with a GPO glpi-agent on all the computer in my company. I created a file .bat with msiexec but i don't know the parameters to specify the server name an accept the licence... 
Can you help me please ? 

Thank you ;)

**Comment by g-bougard** [comment]
Hi @kevkev-73 
take a look at #19 and #15 where the subject has still been investigated and where you should find you answer.
I'm putting in my TODO list the need to document the installation of GLPI-Agent MSI package.

**Comment by kevkev-73** [comment]
Thank you for your answer.

I tried to create a .bat file with the row :
"msiexec.exe /i "C:\GLPI-Agent-1.0-git349dee89-x64.msi" /quiet RUNNOW=1 SERVER='https:/my_server/marketplace/fusioninventory/' ADD_FIREWALL_EXCEPTION=1".

After run the bat file, Glpi was not installed into computer. 
How, i can solve my problem ? 

Thank you

**Comment by g-bougard** [comment]
Hi @kevkev-73 
I'm not sure about your quotes and your `/i` option. Your .bat file should be like this with an administrative installation:
```bat
msiexec.exe /a "C:\GLPI-Agent-1.0-git349dee89-x64.msi" /quiet RUNNOW=1 SERVER='https:/my_server/marketplace/fusioninventory/' ADD_FIREWALL_EXCEPTION=1
```

**Comment by kevkev-73** [comment]
Hi @g-bougard 
Thank you !
It works and I forgot to run the file with administrator rights. ;)

**Comment by DEVdotCapivara** [comment]
Trying the same with GLPI-Agent for GLPI Inventory but had no positive results with this script: 

`msiexec.exe /a "\\domain\netlogon\glpiagent\GLPI-Agent-1.5-x64.msi" /quiet RUNNOW=1 SERVER='http://glpi.domain.com.br/glpi/plugins/glpiinventory/' ADD_FIREWALL_EXCEPTION=1`

Trying to find another way around

**Comment by g-bougard** [comment]
Be sure to run the command from the a cmd administrative console, not from a powershell one.

You can try also the vbs script, see https://glpi-agent.readthedocs.io/en/latest/installation/index.html#large-installations
