### ISSUE TITLE
Daily build git8a054db4-x64.msi not working

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [glpi-project/glpi-agent#220]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

Hello,

i got the following error in the logfile of the actual daily build:

[Fri Sep 23 10:52:00 2022][error] [http client] communication error: 500 Internal Server Error
[Fri Sep 23 10:52:00 2022][error] [http client] server error: JSON does not validate. Violations:
"RAID" does not match to ^(SCSI|HDC|IDE|USB|1394|SATA|SAS|ATAPI)$ at #->properties:content->properties:storages->items[0]:0->properties:interface

### To reproduce

1. Download Build
2. Install Build
3. Run agent

### Expected behavior

Don't see this error in logfile

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

### Additional context

git8a054db4-x64

**Comment by g-bougard** [comment]
Hi @vollkommenIrrelevant 

this is a server issue which should be fixed in GLPI v10.0.3 afaik.

As you didn't report your GLPI version in issue description, can you confirm which GLPI version you're using ?
If you're not using 10.0.3, please upgrade.

**Comment by vollkommenIrrelevant** [comment]
Thank you, i'm using 10.0.1 due there is actual no update of fusioninventory for newer versions.

**Comment by trasher** [comment]
The fix was not part of 10.0.3, I've just added it for next release: https://github.com/glpi-project/glpi/pull/12747

FI plugin should work with latest GLPI releases. You really should consider upgrading, several major security issues has been fixed.

**Comment by vollkommenIrrelevant** [comment]
Thank you!
I did some preventions against attacking this and currently on migration to glpi plugin...

**Comment by g-bougard** [comment]
Anyway to fix this issue, you still can apply glpi-project/inventory_format#81 on the inventory.schema.json file you'll find somewhere in your GLPI install.
