### ISSUE TITLE
ssl-fingerprint and entry in logfile

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [glpi-project/glpi-agent#221]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Is your help request related to a problem?

I installed GLPI-Agent with following command:

`GLPI-Agent-1.5-git7e89bf8e-x64.msi" /quiet ADDLOCAL=feat_AGENT ADD_FIREWALL_EXCEPTION=1 server='https://X.X.X.X/front/inventory.php' RUNNOW=1 ssl-fingerprint=sha256$XXXXXXXXXXXXXXX`

In the logfile of the Agent (daily build GLPI-Agent-1.5-git8a054db4-x64.msi) I found the entry:
`"Sep 23 11:00:59 2022][info] [http client] You can set it in conf as 'ssl-fingerprint' and disable 'no-ssl-check' option to trust that server certificate".`

Does anybody knowing why this output was in the logfile indeed i'm using the parameter ssl-fingerprint?

### Expected behavior

Entry is not part of the logfile.

### Actions you've considered

-

**Comment by vollkommenIrrelevant** [comment]
I found out that the message is mistakly. I had the domain in the cert and tried connect the ip-adress with the plugin. An improvment would be great...

**Comment by g-bougard** [comment]
Hi @vollkommenIrrelevant 

as far I remember this message can only appear if `no-ssl-check` is set.

I'll check if I missed something.

Anyway, I didn't understand your last comment.

**Comment by vollkommenIrrelevant** [comment]
> Anyway, I didn't understand your last comment.

I got the output indeed there is a problem and if i disable no-ssl-check everything brokes because in zertifikate is not the server-ip which was entered in the agent-setup... ;-)
` "Sep 23 11:00:59 2022][info] [http client] You can set it in conf as 'ssl-fingerprint' and disable 'no-ssl-check' option to trust that server certificate".`

**Comment by g-bougard** [comment]
I confirm the ssl-fingerprint info in log only appears if no-ssl-check is not set.
Did you forget to restart the service after a change in registry ? Anyway check your registry in the case you upgraded and so maybe the option could have been kept set after the upgrade... and restart the service if you fix the value.

**Comment by vollkommenIrrelevant** [comment]
> Did you forget to restart the service after a change in registry 

yep...

**Comment by g-bougard** [comment]
I think we can close so.
