### ISSUE TITLE
Test/build environment

### ISSUE THREAD

**Issue by pmatis** [glpi-project/glpi-agent#222]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Professional support

Yes, I know

### Is your help request related to a problem?

No

### Expected behavior

Compile/package an MSI, sh, rpm, deb, etc.

I searched and couldn't find it, but it must be out there. I use Linux as my desktop and laptop operating system. Please direct me to documentation on how to take the checked out git repository and make my own packages, potentially after modifying code. I'd like to try some changes and deploy my own glpi-agent version on a device to test, then submit a pull request once I have something useful.

I'm familiar with git forking, checkout and pull requests but not familiar with packaging this project from source.

Thank you.

### Actions you've considered

Searching the docs, google, duckduckgo, brave, etc. Maybe I just don't know the correct terms to search for?

**Comment by g-bougard** [comment]
Hi @pmatis 

you're right this part of the doc is just missing.

But you can check what is doing the [glpi-agent-packaging.yml workflow](https://github.com/glpi-project/glpi-agent/blob/develop/.github/workflows/glpi-agent-packaging.yml) file. All the current packaging is done by GH Actions. If you're familiar with forking and checkout with GH, you may just need to enable GH Actions to have your first package just built out of the box ;-)

When GH Actions runs, you'll find development packages as artifacts. As example check this build:
https://github.com/glpi-project/glpi-agent/actions/runs/3114543765
This is a branch I'm working on to remove XML::TreePP dependency so rpm packages could be used on RH9/CentOS9/RockyLinux9.

Following the workflow file, you should understand how to build specific packages on your computer.

Hope this help.
After that, if you want to contribute some dedicated docs, just make a PR on https://github.com/glpi-project/doc-agent ;-)

**Comment by g-bougard** [comment]
Closing without user feedback
