### ISSUE TITLE
Fusion Migration to GLPI Agent

### ISSUE THREAD

**Issue by Cha-sim** [glpi-project/glpi-agent#223]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

Hello,
I migrated my version of GLPI 9.5, which used Fusion Inventory, to GLPI 10.

I would like to use GLPI Inventory Agent, the 1.4 agent is well installed and configured.

But when going back to GLPI, with each new inventory, it creates a new machine for me without updating the previous one.
I had erased my entire fleet (fusion) before launching glpi agent
i try with native inventory, same probleme

### To reproduce

1. Migrate GLPI 9.5 With fusion to GLPI 10 with glpi agent
2. Erase all the ancient data of fusion inventory in glpi
3. install glpi agent 1.4
4. force inventory
5. show inventory in glpi 
6. force inventory
7. . show inventory in glpi  (same machine but duplicate in glpi ui)

### Expected behavior

I would like each new inventory of a machine to update this machine in GLPI without creating a new one

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.3

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.4

**Comment by g-bougard** [comment]
Hi @Cha-sim 

you must check your update and import rules as such problem generally happens when these rules are wrongly setup.

**Comment by Cha-sim** [comment]
Hello,
I took back all of my rules.

And I found that there was a bug.

In the import and link rules, under computer.

The "does not exist" condition works like "exists" and vice versa, I don't have this problem in the other rules (printers, monitor...)

may be a translation issue. (my glpi > French)

**Comment by g-bougard** [comment]
Okay, I'm closing here as you created [glpi-project/glpi#12757](https://github.com/glpi-project/glpi/issues/12757) & [glpi-project/glpi#12758](https://github.com/glpi-project/glpi/issues/12758) and this is not a GLPI Agent issue.
