### ISSUE TITLE
GLPI Agent send to server with incorrect name

### ISSUE THREAD

**Issue by youssef-chtourou** [glpi-project/glpi-agent#224]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

I install the agent in my vm (OS : Centos)
The problem is : the name of my vm in the Glpi server is incorrect ( half of my hostname )

I create a json file to specify the name of host 

```
{
   "content": {
      "hardware": {
         "name": "kafka01.mid.domain.group"
      }
   }
}
```

and i add a cfg file like :

`additional-content=/path/to/computer-name.json
`
I install the agent as service , but in glpi server , the name of computer is : kafka01 only 

### To reproduce

N/A

### Expected behavior

N/A

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.3

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.4

### Additional context

N/A

**Comment by g-bougard** [comment]
Hi @chtourou-youssef 
in GLPI, can you download the inventory from the asset and check the "hardware" section ?

**Comment by g-bougard** [comment]
Closing without user feedback
