### ISSUE TITLE
Unnecessary information (like: "debug-threads=on") is added to the name of the Proxmox 7.2 virtual machine

### ISSUE THREAD

**Issue by Ytenok** [glpi-project/glpi-agent#229]
### Bug reporting acknowledgment

Not applicable

### Describe the bug

When glpi-agent1.4 make inventory task on Proxmox7.2-11 host machine he send unnecessary info to server side like "debug-threads=on" to the name of VM.
![2022-10-07 15-48-50 - ShareXscreenshot@1081-IT](https://user-images.githubusercontent.com/2003260/194564236-97b6dba4-9ccf-4390-ae6b-767160440486.png)

It is small part of output file "computer_0_218.json":
....
`20:46:00","tty":"?","user":"www-data","virtualmemory":76428},{"cmd":"\/usr\/bin\/kvm -id 1010 -name pve100-wts1c,debug-threads=on -no-shutdown -chardev socket,id=qmp,path=\/var\/run\/qemu-server\/1010.qmp,server=on,wait=off -mon chardev=qmp,mode=control -chardev socket,id=qmp-event,path=\/var\/run\/qmeventd.sock,reconnect=5 -mon chardev=qmp-event,mode=control -pidfile \/var\/run\/qemu-server\/1010.pid -daemonize -smbios type=1`
....
![2022-10-07 16-17-08 - ShareXscreenshot@1081-IT](https://user-images.githubusercontent.com/2003260/194563168-2fa8ddc2-fc17-4b58-93f8-7d20edb0a90b.png)

### To reproduce

1. Install Proxmox 7.2-11
2. Create some guest machines
3. Install glpi-agent 1.4 on the host machine
4. run task Inventory
5. see result on glpi10 server side

### Expected behavior

Do not add "debug-threads=on" to the name of VM :-)

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.3

**Comment by beatwinthewave** [comment]
I have exactly the same problem.

**Comment by g-bougard** [comment]
Hi @Ytenok & @beatwinthewave 
can you validate the fix with 5316012 or with the next nightly build ? Thx

**Comment by Ytenok** [comment]
> Hi @Ytenok & @beatwinthewave can you validate the fix with [5316012](https://github.com/glpi-project/glpi-agent/commit/531601264e166b5cd0e67d0646dd83d32c9cbca6) or with the next nightly build ? Thx

Works good, thank you! PS: Tried this version: glpi-agent-1.5-git53160126-linux
