### ISSUE TITLE
Collect task

### ISSUE THREAD

**Issue by Giudy** [glpi-project/glpi-agent#23]
Hello, with
glpi 9.5.5/fusioninventory 3/GLPI-Agent_v1.0-git0dbfed3d
I have a few collect task (files and register) that works but I cannot see any result anywhere.
in inventory/computer I just see the tasks performed
![immagine](https://user-images.githubusercontent.com/7987648/133303188-6f195e39-c608-4cff-81db-bbdc3dd6fd1a.png)
![immagine](https://user-images.githubusercontent.com/7987648/133308519-6bd0e8bc-2117-438a-a992-0265d2808653.png)

But don't find any tab "collect information" or something that shows me the collected information in the inventory
I did the same test with the fusioninventory agent 2.6 having the same results
Any idea?

**Comment by trasher** [comment]
Please report issue on fusioninventory plugin
