### ISSUE TITLE
Can't reach the web page of Agent 

### ISSUE THREAD

**Issue by HugzWaaa** [glpi-project/glpi-agent#237]
### Describe the bug

I took all the setup I did on a computer with which I can access the web page of the agent on a new computer, but I can't access it and I don't understand (same rule in the firewall and the registry editor is correctly set for me)

### To reproduce

1. Normal install of GLPI-Agent
2. Setup in regedit
3. Firewall rules added

### Expected behavior

have access to the agent's web page

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

Other (See additional context below)

### GLPIInventory plugin

1.0.4

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195553288-511e4868-f911-4a83-af76-bd41a29e9ac1.png)

**Comment by HugzWaaa** [comment]
- Service is Running
- Firewall allow the program

**Comment by HugzWaaa** [comment]
sorry for the label bug I do not know how to put the other

**Comment by HugzWaaa** [comment]
Have any idea for help ?

**Comment by g-bougard** [comment]
Hi @HugzWaaa 

you're telling you setup the agent in registry. Did you restart the service after that ?

**Comment by g-bougard** [comment]
And can you share a registry export of the agent configuration ? You can of course hide the "server" configuration to keep your server url private.

**Comment by HugzWaaa** [comment]
Yes I just did it again to be sure

**Comment by HugzWaaa** [comment]
yep of course

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195554930-7d3ef4e2-b847-4192-9f26-384ce16b58cf.png)

**Comment by HugzWaaa** [comment]
what do you see that is not correct?

**Comment by HugzWaaa** [comment]
And I don't know if it can help but the computer is already up in my GLPI server

**Comment by HugzWaaa** [comment]
just to say that for agent-server communication it's ok

**Comment by g-bougard** [comment]
As you masked `httpd-ip`, I guess you put the computer ip. "localhost" ip is "127.0.0.1" (IPv4) or "::1" (IPv6). So requesting "localhost" won't work.

If you have just one IP on the computer, don't set it so "0.0.0.0" will be used and this means listening on all network, including localhost.

PS: Please, stop spamming the issue comments with short messages. This is not a chat system. Breath a little and take your time.

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195557586-a0e19f88-2326-4be4-ad76-5b4d18461a11.png)
Okay great advices, on my first computer I just can access to the web page with one IP, but now thanks to you I can access it from any computer IP

And now the second computer is okay
