### ISSUE TITLE
Command line option ignored

### ISSUE THREAD

**Issue by J-C-P** [glpi-project/glpi-agent#238]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Professional support

I'm a GLPI partner

### Is your help request related to a problem?

When using the VBS to deploy the Agent on a Windows computer, the options are not taken into account if I do a "repair".

The situation : I have multiple computers with multiple versions of the Agent and some FusionInventory agents are still present.

I would like to use the VBS to upgrade all to GLPI Agent 1.4 and reconfigure the Server URL to the correct one (GLPI 10 with GlpiInventory plugin).
When I run the VBS on a computer where the agent is already version 1.4, the new settings are not taken into account.
For instance, the target URL is not changed.

I use the "Repair=Yes" option in the VBS. Verbose doesn't show any error.

Until now, I didn't try if a version upgrade (going from 1.3 to 1.4, for instance) would also change the settings.
I'm stuck at point 1 of my upgrade :-)

By the way, the documentation mention a GlpiAgent v1.5 (in the plugin section) but I don't find it. Is it a top secret version ?

Thanks,
JC

### Expected behavior

settings being overwritten

### Actions you've considered

Contacting the support :)

**Comment by g-bougard** [comment]
Hi @J-C-P 

the "Repair" option should only be used if you suspect a corruption in installed files.

The 1.5 version is indeed the nightly build until it is finally released on github releases page, so really not a secret ;-)
As a reminder, the nightly builds page is there: https://nightly.glpi-project.org/glpi-agent/
So you still can switch to that version.

I'm not a windows admin expert, so I'm not sure this is really what you need, but do you know you can use [GLPI-Agent.adml](https://github.com/glpi-project/glpi-agent/blob/develop/contrib/windows/GLPI-Agent.adml) & [GLPI-Agent.admx](https://github.com/glpi-project/glpi-agent/blob/develop/contrib/windows/GLPI-Agent.admx) to handle agent configuration via GPO ?

A work-around to keep installed agent as 1.4 is still to switch to 1.3 or nightly build and after that switch back to 1.4 with expected options. This is not optimal.
Anyway, maybe I missed to investigate if we can use a "Change" option as we are using MSI packaging. I'll make some check.

**Comment by g-bougard** [comment]
Hi @J-C-P 

indeed I finally understand how you can reconfigure an agent with the currently installed version.

You just need to add on your commandline the following option: `REINSTALL=feat_AGENT`

Can you try it and confirm this is what you needed ? Thx

**Comment by J-C-P** [comment]
Thanks for your quick followup !

I tried the REINSTALL option (do we agree it is not it the documentation ?) and it didn't change the server URL, for instance. It just reinstall de same version over the old one but do not take care of the setup options.

The same test without the "repair=yes" in the VBS do not work either as it doesn't run the setup at all.

**Comment by g-bougard** [comment]
With my test I was able to change DEBUG value but didn't try SERVER...

But if you used the repair option I guess this normally doesn't work. And as the VBS checks the installed version to decide if it's time to install, it's also normal this didn't work.

I decided to update the VBS to support a `Reconfigure` option. By default, it is enabled and will add the `REINSTALL=feat_AGENT` option if REINSTALL option is not set.
Let me know if this works for you.

The updated vbs is still there: [glpi-agent-deployment.vbs](https://github.com/glpi-project/glpi-agent/blob/develop/contrib/windows/glpi-agent-deployment.vbs)

**Comment by J-C-P** [comment]
It's working great :-)

I had to correct a little error in the vbs.
The "Reconfigure" variable was undefined.
I made the change on line 55 (I don't understand how Git works... I don't know how to fork, push, submit... Sorry)
`Dim Repair, Verbose`
->
`Dim Repair, Reconfigure, Verbose`

**Comment by g-bougard** [comment]
Nice shot, thank you for the validation.
I'll fix the script ;-)
