### ISSUE TITLE
Problem with networkDiscovery task

### ISSUE THREAD

**Issue by HugzWaaa** [glpi-project/glpi-agent#239]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Is your help request related to a problem?

Yes
![image](https://user-images.githubusercontent.com/113598277/195573747-32f35a79-8e52-4cc5-a5f7-6d6ff75e0503.png)
It's the networkDiscovery log, in this we can see that it finds information about equipment present in a client network (here the import is refused because of the rules but I deactivated them all so that the import is no longer refused), so I retested once the rules were deactivated, so it imports them well now but I have 2 concerns:

- The first one is that they are not computers but they are classified in the computer category

- The second is that when the equipment goes up in the glpi (as a computer) the information that we can see in the log does not go up with 

![image](https://user-images.githubusercontent.com/113598277/195575573-8858dbd0-a2b8-4388-b21c-61f621502400.png)

### Expected behavior

If possible the best solution (for my case) would be that all the equipment discovered by networkDiscovery goes directly into the network equipment category (no matter the nature of the equipment in my case, but if the equipment is discovered by networkDiscovery then it must go into network equipment), and also that the equipment goes back with the information we see in the log

### Actions you've considered

None actually because I don't understand why the info is available in the netDiscovery log but not in the computer category once it is imported

And for the equipment that are discovered by netDiscovery to be classified in the network equipment category I think that I would have to modify a small part of the source code (on the server side or agent side, even if on the server side it would be more interesting because then I would not have to make the modification X the number of agents) but I have no idea how to do it

**Comment by stonebuzz** [comment]
@HugzWaaa 

```glpiinventory``` is only made for Network Equipment like ```Printer``` or ```NetworkEquipment```

Is not designed for ```Computer``` inventory 

If an asset is seen as ```Computer``` there are several reasons for this : 

- It's a 'real' ```Computer``` so you need to install glpi-agent on it.
- it's a real ```Network Equipment``` but glpi-agent did not find the type (```Printer``` or ```NetworkEquipment```) according to sysobject.ids (from ```SNMP``` ) due to bad SNMP crendential defined in IP range. 

From the server where the agent do the discovery is installed can you run this and past here the result : 

```
snmpget -v2c -c public "Network Asset IP" 1.3.6.1.2.1.1.2.0
```

Best regards

**Comment by HugzWaaa** [comment]
![image](https://user-images.githubusercontent.com/113598277/195594232-5a430320-dfda-4f82-bdb8-30c716b15df3.png)
I ran the command on the client computer where the networkDiscovery was (I did not put only one credential in the IP range for info)

would you have an idea of what I have to do so that it is recognized as network equipment by the agent (because I am thanks to the MAC seen in the logs that it is indeed a network equipment)

**Comment by g-bougard** [comment]
Hi @HugzWaaa 

honestly you're in the wrong place to claim such basic help. Better use the [forum](https://forum.glpi-project.org/) where other involved people from the community could really help you. You can even ask on [that community discord](https://discord.gg/qgDXNwS) if you're familiar with Discord.

Claiming help here should be your last resort if you don't find any answer elsewhere.

**Comment by HugzWaaa** [comment]
So if it's so basic I don't really understand why it doesn't work from the start, and then it's so basic the time to write and send your useless message why didn't you help me fix the problem instead, too easy for you is that? especially since stonebuzz him at least try to help me and you come in the conversation, not only you try nothing to help me but also you tell me that a support where you can open issues to get help is not the right place to ask for help, you know if your support is not used to help then it's useless like your message
