### ISSUE TITLE
Monitors serial is not showing properly

### ISSUE THREAD

**Issue by gopalatvvs** [glpi-project/glpi-agent#24]
I have checked the Dell D2020H Monitor serial number is  not showing properly in GLPI-9.5.5 and fusioninventory-agent is 2.6. and GLPI-9.5.4 and fusioninventory-agent is 2.5. It is showing service tag instead of serial number.

output is :

<BASE64>AP///////wAQrB7xSU04QQoeAQMOKxh46mnVolZPoCgPUFSlSgBxT4HAgQCpwAEBAQEBAQEBMCpAyGCEZDAYUBMAsPMQAAAeAAAA/wBKTktWWDIzCiAgICAgAAAA/ABERUxMIEQyMDIwSAogAAAA/QA4TB5QEQAKICAgICAgACU=</BASE64>
      <CAPTION>DELL D2020H</CAPTION>
      <DESCRIPTION>10/2020</DESCRIPTION>
      <MANUFACTURER>Dell Inc.</MANUFACTURER>
      <PORT>VGA</PORT>
      <SERIAL>JNKVX23</SERIAL>
    </MONITORS>
    <MONITORS>

I don't know why it is convert into Base64. Could you please help to me in this case it would be great. Even Acer monitors also.
So i want original serial number instead of coverting Base 64 and it is coming alphanumberic. 

Could you please look into this issue

**Comment by flegastelois** [comment]
Dear GLPI user,

This issue is not related to GLPI Agent.

You may also consider taking a [subscription](https://glpi-project.org/subscriptions/) to get professionnal support or contact [GLPI editor team](https://portal.glpi-network.com/contact-us) directly.

Kind regards,
