### ISSUE TITLE
(Bad file descriptor), SSL connect attempt failed tls_process_server_certificate:certificate verify failed using ca-cert-dir on 1.4 ?

### ISSUE THREAD

**Issue by SteadEXE** [glpi-project/glpi-agent#242]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Hello,

I discovered that a lot of my agent stopped to inventories after upgrading to 1.3 or 1.4.
After investigating it seems that agent are up, but cannot verify SSL certificate.

I have ca-cert-dir pointing to a directory where there are the certificate signature. 
It was working up to 1.2 without any issue.
(I used the procedure https://glpi-agent.readthedocs.io/en/latest/configuration.html)

If I turn no-ssl-check to 1 it works.
If I use the ssl-fingerprint it works aswell.

The certificate is a wildcard certificate for our company FQDN.

### To reproduce

1. Install an agent
2. Configure the ca-cert-dir to works.
3. Run an inventory

### Expected behavior

Agent should locate the proper signature and continue the inventory.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.3

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.4

### Additional context
```
[Fri Oct 14 10:47:51 2022][info] GLPI Agent exiting (11872)
[Fri Oct 14 10:47:54 2022][debug] Logger backend File initialized
[Fri Oct 14 10:47:54 2022][debug] GLPI Agent (1.4)
[Fri Oct 14 10:47:54 2022][debug] Configuration directory: C:/Program Files/GLPI-Agent/etc
[Fri Oct 14 10:47:54 2022][debug] Data directory: C:/Program Files/GLPI-Agent/share
[Fri Oct 14 10:47:54 2022][debug] Storage directory: C:\Program Files\GLPI-Agent\var
[Fri Oct 14 10:47:54 2022][debug] Lib directory: C:/Program Files/GLPI-Agent/perl/agent
[Fri Oct 14 10:47:54 2022][debug] [target server0] Next server contact planned for Fri Oct 14 10:48:34 2022
[Fri Oct 14 10:47:54 2022][debug2] getAvailableTasks() : add of task Collect version 2.8
[Fri Oct 14 10:47:54 2022][debug2] getAvailableTasks() : add of task Deploy version 2.10
[Fri Oct 14 10:47:54 2022][debug2] getAvailableTasks() : add of task Inventory version 1.12
[Fri Oct 14 10:47:54 2022][debug2] getAvailableTasks() : add of task RemoteInventory version 1.0
[Fri Oct 14 10:47:54 2022][debug2] Preparing execution plan
[Fri Oct 14 10:47:54 2022][debug] Available tasks:
[Fri Oct 14 10:47:54 2022][debug] - Collect: 2.8
[Fri Oct 14 10:47:54 2022][debug] - Deploy: 2.10
[Fri Oct 14 10:47:54 2022][debug] - Inventory: 1.12
[Fri Oct 14 10:47:54 2022][debug] - RemoteInventory: 1.0
[Fri Oct 14 10:47:54 2022][debug] target server0: server https://glpi.[redacted].fr/plugins/glpiinventory/
[Fri Oct 14 10:47:54 2022][debug] Planned tasks for server0: Deploy,Inventory
[Fri Oct 14 10:47:54 2022][debug] Provided by Teclib Edition
[Fri Oct 14 10:47:54 2022][debug] Installer built on Fri Jul  1 09:35:20 2022 UTC
[Fri Oct 14 10:47:54 2022][debug] Built with Strawberry Perl 5.36.0
[Fri Oct 14 10:47:54 2022][debug] Built on github actions windows image for glpi-project/glpi-agent repository
[Fri Oct 14 10:47:54 2022][info] GLPI Agent service starting
[Fri Oct 14 10:47:54 2022][debug] Trusted target ip: 192.168.28.7/32, ::ffff:c0a8:1c07/128
[Fri Oct 14 10:47:54 2022][debug] Trusted client ip: 127.0.0.1/32, ::ffff:7f00:1/128, ::1/128
[Fri Oct 14 10:47:54 2022][debug] Trusted client ip: 127.0.0.1/32, ::ffff:7f00:1/128, ::1/128
[Fri Oct 14 10:47:54 2022][debug] Trusted client ip: 192.168.28.7/32, ::ffff:c0a8:1c07/128
[Fri Oct 14 10:47:54 2022][debug] [http server] Trying to load Inventory Server plugin
[Fri Oct 14 10:47:54 2022][debug] [inventory server plugin] Initializing Inventory v1.1 Server plugin...
[Fri Oct 14 10:47:54 2022][debug] [inventory server plugin] Loading Inventory Server plugin configuration from C:/Program Files/GLPI-Agent/etc/inventory-server-plugin.cfg
[Fri Oct 14 10:47:54 2022][debug] [target listener] Next tasks run planned for Fri Oct 14 11:45:12 2022
[Fri Oct 14 10:47:54 2022][debug] [http server] HTTPD Inventory Server plugin loaded but disabled
[Fri Oct 14 10:47:54 2022][debug] [http server] Trying to load Proxy Server plugin
[Fri Oct 14 10:47:54 2022][debug] [proxy server plugin] Initializing Proxy v2.1 Server plugin...
[Fri Oct 14 10:47:54 2022][debug] [proxy server plugin] Loading Proxy Server plugin configuration from C:/Program Files/GLPI-Agent/etc/proxy-server-plugin.cfg
[Fri Oct 14 10:47:54 2022][debug] [http server] HTTPD Proxy Server plugin loaded but disabled
[Fri Oct 14 10:47:54 2022][debug] [http server] Trying to load SecondaryProxy Server plugin
[Fri Oct 14 10:47:54 2022][debug] [proxy2 server plugin] Initializing SecondaryProxy v1.1 Server plugin...
[Fri Oct 14 10:47:54 2022][debug] [proxy2 server plugin] Loading SecondaryProxy Server plugin configuration from C:/Program Files/GLPI-Agent/etc/proxy2-server-plugin.cfg
[Fri Oct 14 10:47:54 2022][debug] [http server] HTTPD SecondaryProxy Server plugin loaded but disabled
[Fri Oct 14 10:47:54 2022][debug] [http server] Trying to load SSL Server plugin
[Fri Oct 14 10:47:54 2022][debug] [ssl server plugin] Initializing SSL v1.1 Server plugin...
[Fri Oct 14 10:47:54 2022][debug] [ssl server plugin] Loading SSL Server plugin configuration from C:/Program Files/GLPI-Agent/etc/ssl-server-plugin.cfg
[Fri Oct 14 10:47:54 2022][debug] [http server] HTTPD SSL Server plugin loaded but disabled
[Fri Oct 14 10:47:54 2022][debug] [http server] Trying to load Test Server plugin
[Fri Oct 14 10:47:54 2022][debug] [server test plugin] Initializing Test v1.4 Server plugin...
[Fri Oct 14 10:47:54 2022][debug] [server test plugin] Loading Test Server plugin configuration from C:/Program Files/GLPI-Agent/etc/server-test-plugin.cfg
[Fri Oct 14 10:47:54 2022][debug] [http server] HTTPD Test Server plugin loaded but disabled
[Fri Oct 14 10:47:54 2022][debug] [http server] Trying to load ToolBox Server plugin
[Fri Oct 14 10:47:54 2022][debug] [toolbox plugin] Initializing ToolBox v1.0 Server plugin...
[Fri Oct 14 10:47:54 2022][debug] [toolbox plugin] Loading ToolBox Server plugin configuration from C:/Program Files/GLPI-Agent/etc/toolbox-plugin.cfg
[Fri Oct 14 10:47:54 2022][debug] [http server] HTTPD ToolBox Server plugin loaded but disabled
[Fri Oct 14 10:47:54 2022][info] [http server] HTTPD service started on port 62354
[Fri Oct 14 10:47:54 2022][debug2] Looking for Win32_Processor class WMI objects
[Fri Oct 14 10:47:55 2022][debug] Agent memory usage before freeing memory: WSS=115863552 PFU=105168896
[Fri Oct 14 10:47:55 2022][info] GLPI Agent memory usage: WSS=3072000 PFU=105168896
[Fri Oct 14 10:47:55 2022][debug] Running in background mode
[Fri Oct 14 10:47:55 2022][info] target server0: next run: Fri Oct 14 10:48:34 2022 - https://glpi.[redacted].fr/plugins/glpiinventory/
[Fri Oct 14 10:48:05 2022][debug] target server0: init event for Deploy task
[Fri Oct 14 10:48:05 2022][debug] [target server0] New storage maintenance event on deploy task
[Fri Oct 14 10:48:05 2022][debug2] [target server0] Event scheduled in 120 seconds
[Fri Oct 14 10:48:06 2022][debug] target server0: init event for Inventory task
[Fri Oct 14 10:48:34 2022][info] target server0: server https://glpi.[redacted].fr/plugins/glpiinventory/
[Fri Oct 14 10:48:34 2022][debug] [http client] Using Compress::Zlib for compression
[Fri Oct 14 10:48:34 2022][info] sending prolog request to server0
[Fri Oct 14 10:48:34 2022][debug2] [http client] sending message:
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <DEVICEID>X360G8-IT-01.[redacted].local-2022-08-23-15-05-14</DEVICEID>
  <QUERY>PROLOG</QUERY>
  <TOKEN>12345678</TOKEN>
</REQUEST>
[Fri Oct 14 10:48:34 2022][debug] [http client] Updating keystore known certificates
[Fri Oct 14 10:48:34 2022][debug2] Changing to 'C:/Program Files/GLPI-Agent/var/keystore-export-KQZnCv' temporary folder
[Fri Oct 14 10:48:34 2022][debug2] executing certutil -Store -Silent -Split
[Fri Oct 14 10:48:34 2022][debug2] executing certutil -Store -Silent -Enterprise -Split
[Fri Oct 14 10:48:34 2022][debug2] executing certutil -encode 109f1caed645bb78b3ea2b94c0697c740733031c.crt temp.cer
[Fri Oct 14 10:48:34 2022][debug2] executing certutil -encode 8881a2232c01e14e4f6bed5640de18dcf27e58a7.crt temp.cer
[Fri Oct 14 10:48:34 2022][debug2] executing certutil -encode 90537c348f3617df8d939ce9d09b0527eea2700b.crt temp.cer
[Fri Oct 14 10:48:34 2022][debug2] executing certutil -encode a5f0a2eaa40ae95a9ff86a9cd17777425f1a7f49.crt temp.cer
[Fri Oct 14 10:48:34 2022][debug2] executing certutil -encode d4ffdb19ba590fffaa34db5f4b568706a2978436.crt temp.cer
[Fri Oct 14 10:48:34 2022][debug2] executing certutil -encode d559a586669b08f46a30a133f8a9ed3d038e2ea8.crt temp.cer
[Fri Oct 14 10:48:34 2022][debug2] executing certutil -encode ef3b1b70c3aeb97967fbc6db9cfcf9d5e90890f8.crt temp.cer
[Fri Oct 14 10:48:35 2022][debug2] executing certutil -encode fee449ee0e3965a5246f000e87fde2a065fd89d4.crt temp.cer
[Fri Oct 14 10:48:35 2022][debug2] executing certutil -encode ff03bbe2eb937ee7b68b66f2df23cae1f1c06e66.crt temp.cer
[Fri Oct 14 10:48:35 2022][debug2] Changing back to 'C:/Program Files/GLPI-Agent/perl/bin' folder
[Fri Oct 14 10:48:35 2022][error] [http client] internal response: 500 Can't connect to glpi.[redacted].fr:443 (Bad file descriptor), SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
[Fri Oct 14 10:48:35 2022][error] No answer from server at https://glpi.[redacted].fr/plugins/glpiinventory/
```

**Comment by g-bougard** [comment]
Hi @SteadEXE 

can you try the perl oneliner I proposed to test there for another issue ?
https://github.com/glpi-project/glpi-agent/issues/226#issuecomment-1272912636

Maybe I missed something but while debug=2 is set, we should have more debug on SSL stack and your log doesn't have such debug. The oneliner should enable it and this may help to understand what's going on.

Try the onleline for https://github.com/ and for your own glpi server.

P.S.: For your glpi server, don't forget to add your `ca-cert-dir` option. You can verify with and without.

**Comment by SteadEXE** [comment]
Hi @g-bougard
Thanks for the reply.

With my domain with ca-cert-dir enabled:

```
C:\Program Files\GLPI-Agent>perl\bin\glpi-agent.exe -Iperl\agent -MConfig -MGLPI::Agent::Logger -MGLPI::Agent::HTTP::Client -MURI -MHTTP::Request -e "$url = shift @ARGV; %conf = @ARGV; $req = GLPI::Agent::HTTP::Client->new(logger => GLPI::Agent::Logger->new(%conf), config => \%conf); $test = $req->request(HTTP::Request->new(GET => URI->new($url))); undef $req; print 'STATUS: ', $test->status_line, \"\nperl uname: \" , $Config{myuname}" https://glpi.[redacted].fr/ debug 2 no-ssl-check 0 ca-cert-dir \\[redacted].local\netlogon\glpi\certs
[debug] Logger backend Stderr initialized
[debug] GLPI Agent (1.4)
[debug] [http client] Updating keystore known certificates
[debug2] Changing to 'C:/Users/jbao/AppData/Local/Temp/keystore-export-8oXPoV' temporary folder
[debug2] executing certutil -Store -Silent -Split
[debug2] executing certutil -Store -Silent -Enterprise -Split
[debug2] executing certutil -encode 109f1caed645bb78b3ea2b94c0697c740733031c.crt temp.cer
[debug2] executing certutil -encode 8881a2232c01e14e4f6bed5640de18dcf27e58a7.crt temp.cer
[debug2] executing certutil -encode 90537c348f3617df8d939ce9d09b0527eea2700b.crt temp.cer
[debug2] executing certutil -encode a5f0a2eaa40ae95a9ff86a9cd17777425f1a7f49.crt temp.cer
[debug2] executing certutil -encode d4ffdb19ba590fffaa34db5f4b568706a2978436.crt temp.cer
[debug2] executing certutil -encode d559a586669b08f46a30a133f8a9ed3d038e2ea8.crt temp.cer
[debug2] executing certutil -encode ef3b1b70c3aeb97967fbc6db9cfcf9d5e90890f8.crt temp.cer
[debug2] executing certutil -encode fee449ee0e3965a5246f000e87fde2a065fd89d4.crt temp.cer
[debug2] executing certutil -encode ff03bbe2eb937ee7b68b66f2df23cae1f1c06e66.crt temp.cer
[debug2] Changing back to 'C:/Program Files/GLPI-Agent' folder
DEBUG: .../IO/Socket/SSL.pm:2961: new ctx 64879792
DEBUG: .../IO/Socket/SSL.pm:704: socket not yet connected
DEBUG: .../IO/Socket/SSL.pm:706: socket connected
DEBUG: .../IO/Socket/SSL.pm:729: ssl handshake not started
DEBUG: .../IO/Socket/SSL.pm:771: using SNI with hostname glpi.[redacted].fr
DEBUG: .../IO/Socket/SSL.pm:806: request OCSP stapling
DEBUG: .../IO/Socket/SSL.pm:822: set socket to non-blocking to enforce timeout=180
DEBUG: .../IO/Socket/SSL.pm:836: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:839: done Net::SSLeay::connect -> -1
DEBUG: .../IO/Socket/SSL.pm:849: ssl handshake in progress
DEBUG: .../IO/Socket/SSL.pm:859: waiting for fd to become ready: SSL wants a read first
DEBUG: .../IO/Socket/SSL.pm:879: socket ready, retrying connect
DEBUG: .../IO/Socket/SSL.pm:836: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:2805: ok=0 [1] /C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust RSA Certification Authority/C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Organization Validation Secure Server CA
DEBUG: .../IO/Socket/SSL.pm:839: done Net::SSLeay::connect -> -1
DEBUG: .../IO/Socket/SSL.pm:842: SSL connect attempt failed

DEBUG: .../IO/Socket/SSL.pm:842: local error: SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
DEBUG: .../IO/Socket/SSL.pm:845: fatal SSL error: SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
DEBUG: .../lib/Net/HTTPS.pm:67: ignoring less severe local error 'IO::Socket::IP configuration failed', keep 'SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed'
DEBUG: .../IO/Socket/SSL.pm:3010: free ctx 64879792 open=64879792
DEBUG: .../IO/Socket/SSL.pm:3014: free ctx 64879792 callback
DEBUG: .../IO/Socket/SSL.pm:3021: OK free ctx 64879792
[error] [http client] internal response: 500 Can't connect to glpi.[redacted].fr:443 (Bad file descriptor), SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
STATUS: 500 Can't connect to glpi.[redacted].fr:443 (Bad file descriptor)
perl uname: Win32 strawberry-perl 5.36.0.1 #1 Wed Jun 15 15:36:57 2022 x64
```

With github:

```
C:\Program Files\GLPI-Agent>perl\bin\glpi-agent.exe -Iperl\agent -MConfig -MGLPI::Agent::Logger -MGLPI::Agent::HTTP::Client -MURI -MHTTP::Request -e "$url = shift @ARGV; %conf = @ARGV; $req = GLPI::Agent::HTTP::Client->new(logger => GLPI::Agent::Logger->new(%conf), config => \%conf); $test = $req->request(HTTP::Request->new(GET => URI->new($url))); undef $req; print 'STATUS: ', $test->status_line, \"\nperl uname: \" , $Config{myuname}" https://github.com/ debug 2 no-ssl-check 0
[debug] Logger backend Stderr initialized
[debug] GLPI Agent (1.4)
[debug] [http client] Updating keystore known certificates
[debug2] Changing to 'C:/Users/jbao/AppData/Local/Temp/keystore-export-POszi3' temporary folder
[debug2] executing certutil -Store -Silent -Split
[debug2] executing certutil -Store -Silent -Enterprise -Split
[debug2] executing certutil -encode 109f1caed645bb78b3ea2b94c0697c740733031c.crt temp.cer
[debug2] executing certutil -encode 8881a2232c01e14e4f6bed5640de18dcf27e58a7.crt temp.cer
[debug2] executing certutil -encode 90537c348f3617df8d939ce9d09b0527eea2700b.crt temp.cer
[debug2] executing certutil -encode a5f0a2eaa40ae95a9ff86a9cd17777425f1a7f49.crt temp.cer
[debug2] executing certutil -encode d4ffdb19ba590fffaa34db5f4b568706a2978436.crt temp.cer
[debug2] executing certutil -encode d559a586669b08f46a30a133f8a9ed3d038e2ea8.crt temp.cer
[debug2] executing certutil -encode ef3b1b70c3aeb97967fbc6db9cfcf9d5e90890f8.crt temp.cer
[debug2] executing certutil -encode fee449ee0e3965a5246f000e87fde2a065fd89d4.crt temp.cer
[debug2] executing certutil -encode ff03bbe2eb937ee7b68b66f2df23cae1f1c06e66.crt temp.cer
[debug2] Changing back to 'C:/Program Files/GLPI-Agent' folder
DEBUG: .../IO/Socket/SSL.pm:2961: new ctx 54338048
DEBUG: .../IO/Socket/SSL.pm:704: socket not yet connected
DEBUG: .../IO/Socket/SSL.pm:706: socket connected
DEBUG: .../IO/Socket/SSL.pm:729: ssl handshake not started
DEBUG: .../IO/Socket/SSL.pm:771: using SNI with hostname github.com
DEBUG: .../IO/Socket/SSL.pm:806: request OCSP stapling
DEBUG: .../IO/Socket/SSL.pm:822: set socket to non-blocking to enforce timeout=180
DEBUG: .../IO/Socket/SSL.pm:836: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:839: done Net::SSLeay::connect -> -1
DEBUG: .../IO/Socket/SSL.pm:849: ssl handshake in progress
DEBUG: .../IO/Socket/SSL.pm:859: waiting for fd to become ready: SSL wants a read first
DEBUG: .../IO/Socket/SSL.pm:879: socket ready, retrying connect
DEBUG: .../IO/Socket/SSL.pm:836: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:2805: ok=1 [2] /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA
DEBUG: .../IO/Socket/SSL.pm:2805: ok=1 [1] /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA/C=US/O=DigiCert Inc/CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
DEBUG: .../IO/Socket/SSL.pm:2805: ok=1 [0] /C=US/O=DigiCert Inc/CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1/C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=github.com
DEBUG: .../IO/Socket/SSL.pm:1781: scheme=www cert=68190976
DEBUG: .../IO/Socket/SSL.pm:1791: identity=github.com cn=github.com alt=2 github.com 2 www.github.com
DEBUG: .../IO/Socket/SSL.pm:2852: did not get stapled OCSP response
DEBUG: .../IO/Socket/SSL.pm:839: done Net::SSLeay::connect -> 1
DEBUG: .../IO/Socket/SSL.pm:894: ssl handshake done
DEBUG: .../IO/Socket/SSL.pm:3010: free ctx 54338048 open=54338048
DEBUG: .../IO/Socket/SSL.pm:3014: free ctx 54338048 callback
DEBUG: .../IO/Socket/SSL.pm:3021: OK free ctx 54338048
STATUS: 200 OK
perl uname: Win32 strawberry-perl 5.36.0.1 #1 Wed Jun 15 15:36:57 2022 x64
```

I hope it helps

**Comment by g-bougard** [comment]
Hi @SteadEXE 

I can confirm the bug as I finally managed to reproduce. If I setup `ca-cert-dir`, the keystore export feature just broke the folder lookup. And this doesn't break the `ca-cert-file` option.

**Comment by g-bougard** [comment]
@SteadEXE 
Can you validate your issue is fixed with next nightly build ?
Thank you

**Comment by SteadEXE** [comment]
@g-bougard it does work with latest nightly.
Fun fact, if there was ca-cert-dir and ssl-fingerprint set, ssl-fingerprint was ignored. 
By the way I think both should not be used at the same time.

I assume ssl-fingerprint only work on certificate not on ca-cert right?

**Comment by g-bougard** [comment]
Thank you for the confirmation.
Not sure, but I better guess the openssl lib first try to find a CA certificate under ca-cert-dir, then if none matches the required one, ssl-fingerprint should apply and trust the server certificate if it matches. Have you tried to remove your certificate wrong ca-cert-dir ?

**Comment by SteadEXE** [comment]
I did not check anything, except ssl-fingerprint and removing ca-cert-dir option.
I deployed the GPO to use SSL-fingerprint instead of ca-cert-dir until 1.5 lands, looks like all my 350 agents are talking to GLPI again. 👍

**Comment by vollkommenIrrelevant** [comment]
How check GLPI if the certificate is valid? We have a selfsigned root certificate on every client and a chained sub-certificate (sorry for bad translation) for glpi on the glpi-server. If I set no-ssl-check to 0 I got a error:

```
[Mon Oct 24 17:49:19 2022][error] [http client] internal response: 500 Can't connect to X.Y.lu:443 (Bad file descriptor), SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
[Mon Oct 24 17:49:19 2022][error] No answer from server at https://X.Y.lu/front/inventory.php
[Mon Oct 24 17:49:19 2022][info] target server0: next run: Mon Oct 24 17:51:19 2022 - https://X.Y.lu/front/inventory.php
```

If I access to glpi via Browser, eg. Chrome I got "connection secure", but there is no green adressbar. What is expected behavior of glpi-agent (latest nightly)?

**Comment by g-bougard** [comment]
> How check GLPI if the certificate is valid? We have a selfsigned root certificate on every client and a chained sub-certificate (sorry for bad translation) for glpi on the glpi-server. If I set no-ssl-check to 0 I got a error:
> 
> ```
> [Mon Oct 24 17:49:19 2022][error] [http client] internal response: 500 Can't connect to X.Y.lu:443 (Bad file descriptor), SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
> [Mon Oct 24 17:49:19 2022][error] No answer from server at https://X.Y.lu/front/inventory.php
> [Mon Oct 24 17:49:19 2022][info] target server0: next run: Mon Oct 24 17:51:19 2022 - https://X.Y.lu/front/inventory.php
> ```
> 
> If I access to glpi via Browser, eg. Chrome I got "connection secure", but there is no green adressbar. What is expected behavior of glpi-agent (latest nightly)?

If the agent knows nothing about your private authority (the GLPI server for self-signed certificate), it normally doesn't trust the server. You can copy the private ca cert on the client side and put its path via `ca-cert-file`, or you can extract its SSL fingerprint and set it on `ssl-fingerprint` option (check #246).
In your browser, you probably accepted manually in the past the not publicly trusted certificate of your server as you know you can trust it.

**Comment by vollkommenIrrelevant** [comment]
> > How check GLPI if the certificate is valid? We have a selfsigned root certificate on every client and a chained sub-certificate (sorry for bad translation) for glpi on the glpi-server. If I set no-ssl-check to 0 I got a error:
> > ```
> > [Mon Oct 24 17:49:19 2022][error] [http client] internal response: 500 Can't connect to X.Y.lu:443 (Bad file descriptor), SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
> > [Mon Oct 24 17:49:19 2022][error] No answer from server at https://X.Y.lu/front/inventory.php
> > [Mon Oct 24 17:49:19 2022][info] target server0: next run: Mon Oct 24 17:51:19 2022 - https://X.Y.lu/front/inventory.php
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If I access to glpi via Browser, eg. Chrome I got "connection secure", but there is no green adressbar. What is expected behavior of glpi-agent (latest nightly)?
> 
> If the agent knows nothing about your private authority (the GLPI server for self-signed certificate), it normally doesn't trust the server. You can copy the private ca cert on the client side and put its path via `ca-cert-file`, or you can extract its SSL fingerprint and set it on `ssl-fingerprint` option (check #246). In your browser, you probably accepted manually in the past the not publicly trusted certificate of your server as you know you can trust it.

 

We deployed our self-signed ca-cert via gpo to Public Key Policies/Trusted Root Certification Authorities to the (Windows) Computer so the Agent should know the ca-cert without ca-cert-file. With Chrome (for example) its working fine, but without green adressbar.
=> Error Message in Agent from above

If I give the ca-cert directly via the param --ca-cert-file => running fine with no ssl-check 0.
=> So there may be a Problem with the Agent to getting the ca-cert-file from Public Key Policies/Trusted Root Certification Authorities. Is this possible and is my conclusion correct?

**Comment by g-bougard** [comment]
This is possible if the agent doesn't find it in the keystore it exports.
Since GLPI Agent 1.3, the agent runs the following commands to export the available certificates:
```
certutil -Store -Silent -Split
certutil -Store -Silent -Enterprise -Split
```
Is your certificate available from there ? Also can you confirm which agent version you're using ? Eventually enabled debug2 level to check what is really exported.

**Comment by vollkommenIrrelevant** [comment]
> ```
> certutil -Store -Silent -Split
> ```
there are some certificates, but not the missing ca-cert-file
> ```
> certutil -Store -Silent -Enterprise -Split 
> ```
CA "Zwischenzertifizierungsstellen"

> Is your certificate available from there ? Also can you confirm which agent version you're using ? Eventually enabled debug2 level to check what is really exported.

I found the solution: 
If I copy the ca-cert file manually into CA "Zwischenzertifizierungsstellen" =>working.
If the ca-cert is only in "Vertrauenswürdige Stammzertifizierungsstellen" (something like trusted root certification authorities) => not working
=> I think the agent should have to check trusted root certification authorities for the ca-certs.

I`m actually using for this tests the last nightly build from last week...

**Comment by g-bougard** [comment]
Your certificate is probably in another specific store. If you can tell me which one to use, I can add it to the export. You have the official documentation there: https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/certutil#-store
Do you think you can find the right syntax to export the store where your certificate is included ?

**Comment by vollkommenIrrelevant** [comment]
> Your certificate is probably in another specific store. If you can tell me which one to use, I can add it to the export. You have the official documentation there: https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/certutil#-store Do you think you can find the right syntax to export the store where your certificate is included ?

This would be great. If I write `certutil -Store root` I can see the correct ca-certificate...

**Comment by g-bougard** [comment]
So can you confirm it works for you if you apply the following patch to an installed agent:
```diff
diff --git a/perl/agent/GLPI/Agent/HTTP/Client.pm b/perl/agent/GLPI/Agent/HTTP/Client.pm
index 3b0ff833f..6155ae225 100644
--- a/perl/agent/GLPI/Agent/HTTP/Client.pm
+++ b/perl/agent/GLPI/Agent/HTTP/Client.pm
@@ -396,6 +396,10 @@ sub _KeyChain_or_KeyStore_Export {
                 command => "certutil -Store -Silent -Split",
                 logger  => $logger
             );
+            getAllLines(
+                command => "certutil -Silent -Split -Store Root",
+                logger  => $logger
+            );
             getAllLines(
                 command => "certutil -Store -Silent -Enterprise -Split",
                 logger  => $logger
```

**Comment by g-bougard** [comment]
For your information, with 95f6647, next nightly build will run the following commands to export all possible CA & Root certificates from the windows keystore:
```
certutil -Silent -Split -Store CA
certutil -Silent -Split -Store Root
certutil -Silent -Split -Enterprise -Store CA
certutil -Silent -Split -Enterprise -Store Root
certutil -Silent -Split -GroupPolicy -Store CA
certutil -Silent -Split -GroupPolicy -Store Root
```
in place of just the first and the third of this list.

**Comment by vollkommenIrrelevant** [comment]
> For your information, with [95f6647](https://github.com/glpi-project/glpi-agent/commit/95f664763eda9285a5f9ff478d538a71faebe9c7), next nightly build will run the following commands to export all possible CA & Root certificates from the windows keystore:
> 
> ```
> certutil -Silent -Split -Store CA
> certutil -Silent -Split -Store Root
> certutil -Silent -Split -Enterprise -Store CA
> certutil -Silent -Split -Enterprise -Store Root
> certutil -Silent -Split -GroupPolicy -Store CA
> certutil -Silent -Split -GroupPolicy -Store Root
> ```
> 
> in place of just the first and the third of this list.

It seems ok - but to be sure due a lot of changes for testing i will check with the next nightly build with a other client.

**Comment by vollkommenIrrelevant** [comment]
Working like a charme for the clients with windows 10 :-)
`msiexec.exe /i "\\X\GLPI-Agent-1.5-git95f66476-x64.msi" /quiet ADDLOCAL=feat_AGENT ADD_FIREWALL_EXCEPTION=1 server='https://Y/front/inventory.php' RUNNOW=1
`
For Windows Server 2012 there seems still a problem, I got the same error message as above.

**Comment by g-bougard** [comment]
Hi @vollkommenIrrelevant 
for Windows Server 2012, are you sure the certificate is deployed ? If yes, can you investigate and tell me which options I need to use with `certutil` command to find it ?

**Comment by vollkommenIrrelevant** [comment]
> Hi @vollkommenIrrelevant for Windows Server 2012, are you sure the certificate is deployed ? If yes, can you investigate and tell me which options I need to use with `certutil` command to find it ?

yes it`s deployed - but i have to think about the problem because i do not understand the problem actual. Maybe i will test with a nother server when i have a bit time...

**Comment by vollkommenIrrelevant** [comment]
> > Hi @vollkommenIrrelevant for Windows Server 2012, are you sure the certificate is deployed ? If yes, can you investigate and tell me which options I need to use with `certutil` command to find it ?
> 
> yes it`s deployed - but i have to think about the problem because i do not understand the problem actual. Maybe i will test with a nother server when i have a bit time...

Ok, i checked with following conclusion:
- Installed as Domain Admin in a testdomain with testserver => not working
- Installed as User on a production system with Windows Server 2012 => working

Due working as Domain Admin ist not realy best praktice - for me it`s fine with Windows Server 2012 to.
