### ISSUE TITLE
PC with Windows 8.1 not being inventoried

### ISSUE THREAD

**Issue by galarov** [glpi-project/glpi-agent#243]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

The issue is discussed here: https://github.com/glpi-project/glpi-agent/issues/161
It was closed so I decided to re-start the discussion.

Hello,

I've got the same problem with glpi-agent on Windows 8.1.

GLPI Server: GLPI 10.0.2
GLPI Agent: GLPI-Agent-1.4

Problem is as stated above: After installing the agent on a computer with Windows 8.1 inventorisation is done allright, but there is an error when the computer is trying to send the report to the server. I observe this problem on all Windows 8.1 computers (100+).

The GLPI installation is fresh - no upgrades or other modifications was applied. Just installed the serve, deployed agents and ran into this issue.

Agent side: glpi-agent log:
```
[Wed Oct 12 20:57:34 2022][info] target server0: server https://inventory.openbit.ru:40443/front/inventory.php
[Wed Oct 12 20:57:34 2022][info] sending contact request to server0
[Wed Oct 12 20:57:35 2022][info] running task Inventory
[Wed Oct 12 20:57:35 2022][info] New inventory from WS37-2022-10-12-13-06-34 for server0 (tag=ARKADIA)
[Wed Oct 12 20:58:02 2022][error] [http client] authentication required, error status: 500 Internal Server Error
[Wed Oct 12 20:58:04 2022][info] target server0: next run: Thu Oct 13 20:10:55 2022 - https://inventory.openbit.ru:40443/front/inventory.php
[Wed Oct 12 20:58:04 2022][info] GLPI Agent memory usage: WSS=3297280 PFU=145129472
```

Server side: /var/log/httpd/ssl_error_log:
```
[Wed Oct 12 20:57:10.451317 2022] [php:warn] [pid 34937] [client 176.32.182.186:50778] PHP Warning: Undefined array key "nok_hRVuvKpgZp$$$$927" in /var/www/glpi/src/Inventory/Asset/Software.php on line 676
[Wed Oct 12 20:57:10.451621 2022] [php:error] [pid 34937] [client 176.32.182.186:50778] PHP Fatal error: Column 'softwares_id' cannot be null in /var/www/glpi/src/DBmysql.php on line 1953
```

A workaround.

One way to get around this problem is to disable sending software category by the agent: "no-category REG_SZ software". In this case Windows 8.1 computers appear on the server and all inventory data is in place except for Software offcourse.

Another way is like you mentioned above:

"c:\Program Files\GLPI-Agent\glpi-inventory.bat" --json >c:\temp\inventory.json
"c:\Program Files\GLPI-Agent\glpi-injector.bat" -f c:\temp\inventory.json -u https://glpi_perseygroup_user:[password@inventory.openbit.ru](mailto:password@inventory.openbit.ru):40443/front/inventory.php

When I use glpi-injector.bat, the report is sent to the server without issue. The computer appears on the list. But we use a number of Entities. Rules put computers into respective Entities according to "Inventory TAG". So, when I run glpi-injector.bat, TAG is not being set and the computer appears in Root entity. So it's not good.

I would appreciate any ideas how to fix it.

Thank you.

Best regards,
Alexey Bystrov

### To reproduce

Install on PC GLPI-Agent-1.4-x64
Force inventory

### Expected behavior

A new PC should appear on the GLPI server but it will not. 

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.2

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.4

**Comment by g-bougard** [comment]
Hi @galarov 

you should first upgrade your GLPI as 10.0.3 comes with a lot of fixes including related to such error on server side.
It also includes an important security issue fixes: https://glpi-project.org/security-update-10-0-3-and-9-5-9/
And you're probably concerned if your server is opened to internet.

**Comment by trasher** [comment]
Also, try to reproduce issue importing the JSON or XML file directly in the GLPI web UI. Then open an issue on GLPI repo with all requested informationn including the inventory file to reproduce.

**Comment by galarov** [comment]
Thank you for the quick response. I'll try all this.

**Comment by galarov** [comment]
I've updated glpi server up to 10.0.3. Then forced inventory process on one of Windows 8.1 computers. No luck, errors are the same.

I opened a case with GLPI Repo: https://github.com/glpi-project/glpi/issues/12987

Thank you
