### ISSUE TITLE
Agents created but no computers generated.

### ISSUE THREAD

**Issue by Venkarian** [glpi-project/glpi-agent#245]
Hello,
I'm having an issue, I have an install of GLPI 10.1.0. The agents are populated in GLPI but, the computers are not generated.
I'm also using the glpiinventory plugin.

Can anyone provide me some help on this ?

Thanks,
Best regards.

**Comment by g-bougard** [comment]
Hi @Venkarian 
please, use the [forum](https://forum.glpi-project.org/) for such request.
