### ISSUE TITLE
SSL Fingerprint Renew

### ISSUE THREAD

**Issue by Jason-Linux** [glpi-project/glpi-agent#246]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Professional support

Yes, I know

### Expected behavior

I would like to know if it's normal that the fingreprint renew, how can i get new fingerprint automatically.

### Actions you've considered

I Install new Fingerprint

**Comment by g-bougard** [comment]
Hi @Jason-Linux 

`ssl-fingerprint` update can NOT be done automatically from the agent. As it is there to validate a certificate that SSL won't normally validate, you MUST check yourself the certificate can be trusted. If you don't make this check this totally breaks the SSL purpose. You're still free to use a server certificate signed by a public CA to avoid this need.

If you update the server certificate, you have to update `ssl-fingerprint` following this steps:
1. run one agent with the `no-ssl-check` option enable
2. update the `ssl-fingerprint` value with the one reported in log

But you may extract this fingerprint automatically from the server certificate you generated. Here is a shell one-liner to output the expected value on linux:
```
openssl x509 -fingerprint -sha256 -noout -in glpi-server-certificate.pem | sed -e "s/://g" -e "s/ Fingerprint=/\$/" | tr 'A-Z' 'a-z'
```
Where `glpi-server-certificate.pem` is the path to the glpi server certificate in PEM format.
