### ISSUE TITLE
(Bad file descriptor), SSL connect attempt failed 

### ISSUE THREAD

**Issue by 2Ben** [glpi-project/glpi-agent#248]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Professional support

Yes, I know

### Is your help request related to a problem?

Seems related to #242 
Following the info on that Issue I disabled ESET but it did not fix the problem.
Our SSL cert is fine with full chain, and manually going to  `https://glpi.company.com/plugins/glpiinventory/` from the computer running the Agent "works", as is, no output of course but no error 500 or 405 or even 404 or similar.

What can I do?
Thanks!

### Expected behavior

Inventory should upload to GLPI server.

### Actions you've considered

Disabled ESET: no change.

### Additional context

Full logs:
```
[Wed Oct 26 11:40:05 2022][debug] [http server] GET request /now from client 127.0.0.1
[Wed Oct 26 11:40:05 2022][debug] [http server] rescheduling next contact for all targets right now
[Wed Oct 26 11:40:05 2022][debug] [http server] response status 200
[Wed Oct 26 11:40:06 2022][info] target server0: server https://glpi.company.com/plugins/glpiinventory/
[Wed Oct 26 11:40:06 2022][debug] [http client] Using Compress::Zlib for compression
[Wed Oct 26 11:40:06 2022][info] sending prolog request to server0
[Wed Oct 26 11:40:06 2022][error] [http client] internal response: 500 Can't connect to glpi.company.com:443 (Bad file descriptor), SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
[Wed Oct 26 11:40:06 2022][error] No answer from server at https://glpi.company.com/plugins/glpiinventory/
[Wed Oct 26 11:40:06 2022][info] target server0: next run: Wed Oct 26 11:48:06 2022 - https://glpi.company.com/plugins/glpiinventory/
[Wed Oct 26 11:40:06 2022][debug] Agent memory usage before freeing memory: WSS=28565504 PFU=125964288
[Wed Oct 26 11:40:06 2022][info] GLPI Agent memory usage: WSS=3203072 PFU=125964288
[Wed Oct 26 11:40:07 2022][debug] [http server] GET request / from client 127.0.0.1
[Wed Oct 26 11:40:07 2022][debug] [http server] response status 200
```

**Comment by g-bougard** [comment]
Hi @2Ben 

as in #242, can you try the perl oneliner I proposed to test there in #226 issue ?
https://github.com/glpi-project/glpi-agent/issues/226#issuecomment-1272912636

Try the oneliner for https://github.com/ and for your own glpi server.

**Comment by 2Ben** [comment]
OK I ran the commands and it seems that the SSL module for perl is not installed/packaged with the Agent.
```
[debug] Logger backend Stderr initialized
[debug] GLPI Agent (1. 5-git2519c10c)
Socket: :SSL Perl module not available, unable to validate SSL certificates (workaround: use 'no-ssl-check' configure
tion parameter) at perl \agent/GLPI/Agent/HTTP/Client. pm line 266.
```

**Comment by g-bougard** [comment]
Hi @2Ben 
`Socket: :SSL` is just a wrong error reporting. Can I assume something goes wrong when you reported the message and the right reported missing module is `IO::Socket::SSL` ?
Anyway, can you try the oneliner after installing the latest nightly build ?
Personally, I think something goes wrong during installation and some files has been removed, maybe by your anti-virus.

**Comment by g-bougard** [comment]
Closing without user feedback.
