### ISSUE TITLE
Installation arguments do not work

### ISSUE THREAD

**Issue by martinautox** [glpi-project/glpi-agent#250]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Is your help request related to a problem?

I was about to try to Silent Install the GLPI Agent using msiexec on Windows.
All the arguments like "/runnow /acceptlicense /server= don't seem to work here.

Is it possible to roll out the client only via vbs file or with WSUS?

### Expected behavior

Working setup arguments at msiexec

### Actions you've considered

Create and distribute GPO, but if I can do it with WPP I would prefer it

**Comment by g-bougard** [comment]
Hi @martinautox 
please read documentation: https://glpi-agent.readthedocs.io/en/latest/installation/windows-command-line.html#command-line-parameters
The option format is not the same than FIA installer, as FIA used an EXE installer and here we have a MSI installer.

**Comment by martinautox** [comment]
I started from this information, but I did not achieve any success. And unfortunately I can't see which arguments work here for the MSI version.

**Comment by LeFouineur** [comment]
I use WPP to deploy GLPI Agent to my parc, it works nicely.

When I first tried, I add also problems deploying only in CLI (the documentation wasn't really fully there at the time and the installer wasn't really accepting arguments correctly between nightly builds versions each time), so the solution I used was this one : 
    - GPO deploy the configuration of the agent by updating the register key
    - WPP just load the installer, without arguments.
 
The only downsite is that the register keys must be on the PC before to not have an error.

For the case where the register key wasn't present at my first deployment test, I just used the only argument necessary for the install : 
```` FULL_PATH_TO_MSI\GLPI-Agent-1.5-*.msi /quiet SERVER=URI_OF_THE_SERVER````

Now than the installer is more stable, you can add all the arguments you want directly after the one for the SERVER and they would be used with you MSI in WPP.

**Comment by martinautox** [comment]
I have tried all this, but every time I add more than the argument /quiet like the server argument or that the firewall rule should be set, I get the following error and it just doesn't run.

![image](https://user-images.githubusercontent.com/115162854/198958266-77cdb28d-84cc-4a14-9027-f984cca2e737.png)

**Comment by LeFouineur** [comment]
I add the same problem when I was trying to start it as a normal msi file (````msiexec /i glpi-agent*.msi /q *````).
The only way it was working correctly everytime was calling the full path of the file itself without anything before.
In the end, my command line ended like that in my script :

````cmd
C:\LocalSources\GLPI\GLPI-Agent-1.*.msi /quiet ADD_FIREWALL_EXCEPTION=1 SERVER=https://URL_GLPI_SERVER/front/inventory.php

````
