### ISSUE TITLE
toolbox -> ip ranges -> (select+credentials) subsequent call to "Add credential" not working 

### ISSUE THREAD

**Issue by c3ph3us** [glpi-project/glpi-agent#254]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

in toolbox ip ranges tab/window  Associated credentials [SELECTED]  subsequent calls (VIA SELECT OTHER CREDENTIALS) to  <input class="submit-secondary" type="submit" name="submit/addcredential" value="Add credential"> don't work 'as expected' - second credential is not added, only re-enter page allows to add subsequent credential

### To reproduce

toolbox -> ip ranges -> select range -> select credential -> "Add credential"

### Expected behavior

add multiple credentials to range not leaving the ip ranges page 

### Operating system

Linux

### GLPI Agent version

Other (See additional context below)

### GLPI version

Not applicable

### Additional context

[GLPI Agent v1.5-dev]
ToolBox Plugin v1.1

**Comment by g-bougard** [comment]
Hi @c3ph3us 
thank you for your report.
As I'm working on toolbox on a dedicated branch to include other feature, you'll find the expected fix in dda35c9 commit from that branch.
You may also be interested by d6fb1cf which permit to keep an iprange selected after adding or removing a credential.
The fix won't be available in nightly until I merge the dedicated branch.

**Comment by g-bougard** [comment]
Hi @c3ph3us 
fix is now merged in develop and will be published in next nightly.
I invite you to test new ToolBox and report any issue.
Thank you again for your report.
