### ISSUE TITLE
agent web statuspage [add nav link to toolbox] enhancement 

### ISSUE THREAD

**Issue by c3ph3us** [glpi-project/glpi-agent#255]
### Documentation

Yes, I read it

### Professional support

Yes, I know

### Is your feature request related to a problem?

toolbox has ability to show link to agent but not viceversa 

### Expected behavior

it wold be nice to have the ability to travel between agent web status page  and toolbox page :) if possible [eg. when linking enabled by user and the pages are available]

### Alternatives you've considered

type url in browser to  switch between status page and toolbox page 

### Additional context

[GLPI Agent v1.5-dev]
ToolBox Plugin v1.1

**Comment by g-bougard** [comment]
Hi @c3ph3us 

the feature will be available in next release.
