### ISSUE TITLE
RustDesk not identified in inventory

### ISSUE THREAD

**Issue by gabriiellduarte** [glpi-project/glpi-agent#256]
### Documentation

Not applicable

### Solution search

Yes, I read it

### Professional support

Yes, I know

### Is your help request related to a problem?

No

### Expected behavior

When I start the inventory, the anydesk installed on the machine is identified and migrated to the glpi, but the rustdesk is not identified since it is installed, I tested it with teamviewer and the inventory is sent to the glpi with the ID of teamviewer and anydesk, but the rustdesk does not send it and is not identified in the log. Possible Bug?

### Actions you've considered

Restarting the services, restarted the machine and forced inventory 3x and on other machines as well.

**Comment by g-bougard** [comment]
Hi @gabriiellduarte 
RustDesk is just not supported by GLPI Agent at that time. Sorry, I even wasn't aware of this RemoteManagement alternative before you report it.
We should support it in the future.

**Comment by gabriiellduarte** [comment]
How strange, only if it is a disabled function because in the agent's own code it has a part that identifies the installed RustDesk and extracts the code.
![image](https://user-images.githubusercontent.com/11770579/202414588-3cb82015-252f-41f0-ab26-6abcdecb40f3.png)

**Comment by gabriiellduarte** [comment]
![image](https://user-images.githubusercontent.com/11770579/202414851-a99442e0-f2c8-40e8-bf3e-64c374b1915b.png)

**Comment by gabriiellduarte** [comment]
I saw that @paspo already opened a merge #193  for insertion, that's why I saw this function in the files. Hope to get it implemented soon. Thanks!

**Comment by g-bougard** [comment]
Okay, forgot this was integrated.
So this feature is actually only supported in nightly builds. Have you tried it ?
Get it there: https://nightly.glpi-project.org/glpi-agent/

**Comment by billgatos** [comment]
Hi all,

Using Nightly latest as today, i get in my local json file after inventory the info for rustdesk id

<REMOTE_MGMT>
99999999
anydesk
</REMOTE_MGMT>
<REMOTE_MGMT>
99999999
rustdesk
</REMOTE_MGMT>

But that info isn't loaded to glpi ?????

any thoughts on this .

Best regards.

**Comment by paspo** [comment]
@billgatos 

I've just tried with [latest nightly](https://nightly.glpi-project.org/glpi-agent/GLPI-Agent-1.5-gitedc3b504-x64.msi) and it worked flawlessly (rustdesk, teamviewer, anydesk, and supremo on a test VM)

try connecting to agent's web interface (`http://localhost:62354`) and force an inventory

**Comment by g-bougard** [comment]
Thank you for your feedback.

**Comment by g-bougard** [comment]
> Hi all,
> 
> Using Nightly latest as today, i get in my local json file after inventory the info for rustdesk id
> 
> <REMOTE_MGMT> 99999999 anydesk </REMOTE_MGMT> <REMOTE_MGMT> 99999999 rustdesk </REMOTE_MGMT>
> 
> But that info isn't loaded to glpi ?????
> 
> any thoughts on this .
> 
> Best regards.

Hi @billgatos 
I can just guess you're not using an up-to-date GLPI installation.
Please always report your GLPI installation when reporting a problem.

**Comment by billgatos** [comment]
hi all,

The following recepie works:
GLPI 10.0.5 and agent 1.5 nightly gets the rustdesk id to GLPI asset.

**Comment by steven86m** [comment]
Hi All,

I'm having an issue inventorying Rust desk into GLPI (Glpi is 10.0.10 with RustDesk 1.2.4)

it's not showing up in the inventory but teamviewer does and anydesk too.

Any help appreciated.

**Comment by g-bougard** [comment]
Hi @steven86m 
what glpi-agent version are you using ? You need at least glpi-agent 1.6 you have Rustdesk 1.2.x support from 1.2.2. Latest glpi-agent version is 1.7.1.

**Comment by steven86m** [comment]
> Hi @steven86m what glpi-agent version are you using ? You need at least glpi-agent 1.6 you have Rustdesk 1.2.x support from 1.2.2. Latest glpi-agent version is 1.7.1.

Just used agent 1.7.1  and it worked perfectly thanks
