### ISSUE TITLE
Error importing AIX inventory file: on slots tag, description attribute no need to be required

### ISSUE THREAD

**Issue by milamberspace** [glpi-project/glpi-agent#258]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

I try to import into GLPI an inventory file generated by GLPI-agent 1.4 (compile from source on AIX 7.2).

I have an error:
ERROR: JSON does not validate. Violations:
Required property missing: description, data: {"designation":"PCI Bus","name":"pci0"}

Details:

$ glpi-injector --debug --file /home/user/Documents/vm-aix72.xml --url https://assistance.domain.com/plugins/glpiinventory/
Loading /home/user/Documents/vm-aix72.xml...[E3781CC1] ERROR: JSON does not validate. Violations:
Required property missing: description, data: {"designation":"PCI Bus","name":"pci0"} at #->properties:content->properties:slots->items[0]:0

DEBUG: <?xml version="1.0"?>
<REPLY><ERROR><![CDATA[JSON does not validate. Violations:
Required property missing: description, data: {"designation":"PCI Bus","name":"pci0"} at #->properties:content->properties:slots->items[0]:0
]]></ERROR></REPLY>
These elements were not sent:
/home/user/Documents/vm-aix72.xml

in the inventory XML file (extract):

    <PROCESSES>
      <CMD>perl</CMD>
      <CPUUSAGE>16.7</CPUUSAGE>
      <MEM>1.0</MEM>
      <PID>7078304</PID>
      <STARTED>2022-11-15 11:49</STARTED>
      <TTY>pts/1</TTY>
      <USER>root</USER>
      <VIRTUALMEMORY>32100</VIRTUALMEMORY>
    </PROCESSES>
    <SLOTS>
      <DESIGNATION>PCI Bus</DESIGNATION>
      <NAME>pci0</NAME>
    </SLOTS>
    <SLOTS>
      <DESIGNATION>Virtual I/O Bus</DESIGNATION>
      <NAME>vio0</NAME>
    </SLOTS>
    <SOFTWARES>
      <COMMENTS>International Components for Unicode</COMMENTS>
      <FOLDER>/usr/lib/objrepos</FOLDER>
      <NAME>ICU4C.rte</NAME>
      <VERSION>7.2.5.0</VERSION>
    </SOFTWARES>
    <SOFTWARES>
      <COMMENTS>Java SDK 64-bit Java Runtime Environment</COMMENTS>
      <FOLDER>/usr/lib/objrepos</FOLDER>
      <NAME>Java8_64.jre</NAME>
      <VERSION>8.0.0.635</VERSION>
    </SOFTWARES>

=> No DESCRIPTION tag on SLOTS PCI Bus.

In the inventory.schema.json file on GLPI server, the description is mandatory.

If I remove the required on description field, it's works

$ diff /var/www/glpi-10.0.5/vendor/glpi-project/inventory_format/inventory.schema.json_old /var/www/glpi-10.0.5/vendor/glpi-project/inventory_format/inventory.schema.json
1655d1654
<               "description",

$ glpi-injector --debug --file /home/user/Documents/vm-aix72.xml --url https://assistance.domain.com/plugins/glpiinventory/
Loading /home/user/Documents/vm-aix72.xml...[0410C4A4] OK
DEBUG: <?xml version="1.0"?>
<REPLY><RESPONSE>SEND</RESPONSE></REPLY> 

### To reproduce

Try to import an inventory XML file for a AIX machine

### Expected behavior

The XML inventory file from AIX machine generated by GLPI Agent can be imported on GLPI Server (10.0.0.5)

### Operating system

Other (See additional context below)

### GLPI Agent version

1.4

### GLPI version

Other (See additional context below)

### Additional context

Related to: https://forum.glpi-project.org/viewtopic.php?id=285236

**Comment by g-bougard** [comment]
Hi @milamberspace 
firstly, try to use "`slot`" as value for "`--no-category`" option when generating the inventory file.

**Comment by g-bougard** [comment]
Anyway, do you see slots imported after you removed description requirement in inventory.schema.json ?
The fix could to fix inventory.schema.json file or to add a DESCRIPTION to slots on AIX, but I really don't know what to set there, unless you have your own idea ?

**Comment by milamberspace** [comment]
Hi @g-bougard

With ./glpi-inventory --no-category=slot > ${HOSTNAME}.xml
the injection works.

>> Anyway, do you see slots imported after you removed description requirement in inventory.schema.json ?


No, not found in the elements in GLPI.
Perhaps, you can add on components sections as BUS (PCI and Virtual I/O/ Bus), but seems that haven't a special value in the inventory.

**Comment by g-bougard** [comment]
Hi @milamberspace 
thank you for your feedback.
Indeed the slots support was just wrong on Aix. This is fixed in develop branch right now. I also checked other OS and found HPUX one was also broken.
Regarding GLPI, slots are simply ignored at that time... and the reason is probably "that hasn't a special value in inventory" as you said ;-)
So you still can just continue with the `--no-category` option and you'll be able to remove it with the next version.
