### ISSUE TITLE
Windows Incorrect Version

### ISSUE THREAD

**Issue by Alefunshow** [glpi-project/glpi-agent#263]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

HI, I'm having some issue with the info of my newtwork computers. The windows version is incomplete or it show version 2009 instead of telling me Which windows version have my pc

### To reproduce

Getting Info from info page in GLPI

### Expected behavior

Get full windows version

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.3

**Comment by g-bougard** [comment]
Hi @Alefunshow 
can you share the output of `glpi-inventory --partial os` on related computer ?

**Comment by Alefunshow** [comment]
Where can I extract this value?

**Comment by Alefunshow** [comment]
![image](https://user-images.githubusercontent.com/38226690/203014620-1bba2bee-b085-4e10-ab6c-5231eba03706.png)
here you can see that the "name" is windows "Edition" pro version "2009" but my os is windows 11 pro 22h2 and the same info appears for a win 10 21h2 machine. So I can't search for os in glpi. Is there any fix?

Previously in the "name" there was full os name like "windows 11 pro" or "windows 7 professional"

**Comment by g-bougard** [comment]
Does this happen after OS upgrade ?
Maybe you're concerned by glpi-project/glpi#13298

`glpi-inventory --partial os` must be run from an Administrator console on the concerned computer and from the GLPI Agent folder.

**Comment by Alefunshow** [comment]
No, previously i was using ocs inventory. And it was working but now with fusionInventory I'm having this issue

**Comment by Alefunshow** [comment]
I'm using agent 2.6

**Comment by Alefunshow** [comment]
![image](https://user-images.githubusercontent.com/38226690/203024021-01a1d489-df4f-4b67-b2b2-eed670bc20f2.png)
Here the glpi-inventory command executed

**Comment by Alefunshow** [comment]
![image](https://user-images.githubusercontent.com/38226690/203024194-8d829bc4-0169-4fcc-bf1f-61ed04ff0b84.png)
An this the result of the invetory task. name is not the full_name of my os

**Comment by Alefunshow** [comment]
@g-bougard Any info about this issue?

**Comment by g-bougard** [comment]
To me this is definitively not an agent issue:
 - in the "operatingsystem" section of the inventory you're showing:
   - "name" is "Windows" and this is what GLPI reports
   - "full_name" is what you want to see in GLPI -> GLPI problem -> Check glpi-project/glpi#13298 as I still asked you. You can even add your 3 cents to that issue.
But this also maybe a rules problem in GLPI. Have you also consider to upgrade to the latest version ?
Anyway, I'm closing as this issue was opened in the wrong place.
