### ISSUE TITLE
agent-esx

### ISSUE THREAD

**Issue by FrancoisG25** [glpi-project/glpi-agent#264]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Is your help request related to a problem?

I can't use the command agent-esx

My GLPI server is insalled on debian version 10.0.3

I have GLPI-Agent_v1.4 and GLPI-Agent_v1.5 on Debian and Alma server.

Can someone help me plz?

### Expected behavior

I'm trying to inventory my esx.

### Actions you've considered

I try to create glpi-esx in /usr/bin/ but i have dependencies issue :
Can't locate GLPI/Agent/Task/ESX.pm in @INC (you may need to install the GLPI::Agent::Task::ESX module) (@INC contains: /usr/share/glpi-agent/lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /usr/bin/glpi-esx line 14.
BEGIN failed--compilation aborted at /usr/bin/glpi-esx line 14.

Available tasks :
- Inventory (v1.12)
- RemoteInventory (v1.0)

**Comment by g-bougard** [comment]
You forgot to install the related package.

Please use forum in place of github issue tracker for such basic problem.

**Comment by FrancoisG25** [comment]
Thanks for your reply i will ask on the forum how to install the esx package with my glpi-agent
