### ISSUE TITLE
ISCSI does not match storage items

### ISSUE THREAD

**Issue by carlosadean** [glpi-project/glpi-agent#266]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

The glpi-agent v1.4 collects the storage information but does not recognize the ISCSI on it. Running with debug mode it shows the following in the agent log file:

[Tue Nov 22 09:17:37 2022][debug] - reading /sys/block content: success
[Tue Nov 22 09:17:38 2022][debug] invalid value iSCSI for field INTERFACE for section STORAGES
[Tue Nov 22 09:17:38 2022][debug] invalid value iSCSI for field INTERFACE for section STORAGES
[Tue Nov 22 09:17:38 2022][debug] invalid value iSCSI for field INTERFACE for section STORAGES
[Tue Nov 22 09:17:38 2022][debug] invalid value iSCSI for field INTERFACE for section STORAGES
[Tue Nov 22 09:17:38 2022][debug] invalid value iSCSI for field INTERFACE for section STORAGES
[Tue Nov 22 09:17:38 2022][debug] invalid value iSCSI for field INTERFACE for section STORAGES
[Tue Nov 22 09:17:38 2022][debug] invalid value iSCSI for field INTERFACE for section STORAGES
[Tue Nov 22 09:17:38 2022][debug] invalid value iSCSI for field INTERFACE for section STORAGES
[Tue Nov 22 09:17:38 2022][debug] invalid value iSCSI for field INTERFACE for section STORAGES
[Tue Nov 22 09:17:38 2022][debug] invalid value iSCSI for field INTERFACE for section STORAGES
[Tue Nov 22 09:17:38 2022][debug] Running GLPI::Agent::Task::Inventory::Linux::Uptime
[Tue Nov 22 09:17:38 2022][debug] Running GLPI::Agent::Task::Inventory::Linux::Videos
[Tue Nov 22 09:17:38 2022][debug] retrieving display information:
[Tue Nov 22 09:17:38 2022][debug] - running ddcprobe command: command not available
[Tue Nov 22 09:17:38 2022][debug] - reading Xorg log file: unable to get Xorg PID
[Tue Nov 22 09:17:38 2022][debug] Running GLPI::Agent::Task::Inventory::Linux::i386
[Tue Nov 22 09:17:38 2022][debug] Running GLPI::Agent::Task::Inventory::Linux::i386::CPU
[Tue Nov 22 09:17:38 2022][debug] Running GLPI::Agent::Task::Inventory::Provider
[Tue Nov 22 09:17:38 2022][debug] Running GLPI::Agent::Task::Inventory::Virtualization
[Tue Nov 22 09:17:38 2022][debug] Running GLPI::Agent::Task::Inventory::Virtualization::SystemdNspawn
[Tue Nov 22 09:17:38 2022][debug] [http client] 564ABF7C: Using Compress::Zlib for compression
[Tue Nov 22 09:17:39 2022][error] [http client] communication error: 500 Internal Server Error
[Tue Nov 22 09:17:39 2022][error] [http client] 564ABF7C: server error: JSON does not validate. Violations:
"ISCSI" does not match to ^(SCSI|HDC|IDE|USB|1394|SATA|SAS|ATAPI)$ at #->properties:content->properties:storages->items[1]:1->properties:interface
[Tue Nov 22 09:17:39 2022][debug] Remote inventory task execution disabled: no remote to inventory

### To reproduce

I just ran `glpi-agent --server=http://myserver/front/inventory.php --tag=$tag --debug`

### Expected behavior

The agent could collect all hardware information.

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.3

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.4

**Comment by g-bougard** [comment]
Hi @carlosadean 
this is fixed in latest GLPI version. Please upgrade to 10.0.5.
Thank you.
