### ISSUE TITLE
httpd-trust error

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi-agent#27]
### Bug reporting acknowledgment

- [X] Yes, I read it

### Describe the bug

I configured httpd-trust like with fusioninventory agent:

httpd-trust: 192.168.1.210, 192.168.1.208

In log file I get: 

[Wed Oct 27 08:12:28 2021][error] unable to get address for ' 192.168.1.208': Unknown host. 

### To reproduce

1. Start GLPI-Agent-1.0-beta1-x64.msi
2. "HTTP Server Options: Set embedded HTTP server options"
3. Trusted IPs field > set 192.168.1.210, 192.168.1.208
4. Finish install.

or

1. HKEY_LOCAL_MACHINE\SOFTWARE\GLPI-Agent
2. httpd-trust
3. value: 192.168.1.210, 192.168.1.208

### Expected behavior

All hosts listed are trusted and no log errors generate.

### Operating system

Windows

### GLPI Agent version

1.0

### GLPI version

9.5.6

### FusionInventory for GLPI version

Older (See additional context below)

### Additional context

FusionInventory 9.5.0+1.0

**Comment by g-bougard** [comment]
Hi, @WebGregGit 
thank you for this submission.
It seems you have a space in the httpd-trust definition, between the comma and the second ip. Can you check if it comes from your setting ?
I'll check how the agent handles this kind of issue.

**Comment by WebGregGit** [comment]
Hello @g-bougard 

I installed again and made sure there were no spaces this time. And no errors in log file. This could be it :)

**Comment by WebGregGit** [comment]
This looks like a space problem between the comma and the next ip
