### ISSUE TITLE
Parse LLDP PortID into mac, ifdescr and ifnumber

### ISSUE THREAD

**Issue by po1vo** [glpi-project/glpi-agent#277]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

LLDP provides PortID as either port's logical number or ifname or mac, right now all of these are dumped into IFNUMBER key, however IFNUMBER is a numeric field.

### To reproduce

See glpi-project/glpi/issues/13094

### Expected behavior

If PortID is a number, it should go to `IFNUMBER`.
If it's a mac - to `MAC`.
If it's a port name - to `IFDESCR`.

### Operating system

Windows, Linux, MacOSX

### GLPI Agent version

1.4

### GLPI version

10.0.3

**Comment by g-bougard** [comment]
Hi @po1vo 

I agree there's probably something to do there.

I checked our private walk repository for such problematic cases where IFNUMBER is not an integer into a CONNECTIONS node.

For now I found things like:
- `IFNUMBER => 'Gi1/0/19'`, which should probably be set as IFNAME,
- `IFNUMBER => 'eth3'`, idem,
- `IFNUMBER => 'Ethernet1/27'`, idem,
- and many more which should probably be set as IFNAME

I didn't find any case where the "number" should be changed as a MAC address.

@vollkommenIrrelevant would you care to share the walk of your device where a IFNUMBER looks like `E0-07-1B-4E-68-12`.
The walk should be generated following the following doc: https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output
You can send it to me privately so I can include it in our private walk repository.

Anyway, seeing something like:
```
<CONNECTION>
    <IFNUMBER>E0-07-1B-4E-68-12</IFNUMBER>
    <SYSMAC>e0:07:1b:4e:68:10</SYSMAC>
</CONNECTION>
```
What is the right MAC ? e0:07:1b:4e:68:10 or e0:07:1b:4e:68:12 ?
In that case, we should probably just drop IFNUMBER if this is not the right MAC and eventually set SYSMAC if none is set.

**Comment by po1vo** [comment]
@g-bougard , `SYSMAC` is mandatory and MUST always be present in all cases.
So this:
```xml
<CONNECTION>
    <IFNUMBER>E0-07-1B-4E-68-12</IFNUMBER>
    <SYSMAC>e0:07:1b:4e:68:10</SYSMAC>
</CONNECTION>
```
Should look like:
```xml
<CONNECTION>
    <MAC>e0:07:1b:4e:68:12</MAC>
    <SYSMAC>e0:07:1b:4e:68:10</SYSMAC>
</CONNECTION>
```

**Comment by po1vo** [comment]
> * `IFNUMBER => 'Gi1/0/19'`, which should probably be set as IFNAME,
> * `IFNUMBER => 'eth3'`, idem,
> * `IFNUMBER => 'Ethernet1/27'`, idem,
> * and many more which should probably be set as IFNAME

IFNAME is not a valid field in CONNECTIONS according to inventory_format, you should set IFDESCR

**Comment by g-bougard** [comment]
According to [FI still mandatory NetInventory protocol](https://documentation.fusioninventory.org/Advanced_topics/dev/spec/protocol/netinventory/), you're right ;-)

**Comment by vollkommenIrrelevant** [comment]
> @vollkommenIrrelevant would you care to share the walk of your device where a IFNUMBER looks like `E0-07-1B-4E-68-12`. The walk should be generated following the following doc: https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output You can send it to me privately so I can include it in our private walk repository.
> 
> Anyway, seeing something like:
> 
> ```
> <CONNECTION>
>     <IFNUMBER>E0-07-1B-4E-68-12</IFNUMBER>
>     <SYSMAC>e0:07:1b:4e:68:10</SYSMAC>
> </CONNECTION>
> ```
> 
> What is the right MAC ? e0:07:1b:4e:68:10 or e0:07:1b:4e:68:12 ? In that case, we should probably just drop IFNUMBER if this is not the right MAC and eventually set SYSMAC if none is set.

i send you the snmpwalk of 88:51:fb:ba:2f:40 and e0:07:1b:4e:68:10 by mail. In the walk the macadress is represented as Hex-String... e0:07:1b:4e:68:10 is connected with 88:51:fb:ba:2f:40 and is showing all the E0-07-1B-4E-68-12 ports (=E0 07 1B 4E 68 12)

**Comment by g-bougard** [comment]
@vollkommenIrrelevant 
thank you, I have everything to make tests and find the right fix.

**Comment by g-bougard** [comment]
Hi @vollkommenIrrelevant 
you should be able to make tests with the next nightly build.
Thank again for sharing your walks.

**Comment by po1vo** [comment]
@g-bougard please see my comments to your commit

**Comment by g-bougard** [comment]
Seen & answered.
