### ISSUE TITLE
Import of "Softwares" does not work after deleting Software in GLPI manually 

### ISSUE THREAD

**Issue by ghost** [glpi-project/glpi-agent#278]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

My windows-computer has installed a glpi-agent v1.4.

Everthing was inventoried fine (computer-information, components, softwares ...etc.)

After deleting some softwares from the asset in the glpi, the software will not be inventoried anymore.

I tried to reinstall the GLPI-Agent, but it doesnt work then either.
Same things i tried and explored for glpi-agent for linux (Debian11, installed with "glpi-agent-1.4-linux-installer.pl"

### To reproduce

I run the GLPI-Agent on my windows-client, the inventory worked fine....

But:

for testing reasons and preparing an inventory-filter for softwares (like, dont inventory applications with category "system") i deleted all softwares listed for my asset. 
I tried to inventory them again (without filtering), but the glpi-agent or the glpi itself isnt importing the softwares.
I searched for the database-structure and found the right table "glpi_items_softwareversions" where the assets and softwares comes together. My selection showed me, that im right. I could see all softwares for my computer (used sql selection: "select * from glpi_items_softwareversions where items_id like "1067";")

Those 613 softwares were listed and the attribute or column "is_deleted" that all of them are deleted for my asset.
I updated the value to "0" for all entries with this command: "update glpi_items_softwareversions set is_deleted=0 where is_deleted=1 and items_id like "1067";" and i was able to see all my softwares again.

In my GLPI-Agent-Log i can see, that all software is discovered.

The log is telling me, that all data got sent to my server:

_If the server rejects the inventory, please, report an issue on glpi-agent github project.
[Mon Nov 28 14:03:54 2022][debug2] [http client] EFCF7DF4: sending message:
{
   "action": "inventory",
   "content": {
      "accesslog": {
         "logdate": "2022-11-28 14:01:36"

...all of my secret data ;D ...

[Mon Nov 28 14:03:55 2022][debug2] [http client] EFCF7DF4: received message:
{"expiration":"24","status":"ok"}_

Those log entries for my software were counted with 6849 lines, divided by 11 (average number of lines for one software entry) are round-a-bout 613, like all my softwares.

So my question:

do I handle the agent and the glpi-inventory incorrect or is this a bug? 
Why is the GLPI-Inventory not updating the value from "is_deleted" when the software is installed, read out and sent to my server by the agent?

### Expected behavior

updating the value from "is_deleted"

importing or activating the software-entries in the glpi for my assets

### Operating system

Windows, Linux

### GLPI Agent version

1.4

### GLPI version

10.0.3

**Comment by g-bougard** [comment]
Hi @PiOfIT 
first this is not a glpi-agent problem: it produces exactly the same inventory file if you have or not delete softwares in GLPI.
Then, if you see the softwares with "is_deleted" set to 1 in db, this probably means the softwares was put in trash bin from the software assets panel. So during the next inventory, they were updated... but in trash bin. You probably had to just purge the softwares in trash bin to see what you expected: the software are coming back during next inventory.
Eventually, you should better delete softwares from the software tab of the related computer asset.
Hope you understood what I mean.

**Comment by ghost** [comment]
Hi @g-bougard !

okay i see...thats what i thought, because my log file showed me all information for my agents.

Maybe I made my problem a bit unclear. I dont delete the softwares from the software panel, i delete them on the computer panel (....computer.form.php&_itemtype=Computer&_glpi_tab=Item_SoftwareVersion...)  and there is no bin for deleted entries.

![2022-11-29 08_26_05-Window](https://user-images.githubusercontent.com/45315071/204465282-f68afedd-e523-4911-a4d0-f30feba29a1c.png)

I dont want to delete the software itself in GLPI, i just want to delete the connection between a software and my agent.

After deleting the connection, the value for "is_deleted" changes to "1" in db, but if i start another inventory for my agents, the software for those i deleted the connection dont get "reactivated" for my agent, so the value for "is_deleted" doesnt change to "0".

**Comment by g-bougard** [comment]
Okay, this is just a normal behavior in GLPI: it locks the fact you deleted the software from the asset as you did it manually.
In that case, if you want to unlock, just open the "Locks" frame of the asset and remove the locks for the softwares.

**Comment by ghost** [comment]
WOW, I didn't know about this function. Thats what i searched for!! Thank you :D
