### ISSUE TITLE
glpi-injector.pl: Unable to import XML inventory files 

### ISSUE THREAD

**Issue by had22** [glpi-project/glpi-agent#279]
### Bug reporting acknowledgment

Not applicable

### Describe the bug

Hello everyone,
 
We have a GLPI server at the central site and remote sites that use the fusion inventory agent locally.  fusioninventory-injector.pl is used to inject the inventory files of these remote sites (.xml) into the GLPI server. The following command was used:
`perl fusioninventory-injector.pl -v -d /home/xxx/folderxml/ --url http://localhost/glpi/plugins/fusioninventory/`
The files (.xml) are in the folderxml folder .**Everything worked well before with version 9.5.4.**

Recently, we migrated to GLPI 10.0.5. We used glpi-injector instead of fusioninventory- injector to inject the files (.xml) with the command:
`perl glpi-injector.pl -v -d /home/xxx/folderxml/ --url http://localhost/glpi/plugins/glpiinventory/`
But it dosn't work. We got these errors:

1. The first issue was about the setup module (with lowercase S) in the glpi-injector file --> We replaced the lowercase s with uppercase (Setup)and it worked. We want to raise this bug to fix it.

2. second error:
```
Can't locate GLPI/Agent/XML.pm in @INC (you may need to install the GLPI::Agent::XML module) (@INC contains: ./lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at /home/inventaire/fusioninventory/scripts/glpi-injector.pl line 19.
```

 We searched this module (GLPI::Agent::XML) in the CPAN website  www.cpan.org but does not exist. How can this problem be corrected?

4. We added a comment in front of #GLPI::Agent::XML in glpi_ingector.pl but this time we got an other error: 

Loading /home/xxx.../fileinventory.xml...[6E5319BD] ERROR: Bad content as server response
DEBUG: <?xml version="1.0"?>
<REPLY><RESPONSE>SEND</RESPONSE></REPLY>

Can you help us on this issue?  Thanks in advance 

Regards,
Hado

### To reproduce

GLPI 10.0.5
GLPI inventory  plugins 1.0.5
glpi-injector.pl to inject xml files in GLPI server

### Expected behavior

inject the .xml inventory file into the GLPI server using glpi-injector.pl

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.4, Other (See additional context below)

### Additional context

GLPI inventory  plugins version 1.0.5

**Comment by g-bougard** [comment]
Hi @had22 

GLPI::Agent::XML module is a new library that comes with nightly builds only as it only in the dev version for now. And yes it is required by glpi-injector.

As you're telling you're using GLPI-Agent v1.4, this means to me you've messed up something. As the reported error tells you're running the injector from the `/home/inventaire/fusioninventory/scripts` folder, this also means you're not using a standard installation.

So you clearly forgot to tell in the "Additional context" how you installed the agent and where you took it.

**Comment by had22** [comment]
Hi g-bougard,

We use GLPI Agent only for new machines (mainly in the central site) using the standard installation. we don't have an issue with this.

Our problem is about a large part of inventory files (.xml). As I explained before, it concerns remote sites with fusion inventory agent that run locally on these machines and we need to inject the inventory files (.xml) in the GLPI server with glpi-injector.

So according to your response, the glpi-injector will not work. We have to wait for the GLPI::Agent::XML ?

Thank you for your help,

Regards

**Comment by g-bougard** [comment]
I didn't say glpi-injector is not working. I said you're using a `glpi-injector` script which requires a library only provided with latest dev agent.
This still means you messed up something if you installed glpi-agent 1.4. Maybe you downloaded that only script from github develop branch and put it in `/home/inventaire/fusioninventory/scripts`... who knows as we are still missing some informations.
If you downloaded the script, please download the 1.4 version from:
https://raw.githubusercontent.com/glpi-project/glpi-agent/1.4/bin/glpi-injector
This version doesn't require GLPI::Agent::XML module.

**Comment by had22** [comment]
Yes, we just downloaded glpi-injector and put it in the /home/inventaire/fusioninventory/scripts. In this Directory we have also the inventory.xml files then we execute the commande:
perl glpi-injector.pl -v -d /home/xxx/folderxml/ --url http://localhost/glpi/plugins/glpiinventory/

I will try with the glpi-injector that you have given me and you keep you informed.

Thanks

**Comment by had22** [comment]
I did the test. It worked. Thank you for your help. 

Regards,
Hado
