### ISSUE TITLE
Incorrect Russian encoding in inventory

### ISSUE THREAD

**Issue by corymar** [glpi-project/glpi-agent#28]
### Bug reporting acknowledgment

- [X] Yes, I read it

### Describe the bug

After running the agent with fusioninventory 9.5+3.0 server-side plugin there is garbage in computer inventory - programs
Suppose there are encoding conversion malfunctions on agent side since FI agent reports with correctly displayed characters
![Computer_software](https://user-images.githubusercontent.com/60350203/139877952-ea5400fa-2b4d-4164-9cb9-7eb015cef15c.png)
Unix(LF)/UTF8 xml inventory file contents:
![изображение](https://user-images.githubusercontent.com/60350203/139878829-a994a990-6970-4de4-b390-c4822c56bf05.png)

### To reproduce

1. Install GLPI-Inventory plugin on Windows 10 with default Russian language and Russian region
2. Initiate inventory with GLPI-Inventory plugin with https://glpi/plugins/fusioninventory/ server setting
3. Check GLPI - Assets - Computers - computer with inventory information - software 

### Expected behavior

Expected correct display of russian language instead of garbage characters

### Operating system

Windows

### GLPI Agent version

1.0-beta1-x64

### GLPI version

Older (See additional context below)

### FusionInventory for GLPI version

9.5+3.0

### Additional context

GLPI 9.5.5

**Comment by g-bougard** [comment]
Hi @corymar 

thank you for your report.

The related software comes from the Windows Store as FROM=uwp. This inventory has been changed to be supported during remote inventory so I can understand something got lost against FIA.

Can you check the json inventory and report if you have the same issue ? To do so, you can simply run the following command from an administrator console and from the GLPI Agent installation folder:
```
glpi-inventory --partial software >software.json
```
And check `software.json` content.

**Comment by g-bougard** [comment]
Another point, to be clear, you're telling "Install GLPI-Inventory plugin on Windows 10", but GLPI Agent is not a GLPI plugin, this is an independent software installed on computers to be inventoried.

**Comment by corymar** [comment]
> 
> 
> Another point, to be clear, you're telling "Install GLPI-Inventory plugin on Windows 10", but GLPI Agent is not a GLPI plugin, this is an independent software installed on computers to be inventoried.

Thank you for pointing it out, of course you're right, the correct word is not "plugin" but "agent"

>... 
> The related software comes from the Windows Store as FROM=uwp. This inventory has been changed to be supported during remote inventory so I can understand something got lost against FIA.
> Can you check the json inventory and report if you have the same issue ? To do so, you can simply run the following command from an administrator console and from the GLPI Agent installation folder:
> glpi-inventory --partial software >software.json
> And check `software.json` content.

Did as you suggested. There is non-windows store program "КриптоПро" (CryptoPro)
in software.json (_Windows CR/LF, UTF16 LE BOM_):
![изображение](https://user-images.githubusercontent.com/60350203/140755881-ee6a82b0-a02e-46c0-8635-98b7912f4991.png)

same software in local inventory xml file (_Windows CR/LF UTF-8 non-BOM_):
![изображение](https://user-images.githubusercontent.com/60350203/140756372-27bfda23-9056-44eb-98df-8b548499a9e8.png)

Can't test it in remote right now, but suggest it will be _Unix LF UTF-8_
As a result, it shows normally in local xml file and shows as garbage in json

On the other hand, windows store software "BrokerPlugin" is broken in both json and xml:
![изображение](https://user-images.githubusercontent.com/60350203/140757259-0a61153c-ed70-4c97-928d-a092d6613848.png)
![изображение](https://user-images.githubusercontent.com/60350203/140757317-f08bcf51-15c6-451b-83f5-94aed043549d.png)

So there is definitely some codepage and/or encoding issues not only for windows store software

Hope it helps

**Comment by g-bougard** [comment]
Hi @corymar 
thank you for this accurate update.
I was able to install a fresh russian win10 and I confirm I can reproduce the encoding issue for uwp package. I should be able to fix it quickly.
About the other case, "registry" entry in JSON format. I don't see any case at the moment and I can't install the software you pointed me as it is not free. So can you extract the related registry entry with regedit ? It should be under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall`.

**Comment by corymar** [comment]
Hi, @g-bougard 

Attached please find the archive with *.reg file for cryptopro software uninstall string
[cryptopro_uninstall_entry.zip](https://github.com/glpi-project/glpi-agent/files/7503591/cryptopro_uninstall_entry.zip)

**Comment by g-bougard** [comment]
Hi @corymar 
I pushed a fix in 55b81ba for your issue.
c5e04ee commit fixes the other issue related to json encoding (including the cryptopro case and thank you for your registry dump, it helped).
I still need to validate remote inventory but you're not concerned at the moment ;-)
Wait next nightly build and test it and feel free to reopened if something goes wrong.

**Comment by g-bougard** [comment]
Just tested myself with GLPI-Agent_v1.0-git55b81ba1 nightly build, it seems something still goes wrong. The cryptopro entry is still good, but not uwp packages.
@corymar can you confirm, thanks ?

**Comment by corymar** [comment]
Hi, @g-bougard 

I can confirm that both json and xml manual export are now looking fine with non-uwp software for name field:

![изображение](https://user-images.githubusercontent.com/60350203/141160238-e469441a-fcc7-464c-a9e0-5b0b57d14f8f.png)
![изображение](https://user-images.githubusercontent.com/60350203/141164305-45b10a6d-63ba-4af2-a12a-0c171f0c1419.png)

But there is same error with folder name display (guid field) in both json and xml:

![изображение](https://user-images.githubusercontent.com/60350203/141160918-94a2d706-03ea-4524-b168-a59afaf455f1.png)
![изображение](https://user-images.githubusercontent.com/60350203/141164208-8442c827-93b8-41a6-984f-da725e05adb6.png)

Regarding uwp software there are now english description fields in json, but everything is malformed in xml:

![изображение](https://user-images.githubusercontent.com/60350203/141161440-a30f7270-21fb-44f8-9696-327396aa112e.png)
![изображение](https://user-images.githubusercontent.com/60350203/141164091-9e28daca-35f4-4694-bc14-485b4df9ca5c.png)

New release files are generated in same UTF-8 non-BOM encoding when previous json was in UTF-16 LE BOM

Also there are some differences in handling of different uwp programs.
System or preinstalled (guess) are now displayed in english instead of malformed russian (maybe it grabs non-translated strings):

![изображение](https://user-images.githubusercontent.com/60350203/141164988-3d61d2ea-626a-4f39-9961-ba81d61986a5.png)

and some are not translated, but they are correctly displayed:

![изображение](https://user-images.githubusercontent.com/60350203/141165370-4e4e9be9-43ce-4b7e-9124-dd3068f18fed.png)

Attached please find 3 files: old json, new json, new xml
[reports_20211110.zip](https://github.com/glpi-project/glpi-agent/files/7514861/reports_20211110.zip)

Also adding 1c 7.7 uninstall entry registry dump:
[1c_registry_dump.zip](https://github.com/glpi-project/glpi-agent/files/7514927/1c_registry_dump.zip)

**Comment by corymar** [comment]
Do you need any registry dumps ?

**Comment by g-bougard** [comment]
Hi @corymar 
thank you for your exports.
Can you confirm the value you have in registry for the following key ?
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage\ACP`

**Comment by corymar** [comment]
Hi @g-bougard 

Yes, there is REG_SZ "ACP" key with "1251" value there
![изображение](https://user-images.githubusercontent.com/60350203/141610878-9d8e70bd-8f18-42ce-a955-fc5f9cf6c7ce.png)

**Comment by g-bougard** [comment]
Hi @corymar 
can you try the latest nightly ? I pushed few commits on friday that should fix that issue.

**Comment by corymar** [comment]
Hi, @g-bougard 

Sorry for delay, just tested everything on current nightly build
Seems that everything is ok, no malformed strings in both json and xml
Attached please find them in case they are needed
[reports.zip](https://github.com/glpi-project/glpi-agent/files/7575419/reports.zip)

Thank you!

**Comment by g-bougard** [comment]
Thank you for that feedback.
