### ISSUE TITLE
many unnecessary records are generated in the inventory history

### ISSUE THREAD

**Issue by Badkempachi** [glpi-project/glpi-agent#285]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Good afternoon,
I have a problem, it is related to the fact that many unnecessary records are generated.
In my case, this is information about software removal and windows update patches. The inventory is performed every hour, and every hour, for a reason that I don't understand, I first display that the software has been removed and then installed again. Please tell me what this is related to and how to fix it?
Note this problem is not observed on all computers, but only on some, they have Windows 10 installed.

### To reproduce

I go into the history of the computer and see this picture. I attach logs.

### Expected behavior

Displaying a change in the software only of the information that has actually been changed

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.4

### Additional context

Windows 10 - 22H2
GLPI version - 10.0.5
GLPI-Agent_v1.5-git546ca3c5

[History_user3_2022_12_07 — copy.csv](https://github.com/glpi-project/glpi-agent/files/10175757/History_user3_2022_12_07.copy.csv)
[computer_0_50.json.txt](https://github.com/glpi-project/glpi-agent/files/10175760/computer_0_50.json.txt)

**Comment by trasher** [comment]
I'm not able to reproduce.

**Comment by stonebuzz** [comment]
Do you have errors in the logs of GLPI (during inventory)

**Comment by Badkempachi** [comment]
> I'm not able to reproduce.

In any case, the problem takes place
![2](https://user-images.githubusercontent.com/97535165/206192427-5d10f99d-6282-4e33-a7e3-e54614a41c84.jpg)
![1](https://user-images.githubusercontent.com/97535165/206192435-d61d1602-111a-4486-8a38-2878291a584e.jpg)

**Comment by Badkempachi** [comment]
> 

There is an error, but it does not apply to this problem.

[2022-12-07 16:29:05] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "capacity" in /var/www/html/glpi/src/Inventory/Asset/Device.php at line 143
  Backtrace :
  src/Inventory/Asset/Drive.php:121                  Glpi\Inventory\Asset\Device->handle()
  src/Inventory/Asset/MainAsset.php:862              Glpi\Inventory\Asset\Drive->handle()
  src/Inventory/Asset/MainAsset.php:782              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:950                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1510                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:564              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:702                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:337                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:332    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:244    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()

**Comment by Badkempachi** [comment]
> > I'm not able to reproduce.
> 
> In any case, the problem takes place ![2](https://user-images.githubusercontent.com/97535165/206192427-5d10f99d-6282-4e33-a7e3-e54614a41c84.jpg) ![1](https://user-images.githubusercontent.com/97535165/206192435-d61d1602-111a-4486-8a38-2878291a584e.jpg)

I understand that it is necessary to create a query in the glpi branches, because I also did not find anything that could cause the problem.

**Comment by stonebuzz** [comment]
> > 
> 
> There is an error, but it does not apply to this problem.
> 
> [2022-12-07 16:29:05] glpiphplog.WARNING: *** PHP Warning (2): Undefined array key "capacity" in /var/www/html/glpi/src/Inventory/Asset/Device.php at line 143 Backtrace : src/Inventory/Asset/Drive.php:121 Glpi\Inventory\Asset\Device->handle() src/Inventory/Asset/MainAsset.php:862 Glpi\Inventory\Asset\Drive->handle() src/Inventory/Asset/MainAsset.php:782 Glpi\Inventory\Asset\MainAsset->handleAssets() src/RuleImportAsset.php:950 Glpi\Inventory\Asset\MainAsset->rulepassed() src/Rule.php:1510 RuleImportAsset->executeActions() src/RuleCollection.php:1591 Rule->process() src/Inventory/Asset/MainAsset.php:564 RuleCollection->processAllRules() src/Inventory/Inventory.php:702 Glpi\Inventory\Asset\MainAsset->handle() src/Inventory/Inventory.php:337 Glpi\Inventory\Inventory->handleItem() src/Inventory/Request.php:360 Glpi\Inventory\Inventory->doInventory() src/Inventory/Request.php:90 Glpi\Inventory\Request->inventory() src/Agent/Communication/AbstractRequest.php:332 Glpi\Inventory\Request->handleAction() src/Agent/Communication/AbstractRequest.php:244 Glpi\Agent\Communication\AbstractRequest->handleJSONRequest() front/inventory.php:92 Glpi\Agent\Communication\AbstractRequest->handleRequest() ...tplace/glpiinventory/front/communication.php:72 include_once() marketplace/glpiinventory/index.php:45 include_once()

This error is fixed from GLPI Nightly Build

can you test (unnecessary records)  with this version ?

https://nightly.glpi-project.org/glpi/

Best regards

**Comment by Badkempachi** [comment]
> > > 
> > 
> > 
> > There is an error, but it does not apply to this problem.
> > [2022-12-07 16:29:05] glpiphplog.WARNING: *** PHP Warning (2): Undefined array key "capacity" in /var/www/html/glpi/src/Inventory/Asset/Device.php at line 143 Backtrace : src/Inventory/Asset/Drive.php:121 Glpi\Inventory\Asset\Device->handle() src/Inventory/Asset/MainAsset.php:862 Glpi\Inventory\Asset\Drive->handle() src/Inventory/Asset/MainAsset.php:782 Glpi\Inventory\Asset\MainAsset->handleAssets() src/RuleImportAsset.php:950 Glpi\Inventory\Asset\MainAsset->rulepassed() src/Rule.php:1510 RuleImportAsset->executeActions() src/RuleCollection.php:1591 Rule->process() src/Inventory/Asset/MainAsset.php:564 RuleCollection->processAllRules() src/Inventory/Inventory.php:702 Glpi\Inventory\Asset\MainAsset->handle() src/Inventory/Inventory.php:337 Glpi\Inventory\Inventory->handleItem() src/Inventory/Request.php:360 Glpi\Inventory\Inventory->doInventory() src/Inventory/Request.php:90 Glpi\Inventory\Request->inventory() src/Agent/Communication/AbstractRequest.php:332 Glpi\Inventory\Request->handleAction() src/Agent/Communication/AbstractRequest.php:244 Glpi\Agent\Communication\AbstractRequest->handleJSONRequest() front/inventory.php:92 Glpi\Agent\Communication\AbstractRequest->handleRequest() ...tplace/glpiinventory/front/communication.php:72 include_once() marketplace/glpiinventory/index.php:45 include_once()
> 
> This error is fixed from GLPI Nightly Build
> 
> can you test (unnecessary records) with this version ?
> 
> https://nightly.glpi-project.org/glpi/
> 
> Best regards

Thanks, I'll try.
But there is a small problem, I have already tried to install a night build, but I ran into a problem in the form of a message that there are traces from the previous version and informs me about the need to familiarize myself with the instructions. I was looking for information in the “./install” directory and I do not exclude that I could have missed or looked in the wrong place. Therefore, I have a request to you, you can tell me where I can see the document on the correct update, or how I can avoid warnings about the presence of files from the previous version.

**Comment by trasher** [comment]
https://glpi-install.readthedocs.io/en/latest/update.html
"Ensure the target directory is empty and extract files there."

**Comment by g-bougard** [comment]
I set the issue as "invalid" as this is not the right project to report such "issue".
@trasher @stonebuzz feel free to migrate the issue or continue here ;-)

**Comment by trasher** [comment]
I did not pay attention that ahs been opened here... @Badkempachi feel free to open issue on glpi-project/glpi with all requested information; if you still reproduce with latest nightly.

**Comment by Badkempachi** [comment]
> https://glpi-install.readthedocs.io/en/latest/update.html "Ensure the target directory is empty and extract files there."
Sorry for continuing to write here, but it's not clear where to open the topic later, I just tried to update to the night build, but I ran into the same problem as before.  At the same time, I tried to find errors in the logs, but there are none. Tell me, please, what to do with it?
P.s. I did the update according to the instructions provided by you.
![error_update](https://user-images.githubusercontent.com/97535165/206207837-28ee1cd3-d403-4bac-81ca-aaedf96e0a82.jpg)
