### ISSUE TITLE
Mac: GLPI-Agent & Networkports

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [glpi-project/glpi-agent#289]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

It seems tehre is a problem with glpi Agent and Mac. The Page "Networkports" is showing after Inventory some elements like Thunderbolt or Network Adapter... I'm not shure if this is "by Design" due different Hardware of Appledevices.

### To reproduce

Make an Inventory with an actual Macbook and all Softwareupdates.

### Expected behavior

Only Networkports are visible

### Operating system

MacOSX

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

actual Nightly Build, actual GLPI, actual Plugin

![grafik](https://user-images.githubusercontent.com/25504254/206516443-ef539538-67db-4ceb-b47f-603ecd52b532.png)

**Comment by vollkommenIrrelevant** [comment]
As Addition: The NetworkCard Element is showing different Macadresses:
![grafik](https://user-images.githubusercontent.com/25504254/206524306-c9e75eeb-ec0d-4bae-8baa-fcb622ee3a78.png)

**Comment by g-bougard** [comment]
Hi @vollkommenIrrelevant 
this is by design: the agent will report network cards and virtual network cards and if there are up or down.
You can disable "Virtual network cards" in Inventory -> Configuration -> Components.
