### ISSUE TITLE
glpi-agent-deployment.vbs fails installing GLPI-Agent : Msiexec returns a 2711 error code with the `ADDLOCAL` parameter

### ISSUE THREAD

**Issue by sebma** [glpi-project/glpi-agent#290]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Hi @g-bougard , your [`glpi-agent-deployment.vbs`](../blob/develop/contrib/windows/glpi-agent-deployment.vbs) VBScript does not install the GLPI-Agent, so I removed the `/quiet` from the [Msiexec options](https://ss64.com/nt/msiexec.html) and replaced the last parameters (` 0, True`) of [`WshShell.Run` at line 547](../blob/develop/contrib/windows/glpi-agent-deployment.vbs#L547) by ` 1, True` (according to this [doc](https://ss64.com/vb/run.html)): 

![glpi-agent-deployment-From-Powershell-ERROR](https://user-images.githubusercontent.com/4569306/206712735-4bc7f592-bb0a-43b8-944d-395f6f1094b7.png)

Here is my `SetupOptions` line : 

```vbscript
SetupOptions = "RUNNOW=1 HTTPD_TRUST='127.0.0.1/32,172.16.5.62' ADDLOCAL='feat_AGENT,feat_NETINV,feat_DEPLOY,feat_COLLECT,feat_WOL' SERVER='https://xxxxxxxxxxxxxx.com/plugins/fusioninventory/'"`
```

How can I make this work ?

### To reproduce

1. Copy `glpi-agent-deployment.vbs` to `glpi-agent-deployment-SEB.vbs`
2. Run `powershell.exe` or `cmd.exe` as an Administrator user
3. Type this command : `cscript //nologo ./glpi-agent-deployment-SEB.vbs`

### Expected behavior

GLPI-Agent should be intalled.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

9.5.7

### GLPIInventory plugin or FusionInventory for GLPI plugin version

9.5+4.2

**Comment by sebma** [comment]
Here is the log if I launch it using `/quiet /L*V ./agent-install.log .........` : [agent-install_Issue_290.log](https://github.com/glpi-project/glpi-agent/files/10195280/agent-install_Issue_290.log)

**Comment by sebma** [comment]
Here is a focus on the error that occurs with the [`ADDLOCAL` parameter](https://glpi-agent.readthedocs.io/en/latest/installation/windows-command-line.html#command-line-parameters) value : 
```log
MSI (s) (9C:28) [14:39:58:620]: Note: 1: 2711 2: 'feat_AGENT 
Action start 14:39:58: CostFinalize.
DEBUG: Error 2711:  The specified Feature name (''feat_AGENT') not found in Feature Table.
MSI (s) (9C:28) [14:39:58:620]: Product: GLPI Agent 1.4 -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2711. The arguments are: 'feat_AGENT, , 

The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2711. The arguments are: 'feat_AGENT, , 
Action ended 14:39:58: CostFinalize. Return value 3.
Action ended 14:39:58: INSTALL. Return value 3.
```

**Comment by stonebuzz** [comment]
Maybe a ```quote``` problem, can you retry with ```double quote``` ?

**Comment by stonebuzz** [comment]
maybe without (from doc : double quotes (") doesn't work with UNCs.)

```
ADDLOCAL=feat_AGENT,feat_NETINV,feat_DEPLOY,feat_COLLECT,feat_WOL
```

**Comment by g-bougard** [comment]
Hi @sebma 
anyway, please remove `feat_AGENT` from `ADDLOCAL` as it is always installed by default. You should also remove `feat_WOL` has this is still not supported by GLPI Agent. And we didn't planed to support it in a near future. If you need this feature, you should probably try to use a linux agent for WOL.
As explained in the documentation, `feat_AGENT` should only be used without any feature to restrict the installation to only inventory task.

**Comment by g-bougard** [comment]
@stonebuzz is probably right as we can see the following line in the log:
```
DEBUG: Error 2711:  The specified Feature name (''feat_AGENT') not found in Feature Table.
```
Please, simply remove the quotes from the ADDLOCAL definition.

Also, I suspect running the vbs from a PS environment may make troubles. Try to run it from a CMD  environment.

**Comment by sebma** [comment]
> maybe without (from doc : double quotes (") doesn't work with UNCs.)
> 
> ```
> ADDLOCAL=feat_AGENT,feat_NETINV,feat_DEPLOY,feat_COLLECT,feat_WOL
> ```

@stonebuzz Indeed, that was the solution that worked on my system.

Thanks a lot to you @stonebuzz and @g-bougard .

**Comment by stonebuzz** [comment]
@sebma 
please upgrade your GLPI to latest version to prevent this

https://glpi-project.org/security-update-10-0-3-and-9-5-9/

best regards

**Comment by stonebuzz** [comment]
You can use 

https://github.com/glpi-project/glpi-inventory-plugin
 (FusionInventor fork) to get a version compatible with GLPI 10.0.5 =)

**Comment by sebma** [comment]
> @sebma please upgrade your GLPI to latest version to prevent this
> 
> https://glpi-project.org/security-update-10-0-3-and-9-5-9/
> 
> best regards

@stonebuzz Thanks for the tip. We are planning to upgrade GLPI production Server to 10.0.5 but first we need to replace the FusionInventory Agent by GLPI-Agent on all our workstations.

**Comment by sebma** [comment]
> You can use
> 
> https://github.com/glpi-project/glpi-inventory-plugin (FusionInventor fork) to get a version compatible with GLPI 10.0.5 =)

@stonebuzz Our GLPI test server is running GLPIv10.0.5+glpi-inventory-plugin v1.0.5

**Comment by stonebuzz** [comment]
Fusion agent is compatible with glpiinventory (SNMP, deploy, collect)  and GLPI native inventory.
You can migrate to glpi-agent easily and quietly after migrating your GLPI
