### ISSUE TITLE
 Many unnecessary records are generated in the inventory history

### ISSUE THREAD

**Issue by Badkempachi** [glpi-project/glpi-agent#291]
> No. #13565 fix missing information on logged events; that won't fix anything.
> 
> On a GLPI point of view, there is no bug here. Both provided inventory files has different contents on softwares, therefore GLPI adds/deletes them; that's expected.

Agree that this is not normal. From what I saw, the problem lies on the Windows 10 operating system, I don’t observe this problem on Linux and windows server.
And what is most interesting is that not all computers on Windows 10 behave this way, but only some of them. But it's still not very clear what the problem is, the computers themselves are in the domain and are controlled by GPO.
From the logs, I see that the problem with the generation of repeated events with the installation\removal of software began, in fact, from the beginning of November 2022.

_Originally posted by @Badkempachi in https://github.com/glpi-project/glpi/issues/13559#issuecomment-1344311949_

**Comment by stonebuzz** [comment]
Hi @Badkempachi 

Can you give us more details on how you execute the agent (windows service, task, powershell, personnal script)

Best regards

**Comment by stonebuzz** [comment]
is it the same user connected to the PC at each inventory?

**Comment by stonebuzz** [comment]
How do you deploy the agent (VBS, GPO, manual install) ?

**Comment by Badkempachi** [comment]
> Hi @Badkempachi
> 
> Can you give us more details on how you execute the agent (windows service, task, powershell, personnal script)
> 
> Best regards

Windows service

**Comment by Badkempachi** [comment]
> is it the same user connected to the PC at each inventory?

yes

**Comment by stonebuzz** [comment]
Can you enable debug mode 2 and redirect output to file (from registry : need to restart the service)

then post here log file when inventory is complete and when inventory is incomplete

**Comment by Badkempachi** [comment]
> How do you deploy the agent (VBS, GPO, manual install) ?

GPO + Powershell (I use it to check for the presence of an agent on the computer and check for a new version on the AD server)
The agent is installed with the following command.
.\GLPI.msi /quiet ADD_FIREWALL_EXCEPTION=1 ADDLOCAL=ALL RUNNOW=1 SCAN_HOMEDIRS=1 SCAN_PROFILES=1 SERVER=https://glpi.local.com/marketplace/glpiinventory CA_CERT_FILE="C:\Program Files\GLPI-Agent\cert.pem"

**Comment by Badkempachi** [comment]
> Can you enable debug mode 2 and redirect output to file (from registry : need to restart the service)
> 
> then post here log file when inventory is complete and when inventory is incomplete

setting up is not a problem, But how to understand that it "incomplete"? Or did I misunderstand

**Comment by stonebuzz** [comment]
When you observed software deletion from glpi =)

**Comment by Badkempachi** [comment]
> When you observed software deletion from glpi =)

Good. I will be able to provide inventory files, most likely, only on 12.12.2022

**Comment by Badkempachi** [comment]
> Can you enable debug mode 2 and redirect output to file (from registry : need to restart the service)
> 
> then post here log file when inventory is complete and when inventory is incomplete

Hi @stonebuzz 
Attached the inventory files where the problem was found.
PS. : today I performed the GLPI update from the night build (2022-12-10), I performed the update after the inventory file was received, the addition of software was recorded there.  Regarding the second inventory file, where an action in the form of software removal was recorded, this information was recorded with an updated agent from the night build (GLPI-Agent-1.5-git299c43e3-x64).
*del*

**Comment by stonebuzz** [comment]
Hi @Badkempachi 
I still find differences between the XMl files
![image](https://user-images.githubusercontent.com/7335054/207059543-cb8c8ce8-a10d-461d-9087-4ae95172c3a0.png)

@g-bougard any idea ?

Best regards

**Comment by Badkempachi** [comment]
The information about the software has not been changed. Only personal data has been changed.

**Comment by stonebuzz** [comment]
So this issue is solved.

Please open a new issue for ```personal data```. 

Best regards

**Comment by Badkempachi** [comment]
> So this issue is solved.
> 
> Please open a new issue for `personal data`.
> 
> Best regards

No, you misunderstood me, in the inventory files I changed only the information containing personal information and at the same time changed this information in both files in the same way. The problem with software inventory remained the same.

**Comment by stonebuzz** [comment]
ha okay, I understand

**Comment by stonebuzz** [comment]
@g-bougard 

we still have some differences in the software list (between two run)

**Comment by Badkempachi** [comment]
I tried to figure it out myself, but I still didn't understand. If it was one computer, then this is one thing, it could be assumed that a conflict with some kind of software.   it conflicts and does not allow me to get information about the software, but I have about 30 computers with this problem.
I also attach information from the computer's inventory history, and it is clear that there are times when changes are not fixed and it should always do so, but for some reason this does not happen.
The question also arises, why is the UUID change fixed, although in fact it does not happen?

![history](https://user-images.githubusercontent.com/97535165/207067233-badecff1-5c21-46ed-875f-557746f8dace.jpg)

**Comment by stonebuzz** [comment]
No change between two files

![image](https://user-images.githubusercontent.com/7335054/207067716-e46a7094-3780-414d-a666-e0a27ebc25f3.png)

Just set as upper case

**Comment by g-bougard** [comment]
Maybe @Badkempachi should just use a larger backend-collect-timeout option value. I think the UUID upper/lower case change is an issue of WMI timeouts.
The timeout can be a result of a overloaded computer during the inventory or maybe corrupted wmi datastore.

**Comment by Badkempachi** [comment]
> Maybe @Badkempachi should just use a larger backend-collect-timeout option value. I think the UUID upper/lower case change is an issue of WMI timeouts. The timeout can be a result of a overloaded computer during the inventory or maybe corrupted wmi datastore.


I changed the inventory execution interval to every 5 hours. Checked the work of WMI, found no errors.  I'll write about the results tomorrow.

**Comment by g-bougard** [comment]
`backend-collect-timeout` is an option for the agent which default to 180. Its unit is "seconds", so the default timeout pour wmi inventory step which involves WMI call is 3 minutes. You can rise up it to 5 or 10 minutes, at least for testing. Edit it in registry and restart the agent service.

**Comment by Badkempachi** [comment]
> 

Hi @g-bougard 
Increasing the timeout on the computer helped. Thanks.
And can you tell me what the UUID change is related to? In my case, it is taken into account that a case change occurs, but what affects it?
![result](https://user-images.githubusercontent.com/97535165/207255254-34c55acd-69a2-4a1f-90ed-ddb05517e130.png)

**Comment by g-bougard** [comment]
Hi @Badkempachi 
great to hear changing the timeout fixes your issue. This may be a recurrent problem on long running windows OS based computer as far I saw.
About UUID case change, when I'm not totally sure, but I think sometime the agent catches it from dmidecode output and sometime via wmi depending on the impact of timeouts. This is still not clear to me and as I still didn't get any computer over the hand with such problem, I really can't be sure.
