### ISSUE TITLE
failed to exec /etc/cron.hourly/glpi-agent: Exec format error

### ISSUE THREAD

**Issue by haary** [glpi-project/glpi-agent#298]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

When glpi-agent 1.4 is installed on  Debian (and possibly other Linux Distros as well) with the perl installer script to run as cron job, the cron job fails with the following error message 

> /etc/cron.hourly/glpi-agent:
> run-parts: failed to exec /etc/cron.hourly/glpi-agent: Exec format error
> run-parts: /etc/cron.hourly/glpi-agent exited with return code 1
> 

The cause is that the script /etc/cron.hourly/glpi-agent  is not correctly formatted. Instead of shebang with the interpreter in the first line, there is a newline.

### To reproduce

1. Install glpi-agent  with `./glpi-agent-1.4-linux-installer.pl --no-httpd --cron` on Debian 
2. Wait for the next cron run or execute  `run-parts /etc/cron.hourly/`
3. An error mesage appears

> run-parts: failed to exec /etc/cron.hourly//glpi-agent: Exec format error
> run-parts: /etc/cron.hourly//glpi-agent exited with return code 1
> 

### Expected behavior

The cron script /etc/cron.hourly//glpi-agent runs without errors. 

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.3

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.4

**Comment by g-bougard** [comment]
Hi @haary 
thank you for this report.
