### ISSUE TITLE
Error with proxy plugin

### ISSUE THREAD

**Issue by fjcobo** [glpi-project/glpi-agent#30]
### Documentation

- [X] Yes, I do

### Solution search

- [x] Yes, I do

### Professional support

Yes, I know

### Is your help request related to a problem?

I´m triying to configure glpi-agent proxy plugin. I get the service up. Then, from another agent I configure the following URL in server: http://PROXY_AGENT_IP/proxy/glpi.

When agent sent inventory to proxy I can see this logs:

![image](https://user-images.githubusercontent.com/51161356/143014538-f4e9a595-f60c-4782-bad0-ef90b986a530.png)

I don't see any errors, but I can't see the inventory on the server either.

### Expected behavior

Getting the inventory on server side.

### Actions you've considered

I have added the parameters (only_local_store = no | local_store = /tmp ) but it doesn't generate the file locally either.

**Comment by g-bougard** [comment]
Hi @fjcobo 
your log is only showing a successfully transmitted PROLOG request. If this is the first time the agent reaches the server it will probably wait a moment but less than an hour. Does the agent came back and this time an INVENTORY request was transmitted ?

**Comment by fjcobo** [comment]
Hi @g-bougard 
No, after all the day, I only can see PROLOG requests. Inventory Module is enabled in agent side.

**Comment by g-bougard** [comment]
Okay, what do you see in the agent side log then ?

**Comment by fjcobo** [comment]
Agent side log:
![imagen](https://user-images.githubusercontent.com/51161356/143211770-976ad606-424c-4d98-aeb4-5c7ccb2f17c5.png)

**Comment by g-bougard** [comment]
You should enable debug2 on agent side to check more deeply.
Indeed, you seem to have enable SSL server plugin on the proxy, so the problem may be related to it: did you install the SSL proxy server certificate on the client ?

**Comment by fjcobo** [comment]
With debug=2 no additional error is observed. Yes, I had enabled SSL server on proxy side but I had no-ssl-check=1 on agent side too.
Now, I have disabled SSL plugin on proxy and everything is ok. 
Thanks for you time.

**Comment by g-bougard** [comment]
Hi @fjcobo 
thank you for your feedback.
Anyway SSL server plugin should still work with proxy one at the same time. So I'll investigate to find any regression with that configuration.

**Comment by g-bougard** [comment]
Hi @fjcobo 
just for your information, I just pushed a fixed so you can use SSL server plugin with Proxy server plugin. See 73986331a or try next nightly build.
