### ISSUE TITLE
netdiscovery does not see the printer Godex, but snmpwalk see

### ISSUE THREAD

**Issue by PlintuZz** [glpi-project/glpi-agent#31]
### Documentation

- [X] Yes, I do

### Solution search

- [X] Yes, I do

### Professional support

Yes, I know

### Expected behavior

```
> glpi-netdiscovery --first 192.168.0.242 --last 192.168.0.242 --credentials version:2c,community:public --debug
[debug] Logger backend Stderr initialized
[debug] initializing job 1
[debug] initializing block 192.168.0.242-192.168.0.242
[debug] Current run expiration timeout: soon
[debug] creating 1 worker threads
[debug] [thread 1] creation
[debug] [thread 1] #1, scanning 192.168.0.242
[debug] [thread 1] #1, - scanning 192.168.0.242 with SNMP, credentials 1: no result, no response from host 192.168.0.242
[debug] [thread 1] #1, - scanning 192.168.0.242 with netbios: no result
[debug] [thread 1] #1, - scanning 192.168.0.242 with echo ping: success
[debug] [thread 1] #1, - scanning 192.168.0.242 in arp table: no result
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <DNSHOSTNAME>192.168.0.242</DNSHOSTNAME>
      <IP>192.168.0.242</IP>
    </DEVICE>
    <MODULEVERSION>4.4</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
[debug] [thread 1] termination
[debug] All netdiscovery threads terminated
```

### Actions you've considered

```
> snmpwalk -v 2c -c public 192.168.0.242
SNMPv2-MIB::sysDescr.1.1 = STRING: MST-SKL-G530
SNMPv2-MIB::sysDescr.1.2 = STRING: 000000
SNMPv2-MIB::sysDescr.1.3 = STRING: BOOT :1.007
SNMPv2-MIB::sysDescr.1.4 = STRING: F/W : G530 V1.100 (Dec 19 2019 16:23:16-01)

SNMPv2-MIB::sysDescr.1.5 = STRING: PCB : 248010

SNMPv2-MIB::sysDescr.1.6 = STRING: Mac Address : 00-1d-9a-07-c5-1e
SNMPv2-MIB::sysDescr.1.7 = STRING: 192.168.0.242
SNMPv2-MIB::sysDescr.1.8 = STRING: 00 Ready
SNMPv2-MIB::sysDescr.1.9 = STRING: Total printing length 00000499 METER(S)
SNMPv2-MIB::sysDescr.20.1 = STRING: PaperOut Error happens 0 times

SNMPv2-MIB::sysDescr.20.2 = STRING: Paper Jam Error happens 0 times

SNMPv2-MIB::sysDescr.20.3 = STRING: Ribbon Out Error 0 times

SNMPv2-MIB::sysDescr.20.4 = STRING: Door Open Error happens 0 times

SNMPv2-MIB::sysDescr.20.5 = STRING: Rewinder Full Error 0 times

SNMPv2-MIB::sysDescr.20.6 = STRING: File System Full Error happens 0 times

SNMPv2-MIB::sysDescr.20.7 = STRING: Name Not Found Error 0 times

SNMPv2-MIB::sysDescr.20.8 = STRING: NameDuplicate Error happens 0 times

SNMPv2-MIB::sysDescr.20.10 = STRING: Cutter Jam Error happens 0 times

SNMPv2-MIB::sysDescr.20.11 = STRING: TPH Over Heat Error happens 0 times

HOST-RESOURCES-MIB::hrDeviceStatus.1 = INTEGER: running(2)
SNMPv2-MIB::sysDescr.1.1 = STRING: MST-SKL-G530
Error: OID not increasing: HOST-RESOURCES-MIB::hrDeviceStatus.1
 >= SNMPv2-MIB::sysDescr.1.1
```

**Comment by g-bougard** [comment]
Hi @PlintuZz 

you should have followed [snmpwalk output](https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output) to generate the snmpwalk.

Anyway it seems you have a wrong value in `SNMPv2-MIB::sysDescr.1.2` as private snmp oid is expected there. The string "000000" is simply wrong but maybe you'll obtain another output using the right options. If not, you should first ask Godex why such a value is obtained there. Then they may have published a new firmware for your printer which could have a fix it.

**Comment by PlintuZz** [comment]
[walk-filename.zip](https://github.com/glpi-project/glpi-agent/files/7642625/walk-filename.zip)
i update firmware and generate walk file, but this file incluide one string.

snmpwalk -v 2c -c public -t 15 -Cc -On -Ox 192.168.0.242 .1
End of MIB

**Comment by g-bougard** [comment]
It means your walk is indeed empty. Are you sure your printer was online at the time you made it ?

**Comment by PlintuZz** [comment]
Yes, sure. 
if i dont give root oid it creates a file like this 
[godex_g530.zip](https://github.com/glpi-project/glpi-agent/files/7647736/godex_g530.zip)

.1.3.6.1.2.1.1.1.1.1 = STRING: MST-SKL-G530
.1.3.6.1.2.1.1.1.1.2 = STRING: 000000
.1.3.6.1.2.1.1.1.1.3 = STRING: BOOT :1.007
.1.3.6.1.2.1.1.1.1.4 = STRING: F/W : G530 V1.Y64 (Dec 31 2019 17:15:36-01)

.1.3.6.1.2.1.1.1.1.5 = STRING: PCB : 248010

.1.3.6.1.2.1.1.1.1.6 = STRING: Mac Address : 00-1d-9a-07-c5-1e
.1.3.6.1.2.1.1.1.1.7 = STRING: 192.168.0.242
.1.3.6.1.2.1.1.1.1.8 = STRING: 00 Ready
.1.3.6.1.2.1.1.1.1.9 = STRING: Total printing length 00000500 METER(S)
.1.3.6.1.2.1.1.1.20.1 = STRING: PaperOut Error happens 0 times

.1.3.6.1.2.1.1.1.20.2 = STRING: Paper Jam Error happens 0 times

.1.3.6.1.2.1.1.1.20.3 = STRING: Ribbon Out Error 0 times

.1.3.6.1.2.1.1.1.20.4 = STRING: Door Open Error happens 0 times

.1.3.6.1.2.1.1.1.20.5 = STRING: Rewinder Full Error 0 times

.1.3.6.1.2.1.1.1.20.6 = STRING: File System Full Error happens 0 times

.1.3.6.1.2.1.1.1.20.7 = STRING: Name Not Found Error 0 times

.1.3.6.1.2.1.1.1.20.8 = STRING: NameDuplicate Error happens 0 times

.1.3.6.1.2.1.1.1.20.10 = STRING: Cutter Jam Error happens 0 times

.1.3.6.1.2.1.1.1.20.11 = STRING: TPH Over Heat Error happens 0 times

**Comment by g-bougard** [comment]
Hi @PlintuZz 
as sysObjectID OID entry is still set to just "000000", you should contact Godex manufacturer and complain why such a value is found there. They must provide you a firmware correctly setting this entry. But maybe they just don't own such private OID. In that case, they should set a standard entry with their name so we can recognize them safely as manufacturer.
We can't support such poorly designed hardware without a manufacturer official answer.
I'm closing this issue, but feel free to reopen with their official answer.
