### ISSUE TITLE
duplicates record with network discovery threads > 1

### ISSUE THREAD

**Issue by mareban** [glpi-project/glpi-agent#313]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

I still have but want a public following to keep the community aware

### Describe the bug

Hi,

We've installed the GLPI 10.0.5 and GLPI-Agent 1.4-1 on an Ubuntu 22.04 VM server with 2 vcpus !

We are using the default rules and when we are doing a network discovery on the web console with the default value for the plugin, we are getting some ramdom duplicates of devices after cleaning and rescanning again (duplicates xml files generated  to import) !!

We've tried hard to avoid the problem using the rules and field uniqueness (duplicate reported but always imported !!?) to avoid duplicate without success :-(

Setting the network discovery thread only to one fix the issue but the discovery is very slow ! 

Is it a bug or do we miss something on our installation ?

Thanks for your help.

### To reproduce

network discovery

### Expected behavior

no duplicate asset

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.5

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.0.6

### Additional context

.

**Comment by g-bougard** [comment]
Hi @mareban 

as you claimed to have a professional support, can you also open a ticket linking this issue and with the following datas ? This will be more appropriate to exchange sensible datas.
After you enabled the debug=2 in configuration and restarted the agent, we will need the full agent log for the following cases:
1. when the task runs with thread=1 and you don't have any duplicate,
2. when the task runs with thread>1 and you have duplicates. And in that case, you'll have to tell us which duplicates you found.

Eventually, did you try with a [nightly build](https://nightly.glpi-project.org/glpi-agent/) ?

**Comment by mareban** [comment]
Thx for your reply ! Sorry for professional support , my bad , GLPI is not yet in prod and is evaluated !!

Ok, we'll try the nighly build, thanks for your help.

**Comment by mareban** [comment]
With the nightly build of the glpi agent, same result  :-( !

We've tried to scan small or big range of subnets dedicated to our network devices or printers and always get random amount of duplicates ! When we remove those duplicates, all seems to update well !

With only one thread everything is running well but it is very slow !

We don't know if it is a bug, a misconfiguration somewhere, a dependancy problem or whatever !

So we are lost and maybe we will consider to use a previous version with fusion inventory or find another solution if we cannot  fix this weird problem soon   :-( !

Thanks for your help.

PS : we've tried to set a field uniqueness on serial , the duplicates are reported but imported even setting the "import denied" !!??

**Comment by g-bougard** [comment]
Okay, so I'm closing this issue as you seem to give up and I still don't see any info that can help us to debug the problem.
Just an advice about the "very slow" problem: don't hesitate to reduce the timeout to 1 as this is the timeout for one snmp request.

**Comment by mareban** [comment]
Thanks for your help ! We don't want to give up, but we don't want to spend time on an issue on a fresh install (server+application+db+agent) for an issue of the discovery and import assets process  that is random (the number of assets imported is variable but always with duplicates) !

One thing that i did not mention, is that we force the scan manually, maybe it's not the best way to do that ?

PS : yes, we've already  set the timeout to 1 for a single thread scan :-)

 Anyway Thx.

**Comment by mareban** [comment]
For info, Doing the network discovery and inventory (netdiscovery) and inject the xml results (injector) works fine with command line using threads :-) !

So inventory works fine in command line, but not as expected using the web interface and multi-threading in our installation !?

Something seems to be wrong somewhere , we will try to schedule a scan instead of force it from the web console to see what happen :-) 

Thx

**Comment by g-bougard** [comment]
Maybe next version will fix your problem as there's a big rework on netdiscovery task.
You can eventually try the [last build from the feature/glpi-netscan branch](https://github.com/glpi-project/glpi-agent/actions/runs/3901260455). You'll find debian packages in the Debian-Build artifact.
