### ISSUE TITLE
Linux perl installer doesn't support user/password options for HTTP authentication

### ISSUE THREAD

**Issue by yodapotatofly** [glpi-project/glpi-agent#315]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

The perl installer doesn't have options to use User and Password parameter for HTTP authentication from the agent to the server

### To reproduce

`perl glpi-agent-1.4-linux-installer.pl --help`

### Expected behavior

`--user` and `--password` options should be present

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.5

**Comment by g-bougard** [comment]
Hi @yodapotatofly 
thank you for your issue submission.
Next nightly build will include the fix.

**Comment by yodapotatofly** [comment]
Thanks
