### ISSUE TITLE
Acer V247Y wrong serial

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi-agent#322]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

The agent reads the serial number incorrectly, because of this, the monitor moves between computers, it is necessary to change the Serial and AltSerial for this model.

### To reproduce

GLPI-Agent_v1.4
Acer V247Y

### Expected behavior

The correct serial number.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.5

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.0.6

### Additional context

```
    <MONITORS>
      <ALTSERIAL>TJZEE00620704d948574</ALTSERIAL>
      <BASE64>AP///////wAEcnIHlE1wIAcgAQNoNR54Ls5lpldRnycPUFS/74BxT4FAgYCBwIEAlQCzANHAKkSAoHA4J0AwIDUADyghAAAaAAAA/QA4TB5VFQAKICAgICAgAAAA/ABWMjQ3WQogICAgICAgAAAA/wBUSlpFRTAwNjg1NzQKAEM=</BASE64>
      <CAPTION>V247Y</CAPTION>
      <DESCRIPTION>7/2022</DESCRIPTION>
      <MANUFACTURER>Acer Technologies</MANUFACTURER>
      <NAME>Универсальный монитор PnP</NAME>
      <PORT>VGA</PORT>
      <SERIAL>TJZEE0068574</SERIAL>
      <TYPE>Универсальный монитор PnP</TYPE>
    </MONITORS>
```
EDID 
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\DISPLAY\ACR0772

![image](https://user-images.githubusercontent.com/16879167/214578898-c17e17f9-9f57-4193-b686-1ff00253d78d.png)

**Comment by g-bougard** [comment]
Hi @kofe88 
I'll include a fix for next release.
Anyway, for that problem a solution on server-side would probably be more appropriate.
Can you up-vote that GLPI feature request ? https://github.com/glpi-project/glpi/issues/10165

**Comment by g-bougard** [comment]
Hi @kofe88 
tomorrow [nightly build](https://nightly.glpi-project.org/glpi-agent/) should fix your issue, can you please test it on affected computers ?

**Comment by kofe88** [comment]
@g-bougard 
Greetings! Yes, it solved the problem with this monitor model!
