### ISSUE TITLE
No Office Licence inventory due to License.pm

### ISSUE THREAD

**Issue by lordimac** [glpi-project/glpi-agent#323]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

GLPI Agent does not inventory Office Licences. Running the Agent with debug2 I get the following error in my output:

```
[debug] Running GLPI::Agent::Task::Inventory::Win32::License
[debug] unexpected error in GLPI::Agent::Task::Inventory::Win32::License: Can't use string ("") as a HASH ref while "strict refs" in use at C:/Program Files/GLPI-Agent/perl/agent/GLPI/Agent/Task/Inventory/Win32/License.pm line 137.
```

Line 137 is occording to the inventory of office licences.

### To reproduce

Running glpi-inventory.bat --debug --debug --json > C:\TEMP\glpi.json

### Expected behavior

Inventory of office licences

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.5

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.0.6

**Comment by g-bougard** [comment]
Hi @lordimac 
thank you for your report.
You should have a value key with an empty string under `HKEY_LOCAL_MACHINE/SOFTWARE/Microsoft/Office` or `HKEY_LOCAL_MACHINE/SOFTWARE/Wow6432Node/Microsoft/Office` i nyour registry. This is not really expected. Can you check your registry and tell us what is this key ? It can probably be safely removed. Indeed no value key even not empty is expected there.
I'll fix the issue but this is interesting to know what really triggered the problem.

**Comment by g-bougard** [comment]
Hi @lordimac 
anyway tomorrow [nightly build](https://nightly.glpi-project.org/glpi-agent/) should work as expected, would you please test it ?

**Comment by lordimac** [comment]
Oh wow, thank you. Didnt see this at all. The (Default) Value of `HKEY_LOCAL_MACHINE/SOFTWARE/Wow6432Node/Microsoft/Office` was set to nothing but after deleting it the Agent is running fine.

I tested your change in Licence.pm right now and it works even with empty (Default) key. Thanks!
