### ISSUE TITLE
Inventory not made (HTTP 500) when computer created before inventory without UUID

### ISSUE THREAD

**Issue by felag** [glpi-project/glpi-agent#325]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

When computers are created without UUID and before inventory with agent, default ruleset prevents computer information to be imported.

Changing default rules to have rule "Computer update by serial." at first allows inventory.

### To reproduce

1. create a computer with name and serial (without UUID)
2. Install glpi-agent on computer and launch inventory

Inventory is not done and an error occur on PC, agent logs show:
92.168.205.38 - - [22/Nov/2022:11:15:46 +0100] "POST /glpi/plugins/glpiinventory/ HTTP/1.1" 500 - "-" "GLPI-Agent_v1.5-git95f66476"

### Expected behavior

When no UUID exist in already existing computer with serial but without UUDI:

* 2 first default rules "Computer update by uuid" and "Computer update by serial+uuid" should not match,
* allowing rule "Computer update by serial" to match and update computer inventory

### Operating system

Windows

### GLPI Agent version

1.4, Nightly build (git version in additional context below)

### GLPI version

10.0.5

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.0.x (See additional context below)

### Additional context

GLPi Inventory 1.0.5

**Comment by g-bougard** [comment]
Hi @felag 
sorry I don't see any GLPI-Agent bug there. First you're speaking about server rules, so your concerned is against server, not agent. Then default rules are there to help in the most general context. In your specific case, you have to adjust rules to your needs. If you think there's a bug in rules themselves, open an issue on the GLPI project.

**Comment by felag** [comment]
@g-bougard Thanks for precision: I agree that it is "rules" related and not glpi-agent related.

FYI: I have submitted [same issue here](https://github.com/glpi-project/glpi/issues/13940) on glpi repository.
