### ISSUE TITLE
Acer R240HY and SAMSUNG S24D300 wrong serial

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi-agent#328]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Wrong serial:

---

ACER R240HY

        "monitors": [
            {
                "altserial": "T4BEE00C112089502411",
                "base64": "AP\/\/\/\/\/\/\/wAEcm8EUIkgEQwfAQOANR547gVlp1ZSnCcPUFSzDABxT4GAgcCBAJUAswDRwAEBAjqAGHE4LUBYLEUADyghAAAeAAAA\/QA4Sx9LEgAKICAgICAgAAAA\/ABSMjQwSFkKICAgICAgAAAA\/wBUNEJFRTAwQzI0MTEKAVg=",
                "caption": "R240HY",
                "description": "12\/2021",
                "manufacturer": "Acer Technologies",
                "name": "Generic PnP Monitor",
                "serial": "T4BEE00C2411",
                "type": "Generic PnP Monitor"
            }
        ],
	
EDID ACR046F

---

SAMSUNG S24D300

	
        "monitors": [
            {
                "altserial": "0AJHHLER500092",
                "base64": "AP\/\/\/\/\/\/\/wBMLUILSEpBMBUfAQMONR54Kp\/xpVVQniYQUFS\/74BxT4HAgQCBgJUAqcCzAAEBAjqAGHE4LUBYLEUAEyshAAAeAAAA\/QA4Sx5REQAKICAgICAgAAAA\/ABTMjREMzAwCiAgICAgAAAA\/wBITEVSNTAwMDkyCiAgAHg=",
                "caption": "S24D300",
                "description": "21\/2021",
                "manufacturer": "Samsung Electric Company",
                "name": "\u0423\u043d\u0438\u0432\u0435\u0440\u0441\u0430\u043b\u044c\u043d\u044b\u0439 \u043c\u043e\u043d\u0438\u0442\u043e\u0440 PnP",
                "serial": "HLER500092",
                "type": "\u0423\u043d\u0438\u0432\u0435\u0440\u0441\u0430\u043b\u044c\u043d\u044b\u0439 \u043c\u043e\u043d\u0438\u0442\u043e\u0440 PnP"
            }
	
EDID SAM0B42	

---

### To reproduce

GLPI-Agent_v1.4
ACER R240HY
EDID SAM0B42

### Expected behavior

The correct serial number.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

**Comment by g-bougard** [comment]
Hi @kofe88 
can you at least confirm `altserial` numbers are the right serials to use ?

**Comment by kofe88** [comment]
Hi @g-bougard 

For ACER R240HY its the right.

```json

        "monitors": [
            {
                "altserial": "T4BEE00C112092112411",
                "base64": "AP\/\/\/\/\/\/\/wAEcm8EEZIgEQwfAQOANR547gVlp1ZSnCcPUFSzDABxT4GAgcCBAJUAswDRwAEBAjqAGHE4LUBYLEUADyghAAAeAAAA\/QA4Sx9LEgAKICAgICAgAAAA\/ABSMjQwSFkKICAgICAgAAAA\/wBUNEJFRTAwQzI0MTEKAY4=",
                "caption": "R240HY",
                "description": "12\/2021",
                "manufacturer": "Acer Technologies",
                "serial": "T4BEE00C2411"
            }

```

![image](https://user-images.githubusercontent.com/16879167/220571914-432c6e22-376a-41f0-bfb5-72a6ac5cbcac.png)

---


For SAMSUNG S24D300 It's not necessary yet, we need to investigate more.

**Comment by g-bougard** [comment]
Hi @kofe88 
okay, thank you, so I added the support for the Acer monitor.
