### ISSUE TITLE
network inventory not working for somes switchs

### ISSUE THREAD

**Issue by cencen99** [glpi-project/glpi-agent#329]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

The network inventory is not working properly for some switches. There is only one available port: management.
I have errors in the SQL error log: Error: 
-Out of range value for column 'netmask_3' at row 1 for glpi_ipnetworks
-Error: Out of range value for column 'binary_0' at row 1 for glpi_ipaddresses

### To reproduce

launch network inventory on network

### Expected behavior

all ports be inventoried.

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

### Additional context

glpit agent 1.5 git75728309

trying with a fresh installation with debian 11, apache2, mariadb: still no inventory from some switches.

**Comment by g-bougard** [comment]
Hi @cencen99 
sorry, this is really not a glpi-agent issue and you provide no evidence it could be. You even provide nothing we can use to reproduce the problem as you even completely broke the SQL request while trying to obfuscate your private data.
Please open an issue on GLPI project, but replace ips in the sql-error log with valid ips telling they are not real ips.
