### ISSUE TITLE
macOS: certificate should be stored in the Keychain, not inside GLPI-Agent.app/etc

### ISSUE THREAD

**Issue by grahampugh** [glpi-project/glpi-agent#33]
### Documentation

- [X] Yes, I do

### Professional support

Still not applicable

### Is your feature request related to a problem?

It is bad practice to require dynamic configuration to be placed within an app bundle on macOS, since this prevents signing and notarisation of the app (see also #32). In the context of certificates, macOS has a secure keystore called the Keychain. This is the correct place for certificates to be stored and read by applications. This allows the certificates to be securely deployed via MDM.

### Expected behavior

The GLPI certificate should be stored and read from the macOS Keychain.

### Alternatives you've considered

N/A.

**Comment by g-bougard** [comment]
Hi @grahampugh 

thank you, this is a great idea.

Actually, perl library only supports reading pem files.

I will check how we can support macOS Keychain but I think we can at least export the needed server certificate in a convenient place (probably `/Library/Application Support/GLPI-Agent`) and configure it automatically.

I guess a command like the following where GLPI_SERVER is replaced by the hostname of the glpi server url could make the job:
```
security find-certificate -a -c "GLPI_SERVER" -p >GLPI_SERVER.pem
```

**Comment by g-bougard** [comment]
Hi @grahampugh 

I prepared an update for this feature request. Do you have time to test it ?

You need to install latest nightly as the #142 PR is based on a refacto which simplify it a lot. After you have installed it, you just need to replace in your installation, the `/Applications/GLPI-Agent/agent/GLPI/Agent/HTTP/Client.pm` file by this one: [Client.pm](https://raw.githubusercontent.com/glpi-project/glpi-agent/b1eec1426162cbc56995859d896f37d14d0c1456/lib/GLPI/Agent/HTTP/Client.pm).

In the case you're using on of `ca-cert-file` or `ca-cert-dir` options, you also need to clear it before the feature could be enabled.

To explain the purpose of the update: it will generate a file including the output of `security find-certificate -a -p` and this file will be used like it was set for `ca-cert-file` option. The file is cached for 1 hour and will be re-generated on first SSL access on glpi server after the program or service is started. So you'll also have to restart the service after the update has been applied.

**Comment by g-bougard** [comment]
@grahampugh 
you can also directly try the dev PKG from the MacOSX-Build artifact from the [GH Actions run #2487594387](https://github.com/glpi-project/glpi-agent/actions/runs/2487594387). The only pitfall is the development builds are not notarized so you'll have to by-pass the system security.
