### ISSUE TITLE
After the inventory does not change the name of the current PC user

### ISSUE THREAD

**Issue by stereosoul** [glpi-project/glpi-agent#332]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

After the inventory does not change the name of the current PC user. It remains the username that was during the last successful inventory.

### To reproduce

1.Install and configure agent
2.Force inventory
3. Look at results in GLPI

### Expected behavior

Current PC user must change

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

**Comment by g-bougard** [comment]
Hi @stereosoul 

I'm not sure this is an agent issue, but can you provide the output of the following command before and after the user has changed ?
```
glpi-inventory --partial user
```
On windows, open an administrative console, change your directory to the glpi-agent installation folder and run the given command.

If reported user is the same. You or the agent may have missed something.
If the user is different, this will help to reproduce the problem.

**Comment by stereosoul** [comment]
I tried to reproduce the problem on several devices and realized that the problem is only with one.
output of command glpi-inventory --partial user gives the correct result ( current logged in user), but on the asset page the user does not change ( only on one machine). How it is possible to diagnose it on the problem machine?

**Comment by stereosoul** [comment]
![ws-4058](https://user-images.githubusercontent.com/81831199/216563569-5b236720-61de-4673-b06e-ae503f2898d3.png)
last logged user is aleksey.meshkov but in asset its marina.zeltser ( previous user on this machine)

**Comment by g-bougard** [comment]
You should also check on the asset if the user was not set manually in the past to it appears in the "locks" tab.
If yes, just remove the lock.

**Comment by stereosoul** [comment]
Nope, this field not locked.
![user](https://user-images.githubusercontent.com/81831199/216573905-85ad359c-8879-4087-a467-73ef9575fb4b.png)
![locks](https://user-images.githubusercontent.com/81831199/216573911-488dbe65-92f3-4930-b14e-5f48195ff9c4.png)

**Comment by g-bougard** [comment]
Just in case, you should also check the computer history to see if the asset is not updated by 2 different computers.
Anyway, this doesn't seem to be an agent issue. Check the GLPI php-errors.log file for an error related to this computer inventory import.

You can store the partial inventory generated earlier and try to import it manually. Then if nothing changes, check for errors on glpi log files.

**Comment by stereosoul** [comment]
Thanks!

**Comment by UnknownA8** [comment]
Sorry to refresh. I have exactly the same problem. There are no errors anywhere. The agent on the computer show to the correct current user after using the glpi-inventory --partial user command. In GLPI still i have user who was log on while first inventory. In inventory history of computer others application/devices are updating correct.
