### ISSUE TITLE
[error] [http client] failed to uncompress content starting with: 

### ISSUE THREAD

**Issue by jcl-64** [glpi-project/glpi-agent#334]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

I still have but want a public following to keep the community aware

### Describe the bug

in glpi-agent.log file, closing each inventory report, last sentence is always : 
**[error] [http client] failed to uncompress content starting with:**
(There is nothing else after that)

- Computer inventory is done and glpi server receive it with all components 
- but there is no result for the tasks "network scan NMAP"
- 5 agents on 5 computers give the same error
- installed agents may scan the netwok when using the toolbox agent
- All the tasks and jobs "Scan NMAP" fail with message "The agent requests a configuration that has already been sent to it by the server. The agent may have encountered a critical error"

### To reproduce

glpi 10.0.5 on Ubuntu
plug'in GLPI Inventory
Agent 1.4

### Expected behavior

waiting for "network scan" task complete to add network components

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.5

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

### Additional context

Many thanks if someone have had the same issue and have an answer.

**Comment by stonebuzz** [comment]
SNMP Discovery and Inventory are not design for Computer 
It's for Network Equipment (Switch, Printer).
Please install agent on it.

Best regards
