### ISSUE TITLE
Add documentation on option "ca-cert-dir"

### ISSUE THREAD

**Issue by SteadEXE** [glpi-project/glpi-agent#34]
### Documentation

- [X] Yes, I do

### Solution search

- [X] Yes, I do

### Professional support

Yes, I know

### Expected behavior

I expect the documentation to tell us hown to use the "ca-cert-dir" configuration.

### Actions you've considered

I tried to search Online, but without success.

### Additional context

Hello,

In the case of a CA change, we don't want our agents to get disconnected from GLPI.
I see that ca-cert-dir option is made to be able to put multiple CA certificates. 
But the documentation says "Indexed Certificates". I don't know how to index them, I tried multiple time to find how to do it without success.
Maybe can you give me a hint, or maybe add the way to do it in the documentation?

Thanks :)

**Comment by g-bougard** [comment]
Hi @SteadEXE 

you are right, this is missing in first expected place. Indeed the information is available at only one place: for the CA_CERT_DIR at [windows command line parameters doc](https://glpi-agent.readthedocs.io/en/latest/installation/windows-command-line.html#command-line-parameters)

I'll backport this content in the configuration doc too.

**Comment by g-bougard** [comment]
Just a point, did you try to concatenate all you CA certificates in the file pointed by ca-cert-file option ?

**Comment by g-bougard** [comment]
I updated the configuration doc: [ca-cert-dir configuration](https://glpi-agent.readthedocs.io/en/latest/configuration.html#ca-cert-dir)

I'm closing the issue but feel free to request further explanation if you think you missed something.
