### ISSUE TITLE
Please add this Ubiquiti Switch and Unifi Access Point

### ISSUE THREAD

**Issue by dellywputra** [glpi-project/glpi-agent#343]
Hi,
I have some 
- Switch Ubiquiti USW-48-G2
- Access point UniFi U6-LR
- Access point UniFi UAP-AC-HD

but it seems isn't in glpi-agent database sysobject.ids. Here is it the example output of my UniFi Switch,

```
[root@es-03 tgj]# glpi-netdiscovery --credentials version:2c,community:BRIN --debug --host 10.61.254.254
[debug] Logger backend Stderr initialized
[debug] GLPI Agent (1.4-1)
[info] Can't load Net::NBName, netbios can't be used
[debug] initializing job 1
[debug] initializing block 10.61.254.254-10.61.254.254
[debug] Current run expiration timeout: soon
[debug] creating 1 worker threads
[debug] [thread 1] creation
[debug] [thread 1] glpi-project/sysobject.ids#1, scanning 10.61.254.254
[debug] [thread 1] glpi-project/sysobject.ids#1, full match for sysobjectID .1.3.6.1.4.1.8072.3.2.10 in database
[debug] [thread 1] glpi-project/sysobject.ids#1, sysobjectID match: linux mib support enabled
[debug] [thread 1] glpi-project/sysobject.ids#1, - scanning 10.61.254.254 with SNMP, credentials 1: success
[debug] [thread 1] glpi-project/sysobject.ids#1, - scanning 10.61.254.254 with echo ping: success
[debug] [thread 1] glpi-project/sysobject.ids#1, - scanning 10.61.254.254 in arp table: no result
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <AUTHPORT />  <AUTHPROTOCOL />  <AUTHSNMP>1</AUTHSNMP>
      <CONTACT>Default</CONTACT>
      <DESCRIPTION>Linux MKS-BASS-Gedung-A 3.18.24 #0 Thu Aug 30 12:10:54 2018 mips</DESCRIPTION>
      <DNSHOSTNAME>10.61.254.254</DNSHOSTNAME>
      <IP>10.61.254.254</IP>
      <IPS>
        <IP>10.61.254.254</IP>
        <IP>127.0.0.1</IP>
      </IPS>
      <LOCATION>Default</LOCATION>
      <MAC>d0:21:f9:57:9a:1b</MAC>
      <MANUFACTURER>Net-SNMP</MANUFACTURER>
      <MODEL>Linux</MODEL>
      <SNMPHOSTNAME>MKS-BASS-Gedung-A</SNMPHOSTNAME>
      <TYPE>COMPUTER</TYPE>
      <UPTIME>16 hours, 57:50.29</UPTIME>
    </DEVICE>
    <MODULEVERSION>5.1</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
[debug] [thread 1] termination
[debug] All netdiscovery threads terminated
```

Thankyou.

**Comment by g-bougard** [comment]
Hi @dellywputra 
can you provide a [full snmpwalk output](https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output) for your device ?
There's still some Ubiquiti support in LinuxAppliance but maybe this device is newer and so not detected as expected.
Also provide any MIB you can own related to these devices.
I remember to have such request in the past related to Unifi AP, and I'm definitively not sure that device can be inventoried. If I remember well, SNMP support may be too cheap in information.

**Comment by dellywputra** [comment]
Hi @g-bougard
Here I attach the full results of my Ubiquiti USW-48-G2 snmpwalk.
if I may ask, when I insert this device via glpi-agent into glpi it is categorized as an unmanaged device not as a network device, why is that?

Thank you.

[snmpwalk Ubiquit USW-48G-G2.txt](https://github.com/glpi-project/glpi-agent/files/10702859/snmpwalk.Ubiquit.USW-48G-G2.txt)

**Comment by g-bougard** [comment]
Hi @dellywputra 
it is not in the format I asked (follow the link I gave please).
Anyway, after a quick view, if this is only all the OIDs we can pull from the device, don't expect we can do anything with them: I see nothing telling this is related to an ubiquiti device or to decide if it's really a networking device. So the reason you have it in unmanaged: we don't have enough information to manage it.

**Comment by dellywputra** [comment]
Hi @g-bougard 
Sorry for that,
Here I attach the following as you directed.
I have new information regarding the device, now this device is no longer included in the unmanaged device category but now, it is included in the computer category which should be included in the network device category.

[walk-filename.txt](https://github.com/glpi-project/glpi-agent/files/10712210/walk-filename.txt)

**Comment by g-bougard** [comment]
Hello @dellywputra 
thank you the walk is better and I was able to identify a very useful OID from which I can discover the IANA enterprise ID. This way, the agent will now use it to look up the sysObjectID database file to get the manufacturer and the default device type for this manufacturer. You can set a model for the default enterprise, for this device, I found "27282" as ManufacturerID but this will set the same model for all such Ubiquiti devices. Actually, with the update from 10c4ec5, the agent will report "Linux" as model for your device. The best way to handle this info is probably just to edit manually the model in GLPI so it will also be locked. Anyway, now you'll have the right manufacturer and type. The serial is set to the digits only MAC address and if I remember well, this is correct for Ubiquiti devices.
