### ISSUE TITLE
Wrong informations - Monitor - AG Neovo E-191

### ISSUE THREAD

**Issue by AntoninGP** [glpi-project/glpi-agent#344]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Trouble: Hello, when am tring to inventory a monitor, don't have the correct manufacturer and serial number:

Monitor:
Brand: AG neovo 
Model: E-191
S/N: C1E19K0694900831

>       "monitors": [
>         {
>            "base64": "AP///////wAFIyAZgQUAADETAQNtJR546v1WpVNKnSQUT1S/74BFRnFAcU+BQIFPgYCBioGPMCoAmFEAKkAwcBMAdy0RAAAeAAAA/QAxSx5QDgAKICAgICAgAAAA/ABFLTE5MQogICAgICAgAAAA/wAxNDA5CiAgICAgICAgACU=",
>            "caption": "E-191",
>            "description": "49/2009",
>            "manufacturer": "Arnos Insturments & Computer Systems",
>            "serial": "1409"
>         }
>      ],
>      "versionclient": "GLPI-Agent_v1.4"

Thanks

### To reproduce

do an inventory with glp-agent (partial or not)

### Expected behavior

>       "monitors": [
>         {
>            "base64": "AP///////wAFIyAZgQUAADETAQNtJR546v1WpVNKnSQUT1S/74BFRnFAcU+BQIFPgYCBioGPMCoAmFEAKkAwcBMAdy0RAAAeAAAA/QAxSx5QDgAKICAgICAgAAAA/ABFLTE5MQogICAgICAgAAAA/wAxNDA5CiAgICAgICAgACU=",
>            "caption": "E-191",
>            "description": "49/2009",
>            "manufacturer": "AG neovo",
>            "serial": "C1E19K0694900831"
>         }
>      ],
>      "versionclient": "GLPI-Agent_v1.4"

### Operating system

Windows, Linux

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

### Additional context
I tried with MonitorInfoView v1.22 from NirSoft, same errors, it seems to be an EDID mistake.

**Comment by g-bougard** [comment]
Hi @AntoninGP 
this is a pretty old model ;-) So it may have some compatibility issues.
Anyway I made some searches. Actually the EDID block is reporting AIC as manufacturer code. This code was registered as "Arnos Insturments & Computer Systems" in PNP ID list (See https://uefi.org/pnp_id_list). And yes, it was registered with the typo on "intruments". Anyway, if I check the "AG Neovo" wikipedia page, I see this is another name for "Associated Industries China, Inc."... so the AIC better means "Associated Industries China". What is wrong here with this monitor is they're using a PNP ID they didn't register. We can fix the manufacturer.
For the serial, "1409" is really a string recorded in the EDID as S/N. Maybe AG Neovo has an encoding scheme for monitor S/N, but we aren't aware and I didn't find any information about it on internet. We can only hope this serial is at least unique to avoid collision when you have more than one such monitor. If you have some support contact with AG Neovo, you can request some information to obtain an algorithm to compute the expected S/N. If you obtain such information, we may try to implement them.

**Comment by g-bougard** [comment]
Hi @AntoninGP 
actually, next nightly build will only fix the manufacturer for this monitor.
As I said, we have not enough information to compute the right S/N.
Feel free to reopen if you obtain some information to compute the right S/N.
