### ISSUE TITLE
label for /boot/efi

### ISSUE THREAD

**Issue by liedekef** [glpi-project/glpi-agent#346]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

The label info concerning /boot/efi (type is always vfat) returned by "dosfslabel /dev/nvme0n1p1" is in some cases "There are differences between boot sector and its backup."

### To reproduce

On a fedora 37, running agent 1.4, the info concerning /boot/efi (type is always vfat) returned by "dosfslabel /dev/nvme0n1p1" is:

```
[root@laptop]# fatlabel /dev/nvme0n1p1
There are differences between boot sector and its backup.
This is mostly harmless. Differences: (offset:original/backup)
  65:01/00
  Not automatically fixing this.
```

While this (among others) means no label is present (but it in fact means the dirty bit is set), I'm seeing as label in glpi "There are differences between boot sector and its backup.". This is the first line of the output, as returned by Task/Inventory/Linux/Drives.pm for vfat.

So, some things here:
- use fatlabel, no longer dosfslabel
- don't use the output from fatlabel if the first line is "There are differences between boot sector and its backup" :-)

### Expected behavior

No label if the content is "There are differences between boot sector and its backup."

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

**Comment by g-bougard** [comment]
Hi @liedekef 
thank you for your issue.
We can't remove `dosfslabel` to keep compatibility for older systems. But we can of course first check for `fatlabel`.
Can you try to apply the following patch and tell me if it works in the case there's no label for you:
```diff
diff --git a/lib/GLPI/Agent/Task/Inventory/Linux/Drives.pm b/lib/GLPI/Agent/Task/Inventory/Linux/Drives.pm
index a8edcfbe4..f5810bf5b 100644
--- a/lib/GLPI/Agent/Task/Inventory/Linux/Drives.pm
+++ b/lib/GLPI/Agent/Task/Inventory/Linux/Drives.pm
@@ -55,7 +55,8 @@ sub _getFilesystems {
     # Anyway attempt to get details with filesystem-dependant utilities
     my $has_dumpe2fs   = canRun('dumpe2fs');
     my $has_xfs_db     = canRun('xfs_db');
-    my $has_dosfslabel = canRun('dosfslabel');
+    my $has_fatlabel   = canRun('fatlabel');
+    my $has_dosfslabel = $has_fatlabel ? 0 : canRun('dosfslabel');
 
     foreach my $filesystem (@filesystems) {
         if ($filesystem->{FILESYSTEM} =~ /^ext(2|3|4|4dev)/ && $has_dumpe2fs) {
@@ -93,11 +94,14 @@ sub _getFilesystems {
             next;
         }
 
-        if ($filesystem->{FILESYSTEM} eq 'vfat' && $has_dosfslabel) {
-            $filesystem->{LABEL} = getFirstLine(
+        if ($filesystem->{FILESYSTEM} eq 'vfat' && ($has_fatlabel || $has_dosfslabel)) {
+            my $label = getLastLine(
                 logger  => $logger,
-                command => "dosfslabel $filesystem->{VOLUMN}"
+                command => ($has_fatlabel ? "fatlabel" : "dosfslabel")." ".$filesystem->{VOLUMN}
             );
+            # Keep label only if last line starts with a non space character
+            $filesystem->{LABEL} = trimWhitespace($label)
+                if $label =~ /^\S/;
             next;
         }
     }
```
The patch is better analyzing the last line in place of the first one.

**Comment by liedekef** [comment]
Well, I fixed the "dirty bit" issue, so I no longer get the message now. But I checked your suggestion and it seems ok to me.
