### ISSUE TITLE
Incorrect work with Cyrillic

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi-agent#349]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Incorrect work with Cyrillic in the English version of WIndows with installed programs, versions of which use Cyrillic in the name and in the developers. Instead of Cyrillic, there are question marks.

In the Windows system itself, the language is displayed correctly.

### To reproduce

1. Install WIndows 10x64 with eng language
2. Install the program with Cyrillic in the title or in the author
3. Perform inventory

### Expected behavior

Correct Cyrillic display

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

### Additional context

```json
 {
                "arch": "x86_64",
                "from": "registry",
                "guid": "{7261C35C-6C36-4978-96A4-E54ABCC82A1F}",
                "install_date": "2023-02-21",
                "name": "Yandex Browser",
                "publisher": "??? \u00ab??????\u00bb",
                "system_category": "application",
                "uninstall_string": "MsiExec.exe \/X{7261C35C-6C36-4978-96A4-E54ABCC82A1F}",
                "version": "23.1.2.931"
            },
```

```json

            {
                "arch": "i586",
                "from": "registry",
                "guid": "Office16.PROPLUS",
                "install_date": "2023-02-21",
                "name": "Microsoft Office ???????????????? ???? 2016",
                "no_remove": false,
                "publisher": "Microsoft Corporation",
                "system_category": "application",
                "uninstall_string": "\"C:\\Program Files (x86)\\Common Files\\Microsoft Shared\\OFFICE16\\Office Setup Controller\\setup.exe\" \/uninstall PROPLUS \/dll OSETUP.DLL",
                "version": "16.0.4266.1001"
            },

```

![image](https://user-images.githubusercontent.com/16879167/220549529-61e34c0e-8ed5-4b32-94b5-12229896eb61.png)

![image](https://user-images.githubusercontent.com/16879167/220549667-ea0cc918-ca1b-408d-a297-1e66deda9b1b.png)

![image](https://user-images.githubusercontent.com/16879167/220549781-c671b293-9321-41d0-a401-a5b4dc1368a0.png)

**Comment by g-bougard** [comment]
Hi @kofe88 
can you share a registry export of the following keys:
```
HKEY_LOCAL_MACHINE/SOFTWARE/Microsoft/Windows/CurrentVersion/Uninstall
HKEY_LOCAL_MACHINE/SOFTWARE/Wow6432Node/Microsoft/Windows/CurrentVersion/Uninstall
```
I need at least the subkeys related to faulty softwares.

I also need to know the value you have in `HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Control/Nls/CodePage/ACP` key.

**Comment by kofe88** [comment]
@g-bougard , Hi

![image](https://user-images.githubusercontent.com/16879167/221566645-5c5c0b34-5e1c-4763-8293-5f8c6634513c.png)

[regs.zip](https://github.com/glpi-project/glpi-agent/files/10839877/regs.zip)

**Comment by g-bougard** [comment]
Hi @kofe88 
was not easy to fix but next nightly build should fix your issue.
