### ISSUE TITLE
Remote Management - Supremo

### ISSUE THREAD

**Issue by ddemetris** [glpi-project/glpi-agent#35]
### Documentation

Yes, I read it

### Is your feature request related to a problem?

Hello,

If it's possible to support Supremo Remote Desktop, as it's almost the same as TeamViewer

HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Supremo
    ClientID    REG_DWORD    0xXXXXXXXX

HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\teamviewer
    ClientID    REG_DWORD    0xXXXXXXXX

### Expected behavior

The Supremo ID to be shown in the Remote Management category of the computers

### Alternatives you've considered

N/A

**Comment by g-bougard** [comment]
Hi @ddemetris 

this could be interesting as this product seems also to have a client for linux and MacOSX, thank you for your suggestion.

Do you know if the client installs a link binding on the system so we may also think to add such support on GLPI side ?

**Comment by ddemetris** [comment]
Hello,

I have asked their support and they said that is not possible to generate a link to directly connect.

The way it works from their web based client is by using
`supremo:XXXXXXXXX`
from a browser that sends the ID to the Supremo client (tested on Windows) whether:

`HKEY_CLASSES_ROOT\supremo
    (Default)    REG_SZ    Supremo URI
    URL Protocol    REG_SZ
    Content Type    REG_SZ    application/x-supremo

HKEY_CLASSES_ROOT\supremo\shell
    (Default)    REG_SZ    open

HKEY_CLASSES_ROOT\supremo\shell\open\command
    (Default)    REG_SZ    "C:\Program Files (x86)\Supremo\Supremo.exe" "%1"
`

**Comment by g-bougard** [comment]
Closing as #179 is merged.
