### ISSUE TITLE
Links with the real parc

### ISSUE THREAD

**Issue by chris29B** [glpi-project/glpi-agent#354]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Good morning,
I have a problem with links with GLPI Agent on the machines. I had before OCS agents on the machines, I deployed via GPO GLPI Agent 1.4 which communicates perfectly with the console.
But I have about a quarter of the posts that create no links and when I look in the import information, nothing, no rules.

I looked at the PHP and Mysql log file, there is nothing

### To reproduce

1. Agent Inventory
2. Connection to console
3. Looks the rules for import and links

### Expected behavior

Link don't use any rules
![bugs1](https://user-images.githubusercontent.com/102288193/222380116-775324d1-70c3-47a5-9904-953c22376d98.png)
![bugs2](https://user-images.githubusercontent.com/102288193/222380131-74b4d559-6788-472c-9b6b-222900cb4373.png)
![bugs3](https://user-images.githubusercontent.com/102288193/222380041-d442e3ff-c619-4646-b0e4-e057ef93b9d3.png)

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

**Comment by g-bougard** [comment]
Hi @chris29B 

this is a server issue, not an agent one afaik.

This is also a support request and you should better request support from the community on the GLPI forum.
You can also purchase a GLPI subscription with one of our partner if you need some professional support.

Also only reproducible bug should be reported here. Nothing in your reported information can give us a way to reproduce your problem... unless you give us access to your systems. My guess is you really need a professional support.

**Comment by chris29B** [comment]
I understand. Thanks for your response
Kind regards
