### ISSUE TITLE
Inventory History adding / deleting due to ampersand in software name

### ISSUE THREAD

**Issue by supertramp4** [glpi-project/glpi-agent#359]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Hi, I am using a nightly build probably from 2 months ago ( GLPI 10.1.0-dev ), and i have noticed that if  software contains a & in the title, then it is constantly being deleted, and added.
Looking at the database, in the glpi_logs table, you can clearly see the entries as follows

id;itemtype;items_id;itemtype_link;linked_action;user_name;date_mod;id_search_option;old_value;new_value
2846870;Computer;5;Software;17;inventory;2023-03-08 12:36:03;0;;Design & Print - 2.2.0
2847013;Computer;5;Software;19;inventory;2023-03-08 12:36:03;0;;Design &#38; Print - 2.2.0
2852076;Computer;5;Software;17;inventory;2023-03-08 16:20:57;0;;Design & Print - 2.2.0
2852080;Computer;5;Software;19;inventory;2023-03-08 16:20:57;0;;Design &#38; Print - 2.2.0

The GLPI Inventory json file shows the software as 

{"arch":"i586","from":"registry","guid":"Design & Print 2.2.0","helplink":"www.avery.co.uk","install_date":"2022-11-16","name":"Design & Print","publisher":"Avery Products Corp.","system_category":"application","uninstall_string":"C:\\Program Files (x86)\\Design&Print\\uninstall.exe","version":"2.2.0","version_major":"2","version_minor":"2"}

I hope one of you clever people can identify the reason ?

### To reproduce

Normal operation

### Expected behavior

It should not replace the & with #38;

### Operating system

Windows

### GLPI Agent version

1.2

### GLPI version

development release (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.0.x (See additional context below)

### Additional context

GLPI Inventory Plugin 1.0.4

**Comment by g-bougard** [comment]
Hi @supertramp4 

using an ampersand in json format is valid. So this is not an agent issue.

Please open an issue on the [server glpi project](https://github.com/glpi-project/glpi/issues).

**Comment by stonebuzz** [comment]
Hi @supertramp4 please retry with GLPI niglhty build (version 10.0 not main)

https://nightly.glpi-project.org/glpi/

Please open an issue on the [server glpi project](https://github.com/glpi-project/glpi/issues) if problem persist

Best regards
