### ISSUE TITLE
Add an option to migrate from Fusion Inventory to GLPI Agent ?

### ISSUE THREAD

**Issue by SteadEXE** [glpi-project/glpi-agent#36]
### Documentation

Yes, I read it

### Professional support

Yes, I know

### Is your feature request related to a problem?

Not really a problem, but an improvement

### Expected behavior

I would like to get a flag to be able to uninstall Fusion Inventory when installating GLPI agent.

### Alternatives you've considered

At the moment, we have to deploy two GPO, one that uninstall Fusion Inventory, one that install GLPI Agent.

### Additional context

I know there was an option built in the Fusion Inventory to uninstall OCS Inventory.
It could be a good idea to get the same option to uninstall Fusion Inventory Agent when installing GLPI Agent.

Otherwise, the agent works great :)

**Comment by g-bougard** [comment]
Hi @SteadEXE 

thank you for your suggestion.

I still answered it some months ago in #13. At the moment we didn't make that choice. I can understand having 2 GPOs for a migration is worst than having 1 to replace the agent service but at least you know what you're doing ;-) and after the migration you will be able to remove the one uninstalling FI.

I didn't notice such an option in FusionInventory installer, but maybe that was in a very old development.

**Comment by SteadEXE** [comment]
Hi @g-bougard I understand,

It was an idea, at the moment, nothing prevent us from working.
Thank you for your reply 👍 

Have a nice day.

**Comment by WebGregGit** [comment]
Batch...


```
	IF EXIST "\\%computername%\c$\Program Files\FusionInventory-Agent\Uninstall.exe" (
		psexec.exe \\!%computername%! "c:\Program Files\FusionInventory-Agent\Uninstall.exe" /S
	)
```

**Comment by g-bougard** [comment]
I included an option (disabled by default) in the vbs to ask for FusionInventory-Agent uninstall.
The option also permits to get `server` or `local` from FusionInventory-agent configuration found in registry before the uninstall.

**Comment by SteadEXE** [comment]
Sweet.
