### ISSUE TITLE
Frequently different inventory results

### ISSUE THREAD

**Issue by AndiMb** [glpi-project/glpi-agent#360]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

We are facing frequently changing inventory results of the GLPI Agent injected to the server for some of our windows clients.

This can be seens in the computer history.
![image](https://user-images.githubusercontent.com/5680717/224344858-3908b946-2c11-40ba-856a-39e217c71fb6.png)

Additional some of our windows clients have a very short software list with 40-50 software products while all other have 190-200.

On the GLPI Agent side we see a lot of WMI time outs. Due to https://github.com/glpi-project/glpi-agent/issues/232 we installed a nighlty build of the GLPI Agent some of the timeouts are gone, but there are still the changing results. We have scan_profiles active. When we disable scan_profile it seems to work. 

This is not happening on clients on non-AD/Domain clients.

### To reproduce

1. Install GLPI-Agent 1.4 with scan-profile=1 or Install GLPI-Agent 1.5-nightly build with scan_profile=1

### Expected behavior

Get the same inventory result in each inventory.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

**Comment by g-bougard** [comment]
Hi @AndiMb 

thank you for your issue submission.

As you pointed yourself #232 and everything seems to work on `clients on non-AD/Domain clients`, you seem to experiment another issue related to AD timeouts during software inventory and this time because you're using the `scan-profiles` option.

On a concerned computer, can you generate the output of the following command obfuscating any sensible data ? To run it, you should open an administrative console and run it from the glpi-agent installation folder.
```
glpi-inventory --debug --debug --partial software --scan-profiles >NUL
```
For now, I don't request you to share the generated json as the command will redirect stdout output to `NUL` special file.
Indeed, I just want by now to see errors in debug=2 level. Can you also tell if the output is blocking, at which line and for how long ?
You can also share the agent log showing the WMI timeouts after you set debug level to 2 and remove any sensible data in that log.

Can you also share the output of the following command and tell how many time it takes ?
```
wmic path Win32_UserProfile get sid,localpath,special
```

**Comment by AndiMb** [comment]
Sorry, for the late reply. I'm having trouble to reproduce the error, when running the inventory with the given command in an admin console. The only difference I see, is that the Agent is normaly running as "System" and the command now as "Administrator". So I have to reset scan-profiles and the debug for the Agent again and check the output in the logs.

**Comment by AndiMb** [comment]
This is the relevant part of the log, where the first timeout happens.
```
...
[Wed Mar 15 13:24:07 2023][debug2] Looking for Win32_ParallelPort class WMI objects
[Wed Mar 15 13:24:07 2023][debug2] Looking for Win32_PortConnector class WMI objects
[Wed Mar 15 13:24:07 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::Printers
[Wed Mar 15 13:24:07 2023][debug2] Looking for Win32_Printer class WMI objects
[Wed Mar 15 13:24:07 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::Slots
[Wed Mar 15 13:24:07 2023][debug2] Looking for Win32_SystemSlot class WMI objects
[Wed Mar 15 13:24:07 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::Softwares
[Wed Mar 15 13:24:07 2023][debug2] Doing SELECT * FROM Win32_UserProfile WHERE LocalPath IS NOT NULL AND Special=FALSE WMI query
[Wed Mar 15 13:24:08 2023][debug2] Doing SELECT * FROM Win32_UserAccount WHERE Disabled='False' AND Lockout='False' AND SID='S-1-5-....' WMI query
[Wed Mar 15 13:27:06 2023][debug2] _loadUserSoftwareFromHKey_Users(S-1-5-....) : add of 2 softwares in inventory
[Wed Mar 15 13:27:17 2023][debug2] _loadUserSoftwareFromHKey_Users(S-1-5-....) : add of 1 softwares in inventory
[Wed Mar 15 13:27:28 2023][debug] GLPI::Agent::Task::Inventory::Win32::Softwares killed by a timeout
[Wed Mar 15 13:27:28 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::Sounds
[Wed Mar 15 13:30:27 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::Storages
...
```
All later steps like sound, takes a very long time. In this case 3 minutes each perhaps due to the 180 seconds timeout.

**Comment by g-bougard** [comment]
Hi @AndiMb 
can you try to set `backend-collect-timeout` to **300** (to set it to 5 minutes) or even **600** (for 10 minutes) ? The default is 300 which stand for 3 minutes and it seems the timeout occurred around 3 minutes.
Then do you still see timeout after that update ?

**Comment by AndiMb** [comment]
I tried 300 seconds and it is the same result in the log only the timeout happens after 5 minutes insteed of 3 minutes.

```
[Wed Mar 15 15:12:51 2023][debug2] Looking for Win32_ParallelPort class WMI objects
[Wed Mar 15 15:12:51 2023][debug2] Looking for Win32_PortConnector class WMI objects
[Wed Mar 15 15:12:51 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::Printers
[Wed Mar 15 15:12:51 2023][debug2] Looking for Win32_Printer class WMI objects
[Wed Mar 15 15:12:51 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::Slots
[Wed Mar 15 15:12:51 2023][debug2] Looking for Win32_SystemSlot class WMI objects
[Wed Mar 15 15:12:51 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::Softwares
[Wed Mar 15 15:12:51 2023][debug2] Doing SELECT * FROM Win32_UserProfile WHERE LocalPath IS NOT NULL AND Special=FALSE WMI query
[Wed Mar 15 15:12:52 2023][debug2] Doing SELECT * FROM Win32_UserAccount WHERE Disabled='False' AND Lockout='False' AND SID='S-1-5-...' WMI query
[Wed Mar 15 15:17:49 2023][debug2] _loadUserSoftwareFromHKey_Users(S-1-5-...) : add of 2 softwares in inventory
[Wed Mar 15 15:17:51 2023][debug2] _loadUserSoftwareFromHKey_Users(S-1-5-...) : add of 1 softwares in inventory
[Wed Mar 15 15:18:02 2023][debug2] _loadUserSoftwareFromHKey_Users(S-1-5-...) : add of 2 softwares in inventory
[Wed Mar 15 15:18:02 2023][debug] GLPI::Agent::Task::Inventory::Win32::Softwares killed by a timeout
[Wed Mar 15 15:18:02 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::Sounds
[Wed Mar 15 15:22:59 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::Storages
[Wed Mar 15 15:28:21 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::USB
```
I will try 10 minutes next.

**Comment by g-bougard** [comment]
How many users can be logged on that computer ?

**Comment by AndiMb** [comment]
Hi,
these are normal Windows clients in a PC pool where one person at a time is able to have an active session. But these clients are also accessable over RDP so in a few cases there can be situations where one person is logged on physically and another remote, where one session is active and another inactive. But these a rare cases.

**Comment by AndiMb** [comment]
Here is the log of the test with 600 seconds (10 minutes), which has the timeout after 10 minutes.
The higher the value of the timeout the more accounts are looped. It seems the agent is looping over all domain accounts that where logged on to this client at some time. But beside the local admin I was using no other account had an active session.

```
[Wed Mar 15 16:58:32 2023][debug2] Looking for Win32_ParallelPort class WMI objects
[Wed Mar 15 16:58:32 2023][debug2] Looking for Win32_PortConnector class WMI objects
[Wed Mar 15 16:58:32 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::Printers
[Wed Mar 15 16:58:32 2023][debug2] Looking for Win32_Printer class WMI objects
[Wed Mar 15 16:58:32 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::Slots
[Wed Mar 15 16:58:32 2023][debug2] Looking for Win32_SystemSlot class WMI objects
[Wed Mar 15 16:58:32 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::Softwares
[Wed Mar 15 16:58:32 2023][debug2] Doing SELECT * FROM Win32_UserProfile WHERE LocalPath IS NOT NULL AND Special=FALSE WMI query
[Wed Mar 15 16:58:32 2023][debug2] Doing SELECT * FROM Win32_UserAccount WHERE Disabled='False' AND Lockout='False' AND SID='S-1-5-...' WMI query
[Wed Mar 15 17:08:26 2023][debug2] _loadUserSoftwareFromHKey_Users(S-1-5-...) : add of 2 softwares in inventory
[Wed Mar 15 17:08:32 2023][debug2] _loadUserSoftwareFromHKey_Users(S-1-5-...) : add of 1 softwares in inventory
[Wed Mar 15 17:08:43 2023][debug2] _loadUserSoftwareFromHKey_Users(S-1-5...) : add of 2 softwares in inventory
[Wed Mar 15 17:08:54 2023][debug] GLPI::Agent::Task::Inventory::Win32::Softwares killed by a timeout
[Wed Mar 15 17:08:54 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::Sounds
[Wed Mar 15 17:18:45 2023][info] Timeout reached on SELECT * FROM Win32_UserAccount WHERE Disabled='False' AND Lockout='False' AND SID='S-1-5-...' WMI query
[Wed Mar 15 17:18:45 2023][debug2] Doing SELECT * FROM Win32_UserAccount WHERE Disabled='False' AND Lockout='False' AND SID='S-1-5-...' WMI query
[Wed Mar 15 17:18:48 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::Storages
[Wed Mar 15 17:29:10 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::USB
[Wed Mar 15 17:39:04 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::Users
[Wed Mar 15 17:49:26 2023][debug] Running GLPI::Agent::Task::Inventory::Win32::Videos
[Wed Mar 15 17:50:02 2023][info] Timeout reached on SELECT * FROM Win32_UserAccount WHERE Disabled='False' AND Lockout='False' AND SID='S-1-5-...' WMI query
[Wed Mar 15 17:50:02 2023][debug2] Doing SELECT * FROM Win32_UserAccount WHERE Disabled='False' AND Lockout='False' AND SID='S-1-5-...' WMI query
[Wed Mar 15 17:59:20 2023][debug] Section DRIVES has changed since last inventory
[Wed Mar 15 17:59:20 2023][debug] Section FIREWALL has changed since last inventory
[Wed Mar 15 17:59:20 2023][debug] Section LICENSEINFOS has changed since last inventory
[Wed Mar 15 17:59:20 2023][debug] Section PRINTERS has changed since last inventory
```

**Comment by g-bougard** [comment]
Indeed, I see there a strange behavior. The agent effectively scan the 3 users profiles it found, but only at the end of the timeout: after 5 minutes in your previous test and after 10 minutes in this last one. So it seems the agent is blocked until it decides to kill the module inventory run... the kill seems to free some resources which leaves the module run a few time to log it detects softwares for users.
I must now find a way to reproduce than behavior.

**Comment by AndiMb** [comment]
All I can say is that the 
`wmic path Win32_UserAccount WHERE "SID='S-1-5-...' AND Disabled='False' AND Lockout='False'"`
in our environment (AD forest with thousands of accounts and multiple domains) takes at least two minutes to deliver a result.

**Comment by g-bougard** [comment]
Hi @AndiMb 
just saw an interesting case, what's the timing of such request in your environement ?
```
wmic path Win32_UserAccount WHERE "SID LIKE 'S-1-5-...' AND Disabled='False' AND Lockout='False'"
```
The only difference with your test is the `=` changed to ` LIKE `, but still with the exact expected value. It seems the way that request is run could be less problematic than using the "equal" sign.

**Comment by g-bougard** [comment]
Even you can try the following patch on the agent:
```perl
diff --git a/lib/GLPI/Agent/Tools/Win32/Users.pm b/lib/GLPI/Agent/Tools/Win32/Users.pm
index 0b91bc7a4..288b7d759 100644
--- a/lib/GLPI/Agent/Tools/Win32/Users.pm
+++ b/lib/GLPI/Agent/Tools/Win32/Users.pm
@@ -69,10 +69,10 @@ sub getUsers {
         Lockout='False'
     );
     push @conditions, "LocalAccount='True'" if $params{localusers};
-    push @conditions, "SID='$params{sid}'" if $params{sid};
+    push @conditions, "SID LIKE '$params{sid}'" if $params{sid};
     if ($params{login}) {
         $params{login} =~ s/'/\\'/g;
-        push @conditions, "Name='$params{login}'";
+        push @conditions, "Name LIKE '$params{login}'";
     }
 
     my $query = "SELECT * FROM Win32_UserAccount WHERE ".join(" AND ", @conditions);

```

**Comment by AndiMb** [comment]
The change from "=" to "LIKE" doesn't change anything in our environment. The wmic command takes a long time. It seems, it takes so long to collect all the data over all domains in the forest. My test client is not able to see the domain controllers of all domains in the forest due to firewalls, especially the root domain, where all user accounts live. The client is only able to connect to the domain controllers of the domain the client is joint. So the `wmic path Win32_UserAccount WHERE "SID LIKE 'S-1-5-...' AND Disabled='False' AND Lockout='False'"` query delivers no result, if the account is from a domain in the forest, that is not directly reachable for the testclient. But it is just a guess. I have no idea how wmi is working.

**Comment by g-bougard** [comment]
Okay thank you for your feedback.

The purpose of the request is to only catch the username linked to the found SID. This name will be set as installed software user when looking for softwares in profiles.

Can you try the following from an administrative console, replacing the SID with one of your domain ?
```powershell
PS C:\Users\gbougard> $objSID = New-Object System.Security.Principal.SecurityIdentifier ("S-1-5-21-1443555731-1244557431-2223777638-1001")
PS C:\Users\gbougard> $objUser = $objSID.Translate( [System.Security.Principal.NTAccount])
PS C:\Users\gbougard> $objUser.Value
WIN11-22H2-XYZ\gbougard
```
Here this is a sample from one of my test vm. Does it take the same time than the WMI request ?

P.S.:
It seems in the following log there's only one SID which is related to a domain account:
```
[Wed Mar 15 16:58:32 2023][debug2] Doing SELECT * FROM Win32_UserProfile WHERE LocalPath IS NOT NULL AND Special=FALSE WMI query
[Wed Mar 15 16:58:32 2023][debug2] Doing SELECT * FROM Win32_UserAccount WHERE Disabled='False' AND Lockout='False' AND SID='S-1-5-...' WMI query
[Wed Mar 15 17:08:26 2023][debug2] _loadUserSoftwareFromHKey_Users(S-1-5-...) : add of 2 softwares in inventory
[Wed Mar 15 17:08:32 2023][debug2] _loadUserSoftwareFromHKey_Users(S-1-5-...) : add of 1 softwares in inventory
[Wed Mar 15 17:08:43 2023][debug2] _loadUserSoftwareFromHKey_Users(S-1-5...) : add of 2 softwares in inventory
```
Does this account still exist in the domain and is it still used on that computer ?

**Comment by g-bougard** [comment]
Another point, after some digging in my test vm registry, I found some interesting keys.

The first one is: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI\SessionData\1` which contains subkeys which permits to have a link between my username and its sid.
Do you have such this one or even others under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI\SessionData` ?

Another one is `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI\LastLoggedOnUserSID` which can be linked to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI\LastLoggedOnUser` account name. Of course, these registry keys only concern the last logged user, so this is not enough when more the one user are using a computer.

Another promising one is `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\DataStore` where I can find my user account name under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\DataStore\S-1-5-21-1443555731-1244557431-2223777638-1001\0`

**Comment by g-bougard** [comment]
Can you eventually try this patch ?
```patch
diff --git a/lib/GLPI/Agent/Tools/Win32/Users.pm b/lib/GLPI/Agent/Tools/Win32/Users.pm
index 0b91bc7a4..35196b102 100644
--- a/lib/GLPI/Agent/Tools/Win32/Users.pm
+++ b/lib/GLPI/Agent/Tools/Win32/Users.pm
@@ -51,7 +51,34 @@ sub getProfileUsername {
     return $userenvkey->{'/USERNAME'}
         if $userenvkey && defined($userenvkey->{'/USERNAME'}) && length($userenvkey->{'/USERNAME'});
 
-    # Then try WMI request
+    # Then try to get it from Group Policy Caching
+    my $cacheentry = getRegistryKey(
+        path        => "HKEY_LOCAL_MACHINE/SOFTWARE/Microsoft/Windows/CurrentVersion/Group Policy/DataStore/$user->{SID}/0",
+        # Important for remote inventory optimization
+        required    => [ qw/szTargetName/ ],
+    );
+    return $cacheentry->{'/szTargetName'}
+        if $cacheentry && defined($cacheentry->{'/szTargetName'}) && length($cacheentry->{'/szTargetName'});
+
+    # Eventually look up in LogonUI session datas
+    my $sessiondata = getRegistryKey(
+        path        => "HKEY_LOCAL_MACHINE/SOFTWARE/Microsoft/Windows/CurrentVersion/Authentication/LogonUI/SessionData",
+        # Important for remote inventory optimization
+        required    => [ qw/LoggedOnUserSID LoggedOnUser/ ],
+    );
+    if ($sessiondata) {
+        foreach my $key (keys(%{$sessiondata})) {
+            next unless $key =~ m{/$};
+            my $usersid = $sessiondata->{$key}->{'/LoggedOnUserSID'};
+            next unless defined($usersid) && $user->{SID} eq $usersid;
+            my $account = $sessiondata->{$key}->{'/LoggedOnUser'};
+            next unless defined($account);
+            my ($username) = $account =~ /^[^\\]*\\(.*)$/;
+            return $username if defined($username) && length($username);
+        }
+    }
+
+    # Finally try WMI request
     my ($account) = getUsers(sid => $user->{SID});
     return $account->{NAME} if $account && $account->{NAME};
 
```

**Comment by AndiMb** [comment]
Hi,
I tried the patch on different clients and it works like charm. It seems to be a good solution to use the local data.

How is the username used in GLPI? All usernames I can see for software seems to be taken from the computer user.
Is it possible in GLPI to see if a software is installed in a profile?

**Comment by g-bougard** [comment]
Hi @AndiMb 

thank you for your feedback. I'll include that update in the nightly then.

The username should be shown in the installations list for a given software:
![image](https://user-images.githubusercontent.com/12514489/229795200-983e6f85-6708-43d7-99fc-fc578b59902a.png)
You have a user column there where the username should appear.

You should be able to search for the username in the software asset form (see `/front/software.php` from your GLPI base URL). In the software asset list, you can also add the "username" column.

**Comment by AndiMb** [comment]
Thank you for the answer. This is what I expected. But it seems that the user assigned to the computer is used as the user for software. If the Computer has a user assigned I see a user for the Software and if there is no user assigned to the computer the user field is empty. So it seems, that the user account, where the software was installed in the profile, has no impact, has it?

**Comment by g-bougard** [comment]
The username will only be set for software detected in profiles. By default, no user is linked to software installed for all the computer users.
