### ISSUE TITLE
GLPI-Agent 1.7

### ISSUE THREAD

**Issue by RobertoMarcelino** [glpi-project/glpi-agent#361]
### Bug reporting acknowledgment

Not applicable

### Professional support

None

### Describe the bug

The version does not change even if the plugin is updated to a new version.

![image](https://user-images.githubusercontent.com/57845086/224450795-584e9870-0a78-4ad4-9e03-bf62028c4be8.png)

### To reproduce

![image](https://user-images.githubusercontent.com/57845086/224450811-afe83471-6752-44f1-812f-a717cee0b19e.png)

### Expected behavior

The version should reflect the installed agent version.

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.0.6

### Additional context

![image](https://user-images.githubusercontent.com/57845086/224450946-25434f31-312e-42e7-9d0b-98ae75675277.png)

**Comment by g-bougard** [comment]
Hi @RobertoMarcelino 

sorry I made a mistake somewhere updating a script dedicated to release process. The version is even just wrong as the current nightly version should be like 1.5-gitXXXXXX.
So don't use this nightly build, and better try the previous one.

**Comment by g-bougard** [comment]
I fixed the version numbering so next nightly should be a 1.5.

If you still see any trouble about the `The version should reflect the installed agent version` question after you installed the next nightly build, please, open another issue and this time can you include table headers in your screenshots or at least explain how you obtained them. And please, don't copy/paste 3 times the same screenshot in the different form areas, this is just annoying and we can choose to just close the issue for wrong issue tracker usage.
