### ISSUE TITLE
GLPI-Agent v1.4 queries the properties of the domain Administrator account using SAM-R if there is a local Administrator account

### ISSUE THREAD

**Issue by Geo-Ron** [glpi-project/glpi-agent#365]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Still not applicable

### Describe the bug

On a Windows device, the inventory using the GLPI-Agent queries the properties of the Domain administrator account if there is a local administrator account.

The SAM-R query to our domain-controllers occur when the step:
`[debug] Running GLPI::Agent::Task::Inventory::Virtualization::Wsl`
is run.

This in turn triggers an alert at our security monitoring tool that the domain administrator account is queried.

### To reproduce

` .\glpi-inventory.bat --debug --json --partial=virtualmachine`

monitor using WireShark and see the SAM-R requests fly by.

if you rename the local administrator account, that new username is queried on the domain. So I think this query is tied to a specific user SID

### Expected behavior

only keep requests local, if local accounts are inventoried.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

Not applicable

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

### Additional context

I think the code section that is responsible for this resides [here](https://github.com/glpi-project/glpi-agent/blob/develop/lib/GLPI/Agent/Task/Inventory/Virtualization/Wsl.pm). But I can not figure at which part is causing our alerts.

**Comment by g-bougard** [comment]
Hi @Geo-Ron 

Wsl module tries to inventory WSL instance installed by any user. Due to some limitation in the way the OS handles that installations, we must scan all user profiles for such kind of installation.
The way this is done has changed in the current nightly build as we discovered it can involve WMI timeouts (see #232 for more details) when an AD is in use.

So can you try the latest nightly build and tell if the changes still trigger an alert ?

**Comment by Geo-Ron** [comment]
Hi @g-bougard ,

Nice!
If you can show me how to retrieve the latest nightly build, I can try and test it!

**Comment by Geo-Ron** [comment]
> Hi @g-bougard ,
> 
> Nice! If you can show me how to retrieve the latest nightly build, I can try and test it!

Ah, found it. Reading is still an art I guess... 
I will test.

**Comment by Geo-Ron** [comment]
The issue seems to be fixed in the latest nightly build

**v1.4**
![image](https://user-images.githubusercontent.com/23144316/226347184-93d34be7-14fb-42fe-939a-c9076345b597.png)

Latest nightly build (v1.5-gitf87023d1)
![image](https://user-images.githubusercontent.com/23144316/226347771-44aea6a9-a8c3-4c95-bceb-e06f9a9635f2.png)

**Comment by Geo-Ron** [comment]
Is there any ETA on the release of v1.5 ?

**Comment by g-bougard** [comment]
Hi @Geo-Ron 
great to see your problem is fixed in nightly.
We don't still define a date for the 1.5 release. We are still in a Code-signing certificat renewing process and this is a pain with some providers...
I'm closing the issue as it's fixed in nightly.
