### ISSUE TITLE
Can't get inventory of Proxmox VE Node

### ISSUE THREAD

**Issue by haary** [glpi-project/glpi-agent#366]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

A Proxmox VE 7.3 host fails to send its inventory with glpi-agent 1.4 to GLPI 10.0.6. In an attempt to debug the problem  manually, I tried to send XML file (generated by glpi-inventory) via curl and get the following error from the GLPI server:

```
<?xml version="1.0"?>
<REPLY><ERROR><![CDATA[JSON does not validate. Violations:
Required property missing: name, data: {"status":"running","subsystem":"qemu","vcpu":1,"vmtype":"qemu"} at #->properties:content->properties:virtualmachines->items[14]:14
]]></ERROR></REPLY>
```

The problematic section of the XML file is here:
```
    <VIRTUALMACHINES>
      <STATUS>running</STATUS>
      <SUBSYSTEM>qemu</SUBSYSTEM>
      <VCPU>1</VCPU>
      <VMTYPE>qemu</VMTYPE>
    </VIRTUALMACHINES>
```

It looks like glpi-inventory detects one more container/VM than is really there. All other containers are also listed in the XML file. When I delete the problematic section from the XML file, the server accepts it without complaint.

### To reproduce

1. Run glpi-inventory on an host with Proxmox VE 7.3
2. Examine the contents of the generated XML file and find the following at the end:
```
    <VIRTUALMACHINES>
      <STATUS>running</STATUS>
      <SUBSYSTEM>qemu</SUBSYSTEM>
      <VCPU>1</VCPU>
      <VMTYPE>qemu</VMTYPE>
    </VIRTUALMACHINES>
```

### Expected behavior

glpi-inventory should correctly list only Containers/VMs in the XML which actually do exist.

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

### Additional context

The command line tools on the Proxmox VE host (`lxc-ls, pct list, qm list`) correctly only detect the containers/VM that are really there, so it seems that there is no problem with Proxmox VE.

The host is an VPS at Netcup, running Proxmox VE 7.3 installed on top of Debian 11. Since Netcup doesn't allow nested VMs on VPS, Proxmox can only run LXC containers.

**Comment by haary** [comment]
It seems the problem is a running qemu-guest-agent (qemu-ga). After  stopping qemu-ga glpi-inventory no longer 
erroneously detects a non-existing VM. However, Qemu.pm should be fixed in such a way, that it doesn't mistakes a running qemu-qa for a runnning VM.

**Comment by g-bougard** [comment]
Hi @haary 

thank you for your report.

The best way to detect qemu vm is to parse process list. So I understand stopping the qemu-ga related service fixes your problem.

Can you try to apply the following patch on the related file ?
```diff
diff --git a/lib/GLPI/Agent/Task/Inventory/Virtualization/Qemu.pm b/lib/GLPI/Agent/Task/Inventory/Virtualization/Qemu.pm
index 1cc6ee20f..47a7414ca 100644
--- a/lib/GLPI/Agent/Task/Inventory/Virtualization/Qemu.pm
+++ b/lib/GLPI/Agent/Task/Inventory/Virtualization/Qemu.pm
@@ -77,6 +77,7 @@ sub doInventory {
         # match only if an qemu instance
         next if $process->{CMD} =~ /^\[/;
         next if $process->{CMD} !~ /(qemu|kvm|qemu-kvm|qemu-system\S+) .*\S/x;
+        next if $process->{CMD} =~ /qemu-ga/x;
 
         my $values = _parseProcessList($process);
         next unless $values;
```

**Comment by haary** [comment]
Hi @g-bougard 
I applied your patch to Qemu.pm and it is working. The XML looks good and no errors from the server.
