### ISSUE TITLE
No software deployment  Error 

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi-agent#368]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Good morning,
The package is well prepared. The machine is up to date on the server.
I have the following: 
with the  fusion client: 
`No Deploy job enabled or Deploy support disabled server side.`
with  the client glpiagent : 
```
[Mon Mar 20 08:35:58 2023][info] No Collect job enabled or Collect support disabled server side.
[Mon Mar 20 08:36:02 2023][info] running task Deploy
[Mon Mar 20 08:36:03 2023][error] [http client] redirect loop detected (max_redirect = 7): 302 Found
[Mon Mar 20 08:36:03 2023][info] No Deploy job found in server jobs list.
```

Thanks

### To reproduce

-

### Expected behavior

-

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

**Comment by g-bougard** [comment]
Hi @falco2001 
I don't see any glpi-agent bug here:
```
[error] [http client] redirect loop detected (max_redirect = 7): 302 Found
```
You have a server configuration issue and the message seems clear, your http redirection is looping on itself.

**Comment by falco2001** [comment]
```
[Mon Mar 20 11:03:22 2023][info] sending prolog request to server0
[Mon Mar 20 11:03:23 2023][info] server0 answer shows it supports GLPI Agent protocol
[Mon Mar 20 11:03:23 2023][info] running task Deploy
[Mon Mar 20 11:03:23 2023][error] [http client] communication error: 400 Bad Request
[Mon Mar 20 11:03:23 2023][info] **Deploy task not supported by server0**
[Mon Mar 20 11:03:23 2023][info] running task Inventory
[Mon Mar 20 11:03:23 2023][info] New inventory from l107512.toto-2023-01-18-15-00-11 for server0
[Mon Mar 20 11:03:43 2023][info] running task Deploy: storage maintenance event
[Mon Mar 20 11:03:45 2023][info] GLPI Agent memory usage: WSS=3350528 PFU=116600832
[Mon Mar 20 11:04:54 2023][info] running task Collect
[Mon Mar 20 11:04:54 2023][info] No Collect job enabled or Collect support disabled server side.

```
what are these errors, I don’t understand anything anymore. on the test platform I am in http should I put an http-trust? Thank you

**Comment by falco2001** [comment]
```
[Mon Mar 20 11:25:31 2023][info] running task Deploy
[Mon Mar 20 11:25:31 2023][debug2] http:/serverok/plugins/glpiinventory?action=getConfig&machineid=l107512.DSI.ENS-LYON.FR-2023-01-18-15-00-11&task[Deploy]=2.10
[Mon Mar 20 11:25:31 2023][debug2] http://otherserver????/plugins/glpiinventory/b/deploy/?action=getJobs&machineid=l107512.toto-2023-01-18-15-00-11&version=2.10
[Mon Mar 20 11:25:31 2023][error] [http client] redirect loop detected (max_redirect = 7): 302 Found
[Mon Mar 20 11:25:31 2023][debug] bad JSON: No answer from server.
[Mon Mar 20 11:25:31 2023][info] No Deploy job found in server jobs list.
[Mon Mar 20 11:25:31 2023][debug] Remote inventory task execution disabled: no remote to inventory
[Mon Mar 20 11:25:31 2023][info] running task Collect
```

Help !!

**Comment by falco2001** [comment]
![image](https://user-images.githubusercontent.com/31952346/226311036-3f9252c5-6ea5-4115-83c8-6b2d6e90c5cb.png)

**Comment by falco2001** [comment]
Hello,
why the glpiagent client goes looking for:  
[Mon Mar 20 11:25:31 2023][debug2] http://otherserver????/plugins/glpiinventory/b/deploy/?action=getJobs&machineid=l107512.toto-2023-01-18-15-00-11&version=2.10
but this is ok: 
[Mon Mar 20 11:25:31 2023][debug2] http:/serverok/plugins/glpiinventory?action=getConfig&machineid=l107512.DSI.ENS-LYON.FR-2023-01-18-15-00-11&task[Deploy]=2.10

**Comment by g-bougard** [comment]
Hi @falco2001 
you should check the "Agent base URL" in the "Assets" tab of your entity. A wrong URL should have been set there. Try again by just removing it.

**Comment by falco2001** [comment]
👍  🥇
