### ISSUE TITLE
no inventories since Update 10.0.3 > 10.0.6

### ISSUE THREAD

**Issue by CGDV-Sophie** [glpi-project/glpi-agent#369]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Good morning,

I tried to update GLPI 10.0.3 to 10.0.6 and the inventory system no longer works.

I have access to the pages but when I run an inventory on the machines I have 👍 

```
[Mon Mar 20 11:04:32 2023][error] [http client] communication error: 500 Internal Server Error
[Mon Mar 20 11:04:33 2023][info] running task Deploy
[Mon Mar 20 11:04:33 2023][error] [http client] communication error: 400 Bad Request
[Mon Mar 20 11:04:33 2023][info] Deploy task not supported by server0
[Mon Mar 20 11:04:36 2023][info] running task Collect
[Mon Mar 20 11:04:36 2023][error] [http client] communication error: 400 Bad Request
[Mon Mar 20 11:04:36 2023][info] Collect task not supported by server0
[Mon Mar 20 11:04:38 2023][info] target server0: next run: Tue Mar 21 10:25:42 2023 - http://xxxxx/glpi/front/inventory.php
[Mon Mar 20 11:04:38 2023][info] GLPI Agent memory usage: WSS=3366912 PFU=159170560
```

P.S. Acces to `http://xxxx/glpi/marketplace/glpiinventory/front/menu.php` is ok
acces to `http://xxxx/glpi/front/inventory.php` send error 405
No error in error.log apache

### To reproduce

save GLPI 10.0.3 DB
save GLPI 10.0.3 rep
clean GLPI 10.0.3 rep
DL GLPI 10.0.6
unzip GLPI 10.0.6 
copy config/glpicrypt.key save to /glpi/
use php bin/console db:update

### Expected behavior

I tried to update GLPI 10.0.3 to 10.0.6 and the inventory system no longer works.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

**Comment by g-bougard** [comment]
Hi @CGDV-Sophie 
this seems not a glpi-agent issue, but a glpi server one.
Please open an issue on the [related project](https://github.com/glpi-project/glpi/issues).
Thank you

**Comment by CGDV-Sophie** [comment]
Ok, sorry
