### ISSUE TITLE
Timeout due to long wmi query to convert user SID to user name (Continuation of #360)

### ISSUE THREAD

**Issue by AndiMb** [glpi-project/glpi-agent#374]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

After rolling out the nightly build with the solution of #360, there are still time out in a lot of situations. 

Is there any chance to use the powershell command `((New-Object System.Security.Principal.SecurityIdentifier ("S-1-5-21-....")).Translate([System.Security.Principal.NTAccount])).Value` to get the username for the SID. This command seems to run very fast in comparison to the wmi query in our environment.

### To reproduce

Same a #360

### Expected behavior

Run without timeout

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

GLPI-Version: 10.0.7
GLPIInventory-Version: 1.2.1

**Comment by g-bougard** [comment]
Hi @AndiMb 

thank you for your suggestion, I'll try to implement it tomorrow.

Maybe we can't use it in older platforms, but I think we still can try it before the not sufficiently efficient one is tried.

**Comment by g-bougard** [comment]
Hi @AndiMb 

I just included your suggestion in the code. Next nightly will be built with it. It will also include a fix related to the username encoding which was wrong when taken from the GPC cache.

Tell us in this improved performance in your context and finally avoid all the timeout cases.
