### ISSUE TITLE
Install agent in opnsense or pfsense

### ISSUE THREAD

**Issue by CamiloPerezOrtiz** [glpi-project/glpi-agent#378]
### Bug reporting acknowledgment

Not applicable

### Professional support

None

### Describe the bug

Hello,
I am working on glpi version 10, it is possible to install the agent on an operating system such as opnsense or pfsense, I have followed the steps to run the agent on freebsd but I have not graded it.
I appreciate your responses.

### To reproduce

Download https://github.com/glpi-project/glpi-agent/archive/refs/tags/1.4.tar.gz
Run perl Makefile.PL
Error: Can't locate inc/Module/Install.pm in @INC (you may need to install the inc::Module::Install module) (@INC contains: /usr/local/lib/perl5/site_perl/mach/5.32 /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/mach /usr/local/lib/perl5/5.32 .) at Makefile.PL line 8.
BEGIN failed--compilation aborted at Makefile.PL line 8

### Expected behavior

Run agent

### Operating system

Other (See additional context below)

### GLPI Agent version

1.4

### GLPI version

10.0.6

**Comment by g-bougard** [comment]
Hi @CamiloPerezOrtiz 

you shouldn't use the repository archive from github as this is not the one expected from the install from source documentation.

But I see we forgot to publish the source expected by this documentation... My apologies for that missing.

To complete the process, you have to install Module::Install module with the following command as this is done is our [Windows test](https://github.com/glpi-project/glpi-agent/blob/3c8816ae2ae2c041d1e9935888fcb85c3fe45349/.github/workflows/glpi-agent-ci.yml#L83) and [MacOSX test](https://github.com/glpi-project/glpi-agent/blob/3c8816ae2ae2c041d1e9935888fcb85c3fe45349/.github/workflows/glpi-agent-ci.yml#L138) GH Actions workflows:
```
cpan -T Module::Install
```
Of course, this means you need to have cpan installed ;-)

I'll check the doc and will probably include the requested archive for the next release.

You can eventually prepare the expected archive by running `make dist` from sources installed on another distro like linux where every dependencies can be easily installed by packages.

**Comment by CamiloPerezOrtiz** [comment]
@g-bougard Thanks for the help, the agent can now run, if I needed to install that module. Thank you.
