### ISSUE TITLE
Security policy

### ISSUE THREAD

**Issue by Alemmi** [glpi-project/glpi-agent#380]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Because we've not found any security policy about glpi-agent we've followed the one of glpi: We have opened an issue on [huntr](https://huntr.dev/bounties/f40f799e-f5a5-4291-8646-8ea65dc8bd65/) (it's obv private).

Thanks in advance.

Reported by @Alemmi @u238

### To reproduce

See on [huntr](https://huntr.dev/bounties/f40f799e-f5a5-4291-8646-8ea65dc8bd65/)

### Expected behavior

See on [huntr](https://huntr.dev/bounties/f40f799e-f5a5-4291-8646-8ea65dc8bd65/)

### Operating system

Windows, Linux, MacOSX, Other (See additional context below)

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

**Comment by g-bougard** [comment]
Hi @Alemmi 

thank for your report, I'll take time to investigate.

**Comment by g-bougard** [comment]
Hi @Alemmi 
just added the SECURITY.md file to the repository.
Again, big thank you for your report and your work.
