### ISSUE TITLE
Wrong counter for Kyocera Printer

### ISSUE THREAD

**Issue by efgiese** [glpi-project/glpi-agent#382]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.7

### Bug description

The counter for total_pages in glpi_printerlogs is wrong for Kyocera Printers. For those printers (e.g. TASKalfa 356ci, TASKalfa 3253ci, ECOSYS P3155dn, ECOSYS M3145idn) the counter for total_pages should be the addition of:

'.1.3.6.1.4.1.1347.42.2.5.1.1.1.1' (duplex 1-side) and
'.1.3.6.1.4.1.1347.42.2.5.1.1.2.1' (duplex 2-side)

That works for all those printers to show the write total_pages like it is shown on the status page of the printer.

### Relevant log output

```shell
none
```

### Steps To reproduce

Compare the counters in glpi with the counters on the status page.

**Comment by trasher** [comment]
Looks like an agent issue; I transfer

**Comment by g-bougard** [comment]
Hi @efgiese 
can you share the inventory part reporting the printer counters ? And at the same time can you get the content of the OID you're talking about. You can use [glpi-netinventory](https://glpi-agent.readthedocs.io/en/latest/man/glpi-netinventory.html) script to request the inventory at any time. And then point us what is wrong in the counters inventory part ?

**Comment by efgiese** [comment]
This is ECOSYS P3155dn
![grafik](https://user-images.githubusercontent.com/43266079/233600478-f7783c00-d478-48e3-8437-7a6a5c4fa849.png)
![grafik](https://user-images.githubusercontent.com/43266079/233601836-2c40f01e-1d58-4738-82c7-4f43c873827b.png)

[192.168.200.37.walk.txt](https://github.com/glpi-project/glpi-agent/files/11294361/192.168.200.37.walk.txt)

This is TASKalfa 3253ci
![grafik](https://user-images.githubusercontent.com/43266079/233601470-8da950a0-9f73-4a83-a4e7-b7b566a6c816.png)
![grafik](https://user-images.githubusercontent.com/43266079/233601923-0568bb19-5cdd-4a26-9a90-f5662513eb2b.png)

[192.168.200.40.walk.txt](https://github.com/glpi-project/glpi-agent/files/11294370/192.168.200.40.walk.txt)

The counters in the inventory differ from those in the screenshot.

**Comment by efgiese** [comment]
This is  TASKalfa 356ci
![grafik](https://user-images.githubusercontent.com/43266079/233603207-047139a3-dd75-4552-b5ac-9da314234569.png)
![grafik](https://user-images.githubusercontent.com/43266079/233603341-02f7641e-6d3f-4410-b93b-84efd2c232cf.png)

[192.168.200.51.walk.txt](https://github.com/glpi-project/glpi-agent/files/11294431/192.168.200.51.walk.txt)

**Comment by g-bougard** [comment]
Hi @efgiese 
I can see there are differences between your screenshots and the XML files you wrongly named with ".walk.txt" extension, ".xml" would have been more appropriate.
So now I really need SNMP walk and the related screenshot to be able to use the right OIDs. You can follow that documentation to produce SNMP walk: https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output
Also do you think you can change the printer language to english just the time to take screenshots ?

**Comment by efgiese** [comment]
Hi @g-bougard,
this is TASKalfa 3253ci...
![grafik](https://user-images.githubusercontent.com/43266079/233930914-5843eccc-7c0e-4768-a662-57cefbd6787c.png)
![grafik](https://user-images.githubusercontent.com/43266079/233931038-e903c2f1-7d4e-4a09-9831-8f2f1cb8b90f.png)
[walk-gyger.walk.txt](https://github.com/glpi-project/glpi-agent/files/11307895/walk-gyger.walk.txt)

**Comment by efgiese** [comment]
This is ECOSYS P3155dn

![grafik](https://user-images.githubusercontent.com/43266079/233932323-170ec04a-d43d-4d87-8d5a-e6e47f9c7cab.png)
![grafik](https://user-images.githubusercontent.com/43266079/233932476-61725e5c-01ac-4d7f-98ee-6b4d3ed3edb9.png)
[walk-albers.walk.txt](https://github.com/glpi-project/glpi-agent/files/11307927/walk-albers.walk.txt)

**Comment by efgiese** [comment]
This is TASKalfa 356ci

![grafik](https://user-images.githubusercontent.com/43266079/233932878-ab356136-1b60-46d2-9692-ac7888b28020.png)
![grafik](https://user-images.githubusercontent.com/43266079/233933111-478ceed8-1629-4c98-8297-937a7c06e41e.png)
[walk-dali.walk.txt](https://github.com/glpi-project/glpi-agent/files/11307958/walk-dali.walk.txt)

You can not use the .1.3.6.1.4.1.1347.42.2.5.1.1.3.1 because of the 
<html><body>


Combine (None) | 22182
-- | --
  |  
Combine (2in1) | 42
  |  
Combine (4in1) | 0


</body>
</html>
Hope this helps...

**Comment by efgiese** [comment]
This is ECOSYS M3145idn

![grafik](https://user-images.githubusercontent.com/43266079/233934415-dd57e4c5-b6d1-4b30-a0f1-4225ca853497.png)
![grafik](https://user-images.githubusercontent.com/43266079/233934490-b9c0e69d-d147-4070-b435-c6954e277f1d.png)
[walk-max.walk.txt](https://github.com/glpi-project/glpi-agent/files/11308013/walk-max.walk.txt)

**Comment by g-bougard** [comment]
Okay, found a typo in an old commit related to fusioninventory/fusioninventory-agent#638
The TOTAL counter should have been get from:`.1.3.6.1.4.1.1347.43.10.1.1.12.1.1` and not from `.1.3.6.1.4.1.1347.42.10.1.1.12.1.1`

**Comment by g-bougard** [comment]
Hi @efgiese 
can you validate the fix using the [lastest nightly build](https://nightly.glpi-project.org/glpi-agent/) ?

**Comment by efgiese** [comment]
Hi @g-bougard
i think it does its job...
