### ISSUE TITLE
Install script doesn't work on Oracle Linux 7.9

### ISSUE THREAD

**Issue by Tualua** [glpi-project/glpi-agent#386]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Hello! 
Install script doesn't work on Oracle Linux 7.9 installation. Tried on 2 similar hosts

    ./glpi-agent-1.4-linux-installer.pl --server=https://glpi.domain.tld/front/inventory.php
    Installing glpi-agent v1.4...
    Installing EPEL 7 repository...
    sh: dnf: command not found
    Can't install EPEL 7 repository:

Oracle Linux 7 is the same as CentOS 7 so it uses yum, not dnf.

The only way to install is to force the script to Centos 7 distro

    ./glpi-agent-1.4-linux-installer.pl --server=https://glpi.domain.tld/front/inventory.php --force --distro centos7
    Installing EPEL 7 repository...
    Applying configuration...
    Enabling glpi-agent service...

### To reproduce

1. Install Oracle Linux 7
2. Try to install glpi-agent with script

### Expected behavior

glpi agent is installed

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

Not applicable

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

**Comment by g-bougard** [comment]
Hi @Tualua 
thank you for your detailed report. As you found the workaround using the `--distro` option is working, I'll patch the installer for next nightly to use yum if Oracle Linux version is lower than 8.
