### ISSUE TITLE
VirusTotal flags nightly builds with "Malware-Cryptor.Inject.gen"

### ISSUE THREAD

**Issue by C-Duv** [glpi-project/glpi-agent#388]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

[VirusTotal](https://www.virustotal.com) thinks there is a "Malware-Cryptor.Inject.gen" malware in the nightly builds (tested on `1.5-git6b8b966f`).

### To reproduce

1. Go to [GLPI-Agent Nightly Builds](https://nightly.glpi-project.org/glpi-agent/) webpage
2. Download any Windows asset of the [`git6b8b966f` build](https://nightly.glpi-project.org/glpi-agent/#glpi-agent-v15-git6b8b966f-nightly-build) (say [`GLPI-Agent-1.5-git6b8b966f-x64.msi`](https://nightly.glpi-project.org/glpi-agent/GLPI-Agent-1.5-git6b8b966f-x64.msi))
3. Go to [VirusTotal's upload form](https://www.virustotal.com/gui/home/upload)
4. Submit the `GLPI-Agent-1.5-git6b8b966f-x64.msi` file
5. Wait for analysis to complete

### Expected behavior

VirusTotal should not detect a virus.

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Not applicable

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

### Additional context

It looks like it only concerns Windows builds:

* [`GLPI-Agent-1.5-git6b8b966f-x64.msi`](https://www.virustotal.com/gui/file/76fcbb2e864a613c04b55830a0a5cb8522d159fc2cf421af88876a075a59d7a2)
* [`GLPI-Agent-1.5-git6b8b966f-x86.msi`](https://www.virustotal.com/gui/file/1d2af25ea2e0d9e9551fff42305cc8e083d267ce9c8cb9ca380bf98f8a1203fa)
* [`glpi-agent-1.5-git6b8b966f-x64.zip`](https://www.virustotal.com/gui/file/13b7dee9ede90564e4c6cd741b07e603502d61c2c27552dbc743241001535e6d)
* [`glpi-agent-1.5-git6b8b966f-x86.zip`](https://www.virustotal.com/gui/file/03688c3491c91c9b54f68b567b883ff091eff695358543c1a4d23e853c218440)

Other platform and stable Windows releases (v1.4.x) looks OK.

* [`GLPI-Agent-1.5-git6b8b966f.tar.gz`](https://www.virustotal.com/gui/file/7b6fbb163f97860dd95ad97eab3b8b4be372c9caf688e04d2c7c59d2e4166200)
* [`glpi-agent_1.5-git6b8b966f_all.deb`](https://www.virustotal.com/gui/file/505a269e22c71b0715546f6f7196356ad3013132518262e3886cc992d26a1b82)
* [`GLPI-Agent-1.5-git6b8b966f_x86_64.pkg`](https://www.virustotal.com/gui/file/35ece5e28c3459f1aa736bcc364753bbb1600cf8d89f2a23b7090c2053684e58)
* [`GLPI-Agent-1.5-git6b8b966f_arm64.pkg`](https://www.virustotal.com/gui/file/e0875a6858668c87b45298fd85aa35f71373075d72064303a3bf3e17214d8850)
* [`GLPI-Agent-1.4-x64.msi`](https://www.virustotal.com/gui/file/95c3e417bf7fcc7674b033c1abb89e108f7677bc01a2628ec5a00a6bc289a7e5)
* [`GLPI-Agent-1.4-x86.msi`](https://www.virustotal.com/gui/file/987c4874eae6291d9adcf50b70509b57fa5df2c205624b1cf0975f8a3e59c02e)
* [`glpi-agent-1.4-x64.zip`](https://www.virustotal.com/gui/file/d7139a84e413db6d6345b577f12238ac8da9d6278b669bf057af1a83fe25134d)
* [`glpi-agent-1.4-x86.zip`](https://www.virustotal.com/gui/file/7e2b542c30c61689ba607dc73c0ffa55e8f6310b92dbc21c6d2a2acaba780bb7)

**Comment by g-bougard** [comment]
Hi @C-Duv 

thank you for the report.

It seems provided `dmidecode.exe` is the file flagged as malware in one security vendors' analysis:
https://www.virustotal.com/gui/file/76fcbb2e864a613c04b55830a0a5cb8522d159fc2cf421af88876a075a59d7a2/relations

That exe has been rebuilt from source more that an month ago and here its release source:
https://github.com/glpi-project/dmidecode/releases/tag/3.5

Of course, this is definitively a false positive. That poor VBA32 test is working with white lists and will flag new exe by default as suspect with cryptic signature.

I'll alert VirusTotal on that problem.

**Comment by C-Duv** [comment]
Thanks for the response: let me know how it goes with VirusTotal.

**Comment by g-bougard** [comment]
Hi @C-Duv 
of course, I'm keeping this issue opened until the problem is fixed so you'll be informed and I'll update it when I'll obtain an answer.

**Comment by g-bougard** [comment]
I got an answer: they are investigating.

**Comment by g-bougard** [comment]
Hi @C-Duv 

last week, I updated dmidecode build so it is signed by our (even expired) certificate. I submitted the signed one to VBA32 as it was also detected as malicious by them. They quickly answered me this is a false positive and they will update their whitelist.

I included this dmidecode signed version in the nightly package. Now, the MSI seems okay... but not the portable versions provided as zip. And this is still a VBA32 issue. I think they still not have updated their whitelist and simply providing the signed version in MSI did the trick.

Also I updated the build workflow so it waits for a full analysis report from VT and add a warning on the build page like you'll see on:
https://github.com/glpi-project/glpi-agent/actions/runs/4964537058

**Comment by C-Duv** [comment]
It is now indeed OK for 6b8b966f and 66f3eacc :

* [`GLPI-Agent-1.5-git6b8b966f-x64.msi` (2023-04-29)](https://www.virustotal.com/gui/file/76fcbb2e864a613c04b55830a0a5cb8522d159fc2cf421af88876a075a59d7a2)
* [`GLPI-Agent-1.5-git66f3eacc-x64.msi` (2023-05-04)](https://www.virustotal.com/gui/file/78ce5270efd2c583f6569862f0d0ab6be5f5fe7e22d2a962f9d795ed066a06ec)

But re-started to fail since 786514bf (2023-05-05):

* [`GLPI-Agent-1.5-git786514bf-x64.msi` (2023-05-05)](https://www.virustotal.com/gui/file/b05f79a43135b9e975b2ab1e35b9056ec86637f1d83963308d93c5633c62d368) : _VBA32 "Malware-Cryptor.Inject.gen"_
* [`GLPI-Agent-1.5-git5bca4886-x64.msi` (2023-05-06)](https://www.virustotal.com/gui/file/2db9fc9722c4f8147ebf527d224a9a09003f4a12d475609d24c85b61bdd3a75c) : _VBA32 "Malware-Cryptor.Inject.gen"_
* [`GLPI-Agent-1.5-git29805a48-x64.msi` (2023-05-10)](https://www.virustotal.com/gui/file/0fca56eeb33b05fb45bee67e1c7d209e1378ca66c28124a8f3b85cd0422620c4) : _VBA32 "Malware-Cryptor.Inject.gen"_
* [`GLPI-Agent-1.5-git107745ba-x64.msi` (2023-05-11)](https://www.virustotal.com/gui/file/4c3913de8e1429a6f699b14301e2fbe97d2c2a0be2bffdd738dc24ca9cb12471) : _VBA32 "Malware-Cryptor.Inject.gen"_
* [`GLPI-Agent-1.5-git283f86bf-x64.msi` (2023-05-16)](https://www.virustotal.com/gui/file/202556dea6833259e27061ffdaa9c184448c8684d0f432fcb7bcdf8e5ba33f0a) : _Kingsoft "Script.Ks.Malware.17553"_

I am not sure what you can do but I wanted to let you know.

(For the context: I am building a Chocolatey package for nightly so each build will be scanned through VirusTotal during Chocolatey's moderation process)

**Comment by g-bougard** [comment]
Hi @C-Duv 
VirusTotal can become a nightmare sometime. About VBA32, this will become even more a problem if we need to submit each nightly... I still hope this will be less a problem when we will have our new EV code-signing certificate. The current one expired few months ago.
For the latest problem with Kingsoft, I still reported it to VirusTotal as the false-positive submission email from KingSoft is in error and the editor behind seems have disappeared... I think they are investigating.

**Comment by g-bougard** [comment]
For last nightly, I restarted all analysis. KingSoft issue does no more appear, so all packages are green, but it seems there are some timeout with few backends...

**Comment by g-bougard** [comment]
I also re-analysed older nightlies: they are now "Undetected" against VBA32 and everything is green.

**Comment by C-Duv** [comment]
I have almost finished [my 3 Chocolatey packages](https://community.chocolatey.org/packages?q=glpi-agent-nightly): 2 are still pending but the main one (with the MSI) is OK on Chocolatey side.

I am closing this issue. I could comment again if the issue re-occurs (but shouldn't since you added VirusTotal check on you pipelines).
