### ISSUE TITLE
Incorrect agent version is reported

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi-agent#39]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

After installing agent 1.0.0 and going to computer: port still shows: This is GLPI Agent 1.0-beta1

### To reproduce

1. Clean installation of the latest agent (there was no beta on the computer)
2. Go to https://computer:port
3. Check agent version

### Expected behavior

I would like to see version 1.0.0 here - then I know that when updating on stations where I had a beta version, the agent is actually in the latest version.

### Operating system

Windows

### GLPI Agent version

1.0

### GLPI version

9.5.6

### Additional context

It is not critical, but it would be nice if it displayed correctly - such a cosmetic change :)

Second thing I noticed - after installation and 'Force an Inventory' I did not find info about installation on Assets > Computers > computername > History tab. But I see GLPI-Agent on Software tab.

**Comment by g-bougard** [comment]
Hi @WebGregGit 
there was some lately changes in the windows packaging between 1.0-beta1 and the 1.0 release. Check your system applications, maybe you have finally a double install. Anyway you should uninstall any GLPI-Agent and make a clean install of GLPI-Agent 1.0, maybe after a reboot if you had a double install.

**Comment by WebGregGit** [comment]
I used https://github.com/glpi-project/glpi-agent/releases/download/1.0/GLPI-Agent-1.0-x64.msi  - clean install. I also cleared browser cache.

But.... Nightly build and:  This is GLPI Agent 1.1-git5f68e75e :)
