### ISSUE TITLE
libcrypt.so.1 is missing [solved] [missing documentation]

### ISSUE THREAD

**Issue by MarcSamD** [glpi-project/glpi-agent#391]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

On default Amazon Linux 2023 AMI, we cannot install glpi-agent with Linux AppImage Installer, as we receive the following error message:
```
[ec2-user@hostname tmp]$ sudo ./glpi-agent-1.5-git5bca4886-x86_64.AppImage  --install --server <URL>
/tmp/.mount_glpi-aBcGOW2/usr/bin/perl: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
```

### To reproduce

1. Launch a standard Amazon Linux 2023 AMI and download GLPI Agent AppImage
2. chmod +x glpi-agent-1.5-git5bca4886-x86_64.AppImage
3. sudo ./glpi-agent-1.5-git5bca4886-x86_64.AppImage --install --server <URL>

### Expected behavior

Update [the procedure](https://glpi-agent.readthedocs.io/en/latest/installation/linux-appimage.html) to explain that on Amazon Linux 2023 (not tested on Amazon Linux 2), we need to install libxcrypt-compat first:
`[ec2-user@hostname tmp]$ sudo yum install libxcrypt-compat`

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.x (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

glpi-agent-1.5-git5bca4886-x86_64.AppImage

**Comment by g-bougard** [comment]
Hi @MarcSamD 
thank you for your report.
You fixed your problem by locally install a package, but to me the library should be included in the archive. And indeed the library seems to be included but not resolved. So I think there can an AppImage packaging issue there I need to investigate.

**Comment by g-bougard** [comment]
Checking deeper the documentation and the code of [appimage-builder](https://github.com/AppImageCrafters/appimage-builder), it appears embedded libcrypt.so.1 will only be used if system libc is older than the one from the AppImage package. So you're right libcrypt.so.1 must be provided by the OS.

So right now, I'll follow your though to update the documentation and alert people they may need to install a compatibility package.
