### ISSUE TITLE
Netinventory getting Virtual Device instead Computer

### ISSUE THREAD

**Issue by ThalesArakawa** [glpi-project/glpi-agent#396]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Net-inventory task or command,  in some ports, create a link between port to virtual device instead with computer(what i want). The virtual device is a Cisco Software and this device is together with CDP XML tag in glpi-netinventory walk file.

### To reproduce

1. Cisco Switch with CDP active
2. Computers with Cisco Communicator connected in this switch
3. Run glpi-netinventory

### Expected behavior

After net-inventory, in GLPI > Assets > Network Devices, i expected to see - inside of an network equipment - all the link's between switchs and computers.

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPIInventory 1.2.1 (recent update)

### Additional context

I'm trying disable the CDP look by agent, but i didn't find how to do.

**Comment by g-bougard** [comment]
Hello @ThalesArakawa 
can you share the XML from the Cisco switch and a partial inventory of a computer which should be connected as expected ? To make the inventory, you can open an administrative console, cd to the GLPI-Agent folder and run:
```
glpi-inventory --partial network
```
You can share the resulting output or redirect the output in a file and share the file. You can obfuscate any sensible data in that output.
For the switch XML, if you can identify which port in the XML to which the selected computer should be linked, you can share only that specific XML node: this should be sufficient to understand the problem.

**Comment by ThalesArakawa** [comment]
![netInventExitExample](https://github.com/glpi-project/glpi-agent/assets/65679861/903597f6-8b6c-468d-ab2e-af84cb1d726b)
![sourceCorrectLink](https://github.com/glpi-project/glpi-agent/assets/65679861/929527ea-1a43-4761-9c21-1c61d9c09611)
![sourceWrongLink](https://github.com/glpi-project/glpi-agent/assets/65679861/0f024e28-9d8c-4a7a-813a-a4fcb61674d5)

If the netinventory is realized with virtual device closed the link its create correctly, but if this device is running this CDP tag appear.
The result of glpi-inventory --partial network when the virtual device is closed or running is the same.

**Comment by g-bougard** [comment]
Hi @ThalesArakawa 
it seems to me you shared the output of `C:\Program Files\GLPI-Agent>glpi-inventory.bat --partial storage` as I see storages node and no networks node. Can you replace `storage` by `network` as this is what I indeed requested ?
The 2 XMLs node from the switch inventory are showing 2 different ports: Gi1/0/42 & gi1/0/43. On which port the computer interface is connected ?

About obfuscating, I would prefer to have text where you replace values with faked but coherent ones. So I can try to copy them in another switch XML for testing.

**Comment by ThalesArakawa** [comment]
my bad for storage info... now is the request from network. I made in another computer wich the network link in glpi is ok and the exit is the same. Only the identifiers change.

I see in another post you telling about CDP table, and i need this protocol active in my switches. Maybe the problem? When i make snmpwalk for mac and CDP, the result is ok...

About the XML print, the interface is connected in port 43... Both computers have same function and same programs, but the link created by GLPI does not have expected behavior.

**Comment by ThalesArakawa** [comment]
[glpi-netinventoryPort8.txt](https://github.com/glpi-project/glpi-agent/files/11533825/glpi-netinventoryPort8.txt)
[glpi-agentbatNetworkPort8.txt](https://github.com/glpi-project/glpi-agent/files/11533826/glpi-agentbatNetworkPort8.txt)

**Comment by g-bougard** [comment]
Hi @ThalesArakawa 

can you try to apply the following patch to the agent who runs netinventory tasks ?
```patch
diff --git a/lib/GLPI/Agent/Tools/Hardware.pm b/lib/GLPI/Agent/Tools/Hardware.pm
--- a/lib/GLPI/Agent/Tools/Hardware.pm
+++ b/lib/GLPI/Agent/Tools/Hardware.pm
@@ -1057,6 +1057,9 @@ sub _setConnectedDevices {
             my $lldp_connection = $port->{CONNECTIONS}->{CONNECTION};
             my $cdp_connection  = $cdp_info->{$interface_id};
 
+            # Skip CDP entry if MODEL shows this is a computer with Cisco Communicator installed
+            next if $cdp_connection->{MODEL} && $cdp_connection->{MODEL} =~ /^Communicator/i;
+
             if ($lldp_connection) {
                 my $match = 0;
 
```
The purpose of the patch is to skip CDP info insertion is MODEL starts with "Communicator" string.

**Comment by ThalesArakawa** [comment]
This line fix the glpi-netinventory result, but in front the virtual device is still linked with switch port. 

There's any difference between this cmdlet and the NetInventory Task?

![image](https://github.com/glpi-project/glpi-agent/assets/65679861/c9f5647d-7341-4e79-9b74-fa71c6096818)

**Comment by ThalesArakawa** [comment]
After restart GLPI-Agent service, the objective is accomplished!!! THANKS @g-bougard.
