### ISSUE TITLE
[http client] internal response: 500 Can't connect to inventory.mydomain.hu:443

### ISSUE THREAD

**Issue by reveszKrisztian** [glpi-project/glpi-agent#397]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

GLPI-Agent 1.4 could not communicate with inventory even though No SSL Check is enabled.

`sudo glpi-agent`
`[info] target server0: server https://inventory.mydomain.hu/front/inventory.php`
`[info] sending prolog request to server0`
`[error] [http client] internal response: 500 Can't connect to inventory.mydomain.hu:443, SSL connect attempt failed error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure`
`[error] No answer from server at https://inventory.mydomain.hu/front/inventory.php`

GLPI config:
`cat /etc/glpi-agent/conf.d/00-install.cfg`
`no-ssl-check = 1`
`server = https://inventory.mydomain.hu/front/inventory.php`
`tag = company`

### To reproduce

Ran glpi-agent with "--no-ssl-check" & server specified in the command

### Expected behavior

Agent should be able to communicate with inventory because SSL check is disabled. Same command works on Linux servers.

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.5

**Comment by g-bougard** [comment]
Hi @reveszKrisztian 

your problem is probably due to an issue with the SSL stack on your OS, maybe between what expect the server and your OS capabilities. For example, maybe your system can only use SSLv3 but your server is configured to not accept it.

First, you'll have more information if you enable debug=2 in conf.

Then what is your linux OS and version ? You may also check ssl version on the client and on the server. What happens if you try to download the GLPI page with curl like this: `curl -k https://inventory.mydomain.hu/front/inventory.php >server.html`

As a note, you should upgrade your GLPI version as the current one is 10.0.7 and it fixes some important issues. But this is not related to your issue.

**Comment by reveszKrisztian** [comment]
Hi @g-bougard 

Thanks for your reply!

This current machine uses Ubuntu 16.04. I know it's quite old, but it is necessary for some reason.

Do I have to worry about SSLv? This is why I wanted to use --no-ssl-check, to do not take care about SSL. It works on other Linux and Windows based clients and servers.

This is what I got with debug:

```
sudo glpi-agent
[debug] Logger backend Stderr initialized
[debug] GLPI Agent (1.4-1)
[debug] Configuration directory: /etc/glpi-agent
[debug] Data directory: /usr/share/glpi-agent
[debug] Storage directory: /var/lib/glpi-agent
[debug] Lib directory: /usr/share/glpi-agent/lib
[debug] [target server0] Next server contact planned for Tue May 23 09:10:35 2023
[debug2] getAvailableTasks() : add of task Inventory version 1.12
[debug2] getAvailableTasks() : add of task RemoteInventory version 1.0
[debug2] getAvailableTasks() : add of task WakeOnLan version 2.2
[debug] Available tasks:
[debug] - Inventory: 1.12
[debug] - RemoteInventory: 1.0
[debug] - WakeOnLan: 2.2
[debug] target server0: server https://inventory.mydomain.hu/front/inventory.php
[debug] Planned tasks for server0: Inventory,WakeOnLan,RemoteInventory
[debug] Built by Debian
[debug] Source time: 2022-07-01 09:21
[debug] Running in foreground mode
[info] target server0: server https://inventory.mydomain.hu/front/inventory.php
[debug] [http client] Using Compress::Zlib for compression
[info] sending prolog request to server0
[debug2] [http client] sending message:
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <DEVICEID>OP3-177B-2023-05-22-14-07-30</DEVICEID>
  <QUERY>PROLOG</QUERY>
  <TOKEN>12345678</TOKEN>
</REQUEST>
[error] [http client] internal response: 500 Can't connect to inventory.mydomain.hu:443, SSL connect attempt failed error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
[error] No answer from server at https://inventory.mydomain.hu/front/inventory.php
```

By the way the server uses SSLv3 while the client is a brand new installation of Ubuntu 16.04, no SSL configurations.

With curl I receive an empty file (Replaced with correct URL):
```
curl -k https://inventory.mydomain.hu/front/inventory.php > server.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```

**Comment by reveszKrisztian** [comment]
**PROBLEM SOLVED**

I have reinstalled glpi-agent with snap and it works now. I'm not shure why, so I post here what have I done, and maybe somebody will find this helpful.

First try: (Not working on this machine, but works everywhere else)

```
wget https://github.com/glpi-project/glpi-agent/releases/download/1.4/glpi-agent-1.4-linux-installer.pl
chmod +x glpi-agent-1.4-linux-installer.pl 
./glpi-agent-1.4-linux-installer.pl --server=https://inventory.mydomain.hu/front/inventory.php --no-ssl-check --runnow --tag=company

```

Working solution with Snap:

```
sudo wget https://github.com/glpi-project/glpi-agent/releases/download/1.4/glpi-agent_1.4_amd64.snap
sudo snap install --classic --dangerous glpi-agent_1.4_amd64.snap
sudo snap set glpi-agent server=https://inventory.mydomain.hu/front/inventory.php
sudo snap set glpi-agent tag=company
sudo snap set glpi-agent no-ssl-check=1
```
