### ISSUE TITLE
[Windows] Command line with ADDLOCAL option don't copy glpi-agent.exe

### ISSUE THREAD

**Issue by TheRoby** [glpi-project/glpi-agent#40]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Hi,

with ADDLOCAL option, the msi don't copy the glpi-agent.exe file here : C:\Program Files\GLPI-Agent\perl\bin

### To reproduce

1. msiexec /i "F:\GLPI-Agent-1.0-x64.msi" /quiet RUNNOW=1 SERVER='https://test.fr/' ADD_FIREWALL_EXCEPTION=1 ADDLOCAL=feat_DEPLOY,feat_COLLECT HTTPD_TRUST=0.0.0.0/0
Missing the glpi-agent.exe
2. msiexec /i "F:\GLPI-Agent-1.0-x64.msi" /quiet RUNNOW=1 SERVER='https://test.fr/' ADD_FIREWALL_EXCEPTION=1 HTTPD_TRUST=0.0.0.0/0
the glpi-agent.exe is here ... :)

### Expected behavior

the first command line need to copy glpi-agent.exe :)

Thank you :)

### Operating system

Windows

### GLPI Agent version

1.0

### GLPI version

Not applicable

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

**Comment by g-bougard** [comment]
Hi @TheRoby 
thank you for your issue, I'll make some tests to reproduce it.

**Comment by g-bougard** [comment]
Hi @TheRoby 
can you try next nightly to valid this problem is gone ?
I would like also to thank you as this issue finally helped me to also fixed 2 other problems linked to logfile, vardir and installdir paths ;-)

**Comment by TheRoby** [comment]
Hi @g-bougard !
Sorry for the delay ...
I tested with the 1.1 and it's ok :)

Thank you !
