### ISSUE TITLE
MSSQL instance name error

### ISSUE THREAD

**Issue by bacus99** [glpi-project/glpi-agent#409]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

GLPI 10.0.7 and glpi-agent 1.4, GLPI Inventory 1.2

When I receive glpi-agent inventory, my instance name is always "SQL Server 20XX"  (xx for the MSSQL Version)
If I rename the instance name, for MSSQLSERVER for exemple, it create a new instance

Is it possible to set the name properly?

In the same category, it is not importing multiple instances in GLPI

### To reproduce

install GLPI-agent on a MSSQL server and run the inventory

Check instance in GLPI

### Expected behavior

Should be the instance name or servername\instancename

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.x (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.0.x (See additional context below)

**Comment by bacus99** [comment]
Works for a single instance if I change MSSQL.pm
Line 60 to 76
```
        my $productversion = _runSql(
            sql     => "SELECT SERVERPROPERTY('productversion')",
            %params
        )
            or next;

        my $instance =_runSql(
            sql     => "SELECT \@\@servicename",
            %params
        )

            or next;

        my $version =_runSql(
            sql     => "SELECT \@\@version",
            %params
        )
```
and line 94
```
            name            => $instance,
```
![image](https://github.com/glpi-project/glpi-agent/assets/11425241/fce169c9-2bf6-48fd-997f-f5bab3f12c46)

**Comment by g-bougard** [comment]
Hi @bacus99 

thank you for your contribution.

An adaptation of your fix will be available in next nightly build.
