### ISSUE TITLE
Wrong monitor serial number

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi-agent#41]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

If I use Powershell, I get a serial number for example: 123007

By checking the resulting html of the agent, I can see: 0001e34f

Powershell code:

```

ForEach ($Monitor in Get-WmiObject WmiMonitorID -Namespace root\wmi) {  
    $Name = Decode $Monitor.UserFriendlyName -notmatch 0
    $Serial = Decode $Monitor.SerialNumberID -notmatch 0

    echo "$Name, $Serial"
}

```

### To reproduce

Impossible to reproduce without a monitor with a specific serial number

### Expected behavior

The agent should not change the serial number.

### Operating system

Windows

### GLPI Agent version

1.0

### GLPI version

9.5.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Older (See additional context below)

### Additional context

FusionInventory 9.5.0+1.0

The same problem was with the Fusion Inventory agent. I was hoping the GLPI did it better, but unfortunately it's the same.

**Comment by g-bougard** [comment]
Hi @WebGregGit 
Most manufacturers are using an hexadecimal number for their serialnumber and `0001e34f` is `123007` in hexadecimal.
Do you mean you have a monitor manufacturer expecting a decimal number ?
Can you eventually report the output of the following command from GLPI-Agent installation folder, maybe this can help to better understand your problem:
```
C:\Program Files\GLPI-Agent> glpi-inventory --partial=monitor
```

**Comment by WebGregGit** [comment]
Hi @g-bougard 

Thank you for your message. I will be able to check it on Monday at the earliest. 
It is for sure as you write. The point is that the number display should be standardized. If someone physically goes to check the monitor, hardly anyone will be able to calculate - it should be done by software in my opinion.

If powershell gets a decimal number, it would be nice if glpi did that as well - it's a more human-readable system :)

**Comment by g-bougard** [comment]
The problem is more what the manufacturer expects in the case you have to register it or make a RMA support. As far I know, manufacturers requests hexadecimal, but sometime they requires something else and this is why the agent is able to compute alternate serial for few manufacturers.
So let us know what serial you're seeing on the back of your monitor or on its packaging, and let us know which manufacturer is concerned. The output of `glpi-inventory --partial=monitor` will help ;-)

**Comment by WebGregGit** [comment]
Hi @g-bougard 

OK, I see it - I have to correct it manually. it doesn't matter if the record is in hexadecimal or in decimal. 
There is something completely different on the back of the monitor anyway. I don't know why LG Flatron is encoding its serial numbers this way. But it does not seem to be done by GLPI.

Thank You

**Comment by g-bougard** [comment]
Hi @WebGregGit 
if you provides the output of `glpi-inventory --partial=monitor` as I requested and the expected S/N, I may tell you if this is fixable by the agent.

**Comment by WebGregGit** [comment]
Hi @g-bougard

Back: 706NDZJ3P005
Agent: 0001e84d

**Comment by g-bougard** [comment]
Hi @WebGregGit 
again I can't investigate without the output of `glpi-inventory --partial=monitor`.

**Comment by WebGregGit** [comment]
```
[info] New inventory from PC_test.domain.com-2022-01-13-12-46-50 for local0
{
   "action": "inventory",
   "content": {
      "bios": {
         "assettag": "",
         "bdate": "2020-20-02",
         "biosserial": "CZCxxyyZV5",
         "bmanufacturer": "Hewlett-Packard",
         "bversion": "L01 v02.78",
         "enclosureserial": "CZCxxyyZV5",
         "mmodel": "1998",
         "msn": "CZCxxyyZV5",
         "smanufacturer": "Hewlett-Packard",
         "smodel": "HP EliteDesk 800 G1 SFF",
         "ssn": "CZCxxyyZV5"
      },
      "hardware": {
         "chassis_type": "Low Profile Desktop",
         "description": "PC_test",
         "memory": 8082,
         "name": "PC_test",
         "uuid": "30A6E680-1F2A-11E5-xxxx-ECB1D739F99E",
         "vmsystem": "Physical",
         "winlang": "1045",
         "winowner": "Company",
         "workgroup": "domain.com"
      },
      "monitors": [
         {
            "altserial": "3N989",
            "base64": "AP///////wAebfJKPegBAAYRAQNqIht46jIxo1dMnSURUFSla4AxT0VPYU+BgAEBAQEBAQEBMCoAmFEAKkAwcBMAUg4RAAAeAAAA/QA4Sx5TDgAKICAgICAgAAAA/ABMMTkxOVMKICAgICAgAAAA/AAgCiAgICAgICAgICAgAAE=",
            "caption": "L1919S ",
            "description": "6/2007",
            "manufacturer": "Goldstar Company Ltd",
            "serial": "0001e83d"
         }
      ],
      "versionclient": "GLPI-Inventory_v1.1-gitce8e7d74"
   },
   "deviceid": "PC_test.domain.com-2022-01-13-12-46-50",
   "itemtype": "Computer"
}
```

**Comment by g-bougard** [comment]
For this one, agent serial seems different than the one you gave 2 days ago.
What's the S/N on the monitor back for this one ?

Here I can see "3N989" as `altserial`, this means this manufacturer doesn't respect EDID standard for some other models, and this is probably the case for this one.

**Comment by WebGregGit** [comment]
Hi @g-bougard 
Yes, 2 days ago I had different monitor.  This one has 706NDKD3N989.
