### ISSUE TITLE
GLPI-Agent is not changing workstation name after it is renamed

### ISSUE THREAD

**Issue by RobertoMarcelino** [glpi-project/glpi-agent#413]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

I still have but want a public following to keep the community aware

### Describe the bug

I installed the GLPI-Agent on the workstation, which showed up in the inventory correctly.
I renamed the workstation.
The name appears correctly under Computers, but the old name remains under Agents.
I uninstalled GLPI-Agent and performed a new installation. Same thing: continues the old name in the agent.
I uninstalled GLPI-Agent and deleted the folder under C:\Program files\GLPI-Agent.
I installed it again and the name was correct.
GLPI-Agent is not changing name after renaming the workstation, because of some file remaining in C:\Program files\GLPI-Agent folder.

![image](https://github.com/glpi-project/glpi-agent/assets/57845086/682771ac-76b4-4a5a-a103-447437bd960a)

### To reproduce

N/A

### Expected behavior

N/A

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.x (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.0.6, GLPI Inventory v1.0.x (See additional context below)

### Additional context

GLPI-Agent_v1.5-git1bd80d47
GLPI 10.0.7
GLPI Inventory 1.2.1

**Comment by g-bougard** [comment]
Hi @RobertoMarcelino 
this is not a bug, but a feature. We don't consider the agent name is mandatory and must follow the computer name.
If you need to request the agent to rename the deviceid it reports to the server, you just need to remove the GLPI-Agent.dump file you'll find under `C:\Program Files\GLPI-Agent\var` folder.
