### ISSUE TITLE
Error installing agent on Windows

### ISSUE THREAD

**Issue by silvacharles** [glpi-project/glpi-agent#414]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

The application installer was executed in the x64 version on the workstation with Windows Server 2012 R2, and it generates the following alert in the screenshot below.

### To reproduce

1 - Run with right click and execute
2- Accept the terms
3- Does not advance to the next step

### Expected behavior

Proceed with application installation

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

**Comment by silvacharles** [comment]
![glpi_agent](https://github.com/glpi-project/glpi-agent/assets/16735219/86ad80ac-6372-447c-aaf7-5ec796c7f115)

**Comment by g-bougard** [comment]
Hi @silvacharles 

seems not to be a GLPI-Agent packaging issue but a system issue.

Do you know the reason why the system don't see "C:\" drive as a local hard drive ?

**Comment by g-bougard** [comment]
Closing with feedback.
Feel free to re-open or comment with your fix.
