### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by Deki60** [glpi-project/glpi-agent#42]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

Dear,

I have install the BETA GLPI 10 and the Agent 1.0

but impossible to wake up the agent remotely

I have try : 

HTTPD_TRUST='192.168.12.0/24' (lan where is install GLPI) i have try : Access denied

HTTPD_TRUST='192.168.12.5' (ip of GLPI no result)

HTTPD_TRUST='127.0.0.1/32,192.168.12.5' (OK for local wake up http://localhost:62354/now)

HTTPD_TRUST='127.0.0.1/32,192.168.12.0/24' (OK for local wake up http://localhost:62354/now , access denied http://ipofagent:62354/now ) i can just view agent status 

This is GLPI Agent 1.0
The current status is waiting

and i can't have toolbox interface

before i have complet install with fusioninventory agent and no problem to wake up agent remotly

### To reproduce

SetupOptions = "/quiet RUNNOW=1 HTTPD_TRUST='192.168.15.0/24' SERVER='https://GLPILOCALDNS/front/inventory.php' NO_TASK='' NO_SSL_CHECK=1 ADD_FIREWALL_EXCEPTION=1"

### Expected behavior

be able to wake up the agent remotely

### Operating system

Windows

### GLPI Agent version

1.0

### GLPI version

10.0.0-beta

### GLPIInventory plugin or FusionInventory for GLPI plugin version

10.0.0-rc2

**Comment by g-bougard** [comment]
Can you try the [nightly build](https://nightly.glpi-project.org/glpi-agent) as this should have been lately in december ?

**Comment by Deki60** [comment]
same problem. 
the agent does not accept any remote connection for control only trust with localhost 127.0.0.1/32 

i have try add one other computer for remote in the same lan network, same problem.

**Comment by Deki60** [comment]
another point, what is the file for

C: \ Program Files \ GLPI-Agent \ etc \ agent.cfg? this does not include the configuration applied during installation and its modification has no effect on the operation of the agent. To modify the parameters it is necessary to uninstall the agent and reinstall, where does it locate the real configuration file?

install config : SetupOptions = "/quiet RUNNOW=1 HTTPD_TRUST='192.168.15.0/24' SERVER='https://GLPILOCALDNS/front/inventory.php' NO_TASK='' NO_SSL_CHECK=1 ADD_FIREWALL_EXCEPTION=1"

and agent.cfg after install : 

```
# GLPI agent configuration

# all defined values match default
# all commented values are examples


#
# Target definition options
#

# send tasks results to a GLPI server
#server = http://server.domain.com/front/inventory.php
# send tasks results to a FusionInventory for GLPI server
#server = http://server.domain.com/glpi/plugins/fusioninventory/
# write tasks results in a directory
#local = /tmp

#
# Task definition options
#

# disable software deployment tasks
#no-task = deploy
#tasks = inventory,deploy,inventory

#
# Target scheduling options
#

# maximum delay before first target, in seconds
# Also the maximum delay on network error. Delay on network error starts
# from 60, is doubled at each new failed attempt until reaching delaytime.
delaytime = 3600
# do not contact the target before next scheduled time
lazy = 0

#
# Inventory task specific options
#

# do not list local printers
# no-category = printer
# allow to scan user home directories
scan-homedirs = 0
# allow to scan user profiles
scan-profiles = 0
# save the inventory as HTML
html = 0
# set to 1 to save local inventory as JSON
json = 0
# timeout for inventory modules execution
backend-collect-timeout = 180
# always send data to server
force = 0
# additional inventory content file
additional-content =

#
# Package deployment task specific options
#

# do not use peer to peer to download files
no-p2p = 0

#
# Network options
#

# proxy address
proxy =
# user name for server authentication
user =
# password for server authentication
password =
# CA certificates directory
ca-cert-dir =
# CA certificates file
ca-cert-file =
# do not check server SSL certificate
no-ssl-check = 0
# connection timeout, in seconds
timeout = 180

#
# Web interface options
#

# disable embedded web server
no-httpd = 0
# network interface to listen to
httpd-ip = 
# network port to listen to
httpd-port = 62354
# trust requests without authentication token
httpd-trust= 

#
# Logging options
#

# Logger backend, either Stderr, File or Syslog (Stderr)
logger = stderr
# log file
#logfile = /var/log/glpi-agent.log
# maximum log file size, in MB
#logfile-maxsize = 0
# Syslog facility
logfacility = LOG_USER
# Use color in the console
color = 0

#
# Execution mode options
#

# add given tag to inventory results
tag = 
# debug mode
debug = 0

# time to wait to reload config (0 means no reload, it's default value)
# conf-reload-interval = 0

# Since 2.4, you can include all .cfg files from a folder or any given file
# For example:
#   1. file "conf.d/tag.cfg" contains "tag = 'entity123'"
#      using "include 'conf.d' will set tag to 'entity123'
#   2. file "/etc/production/glpi-tag" contains "tag = 'entity123'"
#      using "include '/etc/production/glpi-tag' will set tag to 'entity123'
# Remark:
#   1. Prefer to use full path to avoid confusion, but be aware relative paths are
#      relative against current config file folder
#   2. A parameter set in included file can be over-rided if set again after the directive
#   3. *.cfg files are read in order in folder, it's better to prefix them with a number
#   4. Package maintainers are encouraged to use this feature to avoid conflict
#      during upgrades after configuration update
#
include "conf.d/"
#include "agent.local"
include 'conf.d/'
```

**Comment by g-bougard** [comment]
Hi @Deki60 
By default, under win32 platform, the agent configuration is setup into registry under `HK_LM\Software\GLPI-Agent` key. So to change the configuration, you can change it in registry and restart the service. You don't need to reinstall it.
The default `agent.cfg` configuration file is kept in the case you run manually or via planified task using the `--config-file` option. This is an advanced case you should not worry about unless you know what you're doing.

I need to make some tests to find why you may obtain a denied access.

**Comment by Deki60** [comment]
@g-bougard 

Thank you. 

I have again try today no chance to launch manual inventory in other computer other localhost

**Comment by g-bougard** [comment]
Hi @Deki60 

about this issue, are you trying from the browser of another computer in the trusted ip range or just from glpi server in the given ip range ? I ask because we had an issue which may prevent the server from finding the agent ip address and which I fixed yesterday in glpi master (See [Fix guessed agent addresses when netports.instantiation_type is NULL PR #10455](https://github.com/glpi-project/glpi/pull/10455)).

About Toolbox, you can check the documentation a updated a week ago: [Toolbox configuration documentation](https://glpi-agent.readthedocs.io/en/latest/plugins/toolbox-plugin.html)

**Comment by Deki60** [comment]
Hi @g-bougard 

I have testing from glpi and from other computer in trusted ip range. Same problem access is denied. 

thank you for Toolbox configuration link. i look ;)

**Comment by Deki60** [comment]
Hi @g-bougard 

I see a new problem with the agent:

I decided to deploy to multiple computers. (Same brand, model and configuration). Installing the agent manually (same agent, same version). On some computer everything is OK, inventory without problem. On others the agent goes up in GLPI but does not make any inventory. We don't even see the version of the agent. 

The agent is present but the pc does not go up

Here log : 

`[Mon Jan 31 09:44:59 2022][info] GLPI Agent service starting
[Mon Jan 31 09:45:00 2022][info] [http server] HTTPD service started on port 62354
[Mon Jan 31 09:45:01 2022][info] GLPI Agent memory usage: WSS=3764224 PFU=104599552
[Mon Jan 31 09:45:01 2022][info] target server0: server https://glpi.SERVEUR/front/inventory.php
[Mon Jan 31 09:45:01 2022][info] sending prolog request to server0
[Mon Jan 31 09:45:01 2022][info] server0 answer shows it supports GLPI Agent protocol
[Mon Jan 31 09:45:08 2022][info] running task Inventory
[Mon Jan 31 09:45:08 2022][info] New inventory from LAPTOPFAILINVENTORY-2022-01-31-09-44-59 for server0
[Mon Jan 31 09:47:55 2022][info] GLPI Agent memory usage: WSS=3350528 PFU=165687296
[Mon Jan 31 09:48:18 2022][info] sending contact request to server0
[Mon Jan 31 09:48:22 2022][info] running task Inventory
[Mon Jan 31 09:48:22 2022][info] New inventory from LAPTOPFAILINVENTORY-2022-01-31-09-44-59 for server0
[Mon Jan 31 09:49:00 2022][info] GLPI Agent memory usage: WSS=3350528 PFU=168800256`

![brave_eMxY0BOuR9](https://user-images.githubusercontent.com/6154697/151766255-27ab81bc-b24f-47fe-8851-cff41feffaf1.jpg)

**Comment by g-bougard** [comment]
Hi @Deki60 

I can't reproduce your problem. We missed probably something.
Anyway, checking this issue, I discover we may have a problem with the installation via the VBScript. It seems, at least for me, the glpi-agent log path is wrongly set in registry at it is set to a relative path.
The result is no agent journal is created so I can't ask you to attach a journal to check what happens from the agent view.

So can I ask you to update the agent configuration in registry ?
Set under `HK_LM\SOFTWARE\GLPI-Agent`, the following keys:
`debug` to `2`
`logfile` to `C:\Program Files\GLPI-Agent\logs\glpi-agent.log`
Then restart the agent and try to access to the agent remotely.
After that test, can you attach the log file you should find at `C:\Program Files\GLPI-Agent\logs\glpi-agent.log` ?

During that time, I'll investigate the installer issue.

**Comment by Deki60** [comment]
Hi @g-bougard 

Thank you for reply. 

I am not currently at the office where the servers are located. I do this as soon as possible and come back to you with the logs.

**Comment by g-bougard** [comment]
The [GLPI-Agent v1.1](https://github.com/glpi-project/glpi-agent/releases/tag/1.1) release includes a fix concerning the glpi-agent logfile wrongly setup during silent install.

**Comment by Deki60** [comment]
Hi @g-bougard 

Installation Glpi agent 1.1 solve problem ! i have access remotly :-) thank you
