### ISSUE TITLE
Stack switch Huawei not show network ports

### ISSUE THREAD

**Issue by r0bertk** [glpi-project/glpi-agent#422]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7 and dev 10.0.8

### Bug description

Hi,
I have switches in the Huawei S5731-S48T4X stack. Glpi does not show network ports. It only shows port management.
Does not work on glpi version 10.0.7 and on dev version 10.0.8 from 02/06/2023. My version of Glpi-Agent nightly is: GLPI-Agent-1.5-gitf1a94d56-x64. (I try with the latest version GLPI-Agent-1.5-git81292aee-x64 unsuccessfully)
The Single Switch inventory is working properly and shows 52 ports. However, when there are 2 or 3 switches in the stack, the .xml file does not have information about ports

### Relevant log output

```shell
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <INFO>
        <COMMENTS>S5731-S48T4X 
Huawei Versatile Routing Platform Software 
 VRP (R) software,Version 5.170 (S5731 V200R021C00SPC100) 
 Copyright (C) 2007 Huawei Technologies Co., Ltd.</COMMENTS>
        <CONTACT>IT</CONTACT>
        <ID>75</ID>
        <IPS>
          <IP>10.0.0.245</IP>
          <IP>192.168.10.253</IP>
          <IP>192.168.70.245</IP>
        </IPS>
        <LOCATION>PD80-STACK</LOCATION>
        <MAC>98:44:ce:72:1c:b0</MAC>
        <MANUFACTURER>Huawei</MANUFACTURER>
        <MODEL>S5731-S48T4X</MODEL>
        <NAME>PD80-STACK</NAME>
        <TYPE>NETWORKING</TYPE>
        <UPTIME>200 days, 07:54:21.55</UPTIME>
      </INFO>
    </DEVICE>
    <MODULEVERSION>5.1</MODULEVERSION>
    <PROCESSNUMBER>1006</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>PC1712.local-2023-05-11-21-53-33</DEVICEID>
  <QUERY>SNMPQUERY</QUERY>
</REQUEST>
```

**Comment by trasher** [comment]
Seems like an agent issue, not GLPI one

**Comment by g-bougard** [comment]
Hi @r0bertk 

can you provide a snmpwalk for this case following the [snmpwalk output documentation](https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output) to produce it with the required format ?

Your XML seems really light and we can hope the snmp walk gives us some clues to understand how this is possible.

**Comment by r0bertk** [comment]
Hi, @g-bougard 
I generated snmpwalk. Please let me know what e-mail address I should send this file to. I don't want to publish this file publicly.
Regards

**Comment by g-bougard** [comment]
Hi @r0bertk
 
you can send it to `gbougard <at> teclib <dot> com`.

**Comment by r0bertk** [comment]
Hi, @g-bougard
the file has been sent
Regards

**Comment by g-bougard** [comment]
Hi @r0bertk 

even if your walk seems truncated I'm able to produce an XML with it and `glpi-netinventory` script using `--file` option. The XML includes 143 ports with different port types (127 seems to be ethernet ports).

How many ports do you expect from this stacked switch ?

You may eventually try to use a larger timeout in the case the bulk request to carry out ports takes a too long time.
Have you checked you glpi-agent log ? If you experiment there an expiration timeout, you can also try to grow `backend-collect-timeout` glpi-agent configuration.
Also, is your glpi-agent near the switch ?

**Comment by r0bertk** [comment]
Hi, @g-bougard

> How many ports do you expect from this stacked switch ?

This is my biggest switch stack. There are 3 switches in it, 2 are Huawei 48 ports + 4 sfp and 1 is 24 port + 4 sfp. So I would like to serve 132 ports

>  If you experiment there an expiration timeout, you can also try to grow backend-collect-timeout glpi-agent configuration.

ok i will try to grow backend-collect-timeout glpi-agent configuration.

> Also, is your glpi-agent near the switch ?

my glpi-agent is near the switch

**Comment by r0bertk** [comment]
Hi, @g-bougard
I changed backend-collect-timeout=180 to 1800 and it didn't change anything

**Comment by g-bougard** [comment]
Can you share your glpi-agent log ?

**Comment by r0bertk** [comment]
Hi, @g-bougard
the file has been sent
Regards

**Comment by g-bougard** [comment]
Hi @r0bertk 

thank you. I see in your log that the agent starts the scan of your device at 13:07:53 and it logs at 13:13:16, almost 5 minutes after it started, few messages like `unknown interface X for IP address A.B.C.D, ignoring`. To me this is a symptom your device didn't respond in time earlier. This is coherent with the fact your walk was truncated.

My guess is your device finally decides to not answer anymore to a request related to ports inventory. You should investigate into your device: maybe you have logs inside with some explanation, maybe the inventory reach a request limit... don't know, but to me the problem comes from the device.

I see also in your log you're on windows and you're using SNMPv3 to access the device. I see also the SNMP timeout is set to 15 seconds.

Now I can only propose you to:
 - put a greater value on `SNMP timeout (network inventory (snmp))` in Network inventory General configuration. You'll find it in GLPI Inventory plugin administration. Try 30, than 60, 120, 240 than 600.
 - try to use SNMPv2 to see if it's faster than SNMPv3
 - try to use a glpi-agent running on linux to check if the context changes anything

**Comment by r0bertk** [comment]
Hi, @g-bougard

> put a greater value on SNMP timeout (network inventory (snmp)) in Network inventory General configuration. You'll find it in GLPI Inventory plugin administration. Try 30, than 60, 120, 240 than 600.

I increased the SNMP (network inventory (snmp)) =  60,and nothing has changed only in the glpi-agent log the time has increased to about 20 minutes:
```
[Fri Jun 16 10:57:50 2023][debug] [thread 199] #1, full match for sysobjectID .1.3.6.1.4.1.2011.2.23.693 in database
[Fri Jun 16 11:18:57 2023][debug] [thread 199] #1, unknown interface 141 for IP address 10.0.0.245, ignoring
```
I can't change timeout to more than 60 in GUI GLPI inventory , in which file can I increase this value?

> try to use SNMPv2 to see if it's faster than SNMPv3

I changed to SNMPv2c and the problem is still there

**Comment by g-bougard** [comment]
Well, 20 minutes for one device... the timeout from the agent should not be the problem, you can get it back to the default value.
You probably have an issue with the device itself and, if you don't find any related error in the device management features, you should just contact Huawei support to understand what could happen.
I'm closing the issue as the agent just seems to be a victim from a faulty device.
But feel free to update if you have interesting information to share.
Of course, you can reopen the issue if you find any evidence of something we can do on agent side to overcome such problem.

**Comment by r0bertk** [comment]
Hi, @g-bougard
However, I am also monitored by LibreNMS and there I have no problem reading via SNMP
![LibreNMS](https://github.com/glpi-project/glpi-agent/assets/13787190/f44956f7-0877-4bad-8e86-ac97a2c15416)

**Comment by g-bougard** [comment]
My guess is librenms makes less SNMP requests at a time where glpi-agent will make a lot of snmp requests in a short time. And maybe we reach a device limitation.
Or maybe this is a windows OS limitation, but this can be tested by running the agent from a linux... maybe from the server hosting your librenms instance.

**Comment by r0bertk** [comment]
Hi, @g-bougard 
I would like to touch on some of my insights tests, check out:
 - I tested glpi-agent on linux, on the same machine as LibreNMS (the same problem all the time on both snmp v2c and snmp v3)
 - I have several switch stacks in the network on different huawei, e.g. S6730-H, S5731-S48T4X, S5731-S24T4X on all these stacks there is a problem with snmp execution, e.g. unknown interface 59 for the IP address 192.168.70.247 appears, ignoring
 - If Huawei is not in the snmp stack, it will pass without any problem already at timeout > 2
 -  timeout 15s is used in Huawei (I changed it to 60, but nothing changed)
 -  There is a SNMP Packet Max Size setting in Huawei: (max 17940) I set it but nothing changes
 - In Huawei, it is possible to include, exclude MIB - specific settings in the screenshot below
![mib](https://github.com/glpi-project/glpi-agent/assets/13787190/fc759106-a440-4cc7-a156-042304e93ad9)

 (maybe I should set something up there?)

 - that, for example, LibreNMS often sends a lot of small packages and it works, while glpi-agent sends one package (a single switch package is about 500-700kB, while a stacked switch package is > 1 MB)
 -  I can send from LibreNMS Capture Debug Information: Discovery, Poller. Send?
 -  in the Huawei documentation information Pipeline is full -> NMS sent too many SNMP request packets to overload the channel. Huawei recommendation -> Reduce the amount of SNMP request packets sent by NMS. (I don't know if it has anything to do with it)
-  Is it possible to somehow upload to GLPI information about switches based on e.g. snmpwalk?

Regards

**Comment by g-bougard** [comment]
Hi @r0bertk 

thank you for the sharing of your tries & experiments.

What I can comment:
 * same issue from linux, even with snmpv2: okay, OS or protocol version is not the problem
 * for the "unknown interface for the IP address ... appears, ignoring" message, this is more a debug info for agent developer as this can suggest we should adapt port analysis if something is finally missing. But here they should appear as the switch failed to send all required ports information.
 * as you demonstrated, the SNMP timeout parameter can't be used to fix this problem.
 * I appreciate you tried to adjust a switch parameter you thought it could be the problem, but okay, the packet size seems not the problem. Or maybe something should also be updated on the OS side, but I think we shouldn't go this way.
 * about mib to include/exclude, I don't this you have to change anything here.
 * about NMS requesting a lot of small packets while the agent requets one and receives a big one... probably too big for the switch, this is a clue. And the clue is I think the agent is making bulk requests.
 * forget librenms capture debug information, this is probably for librenms development, not for us.
 * about the huawei documentation info suggesting to reduce SNMP request amount for NMS, this only tells huawei is aware of some limitations of their devices. Or at at least, their limitations with the normal switch configuration, but anyway, the agant as using bulk requests is still doing less requests.

For the last question, I can say "yes, this is possible"... but as I said before, the walk you provided is truncated, and I think this is another clue in my thought. I told you I was able to see ports in your walk, but I don't know if all the ports are there, so I can't tell you for sure this is the solution. But here is the process:
 * generate a snmp walk by redirecting the output in file using the syntax I asked you to use before
 * use glpi-inventory script to generate a networking XML inventory: `glpi-netinventory --file generated-snmpwalk.walk >switch.xml`
 * you can directly upload the XML with such commant: `glpi-injector -u http://my-glpi-server-url/... -f switch.xml`
   or you can upload all XML file from a folder if you generated all XMLs for a bunch of switch, check the syntax in [glpi-injector man page](https://glpi-agent.readthedocs.io/en/latest/man/glpi-injector.html)

But as I said, this can leave with other problem if snmp walk are truncated. Also, this can prevent some inventory features like vlan inventory.

I would like to know if you can manage to have not truncated snmp walk. Maybe you can try `snmpbulkwalk` command with the same parameters, I guess its comportment is near to the agent comportment. Maybe if it fails you can see other symptomatic messages, check snmpcmd man page on linux to add logging options.

Googling a little, I found a huawei thread where they were talking about a "cpu-defend" parameter. This seems to be a security feature. Can you check your switch documentation to see how you can manage it ? Maybe you can find some security log telling the glpi-agent ip is attacking the switch. If this is the case, maybe you have to add some rules to trust that ip and accept a short overload. In that case, you'll have also to check if the switch is still running as expected during that overload. Is this is the case you'll have to plan the inventory at a time this won't be an issue for your IT.

You may also have to check your firmware level. Sometime an upgrade fixes stuffs.

Don't forget to contact huawei support if nothing works or gives more clue.

Can you still answer if you always have a truncated snmp walk ? And if you can find a way to overcome that first problem ? This is even a more general problem you can submit to huawei support as I guess they won't care about glpi-agent related problems.

**Comment by r0bertk** [comment]
Hi, @g-bougard
Thank you very much for any advice. As suggested, I added ACL on the switch.
I am in the process of further testing.
I have a question about snmpwalk because if I use the command snmpwalk -v <version> -c <community> -t 15 -Cc -On -Ox <somehost> .1 > walk-filename.walk, the process has been going on for several minutes and the last time you wrote that the walk was interrupted, I just finished it with ctr+c, now I don't want to do it. How long is the snmpwalk?
Interestingly, in LibreNMS it is possible to generate a snmpwalk and it was generated for me after about 5 minutes.
I uploaded the glpi-injector file generated by LibreNMS snmpwalk and it imported beautifully to glpi presenting 128 ports
Regards

**Comment by g-bougard** [comment]
Hi @r0bertk 
if it was truncated because you finally aborted it, okay, this is probably not the clue I thought. But depending on the switch size and performance, a walk can take a very long time. Can you monitor the switch load during the walk ? Can you check if the walk output is getting stuck at some time and does the load come back to normal at the same time ? If yes, it may mean the switch decided to stop answering to the walk request. Maybe to can use logging option as I proposed (check snmpcmd man page) to monitor how the switch is answering during the walk.
After a full and not truncated walk, maybe this can help to identify a mib part to exclude if it takes a too long time and it is not use for inventory or monitoring by LibreNMS. But this would work for walk, probaly not for the agent inventory. You may also want to compare the time it takes to generate a walk with `snmpwalk` and `snmpbulkwalk`.

For LibreNMS, maybe it doesn't start the walk from `.1` OID, so it could be more limited and don't reach heavy parts. You'll have to compare that walk with the full one from the command line. If finally, they are the same, it could be interesting to find how this is possible.

P.S.: You can probably find limited parameter for the snmpwalk command that runs in a limited time and provides enough information to generate a minimal XML.

**Comment by r0bertk** [comment]
Hi, @g-bougard
The full snmpwalk lasted 18 hours. Once done, it can be uploaded via glpi-injector to glpi and it passes without errors. The file after processing by glpi-netinventory to .xml is similar in size to the one exported by LibreNMS (only libreNMS does it in 4 minutes).
However, when it comes to monitoring the switch, I did not notice any significant changes in the load. The load is constantly from 9-11%.
At the moment, this solution satisfies me, the most important thing is that I managed to upload ports and connections to computers and other network equipment to GLPI.
After the holidays, I'm still trying to get busy with it. As soon as I come to any conclusions, I will write about it.
Thanks again for your help

**Comment by g-bougard** [comment]
Hi @r0bertk 
thank you for this feedback.
If the switch isn't loaded this probably means it has a limit against the snmp load the agent requests.
18 hours... this is really long. How much lines the walk contains ? Just to evaluate how many requests by second was answered. But it would be interesting to know if the switch has many moment without answering anything.
