### ISSUE TITLE
Restarting myself as glpi-agent service , but not restarting

### ISSUE THREAD

**Issue by Frflamingo** [glpi-project/glpi-agent#425]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

glpi-agent V 1.4
Running on Microsoft Windows 10 Enterprise 2016 LTSB

After 3 month of uptime the agent has stopped 

Looking at the logs the last lines are

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

```rich-text-format
[Wed Jun 14 02:15:28 2023][info] GLPI Agent memory usage: WSS=3465216 PFU=127549440
[Wed Jun 14 04:13:19 2023][info] target server0: server https://xxxxx/marketplace/glpiinventory/
[Wed Jun 14 04:13:19 2023][info] sending contact request to server0
[Wed Jun 14 04:13:22 2023][info] sending prolog request to server0
[Wed Jun 14 04:13:24 2023][info] running task Deploy
[Wed Jun 14 04:13:38 2023][info] running task Collect
[Wed Jun 14 04:13:39 2023][info] No Collect job enabled or Collect support disabled server side.
[Wed Jun 14 04:13:41 2023][info] running task Inventory
[Wed Jun 14 04:13:41 2023][info] New inventory from UK00-A39-2023-03-30-11-32-22 for server0
[Wed Jun 14 04:14:54 2023][info] target server0: next run: Wed Jun 14 06:10:54 2023 - https://xxxx/marketplace/glpiinventory/
[Wed Jun 14 04:14:54 2023][info] GLPI Agent memory usage: WSS=3022848 PFU=138014720
[Wed Jun 14 04:14:54 2023][info] Restarting myself as glpi-agent service
[Wed Jun 14 04:14:58 2023][info] GLPI Agent exiting (34388)
``` 

And actually the agent is not restarting 
Agent was installed using installer and vbs scripts 

### To reproduce

Aging ....

### Expected behavior

I would expect to restart indeed

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

**Comment by g-bougard** [comment]
Hi @Frflamingo 

have you in agent log the time it first started ?

Can you check also in system EventViewer what related message you can have ? Maybe the system forbids that action.

**Comment by g-bougard** [comment]
For you to know, this is a feature implemented when the agent detects it starts to use too much memory as perl is not fully efficient to release memory when used in a service context.
In that situation, the agent tries to run the following command:
```
start /b "" cmd /S /C "net stop glpi-agent && net start glpi-agent" >nul
```
and so, this is what seems to fail in your context.

**Comment by g-bougard** [comment]
Tested 1.5 release on Windows 10 Professionnel 22H2 and the restart command works as expected.

**Comment by Frflamingo** [comment]
Sorry for late answer ....
Same agent is really behaving strangely 
After this ticket i restarted the agent manually (on Jun 21 ) and it (auto) stopped on Jun 23 with same message
Looking back in time , looks like the agent is usually restarting everyday , and the restart is quite successfull like :

> [Thu Jun  8 17:45:36 2023][info] GLPI Agent memory usage: WSS=2998272 PFU=137670656
[Thu Jun  8 17:45:36 2023][info] Restarting myself as glpi-agent service
[Thu Jun  8 17:45:37 2023][info] GLPI Agent exiting (29708)
[Thu Jun  8 17:45:48 2023][info] GLPI Agent service starting
[Thu Jun  8 17:45:51 2023][info] [http server] HTTPD service started on port 62354

Looking into the eventviewer as suggested:
> A timeout was reached (30000 milliseconds) while waiting for the glpi-agent service to connect.

>The glpi-agent service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion.

I reboot the machine and monitor it

**Comment by g-bougard** [comment]
Thank you for your feedback.

You should also probably upgrade the agent. This can help and if there's something to develop to work-around your problem this would be done on current version.

**Comment by Frflamingo** [comment]
Updated agent to 1.5 as of today ... still monitoring 
Suspect a windows aging issue

**Comment by g-bougard** [comment]
Hi @Frflamingo 

feel free to reopen and/or comment is you have any update.
