### ISSUE TITLE
GLP Agent 1.5 linux perl installer won't install by default when nightly is still installed

### ISSUE THREAD

**Issue by GuidoWilden** [glpi-project/glpi-agent#426]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Installer fails immediately:
```
perl glpi-agent-1.5-linux-installer.pl --install
Use of uninitialized value in concatenation (.) or string at glpi-agent-1.5-linux-installer.pl line 1138.
Installing glpi-agent v1.5...
Failed to install glpi-agent
```

### To reproduce

1. Currently running nightly build GLPI-Agent_v1.5-git7d827463
2. Get the above error when running 1.5 installer

### Expected behavior

Should install.

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

GLPI v10.7
GLPI inventory plugin 1.2.1

**Comment by g-bougard** [comment]
Hello @GuidoWilden 

thank you for your report, can you tell us which linux system & version this occurs on ?

**Comment by g-bougard** [comment]
You can also give the output of the command when also using `--verbose` option.

**Comment by GuidoWilden** [comment]
Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-75-generic x86_64)

```
perl glpi-agent-1.5-linux-installer.pl --install --verbose
Running on linux distro: Ubuntu 22.04.2 LTS : Ubuntu : 22.04.2 LTS (Jammy Jellyfish)...
Use of uninitialized value in concatenation (.) or string at glpi-agent-1.5-linux-installer.pl line 1138.
Guessed installation type:
Installing glpi-agent v1.5...
Trying to install glpi-agent v1.5-1 on Ubuntu 22.04.2 LTS release (Ubuntu:22.04.2 LTS (Jammy Jellyfish))...
glpi-agent-task-esx will be upgraded
glpi-agent-task-network will be upgraded
glpi-agent will be upgraded
Extracting glpi-agent_1.5-1_all.deb ...
Extracting glpi-agent-task-esx_1.5-1_all.deb ...
Extracting glpi-agent-task-network_1.5-1_all.deb ...
Running: apt -y install /var/tmp/glpi-agent-task-esx_1.5-1_all.deb /var/tmp/glpi-agent-task-network_1.5-1_all.deb /var/tmp/glpi-agent_1.5-1_all.deb 2>/dev/null
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'glpi-agent-task-esx' instead of '/var/tmp/glpi-agent-task-esx_1.5-1_all.deb'
Note, selecting 'glpi-agent-task-network' instead of '/var/tmp/glpi-agent-task-network_1.5-1_all.deb'
Note, selecting 'glpi-agent' instead of '/var/tmp/glpi-agent_1.5-1_all.deb'
Suggested packages:
  smartmontools read-edid
The following packages will be DOWNGRADED:
  glpi-agent glpi-agent-task-esx glpi-agent-task-network
0 upgraded, 0 newly installed, 3 downgraded, 0 to remove and 4 not upgraded.
Failed to install glpi-agent
```

**Comment by g-bougard** [comment]
Oh! As you're upgrading from a nightly build, you probably need to use `--force` option as apt is telling it is about to downgrade packages.

**Comment by g-bougard** [comment]
I need anyway to fix that not clean perl warning:
```
Use of uninitialized value in concatenation (.) or string at glpi-agent-1.5-linux-installer.pl line 1138.
```

**Comment by GuidoWilden** [comment]
Thank you @g-bougard, `--force` has done the trick.

**Comment by g-bougard** [comment]
Hi @GuidoWilden 
I can confirm you the warning has no consequence and it will be fixed in next nightly.
