### ISSUE TITLE
ESX task failure with glpi 10-beta

### ISSUE THREAD

**Issue by g-bougard** [glpi-project/glpi-agent#43]
Hi @g-bougard 

i force task ESX from GLPI and run cmd on agent. 

```
C:\Program Files\GLPI-Agent>glpi-agent.bat --logger=stderr --debug --debug --tasks=ESX
[debug] Logger backend Stderr initialized
[debug] Logger backend File initialized
[debug] GLPI Agent (1.1-git31840f5c)
[debug] Configuration directory: C:/Program Files/GLPI-Agent/etc
[debug] Data directory: C:/Program Files/GLPI-Agent/share
[debug] Storage directory: C:\Program Files\GLPI-Agent\var
[debug] Lib directory: C:/Program Files/GLPI-Agent/perl/agent
[debug] [target server0] Next server contact planned for Wed Jan  5 13:34:17 2022
[debug2] getAvailableTasks() : add of task Collect version 2.7
[debug2] getAvailableTasks() : add of task Deploy version 2.9
[debug2] getAvailableTasks() : add of task ESX version 2.7
[debug2] getAvailableTasks() : add of task Inventory version 1.10
[debug2] getAvailableTasks() : add of task NetDiscovery version 4.4
[debug2] getAvailableTasks() : add of task NetInventory version 4.4
[debug2] getAvailableTasks() : add of task RemoteInventory version 0.9
[debug2] Preparing execution plan
[debug] Available tasks:
[debug] - Collect: 2.7
[debug] - Deploy: 2.9
[debug] - ESX: 2.7
[debug] - Inventory: 1.10
[debug] - NetDiscovery: 4.4
[debug] - NetInventory: 4.4
[debug] - RemoteInventory: 0.9
[debug] target server0: server http://GLPI-Serveur/plugins/glpiinventory
[debug] Planned tasks for server0: ESX
[debug] Provided by Teclib Edition
[debug] Installer built on Sat Dec 25 02:17:49 2021 UTC
[debug] Built with Strawberry Perl 5.34.0
[debug] Built on github actions windows image for glpi-project/glpi-agent repository
[debug] Running in foreground mode
[info] target server0: server http://GLPI-Serveur/plugins/glpiinventory
[debug] [http client] 39A91910: Using Compress::Zlib for compression
[info] sending contact request to server0
[debug2] [http client] 39A91910: sending message:
{
   "action": "contact",
   "deviceid": "GLPI-Agent.dom1-2021-12-30-10-26-09",
   "enabled-tasks": [
      "esx"
   ],
   "installed-tasks": [
      "collect",
      "deploy",
      "esx",
      "inventory",
      "netdiscovery",
      "netinventory",
      "remoteinventory"
   ],
   "name": "GLPI-Agent",
   "tag": "Tag,
   "version": "1.1-git31840f5c"
}
[debug2] format: Zlib
[debug2] [http client] 39A91910: received message:
{"expiration":24,"status":"ok"}
[info] running task ESX
[debug2] http://GLPI-Serveur/plugins/glpiinventory?action=getConfig&machineid=GLPI-Agent.dom1-2021-12-30-10-26-09&task[ESX]=2.7
[info] No ESX job enabled or ESX support disabled server side.
```

Edit, second test i have an error

```
C:\Program Files\GLPI-Agent>glpi-agent.bat --logger=stderr --debug --debug --tasks=ESX
[debug] Logger backend Stderr initialized
[debug] Logger backend File initialized
[debug] GLPI Agent (1.1-git31840f5c)
[debug] Configuration directory: C:/Program Files/GLPI-Agent/etc
[debug] Data directory: C:/Program Files/GLPI-Agent/share
[debug] Storage directory: C:\Program Files\GLPI-Agent\var
[debug] Lib directory: C:/Program Files/GLPI-Agent/perl/agent
[debug] [target server0] Next server contact planned for Wed Jan  5 13:41:25 2022
[debug2] getAvailableTasks() : add of task Collect version 2.7
[debug2] getAvailableTasks() : add of task Deploy version 2.9
[debug2] getAvailableTasks() : add of task ESX version 2.7
[debug2] getAvailableTasks() : add of task Inventory version 1.10
[debug2] getAvailableTasks() : add of task NetDiscovery version 4.4
[debug2] getAvailableTasks() : add of task NetInventory version 4.4
[debug2] getAvailableTasks() : add of task RemoteInventory version 0.9
[debug2] Preparing execution plan
[debug] Available tasks:
[debug] - Collect: 2.7
[debug] - Deploy: 2.9
[debug] - ESX: 2.7
[debug] - Inventory: 1.10
[debug] - NetDiscovery: 4.4
[debug] - NetInventory: 4.4
[debug] - RemoteInventory: 0.9
[debug] target server0: server http://GLPI-Serveur/plugins/glpiinventory
[debug] Planned tasks for server0: ESX
[debug] Provided by Teclib Edition
[debug] Installer built on Sat Dec 25 02:17:49 2021 UTC
[debug] Built with Strawberry Perl 5.34.0
[debug] Built on github actions windows image for glpi-project/glpi-agent repository
[debug] Running in foreground mode
[info] target server0: server http://GLPI-Serveur/plugins/glpiinventory
[debug] [http client] 192001E3: Using Compress::Zlib for compression
[info] sending contact request to server0
[debug2] [http client] 192001E3: sending message:
{
   "action": "contact",
   "deviceid": "GLPI-Agent-2021-12-30-10-26-09",
   "enabled-tasks": [
      "esx"
   ],
   "installed-tasks": [
      "collect",
      "deploy",
      "esx",
      "inventory",
      "netdiscovery",
      "netinventory",
      "remoteinventory"
   ],
   "name": "GLPI-Agent",
   "tag": "Tag",
   "version": "1.1-git31840f5c"
}
[debug2] format: Zlib
[debug2] [http client] 192001E3: received message:
{"expiration":24,"status":"ok"}
[info] running task ESX
[debug2] http://GLPI-Serveur/plugins/glpiinventory?action=getConfig&task[ESX]=2.7&machineid=GLPI-Agent-2021-12-30-10-26-09
[debug2] http://GLPI-Serveur/plugins/glpiinventory/b/esx/?action=getJobs&machineid=GLPI-Agent-2021-12-30-10-26-09
[info] Got 1 VMware host(s) to inventory.
[error] Undefined subroutine &GLPI::Agent::Task::ESX::uuid_to_string called at C:/Program Files/GLPI-Agent/perl/agent/GLPI/Agent/Task/ESX.pm line 202.
```

_Originally posted by @bbreton09 in https://github.com/glpi-project/glpi/issues/10162#issuecomment-1005650493_

**Comment by g-bougard** [comment]
Hi @bbreton09
I just fixed this issue in 33ef0b73
You'll be able to get the development build from [related GH Actions workflow run](https://github.com/glpi-project/glpi-agent/actions/runs/1662166097) or wait for next nightly build to validate the fix. You can also apply the patch yourself: you have only one line to insert to `C:\Program Files\GLPI-Agent\perl\agent\GLPI\Agent\Task\ESX.pm` around the beginning.

**Comment by bbreton09** [comment]
Hi, @g-bougard 

Task start on agent, in log i have error on JSON but task sucess in GLPI

```
[debug2] format: Zlib
[debug2] [http client] F53EC70E: received message:
{"status":"error","message":"Array\n(\n    [0] => JSON does not validate. Violations:\nAdditional properties not allowed: accountinfo at #->$ref[inventory.schema.json]->properties:content\n\n)\n","expiration":24}
[error] [http client] F53EC70E: server error: Array
(
    [0] => JSON does not validate. Violations:
Additional properties not allowed: accountinfo at #->$ref[inventory.schema.json]->properties:content
```

**Comment by g-bougard** [comment]
Hi @bbreton09 
this is weird, "accountinfo" is indeed coming from your tag and it should have been set elsewhere in json. I'm investigating, but you still can make a try without setting the tag ?

**Comment by g-bougard** [comment]
Hi @bbreton09 
can you try latest GLPI Agent nightly build as I pushed 2 commits that should fix this ESX inventory problem ?

**Comment by bbreton09** [comment]
> Hi @bbreton09 can you try latest GLPI Agent nightly build as I pushed 2 commits that should fix this ESX inventory problem ?

Hi @g-bougard 

I just install GLPI-Agent_v1.1-git76b34bdd, force ESX update. 
The task does not start automatically. Even if I force the agent to synchronize. The manual launch of the command on the agent retrieves a task but does not execute it.

I have an error in GLPI "L'agent demande une configuration qui lui a déjà été envoyée par le serveur. L'agent est susceptible d'avoir rencontré une erreur critique"

On agent side "[info] No ESX job enabled or ESX support disabled server side."

**Comment by g-bougard** [comment]
Hi @bbreton09 

to be clear, if you have such a message: `L'agent demande une configuration qui lui a déjà été envoyée par le serveur. L'agent est susceptible d'avoir rencontré une erreur critique`, this may mean you probably forgot to click on `Force start` button on the task in GLPI. Even, you must do that before each time you start the agent.

The only case you don't have to do that is when the task has run, was successful and you have checked "on" the task option "Re-prepare a target-actor if previous run is successful :".

To resume for each try, you have to:
1. click on "Force start" on the task in GLPI
2. Force the agent to run tasks

**Comment by bbreton09** [comment]
> Hi @bbreton09
> 
> to be clear, if you have such a message: `L'agent demande une configuration qui lui a déjà été envoyée par le serveur. L'agent est susceptible d'avoir rencontré une erreur critique`, this may mean you probably forgot to click on `Force start` button on the task in GLPI. Even, you must do that before each time you start the agent.
> 
> The only case you don't have to do that is when the task has run, was successful and you have checked "on" the task option "Re-prepare a target-actor if previous run is successful :".
> 
> To resume for each try, you have to:
> 
> 1. click on "Force start" on the task in GLPI
> 2. Force the agent to run tasks

This is what i do.

**Comment by g-bougard** [comment]
After clicking "Force start" in GLPI, run manually `C:\Program Files\GLPI-Agent>glpi-agent.bat --logger=stderr --debug --debug --tasks=ESX` as before and then can you report the end of the output, starting from the line `[info] running task ESX` ?

**Comment by bbreton09** [comment]
> After clicking "Force start" in GLPI, run manually `C:\Program Files\GLPI-Agent>glpi-agent.bat --logger=stderr --debug --debug --tasks=ESX` as before and then can you report the end of the output, starting from the line `[info] running task ESX` ?

Hi @g-bougard 

yes i do this with last nightly same issu

1.click on "Force start" on the task in GLPI
2.Force the agent to run tasks
2.1 task start status : "en cours"
3.run manually C:\Program Files\GLPI-Agent>glpi-agent.bat --logger=stderr --debug --debug --tasks=ESX
3.1 no task start

[debug2] format: Zlib
[debug2] [http client] 183A850C: received message:
{"expiration":24,"status":"ok"}
[info] running task ESX
[debug2] http://GLPI-Serveur/plugins/glpiinventory?action=getConfig&task[ESX]=2.7&machineid=GLPI-Aagent-2021-12-30-10-26-09
[info] No ESX job enabled or ESX support disabled server side.

URL in debug2 show

{"configValidityPeriod":600,"schedule":[{"periodicity":3600,"delayStartup":3600,"task":"ESX","remote":"http:\/\/GLPI-Serveur\/plugins\/glpiinventory\/b\/esx\/"}]}

**Comment by bbreton09** [comment]
> > After clicking "Force start" in GLPI, run manually `C:\Program Files\GLPI-Agent>glpi-agent.bat --logger=stderr --debug --debug --tasks=ESX` as before and then can you report the end of the output, starting from the line `[info] running task ESX` ?
> 
> Hi @g-bougard
> 
> yes i do this with last nightly same issu
> 
> 1.click on "Force start" on the task in GLPI 2.Force the agent to run tasks 2.1 task start status : "en cours" 3.run manually C:\Program Files\GLPI-Agent>glpi-agent.bat --logger=stderr --debug --debug --tasks=ESX 3.1 no task start
> 
```
[info] running task ESX
[debug2] http://GLPI-Serveur/plugins/glpiinventory?action=getConfig&task[ESX]=2.7&machineid=GLPI-Agent-2021-12-30-10-26-09
[info] No ESX job enabled or ESX support disabled server side.
```
> 
> URL in debug2 show
> 
`{"configValidityPeriod":600,"schedule":[{"periodicity":3600,"delayStartup":3600,"task":"ESX","remote":"http:\/\/GLPI-Serveur\/plugins\/glpiinventory\/b\/esx\/"}]}`

**Comment by g-bougard** [comment]
Hi @bbreton09 
as I understand, you're clicking the "Force start" on server-side and run 2 times the agent: you're point 2 and 3 are like running the agent ESX task 2 times but without clicking again on "Force start" on server-side between the 2 runs.

So what you have to do is to click "Force start" on server-side, don't force the agent to run tasks, but just run the ESX task from the command line: just point 1 and 3

**Comment by bbreton09** [comment]
Hi @g-bougard 

If i do 1 and 3 the agent never contact server. No log in apacha access.log from client

```
C:\Program Files\GLPI-Agent>glpi-agent.bat --logger=stderr --debug --debug --tasks=ESX
[debug] Logger backend Stderr initialized
[debug] Logger backend File initialized
[debug] GLPI Agent (1.1-gitce8e7d74)
[debug] Configuration directory: C:/Program Files/GLPI-Agent/etc
[debug] Data directory: C:/Program Files/GLPI-Agent/share
[debug] Storage directory: C:\Program Files\GLPI-Agent\var
[debug] Lib directory: C:/Program Files/GLPI-Agent/perl/agent
[debug] [target server0] Next server contact planned for Mon Jan 10 20:10:30 2022
[debug2] getAvailableTasks() : add of task Collect version 2.7
[debug2] getAvailableTasks() : add of task Deploy version 2.9
[debug2] getAvailableTasks() : add of task ESX version 2.7
[debug2] getAvailableTasks() : add of task Inventory version 1.10
[debug2] getAvailableTasks() : add of task NetDiscovery version 4.4
[debug2] getAvailableTasks() : add of task NetInventory version 4.4
[debug2] getAvailableTasks() : add of task RemoteInventory version 0.9
[debug2] Preparing execution plan
[debug] Available tasks:
[debug] - Collect: 2.7
[debug] - Deploy: 2.9
[debug] - ESX: 2.7
[debug] - Inventory: 1.10
[debug] - NetDiscovery: 4.4
[debug] - NetInventory: 4.4
[debug] - RemoteInventory: 0.9
[debug] target server0: server http://GLPI-Server/plugins/glpiinventory
[debug] Planned tasks for server0: ESX
[debug] Provided by Teclib Edition
[debug] Installer built on Fri Jan  7 16:10:41 2022 UTC
[debug] Built with Strawberry Perl 5.34.0
[debug] Built on github actions windows image for glpi-project/glpi-agent repository
[debug] Running in foreground mode
[info] server0 is not ready yet, next server contact planned for Mon Jan 10 20:10:30 2022
```

I try the URL http://GLPI-Server/plugins/glpiinventory work fine.

**Comment by g-bougard** [comment]
Add `--force` option to your command-line as you have this line:
```
[info] server0 is not ready yet, next server contact planned for Mon Jan 10 20:10:30 2022
```

**Comment by bbreton09** [comment]
@g-bougard 

I reinstall GLPI-Agent-1.1-git31840f5c-x64.msi and the task is download without --force.

Last nighly with --force run but with issue:

```
[info] server0 is not ready yet, but run is forced
[info] target server0: server http://GLPI-Server/plugins/glpiinventory
[debug] [http client] 06DCDD95: Using Compress::Zlib for compression
[info] sending contact request to server0
[debug2] [http client] 06DCDD95: sending message:
{
   "action": "contact",
   "deviceid": "GLPI-Agent-2021-12-30-10-26-09",
   "enabled-tasks": [
      "esx"
   ],
   "installed-tasks": [
      "collect",
      "deploy",
      "esx",
      "inventory",
      "netdiscovery",
      "netinventory",
      "remoteinventory"
   ],
   "name": "GLPI-Agent",
   "tag": "TAG",
   "version": "1.1-gitce8e7d74"
}
[debug2] format: Zlib
[debug2] [http client] 06DCDD95: received message:
{"expiration":24,"status":"ok"}
[info] running task ESX
[debug2] http://GLPI-Server/plugins/glpiinventory?action=getConfig&task[ESX]=2.7&machineid=GLPI-Agent-2021-12-30-10-26-09
[debug2] http://GLPI-Server/plugins/glpiinventory/b/esx/?action=getJobs&machineid=GLPI-Agent-2021-12-30-10-26-09
[info] Got 6 VMware host(s) to inventory.
[debug] [http client] 2071ADC9: Using Compress::Zlib for compression
[debug] unknown field NAME for section DRIVES
[debug] unknown field NAME for section DRIVES
[debug] unknown field NAME for section DRIVES
[debug] unknown field NAME for section DRIVES
[error] encountered object 'GLPI::Agent::Protocol::Inventory=HASH(0x605dd88)', but neither allow_blessed, convert_blessed nor allow_tags settings are enabled (or TO_JSON/FREEZE method missing) at C:/Program Files/GLPI-Agent/perl/agent/GLPI/Agent/Protocol/Message.pm line 73.
```

**Comment by g-bougard** [comment]
Thank you for your effort, this really helps as I don't have an ESX to validate it myself.

**Comment by bbreton09** [comment]
> Thank you for your effort, this really helps as I don't have an ESX to validate it myself.

I do my best to help :)
I used 9.5 with fusion agent with task ESX, SNMP and Scann and y try to do same with V10 and GLPI-Inventory :)

**Comment by g-bougard** [comment]
Hi @bbreton09
I added some fixes with 0cbf33b & 199d068
You'll be able to get the development build from [latest GH Actions workflow run](https://github.com/glpi-project/glpi-agent/actions/runs/1678440813) or wait for next nightly build to check if this fixes your issue.

**Comment by bbreton09** [comment]
hi @g-bougard 

I install dev build "version": "1.1-gitf5824389" task start without --force but error.

```
[debug2] format: Zlib
[debug2] [http client] CB2DF785: received message:
{"expiration":24,"status":"ok"}
[info] running task ESX
[debug2] http://GLPI-Server/plugins/glpiinventory?action=getConfig&task[ESX]=2.7&machineid=GLPI-Agent-2021-12-30-10-26-09
[debug2] http://GLPI-Server/plugins/glpiinventory/b/esx/?action=getJobs&machineid=GLPI-Agent-2021-12-30-10-26-09
[info] Got 3 VMware host(s) to inventory.
[debug] [http client] 6BF7BEAB: Using Compress::Zlib for compression
[error] encountered object 'GLPI::Agent::Protocol::Inventory=HASH(0x8dbc0b0)', but neither allow_blessed, convert_blessed nor allow_tags settings are enabled (or TO_JSON/FREEZE method missing) at C:/Program Files/GLPI-Agent/perl/agent/GLPI/Agent/Protocol/Message.pm line 73.
```

I remove TAG from agent  but same issue.

**Comment by g-bougard** [comment]
Hi @bbreton09
sorry I forgot to test the main issue. Last commit should fix it too.
Can you try the development build from [latest GH Actions workflow run](https://github.com/glpi-project/glpi-agent/actions/runs/1681699018) or wait for next nightly build to check if this definitively fixes the problem.

**Comment by bbreton09** [comment]
Hi @g-bougard 

It's works !!
![image](https://user-images.githubusercontent.com/10090794/148931620-bcdb52b0-37b5-44e9-85a7-7efb9b4fbecb.png)

**Comment by g-bougard** [comment]
Nice !
Thank you for your patience ;-)

**Comment by bbreton09** [comment]
@g-bougard  befor i open a new issue can you tell me if SNMP scan is still working  in beta 10 ?

**Comment by g-bougard** [comment]
I'm currently working on few issues with GLPI-Agent, GLPI 10-beta and GlpiInventory plugin release candidate. SNMP Scan should at least work with FusionInventory-Agent 2.6. But feel free to open an issue.
