### ISSUE TITLE
Complete inventory of LXC containers via remote inventory of the host that contains them

### ISSUE THREAD

**Issue by alexmicontini** [glpi-project/glpi-agent#437]
Hi,

Nowadays, the use of virtualization with containers is very common.

In my organization we have about 300 Linux VMs with LXC containers that we need to inventory (before we had systemd-nspawn).

We use the remote inventory task to inventory the hosts that contain the LXC containers, we do not install agent. The agent performs a complete inventory of the hosts, detecting the LXC containers that they have and that can be seen in the Virtualization section.

The problem is that we want the remote inventory task from the glpi agent to the host containing the containers to also perform a complete inventory of the containers, including the software, not just enumerate them, but the glpi agent does not do it even if the user logged in. connect via SSH have root privileges.

![image](https://github.com/glpi-project/glpi-agent/assets/86783891/db7fa6ff-82b1-4c08-854f-c37ca6f4b83a)

![image](https://github.com/glpi-project/glpi-agent/assets/86783891/71ab5127-120d-4607-8701-f50854f7960b)

Would it be possible to make the glpi agent using the remote inventory task to host do the full inventory of the LXC containers, including the software, at the same time?

Is it feasible to modify the glpi agent for that? What alternatives are there to carry out the complete inventory of each LXC container?

Thank you. All the best

**Comment by g-bougard** [comment]
Hi @alexmicontini 

I'm using myself LXC for my GLPI test instances so I understand what you're talking about.

I would yes this is probably possible to fully inventory a lxc container from the host as we can even "run" commands using lxc-attach or lxc-execute commands. Modifying the agent to do such task is also possible, but I think there's a simpler solution: you can manage to always run your container with a ssh daemon so you can also inventory them with remoteinventory task.

**Comment by alexmicontini** [comment]
Hi @g-bougard,

It would be much better for us if the remote inventory to the host containing the LXC containers does the complete inventory of the LXC containers.

Although LXC containers have the SSH daemon enabled and have their own IP address, there are still a majority of systemd-nspawn containers that need to migrate to LXC.

In addition, it is very tedious to remotely inventory the 300 hosts and also each container, at the expense that in the new version of GLPI a remote inventory by discovery is possible.

On the other hand, I do not know if the link between the host and the containers in the inventory would be maintained when a remote inventory is made to the host and also to the containers.

**Comment by g-bougard** [comment]
Hi @alexmicontini 

it would be very tedious to develop the solution you expect. We don't have actually plan to develop such a feature.

The link between the host and the container is GLPI depends on found uuid. As far I know, this works well for LXC, if it doesn't work as expected this would be a bug to fix.

For you to know, GLPI-Agent v1.5, which was release 2 weeks ago, supports now multi-workers for remote inventory task so you can inventory many remote host at the same time. Next 1.6 version should support remoteinventory started from netdiscovery. This feature is actually developped into the feature/glpi-netscan branch and will be soon integrated into develop branch so you would be able soon to test it from a nightly build.

**Comment by alexmicontini** [comment]
Okay @g-bougard,

Thank you very much for answering.

From your answer, we are only left with the option of remote inventorying the host and containers separately. 
We hope to gradually migrate all containers to LXC.

Yes, I am aware of the remote-workers option from v1.5 and we will update from development version 1.5 shortly.

Good news that 1.6 has the discovery for remote inventory, hopefully it won't take long to come out.

Thank you so much. a cordial greeting
