### ISSUE TITLE
Page Code Trouble in inventory

### ISSUE THREAD

**Issue by homebrewtainy** [glpi-project/glpi-agent#44]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

I still have but want a public following to keep the community aware

### Describe the bug

GLPI-Agent (MS-Windows x64) inventories send with page code char anomaly.

### To reproduce

Fresh GLPI 10 beta installation ( GLPI master.0f54d02 nightly builds ) in french environment 
Run fine
Latest Windows x64 GLPI Agent ( GLPI-Agent-1.1-git31840f5c-x64.msi nightly builds ) in french environment 

Inventory planned has system service and run fine => computer is created in GLPI.
Some Assets, like " Software " returns with some text with diacritical characters (see screen capture bellow).

![image](https://user-images.githubusercontent.com/74141901/148373723-7a2fe47c-87c6-4ec5-9440-fae048002c04.png)

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.0-dev ( => /usr/share/glpi)
Installation mode: TARBALL to FHS
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux glpi.jdhweb.com 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Tue Dec 21 13:57:48 EST 2021 x86_64
PHP 8.0.14 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, selinux, session, shmop, sockets, sodium, sqlite3, standard,
	sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.37 (AlmaLinux) ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
Server Software: MariaDB Server
	Server Version: 10.3.28-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi_db_user@localhost/glpi_db
	Host info: Localhost via UNIX socket
	
PHP version (8.0.14) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
Database engine version (10.3.28) is supported.
The log file has been created successfully.
Write access to /var/lib/glpi/files/_cache has been validated.
Write access to /etc/glpi has been validated.
Write access to /var/lib/glpi/files/_cron has been validated.
Write access to /var/lib/glpi/files has been validated.
Write access to /var/lib/glpi/files/_dumps has been validated.
Write access to /var/lib/glpi/files/_graphs has been validated.
Write access to /var/lib/glpi/files/_lock has been validated.
Write access to /var/lib/glpi/files/_pictures has been validated.
Write access to /var/lib/glpi/files/_plugins has been validated.
Write access to /var/lib/glpi/files/_rss has been validated.
Write access to /var/lib/glpi/files/_sessions has been validated.
Write access to /var/lib/glpi/files/_tmp has been validated.
Write access to /var/lib/glpi/files/_uploads has been validated.
SELinux configuration is OK.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /usr/share/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /usr/share/glpi
GLPI_CONFIG_DIR: /etc/glpi
GLPI_VAR_DIR: /var/lib/glpi/files
GLPI_LOG_DIR: /var/log/glpi
GLPI_SYSTEM_CRON: 1
GLPI_INSTALL_MODE: TARBALL to HFS
GLPI_MARKETPLACE_DIR: /usr/share/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_DOC_DIR: /var/lib/glpi/files
GLPI_CACHE_DIR: /var/lib/glpi/files/_cache
GLPI_CRON_DIR: /var/lib/glpi/files/_cron
GLPI_DUMP_DIR: /var/lib/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/lib/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/lib/glpi/files/_locales
GLPI_LOCK_DIR: /var/lib/glpi/files/_lock
GLPI_PICTURE_DIR: /var/lib/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/lib/glpi/files/_plugins
GLPI_RSS_DIR: /var/lib/glpi/files/_rss
GLPI_SESSION_DIR: /var/lib/glpi/files/_sessions
GLPI_TMP_DIR: /var/lib/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/lib/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/lib/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /usr/share/glpi/locales
GLPI_VERSION: 10.0.0-dev
GLPI_SCHEMA_VERSION: 10.0.0-dev@e0e0feeb52f1b9c723920ea3e0ae2ff8e02b981f
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_YEAR: 2021

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/usr/share/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.5.3 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/usr/share/glpi/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/usr/share/glpi/vendor/sabre/http/lib)
sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/usr/share/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/usr/share/glpi/vendor/symfony/console)
scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/usr/share/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/usr/share/glpi/vendor/ramsey/uuid/src)
psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src)
psr/cache in (/usr/share/glpi/vendor/psr/cache/src)
league/csv in (/usr/share/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/usr/share/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/usr/share/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/usr/share/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/usr/share/glpi/vendor/symfony/cache)
html2text/html2text in (/usr/share/glpi/vendor/html2text/html2text/src)
symfony/dom-crawler in (/usr/share/glpi/vendor/symfony/dom-crawler)
twig/twig in (/usr/share/glpi/vendor/twig/twig/src)
twig/string-extra in (/usr/share/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
phpCas version 1.4.0 in (/usr/share/pear)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 

</pre></details>

GLPI MariaDB Database build with :  CHARACTER SET utf8 COLLATE utf8_general_ci

Log files

</details><details><summary>glpi-agent.log debug Level 1 log file</summary><pre> 
[Thu Jan  6 11:02:28 2022][debug] Logger backend File initialized
[Thu Jan  6 11:02:28 2022][debug] GLPI Agent (1.1-git31840f5c)
[Thu Jan  6 11:02:28 2022][debug] Configuration directory: C:/Program Files/GLPI-Agent/etc
[Thu Jan  6 11:02:28 2022][debug] Data directory: C:/Program Files/GLPI-Agent/share
[Thu Jan  6 11:02:28 2022][debug] Storage directory: C:\Program Files\GLPI-Agent\var
[Thu Jan  6 11:02:28 2022][debug] Lib directory: C:/Program Files/GLPI-Agent/perl/agent
[Thu Jan  6 11:02:28 2022][debug] [target server0] Next server contact planned for Thu Jan  6 11:33:28 2022
[Thu Jan  6 11:02:28 2022][debug] Available tasks:
[Thu Jan  6 11:02:28 2022][debug] - Collect: 2.7
[Thu Jan  6 11:02:28 2022][debug] - Deploy: 2.9
[Thu Jan  6 11:02:28 2022][debug] - Inventory: 1.10
[Thu Jan  6 11:02:28 2022][debug] - RemoteInventory: 0.9
[Thu Jan  6 11:02:28 2022][debug] target server0: server https://glpi.__Server-Name__.com/front/inventory.php
[Thu Jan  6 11:02:28 2022][debug] Planned tasks for server0: Deploy,RemoteInventory,Collect,Inventory
[Thu Jan  6 11:02:28 2022][debug] Provided by Teclib Edition
[Thu Jan  6 11:02:28 2022][debug] Installer built on Sat Dec 25 02:17:49 2021 UTC
[Thu Jan  6 11:02:28 2022][debug] Built with Strawberry Perl 5.34.0
[Thu Jan  6 11:02:28 2022][debug] Built on github actions windows image for glpi-project/glpi-agent repository
[Thu Jan  6 11:02:28 2022][info] GLPI Agent service starting
[Thu Jan  6 11:02:28 2022][debug] Trusted target ip: ____Server-Name-IPv6___/128, Server-Name-IPv4, ::ffff:5240:7913/128
[Thu Jan  6 11:02:28 2022][debug] Trusted client ip: 127.0.0.1/32, ::ffff:700:1/128, ::1/128
[Thu Jan  6 11:02:28 2022][debug] [http server] Trying to load Inventory Server plugin
[Thu Jan  6 11:02:28 2022][debug] [inventory server plugin] Initializing Inventory v1.1 Server plugin...
[Thu Jan  6 11:02:28 2022][debug] [inventory server plugin] Loading Inventory Server plugin configuration from C:/Program Files/GLPI-Agent/etc/inventory-server-plugin.cfg
[Thu Jan  6 11:02:28 2022][debug] [target listener] Next server contact planned for Thu Jan  6 12:00:17 2022
[Thu Jan  6 11:02:28 2022][debug] [http server] HTTPD Inventory Server plugin loaded but disabled
[Thu Jan  6 11:02:28 2022][debug] [http server] Trying to load Proxy Server plugin
[Thu Jan  6 11:02:29 2022][debug] [proxy server plugin] Initializing Proxy v2.1 Server plugin...
[Thu Jan  6 11:02:29 2022][debug] [proxy server plugin] Loading Proxy Server plugin configuration from C:/Program Files/GLPI-Agent/etc/proxy-server-plugin.cfg
[Thu Jan  6 11:02:29 2022][debug] [http server] HTTPD Proxy Server plugin loaded but disabled
[Thu Jan  6 11:02:29 2022][debug] [http server] Trying to load SecondaryProxy Server plugin
[Thu Jan  6 11:02:29 2022][debug] [proxy2 server plugin] Initializing SecondaryProxy v1.1 Server plugin...
[Thu Jan  6 11:02:29 2022][debug] [proxy2 server plugin] Loading SecondaryProxy Server plugin configuration from C:/Program Files/GLPI-Agent/etc/proxy2-server-plugin.cfg
[Thu Jan  6 11:02:29 2022][debug] [http server] HTTPD SecondaryProxy Server plugin loaded but disabled
[Thu Jan  6 11:02:29 2022][debug] [http server] Trying to load SSL Server plugin
[Thu Jan  6 11:02:29 2022][debug] [ssl server plugin] Initializing SSL v1.0 Server plugin...
[Thu Jan  6 11:02:29 2022][debug] [ssl server plugin] Loading SSL Server plugin configuration from C:/Program Files/GLPI-Agent/etc/ssl-server-plugin.cfg
[Thu Jan  6 11:02:29 2022][debug] [http server] HTTPD SSL Server plugin loaded but disabled
[Thu Jan  6 11:02:29 2022][debug] [http server] Trying to load Test Server plugin
[Thu Jan  6 11:02:29 2022][debug] [server test plugin] Initializing Test v1.1-git31840f5c Server plugin...
[Thu Jan  6 11:02:29 2022][debug] [server test plugin] Loading Test Server plugin configuration from C:/Program Files/GLPI-Agent/etc/server-test-plugin.cfg
[Thu Jan  6 11:02:29 2022][debug] [http server] HTTPD Test Server plugin loaded but disabled
[Thu Jan  6 11:02:29 2022][debug] [http server] Trying to load ToolBox Server plugin
[Thu Jan  6 11:02:29 2022][debug] [toolbox plugin] Initializing ToolBox v1.0 Server plugin...
[Thu Jan  6 11:02:29 2022][debug] [toolbox plugin] Loading ToolBox Server plugin configuration from C:/Program Files/GLPI-Agent/etc/toolbox-plugin.cfg
[Thu Jan  6 11:02:29 2022][debug] [http server] HTTPD ToolBox Server plugin loaded but disabled
[Thu Jan  6 11:02:29 2022][info] [http server] HTTPD service started on port 62354
[Thu Jan  6 11:02:30 2022][debug] Agent memory usage before freeing memory: WSS=114667520 PFU=104742912
[Thu Jan  6 11:02:30 2022][info] GLPI Agent memory usage: WSS=3141632 PFU=104742912
[Thu Jan  6 11:02:30 2022][debug] Running in background mode
[Thu Jan  6 11:02:30 2022][info] target server0: server https://glpi.__Server-Name__.com/front/inventory.php
[Thu Jan  6 11:02:30 2022][debug] [http client] Using Compress::Zlib for compression
[Thu Jan  6 11:02:30 2022][info] sending prolog request to server0
[Thu Jan  6 11:02:31 2022][info] server0 answer shows it supports GLPI Agent protocol
[Thu Jan  6 11:02:31 2022][debug] new thread 3 to handle task Deploy
[Thu Jan  6 11:02:31 2022][info] running task Deploy
[Thu Jan  6 11:02:31 2022][error] [http client] Got empty response
[Thu Jan  6 11:02:31 2022][info] Deploy task not supported by server0
[Thu Jan  6 11:02:33 2022][debug] new thread 4 to handle task RemoteInventory
[Thu Jan  6 11:02:33 2022][debug] Remote inventory task execution disabled: no remote set
[Thu Jan  6 11:02:35 2022][debug] new thread 5 to handle task Collect
[Thu Jan  6 11:02:35 2022][info] running task Collect
[Thu Jan  6 11:02:35 2022][error] [http client] Got empty response
[Thu Jan  6 11:02:35 2022][info] Collect task not supported by server0
[Thu Jan  6 11:02:37 2022][debug] new thread 6 to handle task Inventory
[Thu Jan  6 11:02:37 2022][info] running task Inventory
[Thu Jan  6 11:02:37 2022][info] New inventory from rover-geek-2022-01-06-11-02-28 for server0
[Thu Jan  6 11:02:39 2022][debug] module GLPI::Agent::Task::Inventory::Win32::Bios disabled because of GLPI::Agent::Task::Inventory::Generic::Dmidecode::Bios
[Thu Jan  6 11:02:39 2022][debug] module GLPI::Agent::Task::Inventory::Win32::Memory disabled because of GLPI::Agent::Task::Inventory::Generic::Dmidecode
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::AccessLog
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Generic
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Batteries
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Databases
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode::Battery
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode::Bios
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode::Hardware
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Win32
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::Hardware
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Vmsystem
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode::Memory
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode::Ports
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode::Psu
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode::Slots
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Drives
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Firewall
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Networks
[Thu Jan  6 11:02:39 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::OS
[Thu Jan  6 11:02:44 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt
[Thu Jan  6 11:02:44 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt::AnyDesk
[Thu Jan  6 11:02:44 2022][debug] Found AnyDesk ID : #########
[Thu Jan  6 11:02:44 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::SSH
[Thu Jan  6 11:02:45 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Screen
[Thu Jan  6 11:02:45 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Softwares
[Thu Jan  6 11:02:45 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Storages
[Thu Jan  6 11:02:45 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Timezone
[Thu Jan  6 11:02:45 2022][debug] Using DateTime::TimeZone to get the timezone name
[Thu Jan  6 11:02:46 2022][debug] Running GLPI::Agent::Task::Inventory::Provider
[Thu Jan  6 11:02:46 2022][debug] Running GLPI::Agent::Task::Inventory::Virtualization
[Thu Jan  6 11:02:46 2022][debug] Running GLPI::Agent::Task::Inventory::Virtualization::HyperV
[Thu Jan  6 11:02:46 2022][debug] Win32::OLE ERROR: Invalid namespace
[Thu Jan  6 11:02:46 2022][debug] Win32::OLE ERROR: Invalid namespace
[Thu Jan  6 11:02:46 2022][debug] Win32::OLE ERROR: Invalid namespace
[Thu Jan  6 11:02:46 2022][debug] Win32::OLE ERROR: Invalid namespace
[Thu Jan  6 11:02:46 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::CPU
[Thu Jan  6 11:02:47 2022][debug] Running GLPI::Agent::Task::Inventory::Virtualization::Wsl
[Thu Jan  6 11:02:47 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::AntiVirus
[Thu Jan  6 11:02:47 2022][debug] Found Windows Defender (state=0x61100)
[Thu Jan  6 11:02:47 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::Chassis
[Thu Jan  6 11:02:47 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::Controllers
[Thu Jan  6 11:02:48 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::Drives
[Thu Jan  6 11:02:48 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::Environment
[Thu Jan  6 11:02:48 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::Firewall
[Thu Jan  6 11:02:48 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::Inputs
[Thu Jan  6 11:02:48 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::License
[Thu Jan  6 11:03:03 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::Modems
[Thu Jan  6 11:03:03 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::Networks
[Thu Jan  6 11:03:03 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::OS
[Thu Jan  6 11:03:03 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::Ports
[Thu Jan  6 11:03:03 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::Printers
[Thu Jan  6 11:03:03 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::Slots
[Thu Jan  6 11:03:03 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::Softwares
[Thu Jan  6 11:03:03 2022][debug] 'scan-profiles' configuration parameter disabled, ignoring software in user profiles
[Thu Jan  6 11:03:06 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::Sounds
[Thu Jan  6 11:03:06 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::Storages
[Thu Jan  6 11:03:06 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::USB
[Thu Jan  6 11:03:07 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::Users
[Thu Jan  6 11:03:08 2022][debug] Running GLPI::Agent::Task::Inventory::Win32::Videos
[Thu Jan  6 11:03:08 2022][debug] last state file 'C:\Program Files\GLPI-Agent\var/https..__glpi.__Server-Name__.com_front_inventory.php/last_state.json' doesn't exist
[Thu Jan  6 11:03:08 2022][debug] Section ANTIVIRUS has changed since last inventory
[Thu Jan  6 11:03:08 2022][debug] Section BIOS has changed since last inventory
[Thu Jan  6 11:03:08 2022][debug] Section CONTROLLERS has changed since last inventory
[Thu Jan  6 11:03:08 2022][debug] Section CPUS has changed since last inventory
[Thu Jan  6 11:03:08 2022][debug] Section DRIVES has changed since last inventory
[Thu Jan  6 11:03:08 2022][debug] Section HARDWARE has changed since last inventory
[Thu Jan  6 11:03:08 2022][debug] Section INPUTS has changed since last inventory
[Thu Jan  6 11:03:08 2022][debug] Section MEMORIES has changed since last inventory
[Thu Jan  6 11:03:08 2022][debug] Section MONITORS has changed since last inventory
[Thu Jan  6 11:03:08 2022][debug] Section NETWORKS has changed since last inventory
[Thu Jan  6 11:03:08 2022][debug] Section OPERATINGSYSTEM has changed since last inventory
[Thu Jan  6 11:03:08 2022][debug] Section PRINTERS has changed since last inventory
[Thu Jan  6 11:03:08 2022][debug] Section SOFTWARES has changed since last inventory
[Thu Jan  6 11:03:08 2022][debug] Section SOUNDS has changed since last inventory
[Thu Jan  6 11:03:08 2022][debug] Section STORAGES has changed since last inventory
[Thu Jan  6 11:03:08 2022][debug] Section VIDEOS has changed since last inventory
[Thu Jan  6 11:03:08 2022][debug] [http client] 7ADBF182: Using Compress::Zlib for compression
[Thu Jan  6 11:03:14 2022][debug] target server0: init event for Deploy task
[Thu Jan  6 11:03:14 2022][debug] [target server0] New storage maintenance event on deploy task
[Thu Jan  6 11:03:15 2022][debug] target server0: init event for RemoteInventory task
[Thu Jan  6 11:03:16 2022][debug] target server0: init event for Collect task
[Thu Jan  6 11:03:17 2022][debug] target server0: init event for Inventory task
</pre></details>

</details><details><summary>GLPI php-errors.log</summary><pre> 
[2022-01-06 11:02:31] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: Mode has not been set in /usr/share/glpi/src/Agent/Communication/AbstractRequest.php at line 433
  Backtrace :
  front/inventory.php:72                             Glpi\Agent\Communication\AbstractRequest->getResponse()

[2022-01-06 11:02:35] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: Mode has not been set in /usr/share/glpi/src/Agent/Communication/AbstractRequest.php at line 433
  Backtrace :
  front/inventory.php:72                             Glpi\Agent\Communication\AbstractRequest->getResponse()
</pre></details>

### Expected behavior

The problem is the same with manual agent inventory, from an administrator elevated PowerShell terminal, even with an active code page 65001 (UTF-8).

Texts should be displayed in UTF-8 with the correct diacritics

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.0-beta, development release (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

**Comment by homebrewtainy** [comment]
I also found this log for the same inventory period!

</details><details><summary>GLPI sql-errors.log</summary><pre> 
[2022-01-06 11:03:10] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/src/DBmysql.php line 352
  *** MySQL query error:
  SQL: INSERT INTO `glpi_devicefirmwares` (`date`, `version`, `manufacturers_id`, `designation`, `devicefirmwaretypes_id`, `date_creation`, `date_mod`) VALUES ('2021-16-08', 'GL703GM.314', '2', 'American Megatrends Inc. BIOS', '1', '2022-01-06 11:03:08', '2022-01-06 11:03:08')
  Error: Incorrect date value: '2021-16-08' for column `glpi_db`.`glpi_devicefirmwares`.`date` at row 1
  Backtrace :
  src/DBmysql.php:1180
  src/CommonDBTM.php:652                             DBmysql->insert()
  src/CommonDBTM.php:1242                            CommonDBTM->addToDB()
  src/CommonDevice.php:482                           CommonDBTM->add()
  src/Inventory/Asset/Device.php:113                 CommonDevice->import()
  src/Inventory/Asset/Bios.php:85                    Glpi\Inventory\Asset\Device->handle()
  src/Inventory/Asset/MainAsset.php:751              Glpi\Inventory\Asset\Bios->handle()
  src/Inventory/Asset/MainAsset.php:672              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:954                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1496                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1583                        Rule->process()
  src/Inventory/Asset/MainAsset.php:515              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:674                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:324                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:318                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:83                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:292    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:212    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:57                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
</pre></details>

**Comment by Jagor** [comment]
Hi! On latest night build GLPI-Agent v1.1-gitf5824389 I have a problem with russian encoding. This is a file in `glpi/files/_inventories/computer/0`

![image](https://user-images.githubusercontent.com/7967670/149138618-c11bf579-e730-43c0-84bf-12e955248bac.png)

`glpi-inventory --partial software >software.json` makes correct file:
![image](https://user-images.githubusercontent.com/7967670/149155238-529a911a-6590-4bad-bbee-589b9553e1f9.png)

**Comment by g-bougard** [comment]
Hi @Jagor 
yes I'm aware of the problem. When running from the console, the JSON should be encoded in the console expected code page so you're seeing the really expected string.

**Comment by g-bougard** [comment]
Hi @homebrewtainy @Jagor 

can you test with [latest GLPI-Agent nightly build](https://nightly.glpi-project.org/glpi-agent/) as 2559b0b should probably fix this problem ?

**Comment by Badkempachi** [comment]
Hi, GLPI-Agent v1.1-git3042142e fixes Cyrillic rendering issue, thanks.

**Comment by Badkempachi** [comment]
> Hi @homebrewtainy @Jagor
> 
> can you test with [latest GLPI-Agent nightly build](https://nightly.glpi-project.org/glpi-agent/) as [2559b0b](https://github.com/glpi-project/glpi-agent/commit/2559b0b652098f48a434d55e618fcaf91e7bf19b) should probably fix this problem ?

Hi, GLPI-Agent v1.1-git3042142e fixes Cyrillic rendering issue, thanks.

**Comment by homebrewtainy** [comment]
> Hi @homebrewtainy @Jagor
> 
> can you test with [latest GLPI-Agent nightly build](https://nightly.glpi-project.org/glpi-agent/) as [2559b0b](https://github.com/glpi-project/glpi-agent/commit/2559b0b652098f48a434d55e618fcaf91e7bf19b) should probably fix this problem ?

Hello / Bonsoir @g-bougard,

GLPI 10 master.72d9190 + GLPI-Agent-1.1-git3042142e-x64 work fine with french rendering issue too, " Merci beaucoup :-) "

**Comment by g-bougard** [comment]
I'm closing the issue as I released today [GLPI-Agent v1.1](https://github.com/glpi-project/glpi-agent/releases/tag/1.1).
