### ISSUE TITLE
RPM package of glpi-agent doesn't depends on perl-Sys-Hostname but it is required

### ISSUE THREAD

**Issue by mightyspiky** [glpi-project/glpi-agent#446]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

After I upgraded one of my hosts from Oracle Linux 8 to Oracle Linux 9, I had to reinstall glpi-agent but, even then, it stopped updating the inventory correctly. I then tried to launch it manually at the console and I had no output, even with "--debug" and "--no-fork" flags. Then, I wiped the content of /var/lib/glpi-agent and ran the agent another time after that and here's what I got:

```
[root@server ~]# glpi-agent --no-fork --debug --force
Execution failure:.
Undefined subroutine &Sys::Hostname::hostname called at /usr/share/glpi-agent/lib/GLPI/Agent/Tools/Hostname.pm line 50.
[root@server ~]#
```

I then proceeded to install package "perl-Sys-Hostname" and, after that, it was good and automatic inventory was working again. I've verified the dependancies of glpi-agent and, indeed, that perl package isn't listed. I think it should be, shouldn't it?

### To reproduce

1. Install glpi-agent rpm on a compatible Linux distribution
2. Run glpi-agent with "--no-fork", "--debug" and "--force" flags.

### Expected behavior

No error in the output and inventory in GLPI should have been updated.

### Operating system

Linux

### GLPI Agent version

Other (See additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

GLPI Agent version: 1.5
GLPI version: 10.0.8

**Comment by g-bougard** [comment]
Hi @mightyspiky 

thank you for your report.

I checked and you're right: for some reason the packaging build didn't include that dependency for 1.5 version where it included it for 1.4.

I updated the spec so the next nightly build should still include that dependency.
