### ISSUE TITLE
No support for cgroup 2 resources limits for LXC containers

### ISSUE THREAD

**Issue by mightyspiky** [glpi-project/glpi-agent#447]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

In Oracle Linux 9 (and probably any RHEL 9 based distro), cgroup 2 are used instead of v1. It means that the parameters in an LXC configuration must change, that is, for example:

```
lxc.cgroup.cpuset.cpus = 2,3
lxc.cgroup.memory.limit_in_bytes = 4096M
```

must be redefined to:

```
lxc.cgroup2.cpuset.cpus = 2,3
lxc.cgroup2.memory.max = 4096M
```

It seems that glpi-agent doesn't take that into account as I have no more value for memory limit for each of my containers in GLPI and the value for the number of CPU is always the total available on my physical host even if I specify a lower value in my configurations. I still have an Oracle Linux 8 server and that one get its LXC containers inventoried correctly.

### To reproduce

1. Run glpi-agent from a RHEL 9 based physical host which have LXC containers configured correctly (with cgroup 2 parameters if needed).
2. See in GLPI that there's no value for memory limit in an LXC container (in Virtualisation section) and that value for CPU limit is always the max available even if configured differently in LXC.

### Expected behavior

I would expect the values defined by "lxc.cgroup2.cpuset.cpus" and "lxc.cgroup2.memory.max" in LXC configurations to be taken into account for the memory and CPU limits of LXC containers of a given host which are showed in the "Virtualisation" section of GLPI web interface.

### Operating system

Linux

### GLPI Agent version

Other (See additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

GLPI Agent version: 1.5
GLPI version: 10.0.8

**Comment by g-bougard** [comment]
Hi @mightyspiky 

thank you for your report.

Next nightly build should support cgroup2 resources.
