### ISSUE TITLE
Not detecting physical size of NVMe Disk

### ISSUE THREAD

**Issue by nchizhov** [glpi-project/glpi-agent#449]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Not detecting storage size of NVMe disk on notebook - show always size - 0 on Windows 10

### To reproduce

1. Notebook: Acer TravelMate P (Model: TPM214-52-581J)
2. Operation System: Windows 10 Pro (64-bit)
3. See disk size of WDC PC SN520 SDAPNUW-512G-1014 in json-file

Local json-file of inventory in attachment.
[23072023.zip](https://github.com/glpi-project/glpi-agent/files/12138418/23072023.zip)

### Expected behavior

Should show correct storage size

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

### Additional context

GLPI Agent Night Build: gitf35d5912

**Comment by g-bougard** [comment]
Hi @nchizhov 

thank you for your report. Can you first share the output of the following command run from an administrative console for this computer ?
```
wmic /namespace:\\root\microsoft\windows\storage path MSFT_PhysicalDisk get /format:list
```
and:
```
wmic path win32_diskdrive get /format:list
```

**Comment by nchizhov** [comment]
> wmic /namespace:\\root\microsoft\windows\storage path MSFT_PhysicalDisk get /format:list

In archive attachment as wmic.txt


> wmic path win32_diskdrive get /format:list

In archive attachment as wmic2.txt 
[wmic.zip](https://github.com/glpi-project/glpi-agent/files/12147830/wmic.zip)

**Comment by g-bougard** [comment]
Hi @nchizhov 

thank you.

I don't see any problem with that wmi datas. The size is visible as expected.

There still can be an issue with the hdparm output which can be used to complete the device datas. So can you from an administrative console do the following ?
 * change directory to the glpi-agent installation folder
 * then change directory to the `perl\bin` subfolder from there
 * run the following command and share their outputs:
   * `hdparm -I /dev/hda`
   * `hdparm -I /dev/hdb`

**Comment by nchizhov** [comment]
Hello.

In attachment requested data
[hdparm.zip](https://github.com/glpi-project/glpi-agent/files/12162857/hdparm.zip)

**Comment by g-bougard** [comment]
Thank you,

here is the problem: on hdb, the size is null and so this should not be mandatory as we still detect the right size with wmi.

**Comment by nchizhov** [comment]
Thank you for answer.

Will be it fixed in future releases?

**Comment by g-bougard** [comment]
Of course, I'm currently testing the patch.

**Comment by g-bougard** [comment]
I pushed the patch so it will be integrated in next nightly build: https://nightly.glpi-project.org/glpi-agent/
So can you plan a test with it tomorrow ?
Thank you again for the sharing of all the helpful outputs.

**Comment by nchizhov** [comment]
Thank you 
> So can you plan a test with it tomorrow ?

Yes, planning.
Will answer here after testing

**Comment by nchizhov** [comment]
Hello.

All working excellent. Thank you.
