### ISSUE TITLE
Toolbox Usage

### ISSUE THREAD

**Issue by rafaelse** [glpi-project/glpi-agent#45]
### Documentation

Yes, I read it

### Solution search

Not applicable

### Is your help request related to a problem?

I would like to try out the new GLPI Agent's features regarding network discovery and scan. However, when I access the Toolbox interface, there are no such options as to set up these tasks (see image below). I searched the documentation, but could not find anything related.

I'd also like to know if I can set up remote inventories (`glpi-remote`) using this plugin.

![image](https://user-images.githubusercontent.com/1613703/148529638-2eb2b1fd-6e77-4a53-8e0e-f53335b9ec6e.png)

### Expected behavior

I was hoping to see at least the menus shown in the images of this article: https://glpi-project.org/glpi-10-native-inventory/

Actually, I guess there should be even more menus to provide the features I mentioned above.

### Actions you've considered

At first, I believed the options were limited because I hadn't set the `--server` option in the agent, but even after doing so, I didn't get the expected behavior.

### Additional context

These are settings I am using:

```
glpi-agent --daemon  --color --httpd-trust=0.0.0.0/0 --server https://myglpi.com/front/inventory.php --no-fork --debug
```
PS: I am able to send local inventory to GLPI.

Toolbox settings:
```
# By default, a plugin is always disabled unless "disabled" is set to "no" or "0".
# You can uncomment the following line or set it in included configuration file
# at the end of this configuration
disabled = no

# Set base url matching for API
url_path = /toolbox
```

**Comment by g-bougard** [comment]
Hi @rafaelse 

Sorry for the lack of documentation, this is on my TODO list.

Indeed the default toolbox configuration is limited to limit misuse of the plugin. You need to edit the `etc/toolbox.yaml` file to enable the wanted edition features. In that configuration you can set `updating_support` to `1` and after you'll be able to edit the configuration online via the gear at the top right of the page. There you'll just have to enable the wanted menu in the `Navigation bar` section.

Toolbox still needs to be improved: it needs authentication before we can provide it with a full interface enabled.

**Comment by rafaelse** [comment]
Hi @g-bougard,

Thanks for the reply, I'll be watching for the documentation.
I tried applying the setting you suggested, but it did not cause any effect. Here are my configurations:

- `/etc/glpi-agent/toolbox.yaml`:

```
updating_support: 1
```

- Toolbox configuration page:

![image](https://user-images.githubusercontent.com/1613703/148546948-0fb60f05-7a3f-4b13-b067-7126eeb14fdb.png)

Can you, please, tell what I did wrong?

**Comment by g-bougard** [comment]
did you restart the service/agent ?

**Comment by rafaelse** [comment]
Yes, I did. Actually, I'm running the agent in a container, so I recreated the container with the new configuration.

**Comment by g-bougard** [comment]
Sorry, my mistake, here is how your `toolbox.yaml` should look like to enable online configuration:
```
configuration:
  updating_support: yes
```

**Comment by rafaelse** [comment]
It worked now, I was able to activate the remaining menus. Thanks a lot!
I'll try the new features and see how they interact with GLPI 10's native inventory support.

**Comment by g-bougard** [comment]
Nice, then I'm closing the issue but feel free to reopen if you have any new question.

**Comment by steph461** [comment]
Nice , I was looking for this information :)
