### ISSUE TITLE
Unrecognized Anti Virus on Hyper-V Virtual Systems [BUG]

### ISSUE THREAD

**Issue by erique-souza** [glpi-project/glpi-agent#455]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Still not applicable

### Describe the bug

Hello everyone, the Anti Virus field is not recognized in GLPI or GLPI-Agent in Hyper-V Virtual Systems, the same anti virus agent was installed in physical machines, and GLPI-Agent and GLPI were able to identify it without any problem that it is an anti virus, there is no difference between system policies, GLPI-Agent agent 1.5 installed, Operating system is different of course because it is a virtualized windows 2019 server, but it was also tested in Virtualized Ubuntu, and even in an ubuntu I didn't bring the anti virus.

I got the 2 complete logs from 1 virtual computer and another from a physical computer, both inventoried with GLPI-Agent 1.5, I'm attaching the logs.

I had no way to test it, but I suspect that VMWare Type machines also have the same problem of not identifying the anti-virus, I say this because I saw some reports in other pots in the community about this.

Removed logs to keep information confidential.

### To reproduce

Having a common anti virus in the operating system (avast, avira, avg, etc..)

Installation of a GLPI-Agent 1.5 on a virtual server by Hyper-V windows or linux (tested on ubuntu)

Validate in GLPI if the anti virus was identified in the specific anti virus tab.

It is possible to do the same test on any physical machine, the result is usually positive, taking the correct inventory.

The software is always identified in the software listing, the real problem is the classification as anti virus in the inventoried computer.

### Expected behavior

anti virus inventory

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.0.6

**Comment by g-bougard** [comment]
Hi @erique-souza 

this is a well-known problem on windows server OS: they don't provide access to installed anti-virus. This is a choice made by Microsoft for all the "server" flavour. And so antivirus inventory can't just be supported by glpi-agent.

I know, that's a shame, but you should complain against operating system editor. Sorry for that.

**Comment by erique-souza** [comment]
> Hi @erique-souza
> 
> this is a well-known problem on windows server OS: they don't provide access to installed anti-virus. This is a choice made by Microsoft for all the "server" flavour. And so antivirus inventory can't just be supported by glpi-agent.
> 
> I know, that's a shame, but you should complain against operating system editor. Sorry for that.

I understand, I would like to make a suggestion for GLPI in these situations: The possibility of creating an anti virus assignment rule if you have any software installed, in these cases you would assign software that has already been inventoried or linked manually in the anti virus tab .

In any case, thanks for the feedback.

**Comment by g-bougard** [comment]
I think you should make this suggestion to https://glpi.userecho.com/
