### ISSUE TITLE
[AGENT-GLPI] Uncaught Exception TypeError: Agent::requestAgent

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi-agent#46]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

I wanted to test the upgrade of a computer station on my GLPI 10 test version but I have a bug if I want to force the GLPI inventory to the computer station

I go back the first time the computer with the agent glpi see 

But if I want to force an inventory or see the status of the agent from GLPI 10.0. The arrows turn loop

Does this functionality work with the Beta version of GLPI10 with AGENT_GLPI ?

### To reproduce

1.Go to Computer
2. Go click inventor
![Sans titre](https://user-images.githubusercontent.com/68054991/148550816-1d7f7825-9c74-4897-bd63-995dd75273a2.jpg)

### Expected behavior

For test 
http://localhost:62354/ ==> Glpi OK , information is OK 

GLPI contact inventory is ko with error

### Log

```shell
[2022-01-07 14:24:17] glpiphplog.WARNING:   *** PHP Warning (2): Undefined variable $response in /var/www/html/glpi10beta/src/Agent.php at line 584
  Backtrace :
  src/Agent.php:608                                  Agent->requestAgent()
  ajax/agent.php:54                                  Agent->requestInventory()
  
[2022-01-07 14:24:17] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Agent::requestAgent(): Return value must be of type GuzzleHttp\Psr7\Response, null returned in /var/www/html/glpi10beta/src/Agent.php at line 584
  Backtrace :
  src/Agent.php:608                                  Agent->requestAgent()
  ajax/agent.php:54                                  Agent->requestInventory()
```
### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.0-beta

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

**Comment by g-bougard** [comment]
Hi @steph461 

you still opened this issue in [glpi #10203](https://github.com/glpi-project/glpi/issues/10203).

We are aware of the problem and it is really on server-side. This is why I'm closing it here. Your glpi issue will be updated as soon as we will handle it ;-)
