### ISSUE TITLE
glpi agent 1.5 : can't uncompress content starting with: 

### ISSUE THREAD

**Issue by adrianofante** [glpi-project/glpi-agent#462]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Still not applicable

### Describe the bug

Our entire park was working normally with GLPI version 10.0.6, agent version 1.4 and plugin version 1.2.
After updating to GLPI 10.0.9, updating the agent to 1.5 and updating the inventory plugin to 1.2.3 the inventory no longer works.

We tried unchecking the option in the JSON format agent installation, and the error remains.

If you downgrade to agent 1.4 the inventory is collected successfully.

On windows or linux we have the error below in the Agent log:
"[error] [http client] can't uncompress content starting with: ﻿x«VJ(ȬJ,Ɍϓ²R2Sґ*.I,)- r somewhat ¶,"

```
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <DEVICEID>SKPMWWS011.ad.xxxxx.com.br-2022-12-27-10-58-21</DEVICEID>
  <QUERY>PROLOG</QUERY>
  <TOKEN>12345678</TOKEN>
</REQUEST>
[Tue Aug 15 08:10:44 2023][debug2] format: Zlib
[Tue Aug 15 08:10:44 2023][error] [http client] can't uncompress content starting with: ﻿x«VJ­(ȬJ,Ɍϓ²R2Sґ*.I,)-r򳕪¶,
 
[Tue Aug 15 08:10:44 2023][error] No supported answer from server at https://suporte.xxxx.com.br/
[Tue Aug 15 08:10:44 2023][info] target server0: next run: Tue Aug 15 08:15:44 2023 - https://suporte.xxxx.com.br/
[Tue Aug 15 08:10:44 2023][debug] Agent memory usage before freeing memory: WSS=24268800 PFU=127868928
[Tue Aug 15 08:10:44 2023][info] GLPI Agent memory usage: WSS=3203072 PFU=127868928
[Tue Aug 15 08:15:44 2023][info] target server0: server https://suporte.xxxx.com.br/
[Tue Aug 15 08:15:44 2023][debug2] [http client] Using Compress::Zlib for compression
[Tue Aug 15 08:15:44 2023][info] sending prolog request to server0
[Tue Aug 15 08:15:44 2023][debug2] [http client] sending message:
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
```

### To reproduce

1. Install GLPI version 10.0.6
2. Install and activate the GLPI Inventory Plugin version 1.2
3. Configure glpi agent version 1.4 on some windows computer
4. Update GLPI to the latest version of GLPI 10.0.9
5. Update inventory plugin to latest version 1.2.3
6. Update the agent to version 1.5

### Expected behavior

Inventory should work without the error

### Operating system

Linux

### GLPI Agent version

1.4, Nightly build (git version in additional context below), Other (See additional context below)

### GLPI version

10.0.x (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

GLPI version
10.0.9

Tested versions of the GLPI Inventory plugin:
1.2.3
1.2.2
1.2.1

Windows Agent Versions Tested:
1.4 - OK, working!
1.5 - DOESN'T WORK!
1.6GLPI-Agent v1.6-git99a04c90 nightly - DOESN'T WORK

**Comment by waaalex** [comment]
SAme issue here #15423

**Comment by g-bougard** [comment]
Hi @adrianofante 

have you tried to set [no-compression](https://glpi-agent.readthedocs.io/en/latest/configuration.html#no-compression) to `1` ?

But this still may be a SSL support issue. You can debug SSL by running the inventory from an administrative console with debug2 logging level enabled.

**Comment by g-bougard** [comment]
Also can you tell us if you're using an antivirus which intercept SSL communications on the client ? If yes, or just in case, to test it, can you try to submit an inventory without using SSL ?

**Comment by adrianofante** [comment]
Even with the option checked in the configuration file it still doesn't work.

It's the same problem here:

https://github.com/glpi-project/glpi/issues/15423

**Comment by g-bougard** [comment]
Hi @adrianofante 
this looks to be the same but on the glpi issue we can see there are some spaces inserted in the answer. It seems not the case for you... unless you removed them when you copied the journal part.

**Comment by g-bougard** [comment]
As proposed on the glpi issue by stonebuzz, can you try to disable temporarily all installed plugins (only keeping glpiinventory one if required) to see if one is making troubles ?

**Comment by waaalex** [comment]
Same trouble with plugins disabled.

**Comment by stonebuzz** [comment]
@waaalex @adrianofante 
Please can you read this (maybe a solution)

https://github.com/glpi-project/glpi/issues/15423#issuecomment-1698620225

**Comment by adrianofante** [comment]
@stonebuzz I have the same problem reported, but in my INC folder I don't have the files reported.

Could it be that something was missing from my GLPI installation?
Everything else works perfectly, just that inventory issue that stopped after updating agents 1.5.

![image](https://github.com/glpi-project/glpi-agent/assets/36228506/dc8e2a42-028e-4911-b2ba-727998f6593c)

**Comment by g-bougard** [comment]
Hi @adrianofante 

it seems this kind of problem could be a consequence of this commit: e6c5c9788

Since this update, uncompressing methods are shared for all supported protocol and are also optimized. Before, XML formatted answers, the agent was using a regexp to extract the compressed data starting from few header bytes. The fact is the datas may still have been corrupted by spaces or EOL in front of the expected data (to me this still remains a GLPI issue). And this is the real problem, we don't have to expect such corrupted datas.

In the glpi-project/glpi#15423 issue, `inc/downstream.php` was identified, but in your case maybe another file may be involved. Check all possible configuration file: no space, no line return should be present before `<?php` text and none should be "closed" with a `?>`.

Anyway, can you extract the lines containing `can't uncompress content starting with` and just after from your agent log to have it as it is in a dedicated file and attach it here ? I want to try to uncompress it manually to see what could be wrong with it.

Also, as I said before, setting `no-compression` to `1` on agent-side should work-around the problem. Maybe you forgot to restart the service before testing ?

**Comment by g-bougard** [comment]
@adrianofante testing it, it seems no-compression work-around may not... working. But so can you share the agent log in that case too ?

**Comment by g-bougard** [comment]
Hi there,

I'm closing this issue without user required feedback.

Feel free to update or even reopen if you have more to say.
