### ISSUE TITLE
Quantity of CPUs is twice what it should be

### ISSUE THREAD

**Issue by mightyspiky** [glpi-project/glpi-agent#464]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

The quantity of CPUs for each of the LXC containers of my Oracle Linux 8 host (cgroups v1) showed in virtualisation section in GLPI is twice of what it should be. For example, one of my LXC container has in its config:

`lxc.cgroup.cpuset.cpus = 2,3`

... and GLPI shows 4 CPUs though it should be 2.

Another one has the following:

`lxc.cgroup.cpuset.cpus = 0-2`

... and GLPI shows 6 CPUs though it should be 3.

I don't have that problem with my Oracle Linux 9 host (cgroups v2). Also, I didn't have the problem with glpi-agent 1.5 (stable version).

### To reproduce

1. Inventory through glpi-agent a RHEL 8 (or RHEL 8 clone) that has LXC containers

### Expected behavior

The number of CPUs should match what is in the LXC config of the containers.

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Other (See additional context below)

### Additional context

GLPI Agent version: 1.6-git99a04c90
GLPI version: 10.0.8

**Comment by g-bougard** [comment]
Hi @mightyspiky 
I guess we indeed can get `lxc.cgroup.cpuset.cpus` & `lxc.cgroup2.cpuset.cpus` at the same time so this double the counting.
Can you try applying the following patch ?
```diff
diff --git a/lib/GLPI/Agent/Task/Inventory/Virtualization/Lxc.pm b/lib/GLPI/Agent/Task/Inventory/Virtualization/Lxc.pm
--- a/lib/GLPI/Agent/Task/Inventory/Virtualization/Lxc.pm
+++ b/lib/GLPI/Agent/Task/Inventory/Virtualization/Lxc.pm
@@ -108,6 +108,7 @@ sub  _getVirtualMachine {
 
         if ($key eq 'lxc.cgroup.cpuset.cpus' || $key eq 'lxc.cgroup2.cpuset.cpus') {
             ###eg: lxc.cgroup.cpuset.cpus = 0,3-5,7,2,1
+            $container->{VCPU} = 0;
             foreach my $cpu ( split( /,/, $val ) ){
                 if ( $cpu =~ /(\d+)-(\d+)/ ){
                     $container->{VCPU} += $2 - $1 + 1;
```

**Comment by mightyspiky** [comment]
It works fine with this patch, thanks. Will this be in a future nightly build?

**Comment by g-bougard** [comment]
Yes, I was just waiting your confirmation ;-)
