### ISSUE TITLE
Error when change or update glpi installation

### ISSUE THREAD

**Issue by lexcorp** [glpi-project/glpi-agent#465]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

I recently installed the glpi version 1.5 agent without problems, however it was necessary to update the server url, so I reinstalled the agent, however when trying to reinstall I receive the following message.

Service (glpi-agent) could not be installed. Verify that you have sufficient privileges to install system services:

![image](https://github.com/glpi-project/glpi-agent/assets/5751288/76f6e73c-82c3-4bca-bbf9-552a8f75d6e0)

The user with which I do the installation is administrator.

### To reproduce

1. Install glpi agent 1.5
2. Reinstall glpi agent 1.5
3. change url server
4. All other options without change
5. When installer try to stop or start services I get this error:

Service (glpi-agent) could not be installed. Verify that you have sufficient privileges to install system services

![image](https://github.com/glpi-project/glpi-agent/assets/5751288/00625ef8-1eb9-4b94-8431-be0e796f1246)

### Expected behavior

Installer is reinstall without errors.

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Other (See additional context below)

### Additional context

GLPI Agent 1.5

**Comment by g-bougard** [comment]
Hi @lexcorp 

sorry but your `To reproduce` details are not really clear. For example, what do you mean by "Reinstall glpi agent 1.5" or "change url server" ? These steps can only be with few steps but in many ways, so you'll have to details how you did that.

**Comment by g-bougard** [comment]
Closing without answer.
Feel free to comment or even re-open if you have some clues to share.
