### ISSUE TITLE
Wrong soft installation date format

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi-agent#47]
Installation date for software may be wrong formatted, see above example.

SOFTWARE IN THE LIST THAT CAUSE THE ISSUE:
`        <SOFTWARES>
      <ARCH>x86_64</ARCH>
      <FROM>registry</FROM>
      <GUID>AutoCAD 2021 - English</GUID>
      <INSTALLDATE>10/30/2021</INSTALLDATE>
      <NAME>Autodesk AutoCAD 2021 - English</NAME>
      <PUBLISHER>Autodesk</PUBLISHER>
      <SYSTEM_CATEGORY>application</SYSTEM_CATEGORY>
      <UNINSTALL_STRING>XXXXXXXXXXXXXXXXXXXXX</UNINSTALL_STRING>
      <VERSION>24.0.47.0</VERSION>
    </SOFTWARES>`

_Originally posted by @JTrotta in https://github.com/glpi-project/glpi/issues/10294#issuecomment-1008754025_

**Comment by g-bougard** [comment]
Hi @JTrotta
can you try the next glpi-agent nightly build tomorrow ?

**Comment by JTrotta** [comment]
Even later...

**Comment by g-bougard** [comment]
Or even sooner ;-)
As you still can try the build from [this GH Actions run](https://github.com/glpi-project/glpi-agent/actions/runs/1678309290): get the Windows-Build archive and extract the MSI installer from it.

**Comment by JTrotta** [comment]
It works!
