### ISSUE TITLE
GLPI-Agent 1.5 does not start

### ISSUE THREAD

**Issue by romulloalves** [glpi-project/glpi-agent#473]
### Bug reporting acknowledgment

Yes, I read it, Not applicable

### Professional support

None

### Describe the bug

I installed the agent on my server with Fedora 38, but it always shows an error when starting. I have other computers with the same version of Fedora 38 and they work fine.

### To reproduce

glpi-agent.service: Failed with result 'exit-code'.
glpi-agent.service: Main process exited, code=exited, status=1/FAILURE
Undefined subroutine &Sys::Hostname::hostname called at /usr/share/glpi-agent/lib/GLPI/Agent/Tools/Hostname.pm line 50.
Execution failure:.
Started glpi-agent.service - GLPI agent.
glpi-agent.service: Failed with result 'exit-code'.
glpi-agent.service: Main process exited, code=exited, status=1/FAILURE
Undefined subroutine &Sys::Hostname::hostname called at /usr/share/glpi-agent/lib/GLPI/Agent/Tools/Hostname.pm line 50.
Execution failure:.
Started glpi-agent.service - GLPI agent.

### Expected behavior

GLPI-Agent does not start

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

**Comment by g-bougard** [comment]
Hi @romulloalves 

that problem still have been reported in #446.

That bug is actually fixed in [nightly builds](https://nightly.glpi-project.org/glpi-agent/).
