### ISSUE TITLE
Debian11 1.5-1 pkg / local inventory --html error / empty $self->{datadir}

### ISSUE THREAD

**Issue by lwafflard** [glpi-project/glpi-agent#475]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

After configuring, xml/json local inventory working great but html not
```
 glpi-agent -l /tmp/inventory.html --html 
.
.
.
Use of uninitialized value in concatenation (.) or string at /usr/share/glpi-agent/lib/GLPI/Agent/Inventory.pm line 672.
[error] Can't call method "fill_in" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Inventory.pm line 684.
```

`$self->{datadir}` seems to be empty, a workaround is to replace the variable with the full path in ` /usr/share/glpi-agent/lib/GLPI/Agent/Inventory.pm line 672.`

```
        my $template = Text::Template->new(
#            TYPE => 'FILE', SOURCE => "$self->{datadir}/html/inventory.tpl"
            TYPE => 'FILE', SOURCE => "/usr/share/glpi-agent/html/inventory.tpl"
        );
```

### To reproduce

1. install agent via deb file [glpi-agent_1.5-1_all.deb](https://github.com/glpi-project/glpi-agent/releases/download/1.5/glpi-agent_1.5-1_all.deb)
2. configure agent
3. confirm local inventory  => ok
4. confirm local inventory HTML => error

### Expected behavior

use local inventory with `--html` without error

### Operating system

Linux

### GLPI Agent version

Other (See additional context below)

### GLPI version

Not applicable

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

### Additional context

Debian 11, install via deb file [glpi-agent_1.5-1_all.deb](https://github.com/glpi-project/glpi-agent/releases/download/1.5/glpi-agent_1.5-1_all.deb), glpi server independent

```
# glpi-agent --version
GLPI Agent (1.5-1)
Built by Debian
Source time: 2023-06-21 13:59
```

**Comment by g-bougard** [comment]
Hi @lwafflard 

thank you for your report.

Anyway this problem has still been fixed by f35d59127.

You can try to install a [nightly build](https://nightly.glpi-project.org/glpi-agent/) to verify it's actually fixed in your case.
