### ISSUE TITLE
Users inventory to be linked with Azure AD users in GLPI

### ISSUE THREAD

**Issue by kouloubike** [glpi-project/glpi-agent#476]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Good morning ,
There is a problem when retrieving the user on enroller machines with intune and in Azure AD.
The user who goes back is in the following form firstnamelastname@azureAD.
It is therefore no longer possible to automatically link an ordonater to a user because the domain does not correspond
To have the correct upn you must execute the following command in cmd
whoami /upn.

### To reproduce

Enroll machines in intune

### Expected behavior

recovery of the correct UPN to have the automatic assignment of the equipment to the user

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.1.0

**Comment by g-bougard** [comment]
Hi @kouloubike 

please can you try with latest GLPI-Agent version: 1.5 ?

Then for this version, can you share the output of the following command run from an administrative console & from the agent installation folder ?
```
glpi-inventory --partial user
```
You can of course anonymize the content and remove any sensible data, like the license key number.

The problem with the `whoami /upn` command is this won't probably work as the service is run from a local system account.

I really think the problem is elsewhere. And please upgrade your GLPI version.

**Comment by g-bougard** [comment]
The real problem is to know if the inventory provides the information. If it does, the problem remains GLPI is not linking users as it may look for the wrong information and this may still be a Azure AD connection configuration issue.

**Comment by kouloubike** [comment]
[image: image.png]

**Comment by kouloubike** [comment]
Thank you for your prompt response
I am in Glpi-Agent 1.5
But this option was not available in the form, which is why I put version 1.4.

Regarding the version of GLPI we have an instance on your server

![image](https://github.com/glpi-project/glpi-agent/assets/65355530/fd5546e7-18a2-4576-b8e7-5307e7b96906)

**Comment by g-bougard** [comment]
So "AzureAD" is what the agent detects as "domain". That's the first time people reported such a problem. Is that an enrolling feature to set the computer domain this way (maybe documented somewhere) ? Can it be an enrolling misconfiguration ?

Can you run the following command ?
```
wmic path Win32_ComputerSystem get /format:list
```
Then do you see a "UserName" field and/or "Name" field ? Do you see "AzureAD" in that fields ?

Can you also tell which windows version is installed on the computer ?

Finally, as your concern is really the user/computer link in GLPI, can you check if you can update your AD authentication configuration to achieve your goal ?

**Comment by kouloubike** [comment]
Hi
For me it's not really a problem, it's rather a legacy of the detection of the user by the agent (the problem is the same with fusioninventory).
To put you in context, we are in full azure AD (no on-premise or hybrid)

As for the version of Windows it is either Windows 10 or Windows 11 10:2 p.m.

It is indeed possible to make the modification by hand.
On a small machine name this is possible but we will have a fleet close to 500 PCs.


![image](https://github.com/glpi-project/glpi-agent/assets/65355530/b7cd4db7-676f-4f97-8105-2ec1ac41b984)

**Comment by g-bougard** [comment]
Anyway, that's not up to the agent if "AzureAD" is set as user domain on the system. My guess is still something can be done in GLPI authentication configuration to figure out that problem.

I may add a test to search for the really expected domain if we find "AzuzeAD" as domain, but I don't know how to retrieve it (as I said `whoami /upn` won't give the expected result when agent is running as a service).

**Comment by articW** [comment]
I'm facing the exactly same problem, with the same scenario of @kouloubike. I think it may be a new bug because there are few companies who relies ONLY on Azure AD. But it's our case.  

Scenario
UPN: john.doe@domain.com 
Display Name: John Doe
Agent version: 1.5. The machine is **AAD Joined**, the inventory is populated as follows

**Alternate username:** JohnDoe@AzureAD
**User:** (blank)
**Domains Tab:** WORKGROUP

**Comment by articW** [comment]
I'm facing the exactly same problem, with the same scenario of @kouloubike. I think it may be a new bug because there are few companies who relies ONLY on Azure AD. But it's our case. (I don't have any on-prem directory, like AD. So, LDAP is not an option for me)

Scenario
**UPN:** john.doe@mydomain.com
**Display Name:** John Mister Doe
**Agent version:** 1.5
**Join Type:** AAD Joined
**Fresh installed Windows**

Populated fields in GLPI
**Alternate username:** JohnMisterDoe@AzureAD
**User:** (blank)
**Domains Tab:** WORKGROUP

> glpi-inventory --partial user

(XXXXXXXXXXX for anonymized data) 

```c
C:\Program Files\GLPI-Agent>glpi-inventory --partial user
[info] New partial inventory from DESKTOP-EHRK1QO-2023-09-09-15-55-00 for local0
{
   "action": "inventory",
   "content": {
      "bios": {
         "assettag": "618737",
         "bdate": "2023-02-01",
         "bmanufacturer": "LENOVO",
         "bversion": "XXXXXXXXXXX",
         "mmanufacturer": "LENOVO",
         "mmodel": "20TBS57S00",
         "msn": "XXXXXXXXXXX",
         "skunumber": "LENOVO_MT_20TB_BU_Think_FM_ThinkPad E14 Gen 2",
         "smanufacturer": "LENOVO",
         "smodel": "ThinkPad E14 Gen 2",
         "ssn": "XXXXXXXXXXX"
      },
      "hardware": {
         "chassis_type": "Notebook",
         "lastloggeduser": "JohnMisterDoe",
         "memory": 16082,
         "name": "DESKTOP-EHRK1QO",
         "uuid": "XXXXXXXXXXX",
         "vmsystem": "Physical",
         "winlang": "1046",
         "winprodid": "XXXXXXXXXXX",
         "winprodkey": "XXXXXXXXXXX",
         "workgroup": "WORKGROUP"
      },
      "users": [
         {
            "domain": "AzureAD",
            "login": "JohnMisterDoe"
         }
      ],
      "versionclient": "GLPI-Inventory_v1.5"
   },
   "deviceid": "DESKTOP-EHRK1QO-2023-09-09-15-55-00",
   "itemtype": "Computer",
   "partial": true
}
[info] Inventory dumped on standard output
``` 

> wmic path Win32_ComputerSystem get /format:list

```c
AdminPasswordStatus=0
AutomaticManagedPagefile=TRUE
AutomaticResetBootOption=TRUE
AutomaticResetCapability=TRUE
BootOptionOnLimit=
BootOptionOnWatchDog=
BootROMSupported=TRUE
BootStatus=
BootupState=Normal boot
Caption=DESKTOP-EHRK1QO
ChassisBootupState=2
ChassisSKUNumber=
CreationClassName=Win32_ComputerSystem
CurrentTimeZone=-180
DaylightInEffect=
Description=AT/AT COMPATIBLE
DNSHostName=DESKTOP-EHRK1QO
Domain=WORKGROUP
DomainRole=0
EnableDaylightSavingsTime=TRUE
FrontPanelResetStatus=2
HypervisorPresent=FALSE
InfraredSupported=FALSE
InitialLoadInfo=
InstallDate=
KeyboardPasswordStatus=2
LastLoadInfo=
Manufacturer=LENOVO
Model=20TBS57S00
Name=DESKTOP-EHRK1QO
NameFormat=
NetworkServerModeEnabled=TRUE
NumberOfLogicalProcessors=8
NumberOfProcessors=1
OEMLogoBitmap=
OEMStringArray=
PartOfDomain=FALSE
PauseAfterReset=-1
PCSystemType=2
PCSystemTypeEx=2
PowerManagementCapabilities=
PowerManagementSupported=
PowerOnPasswordStatus=0
PowerState=0
PowerSupplyState=2
PrimaryOwnerContact=
PrimaryOwnerName=
ResetCapability=1
ResetCount=-1
ResetLimit=-1
Roles={"LM_Workstation","LM_Server","NT"}
Status=OK
SupportContactDescription=
SystemFamily=ThinkPad E14 Gen 2
SystemSKUNumber=LENOVO_MT_20TB_BU_Think_FM_ThinkPad E14 Gen 2
SystemStartupDelay=
SystemStartupOptions=
SystemStartupSetting=
SystemType=x64-based PC
ThermalState=2
TotalPhysicalMemory=16863318016
UserName=AzureAD\JohnMisterDoe
WakeUpType=6
Workgroup=WORKGROUP
``` 

> Can you also tell which windows version is installed on the computer ?

Windows 11 Pro/Enterprise 22H2

> Finally, as your concern is really the user/computer link in GLPI, can you check if you can update your AD authentication configuration to achieve your goal ?

I can change manually the User or Alternate User fields, but it breaks the cycle of automation where the device is automatically linked to a user, and can open tickets about the assets linked to it. It's not a problem for a few devices, but as the number grows, more annoying it gets. 

> I may add a test to search for the really expected domain if we find "AzuzeAD" as domain, but I don't know how to retrieve it (as I said whoami /upn won't give the expected result when agent is running as a service).

In AAD Joined devices, the are some registry keys where the UPN is a value, like
`Computador\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon`
LastUsedUsername or DefaultUsername

Or `Computador\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\CloudDomainJoin\JoinInfo`
UserEmail

Maybe that could help? 

Could you tell me where does the agent collects the Alternate Username and User fields?

Thanks for your attention!

**Comment by g-bougard** [comment]
Can you check from a PowerShell administrative console what gives the following command (adjusting "JohnMisterDoe" to the real user of course):
```
Get-AzureADUser -Filter "DisplayName eq 'JohnMisterDoe'"
```
I'm not sure this is the right filter to use. You can check the [official Get-AzureADUser page](https://learn.microsoft.com/en-us/powershell/module/azuread/get-azureaduser) if you can find a better choice.

My concern here is to find a way to get the expected AzureAD user from the "login" found when we see "AzureAD" as "domain".

I'm not even sure this command could be available on all computers.

I'm also curious, if AzureAD commands are available, if the following command gives the expected domain and only one:
```
Get-AzureADDomain
```

You can also make some tests to check how the agent should report the user:
1. export users in a file with `glpi-inventory --partial user >users.json`
2. edit `users.json` and update the "domain" in the "users" section to match the expected one
3. import manually that `users.json` file using `glpi-injector` or directly from the Administrator/Inventory page in GLPI
4. check if the link has been established

You can also make other tries editing the users section and removing the `domain` and/or setting the `login` with the UPN. Can you report what's the required format ?

**Comment by kouloubike** [comment]
I believe that the solution does not lie on the Azure Ad side but rather in the registry.
I found the following link
https://stackoverflow.com/questions/43443349/how-to-get-an-azure-active-directory-username-in-windows-powershell

The problem is that there are Sids so it’s definitely not easy.

With the order
whoami /user
I have the SID and the user logged in

and I found this user the SID in the cache

Do you know how the connected user is retrieved by the agent?

**Comment by g-bougard** [comment]
Hi,

I would like to thank you @kouloubike as he permitted me to access real datas so I was able to find an update for this problem.

Despite the agent will try to inventory last logged user UPN, this doesn't guarantee the user will be linked to his computer in glpi.

Then you may still have to create one or more "Business Rules for Assets" to parse the login agent found and generate an action to match the expected GLPI login. For these rules, you should not use the condition "Automatic Inventory is Yes" as this doesn't work (at least in GLPI v10.0.9) or you should apply glpi-project/glpi#14768 on your GLPI to make this condition working.

Next nightly build will include this fix.
