### ISSUE TITLE
Registry key not found during monitor inventory

### ISSUE THREAD

**Issue by RobertoMarcelino** [glpi-project/glpi-agent#479]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

The version of GLPI-Agent v1.6-gitd15f1e96 nightly build is generating the following message in the log:

[Sun Sep 10 13:00:09 2023][error] Can't open HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Enum/DISPLAY\MS\4&29906b6&0&UID2121852_0 key: Invalid identifier
[Sun Sep 10 13:00:09 2023][error] Can't open HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Enum/DISPLAY\MS\4&29906b6&0&UID2121852_0 key: Invalid identifier

We verified the non-existence of the key that the agent is looking for.

On Windows 11 Pro the correct existing key is this one:

![image](https://github.com/glpi-project/glpi-agent/assets/57845086/055c5b7e-7b7b-425c-9e22-fbf18f54793c)

### To reproduce

N/A

### Expected behavior

N/A

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.9

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.2.3

### Additional context

GLPI-Agent v1.6-gitd15f1e96 nightly build

**Comment by g-bougard** [comment]
Hi @RobertoMarcelino 

this may be a new problem with windows 11.

As indeed the registry path is computed from property values found on WMI objects, can you share the output of the following 2 commands run from an administrative console ?
```
wmic /namespace:\\root\wmi path WMIMonitorConnectionParams get /format:list
wmic path Win32_DesktopMonitor get /format:list
```
Of course, you should run these commands on the faulty computer.

And can you also share an export of the following registry key ?
```
HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Enum/DISPLAY\MS_0001
```

Also can you tell how the monitor is connected to the computer ?

**Comment by RobertoMarcelino** [comment]
```
C:\Users\carmon>wmic /namespace:\\root\wmi path WMIMonitorConnectionParams get /format:list

Active=TRUE
InstanceName=DISPLAY\MS_0001\4&amp;29906b6&amp;0&amp;UID2121852_0
VideoOutputTechnology=5

Active=TRUE
InstanceName=DISPLAY\Default_Monitor\1&amp;330d05b7&amp;0&amp;UID256_0
VideoOutputTechnology=4294967295


C:\Users\carmon>wmic path Win32_DesktopMonitor get /format:list

Availability=3
Bandwidth=
Caption=Monitor Genérico não PnP
ConfigManagerErrorCode=0
ConfigManagerUserConfig=FALSE
CreationClassName=Win32_DesktopMonitor
Description=Monitor Genérico não PnP
DeviceID=DesktopMonitor1
DisplayType=
ErrorCleared=
ErrorDescription=
InstallDate=
IsLocked=
LastErrorCode=
MonitorManufacturer=(Tipos de monitor padrão)
MonitorType=Monitor Genérico não PnP
Name=Monitor Genérico não PnP
PixelsPerXLogicalInch=96
PixelsPerYLogicalInch=96
PNPDeviceID=DISPLAY\DEFAULT_MONITOR\1&amp;330D05B7&amp;0&amp;UID256
PowerManagementCapabilities=
PowerManagementSupported=
ScreenHeight=1440
ScreenWidth=2560
Status=OK
StatusInfo=
SystemCreationClassName=Win32_ComputerSystem
SystemName=SVR-123-RDS

Availability=3
Bandwidth=
Caption=Tela Plana Digital (640x480 60Hz)
ConfigManagerErrorCode=0
ConfigManagerUserConfig=FALSE
CreationClassName=Win32_DesktopMonitor
Description=Tela Plana Digital (640x480 60Hz)
DeviceID=DesktopMonitor2
DisplayType=
ErrorCleared=
ErrorDescription=
InstallDate=
IsLocked=
LastErrorCode=
MonitorManufacturer=(Tipos de monitor padrão)
MonitorType=Tela Plana Digital (640x480 60Hz)
Name=Tela Plana Digital (640x480 60Hz)
PixelsPerXLogicalInch=96
PixelsPerYLogicalInch=96
PNPDeviceID=DISPLAY\MS_0001\4&amp;29906B6&amp;0&amp;UID2121852
PowerManagementCapabilities=
PowerManagementSupported=
ScreenHeight=1080
ScreenWidth=1920
Status=OK
StatusInfo=
SystemCreationClassName=Win32_ComputerSystem
SystemName=SVR-123-RDS
```

**Comment by g-bougard** [comment]
Hi @RobertoMarcelino 

thank you for the sharing.

I see know there's an issue with a clean up done on the "InstanceName" values for the first output. We were cleaning any underscore followed by numbers. But we really need to do that only at the end of the value.

I'm pushing a fix so next nightly build should no more report the registry key not found error.
