### ISSUE TITLE
Deploy task copy action is no more working in v1.5, but it was in v1.4

### ISSUE THREAD

**Issue by lp73** [glpi-project/glpi-agent#480]
### Bug reporting acknowledgment

Not applicable

### Professional support

None

### Describe the bug

Depuis le passage de agent-glpi 1.4 à 1.5, l'action copier dans la gestion de deploiement de glpiinventory ne fonctionne plus.

### To reproduce

Depuis déployer / Gestion de paquet
Créer un paquet Test copie fichier
Action sur le paquet
type Copier
Provenant de  ANNUAIRE EQUIPE JDL.pdf
vers C:\Users\Default\AppData\Local\Temp\

Créer une tache avec pour cible Test copie fichier
acteur = PC de test

sauvegarder, activer, forcer le démarrage, si besoin restart selected jobs.
executer un inventaire du PC

Mais le fichier n'est pas copier !

Après réinstallation de l'agent 1.4, le même script fonctionne.

### Expected behavior

dans les logs, j'ai 
2023-09-12 12:08:12 | Ok | job successfully completed
-- | -- | --
2023-09-12 12:08:12 | En cours d'exécution | Actions:action #1, processing success
2023-09-12 12:08:12 | En cours d'exécution | Préparation des fichiers:success
2023-09-12 12:08:12 | En cours d'exécution | Téléchargement de fichiers:success
2023-09-12 12:08:12 | En cours d'exécution | Téléchargement de fichiers:ANNUAIRE EQUIPE JDL.pdf already downloaded
2023-09-12 12:08:11 | En cours d'exécution | Téléchargement de fichiers:downloading files
2023-09-12 12:08:11 | En cours d'exécution | Audits:all checks are ok
2023-09-12 12:08:11 | En cours d'exécution | Audits:starting
2023-09-12 12:06:33 | Préparé |  

cependant le fichier n'est pas copié !

j'ai réalisé plusieurs tentative avec des cotes ou des quillements sans plus de succès.

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.9

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.2.3

### Additional context

les action commandes avec des commandes powershell fonctionne.

**Comment by g-bougard** [comment]
Hi @lp73 

thank you for your issue submission, anyway, and even if we are french and our english is far from perfect, please use english language so the community can be involved.

In the GLPI-Agent v1.5 case, can you enable debug2 and share the log part related to Deploy task run ?

I will try to reproduce anyway.

**Comment by g-bougard** [comment]
I'm not able to reproduce: my file is copied as expected. Maybe you have an issue in your task configuration. Checking the agent log may help you so find what could be wrong.

On my side, I didn't make the copy of the file toward the same folder than you, but toward a `C:\Temp` folder a created.

**Comment by g-bougard** [comment]
Closing without feedback.
