### ISSUE TITLE
glpi-agent is intermittently appearing and disappearing

### ISSUE THREAD

**Issue by walterdasilva** [glpi-project/glpi-agent#482]
### Bug reporting acknowledgment

Not applicable

### Professional support

I still have but want a public following to keep the community aware

### Describe the bug

On HOME/ADMINISTRATION/INVENTORY/AGENT  glpi-agent is intermittently appearing and disappearing.
with this actor on task as missing too. 

### To reproduce

1. Deploy glpi-agent
2. start inventory
3. go to Home/Administration/Inventory/Agent e wait to agent show up
4. time-to-time return to page and check random agent are missing
5. time-to-time glpi-agent showing up again

### Expected behavior

stop this behavior 

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.9

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.2.3

**Comment by g-bougard** [comment]
Hi @walterdasilva 

you're describing a glpi server issue, not a glpi-agent one.

As you seem to have a professional support, please contact them.
