### ISSUE TITLE
Computer description not displayed in inventory

### ISSUE THREAD

**Issue by buggzbeny** [glpi-project/glpi-agent#486]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Hello,

We used Fusion Inventory on Glpi 9.x.x and there was computer description which was displayed in "plugin computer system commentary" from registry key :

my $description = getRegistryValue(path => 'HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Services/lanmanserver/Parameters/srvcomment'); 

Now we use GLPI 10.x and Glpi Agent 1.5 and this information is not available on the server even if this is part of inventory in hardware.pm

 C:\Users\administrateur>"C:\Program Files\GLPI-Agent\glpi-inventory.bat" --partial hardware
[info] New partial inventory from PC-TEAM-LBU.louis-barthou.lyc-2023-09-18-16-30-27 for local0
{
   "action": "inventory",
   "content": {
      "bios": {
         "bdate": "2014-04-01",
         "bmanufacturer": "SeaBIOS",
         "bversion": "rel-1.16.1-0-g3208b098f51a-prebuilt.qemu.org",
         "smanufacturer": "QEMU",
         "smodel": "Standard PC (i440FX + PIIX, 1996)"
      },
      "hardware": {
         "chassis_type": "Other",
         **_"description": "salle-test",_**
         "memory": 6143,
         "name": "xxxxxx",
         "uuid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
         "vmsystem": "QEMU",
         "winlang": "1036",
         "winowner": "xxxxxxxxxxxxxx",
         "winprodid": "00331-20020-00000-AA044",
         "workgroup": "workgroup.local"
      },
      "versionclient": "GLPI-Inventory_v1.5"
   },
   "deviceid": "xxxxxxxxxxxxxxxxxxxxx-2023-09-18-16-30-27",
   "itemtype": "Computer",
   "partial": true
}
[info] Inventory dumped on standard output

Is it possible to show this information on GLPI server ?

regards

### To reproduce

Inventory task with Glpi Agent

### Expected behavior

Have a solution to display this information

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.x (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.2.3

**Comment by g-bougard** [comment]
Hi @buggzbeny 

I was telling you in #484 to open an issue on [GLPI project](https://github.com/glpi-project/glpi), not here as there's no problem agent-side.

**Comment by buggzbeny** [comment]
soory ... done on glpi project !

Merci
