### ISSUE TITLE
Can't get import of Dell's S4128T-ON switch

### ISSUE THREAD

**Issue by renanredel** [glpi-project/glpi-agent#487]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

GLPI Agent: 1.5
GLPI Server 10.0.9
OS: Windows Server 2019 Datacenter

I'm trying to make the inventory of some of Dell's S4128T-ON.

When a make the inventory manually, its generate the xml file which contains all the information about the switch.
If I try to inject this file to GLPI using glpi-injector, its return to me this error: 

`glpi-injector -v -f swtorsede.xml --url https://glpi.domain.com.br/
`
```
Loading swtorsede.xml...ERROR: 400 Bad Request, JSON does not validate. Violations:
Required property missing: type, data: {"contact":"Contact Support","firmware":"10.5.2.3","ips":["192.168.1.1","192.168.2.1","192.168.3.1","192.168.4.1","192.168.5.1"],"location":"United States","mac":"f0:d4:e&nbsp;(...)
These elements were not sent:
swtorsede.xml
```

In the XML file, contains some information about the switch. If I remove the columns below, I can to upload the data to GLPI.

```
...
      <INFO>
        <COMMENTS>Dell EMC Networking OS10 Enterprise.
Copyright (c) 1999-2021 by Dell Inc. All Rights Reserved.
System Description: OS10 Enterprise.
OS Version: 10.5.2.3.
System Type: S4128T-ON</COMMENTS>
        <CONTACT>Contact Support</CONTACT>
        <FIRMWARE>10.5.2.3</FIRMWARE>
        <ID>0</ID>
        <IPS>
          <IP>192.168.1.1</IP>
          <IP>192.168.2.1</IP>
          <IP>192.168.3.1</IP>
          <IP>192.168.4.1</IP>
          <IP>192.168.5.1</IP>
        </IPS>
        <LOCATION>United States</LOCATION>
        <MAC>f0:d4:XX:XX:64:XX</MAC>
        <MANUFACTURER>Dell</MANUFACTURER>
        <MEMORY>3</MEMORY>
        <NAME>hostname-dell</NAME>
        <RAM>3904</RAM>
        <SERIAL>TW094J8XXXXXXXXXXXX</SERIAL>
        <UPTIME>3 days, 22:03:46.96</UPTIME>
      </INFO>
...
```

### To reproduce

1. Run glpi-inventory on a Dell S4128T-On switch;
2. Try to upload the file to GLPI.

### Expected behavior

glpi-inventory should correctly upload the XML to the GLPI.

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.9

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.2.3

**Comment by renanredel** [comment]
[swtorsede.zip](https://github.com/glpi-project/glpi-agent/files/12666505/swtorsede.zip)

**Comment by g-bougard** [comment]
Hi @renanredel 

thank you for your report.

Even if I can reproduce the case by injecting manually your XML, this doesn't tell us why the `<TYPE>NETWORKING</TYPE>` node is missing under the `<INFO/>` one. For that we need to reproduce the XML generation itself from a proper snmpwalk.

So can you generate a [snmpwalk output following the documentation](https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output) and share it ? To not disclose it publicly, you can share it privately by sending it to me to `gbougard <at> teclib <dot> com`.

**Comment by renanredel** [comment]
Hi @g-bougard ,

When I tried to run the snmpwalk to theses switchs, I get the following error: 

```
%Failed to get value of SNMP variable. Timeout.
Total: 67
```

I also tried to a different switch model in the same subnet, and its works (no firewall block). 
I think this could be a problem with the firmware from the switch. Any suggestions?

**Comment by g-bougard** [comment]
On "timeout", this maybe means you don't use the right credentials. Otherwise, check the device configuration and logs. And finally if you're sure you're doing right, contact the manufacturer support.

**Comment by renanredel** [comment]
Ok.

Thank you @g-bougard !
