### ISSUE TITLE
GLPI Agent for Android

### ISSUE THREAD

**Issue by tulhaum** [glpi-project/glpi-agent#490]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

GLPI Agent on Android 13 doesn´t run in background, neither startup from system boot, nor execute scheduled task.

### To reproduce

1. Install GLPI Agent from Play Store on Android 13
2. Set up list servers
3. Mark to "Startup from system boot" in Advanced Settings
4. Enable "automatic inventory" and define the "frequency" in Schedule Task.
5. Restart the smartphone. GLPI Agent won´t startup automaticaly. If open manually, doesn´t run in background and every inventory only runs manually.

### Expected behavior

GLPI Agent for Android should run in background, send the inventory at the scheduled time and startup from boot system.

### Operating system

Other (See additional context below)

### GLPI Agent version

1.3

### GLPI version

10.0.9

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.2.3

**Comment by g-bougard** [comment]
Can you answer this issue not related to perl glpi-agent @skita ?
