### ISSUE TITLE
Windows installer does not allow to reset registry correctly

### ISSUE THREAD

**Issue by keguira** [glpi-project/glpi-agent#493]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

I've raised a Q&A so i'll sum up things here

I'm trying to upgrade my parc with agent 1.5
Previously we set `ssl-fingerprint` to validate certificate which is now useless thanks to this new version.

When I try to upgrade the agent, it is impossible to reset the `ssl-fingerprint` registry value because empty values are not accepted in command line (`SSL_FINGERPRINT=` or `SSL_FINGERPRINT=''` will create a weird behavior)

Also the `REINSTALL=feat_AGENT` does keep the registered `ssl-fingerprint` such as I have to update manually this value or uninstall completely the agent to clean it

### To reproduce

Pre-requisite : install an agent in version 1.4 and specify a `ssl-fingerprint`.

**Use-case 1** : update to 1.5.  Clear `ssl-fingerprint` **by passing a "no value"**
```
MsiExec.exe /quiet /i GLPI-Agent-1.5-x64.msi ADDLOCAL=feat_COLLECT SSL_FINGERPRINT=  
```
Result : 
- Agent in 1.5
- `ssl-fingerprint` : `CURRENTDIRECTORY="C:\[mycurrentpathofexecution]"`

Issues : 
1. `ssl-fingerprint` is not emptied but gain the value of the current folder

**Use-case 2** : update to 1.5. Trying to clear `ssl-fingerprint` **by passing empty value**
```
MsiExec.exe /quiet /i GLPI-Agent-1.5-x64.msi ADDLOCAL=feat_COLLECT SSL_FINGERPRINT=''
```
Result : 

- Agent in 1.5
- `ssl-fingerprint` : `CURRENTDIRECTORY="C:\[mycurrentpathofexecution]"`

Issues : 
1. `ssl-fingerprint` is not emptied but gain the value of the current folder

**Use-case 3** : update to 1.5. Trying to change server for `https://bar.example.com` and clear `ssl-fingerprint` by using feature `REINSTALL=feat_AGENT` and specify no ssl-fingerprint as the empty/no value is not usable

```
MsiExec.exe /quiet /i GLPI-Agent-1.5-x64.msi ADDLOCAL=feat_COLLECT SERVER='https://bar.example.com'  REINSTALL=feat_AGENT
```
Result : 

- Agent in 1.5
- `server` : `'https://bar.example.com'`
- `ssl-fingerprint` : `sha:....`

Issues : 
1. `ssl-fingerprint` is not emptied but keep old value.

### Expected behavior

- the `SSL_FINGERPRINT` argument should autorize an empty value (`SSL_FINGERPRINT=''` or `SSL_FINGERPRINT=""` or `SSL_FINGERPRINT=` in general way such as no weird value should be registered
- Documentation should clarify how `REINSTALL=feat_AGENT` work and what it does : it states that it's in the case of a reconfiguration but the current behavior, for the list of autorized arguments, does not seem to do more things than a run without it. In my opinion, if i try to reinstall, it should not keep the existing configuration or at least should not keep configurations managed by the command line arguments.

### Operating system

Windows

### GLPI Agent version

1.5

### GLPI version

10.0.9

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.2.3

### Additional context

The initial discussion is here : https://github.com/glpi-project/glpi-agent/discussions/489
It was to search for a solution in the case i want to upgrade my agent and change configuration at the same time.

**Comment by g-bougard** [comment]
Hello @keguira 

I'm trying to modify the MSI installer so setting `CONFIG=reset` on command line should permit to not use any still set configuration in registry.

**Comment by g-bougard** [comment]
My first attempt seems to work. But it has by now a wrong side-effect: it prevents default values to be set where it should. Need more tests.

**Comment by g-bougard** [comment]
Hi @keguira 

if you want to test the solution, get the [lastest nightly build](https://nightly.glpi-project.org/glpi-agent/) and try to install it using `CONFIG=reset` on the installer commandline along with the requires other options (`SERVER`, etc...). If, for example, a value was set in registry for ssl-fingerprint, it should not be kept, of course unless you also specify it on the commandline.

**Comment by keguira** [comment]
> Hi @keguira
> 
> if you want to test the solution, get the [lastest nightly build](https://nightly.glpi-project.org/glpi-agent/) and try to install it using `CONFIG=reset` on the installer commandline along with the requires other options (`SERVER`, etc...). If, for example, a value was set in registry for ssl-fingerprint, it should not be kept, of course unless you also specify it on the commandline.

I'm going to test that today or tomorrow.
Thank you

**Comment by keguira** [comment]
Hello, sorry for coming back so late : it works. My config has been reset. A user can use this argument during an upgrade or a config patch.
As it reset **all** conf, it should be pointed in the changelog : when using this argument, a user have to also apply previous "things" to modify other configurations (like `conf-reload`, `scan-profiles` etc ...)
