### ISSUE TITLE
Incorrect Video Memory Size

### ISSUE THREAD

**Issue by nchizhov** [glpi-project/glpi-agent#494]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

When get inventory in xml-format sometimes field VIDEOS->MEMORY is negative, but if we get inventory in json format - field videos->memory not exists

### To reproduce

1. Get `glpi-inventory.bat` for xml
2. Get `glpi-inventory.bat --json` for json

### Expected behavior

Correct memory size or remove MEMORY field from xml output if video memory size is incorrect.

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Not applicable

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

### Additional context

Nightly build version:  1.6-git91eadcaf

I attached xml and json inventory from same computer
[inventory.zip](https://github.com/glpi-project/glpi-agent/files/12708224/inventory.zip)

**Comment by g-bougard** [comment]
Hi @nchizhov 

can you share the output of the following command ?
```
wmic path Win32_VideoController get /format:list
```
Also can you share an export of the following registry key tree which contains video cards relates datas:
```
HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Control/Class/{4d36e968-e325-11ce-bfc1-08002be10318}
```
And finally can you tell what correct memory size you really expect ?

**Comment by nchizhov** [comment]
1. Output of wmic and exported part of reg in attach
2. Correct memory size is always random, because video is integrated
[data.zip](https://github.com/glpi-project/glpi-agent/files/12713435/data.zip)

**Comment by g-bougard** [comment]
Hi @nchizhov 
the datas you shared didn't permit me to reproduce the case, but I tried to handle the memory size I can see in your registry export. My guess actually is there's maybe a bug in WMI Win32_VideoController reported AdapterRAM, maybe a perl library issue or a windows issue. The value from registry should be correctly evaluated.
Next nightly build will include that update.
