### ISSUE TITLE
[Feature Request] GLPI-Agent for VMware Photon OS

### ISSUE THREAD

**Issue by undefinedid** [glpi-project/glpi-agent#497]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Hello,

It would be great if the GLPI-Agent supports VMware Photon OS as operating system inventoriable.

Photon OS uses yum-compatible package manager called _tdnf_, for [Tiny Dandified Yum](https://github.com/vmware/tdnf).
Tdnf implements a subset of the _dnf_ commands as listed in the [dnf guide](http://dnf.readthedocs.org/en/latest/).

Currently, when trying to install the noarch RPM package, some dependencies are unsatisfiable:

```
root [ ~ ]# rpm -i glpi-agent-1.5-1.noarch.rpm 
error: Failed dependencies:
        perl(Cpanel::JSON::XS) is needed by glpi-agent-1.5-1.noarch
        perl(Data::UUID) is needed by glpi-agent-1.5-1.noarch
        perl(DateTime) is needed by glpi-agent-1.5-1.noarch
        perl(File::Which) is needed by glpi-agent-1.5-1.noarch
        perl(HTTP::Cookies) is needed by glpi-agent-1.5-1.noarch
        perl(HTTP::Daemon) is needed by glpi-agent-1.5-1.noarch
        perl(HTTP::Headers) is needed by glpi-agent-1.5-1.noarch
        perl(HTTP::Request) is needed by glpi-agent-1.5-1.noarch
        perl(HTTP::Status) is needed by glpi-agent-1.5-1.noarch
        perl(IO::Socket::SSL) is needed by glpi-agent-1.5-1.noarch
        perl(LWP) is needed by glpi-agent-1.5-1.noarch
        perl(LWP::Protocol::https) is needed by glpi-agent-1.5-1.noarch
        perl(LWP::UserAgent) is needed by glpi-agent-1.5-1.noarch
        perl(Net::HTTPS) is needed by glpi-agent-1.5-1.noarch
        perl(Net::IP) is needed by glpi-agent-1.5-1.noarch
        perl(Net::SSLeay) is needed by glpi-agent-1.5-1.noarch
        perl(Parallel::ForkManager) is needed by glpi-agent-1.5-1.noarch
        perl(Proc::Daemon) is needed by glpi-agent-1.5-1.noarch
        perl(Socket::GetAddrInfo) is needed by glpi-agent-1.5-1.noarch
        perl(Text::Template) is needed by glpi-agent-1.5-1.noarch
        perl(UNIVERSAL::require) is needed by glpi-agent-1.5-1.noarch
        perl(URI) is needed by glpi-agent-1.5-1.noarch
        perl(URI::Escape) is needed by glpi-agent-1.5-1.noarch
        perl(XML::LibXML) is needed by glpi-agent-1.5-1.noarch
        perl(YAML::Tiny) is needed by glpi-agent-1.5-1.noarch
```
        
Via the Installer based on perl, it fails at the OS detection:
        
```
root [ ~ ]# perl glpi-agent-1.5-linux-installer.pl 
Unsupported Welcome to Photon 5.0 (\m) - Kernel \r (\l) linux distribution (Unknown Linux distribution:5.0)
```

Thank you for your help and consideration.

### To reproduce

Trying to install GLPI-Agent on Photon OS, via installer-script or via package manager.

### Expected behavior

A compatible GLPI-Agent for Photon OS.

### Operating system

Linux

### GLPI Agent version

Other (See additional context below)

### GLPI version

Not applicable

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

**Comment by g-bougard** [comment]
Hi @undefinedid 

thank you for your submission.

Do you know if Photon OS provides a repository (or few) where the required dependencies could be retrieved ? If such repository exists, we can update the perl installer to support install their definitions.

Do you know if Photon OS supports snap packaging ? If yes, can you try it ? See https://glpi-agent.readthedocs.io/en/latest/installation/index.html#snap

You may also want to try AppImage installer. Check the documentation here: https://glpi-agent.readthedocs.io/en/latest/installation/linux-appimage.html

**Comment by undefinedid** [comment]
Hi @g-bougard

Thank you for your answer. The packages repository of Photon OS can be found here: [https://packages.vmware.com/photon/](https://packages.vmware.com/photon/).

I managed to reduce dependencies via the few packages available through _tdnf_:

```tdnf install perl-File-Which perl-IO-Socket-SSL perl-NetAddr-IP perl-Net-SSLeay perl-URI perl-YAML-Tiny```

But a lot are missing. I think I may have to open a case at VMware to ask them to include more perl extensions in their OS. Otherwise, it will require to use RPM packages to fill gaps in _tdnf_ package manager.


Second point, for now, Photon OS doesn't support _snapd_ unfortunately.


But, third point, install through AppImage is OK! The deployment and the launch of an inventory went without problems:

```
root [ ~ ]# ./glpi-agent-1.5-x86_64.AppImage --install --server http://xxxxxx.domain.ltd/glpi/plugins/fusioninventory/
Installing GLPI Agent v1.5-1...
Copying AppImage to /usr/local/bin...
Configuring...
Writing configuration in /etc/glpi-agent/conf.d/00-install.cfg ...
Created symlink /etc/systemd/system/multi-user.target.wants/glpi-agent.service → /etc/systemd/system/glpi-agent.service.
```


```
root [ ~ ]# glpi-agent
[info] target server0: server http://xxxxxx.domain.ltd/glpi/plugins/fusioninventory/
[info] sending prolog request to server0
[info] running task Deploy
[info] No Deploy job enabled or Deploy support disabled server side.
[info] running task Collect
[info] No Collect job enabled or Collect support disabled server side.
[info] running task ESX
[info] No ESX job enabled or ESX support disabled server side.
[info] running task Inventory
[info] New inventory from XXXXXXX-2023-09-26-06-40-46 for server0
```

So everything is fine, I managed to achieve all I needed.
Many thanks for your help!

**Comment by g-bougard** [comment]
Hi @undefinedid 

thank you for your complete feedback.

Then okay, I guess VMware wants to limit the RPM packages and this will probably what they will answer you if you request more perl modules for integration in PhononOS.

As AppImage version is working, this is a good news. We know now it should be used for PhononOS.
