### ISSUE TITLE
Error usb.ids on Debian

### ISSUE THREAD

**Issue by nchizhov** [glpi-project/glpi-agent#509]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

In GLPI-Agent Daemon on Debian 12 logs error:
`[error] usb.ids not found`

### To reproduce

1. Install last night build deb-package on Debian 12
2. Start glpi-agent service 
3. See in logs `[error] usb.ids not found`

### Expected behavior

Maybe add depends usb.ids to deb-package?

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Not applicable

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

### Additional context

Night Build: gita3965103

**Comment by g-bougard** [comment]
Hi @nchizhov 

sorry, we won't add that dependency for this package for few reasons:
 - errors are here to tell something is probably wrong and yes, here it doesn't find the usb.ids file. Error should suggest you something to do if you really mind: this file on latest debian can be installed with the `usb.ids` package.
 - indeed, before a previous debian version (10 if I remember well), this file was provided by `usbutils` package which is in the glpi-agent package dependency. And if we add this dependency, this will break the package for older debian & ubuntu packages as `usb.ids` package doesn't exist in that older distro.
 - this error is really not critical, the inventory task should run. Maybe we should just set it as a warning. Indeed, this missing file will only affect few mechanism to identify manufacturer of found usb devices. And so the only bad effect will be on the inventory quality but only for usb devices.

So if you agree, I'll only move that error to be a warning.

**Comment by g-bougard** [comment]
I may also better change the packaging to include the pci.ids & usb.ids files from glpi-agent release so they can be used as fall-back. So installing usb.ids or pci.ids package from the OS will only permit agent to get more update to date datas.
The bad side-effect would be to enlarge a little the glpi-agent debian package.

**Comment by nchizhov** [comment]
Ok. Show this message in logs as warning will be more better than error.
