### ISSUE TITLE
Support for Office 2019 license

### ISSUE THREAD

**Issue by g-bougard** [glpi-project/glpi-agent#51]
### Documentation

Yes, I read it

### Professional support

Yes, I know

### Is your feature request related to a problem?

Yes, Office 2019 license are not inventoried by GLPI-Agent.

### Expected behavior

Inventory is done and I can find the information in GLPI.

### Alternatives you've considered

FusionInventory agent is also lacking this as pointed by [FusionInventory Agent #896 issue](https://github.com/fusioninventory/fusioninventory-agent/issues/896)

**Comment by xir6fir6iriezdu** [comment]
hi, 
may i know if this has been any updates on this at all?

**Comment by g-bougard** [comment]
Hi @skyemk 
no update at that time. I'll probably work on that subject during in september.

**Comment by vollkommenIrrelevant** [comment]
@g-bougard 
which year? :-P

May it possible that you will some find some time to add Support for Office 2019?

**Comment by g-bougard** [comment]
Hi @vollkommenIrrelevant 

to be honest, it seems some people doesn't have any trouble to inventory Office 2019, but I'm not sure. So today, I'm even not sure fixing this issue is required.

The only thing I'm sure is you're the first person (even our client doesn't complain) to ask the question. But (troll inside) is this software really used ? ;-)

If you're in trouble, would you care to help providing some outputs ? As I don't have access to any platform with that level of software...

**Comment by vollkommenIrrelevant** [comment]
Haha :-)

We are still using Office 2016 - so i'm not able to check if the bug-report is correct and I'm not in trouble :-)

**Comment by g-bougard** [comment]
Lol

then I think I anyway should close this issue.

If you people want this to happen as you can confirm this is an issue, feel free to reopen or comment.
