### ISSUE TITLE
Not detect default gateway on Debian

### ISSUE THREAD

**Issue by nchizhov** [glpi-project/glpi-agent#511]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Not detecting default gateway in inventory on Debian 12, but by command `ip route` showing correct default route:
```
default via 192.168.0.3 dev eth0 onlink
192.168.0.0/20 dev eth0 proto kernel scope link src 192.168.0.250
```

### To reproduce

1. Run glpi-inventory on Debian 12

### Expected behavior

Should detect correct default gateway

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Not applicable

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

### Additional context

GLPI-Agent Night Build gita3965103

Exported xml in archive in attach.
[test.zip](https://github.com/glpi-project/glpi-agent/files/12813840/test.zip)

**Comment by g-bougard** [comment]
Hi @nchizhov 

can you share the output of `netstat -nr` on your platform ? We need first to understand what is wrong in the current code before changing anything.

can you also share the full output of the following command run as root ?
```
glpi-inventory --partial network --debug --debug
```

**Comment by nchizhov** [comment]
Shared output in attach
[debug.zip](https://github.com/glpi-project/glpi-agent/files/12814191/debug.zip)

**Comment by g-bougard** [comment]
> Shared output in attach [debug.zip](https://github.com/glpi-project/glpi-agent/files/12814191/debug.zip)

Thank you, but `netstat -nr` output is missing.

**Comment by nchizhov** [comment]
`netstat` is missing on current VM. As I know I should install package netutils?

**Comment by g-bougard** [comment]
Okay, so yes, you probably need to install a package, and for you, the right one should be [net-tools](https://packages.debian.org/search?searchon=contents&keywords=netstat&mode=path&suite=stable&arch=any). But if it becomes not included in the base system, it make sens glpi-agent needs to try an alternative like `ip route list default`.

I must admit also there's actually a bug in netstat parsing. For me it reports the wrong default route as I have 2 default routes. It is the wrong one as it has the higher metric value, meaning it won't be used first. But the `netstat` output doesn't show the metric value, only `ip route` does. I will assume default routes are ordered by metric in the output.

**Comment by nchizhov** [comment]
Will be it fixed without using netstat and without install net-tools package?

**Comment by g-bougard** [comment]
Hi @nchizhov 

next nightly build should fix your problem without the need to install net-tools package. Let me know if you have time to validate.

**Comment by nchizhov** [comment]
Checked on last night build - all working correct. 
Thank you.
