### ISSUE TITLE
Rules don't work in native GLPI inventory

### ISSUE THREAD

**Issue by sina-4** [glpi-project/glpi-agent#517]
### Bug reporting acknowledgment

Yes, I read it, Not applicable

### Professional support

Yes, I know

### Describe the bug

I have been using the Fusion Inventory plugin and had created a rule that changes a computer's entity based on its IP address. However, after upgrading to GLPI 10.0.10 and switching to native GLPI inventory, the rule is no longer functioning correctly. It only seems to work if the computer doesn't already exist in the inventory.

### To reproduce

1.Install GLPI-10.0.10
2.Install GLPI-Agent 
3.Create  a valid rule
4.Create a new computer and assign it to an entity
5.Froce an inventory

### Expected behavior

The computer’s entity should change according to the rule (Computer's IP adress has changed so that the entity) 

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.x (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

**Comment by g-bougard** [comment]
Hi @sina-4 

sorry but you're opening this issue on the wrong project. For GLPI server issues, you must open an issue on [GLPI project](https://github.com/glpi-project/glpi).
