### ISSUE TITLE
Cant inventory USB devices with agent 1.4 or 1.5 or 1.6 Ubuntu

### ISSUE THREAD

**Issue by loginone33** [glpi-project/glpi-agent#519]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Hi guys.
Tried diffferent versions of agent to solve the prolem with no luck. I will focus on the main one - agent 1.5 installed as snap,  on Ubuntu 22.04.3 LTS.
Cant't inventory any devices/peripherals connected by USB. Mainly I want to get info on connected - Symbol Bar Code Scanner with co luck. When I run glpi Agent , everything goes fine, but scanner wont update in glpi server, and while agent is running the scanner gets suddenly disconnected.
The same device goes thru the inventory process with no problem using windows agent on WIN11 or WIN10.
log from ubuntu , that shows the scanner beeing reconnected (because running the agent disconnects it for a second):
Oct 13 12:40:30 lauadmin-OptiPlex-7010 kernel: [ 1830.608422] evbug: Disconnected device: input26
Oct 13 12:40:33 lauadmin-OptiPlex-7010 kernel: [ 1833.080446] usb 2-1.1: new full-speed USB device number 13 using ehci-pci
Oct 13 12:40:38 lauadmin-OptiPlex-7010 kernel: [ 1838.399755] usb 2-1.1: New USB device found, idVendor=05e0, idProduct=1200, bcdDevice= 2.01
Oct 13 12:40:38 lauadmin-OptiPlex-7010 kernel: [ 1838.399767] usb 2-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Oct 13 12:40:38 lauadmin-OptiPlex-7010 kernel: [ 1838.399770] usb 2-1.1: Product: Symbol Bar Code Scanner
Oct 13 12:40:38 lauadmin-OptiPlex-7010 kernel: [ 1838.399773] usb 2-1.1: Manufacturer: ﾩSymbol Technologies, Inc, 2002
Oct 13 12:40:38 lauadmin-OptiPlex-7010 kernel: [ 1838.399775] usb 2-1.1: SerialNumber: S/N:28A1CC69D1D8AE4585EDA53F7CD6CB88 Rev:NBRMSAAHDM:01OCT153
Oct 13 12:40:38 lauadmin-OptiPlex-7010 kernel: [ 1838.403370] input: ﾩSymbol Technologies, Inc, 2002 Symbol Bar Code Scanner as /devices/pci0000:00/0000:00:1a.0/usb2/2-1/2-1.1/2-1.1:1.0/0003:05E0:1200.000D/input/input27
Oct 13 12:40:38 lauadmin-OptiPlex-7010 kernel: [ 1838.460641] evbug: Connected device: input27 (ﾩSymbol Technologies, Inc, 2002 Symbol Bar Code Scanner at usb-0000:00:1a.0-1.1/input0)
Oct 13 12:40:38 lauadmin-OptiPlex-7010 kernel: [ 1838.460990] hid-generic 0003:05E0:1200.000D: input,hidraw0: USB HID v1.10 Keyboard [ﾩSymbol Technologies, Inc, 2002 Symbol Bar Code Scanner] on usb-0000:00:1a.0-1.1/input0
Oct 13 12:43:25 lauadmin-OptiPlex-7010 kernel: [ 2005.146557] usb 2-1.1: USB disconnect, device number 13
Oct 13 12:43:25 lauadmin-OptiPlex-7010 kernel: [ 2005.216850] evbug: Disconnected device: input27
Oct 13 12:43:28 lauadmin-OptiPlex-7010 kernel: [ 2007.676858] usb 2-1.1: new full-speed USB device number 14 using ehci-pci
Oct 13 12:43:33 lauadmin-OptiPlex-7010 kernel: [ 2012.992673] usb 2-1.1: New USB device found, idVendor=05e0, idProduct=1200, bcdDevice= 2.01
Oct 13 12:43:33 lauadmin-OptiPlex-7010 kernel: [ 2012.992684] usb 2-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Oct 13 12:43:33 lauadmin-OptiPlex-7010 kernel: [ 2012.992688] usb 2-1.1: Product: Symbol Bar Code Scanner
Oct 13 12:43:33 lauadmin-OptiPlex-7010 kernel: [ 2012.992690] usb 2-1.1: Manufacturer: ﾩSymbol Technologies, Inc, 2002
Oct 13 12:43:33 lauadmin-OptiPlex-7010 kernel: [ 2012.992693] usb 2-1.1: SerialNumber: S/N:28A1CC69D1D8AE4585EDA53F7CD6CB88 Rev:NBRMSAAHDM:01OCT153
Oct 13 12:43:33 lauadmin-OptiPlex-7010 kernel: [ 2012.996928] input: ﾩSymbol Technologies, Inc, 2002 Symbol Bar Code Scanner as /devices/pci0000:00/0000:00:1a.0/usb2/2-1/2-1.1/2-1.1:1.0/0003:05E0:1200.000E/input/input28
Oct 13 12:43:33 lauadmin-OptiPlex-7010 kernel: [ 2013.060957] evbug: Connected device: input28 (ﾩSymbol Technologies, Inc, 2002 Symbol Bar Code Scanner at usb-0000:00:1a.0-1.1/input0)
Oct 13 12:43:33 lauadmin-OptiPlex-7010 kernel: [ 2013.061198] hid-generic 0003:05E0:1200.000E: input,hidraw0: USB HID v1.10 Keyboard [ﾩSymbol Technologies, Inc, 2002 Symbol Bar Code Scanner] on usb-0000:00:1a.0-1.1/input0

agent debug:
[debug] Logger backend Stderr initialized
[debug] GLPI Agent (1.6-gitf83b22f4)
[debug] Configuration directory: /snap/glpi-agent/current/etc/glpi-agent
[debug] Data directory: /snap/glpi-agent/current/usr/share/glpi-agent
[debug] Storage directory: /var/snap/glpi-agent/common
[debug] Lib directory: /snap/glpi-agent/current/usr/share/glpi-agent/lib
[debug] [target server0] Next server contact planned for Fri Oct 13 14:27:58 2023
[debug] Available tasks:
[debug] - Collect: 2.9
[debug] - Deploy: 3.0
[debug] - ESX: 2.8
[debug] - Inventory: 1.13
[debug] - NetDiscovery: 6.0
[debug] - NetInventory: 6.0
[debug] - RemoteInventory: 1.2
[debug] - WakeOnLan: 2.2
[debug] target server0: server http://gl***l/front/inventory.php
[debug] Planned tasks for server0: WakeOnLan,Collect,RemoteInventory,NetDiscovery,Inventory,Deploy,ESX,NetInventory
[debug] Built for snap on 2023-10-10 02:06
[debug] Running in foreground mode
[info] target server0: server http://gl***l/front/inventory.php
[info] sending contact request to server0
[debug] server message: remoteinventory task not supported
[info] sending prolog request to server0
[debug] WakeOnLan task execution not requested
[info] running task Collect
[error] [http client] communication error: 400 Bad Request, Protocol not supported
[info] Collect task not supported by server0
[debug] Remote inventory task execution disabled: no remote setup
[debug] NetDiscovery task execution not requested
[info] running task Inventory
[info] New inventory from lauadmin-OptiPlex-7010-2023-10-13-13-33-38 for server0
[debug] module GLPI::Agent::Task::Inventory::Generic::Firewall::Systemd disabled because of GLPI::Agent::Task::Inventory::Generic::Firewall::Ufw
[debug] module GLPI::Agent::Task::Inventory::Linux::Bios disabled because of GLPI::Agent::Task::Inventory::Generic::Dmidecode::Bios
[debug] module GLPI::Agent::Task::Inventory::Linux::Storages::Adaptec disabled because of GLPI::Agent::Task::Inventory::Linux::Storages
[debug] Running GLPI::Agent::Task::Inventory::AccessLog
[debug] Running GLPI::Agent::Task::Inventory::Generic
[debug] Running GLPI::Agent::Task::Inventory::Generic::Arch
[debug] Running GLPI::Agent::Task::Inventory::Generic::Batteries
[debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode
[debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode::Battery
[debug] Running GLPI::Agent::Task::Inventory::Generic::Batteries::Upower
[debug] Running GLPI::Agent::Task::Inventory::Generic::Databases
[debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode::Bios
[debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode::Hardware
[debug] Running GLPI::Agent::Task::Inventory::Linux
[debug] Running GLPI::Agent::Task::Inventory::Linux::Hardware
[debug] Running GLPI::Agent::Task::Inventory::Vmsystem
[debug] Running GLPI::Agent::Task::Inventory::Linux::Memory
[debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode::Memory
[debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode::Ports
[debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode::Psu
[debug] Running GLPI::Agent::Task::Inventory::Generic::Dmidecode::Slots
[debug] Running GLPI::Agent::Task::Inventory::Generic::Domains
[debug] Running GLPI::Agent::Task::Inventory::Generic::Drives
[debug] Running GLPI::Agent::Task::Inventory::Generic::Environment
[debug] Running GLPI::Agent::Task::Inventory::Generic::Firewall
[debug] Running GLPI::Agent::Task::Inventory::Generic::Firewall::Ufw
[debug] Running GLPI::Agent::Task::Inventory::Generic::Hostname
[debug] Running GLPI::Agent::Task::Inventory::Generic::Networks
[debug] Running GLPI::Agent::Task::Inventory::Generic::OS
[debug] Running GLPI::Agent::Task::Inventory::Generic::PCI
[debug] Running GLPI::Agent::Task::Inventory::Generic::PCI::Controllers
[debug] Running GLPI::Agent::Task::Inventory::Generic::PCI::Modems
[debug] Running GLPI::Agent::Task::Inventory::Generic::PCI::Sounds
[debug] Running GLPI::Agent::Task::Inventory::Generic::PCI::Videos
[debug] Running GLPI::Agent::Task::Inventory::Generic::Printers
[debug] Running GLPI::Agent::Task::Inventory::Generic::Processes
[debug] Running GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt
[debug] Running GLPI::Agent::Task::Inventory::Generic::SSH
[debug] Running GLPI::Agent::Task::Inventory::Generic::Screen
[debug] retrieving EDID data:
[debug] - reading /sys/devices content: success
[debug] Running GLPI::Agent::Task::Inventory::Generic::Softwares
[debug] Running GLPI::Agent::Task::Inventory::Generic::Softwares::Deb
[debug] Running GLPI::Agent::Task::Inventory::Generic::Softwares::Snap
[debug] Running GLPI::Agent::Task::Inventory::Generic::Storages
[debug] Running GLPI::Agent::Task::Inventory::Generic::Timezone
[debug] Using DateTime::TimeZone to get the timezone name
[debug] Running GLPI::Agent::Task::Inventory::Generic::USB
[debug] Running GLPI::Agent::Task::Inventory::Generic::Users
[debug] Running GLPI::Agent::Task::Inventory::Linux::AntiVirus
[debug] Running GLPI::Agent::Task::Inventory::Linux::Distro
[debug] Running GLPI::Agent::Task::Inventory::Linux::Distro::OSRelease
[debug] Running GLPI::Agent::Task::Inventory::Linux::Drives
[debug] Running GLPI::Agent::Task::Inventory::Linux::Inputs
[debug] Running GLPI::Agent::Task::Inventory::Linux::Networks
[debug] retrieving interfaces list:
[debug] - running /sbin/ip command: success
[debug] Running GLPI::Agent::Task::Inventory::Linux::OS
[debug] Running GLPI::Agent::Task::Inventory::Linux::Storages
[debug] retrieving devices list:
[debug] - reading /sys/block content: success
[debug] Running GLPI::Agent::Task::Inventory::Linux::Uptime
[debug] Running GLPI::Agent::Task::Inventory::Linux::Videos
[debug] Running GLPI::Agent::Task::Inventory::Linux::i386
[debug] Running GLPI::Agent::Task::Inventory::Linux::i386::CPU
[debug] Running GLPI::Agent::Task::Inventory::Provider
[debug] Running GLPI::Agent::Task::Inventory::Virtualization
[info] running task Deploy
[error] [http client] communication error: 400 Bad Request, Protocol not supported
[info] Deploy task not supported by server0
[info] running task ESX
[error] [http client] communication error: 400 Bad Request, Protocol not supported
[info] ESX task not supported by server0
[debug] NetInventory task execution not requested

no errors conserning USB Devices.

### To reproduce

snap install agent on ubuntu 
run: glpi-agent

### Expected behavior

Get inventory of USB devices

### Operating system

Linux

### GLPI Agent version

1.5

### GLPI version

10.0.9

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.2.3

### Additional context

-none

**Comment by g-bougard** [comment]
Hello @loginone33 

as far I know, the agent is only parsing the output of `lsusb -v`. Can you share the output of this command on a computer you expected the Symbol Bar Code Scanner to be reported from an Ubuntu ?

And can you also share the output if the following command ?
```
sudo glpi-inventory --debug --debug --partial=usb
```

As packaging is also available for Ubuntu, have you tried to use the linux perl installer in place of the Snap ? Right now, I can only imagine using Snap packaged version has a bad side effect.

**Comment by loginone33** [comment]
Hi, thank You for reply.
1. output of "lsub -v" (only the part with symbol scanner, because the output is very long) :
```
Bus 002 Device 018: ID 05e0:1200 Symbol Technologies Bar Code Scanner
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0         8
  idVendor           0x05e0 Symbol Technologies
  idProduct          0x1200 Bar Code Scanner
  bcdDevice            2.01
  iManufacturer           1 ﾩSymbol Technologies, Inc, 2002
  iProduct                2 Symbol Bar Code Scanner
  iSerial                 3 S/N:28A1CC69D1D8AE4585EDA53F7CD6CB88 Rev:NBRMSAAHDM:            
```
Strange thing is that when I run "lsub -v" scanner gets disconnected for a second as well. I know it because it makes a sound when reconnecting and it makes a sound, just after I run the command.
2. output of "sudo glpi-inventory --debug --debug --partial=usb" but i changed "glpi-inventory" to "glpi-agent" because inventory command was not found.
```
> glpi-agent --debug --debug --partial=usb
[debug] Logger backend Stderr initialized
[debug] GLPI Agent (1.6-gitf83b22f4)
[debug] Configuration directory: /snap/glpi-agent/current/etc/glpi-agent
[debug] Data directory: /snap/glpi-agent/current/usr/share/glpi-agent
[debug] Storage directory: /var/snap/glpi-agent/common
[debug] Lib directory: /snap/glpi-agent/current/usr/share/glpi-agent/lib
[debug] [target server0] Next server contact planned for Tue Oct 17 06:52:14 2023
[debug2] getAvailableTasks() : add of task Collect version 2.9
[debug2] getAvailableTasks() : add of task Deploy version 3.0
[debug2] getAvailableTasks() : add of task ESX version 2.8
[debug2] getAvailableTasks() : add of task Inventory version 1.13
[debug2] getAvailableTasks() : add of task NetDiscovery version 6.0
[debug2] getAvailableTasks() : add of task NetInventory version 6.0
[debug2] getAvailableTasks() : add of task RemoteInventory version 1.2
[debug2] getAvailableTasks() : add of task WakeOnLan version 2.2
[debug] Available tasks:
[debug] - Collect: 2.9
[debug] - Deploy: 3.0
[debug] - ESX: 2.8
[debug] - Inventory: 1.13
[debug] - NetDiscovery: 6.0
[debug] - NetInventory: 6.0
[debug] - RemoteInventory: 1.2
[debug] - WakeOnLan: 2.2
[debug] target server0: server http://gl***l/front/inventory.php
[debug] Planned tasks for server0: NetInventory,RemoteInventory,Inventory,Deploy,ESX,Collect,NetDiscovery,WakeOnLan
[debug] Built for snap on 2023-10-10 02:06
[debug] Running in foreground mode
[info] target server0: server http://g***l/front/inventory.php
[debug2] [http client] Using Compress::Zlib for compression
[info] sending contact request to server0
[debug2] [http client] 5DA729BE: sending message:
{
   "action": "contact",
   "deviceid": "lauadmin-OptiPlex-7010-2023-10-13-13-33-38",
   "enabled-tasks": [
      "collect",
      "deploy",
      "esx",
      "inventory",
      "netdiscovery",
      "netinventory",
      "remoteinventory",
      "wakeonlan"
   ],
   "installed-tasks": [
      "collect",
      "deploy",
      "esx",
      "inventory",
      "netdiscovery",
      "netinventory",
      "remoteinventory",
      "wakeonlan"
   ],
   "name": "GLPI-Agent",
   "version": "1.6-gitf83b22f4"
}
[debug2] format: Zlib
[debug2] [http client] 5DA729BE: received message:
{"message":"remoteinventory task not supported","disabled":["remoteinventory"],"expiration":"24","status":"ok","tasks":{"collect":{"version":"1.2.3","server":"glpiinventory"},"deploy":{"version":"1.2.3","server":"glpiinventory"},"esx":{"version":"1.2.3","server":"glpiinventory"},"inventory":{"server":"glpi","version":"10.0.9"},"netdiscovery":{"version":"1.2.3","server":"glpiinventory"},"netinventory":{"version":"1.2.3","server":"glpiinventory"},"wakeonlan":{"version":"1.2.3","server":"glpiinventory"}}}
[debug] server message: remoteinventory task not supported
[debug2] [http client] Using Compress::Zlib for compression
[info] sending prolog request to server0
[debug2] [http client] sending message:
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <DEVICEID>lauadmin-OptiPlex-7010-2023-10-13-13-33-38</DEVICEID>
  <QUERY>PROLOG</QUERY>
  <TOKEN>12345678</TOKEN>
</REQUEST>
[debug2] format: Zlib
[debug2] [http client] receiving message:
<?xml version="1.0"?>
<REPLY><PROLOG_FREQ>24</PROLOG_FREQ><RESPONSE>SEND</RESPONSE></REPLY>
[error] Can't call method "init" on unblessed reference at /snap/glpi-agent/x1/usr/share/glpi-agent/lib/GLPI/Agent.pm line 465.
[error] Can't call method "init" on unblessed reference at /snap/glpi-agent/x1/usr/share/glpi-agent/lib/GLPI/Agent.pm line 465.
[error] Can't call method "init" on unblessed reference at /snap/glpi-agent/x1/usr/share/glpi-agent/lib/GLPI/Agent.pm line 465.
[error] Can't call method "init" on unblessed reference at /snap/glpi-agent/x1/usr/share/glpi-agent/lib/GLPI/Agent.pm line 465.
[error] Can't call method "init" on unblessed reference at /snap/glpi-agent/x1/usr/share/glpi-agent/lib/GLPI/Agent.pm line 465.
[error] Can't call method "init" on unblessed reference at /snap/glpi-agent/x1/usr/share/glpi-agent/lib/GLPI/Agent.pm line 465.
[error] Can't call method "init" on unblessed reference at /snap/glpi-agent/x1/usr/share/glpi-agent/lib/GLPI/Agent.pm line 465.
[error] Can't call method "init" on unblessed reference at /snap/glpi-agent/x1/usr/share/glpi-agent/lib/GLPI/Agent.pm line 465.
```
3. Firstly I used AppImage installer , but when problems occured for test pourposes I used snap, because it's quickest. If above doesn't give any answer I will try different agent installation. But if it's snap problem maybe we will solve it ;)

**Comment by g-bougard** [comment]
> Strange thing is that when I run "lsusb -v" scanner gets disconnected for a second as well. I know it because it makes a sound when reconnecting and it makes a sound, just after I run the command.

Here you explain yourself the fact the device is disconnected. This command purpose is just to list available USB devices. I guess there's a bug on linux or on your device which triggers the device disconnection. For that point, I don't have any answer and you should probably request a support from the manufacturer, maybe they still have an answer for this question. But I think this is not a big deal to have the device disconnected and connected again unless it prevents to be re-used as expected after that.

Anyway, it seems we have an output, but maybe it is wrongly parsed by the agent and I suspect we fail to report "S/N:28A1CC69D1D8AE4585EDA53F7CD6CB88 Rev:NBRMSAAHDM:" as a serailnumber by itself... The current code will only extract the "S" from "S/N" at the beginning and I agree this is wrong. Just to be able to compare with the windows case that you explained is working and so you know what you expect, can you share the output of the following command run on a windows  with that device and at least only the related entry ?
```
wmic path CIM_LogicalDevice get /format:list
```
Or you can simply report the usb part of the json generated by following command to be run as administrator and from the glpi-agent installation fodler:
```
glpi-inventory --partial usb
```

If you only expect "28A1CC69D1D8AE4585EDA53F7CD6CB88", this should be easy to fix. I don't know if "S/N:28A1CC69D1D8AE4585EDA53F7CD6CB88 Rev:NBRMSAAHDM:" is following some standard. But for me, this is another sample of what manufacturers can wrongly do to achieve some obscure requirement, maybe here be able to report S/N & Rev.

**Comment by loginone33** [comment]
It's no problem that devices is disconnected, but it happens on linux while running the agent, so this is why I mentioned it, I tought this could be related to the inventory problem.
Commands on windows:
1. wmic path CIM_LogicalDevice get /format:list OUTPUT:
Availability=
ConfigManagerErrorCode=0
ConfigManagerUserConfig=FALSE
CreationClassName=Win32_Keyboard
DeviceID=USB\VID_05E0&amp;PID_1200\S/N:28A1CC69D1D8AE4585EDA53F7CD6CB88_REV:NBRMSAAHDM:01OCT153
ErrorCleared=
ErrorDescription=
InstallDate=
IsLocked=
LastErrorCode=
Layout=00000415
NumberOfFunctionKeys=12
Password=
PNPDeviceID=USB\VID_05E0&amp;PID_1200\S/N:28A1CC69D1D8AE4585EDA53F7CD6CB88_REV:NBRMSAAHDM:01OCT153
PowerManagementCapabilities=
PowerManagementSupported=FALSE
Status=OK
StatusInfo=
SystemCreationClassName=Win32_ComputerSystem

2. glpi-inventory --partial usb OUTPUT:

  "caption": "Bar Code Scanner",
            "manufacturer": "Symbol Technologies",
            "name": "Bar Code Scanner",
            "productid": "1200",
            "serial": "S/N:28A1CC69D1D8AE4585EDA53F7CD6CB88_REV:NBRMSAAHDM:01OCT153",
            "vendorid": "05E0"

**Comment by g-bougard** [comment]
Windows is magical... I'm always impressed they can manage to make stuff even worse when it is still bad.

So the question now for the agent:
 1. do you expect we keep `S/N:28A1CC69D1D8AE4585EDA53F7CD6CB88_REV:NBRMSAAHDM:01OCT153` as full serial number, the same than on windows, implying transforming spaces by underscores, but I don't know where "01OCT153" is coming from as I don't see it in the `lsusb` output ? The advantage would be you can trace if a device has been disconnected from a linux to be reconnected on a windows.
 2. do you prefer we keep only `28A1CC69D1D8AE4585EDA53F7CD6CB88` which seems to be the right serial number ? And maybe I can also fix usb windows inventory to extract the right serial number. The problem is we change reported serial number on windows, you'll have duplicated devices and I think you'll have to delete them manually. But you'll also be able to trace computers the devices is connected to.

IMHO, I would prefer to only report `28A1CC69D1D8AE4585EDA53F7CD6CB88` and fix windows support to do the same.

**Comment by loginone33** [comment]
If it's possible that windows agent will get the same serial, than It could be 28A1CC69D1D8AE4585EDA53F7CD6CB88 . We are at the verge of implementing agent in whole company so right now it's a good idea to do it properly.

**Comment by g-bougard** [comment]
Hi @loginone33 

thank you for your answer, I'll fix linux and windows usb inventory to work this way.

Can I suggest you to contact the manufacturer support and tell them the reported serial number is wrong and should only be the serial number part ? If they need to also report a `REV` value it should be set somewhere else and surely not in the **iSerialNumber** USB field. To me, this is even an USB implementation bug. You can even point them to an [official Microsoft position about iSerialNumber on MIDI USB devices](https://devblogs.microsoft.com/windows-music-dev/the-importance-of-including-a-unique-iserialnumber-in-your-usb-midi-devices/#our-request-for-device-manufacturers-and-makers). Even if this position is for MIDI devices, the **iSerialNumber** problem is applicable to any kind of devices.

**Comment by g-bougard** [comment]
Hi @loginone33 

I just pushed the fix. You'll be able to test & validate it works as expected on linux & on windows using the next nightly build.

Thank you for the data sharing, I used them to update and add your case to unit tests.

**Comment by loginone33** [comment]
Thank You very much. Will test it as soon as possible.

**Comment by loginone33** [comment]
tested, serial is good, but still only windows agent sends proper data to glpi server. On linux situation is without changes, I get monitor and pc data, but no luck with USB devices. I will try today on debian instead of ubuntu and see if it's the same.

**Comment by loginone33** [comment]
I Installed agent on debian with snap, and with perl, it still ignores USB devices.

**Comment by g-bougard** [comment]
Can you share the output of `sudo glpi-inventory --debug --debug --partial=usb` ?
The command should be available if you installed the agent with perl installer.

**Comment by loginone33** [comment]
Sure, here You go:
```
...
 "action": "inventory",
   "content": {
      "bios": {
         "bdate": "2018-06-28",
         "bmanufacturer": "Dell Inc.",
         "bversion": "A29",
         "mmanufacturer": "Dell Inc.",
         "mmodel": "0MN1TX",
         "msn": "/JMS8B22/CN7220044F00XS/",
         "skunumber": "OptiPlex 7010",
         "smanufacturer": "Dell Inc.",
         "smodel": "OptiPlex 7010",
         "ssn": "JMS8B22"
      },
      "hardware": {
         "chassis_type": "Lunch Box",
         "dns": "192.168.5.10",
         "name": "DESK-142",
         "uuid": "4c4c4544-004d-5310-8038-cac04f423232",
         "vmsystem": "Physical"
      },
      "usbdevices": [
         {
            "caption": "Integrated Rate Matching Hub",
            "class": "9",
            "manufacturer": "Intel Corp.",
            "productid": "0024",
            "subclass": "0",
            "vendorid": "8087"
         },
         {
            "caption": "Mouse",
            "class": "3",
            "manufacturer": "Logitech, Inc.",
            "productid": "c077",
            "subclass": "1",
            "vendorid": "046d"
         },
         {
            "caption": "KB216 Wired Keyboard",
            "class": "3",
            "manufacturer": "Dell Computer Corp.",
            "productid": "2113",
            "subclass": "0",
            "vendorid": "413c"
         },
         {
            "caption": "Hub",
            "class": "9",
            "manufacturer": "Microchip Technology, Inc. (formerly SMSC)",
            "productid": "2412",
            "subclass": "0",
            "vendorid": "0424"
         },
         {
            "caption": "Bar Code Scanner",
            "class": "3",
            "manufacturer": "Symbol Technologies",
            "productid": "1200",
            "serial": "F01B78F1B2F0460EA17229DEB388571A",
            "subclass": "1",
            "vendorid": "05e0"
         },
         {
            "caption": "Integrated Rate Matching Hub",
            "class": "9",
            "manufacturer": "Intel Corp.",
            "productid": "0024",
            "subclass": "0",
            "vendorid": "8087"
         },
         {
            "caption": "3.0 root hub",
            "class": "9",
            "manufacturer": "Linux Foundation",
            "productid": "0003",
            "subclass": "0",
            "vendorid": "1d6b"
         }
      ],
      "versionclient": "GLPI-Inventory_v1.6-git16d14304"
   },
   "deviceid": "DESK-142-2023-10-18-11-39-29",
   "itemtype": "Computer",
   "partial": true
}
[info] Inventory dumped on standard output
```

**I skipped what i think is non important data, but if you want I can send it as it is.**
I dont know about keyboard and mouse, because does never get imported , even with windows agent.

just for example i runned -  **sudo glpi-inventory --debug --debug --partial=monitor** - because monitor data gets thru, so You can compare

OUTPUT:
```
...
      "monitors": [
         {
            "base64": "AP///////wAQrExATFAzMBgTAQMKLx547u6Vo1RMmSYPUFSlSwBxT4GAswABAQEBAQEBAQEBITmQMGIaJ0BosDYA2igRAAAcAAAA/wBVOTE5Szk2ODAzUEwKAAAA/ABERUxMIFAyMjEwCiAgAAAA/QA4Sx5TEAAKICAgICAgAFo=",
            "caption": "DELL P2210",
            "description": "24/2009",
            "manufacturer": "Dell Inc.",
            "serial": "U919K96803PL"
         }
      ],
      "versionclient": "GLPI-Inventory_v1.6-git16d14304"
   },
   "deviceid": "DESK-142-2023-10-18-11-43-00",
   "itemtype": "Computer",
   "partial": true
...
```

**Comment by g-bougard** [comment]
Indeed it seems a required field is missing: the name...
On windows, the name is set and is just a copy of the caption.

Applying this patch should fix the problem:
```diff
diff --git a/lib/GLPI/Agent/Task/Inventory/Generic/USB.pm b/lib/GLPI/Agent/Task/Inventory/Generic/USB.pm
index c66898a82..df7f5fe77 100644
--- a/lib/GLPI/Agent/Task/Inventory/Generic/USB.pm
+++ b/lib/GLPI/Agent/Task/Inventory/Generic/USB.pm
@@ -53,6 +53,7 @@ sub _getDevices {
             my $entry = $vendor->{devices}->{$device->{PRODUCTID}};
             if ($entry) {
                 $device->{CAPTION} = $entry->{name};
+                $device->{NAME}    = $entry->{name};
             }
         }
 
```

I'll include that patch and next nightly build should fix that issue.

About keyboard and mouse, they are not imported as they are missing a serialnumber. Wihtout it GLPI, can't decide if one keyboard or mouse has moved to another computer. This is a well-known issue: usb doesn't report an serial for that devices. It seems manufacturers don't report it to the usb layer for that devices. I can only guess they are unable to as they probably aren't able to store it on the device. This is probably just too difficult...

**Comment by g-bougard** [comment]
But maybe I'm wrong somewhere. I just checked on my computer and I have a mouse and a keyboard for which a serial seems to be reported... even if I don't see the same numbers than printed on the device back.
Now the fact is more a name is missing, and even a caption. Maybe this part could be improved if we can guess a name.

**Comment by g-bougard** [comment]
Hi @loginone33 
I just pushed a better usb devices linux support enhancement.
Please try again with next nightly build.

**Comment by loginone33** [comment]
Hi, right now theres no new version, so as soon as it will be available i will test it. Thank You for keeping on trying :)

**Comment by g-bougard** [comment]
Hi @loginone33 

I just saw that. It seems the MacOSX build failed. This happens sometime when the Apple notarization online service is failing. I just restarted that build. I hope everything came online since the fail.

**Comment by g-bougard** [comment]
FYI @loginone33, the build passed and new nightly has been published.

**Comment by loginone33** [comment]
Bingo ! Works like a charm ! I don't know if it's important, but keyboard and mouse are still ignored(it's not important for me at least). You said something about usb devices (mouse, keyboard) having different serial than on the device itself, the same thing is with the barcode scanner , but as long as every agent is seeing same serial it gets the job done so I'm happy with the solution. For me most important thing was, when i switch the barcode scanner to a different PC I see this in glpi on the connections tab. Once again thank You very much for proper support!

**Comment by loginone33** [comment]
> Hi @loginone33
> 
> thank you for your answer, I'll fix linux and windows usb inventory to work this way.
> 
> Can I suggest you to contact the manufacturer support and tell them the reported serial number is wrong and should only be the serial number part ? If they need to also report a `REV` value it should be set somewhere else and surely not in the **iSerialNumber** USB field. To me, this is even an USB implementation bug. You can even point them to an [official Microsoft position about iSerialNumber on MIDI USB devices](https://devblogs.microsoft.com/windows-music-dev/the-importance-of-including-a-unique-iserialnumber-in-your-usb-midi-devices/#our-request-for-device-manufacturers-and-makers). Even if this position is for MIDI devices, the **iSerialNumber** problem is applicable to any kind of devices.

I missed that part, sure, I will report this to manufacturer.

**Comment by g-bougard** [comment]
About keyboard & mouse, they not all reports a serial so they won't be integrated in GLPI without it.
My guess is the reported serialnumber is more the embedded usb chip serialnumber. As you said, this should be sufficient to track devices in GLPI.

**Comment by loginone33** [comment]
Hi,
did some research on zebra forums, and about the mentioned scanner it's just the way they do it. Zebra has it's own software to resolve proper serial. 
Heres a link to similair problem:
https://supportcommunity.zebra.com/s/question/0D56S000097xCTYSA2/how-to-convert-ls2208sr20007rur-serial-number-from-windows-registry-to-serial-number-printed-on-sticker-and-box-

So I think theres nothing that we can do about this.
