### ISSUE TITLE
UninstallOcsAgent

### ISSUE THREAD

**Issue by Knoppix1** [glpi-project/glpi-agent#524]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

La déinstallation de OCS ne se fait pas avec le script glpi-agent-deployment.vbs

### To reproduce

Mettre dans le script la variable UninstallOcsAgent à Yes

### Expected behavior

Dans la Function removeOCSAgents() le script n'arrive pas à lire les clés de registre car WshShell.Run n'est pas déclaré dans la fonction
j'ai ajouté ceci au début de la fonction pour que ça fonctionne : 
   Dim WshShell, bKey
   Set WshShell = WScript.CreateObject("WScript.Shell")

### Operating system

Linux

### GLPI Agent version

1.5

### GLPI version

10.0.9

**Comment by sistemas2csd** [comment]
The WshShell function is defined in the main program:

'
'
' MAIN
'
'

Dim nMinutesToAdvance, strCmd, strSystemArchitecture, strTempDir, WshShell, strInstallOrRepair, bInstall
Set WshShell = WScript.CreateObject("WScript.shell")

Regards

**Comment by Knoppix1** [comment]
Hi,
Exact ! My troubleshooting is bad ;)
In GPO computer the script installs GLPI correctly but the uninstallation is not done
If I run the script manually it works fine.
So that's another problem
Thank you for your reply
