### ISSUE TITLE
Inventory not performed via ssh with Toolbox

### ISSUE THREAD

**Issue by erique-souza** [glpi-project/glpi-agent#532]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Still not applicable

### Describe the bug

When trying to run the inventory via ssh protocol on a port other than 22, it was not possible to connect to the device even though the ssh protocol was active, the correct credentials and the starting and ending IP range of the same ip, in the Toolbox interface

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/cbfb3862-f406-4541-998e-7195a52aeb9c)

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/97638ffc-788c-4ffc-bf84-9cbac54a428f)

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/1dfeefa0-c1a2-4629-bafd-8abddd8b7b59)

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/83b72761-b058-4b20-b670-1d562143a493)

### To reproduce

- Have Toolbox Enabled
- Create ssh credential
- Create the IP range only with the target IP, starting and ending IP
- try to carry out the inventory

### Expected behavior

Remote inventory via ssh protocol with new netdiscovery via Toolbox

### Operating system

Windows

### GLPI Agent version

1.6.1

### GLPI version

Not applicable

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

**Comment by g-bougard** [comment]
Hi @erique-souza 

when using user+password credentials, you need to use `libssh2` mode. Here, it seems to only selected `ssh`. This forces to not use `libssh2`. `ssh` mode is only nusable if you configured your environment to use ssh-key based authentication.

So just uncheck `ssh` mode to use the default processing which will select `libssh2`. Or don't forget to at least select `libssh2` mode.

**Comment by erique-souza** [comment]
> Hi @erique-souza
> 
> when using user+password credentials, you need to use `libssh2` mode. Here, it seems to only selected `ssh`. This forces to not use `libssh2`. `ssh` mode is only nusable if you configured your environment to use ssh-key based authentication.
> 
> So just uncheck `ssh` mode to use the default processing which will select `libssh2`. Or don't forget to at least select `libssh2` mode.


I tested using just the libssh2 method or just leaving it without selecting, I checked the user and password credentials are correct, the IP is also within the range, but I was unable to perform the inventory via ssh

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/bcc01978-cec5-4c70-b6b1-7dacbe56ea30)

**Comment by g-bougard** [comment]
Hi @erique-souza 

please share the related output you can extract from the task log. Just telling something is not working is not enough here. We need a starting point showing an error.

**Comment by erique-souza** [comment]
> Hi @erique-souza
> 
> please share the related output you can extract from the task log. Just telling something is not working is not enough here. We need a starting point showing an error.

Alright, I'm getting the log on file and also from the task below

I don't know if there is something wrong but I am using a different port than the default 22 of the ssh protocol

[glpi-agent.log](https://github.com/glpi-project/glpi-agent/files/13451164/glpi-agent.log)

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/b9778878-d90d-4345-9bff-679998497efb)

**Comment by erique-souza** [comment]
I increased the debug to level 2 and redid the inventory, but there was no change in the log file
[glpi-agent.log](https://github.com/glpi-project/glpi-agent/files/13451216/glpi-agent.log)

**Comment by erique-souza** [comment]
[glpi-agent.log](https://github.com/glpi-project/glpi-agent/files/13451222/glpi-agent.log)

I increased the debug to level 2 and redid the inventory

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/65a4e27e-503f-4057-b0f7-d8b5f9bbb9e5)

```
[info] Starting Docker teste network scan task job...
[debug] [target local1] Next tasks run planned for Thu Nov 23 12:16:05 2023
[info] Running Docker teste task...
[debug] initializing job 1
[debug] initializing block 192.168.0.100-192.168.0.100
[debug] Current netdiscovery run expiration timeout: 15 minutes
[debug] using 1 netdiscovery worker
[debug] starting job 1 with 1 ip to scan using 5 workers
[debug] #1, scanning 192.168.0.100
[debug] #1, Remote mode enabled: libssh2
[debug2] #1, Using libssh2 1.8.2 for ssh remote
[debug2] #1, Connecting to '192.168.0.100:8063' remote host...
[debug] #1, Can't reach 192.168.0.100:8063 for ssh remoteinventory via libssh2: -5 LIBSSH2_ERROR_KEX_FAILURE Unable to exchange encryption keys
[debug] #1, - scanning 192.168.0.100:8063 with ssh RemoteInventory, credentials [Docker teste]: no result, Can't run simple command on remote via libssh2, check server is up and ssh access is setup
[debug] #1, - scanning 192.168.0.100 with netbios: no result
[debug] #1, - scanning 192.168.0.100 with echo ping: success
[debug2] #1, executing arp -a 192.168.0.100
[debug] #1, - scanning 192.168.0.100 in arp table: success
[info] #1, Netdiscovery result for 192.168.0.100 saved in ./netdiscovery/192.168.0.100.xml
[debug] #1, #1, worker termination
[debug] #1, Netdiscovery worker terminated
[info] #1, Docker teste: Docker teste network scan done
[debug] #1, Task run in 1.677 seconds
```

**Comment by g-bougard** [comment]
The error shows the agent finally failed on an attempt to connect using key-based authentication and, or the user/password authentication didn't work or it even wasn't tried.

Have you a key-based authentication setup in your environment for your how usage ?

Also can you confirm on which platform you're running ToolBox ?

**Comment by erique-souza** [comment]
> The error shows the agent finally failed on an attempt to connect using key-based authentication and, or the user/password authentication didn't work or it even wasn't tried.
> 
> Have you a key-based authentication setup in your environment for your how usage ?
> 
> Also can you confirm on which platform you're running ToolBox ?

Strange, I don't have any ssh access key configured, only the ssh service enabled on the server I'm trying to inventory.

I'm using Toolbox through a GLPI-Agent 1.6.1 in a Windows 11 environment trying to access ssh through Toolbox like the prints for a Linux Ubuntu server

I made a new attempt on another access, but now on port 22 on the same IP I didn't get any results like the previous tests, I'm sending a new log and new prints to present what I was trying now

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/4b182e0a-fd37-4830-af25-b362be307ae9)

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/4fdb5634-6197-4868-b891-7ddbc5fabc1e)

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/b9a79ba5-d9b9-45a2-a279-2aafad8f78d8)

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/7fd10891-94ae-47d5-8386-8f9b5b2c79e1)

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/dda90d3d-4848-4280-b024-5d5a2c723951)

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/7a2892f8-472c-43df-978c-121f29352d5d)

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/25673260-19f1-48af-9e06-7d3421585cca)

[glpi-agent.log](https://github.com/glpi-project/glpi-agent/files/13492293/glpi-agent.log)

I'm sure it's working outside of Toolbox, I did the 2 authentications

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/13d1b9f2-1d65-4d9c-9858-defba91ab4f0)

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/45999d53-4d13-4709-95db-b6f21fc96b86)

--------------------------------------------------------------------------------------------
![image](https://github.com/glpi-project/glpi-agent/assets/102301295/98ada4f4-a660-4e54-a0e3-4419d091cffa)

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/16d51c4b-7a53-468e-82a8-34e3b0b633d5)

**Comment by g-bougard** [comment]
Indeed it seems recent OpenSSH server versions has dropped some key-exchange support level and the libssh2 1.8.2 we are using fails to negotiate the key exchange. I'm not sure but I think it's possible to downgrade the key-exchange support on sshd daemon, but this is not the right solution.

This libssh2/libssh2#626 PR should still have fix this issue in latest libssh2 versions.

To overcome this problem in GLPI-Agent on windows platform, we will need to upgrade the used perl & libraries. This is actually a huge work but recent updates on StrawberryPerl should help. But I don't think I'll have time to upgrade it before next year. I'll trigger you if I'm starting to upgrade perl support for windows build.

Now, to work around your issue, you should probably best use a GLPi-Agent installed on linux ;-)

**Comment by g-bougard** [comment]
Hi @erique-souza 

if you didn't give up, can you give a chance to latest nightly build ?
It uses now perl 5.38.2 with latest StrawBerry Perl environment which includes libssh2 updated to 1.10.0. I'm not sure libssh2 1.10.0 is sufficient as 1.11.0 is available and only this one seems to include the fix for https://github.com/libssh2/libssh2/pull/626.

**Comment by erique-souza** [comment]
> Hi @erique-souza
> 
> if you didn't give up, can you give a chance to latest nightly build ? It uses now perl 5.38.2 with latest StrawBerry Perl environment which includes libssh2 updated to 1.10.0. I'm not sure libssh2 1.10.0 is sufficient as 1.11.0 is available and only this one seems to include the fix for [libssh2/libssh2#626](https://github.com/libssh2/libssh2/pull/626).

It took me a while to test, but I managed to perform an inventory test via ssh with GLPI-Agent-1.8-gitea453479-x64.msi, now it was able to create a file in "C:\Program Files\GLPI-Agent\var\netdiscovery " with the IP of the server that I tried to inventory in the .xml extension with minimal information about the computer which, according to the log, used the netbios and ping protocols instead of the ssh connection, in fact the connection was unsuccessful even when testing authentication via modes: " ssh", "libssh2" and "perl" and also leaving the credentials unchecked

I tested ssh access before with credentials on port 22, and I was successful from the same machine, so I'm sure the connection exists

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/ebaff852-4cc4-438c-b3e7-0a229a8f9b4b)


![image](https://github.com/glpi-project/glpi-agent/assets/102301295/c6c51011-ad1a-4d57-acb5-fb2b007a237d)

My settings:
![image](https://github.com/glpi-project/glpi-agent/assets/102301295/2d920b93-4b7a-43d9-9423-7a5d832c5fc5)
![image](https://github.com/glpi-project/glpi-agent/assets/102301295/ce5c3a22-5f24-4e3b-8502-98725bc3c71c)
![image](https://github.com/glpi-project/glpi-agent/assets/102301295/b3aa211b-9d14-42f5-bd75-2f9eecb3f8bd)
![image](https://github.com/glpi-project/glpi-agent/assets/102301295/8d1a4ab0-927d-4b65-94bf-63048bf5e6c1)

[glpi-agent.log](https://github.com/glpi-project/glpi-agent/files/14213584/glpi-agent.log)

**Comment by g-bougard** [comment]
Hi @erique-souza 

it seems in the credentials definition you disabled `libssh2` mode. But I still see the following line in the log:
```
[Thu Feb  8 16:04:24 2024][error] #1, Can't trust 192.168.0.100 for ssh remoteinventory: -16 LIBSSH2_ERROR_FILE Unable to determine known_hosts location
```
So I guess the screenshot is wrong and only the result of your latest test.

Anyway the `Unable to determine known_hosts location` error leaves me in trouble. I'm not sure if it's a consequence of a not up-to-date libssh2 library or an error in the logic.

Do you have a `C:\Program Files\GLPI-Agent\var\.ssh\known_hosts` file  ?

**Comment by g-bougard** [comment]
Can you eventually try to run the following command from an administrative console and from GLPI-Agent installation folder ?
```
glpi-agent --logger=stderr --debug --debug --tasks=RemoteInventory --force --remote "ssh://erique:<password>@192.168.0.100"
```
Where you have to replace `<password>` by your password.

Then just share the output.

**Comment by erique-souza** [comment]
> Can you eventually try to run the following command from an administrative console and from GLPI-Agent installation folder ?
> 
> ```
> glpi-agent --logger=stderr --debug --debug --tasks=RemoteInventory --force --remote "ssh://erique:<password>@192.168.0.100"
> ```
> 
> Where you have to replace `<password>` by your password.
> 
> Then just share the output.

Follow the result
![remoteinventory](https://github.com/glpi-project/glpi-agent/assets/102301295/6487f037-51a2-4425-995d-521c35934d6b)


Regarding print, I did some extra tests on each of the modules, checking the "ssh" check box, I did the scanner, then I checked "libssh2" I did the scanner, same thing for "perl" and then I did the same test leaving unchecked, this is the sequence that I followed and that was recorded in this log, it was just for testing even to exhaust the attempts.


About the file in the directory you asked, C:\Program Files\GLPI-Agent\var\.ssh\known_hosts is not created, it is enabled to show hidden items, so this is not the case either

The only file that was created when I tested with Toolbox was the one indicated in the log, which was 192.168.0.100.xml in C:\Program Files\GLPI-Agent\var\netdiscovery

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/2a177dfb-c611-42f5-a6f6-232e2fbe36f8)

**Comment by g-bougard** [comment]
Hi @erique-souza 

your output is not useful as the glpi server seems not reachable. What happened to your GLPI server ?

Eventually, you can ask for save the inventory in the current folder this way:
```
glpi-agent --config=none --logger=stderr --debug --debug --tasks=RemoteInventory --force --local=. --remote "ssh://erique:<password>@192.168.0.100"
```

Then as administrator, can you also try to create the `var/.ssh` folder manually ? Then run again the task from ToolBox ?

Can you confirm the agent is running with administrator privileges ? I mean: is run from an administrative console when run from the console and you're joining the agent running as a service when using toolbox.

**Comment by erique-souza** [comment]
> your output is not useful as the glpi server seems not reachable. What happened to your GLPI server ?

I had put an invalid link on purpose, I thought it was not mandatory for Toolbox, because on the server in the registered task I had put the target to folder instead of server0, but I now made a new note to the server and corrected it to a glpi valid for further testing

I did a new test via Toolbox to see if anything changed, I believe there were no changes compared to previous tests, of course apart from the attempt to connect to the glpi server which apparently worked

[glpi-agent-server-ok.log](https://github.com/glpi-project/glpi-agent/files/14279097/glpi-agent-server-ok.log)

I also created the .ssh folder as requested in the directory's /var, restarted the glpi-agent service and tried to do the inventory via Toolbox, without any changes, as shown in the log below

[glpi-agent-ssh-paste-create-toolbox.log](https://github.com/glpi-project/glpi-agent/files/14279117/glpi-agent-ssh-paste-create-toolbox.log)

On the other hand, I tried again after the .ssh folder was created, that first command that forced the remote inventory task via ssh and now I was able to perform the ssh inventory via terminal, as expected, it created the complete remote server inventory file via terminal , Toolbox couldn't make it work, but the task is working now, I believe it was the lack of the folder, the known_hosts file was also created as expected too

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/84c2c024-acfb-4954-b301-f16d9e5e937e)

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/47166232-8bac-4969-b79c-3b7abaefde56)

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/6f5ccac6-434b-4e99-8788-30f18a49c6da)

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/038ca258-ae83-464e-9784-efc772da5b31)

I believe that at least one of the problems with the remote inventory task forced via terminal was that glpi-agent had not created this .ssh folder within the var, I had to create it manually

I also tested the first command and it did the inventory in GLPI as expected via the terminal, forcing the remote inventory task
![image](https://github.com/glpi-project/glpi-agent/assets/102301295/5e59080d-81d9-405f-a4e7-200cfc09d587)
![image](https://github.com/glpi-project/glpi-agent/assets/102301295/348b092d-1471-40c9-95c3-6cb9d2d7f4c6)


> Can you confirm the agent is running with administrator privileges ? I mean: is run from an administrative console when run from the console and you're joining the agent running as a service when using toolbox.

Yes, I am running both the terminal and glpi-agent with maximum privileges on the Windows operating system

**Comment by g-bougard** [comment]
Hi @erique-souza 

I just pushed a fix related to libssh2 usage with ToolBox on windows: the agent was not able to find the right path to the `var` folder. Indeed I found you even should see a `C:\.ssh` folder which should only contain an empty `known_hosts` file. With the next nightly build this should be fixed. If you find that folder, you can safely remove it.

Anyway, in my test, the `var/.ssh` folder was created automatically when I run the agent with the commandline I proposed to you. So I actually don't understand why it failed with you. Maybe I or you missed something. But this won't be an issue if ToolBox creates it after you install the next nightly build. If you want to test earlier, you should find the development build in the Windows-Build artifact on that [GH Actions run](https://github.com/glpi-project/glpi-agent/actions/runs/7917165772) when finished.

**Comment by g-bougard** [comment]
Hi @erique-souza 

for your information, I updated provided libraries and now glpi-agent will come with OpenSSL 3.2.1 & libssh2 1.11.0. Latest nightly build still includes them.

**Comment by erique-souza** [comment]
> Hi @erique-souza
> 
> for your information, I updated provided libraries and now glpi-agent will come with OpenSSL 3.2.1 & libssh2 1.11.0. Latest nightly build still includes them.

Perfect, I did a new test using Toolbox with the Nightly build of GLPI-Agent: GLPI-Agent-1.8-git59e6e18c-x64

I noticed that it now created the .ssh folder when starting the inventory task via Toolbox, as expected

I was able to perform the ssh inventory using the libssh2 protocol
![image](https://github.com/glpi-project/glpi-agent/assets/102301295/02fa6201-9edb-4a0f-a044-0501352bdaa3)

I placed a valid server for sending, and forced the inventory, the inventory worked as expected and the inventory arrived on the GLPI server

Below is the complete log:
[glpi-agent.log](https://github.com/glpi-project/glpi-agent/files/14559420/glpi-agent.log)

Thanks for your support, you can close this topic in git
