### ISSUE TITLE
Unable to export Toolbox inventory results

### ISSUE THREAD

**Issue by erique-souza** [glpi-project/glpi-agent#533]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Still not applicable

### Describe the bug

With a local inventory through Toolbox already carried out, in the results tab, select the inventoried items and click on the 2 individual export or complete data export buttons, none of the 2 buttons worked for export

I didn't get to test with remote inventory or SNMP inventory

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/4fe25fba-1b88-444c-a0db-6931a80c35fd)

### To reproduce

- Make a local inventory in the "Inventory tasks" tab in Toolbox
- Try exporting the result in the "Results" tab

### Expected behavior

Inventory export

### Operating system

Windows

### GLPI Agent version

1.6.1

### GLPI version

Not applicable

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

**Comment by g-bougard** [comment]
Hi @erique-souza 

thank you for your report, I confirm the bug. I'll try to fix it quickly.

**Comment by g-bougard** [comment]
When changing the buttons design, I forgot to set a value to the buttons.
Next nightly build will fix this problem or you can still apply the fix from c768b23. For example, you can just download the fixed `results-list.tpl` file other the one you'll find in your `share/html/toolbox` installed folder.
