### ISSUE TITLE
500 Can't connect

### ISSUE THREAD

**Issue by blainvillem** [glpi-project/glpi-agent#54]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Is your help request related to a problem?

[error] [http client] communication error: 500 Can't connect to XXX.fr:443 (Bad file descriptor)
[error] No answer from server at https://XXX.fr/plugins/fusioninventory/

### Expected behavior

No error in the logs and information sent to GLPI

### Actions you've considered

Should we use http?

**Comment by g-bougard** [comment]
Hi @blainvillem 
to debug any ssl support problem, start by enabling `debug=2` in agent configuration or set it in registry if you're running agent on windows and don't forget to restart the service. You can also try by running `glpi-agent` script with `--debug --debug` options.

**Comment by blainvillem** [comment]
I have activated the debbug log level 2.
I don't see any additional information, but by deactivating the SSL check, the post goes back to GLPI.

**Comment by g-bougard** [comment]
If you have an auto-signed certificate server, you should use `ca-cert-file` option.

**Comment by blainvillem** [comment]
That's the problem, it's not a self-signed certificate but a certificate issued by the certification authority DegiCert with a validity period of one year.

**Comment by g-bougard** [comment]
What is the public official CA Cert Root link of your certification authority ?

**Comment by g-bougard** [comment]
Hope you have obtained your answer.
Feel free to reopen if you have further related questions.
