### ISSUE TITLE
Error install GLPI-agent Ubuntu 22.04.3

### ISSUE THREAD

**Issue by ofprieto** [glpi-project/glpi-agent#541]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Install glpi-agent on ubuntu 22.04.3 LTS present the next error , 
![bug-glpiagent](https://github.com/glpi-project/glpi-agent/assets/4383194/685e3824-2d42-4374-9b5a-99c3d8e49b34)

### To reproduce

wget https://github.com/glpi-project/glpi-agent/releases/download/1.6.1/glpi-agent-1.6.1-linux-installer.pl
sudo perl glpi-agent-1.6.1-linux-installer.pl

### Expected behavior

don´t install

### Operating system

Linux

### GLPI Agent version

1.6.1

### GLPI version

10.0.10

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.3.3

**Comment by g-bougard** [comment]
Hello @ofprieto 

thank you for your report.

This issue has been fixed few days ago in 854ee13d869404f4ee318d06ed4a627ea9a0283e.

This issue implies the current configuration is finally not kept. So you'll have to reconfigure your agent. Sorry for this inconvenient.

You can use [latest nightly build](https://nightly.glpi-project.org/glpi-agent/) to avoid the problem on other linux computers.
