### ISSUE TITLE
ESXI (vmware) - install on esxi !!!? how

### ISSUE THREAD

**Issue by apracz** [glpi-project/glpi-agent#55]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Professional support

Still not applicable

### Is your help request related to a problem?

how i install agent on esxi ?

### Expected behavior

.

### Actions you've considered

.

### Additional context

.

**Comment by g-bougard** [comment]
If you have your ESX installed on a supported platform (linux or windows), just install the agent as on any normal computer.
If you're using remote ESX dedicated platform, you need to use ESX task. For that, you can first make tests with [glpi-esx](https://glpi-agent.readthedocs.io/en/latest/man/glpi-esx.html) script.
