### ISSUE TITLE
[1.7] useragent remains 1.6.1

### ISSUE THREAD

**Issue by TheRoby** [glpi-project/glpi-agent#568]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Hi,
I update GlpiAgent on my computer with 1.7 (before in 1.6.1) but after update (2 times ...) in GLPI UserAgent remains 1.6.1

![image](https://github.com/glpi-project/glpi-agent/assets/6053818/f299ea6b-7eb9-425d-978e-ffbff9b7bed2)
![image](https://github.com/glpi-project/glpi-agent/assets/6053818/89b37428-311e-432f-ade3-9a8aea2c8cbc)

### To reproduce

1. add a computer with 1.6.1 agent
2. upgrade agent to 1.7
3. request new inventory
4. useragent remains GLPI-Agent_v1.6.1

### Expected behavior

except to be 1.7
![image](https://github.com/glpi-project/glpi-agent/assets/6053818/1ff4bce2-82d6-42b9-a690-b8e518501630)

### Operating system

Windows

### GLPI Agent version

1.7

### GLPI version

10.0.11

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.3.4

**Comment by g-bougard** [comment]
Hi @TheRoby 

the reason the UserAgent remains the previous one is probably the inventory wasn't imported. You should first check the glpi-agent journal for an error.

**Comment by TheRoby** [comment]
> Hi @TheRoby
> 
> the reason the UserAgent remains the previous one is probably the inventory wasn't imported. You should first check the glpi-agent journal for an error.

Sorry for that ... yes last inventory was 15/12/2023 :(

my apologies :) Happy holidays!
