### ISSUE TITLE
Virtual machine is not imported into assets->computers 

### ISSUE THREAD

**Issue by Badkempachi** [glpi-project/glpi-agent#57]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Is your help request related to a problem?

I can't import the virtual machine in assets->computers. The virtual machine is displayed in the GLPI Inventory plugin, but I have not progressed beyond this point.

Virtual machines are deployed through the Hyper-V hypervisor.
### Expected behavior

After installing the agent on the virtual machine, I want to see it added to assets->computers

### Actions you've considered

Installed the latest nightly builds, changed import rules

**Comment by g-bougard** [comment]
Hi @Badkempachi 
please report the agent version and the agent log. `Additional context` section is made for that ;-)

**Comment by Badkempachi** [comment]
> Hi @Badkempachi please report the agent version and the agent log. `Additional context` section is made for that ;-)

GLPI-Agent_v1.1-git3042142e
![glpierror3](https://user-images.githubusercontent.com/97535165/151561151-216bc673-2043-4bce-9ae8-2b7319aff731.png)
![glpierror2](https://user-images.githubusercontent.com/97535165/151561156-c2803319-0839-43e6-bb16-ebae91c44583.png)
![glpierror4](https://user-images.githubusercontent.com/97535165/151561157-8e1e2803-6c95-46f6-a58c-e37eb76cf328.png)
[glpi agent log.txt](https://github.com/glpi-project/glpi-agent/files/7959241/glpi.agent.log.txt)

**Comment by g-bougard** [comment]
Okay, I see a problem with the `description` property of `monitor`, it is an integer in JSON and the server expects a string there.
For now, you should just add "monitor" in `no-category` agent option. You can do it in registry, restart the service and force an inventory.
I'll add a check on agent side so next nightly build should work properly in that case and set it as a string.

**Comment by g-bougard** [comment]
Hi @Badkempachi 
next nightly build should fix this issue.

**Comment by Badkempachi** [comment]
thanks, night build fixed the problem
