### ISSUE TITLE
Software that is installed separately for the user is not listed in the software inventory for the Windows client

### ISSUE THREAD

**Issue by jamecook** [glpi-project/glpi-agent#576]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Some software was missing from the software inventory results, and then I found that the software that was installed separately by the user。

### To reproduce

1、download GitHub Desktop
2、install GitHub Desktop
3、 manually run glpi-inventory.bat under administrator permissions to inventory

### Expected behavior

1. I can see the installed GitHub Desktop in the control panel
2. But I can't find the GitHub Desktop information in the manual inventory results

I've found that the information about the software installed separately by the user should be saved in HKEY_CURRENT_USERSOFTWAREMicrosoftWindowsCurrentVersionUninstal。

### Operating system

Windows

### GLPI Agent version

1.7

### GLPI version

10.0.11

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.3.4

**Comment by g-bougard** [comment]
Hi @jamecook 

by default this is not inventoried, but you can use an option to inventory such kind of installation: [--scan-profiles](https://glpi-agent.readthedocs.io/en/latest/configuration.html#scan-profiles)

When using this option, the agent looks for software installed and also for virtual machines installed in users profiles.
