### ISSUE TITLE
Windows Agent 1.7.1 - glpi-netinventory - LibXML required library error

### ISSUE THREAD

**Issue by SylvieCoz** [glpi-project/glpi-agent#577]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

We were successfully using **netinventory** with Windows GLPI agent 1.4 until now.
I just upgraded to agent **1.7.1** on a server and now netinventory triggers a "Can't load XML::**LibXML required library**"

### To reproduce

1. On Windows, install GLPI agent 1.7.1 (with netinventory installed)
2. Open a Powershell as admin
3. Run
`& "C:\Program Files\GLPI-Agent\perl\bin\glpi-agent.exe" "C:\Program Files\GLPI-Agent\perl\bin\glpi-netinventory" --host xxx.xxx.xxx.xxx`
(where xxx.xxx.xxx.xxx is the IP of the host for which you want a SNMP inventory)

Error is triggered :
`Thread 1 terminated abnormally: Can't load XML::LibXML required library`

### Expected behavior

The XML of a SNMP inventory is expected 😃 

### Operating system

Windows

### GLPI Agent version

1.7

### GLPI version

10.0.x (See additional context below)

### Additional context

Server runs on GLPI 10.0.7 but does'nt impact this issue (the bug occurs before we try to send anything to the server)

**Comment by g-bougard** [comment]
Hi @SylvieCoz 

please don't run glpi-netinventory script this way.

Better use the BAT scripts provided in the glpi-agent installation folder. And if this doesn't work well under PS console, use a CMD console.

If you really need to run this way, consider glpi-agent.exe is indeed the perl binary and so you need to provide the [Perl option](https://perldoc.perl.org/perlrun) to include GLPI-Agent library:
```
"C:\Program Files\GLPI-Agent\perl\bin\glpi-agent.exe" -I "C:\Program Files\GLPI-Agent\perl\agent" "C:\Program Files\GLPI-Agent\perl\bin\glpi-netinventory" --host xxx.xxx.xxx.xxx
```
