### ISSUE TITLE
Fail to run netdiscovery through the toolbox agent when there's a special character @ on password

### ISSUE THREAD

**Issue by arthurrschaefer** [glpi-project/glpi-agent#582]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

When adding the credentials for SSH on the Agent Toolbox and this credential has the character @ on it, the agent can't execute the inventory.

I tried with different special characters like ! . # $ and it seems to work. Just with @ the agent can't login.

### To reproduce

1. Activate toolbox
2. Create the range
3. Add credentials to it
4. Create credentials
5. Create scheduling
6. Create inventory task
7. Run inventory task

### Expected behavior

Run and find the linux servers with SSH enabled and correct password.

### Operating system

Linux

### GLPI Agent version

1.7

### GLPI version

10.0.11, Not applicable

**Comment by g-bougard** [comment]
Hi @arthurrschaefer 

next nightly build should fix this issue.
