### ISSUE TITLE
Incorrect serial number on USB webcam

### ISSUE THREAD

**Issue by efgiese** [glpi-project/glpi-agent#586]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

So far we have used the glpi agent in version 1.5.
To inventory USB webcams, I activated the import of devices. For a Logitech C920 Pro HD webcam, a different serial number is transmitted than the one on the packaging.

Even with the new agent 1.7.1 the problem still exists.

How can the problem be solved?

### To reproduce

1. Connect a usb webcam C920 PRO HD webcam to the computer
2. Take an inventory
3. Check the serial number on the packaging and in GLPI

### Expected behavior

The correct serial number should be displayed.

### Operating system

Windows

### GLPI Agent version

1.7

### GLPI version

10.0.10

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.3.3

**Comment by g-bougard** [comment]
Hi @efgiese 

the problem with USB devices is by default we can only catch the usb interface serial number and this is not the device packaging one. Indeed, the only kind of device for which we don't have such a problem is usb disk drives. All other usb devices has this problem. If we want to get the right S/N, we need to know how to get it using some manufacturer tools, but these tools are rarely provided and even more rarely will documented.

So, sorry, unless you know how to get it, we won't be able to fix that problem.

You should probably first open an issue on your device manufacturer support to ask them how to get the serial number by software. Then if you have an answer which can help us, we may include a method to find the expected S/N.

I'm closing the issue as we can't do anything right now, but feel free to reopen if you finally get a manufacturer positive answer.
