### ISSUE TITLE
AnyDesk Remote Mgmt Inventory and the customized version of its Client Application.

### ISSUE THREAD

**Issue by homebrewtainy** [glpi-project/glpi-agent#59]
### Documentation

Yes, I read it

### Professional support

I still have but want a public following to inform the community

### Is your feature request related to a problem?

A large part of the " AnyDesk Client Software " installations are done with a "customized" version of it.

This method allows the creation of a deployment package containing preconfigurations, security rules, branding, and more.
https://youtu.be/KbRKzDWd-BA?list=PLlEnzX2FLqbs_GC8rUUn4I5rwMJFwki8n

In this case, AnyDesk Software GmbH must assign a "prefix" attached to the user account which generated the "Customized AnyDesk Client".
This deployment behavior is commonly used on MS-Windows environments

This results in a `_anydesk_config` folder no longer in the expected form `C:\ProgramData\AnyDesk\system.conf` but in this form:
`C:\ProgramData\AnyDesk\ad_#hexnum#\system.conf` for example `C:\ProgramData\AnyDesk\ad_a0b2c3d4\system.conf`
This form of configuration file is then ignored by the inventory `Inventory\Generic\Remote_Mgmt\AnyDesk.pm`

### Expected behavior

Is there a way to allow the `AnyDesk.pm` module to consider these installation configurations, as they are officially offered by AnyDesk Software GmbH?

### Alternatives you've considered

The GLPI Agent being installed, on MS-Windows, by running an MSI file, manual modification, on a case-by-case basis, of the `AnyDesk.pm` file is not a sustanable solution.

Thank you for your attention.

Regards.

**Comment by g-bougard** [comment]
Hi @homebrewtainy 
thank you for this request.
As far I remember, this should definitively not be a big deal to check also for `C:\ProgramData\AnyDesk\ad_#hexnum#\system.conf` file.
What logic should we use ? Check for `C:\ProgramData\AnyDesk\ad_#hexnum#\system.conf` and then for `C:\ProgramData\AnyDesk\system.conf` or first for `C:\ProgramData\AnyDesk\system.conf` ?
The question is more: is it possible the 2 files exists and then what should we hav to do in that case.

Another question: is there the same feature for unix systems ? If yes, have you any hint to deal also with that case ?

**Comment by g-bougard** [comment]
Hi @homebrewtainy 

can you try [AnyDesk.pm](https://raw.githubusercontent.com/glpi-project/glpi-agent/61212a8b93c9dffd05936af9605d2d9655ca59fe/lib/GLPI/Agent/Task/Inventory/Generic/Remote_Mgmt/AnyDesk.pm) from #61 PR ?

**Comment by homebrewtainy** [comment]
Hi @g-bougard,

Work fine ! 

Successfully tested on a workstation under MS-Windows 10 Pro this evening.

It may happen that several instances of AnyDesk are present on the same environment.
I will test this ASAP.

Thanks for the improvement :-)

**Comment by g-bougard** [comment]
Hi @homebrewtainy 

thank you for your feedback.

Do you know if the feature should also be supported for unix systems ?

If there's more than one instance, actually the update will only report the first found. I'll check what's possible in that case.

**Comment by g-bougard** [comment]
Hi @homebrewtainy 

can you try [the updated AnyDesk.pm](https://raw.githubusercontent.com/glpi-project/glpi-agent/cd4f4849c1887cbc81f7d70b86b641f6a15b9a55/lib/GLPI/Agent/Task/Inventory/Generic/Remote_Mgmt/AnyDesk.pm) from #61 with multiple AnyDesk installations ?

**Comment by homebrewtainy** [comment]
Hi @g-bougard 
> 
> Do you know if the feature should also be supported for unix systems ?
> 
I need to do some testing on non-Wayland Desktop Linux VMs.
I need a little time for this.

> If there's more than one instance, actually the update will only report the first found. I'll check what's possible in that case.

On MS-Windows, it is confirmed that in case two or more instances of AnyDesk Client (with specific policies rules) are installed, you can find either:
 - an Anydesk Client configuration file in :
`C:\ProgramData\AnyDesk\system.conf`

 - and one or many other configurations files present in :
`C:\ProgramData\AnyDesk\ad_#hexnum1#\system.conf`
`C:\ProgramData\AnyDesk\ad_#hexnum2#\system.conf`
`C:\ProgramData\AnyDesk\ad_#hexnumN#\system.conf`

**Comment by g-bougard** [comment]
Thank you.
The last update should make the job for MS-Windows case. You just need to test it and confirm me this works as expected.
Take your time for linux case, there's no urgency. I'll eventually merge #61 and update linux case later if needed.

**Comment by homebrewtainy** [comment]
Sorry, I had answered your question "wrongly".

It's well confirmed, it works correctly, in any case with two AnyDesk Client instances under Windows.

Before merge #61:

![image](https://user-images.githubusercontent.com/74141901/151967163-db749d2d-6715-42b5-8736-0c6678e175c1.png)

After merge #61:

![image](https://user-images.githubusercontent.com/74141901/151967186-fb04bcfe-6e7b-4dc6-9a2e-c475aaffbc45.png)

No trouble in log file.
<details><summary>glpi-agent.log</summary><pre>
[Tue Feb  1 13:01:21 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::OS
[Tue Feb  1 13:01:26 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt
[Tue Feb  1 13:01:26 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt::AnyDesk
[Tue Feb  1 13:01:26 2022][debug] Found AnyDesk ID : 3########
[Tue Feb  1 13:01:26 2022][debug] Found AnyDesk ID : 5########
[Tue Feb  1 13:01:26 2022][debug] Running GLPI::Agent::Task::Inventory::Generic::SSH
</pre></details>

Great !!

**Comment by g-bougard** [comment]
Hi @homebrewtainy 
I merged the PR so the feature will be available in next nightly for win32 platform.
I'm keeping the issue open until you make us a feedback about the linux platform concern.

**Comment by g-bougard** [comment]
Hi @homebrewtainy 
I'm closing the issue as I released today [GLPI-Agent v1.1](https://github.com/glpi-project/glpi-agent/releases/tag/1.1).
Feel free to open a new dedicated issue if you have more information about linux customized AnyDesk versions.
Thank you for your help.
