### ISSUE TITLE
 1.7.1 does not correctly install on intel macs

### ISSUE THREAD

**Issue by we-sell-bags** [glpi-project/glpi-agent#598]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

osx:12.7.2. intel

GLPI-Agent-1.7.1_x86_64.pkg

the installer starts to install & a directory GLPI Agent. appears in teh application folder , but before the install finishes it dissapears

Then. the installer states "sucessful"

### To reproduce

just install & take standard options for osx

### Expected behavior

it should install & it used to install at ver 1.4

### Operating system

MacOSX

### GLPI Agent version

1.7

### GLPI version

10.0.12

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.3.4

**Comment by g-bougard** [comment]
Hi @we-sell-bags 

as you're speaking about "1.7.1" version in the title, did you try other agent than 1.4 ? Maybe 1.5 or 1.6.1 ? Did you try 1.7.1 on older or other MacOSX system with success ?

Have you checked any system log that could provide any clue ?

To be honest, you're the first to complain about such a problem and with so few information, I don't know where to start.

Have you an antivirus that could have put the folder in quarantine ?

**Comment by we-sell-bags** [comment]
Hi,  yes the latest version...... 1.7.1
and it has NEVER been a problem before.
AV software would flag them, and   yes, there were older versions installed ,before this one and they worked fine.
also the log & quarantine is clear.
ill recheck the av , but it appears it was not the cause.

**Comment by alberto772** [comment]
I've the same problem with Mac with intel silicon, update from 1.6 to 1.7.1 and the Process still remain in waiting state and not work anymore
root@MACM001 ~ # ps -ef | grep glpi
    0  8182     1   0  4:21PM ??         0:00.89 glpi-agent: waiting   
    0  8190  8111   0  4:21PM ttys000    0:00.00 grep glpi

**Comment by g-bougard** [comment]
Hi @we-sell-bags 

lastest is now 1.7.3, have you installation problems with that newer version ?

**Comment by alberto772** [comment]
Solved with this new version
I confirm that the problem was with version 1.7 and 1.7.1
A

**Comment by we-sell-bags** [comment]
it seems ok now...... for  1.7.2 & 1.7.3
on intel macs

**Comment by g-bougard** [comment]
Thank you for the feedback,
so I can close this issue.
