### ISSUE TITLE
Task inventory vmware

### ISSUE THREAD

**Issue by sec1083** [glpi-project/glpi-agent#605]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

I am using glpi v10.0.11 and glpi inventory plugin v1.3.4. I created a task to inventory vmware, but the task does not execute. It is stoped in prepare mode. This task is the only task that does not work. The other tasks like netinventory, inventory and netdiscovery are running well.  

Available tasks :
- NetInventory (v6.1)
- WakeOnLan (v2.2)
- ESX (v2.10)
- Collect (v2.9)
- Inventory (v1.15)
- NetDiscovery (v6.1)
- RemoteInventory (v1.4)

I did not see nothing interesting in the logs about this error

### To reproduce

To reproduce you need to create a task on glpi to make an inventory from the vmware and execute it 

### Expected behavior

The expected behavior is the task running and somo informations on agent log file 

### Operating system

Linux

### GLPI Agent version

1.7

### GLPI version

10.0.11

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.3.4

**Comment by sec1083** [comment]
I found [debug] Skipping fusioninventory-agent-task-esx package as not installed, status='install ok unpacked'  in the debbug log with the command glpi-agent --debug. But i tried using this task on fusioninventory agent but the result is the same on glpi inventory plugin.

**Comment by g-bougard** [comment]
Hi @sec1083 

you're providing no evidence of any bug in glpi-agent. I can only assume you did something wrong with the ESX task configuration in GLPI and if it's the case, you opened this issue at the wrong place.
Can you at least share the log part related to ESX task run ?

**Comment by sec1083** [comment]
![teste](https://github.com/glpi-project/glpi-agent/assets/160243417/5230d3d8-8be1-480a-9ec5-691aded4fda1)

Like i said, the unique task that does not working is this task. It stay in prepare mode more than days. The other tasks are working well, going from prepare to execute. Like i said i instaled all necessary packages and all is configured well. Despite all this, the task vmware still in mode prepare. You ask me about log, but i insist that the plugin is not working well with this specific task, the task simply do nothing. I think that if i try to execute in command line  glpi-esx --debug it will work well, but the plugin task exist to make this for me automatically

**Comment by sec1083** [comment]
I taked this log. Can somebody help me?

```
**[info] running task ESX**
[error] [http client] Can't decode JSON content, starting with:


<!DOCTYPE html>
<html lang="pt"       >
<head>
   <title>Autenticação - GLPI</title>

   <meta charset="utf-8" />
...
```
![image](https://github.com/glpi-project/glpi-agent/assets/160243417/6c850fbe-2007-440d-aff0-89e0074cce0a)

**Comment by g-bougard** [comment]
Hi @sec1083 

you're probably not using the right url but I can't be sure as you truncated the log. Check this documentation and read carefully the `Caution` note: https://glpi-agent.readthedocs.io/en/latest/configuration.html#server

**Comment by sec1083** [comment]
Hi @g-bougard 

I think if the url does not configured right all the tasks would not working, but the scenario is the opposite. All tasks are working well, less the vmware task.

**Comment by g-bougard** [comment]
Hi @sec1083 

all the tasks don't use the same protocol, so if you just think you're right and don't follow an expert advice for this reason, you will probably just miss an easy solution.

Actually, you didn't share a full log so we can't even tell you if the url is right or not. You only share a short part which shows us the agent is not reaching the server at the right place: so or the agent url is wrong, or the server configuration is wrong.
