### ISSUE TITLE
WinRM Remote scan not working | Always showing wrong credentials in GLPI agent toolbox

### ISSUE THREAD

**Issue by thasleemnazeer** [glpi-project/glpi-agent#608]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

I have successfully set up the WinRM service on the remote system, and the credentials are functioning correctly. However, when attempting to run the inventory task for WinRM remote scanning, the following error occurs. I am utilizing GLPI agent version 1.7.1 and have attempted both domain and local credentials.

```
[info] Starting WinRM Local network scan task job...
[info] Running WinRM Local task...
[error] #1, [http client] authentication required, wrong credentials
[error] #1, [http client] authentication required, wrong credentials
[error] #1, [http client] authentication required, wrong credentials
[error] #1, [http client] authentication required, wrong credentials
[error] #1, [http client] authentication required, wrong credentials
[error] #1, [http client] authentication required, wrong credentials
[error] #1, [http client] authentication required, wrong credentials
[info] #1, Netdiscovery result for 192.XXX.XX.X saved in C:/GLPI-Agent/netdiscovery/192.XXX.XX.X.xml
[info] #1, WinRM Local: WinRM Local network scan done

```
### To reproduce

Attempt to perform a remote scan using the agent from one Windows machine to another Windows machine.

### Expected behavior

Showing the wrong
<img width="927" alt="Glpi 1" src="https://github.com/glpi-project/glpi-agent/assets/142693456/0807debf-ef3e-4178-93ac-9edade62da29">

### Operating system

Windows

### GLPI Agent version

1.7

### GLPI version

10.0.11

**Comment by g-bougard** [comment]
Hi @thasleemnazeer 

are you using some special characters in the password ? Your problem can be related to #582.

**Comment by thasleemnazeer** [comment]
Hi @g-bougard. Appreciate your comment. No special characters are using in the password. I have tried with AD login and local credentials as well.

**Comment by g-bougard** [comment]
You should check the following prerequisite: https://glpi-agent.readthedocs.io/en/latest/tasks/remote-inventory.html#pre-requisite

As far I know, only a local user with admin privileges can be used for remote inventory with WinRM.

**Comment by g-bougard** [comment]
Hi @thasleemnazeer 

I'm closing this issue without your feedback.

You may want to retry with latest version which is now 1.9.

Then feel free to reopen or open a new ticket.
