### ISSUE TITLE
Add and remove switch port all the time

### ISSUE THREAD

**Issue by francisco-vilaca** [glpi-project/glpi-agent#612]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

GLPI is adding and removing switch ports every scan 

![image](https://github.com/glpi-project/glpi-agent/assets/144910601/a8a36f4b-de91-4226-ab1a-3c463d92f5b0)

### To reproduce

.

### Expected behavior

.

### Operating system

Linux

### GLPI Agent version

1.7

### GLPI version

10.0.12

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.3.4

**Comment by g-bougard** [comment]
Hi @francisco-vilaca 

please open your issue on [GLPI project itself](https://github.com/glpi-project/glpi/issues) as you're speaking about a GLPI issue.

**Comment by francisco-vilaca** [comment]
instead of closing the case as admin you can simply move the post to the correct category. for me is the agent that those the scan is in the agent log that i can see the log of the scans so it make sense to open in agent section

**Comment by g-bougard** [comment]
Sorry, I'm only admin for glpi-agent project and can't move issues from here to GLPI project.
