### ISSUE TITLE
Switch port connection

### ISSUE THREAD

**Issue by francisco-vilaca** [glpi-project/glpi-agent#613]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

I have created my CCTV cameras on GLPI by hand, scene they do not support snmp protocol. On the other hand my switches do the same network do support snmp protocol but for some reason one the ports connections GLPI do not recognize that the mac-address that is connected to that port already exist on GLPI and connect that object to that port. Instead, live the connection in blank.

I decide to manually connect all the cameras to the correct switch ports, but on the next scan, GLPI removed all the connections and left all blank again.

There is a way to stop GLPI to remove the connection without stopping the scan?

![image](https://github.com/glpi-project/glpi-agent/assets/144910601/68d13ebd-a020-400a-8fcc-abc748a5cc42)

### To reproduce

.

### Expected behavior

.

### Operating system

Linux

### GLPI Agent version

1.7

### GLPI version

10.0.12

### GLPIInventory plugin or FusionInventory for GLPI plugin version

GLPI Inventory v1.3.4

**Comment by g-bougard** [comment]
Hi @francisco-vilaca 

closing for the same reason than #612 ... and please, stop using uppercase only titles.

**Comment by francisco-vilaca** [comment]
i did not understand, i cannot use uppercase in the title?

**Comment by g-bougard** [comment]
This is just a wrong practice as this is just annoying for people who are managing the issues.
