### ISSUE TITLE
Watchguard M5600 import failed

### ISSUE THREAD

**Issue by romnvll** [glpi-project/glpi-agent#627]
### Bug reporting acknowledgment

Not applicable

### Professional support

None

### Describe the bug

Bonjour,
quand je veux detecter mes boitiers watchguard(M5600), j'ai cette erreur :

Import refusé [type]: Networking, [name]: Member2, [mac]: 00:00:5e:00:01:05, [ips]: 10.3.0.1, 192.168.19.1, 192.168.20.1, 192.168.28.254, 192.168.29.254, 192.168.30.2, 192.168.92.1, 192.168.93.1, 192.168.95.1, 192.168.96.1, 5.226.8.139

je ne sais pas ce qu'il manque comme information, ni pourquoi le device est refusé .

est ce que c'est le numero de série qui ne remonte pas ?

Si c'est le cas, je ne sais pas bien comment l'integrer ...

### To reproduce

Result of `glpi-netdiscovery --first IP --last 1ip --credentials version:2c,community:public --debug`:
```
<REQUEST>
  <CONTENT>
    <DEVICE>
      <AUTHSNMP>1</AUTHSNMP>
      <CONTACT>admin@Unknown</CONTACT>
      <DESCRIPTION>M5600</DESCRIPTION>
      <DNSHOSTNAME>192.168.X.X</DNSHOSTNAME>
      <IP>192.168.X.X</IP>
      <IPS>
        <IP>10.3.0.1</IP>
        <IP>192.168.19.1</IP>
         </IPS>
      <LOCATION>Qq part</LOCATION>
      <MAC>00:00:5e:00:01:05</MAC>
      <MANUFACTURER>WatchGuard</MANUFACTURER>
      <MODEL>M5600</MODEL>
      <SNMPHOSTNAME>Member2</SNMPHOSTNAME>
      <TYPE>NETWORKING</TYPE>
      <UPTIME>131 days, 07:10:13.77</UPTIME>
    </DEVICE>
    <MODULEVERSION>5.1</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
```

### Expected behavior

Le modele ne rentre pas dans la base GLPI

### Operating system

Linux

### GLPI Agent version

1.5

### GLPI version

10.0.11

### GLPIInventory plugin or other plugin version

FusionInventory for GLPI (See additional context below)

**Comment by g-bougard** [comment]
Hi @romnvll 

yes, a serialnumber is missing.

You can try to enable the "Import & update rules (by MAC address)" rules. These rules can have side effects and this is why they are disabled by default. You have to test.

Or you can provide a [SNMP walk output in the right format](https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output) so we can try to integrate your device support in agent.

**Comment by romnvll** [comment]
Thank you, @g-bougard 
where can i send you the file ?

**Comment by g-bougard** [comment]
You can send it to: `gbougard <_at_> teclib <_dot_> com`

**Comment by romnvll** [comment]
Le support n'est pas possible puisque watchguard ne donne pas de serial dans les mibs
