### ISSUE TITLE
GLPI Inventory Task actors missing

### ISSUE THREAD

**Issue by walterdasilva** [glpi-project/glpi-agent#632]
### Bug reporting acknowledgment

Not applicable

### Professional support

Still not applicable

### Describe the bug

GLPI Inventory Task are missing actors set. Agent still running on device normally. after some time computer missing from assets computers and of course from glpi inventory task. assets return after next agent inventory but inventory task actors still missed

### To reproduce

install and set glpi inventory

### Expected behavior

glpi inventory task actors not missing

### Operating system

Linux

### GLPI Agent version

1.7.1

### GLPI version

10.0.13

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.5

**Comment by g-bougard** [comment]
Hi @walterdasilva 

as you're not describing a glpi-agent bug, but a symptom in GLPI, I have to convert your issue as a Q&A discusison where I'll try to give few some clues to understand what's going on.
