### ISSUE TITLE
Unable to install GLPI-Agent on XCP-NG

### ISSUE THREAD

**Issue by sdiwakar123** [glpi-project/glpi-agent#643]
Hi
We are Unable to install GLPI-Agent on XCP-NG Hypervisor. Let us know how to install it.

**Comment by g-bougard** [comment]
Hi @sdiwakar123 

what is XCP-NG Hypervisor ?

Please provide reference links when opening such question.

**Comment by sdiwakar123** [comment]
XCP-ng: the user-friendly, high-performance virtualization solution, developed collaboratively for unrestricted features and open-source accessibility. We are running our Virtual Infra on these Servers.

https://xcp-ng.org/

**Comment by g-bougard** [comment]
Okay, so assuming you're using latest version, 8.3, it means the host is based on CentOS 7. And I see included sources (https://updates.xcp-ng.org/8/8.3/base/Source/SPackages/) that probably a lot a perl library may miss.

Anyway, did you try to install our rpm package and, if yes, how ?

Can you eventually try to install with the [linux perl installer](https://github.com/glpi-project/glpi-agent/releases/download/1.7.3/glpi-agent-1.7.3-linux-installer.pl) with the following command line and report the output if it fails ?
```
perl glpi-agent-1.7.3-linux-installer.pl --distro=CentOS --verbose --install --server="http://your-server-url/"
```
It may fail on missing perl dependencies.

**Comment by sdiwakar123** [comment]
error: Failed dependencies:
        perl(Compress::Zlib) is needed by glpi-agent-1.7.3-1.noarch
        perl(Cpanel::JSON::XS) is needed by glpi-agent-1.7.3-1.noarch
        perl(Data::UUID) is needed by glpi-agent-1.7.3-1.noarch
        perl(DateTime) is needed by glpi-agent-1.7.3-1.noarch
        perl(Digest::SHA) is needed by glpi-agent-1.7.3-1.noarch
        perl(File::Which) is needed by glpi-agent-1.7.3-1.noarch
        perl(HTTP::Cookies) is needed by glpi-agent-1.7.3-1.noarch
        perl(HTTP::Daemon) is needed by glpi-agent-1.7.3-1.noarch
        perl(HTTP::Headers) is needed by glpi-agent-1.7.3-1.noarch
        perl(HTTP::Request) is needed by glpi-agent-1.7.3-1.noarch
        perl(HTTP::Status) is needed by glpi-agent-1.7.3-1.noarch
        perl(IO::Socket::SSL) is needed by glpi-agent-1.7.3-1.noarch
        perl(LWP) is needed by glpi-agent-1.7.3-1.noarch
        perl(LWP::Protocol::https) is needed by glpi-agent-1.7.3-1.noarch
        perl(LWP::UserAgent) is needed by glpi-agent-1.7.3-1.noarch
        perl(Net::HTTPS) is needed by glpi-agent-1.7.3-1.noarch
        perl(Net::IP) is needed by glpi-agent-1.7.3-1.noarch
        perl(Net::SSLeay) is needed by glpi-agent-1.7.3-1.noarch
        perl(Parallel::ForkManager) is needed by glpi-agent-1.7.3-1.noarch
        perl(Proc::Daemon) is needed by glpi-agent-1.7.3-1.noarch
        perl(Socket::GetAddrInfo) is needed by glpi-agent-1.7.3-1.noarch
        perl(Sys::Syslog) is needed by glpi-agent-1.7.3-1.noarch
        perl(Text::Template) is needed by glpi-agent-1.7.3-1.noarch
        perl(UNIVERSAL::require) is needed by glpi-agent-1.7.3-1.noarch
        perl(URI) is needed by glpi-agent-1.7.3-1.noarch
        perl(URI::Escape) is needed by glpi-agent-1.7.3-1.noarch
        perl(XML::LibXML) is needed by glpi-agent-1.7.3-1.noarch
        perl(YAML::Tiny) is needed by glpi-agent-1.7.3-1.noarch

Unable to install perl pakage.

**Comment by g-bougard** [comment]
With such a long list of missing dependencies, that would be hard to compile all missing dependencies. This is an operating system issue and we can't directly handle them. Anyway, you may try to install manually the missing packages by downloading them from CentOS7 repositories. If you have a test platform, you may test if enabling CentOS7 repositories can help, but don't enable them by default: use options to enable them only to install agent.

Now, you have 2 other alternatives to try:
1. Use snap package, but you'll probably have to install snapd from EPEL with `yum install snapd`. This is not a light installation so maybe this is not what you need.
   Check the documentation for installation there, but you need to install snapd befdore: https://glpi-agent.readthedocs.io/en/latest/installation/index.html#snap
2. Use AppImage package, but I'm not sure it works other a CentOS7 based OS: https://glpi-agent.readthedocs.io/en/latest/installation/linux-appimage.html

To be honest, this distro is now aged as always based on CentOS7. I hope they planed to migrate to a more recent based distro.

**Comment by g-bougard** [comment]
Hi @sdiwakar123 

I hope you finally managed to install glpi-agent in that environment.

Without any feedback, I'm closing this issue, but feel free to re-open if you think something is wrong in our packaging or comment to share your results.
