### ISSUE TITLE
Android agent 1.4 Can't scrool down when adding a server

### ISSUE THREAD

**Issue by loginone33** [glpi-project/glpi-agent#648]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Android agent 1.4 Can't scrool down when adding a server. On small screen I can see only until Password input, don't have acces to Devbice Type and custom serial. Scrool down not working, tested on couple of devices. Easy way to test is to put any device in landscape and it is clear that You cant scrool down anywhere in the app.
![20240417_131753](https://github.com/glpi-project/glpi-agent/assets/46689159/a8a7d1d0-003b-48e7-a8d5-5e0f4067cfd6)

### To reproduce

![20240417_131753](https://github.com/glpi-project/glpi-agent/assets/46689159/97bb705f-ac8c-4f6c-8b35-d9ff189c4eb9)

### Expected behavior

Scrool Down shoul;d just work.

### Operating system

Other (See additional context below)

### GLPI Agent version

1.4

### GLPI version

10.0.14

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.5

**Comment by trasher** [comment]
This is a android agent issue; you should report it here: https://github.com/glpi-project/android-inventory-agent

I cannot transfer this issue to the correct repository, so I just close.
