### ISSUE TITLE
Silent installation not possible with VBS script

### ISSUE THREAD

**Issue by eleducq** [glpi-project/glpi-agent#65]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Professional support

I still have but want a public following to help the community

### Is your help request related to a problem?

Unable to set up a silent installation via the VBS Script provided on the site.
I have used the /i /quiet options but it doesn't work, but when I remove them no problem via the graphical installation.
Here is my complete "SetupOptions" line:
SetupOptions = "/i /quiet ADD_FIREWALL_EXCEPTION=1 RUNNOW=1 HTTPD_TRUST='0.0.0.0/0' SERVER='http://192.1.6.223/front/inventory.php' TASKS=Deploy,Inventory,Collect"

Thanks for your answer and your time.

### Expected behavior

I expected the agent to install properly and silently without any problems.

### Actions you've considered

I have tried several different methods with only /i or only /quiet , or /S which is used in our current production script. 
I also tried running it with the FusionInventory agent uninstalled or not (which works fine when the agent is on the user's machine)

**Comment by g-bougard** [comment]
Hi @eleducq 
don't use `/i` in your `SetupOptions`, in script it is still defined at [L.448](https://github.com/glpi-project/glpi-agent/blob/336a7bba7ecff26e74aec40ed62ce24d775ba476/contrib/windows/glpi-agent-deployment.vbs#L448) as the MSI filename must follow it.

I should probably clarify that point in the VBS itself and in documentation.

**Comment by eleducq** [comment]
Thank you for your quick reply, so I removed /i and only left the /quiet but it still doesn't install my agent on my client machine.

**Comment by g-bougard** [comment]
You can check the system [Event Viewer](https://en.wikipedia.org/wiki/Event_Viewer) and look for **MsiInstaller** events. You may see an explicit error.
If this is not sufficient, try to set **Verbose** to `Yes` and run the installer. This will show you popups blocking the installer with verbose information.

**Comment by eleducq** [comment]
So I've already tried putting verbose into yes to try and figure out the silent deployment process, and it tells me the system architecture twice, the installation needed once, and what it will run :
```
Running: Msiexec.exe /i
"\\path\GLPI-Agent-1.0-x64.msi" /quiet ADD_FIREWALL_EXCEPTION=1 RUNNOW=1 HTTPD_TRUST='0.0.0.0/0' SERVER='http://192.1.6.223/front/inventory.php' TASKS=Deploy,Inventory,Collect
```
That's why I find it very strange...

**Comment by eleducq** [comment]
And he eventually deploys done, without installing the agent.

**Comment by g-bougard** [comment]
Have you checked **Event Viewer** ?
Have you try to run the shown command manually ?
You may also use an msiexec option to debug the run, just add something like `/L*V "C:\install.log"` before or just after `/quiet`

**Comment by eleducq** [comment]
Adding /L*V "C:\install.log" after /quiet generates this page.
![image](https://user-images.githubusercontent.com/98739327/152829073-d5c3bbc2-ff10-42f5-b60e-004cafd7de61.png)

And I don't observe anything in the Event Viewer.

**Comment by eleducq** [comment]
As far as I'm concerned, I have this in the event viewer, but I don't understand, I'm the administrator of my machine.
![image](https://user-images.githubusercontent.com/98739327/152829977-1289d117-6659-4ae6-927c-5a1a7cc5da23.png)

**Comment by eleducq** [comment]
The error on line 113 corresponds to the fact that you made me add /L*V "C:\install.log", I removed it and run it via an admin cmd and I find myself in the same pattern as before.


> So I've already tried putting verbose into yes to try and figure out the silent deployment process, and it tells me the system architecture twice, the installation needed once, and what it will run :
> 
> ```
> Running: Msiexec.exe /i
> "\\path\GLPI-Agent-1.0-x64.msi" /quiet ADD_FIREWALL_EXCEPTION=1 RUNNOW=1 HTTPD_TRUST='0.0.0.0/0' SERVER='http://192.1.6.223/front/inventory.php' TASKS=Deploy,Inventory,Collect
> ```
> 
> That's why I find it very strange...

**Comment by eleducq** [comment]
I've just fixed my problem, last question about the GPO setup, could you tell me how to run it as an administrator on all the user machines.

**Comment by g-bougard** [comment]
About `/L*V "C:\install.log"`, this should probably work with simple quote: `/L*V 'C:\install.log'`

Your event viewer was telling you should have run the script from an administrative console. The script itself doesn't require administrative rights, but msiexec does.

The screenshot is also showing you're installing GLPI Agent v1.0. Please, use [GLPI-Agent v1.1](https://github.com/glpi-project/glpi-agent/releases/tag/1.1) which has been released last friday and includes a fix related to silent installation (wrong logfile path set).

About GPO setup, sorry, I don't know.

**Comment by eleducq** [comment]
Thanks again for your help, I have indeed already downloaded the .msi of the 1.1 agent. I just put it in the script, and it works fine, I close the ticket.
