### ISSUE TITLE
Deployment Task Message is Garbled on Client

### ISSUE THREAD

**Issue by cautiouscoyote** [glpi-project/glpi-agent#655]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

When using the GLPI Inventory plugin to deploy a task on a client, and display a message afterwards, the formatting of this message is being screwed up: **carriage return and line feed characters** are being displayed instead of the proper new lines and what-not; see attached pictures.

### To reproduce

1. In the GLPI Inventory plugin, compose a deployment task with a package deployment action doing something whatever (can be some simple command).
2. Make sure to add a Message under User Interactions "after actions".
3. Let the client/agent do a run where it should pick up the deployment task.
4. Behold the garbled message being displayed on the client screen.

### Expected behavior

The message should be displayed on the client in the same markup with new lines as composed in the User Interactions field.

### Operating system

Windows

### GLPI Agent version

1.7.1

### GLPI version

10.0.11

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.5

### Additional context

Composed package action message:
![image](https://github.com/glpi-project/glpi-agent/assets/64739233/1598d060-7073-469b-96fd-7cc95f305475)

Actual message as displayed on client:
![image](https://github.com/glpi-project/glpi-agent/assets/64739233/5c44b1c5-3c08-4484-996b-939f49726ee8)

Have reported this matter earlier at the **issue page of the Inventory plugin** here:
https://github.com/glpi-project/glpi-inventory-plugin/issues/493
but it is suggested this is likely an agent issue, so there you have it.

**Comment by g-bougard** [comment]
Hi @cautiouscoyote 

can you make a test on one agent ?

First enable `debug = 2` in registry and don't forget to restart the service.

Then make an installation test and share the log part related to the installation.

This should help to know if it's an agent or a server issue.

**Comment by cautiouscoyote** [comment]
Hi @g-bougard,

Done! Please find attached:
- a **screenshot** of the result, that shows:
   1) a successful installation of a new deploymnt task, the 'IGS-viewer' application (the icon in the green pen stroke on the desktop to the mid-left)
   2) again a garbled desktop message following the deployment action.
- a **trimmed part of the logfile** at "debug2" level; I cropped it down to just the deployment task part, skipping the inventory lines and a load of package downloading lines, in order to keep the size of this shared log down a bit.

I am guessing the output you're looking for can be found at **around line 145** in the provided log section.


![glpi-agent_debug2-test](https://github.com/glpi-project/glpi-agent/assets/64739233/016cc6cb-83d5-4f86-83d6-d94bdf906b33)

[glpi-agent.trimmed.log](https://github.com/glpi-project/glpi-agent/files/15323869/glpi-agent.trimmed.log)

**Comment by g-bougard** [comment]
Okay, after some tests, I noticed you didn't select a "User Interaction Template". This parameter is required. In your case, the simplest one requiring only "OK" from the user is sufficient.

On my side, if I don't select a template, I obtain the same output than you. If I select a template, the output is correct.

The problem here seems in the plugin to me as there's a red asterisk on the UI Template but the form permits you to leave it empty.

Can you confirm it's okay for you when setting up a UI template ?

**Comment by cautiouscoyote** [comment]
"Can you confirm it's okay for you when setting up a UI template ?"

Done! And indeed, upon removing the installed test application "igs-viewer" and then forcibly re-running the deployment job, it got installed again as expected, while displaying a now properly formatted message box:

![glpi-agent_deployment-message_layout_ok](https://github.com/glpi-project/glpi-agent/assets/64739233/a4865cac-e4a6-4d53-9d29-9f9f8da31ce8)

In both cases though, first without and now with forced user action, the message box comes with an "OK" button.
In the first case the message box disappears after a while, in the latter case ... I may not have waited long enough for that; I manually pushed the OK button.

**Comment by g-bougard** [comment]
Hi @cautiouscoyote 

indeed, the format problem was really in GLPIInventory plugin. I proposed a PR to fix it.
