### ISSUE TITLE
No effect on configuration when "Tag" is set in agent.cfg

### ISSUE THREAD

**Issue by noszone** [glpi-project/glpi-agent#662]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

if during installation of agent, the tag is not set. Then, in agent.cfg when set the value of key, it does not give an effect. It's not showing on server side. Only if set in windows registry, the tag can appear.

### To reproduce

1. Install agent with empty tag value
2. Set Tag value in agent.cfg
3. Run inventory task
4. On Server side the agent tag field is empty

### Expected behavior

When key Tag set in agent.cfg, after inventory task it must appear on server side in agent tag field.

### Operating system

Windows

### GLPI Agent version

1.7.3

### GLPI version

10.0.14, Not applicable

### Additional context

GLPI version 10.0.15

**Comment by g-bougard** [comment]
Hi @noszone 

this is normal: on windows, by default, configuration is taken from registry where it is from agent.cfg on other OS.

If you want to take it from a file, you can start agent manually with the following parameters: `--config-file=<path-to>/agent.cfg`

And indeed, this is exactly what is done when you uses the portable version.

**Comment by teenwolf99** [comment]
@g-bougard What you suggested is a work-around, Can this be fixed to use the agent.cfg inside the etc folder which should give meaning to the default cfg file.

**Comment by g-bougard** [comment]
Sorry, there's nothing to fix here. This is how agent works on windows since years, even FIA was working this way: the default on windows is to use registry and the registry can be setup by glpi-agent windows installer. If you want to change the default comportment of glpi-agent on windows, just use the option.
