### ISSUE TITLE
please add containerd and kubernetes support 

### ISSUE THREAD

**Issue by FI5CHER** [glpi-project/glpi-agent#663]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

I still have but want a public following to keep the community aware

### Describe the bug

Hi Teclib. Me again 🤣

It would be great to add support of containerd and kubernetes to the glpi agent.

It might make sense to build a separate addon for Kubernetes, which sends the data of a Kubernetes cluster directly to the GLPI server. 
And the K8S system would then be another asset that consists of several individual computer systems.

### To reproduce

( this is an enhancement request ) 

### Expected behavior

( this is an enhancement request ) 

### Operating system

Linux

### GLPI Agent version

1.7.3

### GLPI version

10.0.14

**Comment by g-bougard** [comment]
Hi @FI5CHER 

please, can you better use the [Ideas discussion category](https://github.com/glpi-project/glpi-agent/discussions/categories/ideas) ?

Also you should open 2 threads, 1 for each support request. And in each case, can you provide a command which can help to list containers and some sample outputs for each one ?
