### ISSUE TITLE
Brother DCP-L5652DN Printers Invented as an Unmanaged Device

### ISSUE THREAD

**Issue by erique-souza** [glpi-project/glpi-agent#664]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Still not applicable

### Describe the bug

I believe that the reason for the Brother DCP-L5652DN printers not being inventoried is that the GLPI-Agent does not have the MIB registered for this printer model,
I did an snmpwalk to capture the data and I believe this data can be included so that in future versions the agent will be able to recognize it as a network printer and be able to do the snmp inventory

Below are the SNMP Walk files that I performed via Linux on the same terminal that the discovery agent is trying to inventory:

snmpwalk -c public -v2c 10.1.97.50 > /home/Fernando/printer10.1.97.50.txt && snmpwalk -c public -v2c 10.1.65.50 > /home/Fernando/printer10.1.65.50.txt

[printer10.1.65.50.txt](https://github.com/glpi-project/glpi-agent/files/15224445/printer10.1.65.50.txt)
[printer10.1.97.50.txt](https://github.com/glpi-project/glpi-agent/files/15224446/printer10.1.97.50.txt)

The serial number is on this MIB: SNMPv2-SMI::mib-2.43.5.1.1.17.1
In both cases, respectively: 
SNMPv2-SMI::mib-2.43.5.1.1.17.1 = STRING: "U64198D3N295908"
SNMPv2-SMI::mib-2.43.5.1.1.17.1 = STRING: "U64198D3N295892"

Below is the GLPI-Agent debug 2 log and prints of the network discovery tasks

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/66c91008-3d0a-4c04-a951-21a2831599a7)

![image](https://github.com/glpi-project/glpi-agent/assets/102301295/7e76b3f7-7f2c-4a5c-855f-d1fb5edbcc60)

[glpi-agent.log](https://github.com/glpi-project/glpi-agent/files/15224538/glpi-agent.log)

### To reproduce

1 - Have a printer model Brother DCP-L5652DN
2 - Having a registered SNMP credential validates access to the environment with the agent
3 - Register an SNMP Discovery task, search for the device and see that it is being brought in as an unmanaged device instead of a printer

### Expected behavior

Device inventory as a network printer

### Operating system

Linux

### GLPI Agent version

1.7.3

### GLPI version

10.0.14

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.5

**Comment by g-bougard** [comment]
Hi @erique-souza 

Brother printer support has been enhanced in latest version. Can you try it ?

**Comment by erique-souza** [comment]
I am planning to access the environment where this request was made between tomorrow 26/09 and Monday 30/09, as soon as I can validate it with the latest version of glpi-agent in 1.11 I will post the result here so we can conclude whether it has been resolved or no

**Comment by erique-souza** [comment]
I did the inventory test on the same printer from this manufacturer, with glpi-agent 1.11 and even so it was not possible to import into GLPI, it continues to fall as an unmanaged device, I also checked the import rules to check both the serial number and mac

I am sending snmpwalk according to previous procedures for validation, and also the glpi of glpi-agent 1.11 with debugg 2 enabled for validation

[walk-printerbrother.walk.txt](https://github.com/user-attachments/files/17155147/walk-printerbrother.walk.txt)

![{5AB894DA-122C-456B-ADC1-CF8422FFD4BF}](https://github.com/user-attachments/assets/4f372ca5-5be9-48ec-9e97-c46ce7d00395)

[glpi-agent-printerbrother.log](https://github.com/user-attachments/files/17155190/glpi-agent-printerbrother.log)

**Comment by g-bougard** [comment]
Hi @erique-souza 

here I see another problem: it seems no credentials has been associated with one ip range. At least this is probably why no credentials parameter is given to the agent in the response to its PROLOG request.

And I tested your walk with glpi-agent v1.11 and this printer seems perfectly supported.

**Comment by erique-souza** [comment]
You can close this issue, it is a bug in the glpi 10.0.10 version with the inventory plugin that was not allowing the snmp credential to be correctly linked to the range, thus never being able to inventory new devices.
This has already been fixed in the most recent versions, thank you
