### ISSUE TITLE
Remote inventory doesn't work if the password contains special characters.

### ISSUE THREAD

**Issue by AlexTR85** [glpi-project/glpi-agent#671]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

I'm a GLPI partner

### Describe the bug

Following the remote inventory manual:
"https://glpi-agent.readthedocs.io/en/latest/tasks/remote-inventory.html"

In the section of adding the server to be analyzed: "glpi-remote add ssh://admin:pass@192.168.43.237"

The special character breaks the command. If added via toolbox, it even makes the remote web inaccessible until you delete the record with that password.

The logs show different things depending on the special  character used.

### To reproduce

In the section of adding the server to be analyzed: "glpi-remote add ssh://admin:p@$s@192.168.43.237"

Adding quotes doesn't change anything.

### Expected behavior

The expected behavior would be for it to enter the record without interpreting the characters in a special way.

Doing a normal SSH works fine.

### Operating system

Linux

### GLPI Agent version

1.8

### GLPI version

10.0.x (See additional context below)

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.4

**Comment by g-bougard** [comment]
Hi @AlexTR85 

in your example, you're using `@` and `$` chars. If the problem only concerns the `@` char, we still have a related issue opened here: #582
So do you also have the issue when only `$` char is used ?

As a work-around, you still may setup SSH public-key based accesses.

**Comment by AlexTR85** [comment]
p@$s is an example, now I have problems with "["

Okay, I'll try the workaround, thanks

**Comment by cedric-anne** [comment]
Does it work if you use the URL encoded string corresponding to your password, e.g. `glpi-remote add ssh://admin:p%40%24s@192.168.43.237` instead of `glpi-remote add ssh://admin:p@$s@192.168.43.237` ?

**Comment by AlexTR85** [comment]
no, encoded not working: [error] [libssh2] Can't authenticate on 10.x.x.x remote host

**Comment by g-bougard** [comment]
Hi @AlexTR85 

next [nightly build](https://nightly.glpi-project.org/glpi-agent/) should fix your issue. Can you test it when available ?

**Comment by AlexTR85** [comment]
hello,

Is Ok with ? https://nightly.glpi-project.org/glpi-agent/#glpi-agent-v19-gitd73f5c8d-nightly-build?

thanck you

**Comment by g-bougard** [comment]
You can use 1.9 released this morning.
