### ISSUE TITLE
Nutanix remote inventory compatibility

### ISSUE THREAD

**Issue by AlexTR85** [glpi-project/glpi-agent#672]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

I'm a GLPI partner

### Describe the bug

I obtain remote inventories from other Linux sources, but from Nutanix AHV (centos7 based), I only receive the machine name.

The log indicates the following:

[info] running task RemoteInventory
[warning] You should execute remote inventory as super-user on remote host
[info] New inventory from 120.210.22.62-2024-05-16-13-18-11 for server0 (tag=XXX)
Use of uninitialized value in lc at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 378.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Generic::Batteries::Acpiconf: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Generic::Batteries::Upower: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
Use of uninitialized value $link in concatenation (.) or string at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 494.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Generic::Firewall::Ufw: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Generic::Ipmi::Fru: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Generic::PCI: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] printers inventory not supported remotely without perl mode enabled
[debug] unexpected error in GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt::SupRemo: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Generic::SSH: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Generic::Softwares::Flatpak: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Generic::Softwares::Nix: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Generic::Softwares::RPM: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Generic::Softwares::Snap: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Generic::Storages::HP: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Generic::USB: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Virtualization::Docker: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Virtualization::Jails: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Virtualization::Lxc: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Virtualization::Parallels: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Virtualization::SolarisZones: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Virtualization::SystemdNspawn: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Virtualization::Virtuozzo: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Virtualization::VmWareDesktop: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Virtualization::Vserver: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] unexpected error in GLPI::Agent::Task::Inventory::Virtualization::Xen: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] Running GLPI::Agent::Task::Inventory::AccessLog
[debug] Running GLPI::Agent::Task::Inventory::Generic
[debug] Running GLPI::Agent::Task::Inventory::Generic::Arch
[debug] Running GLPI::Agent::Task::Inventory::Generic::Batteries
[debug] Running GLPI::Agent::Task::Inventory::Generic::Domains
[debug] Running GLPI::Agent::Task::Inventory::Generic::Drives
[debug] Running GLPI::Agent::Task::Inventory::Generic::Environment
[debug] Running GLPI::Agent::Task::Inventory::Generic::Firewall
[debug] Running GLPI::Agent::Task::Inventory::Generic::Firewall::Systemd
[debug] Running GLPI::Agent::Task::Inventory::Generic::Hostname
[debug] Running GLPI::Agent::Task::Inventory::Generic::Ipmi
[debug] Running GLPI::Agent::Task::Inventory::Generic::Ipmi::Lan
[debug] Running GLPI::Agent::Task::Inventory::Generic::Networks
[debug] Running GLPI::Agent::Task::Inventory::Generic::OS
[debug] Running GLPI::Agent::Task::Inventory::Generic::Processes
[debug] unexpected error in GLPI::Agent::Task::Inventory::Generic::Processes: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] Running GLPI::Agent::Task::Inventory::Generic::Remote_Mgmt
[debug] Running GLPI::Agent::Task::Inventory::Generic::Screen
[debug] retrieving EDID data:
[debug] - reading /sys/devices content: no result
[debug] unexpected error in GLPI::Agent::Task::Inventory::Generic::Screen: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] Running GLPI::Agent::Task::Inventory::Generic::Softwares
[debug] Running GLPI::Agent::Task::Inventory::Generic::Storages
[debug] Running GLPI::Agent::Task::Inventory::Generic::Timezone
[debug] Running GLPI::Agent::Task::Inventory::Generic::Users
[debug] Running GLPI::Agent::Task::Inventory::Provider
[debug] Running GLPI::Agent::Task::Inventory::Virtualization
[debug] Running GLPI::Agent::Task::Inventory::Virtualization::Libvirt
[debug] Running GLPI::Agent::Task::Inventory::Vmsystem
[debug] unexpected error in GLPI::Agent::Task::Inventory::Vmsystem: Can't call method "ext_data" on an undefined value at /usr/share/glpi-agent/lib/GLPI/Agent/Task/RemoteInventory/Remote/Ssh.pm line 193.
[debug] Section ENVS has changed since last inventory
[debug] Full inventory postponed: 3/14
[debug] Remote inventory task run in 5 seconds

### To reproduce

Launch glpi-agent --remote=ssh://admin:pass@192.168.43.237 --logger=stderr --tasks remoteinventory on a nutanix AHV machine

### Expected behavior

A normal inventory

### Operating system

Linux

### GLPI Agent version

1.8

### GLPI version

10.0.x (See additional context below)

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.4

**Comment by g-bougard** [comment]
Hi @AlexTR85 

it seems you have some compatibility problem with the libssh2 library on your system and the remote ssh server. What's the OS of the running GLPI-Agent and what's its version ?

You may want to try ssh-key based authentication and try 'ssh' mode in place of 'libssh2'.

Just for your information, if you subscribe to GLPI, you can require access to the Nutanix GLPI plugin so you don't need glpi-agent remote inventory.

**Comment by g-bougard** [comment]
Hi @AlexTR85 

without feedback, I'm closing this issue without.

Feel free to reopen or comment.
