### ISSUE TITLE
Incorrect next run

### ISSUE THREAD

**Issue by nchizhov** [glpi-project/glpi-agent#674]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

If we will change date on computer to "future" and change time back to normal - glpi-agent will try next run in "future" dates.

### To reproduce

1, Change date to future
2. Try run inventory
3. Back date to "normal"
4. In logs now show that next run will be in "future"

### Expected behavior

Check current date and next run date - if current date is more lower (for example: months, years, n days) than next run, than "reset" next run date.

### Operating system

Windows

### GLPI Agent version

1.8

### GLPI version

Other (See additional context below), Not applicable

**Comment by g-bougard** [comment]
Hi @nchizhov 

the scheduling is based on an interval between runs, so the agent is preparing the next date just after it finishes its tasks. If the date is wrong at that time, you make it guesses a wrong future date.

I don't think this is really a problem in normal usage.

If you made a mistake on date setup on the computer, just force the inventory after the date fix. The agent has no way to detect such a mistake.
