### ISSUE TITLE
NetInventory task not supported by server

### ISSUE THREAD

**Issue by leruetkins** [glpi-project/glpi-agent#68]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Hi

I have installed glpi-agents v1.2-git73986331 nightly build with netdiscovery feauters on both OS: ubuntu 20.04, WIN10.
Then I tried run such commands:
glpi-netinventory --host 192.168.244.9 --credentials version:1,community:public --debug
and receive answer:
```
[debug] Logger backend Stderr initialized
[debug] Current run expiration timeout: 1.0 hour
[debug] creating 1 worker threads
[debug] [thread 1] creation
[debug] [thread 1] #1, scanning 0: 192.168.244.9
[debug] [thread 1] #1, full match for sysobjectID .1.3.6.1.4.1.11.2.3.9.1 in database
[debug] [thread 1] #1, /etc/glpi-agent/toolbox.yaml configuration not found
[debug] [thread 1] #1, sysobjectID match: hp-peripheral mib support enabled
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <CARTRIDGES>
        <TONERBLACK>WARNING</TONERBLACK>
      </CARTRIDGES>
      <INFO>
        <COMMENTS>HP ETHERNET MULTI-ENVIRONMENT,SN:PHBLL4R318,FN:3W91MXR,SVCID:28175,PID:HP LaserJet MFP M426dw</COMMENTS>
        <ID>0</ID>
        <IPS>
          <IP>192.168.244.9</IP>
        </IPS>
        <MAC>b4:b6:86:79:b0:f9</MAC>
        <MANUFACTURER>Hewlett-Packard</MANUFACTURER>
        <MEMORY>256</MEMORY>
        <MODEL>HP LaserJet MFP M426dw</MODEL>
        <NAME>NPI79B0F9</NAME>
        <RAM>256</RAM>
        <SERIAL>PHBLL4R318</SERIAL>
        <TYPE>PRINTER</TYPE>
        <UPTIME>5 days, 09:23:44.51</UPTIME>
      </INFO>
      <PAGECOUNTERS>
        <DUPLEX>5909</DUPLEX>
        <TOTAL>52347</TOTAL>
      </PAGECOUNTERS>
      <PORTS>
        <PORT>
          <IFDESCR>LOOPBACK</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>180328942</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>0.00 seconds</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>LOOPBACK</IFNAME>
          <IFNUMBER>1</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>180328942</IFOUTOCTETS>
          <IFSPEED>0</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>24</IFTYPE>
        </PORT>
        <PORT>
          <IFDESCR>Ethernet</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>3152181283</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>0.00 seconds</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Ethernet</IFNAME>
          <IFNUMBER>2</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>79980889</IFOUTOCTETS>
          <IFSPEED>10000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <IP>192.168.244.9</IP>
          <IPS>
            <IP>192.168.244.9</IP>
          </IPS>
          <MAC>b4:b6:86:79:b0:f9</MAC>
        </PORT>
        <PORT>
          <IFDESCR>wifi0</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>3207355893</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>8.53 seconds</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>wifi0</IFNAME>
          <IFNUMBER>3</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>1685</IFOUTOCTETS>
          <IFSPEED>10000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>5c:ea:1d:9f:90:f7</MAC>
        </PORT>
        <PORT>
          <IFDESCR>wifiUAP</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>0</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>8.59 seconds</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>wifiUAP</IFNAME>
          <IFNUMBER>4</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>38091</IFOUTOCTETS>
          <IFSPEED>10000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>5c:ea:1d:9f:90:f7</MAC>
        </PORT>
      </PORTS>
    </DEVICE>
    <MODULEVERSION>5.0</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>SNMPQUERY</QUERY>
</REQUEST>
[debug] [thread 1] termination
[debug] All netinventory threads terminated
```
Then I run:
glpi-netdiscovery --host 192.168.244.9 --debug -i
and got the same answer. It looks like SNMP discovery works fine. But next I tried run this:
`glpi-agent --logger=stderr --tasks netinventory --debug --server=http://my.server/glpi/front/inventory.php`
and got this:
```
[debug] Logger backend Stderr initialized
[debug] GLPI Agent (1.2-git73986331)
[debug] Configuration directory: /etc/glpi-agent
[debug] Data directory: /usr/share/glpi-agent
[debug] Storage directory: /var/lib/glpi-agent
[debug] Lib directory: /usr/share/glpi-agent/lib
[debug] [target server0] Next server contact planned for Thu Feb 10 18:47:03 2022
[debug] Available tasks:
[debug] - Inventory: 1.10
[debug] - NetDiscovery: 5.0
[debug] - NetInventory: 5.0
[debug] - RemoteInventory: 1.0
[debug] - WakeOnLan: 2.2
[debug] target server0: server http://my.server/glpi/front/inventory.php
[debug] Planned tasks for server0: NetInventory
[debug] Built by Debian
[debug] Source time: 2022-02-09 02:12
[debug] Running in foreground mode
[info] target server0: server http://my.server/glpi/front/inventory.php
[debug] [http client] CB0653DB: Using Compress::Zlib for compression
[info] sending contact request to server0
[debug] [http client] Using Compress::Zlib for compression
[info] sending prolog request to server0
[debug] NetInventory task not supported by server
```
or this on WIN10:
```
[debug] Logger backend Stderr initialized
[debug] Logger backend File initialized
[debug] GLPI Agent (1.2-git73986331)
[debug] Configuration directory: C:/Program Files/GLPI-Agent/etc
[debug] Data directory: C:/Program Files/GLPI-Agent/share
[debug] Storage directory: C:\Program Files\GLPI-Agent\var
[debug] Lib directory: C:/Program Files/GLPI-Agent/perl/agent
[debug] [target server0] Next server contact planned for Thu Feb 10 20:32:24 2022
[debug] Available tasks:
[debug] - Collect: 2.8
[debug] - Deploy: 2.9
[debug] - Inventory: 1.10
[debug] - NetDiscovery: 5.0
[debug] - NetInventory: 5.0
[debug] - RemoteInventory: 1.0
[debug] target server0: server http://my.server/glpi/front/inventory.php
[debug] Planned tasks for server0: NetInventory
[debug] Provided by Teclib Edition
[debug] Installer built on Tue Feb  8 15:52:37 2022 UTC
[debug] Built with Strawberry Perl 5.34.0
[debug] Built on github actions windows image for glpi-project/glpi-agent repository
[debug] Running in foreground mode
[info] server0 is not ready yet, next server contact planned for Thu Feb 10 20:32:24 2022
```

And I can't receive data on my GLPI server. It looks like server does't work with SNMP discovery correctly. 
Regular inventory works fine.
Any idea?

Also I tried send data manually:
`glpi-injector -v -f C:\inv\netdiscovery\192.168.244.9.xml --url http://my.server/glpi/front/inventory.php`
and got this:

```
Loading C:\inv\netdiscovery\192.168.244.9.xml...ERROR: Array
(
    [0] => JSON does not validate. Violations:
Additional properties not allowed: hardware at #->$ref[file~2///var/www/html/glpi/vendor/glpi-project/inventory_format/inventory.schema.json]

)

These elements were not sent:
C:\inv\netdiscovery\192.168.244.9.xml
```

Also I tried add Printer by import in menu: Administartion - Equipment - Import from xml, Then I got White screen and error in php.errors.log:
```
[2022-02-10 10:04:15] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: Array
(
    [0] => JSON does not validate. Violations:
Additional properties not allowed: hardware at #->$ref[file~2///var/www/html/glpi/vendor/glpi-project/inventory_format/inventory.schema.json]

)
 in /var/www/html/glpi/src/Inventory/Inventory.php at line 209
  Backtrace :
  src/Inventory/Request.php:318                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:217                      Glpi\Inventory\Request->inventory()
  src/Inventory/Request.php:86                       Glpi\Inventory\Request->networkDiscovery()
  src/Agent/Communication/AbstractRequest.php:271    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:210    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  src/Inventory/Conf.php:220                         Glpi\Agent\Communication\AbstractRequest->handleRequest()
  src/Inventory/Conf.php:162                         Glpi\Inventory\Conf->importContentFile()
  front/inventory.conf.php:45                        Glpi\Inventory\Conf->importFile()
```
Content of XML file discovered by glpi-netdiscovery:
```
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <AUTHPORT />  <AUTHPROTOCOL />  <AUTHSNMP>1</AUTHSNMP>
      <DESCRIPTION>HP ETHERNET MULTI-ENVIRONMENT,SN:PHBLL4R318,FN:3W91MXR,SVCID:28175,PID:HP LaserJet MFP M426dw</DESCRIPTION>
      <DNSHOSTNAME>192.168.244.9</DNSHOSTNAME>
      <IP>192.168.244.9</IP>
      <IPS>
        <IP>192.168.244.9</IP>
      </IPS>
      <MAC>b4:b6:86:79:b0:f9</MAC>
      <MANUFACTURER>Hewlett-Packard</MANUFACTURER>
      <MODEL>HP LaserJet MFP M426dw</MODEL>
      <NETBIOSNAME>NPI79B0F9</NETBIOSNAME>
      <SERIAL>PHBLL4R318</SERIAL>
      <SNMPHOSTNAME>NPI79B0F9</SNMPHOSTNAME>
      <TYPE>PRINTER</TYPE>
      <UPTIME>5 days, 21:04:45.71</UPTIME>
      <WORKGROUP>WORKGROUP</WORKGROUP>
    </DEVICE>
    <MODULEVERSION>5.0</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
```

p/s Als I can't find additional  sections  for network inventory and ip ranges:

![Screenshot_235](https://user-images.githubusercontent.com/15270519/153278845-fe1f56bd-62a2-4d7a-b964-df1eb9d804ec.png)

Could you help me enable it?

### To reproduce

See on top.

### Expected behavior

1

### Operating system

Windows, Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.0-rc1

### GLPIInventory plugin or FusionInventory for GLPI plugin version

development release (See additional context below)

### Additional context

v1.2-git73986331 nightly build

**Comment by g-bougard** [comment]
Hi @leruetkins 

thank you for your report.

You're indeed reporting few different problems. I'll try to answer them all.

First point, when using GlpiInventory plugin, you must use `http://my.server/glpi/plugins/glpiinventory/` as server on agent-side if you installed the plugin manually or  `http://my.server/glpi/marketplace/glpiinventory/` if you installed it using marketplace. If you don't use that url, the agent won't request the plugin as it should for netdiscovery, netinventory, collect, esx and deploy tasks.

Secondly, about Toolbox, you should setup the agent as explained in documentation: [Toolbox plugin](https://glpi-agent.readthedocs.io/en/latest/plugins/toolbox-plugin.html) but I think you should better manage to make GlpiInventory working as expected as it is the right FusionInventory plugin replacement.

About the format exception, can you try to apply [Add printer missing page counters #66](https://github.com/glpi-project/inventory_format/pull/66) other your `/var/www/html/glpi/vendor/glpi-project/inventory_format/inventory.schema.json` file ?

**Comment by g-bougard** [comment]
For the format exception, there's another problem and I'm on it.

**Comment by g-bougard** [comment]
Indeed, for now, you still can remove `<WORKGROUP>WORKGROUP</WORKGROUP>` from the XML as it makes trouble at the moment.

**Comment by g-bougard** [comment]
Okay, can you also apply [Hardware should be placed in content #67](https://github.com/glpi-project/inventory_format/pull/67) to your `/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php/Converter.php` file ?

**Comment by leruetkins** [comment]
Thanks a lot for your explanation. The documentation did not give me such information.

> still can remove <WORKGROUP>WORKGROUP</WORKGROUP>

It works!


> About the format exception, can you try to apply https://github.com/glpi-project/inventory_format/pull/66 other your /var/www/html/glpi/vendor/glpi-project/inventory_format/inventory.schema.json file ?

Sorry, I can't understand exactly what should I do. Should I delete "duplex" in json file? But I think this string is important for us.
If I send file from netinvertory folder:
```
root@glpi:/home/glpi# glpi-injector -R -f /home/glpi/inv/netinventory/192.168.244.9.xml --debug -url http://my.server/glpi/marketplace/glpiinventory/
Loading /home/glpi/inv/netinventory/192.168.244.9.xml...[70540817] ERROR: Array
(
    [0] => JSON does not validate. Violations:
Additional properties not allowed: duplex at #->$ref[inventory.schema.json]->properties:content->properties:pagecounters

)

DEBUG: <?xml version="1.0"?>
<REPLY><ERROR>Array
(
    [0] =&gt; JSON does not validate. Violations:
Additional properties not allowed: duplex at #-&gt;$ref[inventory.schema.json]-&gt;properties:content-&gt;properties:pagecounters

)
</ERROR></REPLY>

These elements were not sent:
/home/glpi/inv/netinventory/192.168.244.9.xml
```

If I send file from netdiscovery folder is fine ( file /var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php/Converter.php was corrected):

```
root@glpi:/home/glpi# glpi-injector -R -f /home/glpi/inv/netdiscovery/192.168.244.9.xml --debug -url http://my.server/glpi/marketplace/glpiinventory/
Loading /home/glpi/inv/netdiscovery/192.168.244.9.xml...[CCB8072F] OK
DEBUG: <?xml version="1.0"?>
<REPLY><RESPONSE>SEND</RESPONSE></REPLY>
```

**Comment by leruetkins** [comment]
> About the format exception, can you try to apply https://github.com/glpi-project/inventory_format/pull/66 other your /var/www/html/glpi/vendor/glpi-project/inventory_format/inventory.schema.json file ?

I understood this action and it works for me fine!
```

root@glpi:~# glpi-injector -R -f /home/glpi/inv/netinventory/192.168.244.9.xml --debug -url http://my.server/glpi/marketplace/glpiinventory/
Loading /home/glpi/inv/netinventory/192.168.244.9.xml...[40C724FF] OK
DEBUG: <?xml version="1.0"?>
<REPLY><RESPONSE>SEND</RESPONSE></REPLY>
```

**Comment by g-bougard** [comment]
So, are all your problems fixed or what problems are remaining ?

**Comment by leruetkins** [comment]
Yes, these problems are solved for me. But will these changes be added to next version?

p/s GLPI NetInventory still not working :(
I have configured it via instructions, but Networking Descovery doesn't work :(

**Comment by g-bougard** [comment]
Yes, [Hardware should be placed in content #67](https://github.com/glpi-project/inventory_format/pull/67) is still merged and will be included in final GLPI 10 release. I'm confident [Add printer missing page counters #66](https://github.com/glpi-project/inventory_format/pull/66) will be too as it fixes problems.

About, netinventory and netdiscovery tasks, just telling it doesn't work is simply not sufficient. You should at least attach some agent log showing the problem. You should know the tasks won't be run until the agent contact the server. By default, it will only contact the server once a day unless you force the run. You can access local agent http interface locally via URL: `http://localhost:62354/`. From there, you can click on `Force an inventory`. You may also force an inventory from GLPI by accessing the **Computer** tab of the asset, and looking at the **Inventory Information** section: you can click on the icon next to the "Request inventory" text. This should work unless your agent is behind a proxy.

**Comment by leruetkins** [comment]
Thank you so much! 
It my mistake, that I didn't set time interval. I meant that is set by default from Monday to Monday. It was not intuitive for me.
