### ISSUE TITLE
GLPI Agent Deployment Script - "New Ticket" Redirected Incorrectly

### ISSUE THREAD

**Issue by j-tresarrieu** [glpi-project/glpi-agent#694]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Hi,

Since the latest update of the GLPI Agent, we've noticed an issue with the Agent Monitor.
When using the "New Ticket" button, some or perhaps all agents are being redirected incorrectly.

In some instances, it opens the System32 folder, while in others, it opens the agent binaries folder.

This behavior was unexpected. Initially, I observed this today in my lab environment and, upon checking in production, found the same issue.

I'm using the mass deployment script for the GLPI Agent. 

### To reproduce

- Agent installed by GLPI Agent deployment script :
[glpi-agent-deployment-local.txt](https://github.com/user-attachments/files/15882337/glpi-agent-deployment-local.txt)

### Expected behavior

Button redirecting to New Ticket page

### Operating system

Windows

### GLPI Agent version

1.9

### GLPI version

10.0.15

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.5

**Comment by j-tresarrieu** [comment]
I resolved this problem by adding new options in the script to force the ticket URL change.

In the documentation of the Agent Monitor and the changelog, there is a new option called "AGENTMONITOR_NEWTICKET_URL".

Adding this option to the script solved the problem:

```
SetupOptions = "/quiet ADDLOCAL=ALL AGENTMONITOR=1 RUNNOW=1 SERVER=https://glpi.site.fr/ AGENTMONITOR_NEWTICKET_URL=https://glpi.site.fr/front/ticket.form.php"
```

Have you encountered the same issue?

**Comment by g-bougard** [comment]
Hi @j-tresarrieu 

the problem has still been reported in redddcyclone/glpi-agentmonitor#24.

And it is still fixed in glpi-agent nightly build. Please, try it to validate or wait next release.
