### ISSUE TITLE
[error] Undefined subroutine &GLPI::Agent::Tools::Win32::_GLPI_XML_win32_binded_thread

### ISSUE THREAD

**Issue by perplexityjeff** [glpi-project/glpi-agent#699]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Agent was running without issue however at some point this error came up. It crashed the agent as well. Stopping the process and the service by force and restarting it fixed it for now.

### To reproduce

To be honest it was simply running in the background

### Expected behavior

It not doing this

### Operating system

Windows

### GLPI Agent version

1.9

### GLPI version

10.0.15

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.5

### Additional context

```
Jun 28 09:24:38 2024][debug2] [http client] 9A03B9B1: received message:
{"message":"remoteinventory task not supported","disabled":["remoteinventory"],"expiration":"1","status":"ok","tasks":{"collect":{"version":"1.3.5","server":"glpiinventory"},"inventory":{"server":"glpi","version":"10.0.15"},"netdiscovery":{"version":"1.3.5","server":"glpiinventory"},"netinventory":{"version":"1.3.5","server":"glpiinventory"}}}
[Fri Jun 28 09:24:38 2024][debug] server message: remoteinventory task not supported
[Fri Jun 28 09:24:38 2024][debug2] [http client] Using Compress::Zlib for compression
[Fri Jun 28 09:24:38 2024][info] sending prolog request to server0
[Fri Jun 28 09:24:38 2024][error] Undefined subroutine &GLPI::Agent::Tools::Win32::_GLPI_XML_win32_binded_thread called at C:/Program Files/GLPI-Agent/perl/agent/GLPI/Agent/Tools/Win32.pm line 1092.
[Fri Jun 28 09:24:38 2024][info] target server0: next run: Fri Jun 28 10:17:19 2024 - https://glpi.imds.nl/marketplace/glpiinventory/
[Fri Jun 28 09:24:38 2024][debug] Agent memory usage before freeing memory: WSS=35352576 PFU=260333568
[Fri Jun 28 09:24:38 2024][info] GLPI Agent memory usage: WSS=3973120 PFU=260333568
[Fri Jun 28 09:24:38 2024][debug] [http server] GET request /status from client 127.0.0.1
```

**Comment by g-bougard** [comment]
Hi @perplexityjeff 

can you test [latest published nightly build](https://nightly.glpi-project.org/glpi-agent/) ?

It specifically includes fixes related to windows and multi-threading support that may fix such kind of issue.

**Comment by perplexityjeff** [comment]
Hi @g-bougard, will do that. I'll install it and let it run over the weekend and will report back!

**Comment by perplexityjeff** [comment]
Hi @g-bougard, it does seem that the nightly agent builds behave better. I installed 1.10-git4008e9fb and over the weekend resulted with no errors. I do hope on a release soon.

**Comment by g-bougard** [comment]
Hi @perplexityjeff 

thank you for your feedback.

1.10 release is actually planed for 9/07/2024, so in 8 days.
