### ISSUE TITLE
This is not a bug, but it is a suggestion for integration with rmm

### ISSUE THREAD

**Issue by sistemmsn** [glpi-project/glpi-agent#700]
### Bug reporting acknowledgment

Not applicable

### Professional support

None

### Describe the bug

Hello, as I told you, this is not a bug, simply an integration with the glpi agenda where it detects the id of the rmm just as they did with meshcentral #163

![image](https://github.com/glpi-project/glpi-agent/assets/38023703/6aa6c732-d98d-49e4-8f28-db24d4706609)
 
![image](https://github.com/glpi-project/glpi-agent/assets/38023703/55a78b39-2049-4662-879d-3bca1a264914)

![image](https://github.com/glpi-project/glpi-agent/assets/38023703/ef3b7250-0acc-4f56-9072-656a83320ddd)

### To reproduce

N/A

### Expected behavior

N/A

### Operating system

Windows

### GLPI Agent version

1.9

### GLPI version

10.0.15

### GLPIInventory plugin or other plugin version

Not applicable

**Comment by sistemmsn** [comment]
https://glpi.userecho.com/communities/1/topics/2308-remote-monitering-and-management-integration-tactical-rmm

**Comment by g-bougard** [comment]
Hello @sistemmsn 

thank you for your suggestion.

That's really easy to add with the shared datas. I prepared a TacticalRMM.pm module you can test: [TacticalRMM.pm.zip](https://github.com/user-attachments/files/16049996/TacticalRMM.pm.zip)

Just copy it under `C:\Program Files\GLPI-Agent\perl\agent\GLPI\Agent\Task\Inventory\Generic\Remote_Mgmt` folder.

Then can you report the output of the following command run from an administrative console and from the glpi-agent installation folder:
```
glpi-inventory --partial remote_mgmt
```

Then with that output, you should be able to open a glpi issue to request the remote management link creation for the `tacticalrmm` type.

Before merging the module, and as I saw linux & MacOS are also supported, do you know how to get the `AgentID` for that cases ?

**Comment by g-bougard** [comment]
Just tested on my WindowsEval VM and here is the result:
```
{
   "action": "inventory",
   "content": {
      "bios": {
         "bdate": "2006-12-01",
         "biosserial": "0",
         "bmanufacturer": "innotek GmbH",
         "bversion": "VirtualBox",
         "mmanufacturer": "Oracle Corporation",
         "mmodel": "VirtualBox",
         "msn": "0",
         "smanufacturer": "innotek GmbH",
         "smodel": "VirtualBox",
         "ssn": "32eed9c2-204c-42a1-a97e-a6ef2ce44b4f"
      },
      "hardware": {
         "chassis_type": "Other",
         "memory": 8175,
         "name": "WinDev2404Eval",
         "uuid": "32EED9C2-204C-42A1-A97E-A6EF2CE44B4F",
         "vmsystem": "VirtualBox",
         "winlang": "1033",
         "winowner": "Windows User",
         "winprodid": "00329-20000-00001-AA673",
         "winprodkey": "7HBDQ-QNKVG-K4RBF-HMBY6-YG9R6",
         "workgroup": "WORKGROUP"
      },
      "remote_mgmt": [
         {
            "id": "ksAVartDRIqqtvaklsrqliKuGNmymjkVjRtfrtXw",
            "type": "tacticalrmm"
         }
      ],
      "versionclient": "GLPI-Inventory_v1.10-dev"
   },
   "deviceid": "WinDev2404Eval-2024-07-01-10-59-39",
   "itemtype": "Computer",
   "partial": true
}
```
You can use it on a GLPI issue to request the expected link.

**Comment by g-bougard** [comment]
Hi @sistemmsn 

in the format, we can also add a `version` string in the case it can be relevant. Do you know how to get it ?

**Comment by silversword411** [comment]
Great work, looking good!

**Comment by g-bougard** [comment]
Thank you, but do you have any answer to my questions ?
1. how to get AgentID on linux ?
2. how to get AgentID on MacOS ?
3. how to get version ? Maybe a command to run ?

And don't forget to eventually open a GLPI issue to request Remote management link update. You'll have to explain how to generate the URL: clearly how to find the base URL on which to add the found AgentID.

**Comment by sistemmsn** [comment]
> Hi @sistemmsn
> 
> in the format, we can also add a `version` string in the case it can be relevant. Do you know how to get it ?

![image](https://github.com/glpi-project/glpi-agent/assets/38023703/90196b1c-46ac-431d-ad71-af68532e91cd)

 .\tacticalrmm.exe --help
Usage of C:\Program Files\TacticalAgent\tacticalrmm.exe:
  -agent-type string
        server or workstation (default "server")
  -api string
        API URL
  -auth string
        Token
  -cert string
        Path to domain CA .pem
  -client-id int
        Client ID
  -desc string
        Agent's Description
  -insecure
        Insecure for testing only
  -local-mesh string
        Path to mesh executable
  -log string
        The log level (default "INFO")
  -logto string
        Where to log to (default "file")
  -m string
        The mode to run
  -meshdir string
        Path to custom meshcentral dir
  -meshnodeid string
        Mesh Node ID
  -natsport string
        nats standard port
  -nomesh
        Do not install mesh agent
  -p int
        Task PK
  -ping
        Enable ping
  -power
        Disable sleep/hibernate
  -proxy string
        Use a http proxy
  -rdp
        Enable RDP
  -silent
        Do not popup any message boxes during installation
  -site-id int
        Site ID
  -timeout duration
        Installer timeout (seconds) (default 900ns)
  -version
        Prints version
 .\tacticalrmm.exe -version

**Comment by sistemmsn** [comment]
> Thank you, but do you have any answer to my questions ?
> 
> 1. how to get AgentID on linux ?
> 2. how to get AgentID on MacOS ?
> 3. how to get version ? Maybe a command to run ?
> 
> And don't forget to eventually open a GLPI issue to request Remote management link update. You'll have to explain how to generate the URL: clearly how to find the base URL on which to add the found AgentID.

I'm afraid that for these versions for Linux and Mac you need a license hehehe let me see if I can get the payment authorized and I will gladly give you retro thanks

**Comment by g-bougard** [comment]
Hi @sistemmsn

thank you, I still added the version support for windows. It will be provided using nightly build.

**Comment by sistemmsn** [comment]
> > Thank you, but do you have any answer to my questions ?
> > 
> > 1. how to get AgentID on linux ?
> > 2. how to get AgentID on MacOS ?
> > 3. how to get version ? Maybe a command to run ?
> > 
> > And don't forget to eventually open a GLPI issue to request Remote management link update. You'll have to explain how to generate the URL: clearly how to find the base URL on which to add the found AgentID.
> 
> I'm afraid that for these versions for Linux and Mac you need a license hehehe let me see if I can get the payment authorized and I will gladly give you retro thanks

Hello, how are you? I already found a way to install it on Linux. It seems that it is possible, but you need to do something manually and when you acquire the license, they facilitate the installation with one click hehehe.

![imagen](https://github.com/glpi-project/glpi-agent/assets/38023703/b6dbef26-1c3b-4fcd-9f8c-701df8ceecbd)


![imagen](https://github.com/glpi-project/glpi-agent/assets/38023703/cde99aa9-29e9-4822-9374-60b1e33f3b83)

I will try to do the same with OSX

**Comment by g-bougard** [comment]
Hi @sistemmsn 

thank you for this sharing.

I modified the TacticalRMM.pm module to also support linux. Can you test it ?
You can download it with this direct URL: https://raw.githubusercontent.com/glpi-project/glpi-agent/8442a20c069ce82c5ed5c673252d34147cb1b823/lib/GLPI/Agent/Task/Inventory/Generic/Remote_Mgmt/TacticalRMM.pm
And replace the one you'll find in your glpi-agent installation.

You can also eventually test it is still working as expected on windows.

**Comment by sistemmsn** [comment]
working correctly
Linux tested
![imagen](https://github.com/glpi-project/glpi-agent/assets/38023703/6cb2da99-0334-4f78-97f2-956388294420)

**Comment by g-bougard** [comment]
It didn't find the version. `/usr/local/bin` is probably not in the path of the service.
You can try this one: https://raw.githubusercontent.com/glpi-project/glpi-agent/0cfc2a70fd00da5a6f360e7fda9bf491d858d73c/lib/GLPI/Agent/Task/Inventory/Generic/Remote_Mgmt/TacticalRMM.pm

**Comment by sistemmsn** [comment]
you ate the /

Linux
![imagen](https://github.com/glpi-project/glpi-agent/assets/38023703/6790fbf6-1202-4443-be4c-dd127b3b7ac0)
![imagen](https://github.com/glpi-project/glpi-agent/assets/38023703/08c5ec95-06fa-4256-8f4e-8ac942b967a7)

Windows
![imagen](https://github.com/glpi-project/glpi-agent/assets/38023703/0de7b772-55fb-4a8b-8e9b-b0b0343dac2d)

**Comment by g-bougard** [comment]
Sorry, fixed the linux path in: https://raw.githubusercontent.com/glpi-project/glpi-agent/e2207b723fe483b98e05a67b37ac936beff6c742/lib/GLPI/Agent/Task/Inventory/Generic/Remote_Mgmt/TacticalRMM.pm

It seems version check is not working on windows. Can you share the file generated by the following commands ?
1. On windows:
```
"C:\Program Files\TacticalAgent\tacticalrmm.exe" --version >version-windows.txt
```
2. On linux:
```
/usr/local/bin/rmmagent --version >version-linux.txt
```

**Comment by sistemmsn** [comment]
> Sorry, fixed the linux path in: https://raw.githubusercontent.com/glpi-project/glpi-agent/e2207b723fe483b98e05a67b37ac936beff6c742/lib/GLPI/Agent/Task/Inventory/Generic/Remote_Mgmt/TacticalRMM.pm
> 
> It seems version check is not working on windows. Can you share the file generated by the following commands ?
> 
>     1. On windows:
> 
> 
> ```
> "C:\Program Files\TacticalAgent\tacticalrmm.exe" --version >version-windows.txt
> ```
> 
>     2. On linux:
> 
> 
> ```
> /usr/local/bin/rmmagent --version >version-linux.txt
> ```

[version-linux.txt](https://github.com/user-attachments/files/16134806/version-linux.txt)
[version-windows.txt](https://github.com/user-attachments/files/16134825/version-windows.txt)

**Comment by g-bougard** [comment]
Hello @sistemmsn 

I just published 1.10 with a last little update to support rmmagent version.

I'm closing the issue with this release, but feel free to continue sharing data for the MacOS support so we can add it for the next release.

**Comment by sistemmsn** [comment]
hi @g-bougard  

MAC OSX Monterey

![imagen](https://github.com/glpi-project/glpi-agent/assets/38023703/fb6c3c65-4bef-4f78-96e5-12309c2bebd8)

![imagen](https://github.com/glpi-project/glpi-agent/assets/38023703/6c5eb16d-f56a-488c-985b-18205c154d6b)

![imagen](https://github.com/glpi-project/glpi-agent/assets/38023703/7edf2bf2-018c-4d54-9d01-f65995d2e369)

**Comment by sistemmsn** [comment]
https://glpi.userecho.com/communities/1/topics/2380-combine-external-links-with-remote-management

**Comment by g-bougard** [comment]
Hi @sistemmsn 

thank you, I just added support for MacOSX. You'll be able to test with next nightly build.

About GLPI external link, don't hesitate to create a PR on the glpi project if you still have the code.
