### ISSUE TITLE
Can't use an undefined value as an ARRAY reference...

### ISSUE THREAD

**Issue by jsamaniegog** [glpi-project/glpi-agent#703]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

After install and activate toolbox plugin it shows this error: Can't use an undefined value as an ARRAY reference at /usr/share/glpi-agent/lib/GLPI/Agent/HTTP/Server/ToolBox/Results.pm line 674

### To reproduce

1. Install agent
2. Edit /etc/glpi-agent/toolbox-plugin.cfg
3. Uncomment "disabled = no"
4. Restart agent service
5. Show status to see the error: Can't use an undefined value as an ARRAY reference at /usr/share/glpi-agent/lib/GLPI/Agent/HTTP/Server/ToolBox/Results.pm line 674

### Expected behavior

No errors.

### Operating system

Linux

### GLPI Agent version

1.9

### GLPI version

10.0.15

### Additional context

OS: CentOS 7

**Comment by g-bougard** [comment]
Hi @jsamaniegog 

thank you for your report.

It seems this problem occurs if not archiving software is available on your platform. This is weird as at least tar & gzip are commonly available on linux. Anyway, in this happens, the agent should not report this kind of error.

So I modified the agent to support the case no archiving software is found.

**Comment by jsamaniegog** [comment]
Hi @g-bougard 
Both are installed:

```
# gzip --version
gzip 1.5

# tar --version
tar (GNU tar) 1.26
```

**Comment by g-bougard** [comment]
So maybe there's another reason, but the error should no more appear.
