### ISSUE TITLE
Software dictionary not applied after inventory with GLPI agent

### ISSUE THREAD

**Issue by Berlinst** [glpi-project/glpi-agent#714]
I installed the GLPI agent on a computer to perform an inventory of the device in GLPI. After forcing the inventory, the computer was correctly inventoried in GLPI. Following this, I created some rules in the software dictionary to adjust the software categories on the computers, aiming for better filtering.

![image](https://github.com/user-attachments/assets/50cf26aa-95f6-4e5b-a6e9-da5b573a34d1)
-> Software Dictionary

After creating these rules, I forced the inventory again. However, there was no change in the software categories according to the created dictionary. I tested by permanently deleting and removing devices of the computer, then forcing the inventory again, but the software categories remained blank, along with other tabs for the computer in question.

![image](https://github.com/user-attachments/assets/fa957ed6-0798-4b2d-b951-ef65d7c6e429)
-> Before permanently deleting and removing devices of the computer, then forcing the inventory again.

![image](https://github.com/user-attachments/assets/8d515074-0585-4666-81de-19c24a8acca5)
-> After permanently deleting and removing devices of the computer, then forcing the inventory again.

I also tested by reinstalling the GLPI agent, but it didn't resolve the issue. Upon uninstalling and reinstalling the GLPI agent, the software information was retrieved again, but the categories were still not adjusted according to the dictionary.

![image](https://github.com/user-attachments/assets/86b7aa9d-6510-4ca6-9c9a-c993cf6bd438)
-> According to the above dictionary, the software category should be 'Antivírus'.

![image](https://github.com/user-attachments/assets/f385e937-6648-4c0e-bc88-b8adf4b9547d)
-> According to the above dictionary, the software category should be 'Compactador'.

![image](https://github.com/user-attachments/assets/feed0e28-5400-4ce4-8dff-db3cdcf42ea9)
-> According to the above dictionary, the software category should be 'GLPI'.

**Comment by g-bougard** [comment]
Hi @Berlinst 

I'm sorry, but this is the wrong place to open such a server-side issue and your problem seems really only related to glpi. Here we are only handling issues for glpi-agent. Inventory integration remains a GLPI feature.

I think you should probably ask your question first on the GLPI forum here: http://forum.glpi-project.org/
Anyway check the GLPI project additional resources here: https://github.com/glpi-project/glpi?tab=readme-ov-file#additional-resources
