### ISSUE TITLE
Unable to report a bug using the template

### ISSUE THREAD

**Issue by silhusk** [glpi-project/glpi-agent#717]
Maybe it's me, but I don't find a way to report an [issue](https://github.com/glpi-project/glpi-agent/issues) using the [bug_report template](https://github.com/glpi-project/glpi-agent/blob/9cae9310b9303a7571705455c0e63a35de55da93/.github/ISSUE_TEMPLATE/bug_report.yml). GitHub tells me _"Issue templates and forms are currently unavailable. Please try again later."_ and it reports an error in the template: "body[7]: options must be unique. [Learn more about this error.](https://docs.github.com/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#bodyi-options-must-be-unique)".

Looks like it sees version "1.10" as a duplicate? Maybe it reads as a float and it's the same as 1.0?

**Comment by g-bougard** [comment]
Hi @silhusk 

thank you for the notification, I really missed than problem when I added "1.10" in the list. My guess is it was converted in float and then becomes a duplicate of "1.1". I added "v" in front of each version to keep them as just strings.
