### ISSUE TITLE
Windows VBS installer should better handle architecture vs assets

### ISSUE THREAD

**Issue by Frflamingo** [glpi-project/glpi-agent#728]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Since version 1.8 there is no x86 built of the msi anymore 
Nevertheless the vbs installer (contrib/windows/glpi-agent-deployment.vbs) will try to fetch producing an error 
Suggest a warning message and download and install of the latest x86 (1.7.3 ?) 

Typically with a version 1.9 you would get an attempt to dl from :
```
https://github.com/glpi-project/glpi-agent/releases/download/1.9/GLPI-Agent-1.9-x86.msi
```

### To reproduce

1. Using vbs installer set up the version to 1.8 and higher 
2. Launch it on a x86 machine 

### Expected behavior

Install should finish successfully 

### Operating system

Windows

### GLPI Agent version

v1.8

### GLPI version

Not applicable

### GLPIInventory plugin or other plugin version

Not applicable

### Additional context

Is the support of x86 windows  dropped for the agent ?

**Comment by g-bougard** [comment]
Hi @Frflamingo 

thank you for the reminder.

**Comment by g-bougard** [comment]
I just updated the vbs to abort if major version is 1 and minor version is greater than 7.

You can download the latest version from here and test it: https://raw.githubusercontent.com/glpi-project/glpi-agent/develop/contrib/windows/glpi-agent-deployment.vbs

**Comment by Frflamingo** [comment]
This works as expected 
Please note that i had to set verbose=Yes to see the message (using cscript /nologo glpi-agent-deployment.vbs)
Maybe we could add to the message somtheing like "LAst x86 version is 1.7.3) so that user will know 
Suggest change from: 
GLPI-Agent v1.9 doesn't support installation on a 32-bit operative system.
to 
GLPI-Agent v1.9 doesn't support installation on a 32-bit operati**ng** system. Latest supported version is 1.7.3


![image](https://github.com/user-attachments/assets/fa002adb-5630-4119-bb02-a3dd153f7496)

**Comment by g-bougard** [comment]
Thank you for your feedback.

This is not the purpose of the code to tell people which version can be installed. People should finally find the right information in documentation, like here:
https://glpi-agent.readthedocs.io/en/latest/installation/index.html#windows
