### ISSUE TITLE
Agent crash loop when using ADMX

### ISSUE THREAD

**Issue by SteadEXE** [glpi-project/glpi-agent#73]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

When deploying configuration for agent by GPO with the given ADMX, something goes wrong.

Here is a screen of registry with keys created by .msi:

![image](https://user-images.githubusercontent.com/1759156/153852132-aa23e76e-98f7-497f-a78b-68b2aa1a0360.png)

Here is a screen of registry with keys created by ADMX:

![image](https://user-images.githubusercontent.com/1759156/153852287-7c2c045f-2f7d-48a5-ae36-e5026386a8f8.png)

It looks like some keys are not getting parsed properly because when we try to repair the installation using the installer this is what get parsed:

![image](https://user-images.githubusercontent.com/1759156/153852395-ebf5e3c7-c41a-4933-84a6-f444faef1a12.png)

And the agent crash loop while trying to contact the server with a misleading error:

[Mon Feb 14 11:40:28 2022][info] GLPI Agent service starting
[Mon Feb 14 11:40:29 2022][info] GLPI Agent memory usage: WSS=3670016 PFU=82358272
[Mon Feb 14 11:40:29 2022][info] target server0: next run: Mon Feb 14 11:40:20 2022 - https://[REDACTED]/plugins/glpiinventory/index.php
[Mon Feb 14 11:40:29 2022][info] target server0: server https://[REDACTED]/plugins/glpiinventory/index.php
[Mon Feb 14 11:40:30 2022][info] sending prolog request to server0
[Mon Feb 14 11:40:30 2022][error] [http client] communication error: 500 Can't connect to [REDACTED]:443 (Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu.)
[Mon Feb 14 11:40:30 2022][error] No answer from server at https://[REDACTED]/plugins/glpiinventory/index.php
[Mon Feb 14 11:40:30 2022][info] target server0: next run: Mon Feb 14 11:40:30 2022 - https://[REDACTED]/plugins/glpiinventory/index.php
[Mon Feb 14 11:40:31 2022][info] target server0: server https://[REDACTED]/plugins/glpiinventory/index.php
[Mon Feb 14 11:40:31 2022][info] sending prolog request to server0
[Mon Feb 14 11:40:31 2022][error] [http client] communication error: 500 Can't connect to [REDACTED]:443 (Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu.)
[Mon Feb 14 11:40:31 2022][error] No answer from server at https://[REDACTED]/plugins/glpiinventory/index.php
[Mon Feb 14 11:40:31 2022][info] target server0: next run: Mon Feb 14 11:40:31 2022 - https://[REDACTED]/plugins/glpiinventory/index.php
[Mon Feb 14 11:40:32 2022][info] target server0: server https://[REDACTED]/plugins/glpiinventory/index.php
[Mon Feb 14 11:40:32 2022][info] sending prolog request to server0
[Mon Feb 14 11:40:32 2022][error] [http client] communication error: 500 Can't connect to [REDACTED]:443 (Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu.)
[Mon Feb 14 11:40:32 2022][error] No answer from server at https://[REDACTED]/plugins/glpiinventory/index.php
[Mon Feb 14 11:40:32 2022][info] target server0: next run: Mon Feb 14 11:40:32 2022 - https://[REDACTED]/plugins/glpiinventory/index.php
[Mon Feb 14 11:40:33 2022][info] target server0: server https://[REDACTED]/plugins/glpiinventory/index.php
[Mon Feb 14 11:40:33 2022][info] sending prolog request to server0
[Mon Feb 14 11:40:33 2022][error] [http client] communication error: 500 Can't connect to [REDACTED]:443 (Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu.)
[Mon Feb 14 11:40:33 2022][error] No answer from server at https://[REDACTED]/plugins/glpiinventory/index.php
[Mon Feb 14 11:40:33 2022][info] target server0: next run: Mon Feb 14 11:40:33 2022 - https://[REDACTED]/plugins/glpiinventory/index.php
[Mon Feb 14 11:40:34 2022][info] target server0: server https://[REDACTED]/plugins/glpiinventory/index.php

I guess there is a try-catch around the request and the request cannot be made because of a wrong timeout parameter.

I hope all my infos can help :

### To reproduce

Install the agent and try to edit the config trought GPO ADMX

### Expected behavior

No crash

### Operating system

Windows

### GLPI Agent version

1.1

### GLPI version

10.0.0-rc1

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.0-rc4

### Additional context

I also saw that there is no documentation for the paremeter "conf-reload-interval" and it's not possible to edit it during installation or trought ADMX.

**Comment by SteadEXE** [comment]
It's maybe related, we used the VBS to migrate from Fusion Inventory to GLPI Agent, some keys like "no-httpd" are in REG_DWORD instead of REG_SZ and are wrongly interpreted by the agent.
Some agent are in REG_DWORD 0x0 and does not start listening.
With a fresh install keys are in REG_SZ.

**Comment by SteadEXE** [comment]
I took the liberty to edit the code, this should be fixed by https://github.com/glpi-project/glpi-agent/pull/79

**Comment by g-bougard** [comment]
Hi @SteadEXE 

indeed the problem should come from the ADMX as the agent expects REG_SZ. But did you use it for FusionInventory agent in the past ? I think the problem should be the same or something goes wrong now as we now have a MSI and not an EXE installer.

**Comment by SteadEXE** [comment]
I tried on a Windows Sandbox to uninstall Fusion with the GLPI Agent Deploy script, nothing went wrong, everything is in REG_SZ.
I tried to delete "no-httpd" and recreate a "no-httpd" REG_DWORD key, I reinstalled the agent with the MSI and the key didn't got the type changed. I guess the MSI does not override all the keys.

We tried the ADMX before deploying the agent, so I guess all computer already got bad registry keys set, and installing the agent later can't fix the issue.
I guess fixing the ADMX is the more healthy solution so the installer can get the correct value too. But my pull request can prevent some issue if people are playing with registry keys on their own 👍

**Comment by SteadEXE** [comment]
I never played with the MSI, maybe it would be nice to ensure all registry keys are in the right type, if it's wrong, erase it with a default value or by the value passed as parameter. I don't know how easy it is to make this kind of change. I don't want you to make a huge change to fix my mistake, but I guess it would prevent issue if people already deployed the ADMX in their AD.

**Comment by g-bougard** [comment]
Can you try the following ADMX/ADML files ? They should create the registry keys as REG_SZ.
[GLPI-Agent.adm.zip](https://github.com/glpi-project/glpi-agent/files/8109677/GLPI-Agent.adm.zip)
I tried them quickly on win10 pro but I would prefer a confirmation it works as expected, so I'll merge them after you validate them.

**Comment by SteadEXE** [comment]
After the deploy everything seems right:

![image](https://user-images.githubusercontent.com/1759156/154975203-8fe89f85-cb40-4f12-8232-a5c4649af5a2.png)

Nice job 👍

**Comment by SteadEXE** [comment]
I tried on a computer with broken ADMX, it fixed the issue too :)

**Comment by g-bougard** [comment]
Just merged the updated files.
