### ISSUE TITLE
Agent Status Unknown

### ISSUE THREAD

**Issue by Dercni** [glpi-project/glpi-agent#733]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Then agent can communicate with the GLPI server
The GLPI server fails to communicate with the agent and continually reports the agent status as unknown.

The GLPI versions is 10.0.15
The agent versions is 1.10

From the GLPI server I can ping the agent
On the GLPI server I can view the agent web GUI @ port 62354

I have set set the agent logging level to 2 and see nothing in the logs that indicates a problem.

I have installed the GLPI-Inventory plugin

The agent correctly reports it's tasks to the GLPI server, which confirms communications.
![image](https://github.com/user-attachments/assets/ce96c955-bb63-446d-950f-dc4dfa147f86)

As I have spent weeks on this now I am reporting it as a bug as I cannot see where I have gone wrong.

### To reproduce

Navigate to the computer inventory information page
Click either the agent status refresh icon or the request inventory refresh icon

### Expected behavior

The GLPI server is able to connect to the agent when either the "Agent status" refresh icon is clicked or the "Request Inventory" refresh icon is clicked. Presently:
Agent status = Unknown
Request inventory = Unknown

### Operating system

Windows

### GLPI Agent version

v1.10

### GLPI version

10.0.15

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.5

**Comment by g-bougard** [comment]
Hi @Dercni 

you're asking for support not reporting a glpi-agent bug so I'll move your issue as Q&A question.

Your problem can be a network problem: GLPI needs to have a direct network access to the agent port. Also you should tell if you configured a proxy in GLPI. If this is the case, the proxy probably can't contact agents.
