### ISSUE TITLE
Glpi-agent 1.10 toolbox : JSON does not validate

### ISSUE THREAD

**Issue by Sicoval31** [glpi-project/glpi-agent#734]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

I still have but want a public following to keep the community aware

### Describe the bug

In toolbox plugin, a netdiscovery/inventory in local files work perfectly
When try to remote on glpi server, an error occur while import json file : 
```
[info] Starting Borne Wifi network scan task job...
[info] Running Borne Wifi task...
[error] #01, [http client] communication error: 500 Internal Server Error, Array, (,     [0] => JSON does not validate. Violations:, Required property missing: type, data: {"contact":"admin@aerohive.com","ips":["10.100.1.251","10.100.2.251","10.100.3.251","10.100.4.251","10.200.33.1","127.0.0.1","198.18.40.1","198.18.8.1"],"lo (...)

```
Try to import directly XML file : same error

Note that the netdiscovery remote asset in the "matériel non géré" section and the agent is correctly added on GLPI

### To reproduce

 Launch netinventory of aerohive wifi asset via glpi-agent toolbox

### Expected behavior

 remote netinventory to GLpI server

### Operating system

Windows

### GLPI Agent version

v1.10

### GLPI version

10.0.12

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.5

**Comment by g-bougard** [comment]
Hi @Sicoval31 

`Required property missing: type` probably means your network device is not supported as glpi-agent seems not provide a device type.

Can you share the generated XML ? The one you tried to import manually.

What is that device ?

I can check if we can easily support this device. For that, you'll probably have to provide a [snmpwalk output in the expected format](https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output).

**Comment by g-bougard** [comment]
Hi @Sicoval31 

I'm closing this issue without any feedback to my request.

Feel free to reopen if you finally have the answer.
