### ISSUE TITLE
ERROR: XML not well formed!

### ISSUE THREAD

**Issue by m-pastuszek** [glpi-project/glpi-agent#75]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

Inventory task running, but don't sending it to server due to the `XML not well formed! error!`. Agent visible in Glpi server.

```
[Tue Feb 15 09:47:01 2022][info] GLPI Agent service starting
[Tue Feb 15 09:47:02 2022][info] [http server] HTTPD service started on port 62354
[Tue Feb 15 09:47:03 2022][info] GLPI Agent memory usage: WSS=3731456 PFU=102486016
[Tue Feb 15 09:47:03 2022][info] target server0: next run: Tue Feb 15 10:35:23 2022 - http://[REDACTED]/front/inventory.php
[Tue Feb 15 09:47:28 2022][info] target server0: server http://[REDACTED]/front/inventory.php
[Tue Feb 15 09:47:28 2022][info] sending prolog request to server0
[Tue Feb 15 09:47:28 2022][info] server0 answer shows it supports GLPI Agent protocol
[Tue Feb 15 09:47:28 2022][info] running task Deploy
[Tue Feb 15 09:47:28 2022][error] [http client] communication error: 400 Bad Request, Protocol not supported
[Tue Feb 15 09:47:28 2022][info] Deploy task not supported by server0
[Tue Feb 15 09:47:32 2022][info] running task ESX
[Tue Feb 15 09:47:32 2022][error] [http client] communication error: 400 Bad Request, Protocol not supported
[Tue Feb 15 09:47:32 2022][info] ESX task not supported by server0
[Tue Feb 15 09:47:36 2022][info] running task Collect
[Tue Feb 15 09:47:36 2022][error] [http client] communication error: 400 Bad Request, Protocol not supported
[Tue Feb 15 09:47:36 2022][info] Collect task not supported by server0
[Tue Feb 15 09:47:37 2022][info] running task Inventory
[Tue Feb 15 09:47:37 2022][info] New inventory from [REDACTED]-2022-02-15-09-47-01 for server0
[Tue Feb 15 09:50:18 2022][error] [http client] communication error: 400 Bad Request
[Tue Feb 15 09:50:18 2022][error] [http client] unexpected content, starting with: <?xml version="1.0"?>
<REPLY><ERROR>XML not well formed!</ERROR></REPLY>
[Tue Feb 15 09:50:21 2022][info] target server0: next run: Tue Feb 15 10:48:09 2022 - http://[REDACTED]/front/inventory.php
[Tue Feb 15 09:50:21 2022][info] GLPI Agent memory usage: WSS=3387392 PFU=159903744
[Tue Feb 15 09:50:23 2022][info] running task Deploy: storage maintenance event
```

Running `glpi-inventory --json > inventory.json` and then injecting it to server, also ends with:
```
ERROR: XML not well formed!
These elements were not sent:
inventory.json
```

### To reproduce

1. Run Inventory task.

### Expected behavior

Inject data to GLPI server.

### Operating system

Windows

### GLPI Agent version

1.1

### GLPI version

10.0.0-rc1

**Comment by g-bougard** [comment]
Hi @m-pastuszek 
firstly, if you're not using ESX, Collet or Deploy tasks, you still can set them in `no-task` parameter: `deploy,esx,collect`. On windows, you have to set it in registry.
Then, you should set `debug` to `2`, restart the service and force à run so we have more information on what's happening.

You should also probably check on server-side the `php-errors.log` in GLPI `files/_log` folder.

**Comment by g-bougard** [comment]
Hi @m-pastuszek 
back to your issue, I missed you're using the wrong server URL. Please read [server configuration](https://glpi-agent.readthedocs.io/en/latest/configuration.html#server) and particularly the "Caution" section to understand which URL to use.
I'm closing the issue, but feel free to re-open if fixinf the URL doesn't fix your problem.
