### ISSUE TITLE
GLPI agent not working

### ISSUE THREAD

**Issue by franckneo** [glpi-project/glpi-agent#760]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Hello,
We were using GLPI agent 1.4, saw the 1.10 is available, add a GPO : 
msiexec /i C:\GLPI-Agent-1.10-x64.msi /quiet /log "\path\log.log" SERVER=http://<IP>/glpi/plugins/fusioninventory/

Try to push the upgrade to only 1 UO first, some are working fine and some...not.
In the 127.0.0.1:62354 : no reply
From GLPI server trying to refresh status : no reply.
BUT : the installation said no error : MSI (s) (9C:6C) [13:36:08:497]: Product: GLPI Agent 1.10 -- Installation completed successfully.
MSI (s) (9C:6C) [13:36:08:497]: Windows Installer a installé le produit. Nom du produit : GLPI Agent 1.10. Version du produit : 1.10. Langue du produit : 1033. Fabricant : Teclib'. Réussite de l’installation ou état d’erreur : 0.

The service is running just fine.

Can fail on Windows 11 23H2 or Win 10 22H2.

What kind of log can be relevant for it?
Thank you in advance for any reply.
Already tried to uninstall and reinstall the agent but same issue.

### To reproduce

Upgrade from 1.4 to 1.10?
Not sure, because some are working fine and report with agent 1.10 in the server.

### Expected behavior

I expected the web server to start and client to be "checked"

### Operating system

Windows

### GLPI Agent version

v1.10

### GLPI version

9.5.x (See additional context below)

**Comment by g-bougard** [comment]
Hi @franckneo 

I move your issue to Q&A discussions as you're requesting assistance not reporting a glpi-agent bug.
