### ISSUE TITLE
OS Error for RedHat Enterprise 8.10

### ISSUE THREAD

**Issue by ASLLR** [glpi-project/glpi-agent#762]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

I still have but want a public following to keep the community aware

### Describe the bug

Hi everyone, 

I can see with the GLPI agent on Redhat 8.10 during an inventory the version is not correctly remounted. 
In the name field it shows “Red Hat Enterprise Linux” and in the version field (field 46 during an API call) it shows the number 10 (instead of 8.10). Whereas on a version 8.9 or lower the version field is correct.

Thank you in advance,

### To reproduce

1. Have a redhat VM in 8.10
2. Have GLPI agent 1.9 installed on this VM
3. Launch inventory
4. See on GLPI the version number in operating system tab

### Expected behavior

Have the correct version for RedHat 8.10 instead only the 10. 

### Operating system

Linux

### GLPI Agent version

v1.9

### GLPI version

10.0.16

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.5

**Comment by g-bougard** [comment]
Hi @ASLLR 

can you share the output of the following command:
```
glpi-inventory --partial os
```

Can you also share the content of `/etc/os-release` & `/etc/redhat-release` files ?

**Comment by ASLLR** [comment]
Of course (a little anonymized): 

glpi-inventory --partial os  in [glpi-inventory-partial-os.txt](https://github.com/user-attachments/files/17030501/glpi-inventory-partial-os.txt)

os-release in [os-release.txt](https://github.com/user-attachments/files/17030482/os-release.txt)

redhat-release in [redhat-release.txt](https://github.com/user-attachments/files/17030496/redhat-release.txt)


But on GLPI web view it's not that. 

Thank you,

**Comment by g-bougard** [comment]
Yes, it is correctly discovered by glpi-agent.

So to me the problem is not agent-side, but server-side, probably in Operating system dictionary rules.

**Comment by ASLLR** [comment]
Hi @g-bougard, exactly the rule "TECLIB - Mac OS X" in dictionnary match with that ... That's work much better when this rule is disable. 

Thank you.
