### ISSUE TITLE
Acess Point - AP122 Aerohive - Inventory as Unmanaged Device

### ISSUE THREAD

**Issue by erique-souza** [glpi-project/glpi-agent#768]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Still not applicable

### Describe the bug

I am trying to make an inventory of Network devices that are Access Points (Routers) of the AP122 model from the brand/manufacturer Aerohive, but GLPI does not recognize it as a network device but only as an unmanaged device

I even validated the import rules to ensure that I am trying to import both using the serial number and MAC as a common import factor, but I believe that I do not have the MIB registered in glpi-agent to recognize it as a network device

I did the SNMP Walk on your IP version 2 10.16.33.51 and exported the log below as an example
I also made a call via the Network Discovery Task with glpi-agent 1.11, the most updated to date, with debugg 2 active, the log is also below
I took advantage of the fact that I was in contact with the person responsible for the equipment, and below I also have a screenshot of the place where he uses to manage the devices so that we have the information as a basis for the ExtremeCloud portal

![Print da Tela Conect](https://github.com/user-attachments/assets/9445fbf5-3948-4ec4-baa9-3d53fb0890ad)

~~glpi-agent-snmp-ap-122.log~~
[snmp-ap-122.txt](https://github.com/user-attachments/files/17137247/snmp-ap-122.txt)

![{80D0BAF9-B7E2-4730-8347-B2DDA2676E1D}](https://github.com/user-attachments/assets/690029c0-cb2a-414e-919b-c90dd7c81d85)

![{9878BA5F-53AF-4373-A370-364D9F120240}](https://github.com/user-attachments/assets/4c0a8654-6066-4625-8bdc-061749d26544)

![{94E2666D-100F-4D5F-A4B7-5485ECAEBE5A}](https://github.com/user-attachments/assets/b1d5a76e-a172-4ceb-b4b6-9a5273080155)

![{46B73C65-65FC-4C92-9AA5-C9C74A978861}](https://github.com/user-attachments/assets/416519a3-d40f-4226-8d5c-4ff3e4ff6ac1)

### To reproduce

1 - Have a network equipament AP122 Aerohive
2 - Having a registered SNMP credential validates access to the environment with the agent
3 - Register an SNMP Discovery task, search for the device and see that it is being brought in as an unmanaged device instead of a network equipament

### Expected behavior

Device inventory as a network equipament

### Operating system

Linux

### GLPI Agent version

v1.11

### GLPI version

10.0.16

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.5

Edit: Removed log file as it can expose few sensible datas

**Comment by g-bougard** [comment]
Hello @erique-souza 

this device is clearly not well supported by the agent.

Can you test the MibSupport dedicated module in the following archive ? [Aerohive-support.zip](https://github.com/user-attachments/files/17144819/Aerohive-support.zip)

You just have to copy the included `Aerohive.pm` module into the `/usr/share/glpi-agent/lib/GLPI/Agent/SNMP/MibSupport` folder.

I used 2 MIBs I quickly found but I wasn't able to fully test the module as the walk you provided wasn't generated using the required option you'll find here: https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output
Then I  had to make few assumption and I'm pretty sure this is not fully correct.

**Comment by erique-souza** [comment]
Thanks for the guidance, I ran a new snmpwalk test as indicated by the documentation, an example below for anyone looking to consult later:
snmpwalk -v2c -c credencial -t 15 -Cc -On -Ox IP .1 > /tmp/walk-app122.walk

I just had to rename the file added the .txt extension to be compatible with the github upload

[walk-app122.walk.txt](https://github.com/user-attachments/files/17147223/walk-app122.walk.txt)


I also did a test by placing the specific MidSupport in the indicated directory /usr/share/glpi-agent/lib/GLPI/Agent/SNMP/MibSupport with glpi-agent

And the inventory actually worked to be inventoried as a network device for this asset class

![{0259283D-DB79-4D0E-BDBC-5D66F9F5F246}](https://github.com/user-attachments/assets/e99cf625-befa-4ce6-9779-f7faa8c61384)

![{4979F041-7808-4AC9-89CD-CA8583A88591}](https://github.com/user-attachments/assets/c387fe61-6348-4327-9387-cf71c78fd953)

![{BF40C1E7-A383-496F-91AD-5AB180383F51}](https://github.com/user-attachments/assets/71e84bb8-76e0-4060-9a4a-f25d1b305380)

![1](https://github.com/user-attachments/assets/ebf9067d-51b2-477f-9299-48cb54acda40)

I believe that at this point the mib file needs some adjustment to be able to identify the serial number as possible, and also correct the information that is being collected from the model so that it can be picked up if it has one or kept blank instead of having the serial number. mib in place, the other information seems to have been collected correctly such as IP, name, equipment location, manufacturer, user and description

As it was unable to identify the serial number, glpi imported it as a mac, which was the rule it had kept active even as a second import option

I am sending the complete glpi-agent log in debugg 2 mode below after collection for analysis

~~glpi-agent-app122.log~~

Edit: Removed glpi-agent log file to not disclose sensible datas

**Comment by g-bougard** [comment]
Hi @erique-souza 

here is an updated version: [Aerohive-support-v2.zip](https://github.com/user-attachments/files/17148945/Aerohive-support-v2.zip)

I made a stupid mistake in the first version where I indeed forget to query OIDs... This is fixed here and the walk permitted me to change the model related OID too.

Tell me if this works now as expected.

**Comment by erique-souza** [comment]
Validated, the import of now through glpi-agent with the new mib that passed, presented the correct data in the equipment's GLPI, thank you for the support

![nova informação](https://github.com/user-attachments/assets/ad9f7520-3849-4b7b-9f06-a1877d1f0b8a)
