### ISSUE TITLE
DVR Intelbras - Inventory as Unmanaged Device

### ISSUE THREAD

**Issue by erique-souza** [glpi-project/glpi-agent#769]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Still not applicable

### Describe the bug

I am trying to do the inventory of IP DVR devices 10.2.3.130 of the Intelbras brand/manufacturer but GLPI does not recognize it as a network device but only as an unmanaged device

I even validated the import rules to ensure that I am trying to import both using serial and MAC as an import factor in common, but I believe it does not have the MIB registered on GLPI-Agent to recognize it as a network device

I did SNMP Walk on its version 2 of IP 10.2.3.130 and exported the log below as an example
I also made a call via task network discovery with GLPI-Agent 1.11 the most updated so far, with Debugg 2 active, the log also below

(*translated using Google Translate, fix it if not exact*)

![{2823BBA2-FEA2-4691-A67E-125BF38FA186}](https://github.com/user-attachments/assets/dcce58ec-8763-46aa-a1f2-a9267f9ddace)

![{9D2A619A-5A36-4283-9382-ECCA1EBEBE02}](https://github.com/user-attachments/assets/57b2c7f6-0319-4b34-8fab-a90f1197c6c1)

![{913BC920-35C2-4656-B9AC-9B821DAB49B5}](https://github.com/user-attachments/assets/f9d58109-a154-45d6-ada3-68f157373ad9)

[snmpwalk-dvr-intelbras.txt](https://github.com/user-attachments/files/17137497/snmpwalk-dvr-intelbras.txt)
~~glpi-agent-dvr-intelbras.log~~

### To reproduce

1 - Have a network equipament DVR Intelbras
2 - Having a registered SNMP credential validates access to the environment with the agent
3 - Register an SNMP Discovery task, search for the device and see that it is being brought in as an unmanaged device instead of a network equipament

### Expected behavior

Device inventory as a network equipament

### Operating system

Linux

### GLPI Agent version

v1.11

### GLPI version

10.0.16

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.5

Edit: Removed agent log link to limit sensible data exposure

**Comment by g-bougard** [comment]
Hi @erique-souza 

can you provide a more accurate snmpwalk as for Aerohive devices in #768 ?

Indeed private oid datas are required to validate any development.

**Comment by erique-souza** [comment]
Additional data provided in 768

Regarding this one, which is another class of network device, the dvr is a dedicated camera system, using the same more precise snmpwalk procedure, also following the documentation indicated here: 
https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output

snmpwalk -v2c -c CREDENCIAL -t 15 -Cc -On -Ox IP .1 > /tmp/walk-dvrintelbras.walk

I did the most accurate snmpwalk and see the result below for analysis
[walk-dvrintelbras.walk.txt](https://github.com/user-attachments/files/17147555/walk-dvrintelbras.walk.txt)

**Comment by g-bougard** [comment]
Hi @erique-souza 

thank a lot, it helps.

Here is the module you can install to validate it works as expected before I add it to glpi-agent code: [Intelbras-support.zip](https://github.com/user-attachments/files/17148730/Intelbras-support.zip)

Can you clarify one point if you know ? It seems `.1.3.6.1.4.1.1004849` private OID is owned by DahuaTech and I used a MIB from them to clarify which OIDs I can use. So what's the relation between Intelbras & DahuaTech ? Essentially to know if the module is well-named and if we really can report "Intelbras" as manufacturer.

**Comment by erique-souza** [comment]
The Intelbras DVR was also successful in its import from the glpi side through the mib that passed, the device name came as "(none)", I believe that in this case it may have come from the device itself, not revealing its hostname if it has Of course

Regarding the relationship between Dahua Tech and Intelbras, it seems that there was a partnership between the 2 companies where some equipment has technology from both companies, there are some notices on the internet about the topic, I will post one as an example

https://revistasegurancaeletronica.com.br/intelbras-e-dahua-technology-anunciam-associacao-para-impulsionar-inovacao-e-o-desenvolvimento-de-novas-tecnologias/

![dvr](https://github.com/user-attachments/assets/7855ad12-1774-4341-9dfe-a7c09a570577)
