### ISSUE TITLE
Agent does not contact server after being woken up

### ISSUE THREAD

**Issue by rafaelse** [glpi-project/glpi-agent#77]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Is your help request related to a problem?

When i run the automatic action to wake up the agents to perform the scheduled tasks, the agent receives the request from the server but does not contact it to fetch the queued tasks. It simply gives a 200 response and do nothing else.

Here is the request in the agent's log:
![image](https://user-images.githubusercontent.com/1613703/154219598-47bb39b8-ca14-4122-ac15-9a9b5d685172.png)

Here is the log of the automatic action:
![image](https://user-images.githubusercontent.com/1613703/154219848-26d1b2cf-e765-4137-bfeb-2eaec94ab5d7.png)

I can see that 1 agent was supposedly awaken, but it does not start executing the task.

If I run the agent manually like so `glpi-agent http://glpi-http/front/inventory.php`, it pulls the task and executes it regularly.

### Expected behavior

The awaken agent should contact the server and start executing the queued tasks.

I was expecting it to send a request like this one shown in the logs `sending prolog request to server0` so it could fetch information from the server, but it does not happen.

### Actions you've considered

I have
- tried with several `httpd-trust` values;
- made sure that both the server and the agent are running on the same timezone;
- checked to see whether the appropriate tasks were installed and enabled;
- set the agent port to 62354 on the server.

### Additional context

I am running both the server and the agent as Kubernetes pods.

-  Full command used to run the the agent:

```
glpi-agent --daemon --no-fork --color --httpd-trust=0.0.0.0/0 --server=http://glpi-http/front/inventory.php --delaytime=10
```

- Dockerfile to build the agent:

```
FROM perl:5-slim-threaded

RUN mkdir /inventory
WORKDIR /inventory
ARG VERSION=1.1
ADD "https://github.com/glpi-project/glpi-agent/releases/download/${VERSION}/glpi-agent-${VERSION}-linux-installer.pl" ./glpi-agent-linux-installer.pl

RUN apt update -yqq
RUN perl glpi-agent-linux-installer.pl --install --type=network --no-question --silent
ENTRYPOINT [ "glpi-agent" ]
```

- Agent configuration:
![image](https://user-images.githubusercontent.com/1613703/154223381-2a391b29-c921-47fa-ae6f-d9ebdf630c83.png)

**Comment by rafaelse** [comment]
Upon further investigation, I wonder if the request made by the automatic action shouldn't not be made to `/now` instead of `/`

**Comment by g-bougard** [comment]
Hi @rafaelse 
yes, the request should be on `/now`, but maybe the `/` is not the server request, but you reaching the agent http interface ?
So is `172.17.0.7` the GLPI server ip ?

One thing I notice is you seems not set server option with linux installer. Without a "target", the agent won't run as a service and won't trust its setup server as it should by default. It should with the full command you give anyway. You can add `--debug --debug` to your command to have more debug.
In principle, you don't have to use `httpd-trust` if the only ip you need to trust is the glpi server as it is trusted by default (unless the agent can't resolv `glpi-http`).

**Comment by rafaelse** [comment]
I am sorry I didn't explain what the log meant, but it is indeed the server ip and this log is added every time I run the automatic action (wakeup) with a task scheduled for the agent.

I point the agent to the server in run time rather than on installation time, and I can confirm it works because it does send its inventory to the server and gets registered as an agent.

Actually, I've tried with and without the `httpd-trust` option set and I get the same result.

I also opened an issue on the [glpi-inventory-plugin](https://github.com/glpi-project/glpi-inventory-plugin) project since it might be that the plugin is making a request to the wrong URI - https://github.com/glpi-project/glpi-inventory-plugin/issues/54.

**Comment by g-bougard** [comment]
I confirm this is a [glpi-inventory-plugin](https://github.com/glpi-project/glpi-inventory-plugin) issue.
I proposed a [plugin PR](https://github.com/glpi-project/glpi-inventory-plugin/issues/55), can you try it ?
Anyway I'm closing this issue, any further discussion should go in [glpi-inventory-plugin #54](https://github.com/glpi-project/glpi-inventory-plugin/issues/54).

**Comment by rafaelse** [comment]
It is working now, thank you for the fix!
