### ISSUE TITLE
Last Agent Version Windows "Service Start and stop immediately"

### ISSUE THREAD

**Issue by psi-iflc** [glpi-project/glpi-agent#770]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

on a fresh manual install, it seems the service not running. When we start it manually, it immediately stop.
No logs are present on GLPI-AGENT logs...

### To reproduce

Install the agent manually - typical 

### Expected behavior

Service running

### Operating system

Windows

### GLPI Agent version

v1.11

### GLPI version

10.0.15

**Comment by g-bougard** [comment]
Hi @psi-iflc 

does it run or report an error when started manually from an administrative console and from the glpi-agent installation folder ?

**Comment by psi-iflc** [comment]
Hi, no error appear on manually launch throught services.msc. No logs on the glpi-agent installation folder :( ..

The problem not appear on an upgrade from 1.10 to 1.11 (on an other server)

**Comment by psi-iflc** [comment]
OS is Windows Server 2022 on both

**Comment by g-bougard** [comment]
I wanted you to start glpi-agent from an **administrative** console to see if it reports an error on the console:
```
cd "C:\Program Files\GLPI-Agent"
glpi-agent
```

**Comment by g-bougard** [comment]
And you can eventually try:
```
glpi-agent --logger=stderr --debug --debug
```

**Comment by psi-iflc** [comment]
![image](https://github.com/user-attachments/assets/94c74a39-018a-470a-85ab-fb2dea3802b1)

**Comment by g-bougard** [comment]
You are in the wrong folder and as I said run the command from the installation folder, not from the `perl\bin` subfolder. Here `glpi-agent.exe` is indeed a copy of `perl.exe` binary which indeed doesn't recognize this option.

**Comment by psi-iflc** [comment]
I'm sorry, I haven't seen the answer before, please find the result of the command below : 

![image](https://github.com/user-attachments/assets/decbf16f-93a6-459e-a2c1-f69620454943)

**Comment by psi-iflc** [comment]
And here the content of the line 194 mentioned on the execution failure log : 

![image](https://github.com/user-attachments/assets/7bb6c1e7-690d-468d-a21e-6b3698901984)

**Comment by g-bougard** [comment]
What do you have in registry for the `HKEY_LOCAL_MACHINE\SOFTWARE\GLPI-Agent` registry key ?

Actually I can only suppose you didn't configure GLPI-Agent. How did you installed it ?

**Comment by psi-iflc** [comment]
![image](https://github.com/user-attachments/assets/e65553bf-415d-431f-8743-6dcacc91a05a)
![RoyalTS_du8L1Jq3pi](https://github.com/user-attachments/assets/4bf7956b-8cb7-49e2-8054-7a60b1b6556b)
![firefox_eAfEq6NlSy](https://github.com/user-attachments/assets/573b367c-9a98-4793-a184-70582a89e4de)


I have installed it manually with the UI, choose Typical, then, specify local folder, specify Server and let "Quick install" checked

**Comment by g-bougard** [comment]
For some reason, your Operating system seems to reject GLPI-Agent to read its configuration from registry.

Do you have any AV or anything else which could have blocked GLPI-Agent ?

What's the windows OS version on this computer ?

Can you also share the output of the following command ?
```
glpi-agent --version
glpi-agent --setup
```

Do you have any output for the following command ? No need to share the output or just `"operatingsystem"` node of the JSON output.
```
glpi-inventory --partial=os
```

**Comment by psi-iflc** [comment]
I have already checked the Antivirus and have no warning about GLPI...
The OS Version is Server 2022.
Please find the output of the commands : 
glpi-agent --version

![image](https://github.com/user-attachments/assets/47960086-ef3f-4db1-9f88-882df219b010)

glpi-agent --setup

![image](https://github.com/user-attachments/assets/550ad66c-57e0-4589-b887-067472ab1e9a)

glpi-inventory --partial=os
![jsonoutput](https://github.com/user-attachments/assets/f74601b2-cf25-492e-977b-6618ce373ea3)

Thanks for your help

**Comment by g-bougard** [comment]
This is really the first time I see such an error on any windows. Now I can only think something goes wrong during installation.

Can you fully uninstall glpi-agent ?

Check folder is fully removed, if not empty it.
Check also the registry key is removed.

Then reinstall the agent as before and check if the problem still occurs.

**Comment by psi-iflc** [comment]
Hi,
I have uninstalled the Agent and checked folders and registry.
It appears the uninstaller had removed all folders correctly, but in the registry, it appears this key is not deleted by the uninstaller : Ordinateur\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet002\Services\glpi-agent.
After remove of this key, i can install the agent again and the services is running properly !

Below the content of the registry key :

![image](https://github.com/user-attachments/assets/92255211-e672-4a15-882a-eeb3f164fcd0)

**Comment by g-bougard** [comment]
Okay, thank you for your feedback.

So something goes wrong during the first install. And as far we don't know what, we can't tell if this is a bug or not.

About `Ordinateur\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet002\Services\glpi-agent`, as far I know, keys under `Ordinateur\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet002` are just backups in case of crash during a reboot, so you don't have to worry about and is not related to the issue.
