### ISSUE TITLE
[BUG] Unmatched ( in regex;

### ISSUE THREAD

**Issue by augustin55** [glpi-project/glpi-agent#780]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Hello,

I'm facing up these two errors with regex : 

`unexpected error in GLPI::Agent::Task::Inventory::Win32::USB: Unmatched ( in regex; marked by <-- HERE in m/C:/Users/SomeUsers( <-- HERE 12/AppData/Local/Temp/GLPI-Agent-1.11-x64/perl/agent/GLPI/Agent/Tools/USB/(\S+)\.pm$/ at C:/Users/SomeUsers(12/AppData/Local/Temp/GLPI-Agent-1.11-x64/perl/agent/GLPI/Agent/Tools/USB.pm line 34.`

`unexpected error in GLPI::Agent::Task::Inventory::Generic::Dmidecode::Memory: Unmatched ( in regex; marked by <-- HERE in m/C:/Users/SomeUsers( <-- HERE 12/AppData/Local/Temp/GLPI-Agent-1.11-x64/perl/agent/GLPI/Agent/Tools/PartNumber/(\S+)\.pm$/ at C:/Users/SomeUsers(12/AppData/Local/Temp/GLPI-Agent-1.11-x64/perl/agent/GLPI/Agent/Tools/PartNumber.pm line 30.`

Thanks for your help.

### To reproduce

1. Have a Windows user profile which has parenthesis in the name
2. Launch glpi-agent.bat from this user profile

### Expected behavior

It should not have this regex error.

### Operating system

Windows

### GLPI Agent version

v1.11

### GLPI version

10.0.12

### GLPIInventory plugin or other plugin version

GLPI Inventory v1.3.5

### Additional context

Linked to issue #716

**Comment by g-bougard** [comment]
Hi @augustin55 

glpi-agent is intended to be run from an Administrator account, not from a user profile.

What do you really expect running it from a user profile as this is still an error by itself ?

**Comment by g-bougard** [comment]
Anyway, you can try to apply this patch:
```patch
diff --git a/lib/GLPI/Agent/Tools/PartNumber.pm b/lib/GLPI/Agent/Tools/PartNumber.pm
index 7699897c2..bfbc224dd 100644
--- a/lib/GLPI/Agent/Tools/PartNumber.pm
+++ b/lib/GLPI/Agent/Tools/PartNumber.pm
@@ -27,10 +27,9 @@ sub new {
         my %priority = ();
         my ($_classpath) = $INC{module2file(__PACKAGE__)} =~ /^(.*)\.pm$/;
         $_classpath =~ s{\\}{/}g if $OSNAME eq 'MSWin32';
-        my $subclass_path_re = qr/$_classpath\/(\S+)\.pm$/;
         foreach my $file (File::Glob::bsd_glob("$_classpath/*.pm")) {
             $file =~ s{\\}{/}g if $OSNAME eq 'MSWin32';
-            my ($class) = $file =~ $subclass_path_re
+            my ($class) = $file =~ m{/([^/]+)\.pm$}
                 or next;
             my $module = "GLPI::Agent::Tools::PartNumber::" . $class;
             $module->require();
diff --git a/lib/GLPI/Agent/Tools/USB.pm b/lib/GLPI/Agent/Tools/USB.pm
index 604793728..1c5f62773 100644
--- a/lib/GLPI/Agent/Tools/USB.pm
+++ b/lib/GLPI/Agent/Tools/USB.pm
@@ -31,7 +31,7 @@ sub new {
             $file =~ s{\\}{/}g;
             $sub_modules_path =~ s{\\}{/}g;
         }
-        next unless $file =~ m{$sub_modules_path/(\S+)\.pm$};
+        next unless $file =~ m{/([^/]+)\.pm$};
 
         my $module = __PACKAGE__ . "::" . $1;
         # reload can be set by unittests
```

**Comment by augustin55** [comment]
Hi @g-bougard

It's working fine, thanks !

**Comment by g-bougard** [comment]
Hi @augustin55 

I just pushed a better fix.

You'll be able to validate it using next nightly build you'll be able to download from: https://nightly.glpi-project.org/glpi-agent/
