### ISSUE TITLE
No Valid Agentid set on HTTP Client

### ISSUE THREAD

**Issue by dyl1099** [glpi-project/glpi-agent#782]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

I still have but want a public following to keep the community aware

### Describe the bug

I'm using glpi agent 1.10 and when trying to do inventory task I get error "No valid agentID set on http client". i only get that error when trying to upload it directly to the server, if i save local, no issue.

### To reproduce

1)click on run task
2) it stars and the following info shows up
starting print network scan task job
running print task
new inventory from <server name> for Server 0
no valid agenid set on http client
print network scan done

### Expected behavior

the computer to be uploaded directly to glpi.

### Operating system

Windows

### GLPI Agent version

v1.10

### GLPI version

10.0.15

**Comment by g-bougard** [comment]
Hi @dyl1099 

this error means you probably have something wrong in your configuration or usage and you're not providing any evidence of any bug. So I'm moving first your issue as Q&A discussion.
