### ISSUE TITLE
Installation double IP

### ISSUE THREAD

**Issue by AxelChenelet** [glpi-project/glpi-agent#790]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

None

### Describe the bug

Issue when installing agent 1.11 on Windows systems (not tested on other platforms):
If server IP is provided without "http://" or "https://", installer doubles the IP in the server address.
If http·s prefix is used, the IP is not doubled and everything works.

### To reproduce

- Launch agent 1.11 installer
- Select "complete" or "typical" (not tested with "custom") and "quick installation"
- In "remote target" type the server IP without "http://" or "https://" prefix (e.g. "192.168.1.50/glpi")
- Finish setup.
- Open 127.0.0.1:62354
- Click on server0 link -> address is "192.168.1.50/192.168.1.50/glpi" instead of expected "192.168.1.50/glpi"

### Expected behavior

Server0 IP should not be repeated.

### Operating system

Windows

### GLPI Agent version

v1.11

### GLPI version

10.0.16

**Comment by g-bougard** [comment]
Hi @AxelChenelet 

is inventory still working with expected url ?

If yes, the problem is just the url exposed in httpd interface.

**Comment by g-bougard** [comment]
Just tested and found you're right, perl syntax was not fully correct when parsing such an URL.

**Comment by g-bougard** [comment]
Next nightly build should work as expected when url doesn't contain a scheme.

Thank you for your report.

**Comment by AxelChenelet** [comment]
Thank you,
and congratulations on your reactiveness !! :)
Best regards
