### ISSUE TITLE
nightly agent install error

### ISSUE THREAD

**Issue by dwtz** [glpi-project/glpi-agent#84]
Hi,

agent install fails using perl installer, rpm package  is created but dependencies have failed.

LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Rocky
Release:        8.5

```
./glpi-agent-1.2-git25abe43d-linux-installer.pl
Installing glpi-agent v1.2-git25abe43d...
Failed to install glpi-agent

 dnf install  glpi-agent-1.2-git25abe43d.noarch.rpm
Letzte Prüfung auf abgelaufene Metadaten: vor 0:06:18 am Di 15 Mär 2022 04:17:16 EDT.
Fehler:
 Problem: conflicting requests
  - nothing provides perl(Net::SSH2) needed by glpi-agent-1.2-git25abe43d.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by g-bougard** [comment]
Hi @dwtz 

thank you for your submission.

This means **perl-Net-SSH2** is not provided by Rocky Linux. This package is required for `remoteinventory` task so this task won't be able to work at the moment. If you don't need this task, you still can extract the rpm packages and install them by hand with `--nodeps` option for the `rpm` command. By the way, doing this way, you may also miss some other important dependencies.

IMHO, the best work-around at the moment would be to install the snap package if Rocky Linux supports it.

I'll try to upgrade the installer to support Rocky Linux as this distro can become a really important one in the future.

**Comment by dwtz** [comment]
Hi @g-bougard 

I think that applies to all redhat 8 based distributions?

**Comment by g-bougard** [comment]
Hi @dwtz 

I finally decided to change "perl(Net::SSH2)" requirement to set it as "Recommends" in spec file.

This should permit the agent to be installed even if the package is not found, but it will be if it's available (like on Fedora).

You can try the installer from [this GH Actions build artifact](https://github.com/glpi-project/glpi-agent/suites/5683103150/artifacts/186781617).

Then I'm closing the issue, but feel free to re-open if you find any regression.
