### ISSUE TITLE
SSL Version 3 protocol detection

### ISSUE THREAD

**Issue by dwtz** [glpi-project/glpi-agent#85]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

If you enable  SSL on the embedded HTTP interface, Nessus Scanner or sslscan reports SSL Version 3 protocol detection.
I have not found a way to turn it off in config.

### To reproduce

enable SSL Server plugin

### Expected behavior

You should be able to disable such protocols in config like "SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1"

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Not applicable

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

**Comment by g-bougard** [comment]
Hi @dwtz 

indeed SSLv3 is detected as the system openssl library probably supports it by default. I guess your underlying OS is a little old and so its openssl library has not been updated to one where SSLv3 is disabled. So a first action for you would be to upgrade the system. If this is not possible, you can consider to disable agent httpd daemon on systems you don't really need it.

That said, I'm working on an agent update to be able to set which protocols to support or not.

At that time, you still can apply the following patch to disable SSLv3:
```
diff --git a/lib/GLPI/Agent/HTTP/Server/SSL.pm b/lib/GLPI/Agent/HTTP/Server/SSL.pm
index 88014681a..a44404cf2 100644
--- a/lib/GLPI/Agent/HTTP/Server/SSL.pm
+++ b/lib/GLPI/Agent/HTTP/Server/SSL.pm
@@ -128,6 +128,7 @@ sub new {
     eval {
         # SSL upgrade client
         IO::Socket::SSL->start_SSL($client,
+            SSL_version     => "!SSLv3",
             SSL_server      => 1,
             SSL_cert_file   => $plugin->{cert_file},
             SSL_key_file    => $plugin->{key_file},
```

I think it should work as I tested this with TLSv1.1 on my own Fedora 35 (on which by default SSLv3 is disabled by default). By default, **sslscan** shows:
```
[gbougard@dev glpi-agent]$ sslscan -4 --no-ciphersuites --no-groups localhost:62355
Version: 2.0.6-static
OpenSSL 1.1.1g  21 Apr 2020

Connected to 127.0.0.1

Testing SSL server localhost on port 62355 using SNI name localhost

  SSL/TLS Protocols:
SSLv2     disabled
SSLv3     disabled
TLSv1.0   enabled
TLSv1.1   enabled
TLSv1.2   enabled
TLSv1.3   enabled
...
```
If I modify my patch to unset TLSv1.1 with `SSL_version     => "!TLSv11",`, sslscan shows TLSv1.1 is disabled:
```
[gbougard@dev glpi-agent]$ sslscan -4 --no-ciphersuites --no-groups localhost:62355
Version: 2.0.6-static
OpenSSL 1.1.1g  21 Apr 2020

Connected to 127.0.0.1

Testing SSL server localhost on port 62355 using SNI name localhost

  SSL/TLS Protocols:
SSLv2     disabled
SSLv3     disabled
TLSv1.0   enabled
TLSv1.1   disabled
TLSv1.2   enabled
TLSv1.3   enabled
...
```

So I'll modify SSL Server plugin to support an **advanced** `ciphers` option, set empty by default to trust the locally installed library.

**Comment by dwtz** [comment]
Hi @g-bougard ,

thank you for your answer
indeed, the agent is running on a centos 7.9 system.
But system is up to date and end of support is on June 30, 2024.

Redhat 8 Systems works as you described.

OpenSSL 1.1.1g  21 Apr 2020
SSL/TLS Protocols:
SSLv2     disabled
SSLv3     disabled
TLSv1.0   disabled
TLSv1.1   disabled
TLSv1.2   enabled
TLSv1.3   enabled


Patch works for me, thank you for this.

Regards

**Comment by g-bougard** [comment]
Hi @dwtz

I added a `ssl_cipher` option support you would be able to set to `!SSLv3` in your `etc/ssl-server-plugin.local` file.
