### ISSUE TITLE
Agent cant communicate with local server

### ISSUE THREAD

**Issue by Megachip** [glpi-project/glpi-agent#86]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

`[http client] communication error: 500 Can't connect to localhost:443 (SSL connect attempt failed error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error)`

ssl_check is disabled. No issues with FIA 2.6 on another machine.

Webserver is caddy
`server = https://localhost/front/inventory.php`

### To reproduce

- install glpi-agent via script on the same machine like glpi is running 
- configure it

### Expected behavior

A new machine within the assets 

### Operating system

Linux

### GLPI Agent version

1.1

### GLPI version

10.0.0-rc2

### GLPIInventory plugin or FusionInventory for GLPI plugin version

Not applicable

**Comment by g-bougard** [comment]
Hi @Megachip 

when communicating over SSL with a server, even on localhost, you absolutely need to set `ca-cert-file`, `ca-cert-dir` or `no-ssl-check`. And this is also true for FIA. If you had no issue with FIA, this means one of this parameter must have been used anyway. If this is not the case, this is a security issue with FIA.

You can enable debug level 2 to have more SSL debugging and you should see the underlying reason.

**Comment by Megachip** [comment]
> Hi @Megachip
> 
> when communicating over SSL with a server, even on localhost, you absolutely need to set `ca-cert-file`, `ca-cert-dir` or `no-ssl-check`. And this is also true for FIA. If you had no issue with FIA, this means one of this parameter must have been used anyway. If this is not the case, this is a security issue with FIA.
> 
> You can enable debug level 2 to have more SSL debugging and you should see the underlying reason.

no-ssl-check is set on both agents. Will check debug ... whyever, the gipi-agent do not do anything on cli :(

```
[root@glpi glpi-agent]# glpi-agent -f --no-fork -s https://localhost/front/inventory.php --debug --debug --no-ssl-check
[root@glpi glpi-agent]# 
```

**Comment by Megachip** [comment]
```
Mär 17 14:07:18 glpi glpi-agent[182043]: [http client] communication error: 500 Can't connect to localhost:443 (SSL connect attempt failed error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error)
Mär 17 14:07:18 glpi glpi-agent[182043]: No answer from server at https://localhost/front/inventory.php
Mär 17 14:07:18 glpi glpi-agent[182043]: target server0: next run: Thu Mar 17 14:08:18 2022 - https://localhost/front/inventory.php
```
set `debug=2` no additional log informations

**Comment by g-bougard** [comment]
In that case, are you sure your web server is listening on https port on loopback interface ? You can check output of: `netstat -tlnp`
Also, check you don't have any firewall rule blocking access on loopback.
You can also try to run: `curl -v https://localhost/front/inventory.php` or `wget -d https://localhost/front/inventory.php`

**Comment by homebrewtainy** [comment]
Hello,

My 2's cents...
@Megachip , your local glpi server root URL is :
 - http(s) :// localhost/
 or
 - http(s) :// localhost/glpi/
 
Regards.

**Comment by Megachip** [comment]
> In that case, are you sure your web server is listening on https port on loopback interface ? You can check output of: `netstat -tlnp`

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:62354           0.0.0.0:*               LISTEN      182043/glpi-agent:  
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1037/sshd           
tcp        0      0 127.0.0.1:2019          0.0.0.0:*               LISTEN      36884/caddy         
tcp6       0      0 :::80                   :::*                    LISTEN      36884/caddy         
tcp6       0      0 :::22                   :::*                    LISTEN      1037/sshd           
tcp6       0      0 :::443                  :::*                    LISTEN      36884/caddy 
```
listining on all interfaces
> Also, check you don't have any firewall rule blocking access on loopback.
> You can also try to run: `curl -v https://localhost/front/inventory.php` or `wget -d https://localhost/front/inventory.php`

```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, internal error (592):
* error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
* Closing connection 0
curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
```
hmm, issues only occurs on local interface, so I'll guess its not a bug within the agent. 
Thx for help and sorry for the wrong assumption.
