### ISSUE TITLE
Wrong monitor serial number

### ISSUE THREAD

**Issue by joschi99** [glpi-project/glpi-agent#92]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

We have different monitors where the SN for different monitors is wrong or the same:
```
<MONITORS>
  <ALTSERIAL>LY7EE016638103c5851C</ALTSERIAL>
  <BASE64>AP///////wAEcjUDxQOBYyYaAQNoMBt4yk+jplVUniUNUFO/74BxT4FAgYCBwIEAlQCzANHAAjqAGHE4LUBYLEUA3QwRAAAeAAAA/QA4TB9TEQAKICAgICAgAAAA/ABWMjI2SFFMCiAgICAgAAAA/wBMWTdFRTAxNjg1MUMKAHk=</BASE64>
  <CAPTION>V226HQL</CAPTION>
  <DESCRIPTION>38/2016</DESCRIPTION>
  <MANUFACTURER>Acer Technologies</MANUFACTURER>
  <NAME>Generic PnP Monitor</NAME>
  <PORT>DisplayPort</PORT>
  <SERIAL>LY7EE016851C</SERIAL>
  <TYPE>Generic PnP Monitor</TYPE>
</MONITORS>

<MONITORS>
  <ALTSERIAL>LY7EE016638103e2851C</ALTSERIAL>
  <BASE64>AP///////wAEcjUD4gOBYyYaAQNoMBt4yk+jplVUniUNUFO/74BxT4FAgYCBwIEAlQCzANHAAjqAGHE4LUBYLEUA3QwRAAAeAAAA/QA4TB9TEQAKICAgICAgAAAA/ABWMjI2SFFMCiAgICAgAAAA/wBMWTdFRTAxNjg1MUMKAFw=</BASE64>
  <CAPTION>V226HQL</CAPTION>
  <DESCRIPTION>38/2016</DESCRIPTION>
  <MANUFACTURER>Acer Technologies</MANUFACTURER>
  <NAME>Generic PnP Monitor</NAME>
  <PORT>DisplayPort</PORT>
  <SERIAL>LY7EE016851C</SERIAL>
  <TYPE>Generic PnP Monitor</TYPE>
</MONITORS>
```
 as you can see for this 2 monitors the filed SERIAL contains the same serial number, the correct serial number in this case will be on ALTSERIAL, but this ALTSERIAL will not be considered.

This issue could be related maybe to the following tickets:

- https://github.com/glpi-project/glpi-agent/issues/41
- https://github.com/fusioninventory/FusionInventory/issues/41

### To reproduce

launch inventory using this kind of monitors

### Expected behavior

Create a asset for every monitor

### Operating system

Windows

### GLPI Agent version

1.1

### GLPI version

9.5.6

### GLPIInventory plugin or FusionInventory for GLPI plugin version

9.5+3.0

**Comment by joschi99** [comment]
This seem's a know problem with acer

- https://www.lansweeper.com/forum/yaf_postst12184_Acer-monitors.aspx#post44180
- https://github.com/fusioninventory/fusioninventory-for-glpi/issues/875
- https://knowledge.broadcom.com/external/article/156754/inventory-reports-incomplete-serial-numb.html

**Comment by g-bougard** [comment]
Hi @joschi99 

you're right the real problem is related to few manufacturers who don't respect some standards.

Actually I can say you're issue could be worked-around with a feature on GLPI side a requested there: glpi-project/glpi#10165
As you're concerned you can add a +1 on this feature request. Maybe this could be implemented in a future GLPI 10 version.
The advantage of my feature request would be to limit agent maintenance in the future and leave users the choice to fix the problem with few actions.

Actually, I need to update the agent to support your `V226HQL` model but also all models reported in fusioninventory/FusionInventory#41

**Comment by joschi99** [comment]
Hi @g-bougard,
I think that your request https://github.com/glpi-project/glpi/issues/10165 could be a very good solution to solve this problems. I have done a research and seems that also some other producer outside Acer are not 100% compliant with EDID.

Do you think that in the meantime it could be possible that for the Acer models like V226HQL and others the agent could send the ALTSERIAL as serial number, so that inventory could work?

**Comment by g-bougard** [comment]
Hi @joschi99 

next nightly will support your V226HQL Acer model... and much more ;-)
