### ISSUE TITLE
Scan MYSQL database

### ISSUE THREAD

**Issue by EC2311** [glpi-project/glpi-agent#97]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

mysql database not scanned

### To reproduce

scan run by agent and sent to server
The agent is on a laptop with mysql (and glpi;) ) on it. (localhost)

The file generated by agent doesn't content the database hosted by the laptop

### Expected behavior

The agent should scan the database mysql

### Operating system

Windows

### GLPI Agent version

1.2

### GLPI version

10.0.0-rc3

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.0-rc7

### Additional context

perhaps to close the https://github.com/glpi-project/glpi/issues/11272 topic if it's an agent problem

**Comment by g-bougard** [comment]
Hi @EC2311 

can you try to run a database partial inventory and report the obtained output running the following command as root ?
```
glpi-inventory --debug --debug --partial=database
```

Anyway, if the database requires an authentication, you also should create a `/root/.my.cnf` file with the requested credentials.

**Comment by EC2311** [comment]
Hi @g-bougard 

Here is what I see in the output (extract) about database topic : 
![image](https://user-images.githubusercontent.com/42341169/164166144-8f477ca4-92d7-47e6-95f2-2f725c924baa.png)
and
![image](https://user-images.githubusercontent.com/42341169/164166351-7cec5bbc-cbb7-4490-859b-e615cecd51c7.png)

![image](https://user-images.githubusercontent.com/42341169/164167139-37376066-ed78-4bf6-bc6d-80f6ecdabb7b.png)

You speak about the .my.cnf file : where is it ? and what about the content we should set ?

thanks

**Comment by g-bougard** [comment]
Sorry, I missed the "Operating system: Windows" in your issue description and I thought you were talking about a linux server as this is the more usual case.
I have really poor knownledge for MySQL support on windows. What I can tell you is the MySQL module will only be triggered if "mysql" command is found in the system PATH. If you know the standard installation path for the command, maybe I can propose you a patch to test. You can also explain how you installed MySQL so I can try to reproduce.

About the Oracle case, can you confirm you also installed an Oracle server on the same computer ? The module should have been triggered as it detected the "sqlplus" command. Is this command can be related to another tool or database system on your windows system ? The module has only been develop for unix system in mind so it fails on the expected path not compatible with windows system.

**Comment by EC2311** [comment]
ok : i thought the glpi-agent and the glpi was able to detect any kind of database natively : so there are still some modules to create/check ;) : that's why I don't see any database for my laptop :) 

Mysql : As for me, mysql was installed with wampserver installation. I dont' know if mysql command is in the general path. 
Anyway, to know if a database is installed I would check the installation program, not only the path (perhaps to check in the list of softwares scanned/listed by the agent itself ?)  I think a confile will be needed to store password too...

Oracle : I have no oracle database on my laptop. But i have an ODBC driver to link to external oracle database.. So for me the scan oracle database should n't run.

**Comment by g-bougard** [comment]
No tool can detect any kind of database natively as there's no standard way to detect any kind of database. So yes, modules must be created which are really specific to each database kind.

For the mysql case, on windows, mysql command should not be in the general path so the module is not activated as your log is showing.
Do you see MySQL software in your own software inventory ? If yes, can you report the inventory entry ? This can just help to understand how it is installed and can give me a way to reproduce your installation without the need to install a full WAMP system.

About Oracle, can you check where "sqlplus" command is in your system ? How did you install the ODBC driver ? I probably need to reproduce the case to avoid the error.

**Comment by EC2311** [comment]
Mysql : it had been installed with wampserver
![image](https://user-images.githubusercontent.com/42341169/164187643-4e4d7be7-3d8c-48e4-803a-a58cfe9e834a.png)
and the only 'mysql' package I see is the connector (like oracle)
![image](https://user-images.githubusercontent.com/42341169/164187896-f8a393bc-64db-40ab-a9a4-63c387715711.png)

wamp is a global tool which install apache, mysql (or mariadb), and php binary together : I think the discovery must take care of this software as the possibility having mysql or mariadb database.
 
Oracle : I have "client oracle 9i" on my laptop : but I have no oracle db on my laptop... Perhaps sqlplus is installed together with the client : I am searching for sqlplus*.* on laptop 

mariadb : no mariadb on my laptop

**Comment by g-bougard** [comment]
Have you checked for a mariadb package ?

**Comment by EC2311** [comment]
How is the mysql module is setting as "disabled" ?
![image](https://user-images.githubusercontent.com/42341169/164203454-2ba4662f-ee44-4731-bbb6-f5f79017d594.png)

I will try to check it and configure it with my databases mysql 

where must we put the credential file ?
![image](https://user-images.githubusercontent.com/42341169/164204513-bfef5c35-1fe1-49e8-9eac-e2c1c1af4dd3.png)

thanks

**Comment by EC2311** [comment]
About oracle : I have the command sqlplus with the client oracle. but I have no Oracle database on my pc ... -> so the script is running because it finds the sqlplus command... but he would find nothing on oracle database...or perhaps samples db given with the client... ?

**Comment by g-bougard** [comment]
Hi @EC2311 

for MySQL, the module is disabled as it doesn't detect "mysql" command in the system "PATH".
MySQL has a standard way to create credentials: on unix, this is the `~/.my.cnf` file, I don't know right now for windows.

About Oracle, if you have the Oracle client, and it setup the system with "sqlplus" command in the system PATH, this is normal the agent enabled the module. The module will try the default credentials and won't report any database if nothing is setup. The Oracle client is not providing any database, only Oracle "server" provides database.

**Comment by EC2311** [comment]
Hi @g-bougard 

Mysql : 
Is there a way to run mysql module 'alone' ?
You mean that the credential file is automatically created by the script itself ? or must we provide it ? what is the template ?

Oracle : 
always the same error 
![image](https://user-images.githubusercontent.com/42341169/164392363-61716a6f-bcf1-481d-a15d-52bc866a9f61.png)
and i don't know if it is normal

thanks

**Comment by g-bougard** [comment]
The only actual way to enable the module is to modify the system PATH to include the folder where mysql command has been installed.
No credential file is created by the module and only you know how to access your database. So this is up to you to create the file where mysql command expects it.

Oracle module is actually not supported on windows. You can just ignore the error as you don't have any Oracle database on the server. I'll modify the module in nightly and next version so it should work on windows.

**Comment by EC2311** [comment]
Hi @g-bougard 

I updated the Path in my windows : ok
![image](https://user-images.githubusercontent.com/42341169/164611530-78ceb9f7-5c05-4830-bafa-44dd77f014ac.png)
Mysql scans 

but as you can see it tries 'default credentials' 

If you can tell me how and where the module tries to search for the personnal credentials : I don't understand 
![image](https://user-images.githubusercontent.com/42341169/164614425-392fa73d-c330-46dc-aee6-fb87e18592c8.png)

Thanks

**Comment by g-bougard** [comment]
For the default credentials file path, I guess it can depend on your MySQL installation.
I'm not a MySQL DBA admin on windows, so I don't know right now if there's even only one possibility.
Can you tell which path you add to your PATH ?
This can help me to reproduce the same environment then yours.

Also, I forgot to tell you, for testing, you can use the following command:
```
glpi-inventory --debug --debug --partial=database --credentials=use:mysql,type:login_password,login:USER,password:PASSWORD
```
Of course setting USER & PASSWORD to your credentials.

**Comment by EC2311** [comment]
I added this path
![image](https://user-images.githubusercontent.com/42341169/164645931-81133625-6b24-4ef4-9a42-aa892cede0a2.png)
then the mysql module run

and with your command : he succeeds in scanning the mysql database :) and the result are ok (with the credentials)

so the only problem is to know where the 'module mysql' searchs for the credentials or how to push them ...

**Comment by g-bougard** [comment]
Maybe this stackoverflow thread can help you: https://stackoverflow.com/questions/1712646/i-can-not-find-my-cnf-on-my-windows-computer
Looking at your mysql path, is there a `C:\wamp64\bin\mysql\mysql5.7.31\my.cnf` file ?
If not, maybe creating one with the following content can do the job:
```
[client]
user     = USER
password = PASSWORD
```
It seems also `%WINDIR%\my.cnf` (aka `C:\Windows\my.cnf`) and `C:\my.cnf` are valid paths. Using one of them will preserve credentials across upgrades.
This is also explained in [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/option-files.html).

Anyway, looking at you path, I don't see how the agent can safely guess where to look for mysql command on windows.

**Comment by EC2311** [comment]
I created (for the moment) a cnf file in my path with credentials.
I run the command glpi-inventory --debug --debug --partial=database -> the scan database is ok :)
(I think that due to wamp isntallation, and as it's a default installation : password and user are not set in my.ini file. And I don't know if the perl module scan in my.ini file ?) : but my.cnf is ok.

and 
i run the command glpi-inventory.bat -> the scan of database is not run (module disabled?)
![image](https://user-images.githubusercontent.com/42341169/164682619-d7458b6d-63c3-4f44-8068-f54c837b8ae2.png)

perhaps due to that  ?
![image](https://user-images.githubusercontent.com/42341169/164705290-0e5013ee-ac7f-44b5-9dde-b6aaaedfc82e.png)
but in no-category : empty...
![image](https://user-images.githubusercontent.com/42341169/164705254-21e6f611-53f7-46e8-8d49-8c752f284da4.png)

**Comment by g-bougard** [comment]
Hi @EC2311 

indeed, the database inventory is only done when JSON format inventory is used. This happens when glpi-agent service is communicating with a GLPI 10 server. This also happens when `--partial` option is used. When running glpi-inventory to obtain a full inventory, it will by default produce a XML file, unless you use `--json` option.

So try `--json` option and you should be good.

**Comment by g-bougard** [comment]
Hi @EC2311 
I'm closing the issue. I hope you found your way to make mysql database inventory.
Feel free to reopen.
