### ISSUE TITLE
macOS: Perl error when execute manual inventory on APFS (Case Sensitive) file system

### ISSUE THREAD

**Issue by M3t4Data** [glpi-project/glpi-agent#99]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Perl error after execution of manual inventory with glpi-agent perl script:
```
$ sudo /Applications/GLPI-Agent/bin/glpi-agent 

Can't locate GLPI/Agent.pm in @INC (you may need to install the GLPI::Agent module) (@INC contains: /Applications/GLPI-Agent/agent /Applications/GLPI-Agent/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level /Applications/GLPI-Agent/lib/perl5/site_perl/5.34.0 /Applications/GLPI-Agent/agent/darwin-thread-multi-2level /Applications/GLPI-Agent/lib/darwin-thread-multi-2level /Applications/GLPI-Agent/lib) at /Applications/GLPI-Agent/bin/glpi-agent line 12.
BEGIN failed--compilation aborted at /Applications/GLPI-Agent/bin/glpi-agent line 12.
```
The service org.glpi-project.glpi-agent not run, /var/log/system.log return:
`Service exited with abnormal code: 2`

### To reproduce

1. Install package GLPI-Agent-1.2_x86_64.pkg on macOS with APFS (Case Sensitive) file system
2. Update config file `/Application/GLPI-Agent/etc/agent.cfg` with the good server URL
3. Restart the GLPI Agent service
4. Execute glpi-agent script `/Applications/GLPI-Agent/bin/glpi-agent `

### Expected behavior

Inventory sended succesfully to GLPI after manual execution of glpi-agent script.
The service run succesfully.

### Operating system

MacOSX

### GLPI Agent version

1.2

### GLPI version

Not applicable

**Comment by g-bougard** [comment]
Hi @M3t4Data 

thank you for your report.

This is maybe a packaging issue.

To fix your problem, can you rename `/Applications/GLPI-Agent/agent/Glpi` to `/Applications/GLPI-Agent/agent/GLPI` as root ?

**Comment by M3t4Data** [comment]
I made the modification, the inventory script runs without error, the service starts correctly and the inventory is sended correctly too.
Thank you for your quick response !

**Comment by g-bougard** [comment]
Hi @M3t4Data 
I finally found my way on that issue. That was a weird side effect: as the package name was set to `Glpi-Perl-Agent`, a `Glpi/Perl` folder was created before a `GLPI` one during the perl module installation... This wouldn't have been a problem if the building system still was case sensitive.
Anyway, big thank you for your reporting.
Next nightly will include the fix.
